import { ApiError, getErrorMessage } from "@/lib/errors";
import type { Messages } from "@/i18n/LocaleContext";

/** The words of the courier settlements page (/settlements): what couriers hold, the settlements, and the two sheets. */
export const SETTLEMENT_STRINGS = {
  en: {
    title: "COD settlements",
    description: "Match the cash couriers collected on delivered orders with what they actually transferred to you.",
    answerDue: "Couriers still owe you {amount} for {orders} delivered.",
    answerClear: "No money is waiting with the couriers right now.",
    record: "Record a transfer",
    tools: "Settlement tools",
    importStatement: "Import a courier statement",
    importHint: "Match the courier's Excel or CSV file to your orders",
    refresh: "Refresh",
    refreshHint: "Ask again for what couriers hold and the settlements",

    kpiDue: "Due from couriers",
    kpiDueHint: "For {orders} delivered and not settled",
    kpiDueNone: "Nothing is waiting",
    kpiReceived: "Received",
    kpiReceivedHint: "Net of the confirmed settlements",
    kpiFees: "Courier fees",
    kpiFeesHint: "Taken off in the confirmed settlements",
    kpiDrafts: "Draft settlements",
    kpiDraftsHint: "Waiting for you to confirm",
    kpiDraftsNone: "No draft is waiting",

    viewLabel: "What the page shows",
    viewHeld: "With couriers",
    viewSettlements: "Settlements",

    heldLabel: "Money held, courier by courier",
    colCourier: "Courier",
    daysBand: "{from}–{to} days",
    daysOver: "Over {n} days",
    colTotal: "Total held",
    colAction: "Next step",
    ordersOldest: "{orders} · oldest delivery {date}",
    lateChip: "{amount} over {n} days",
    onTime: "Nothing over {n} days",
    inDraft: "In a draft, waiting to be confirmed",
    recordFor: "Record what {courier} paid you",
    noUnsettled: "No unsettled COD orders",
    noUnsettledDesc: "Delivered cash-on-delivery orders show up here until the courier pays you for them.",
    seeOrders: "See the orders",

    chipsLabel: "Settlements by status",
    chipAll: "All",
    chipDraft: "Drafts",
    chipConfirmed: "Confirmed",
    status_draft: "Draft",
    status_confirmed: "Confirmed",
    colDate: "Created",
    colStatus: "Status",
    colCollected: "Collected",
    colFees: "Fees",
    colNet: "Net",
    confirmShort: "Confirm",
    peek: "Open the settlement of {courier}, {date}",
    menuLabel: "Actions for this settlement",
    menuOpen: "Open the settlement",
    menuCopyRef: "Copy the reference",
    copiedRef: "The reference is copied",
    noSettlements: "No settlements yet",
    noSettlementsDesc: "A settlement records what a courier transferred to you for the orders it delivered.",
    noDrafts: "No draft is waiting to be confirmed",
    noConfirmed: "No settlement is confirmed yet",
    showAll: "Show all settlements",

    detailTitle: "Settlement · {carrier}",
    reference: "Reference",
    period: "Period",
    periodRange: "{from} – {to}",
    createdOn: "Created",
    confirmedOn: "Confirmed",
    notes: "Notes",
    linesTitle: "Orders in it",
    lineOf: "of",
    orderGone: "Deleted order",
    openOrder: "Open order {number}",
    confirm: "Confirm settlement",
    delete: "Delete draft",
    confirmTitle: "Confirm this settlement?",
    confirmDesc:
      "This records the collected amount as a payment on every order in it and marks them paid. A confirmed settlement can't be edited or deleted.",
    confirmed: "Settlement confirmed",
    deleteTitle: "Delete this draft?",
    deleteDesc: "The orders go back to the unsettled list. Nothing is recorded on them.",
    deleted: "Draft deleted",

    reconcileTitle: "Record a transfer",
    reconcileTitleFor: "What {courier} paid you",
    reconcileDesc: "Tick the orders the courier paid you for and fix an amount where it differs. It is saved as a draft: nothing is recorded on the orders until you confirm it.",
    chooseCourier: "Which courier paid you?",
    feePerOrder: "Fee per order",
    applyFee: "Apply to selected",
    selectAll: "Select all",
    selectOrder: "Select order {number}",
    selectedCount_one: "1 selected",
    selectedCount_other: "{n} selected",
    due: "Due",
    waybill: "Waybill",
    partOfOrder: "Part of order",
    delivered: "Delivered",
    collected: "Collected",
    courierFee: "Courier fee",
    totalsLine: "{count} · collected {collected} · fees {fees}",
    createDraft: "Create draft settlement",
    creating: "Saving…",
    draftCreated: "Draft settlement saved",
    invalidAmount: "Type the amount in digits only.",
    exceedsDue: "More than what's due on this order ({due}).",
    invalidFee: "Type the fee in digits only, or leave it empty.",

    errNotSettleable: "One of the orders can't be settled anymore — refresh and try again.",
    errDuplicate: "An order is on this settlement twice.",
    errExceeds: "A collected amount is more than what's due on its order.",
    errConfirmed: "This settlement is already confirmed and can't be changed.",
    errEmpty: "This settlement has no orders.",
  },
  ar: {
    title: "تحصيل شركات الشحن",
    description: "طابق الفلوس اللي شركات الشحن حصّلتها من الأوردرات اللي اتسلّمت مع اللي حوّلوهولك فعلاً.",
    answerDue: "شركات الشحن لسه عليها {amount} عن {orders} اتسلّموا.",
    answerClear: "مفيش فلوس متأخرة عند شركات الشحن دلوقتي.",
    record: "سجّل تحويل",
    tools: "أدوات التحصيل",
    importStatement: "استورد كشف شركة الشحن",
    importHint: "طابق ملف Excel أو CSV بتاع شركة الشحن مع أوردراتك",
    refresh: "حدّث",
    refreshHint: "هات تاني اللي عند شركات الشحن والتسويات",

    kpiDue: "عند شركات الشحن",
    kpiDueHint: "عن {orders} اتسلّموا ولسه متسوّوش",
    kpiDueNone: "مفيش حاجة مستنية",
    kpiReceived: "اللي وصلك",
    kpiReceivedHint: "صافي التسويات المتأكدة",
    kpiFees: "مصاريف الشحن",
    kpiFeesHint: "اتخصمت في التسويات المتأكدة",
    kpiDrafts: "تسويات مسودة",
    kpiDraftsHint: "مستنية تأكيدك",
    kpiDraftsNone: "مفيش مسودة مستنية",

    viewLabel: "الصفحة بتعرض إيه",
    viewHeld: "عند شركات الشحن",
    viewSettlements: "التسويات",

    heldLabel: "الفلوس اللي عند كل شركة شحن",
    colCourier: "شركة الشحن",
    daysBand: "{from}–{to} يوم",
    daysOver: "أكتر من {n} يوم",
    colTotal: "الإجمالي",
    colAction: "الخطوة الجاية",
    ordersOldest: "{orders} · أقدم تسليم {date}",
    lateChip: "{amount} فاتوا {n} يوم",
    onTime: "مفيش حاجة فاتت {n} يوم",
    inDraft: "في مسودة مستنية تأكيدك",
    recordFor: "سجّل اللي {courier} دفعته",
    noUnsettled: "مفيش أوردرات دفع عند الاستلام محتاجة تسوية",
    noUnsettledDesc: "الأوردرات اللي اتسلّمت بتفضل هنا لحد ما شركة الشحن تحوّلك فلوسها.",
    seeOrders: "شوف الأوردرات",

    chipsLabel: "التسويات حسب الحالة",
    chipAll: "الكل",
    chipDraft: "مسودات",
    chipConfirmed: "متأكدة",
    status_draft: "مسودة",
    status_confirmed: "متأكدة",
    colDate: "اتعملت",
    colStatus: "الحالة",
    colCollected: "المحصّل",
    colFees: "المصاريف",
    colNet: "الصافي",
    confirmShort: "أكّد",
    peek: "افتح تسوية {courier}، {date}",
    menuLabel: "إجراءات التسوية",
    menuOpen: "افتح التسوية",
    menuCopyRef: "انسخ المرجع",
    copiedRef: "المرجع اتنسخ",
    noSettlements: "مفيش تسويات لسه",
    noSettlementsDesc: "التسوية بتسجّل اللي شركة الشحن حوّلتهولك عن الأوردرات اللي سلّمتها.",
    noDrafts: "مفيش مسودة مستنية تأكيد",
    noConfirmed: "لسه مفيش تسوية اتأكدت",
    showAll: "اعرض كل التسويات",

    detailTitle: "تسوية · {carrier}",
    reference: "المرجع",
    period: "الفترة",
    periodRange: "{from} – {to}",
    createdOn: "اتعملت",
    confirmedOn: "اتأكدت",
    notes: "ملاحظات",
    linesTitle: "الأوردرات اللي فيها",
    lineOf: "من",
    orderGone: "أوردر ممسوح",
    openOrder: "افتح الأوردر {number}",
    confirm: "أكّد التسوية",
    delete: "امسح المسودة",
    confirmTitle: "تأكّد التسوية دي؟",
    confirmDesc: "ده هيسجّل المبلغ المحصّل كدفعة على كل أوردر فيها ويعلّمهم مدفوعين. التسوية المتأكدة مينفعش تتعدّل أو تتمسح.",
    confirmed: "التسوية اتأكدت",
    deleteTitle: "تمسح المسودة دي؟",
    deleteDesc: "الأوردرات هترجع لقايمة اللي لسه متسوّوش ومش هيتسجّل عليها حاجة.",
    deleted: "المسودة اتمسحت",

    reconcileTitle: "سجّل تحويل",
    reconcileTitleFor: "اللي {courier} دفعته",
    reconcileDesc: "علّم على الأوردرات اللي شركة الشحن دفعتلك تمنها وعدّل المبلغ لو مختلف. بتتحفظ مسودة: مفيش حاجة بتتسجّل على الأوردرات غير لما تأكّدها.",
    chooseCourier: "أنهي شركة شحن دفعتلك؟",
    feePerOrder: "المصاريف لكل أوردر",
    applyFee: "طبّق على المتحدد",
    selectAll: "حدّد الكل",
    selectOrder: "حدّد الأوردر {number}",
    selectedCount_one: "واحد متحدد",
    selectedCount_two: "اتنين متحددين",
    selectedCount_few: "{n} متحددين",
    selectedCount_other: "{n} متحدد",
    due: "المستحق",
    waybill: "بوليصة",
    partOfOrder: "جزء من الطلب",
    delivered: "اتسلّم",
    collected: "المحصّل",
    courierFee: "مصاريف الشحن",
    totalsLine: "{count} · محصّل {collected} · مصاريف {fees}",
    createDraft: "احفظ مسودة تسوية",
    creating: "بنحفظ…",
    draftCreated: "مسودة التسوية اتحفظت",
    invalidAmount: "اكتب المبلغ أرقام بس.",
    exceedsDue: "أكتر من المستحق على الأوردر ده ({due}).",
    invalidFee: "اكتب المصاريف أرقام بس، أو سيبها فاضية.",

    errNotSettleable: "أوردر من الأوردرات مبقاش ينفع يتسوّى — حدّث وجرّب تاني.",
    errDuplicate: "فيه أوردر متكرر في التسوية دي.",
    errExceeds: "فيه مبلغ محصّل أكتر من المستحق على الأوردر بتاعه.",
    errConfirmed: "التسوية دي متأكدة خلاص ومينفعش تتغيّر.",
    errEmpty: "التسوية دي مفيهاش أوردرات.",
  },
} satisfies Messages;

export type SettlementStrings = (typeof SETTLEMENT_STRINGS)["en"];

/** How late a courier may be before the page says so. */
export const LATE_DAYS = 14;

/** A refusal of the settlements API in the merchant's words; anything else as the dashboard words it. */
export function settlementErrorText(err: unknown, t: SettlementStrings): string {
  if (err instanceof ApiError) {
    if (err.code === "ORDER_NOT_SETTLEABLE") return t.errNotSettleable;
    if (err.code === "DUPLICATE_ORDER") return t.errDuplicate;
    if (err.code === "COLLECTED_EXCEEDS_DUE") return t.errExceeds;
    if (err.code === "SETTLEMENT_CONFIRMED") return t.errConfirmed;
    if (err.code === "SETTLEMENT_EMPTY") return t.errEmpty;
  }
  return getErrorMessage(err);
}
