import type { EditorLocale } from "./editorLocale";

/**
 * The starting copy of the block library's presets (blocks.ts) in the editor's
 * language. The presets are written in Arabic — prompts to the merchant
 * ("اكتب هنا…"), never claims — and an English editor gets these English
 * prompts instead; the element types' own English defaults ("New heading")
 * get Arabic ones in an Arabic editor. Either way it is text the merchant
 * replaces, so a string missing here just stays as written.
 */
const PRESET_COPY_EN: Record<string, string> = {
  "الأسئلة الشائعة": "Frequently asked questions",
  "ينتهي العرض خلال": "Offer ends in",
  "اكتب هنا…": "Write here…",
  "اكتب هنا الجملة التي تريد أن يراها كل زائر أولًا": "Write the line you want every visitor to see first",
  "اكتب هنا جملة تصف متجرك في سطر واحد": "Write one line that describes your store",
  "اشرح في سطرين ماذا تبيع ولمن، واترك الباقي للمنتجات.": "Say in two lines what you sell and who it's for — let the products do the rest.",
  "تسوّق الآن": "Shop now",
  "اكتب هنا أول سبب يجعل العميل يثق بك": "Write the first reason a customer can trust you",
  "اكتب هنا سياسة الاستبدال أو الضمان لديك": "Write your exchange or warranty policy",
  "اكتب هنا طريقة تواصلك مع العملاء": "Write how customers can reach you",
  "اشرح في سطرين ماذا تبيع ولمن، واترك الباقي للصورة.": "Say in two lines what you sell and who it's for — let the picture do the rest.",
  "اكتب هنا عنوان الواجهة": "Write your headline here",
  "اكتب سطرًا واحدًا يوضّح ما يميّز متجرك.": "Write one line on what sets your store apart.",
  "اكتب هنا عنوان الفيديو": "Write the video's title",
  "اكتب سطرًا يخبر العميل بما سيراه في الفيديو.": "Write a line telling customers what the video shows.",
  "اكتب هنا جملة قصيرة عن خدمتك": "Write a short line about your service",
  "اكتب هنا جملة ثانية": "Write a second line",
  "اكتب هنا جملة ثالثة": "Write a third line",
  "اكتب هنا عنوانًا قصيرًا": "Write a short title",
  "اكتب هنا نقطة الثقة": "Write the trust point",
  "اكتب تفاصيلها في سطر.": "Explain it in one line.",
  "آراء العملاء": "Customer reviews",
  "اكتب سطرًا عن مصدر هذه الآراء.": "Write a line about where these reviews come from.",
  "ماذا يقولون عنا": "What people say about us",
  "قارن بنفسك": "Compare for yourself",
  "لدينا": "With us",
  "في مكان آخر": "Elsewhere",
  "اكتب هنا النقطة التي تقارن فيها": "Write the point you're comparing",
  "اكتب هنا ما تقدّمه": "Write what you offer",
  "اكتب هنا البديل": "Write the alternative",
  "اكتب هنا نقطة ثانية": "Write a second point",
  "اكتب هنا نقطة ثالثة": "Write a third point",
  "اكتب سطرًا يخبر العميل بما ينظر إليه في الجدول.": "Write a line telling customers what to look for in the table.",
  "منتجات أخرى قد تعجبك": "You might also like",
  "تسوّق حسب المجموعة": "Shop by collection",
  "اكتب سطرًا يساعد العميل على اختيار نقطة البداية.": "Write a line that helps customers pick where to start.",
  "لماذا هذا المنتج؟": "Why this product?",
  "اكتب هنا السبب الأول": "Write the first reason",
  "اكتب هنا السبب الثاني": "Write the second reason",
  "اكتب هنا السبب الثالث": "Write the third reason",
  "عرض كل المنتجات": "See all products",
  "اكتب هنا عنوان المجموعة": "Write the collection's title",
  "اكتب سطرًا عن هذه المنتجات.": "Write a line about these products.",
  "عروض وباقات": "Offers and bundles",
  "اشرح في سطر ما تتضمنه الباقة وما شروطها.": "Explain in one line what's in the bundle and its terms.",
  "عرض كل العروض": "See all offers",
  "اختر العرض المناسب لك": "Pick the offer that suits you",
  "اكتب سطرًا يوضّح الفرق بين العروض الثلاثة.": "Write a line on how the three differ.",
  "أدِره بإصبعك": "Spin it with your finger",
  "اكتب سطرًا يشجّع العميل على تقليب المنتج بنفسه.": "Write a line inviting customers to turn the product around themselves.",
  "اختر من مجموعتنا": "Choose from our collection",
  "لماذا تختارنا": "Why choose us",
  "اكتب سطرًا تمهيديًا قصيرًا عمّا تقدّمه.": "Write a short intro line about what you offer.",
  "اكتب الميزة الأولى": "Write the first feature",
  "اكتب الميزة الثانية": "Write the second feature",
  "اكتب الميزة الثالثة": "Write the third feature",
  "اكتب الميزة الرابعة": "Write the fourth feature",
  "لماذا تشتري منّا؟": "Why buy from us?",
  "اكتب هنا ما يقلق العميل قبل الشراء": "Write what worries customers before they buy",
  "اكتب هنا إجابتك أنت — دون مقارنة بأحد بالاسم.": "Write your own answer — without naming anyone to compare with.",
  "اكتب هنا نقطة ثانية تميّزك": "Write a second point that sets you apart",
  "اكتب هنا تفاصيلها.": "Write the details.",
  "اشرح هذه الميزة في سطر أو سطرين.": "Explain this feature in a line or two.",
  "اشرحها في سطر.": "Explain it in one line.",
  "اكتب هنا عنوان هذا الجزء": "Write this part's title",
  "اكتب فقرة قصيرة عن هذه الصورة — منتج، أو قصة، أو طريقة عمل.": "Write a short paragraph about this picture — a product, a story or how it's made.",
  "اعرف المزيد": "Learn more",
  "اكتب هنا اسم الخطوة الأولى": "Write the first step's name",
  "اكتب سطرين يشرحان هذه الخطوة ولماذا هي مهمة.": "Write two lines on this step and why it matters.",
  "اكتب هنا اسم الخطوة الثانية": "Write the second step's name",
  "قبل وبعد": "Before and after",
  "قبل": "Before",
  "اكتب هنا وصف الحال قبل المنتج، وارفع صورته.": "Describe how things were before the product, and upload a picture.",
  "بعد": "After",
  "اكتب هنا وصف الحال بعد المنتج، وارفع صورته.": "Describe how things are after the product, and upload a picture.",
  "كيف يُصنع؟": "How it's made",
  "اكتب سطرًا يمهّد للخطوات التالية.": "Write a line introducing the steps below.",
  "اكتب عنوان الخطوة الأولى": "Write the first step's title",
  "اكتب هنا وصفها، وارفع صورتها.": "Describe it here, and upload its picture.",
  "اكتب عنوان الخطوة الثانية": "Write the second step's title",
  "اكتب عنوان الخطوة الثالثة": "Write the third step's title",
  "اكتب الرقم": "Write the number",
  "اكتب هنا ما يعبّر عنه هذا الرقم.": "Write what this number counts.",
  "كيف يعمل؟": "How it works",
  "اكتب سطرًا يمهّد للخطوات.": "Write a line introducing the steps.",
  "١": "1",
  "٢": "2",
  "٣": "3",
  "اشرح هذه الخطوة في سطر أو سطرين.": "Explain this step in a line or two.",
  "قصتنا": "Our story",
  "اكتب سطرًا عن رحلتك منذ البداية حتى الآن.": "Write a line about your journey from the start until now.",
  "البداية": "The beginning",
  "اكتب هنا المحطة الأولى وتاريخها": "Write the first milestone and its date",
  "اكتب هنا المحطة الثانية": "Write the second milestone",
  "الآن": "Today",
  "اكتب هنا محطة حديثة": "Write a recent milestone",
  "اكتب هنا ما هو قادم": "Write what's next",
  "الفريق": "The team",
  "اكتب سطرًا عمّن يقف وراء المتجر.": "Write a line about who's behind the store.",
  "اكتب هنا اسم الشخص": "Write the person's name",
  "اكتب هنا دوره في سطر.": "Write their role in one line.",
  "كتالوج الإطلالات": "Lookbook",
  "اكتب سطرًا عن هذه المجموعة، وارفع صورها بالأسفل.": "Write a line about this collection, and upload its pictures below.",
  "اكتب هنا أهم ميزة لديك": "Write your most important feature",
  "اشرحها في سطرين أو ثلاثة — هذه البطاقة عريضة لأنها للكلام الأهم.": "Explain it in two or three lines — this card is wide because it holds what matters most.",
  "اكتب هنا ميزة ثانية": "Write a second feature",
  "اكتب هنا ميزة ثالثة": "Write a third feature",
  "اكتب هنا ميزة رابعة": "Write a fourth feature",
  "اشرحها في سطرين أو ثلاثة.": "Explain it in two or three lines.",
  "اكتب هنا عنوان القصة": "Write the story's title",
  "اكتب هنا الفقرة الطويلة — كيف بدأت، وماذا تفعل، ولماذا تفعله.": "Write the long paragraph here — how you started, what you do and why you do it.",
  "اكتب سطرًا يخبر العميل بما سيجده هنا، وكيف يصل إليك إن لم يجد سؤاله.": "Write a line telling customers what they'll find here, and how to reach you if their question isn't listed.",
  "اكتب هنا سؤالًا يتكرر من العملاء": "Write a question customers often ask",
  "اكتب هنا إجابتك.": "Write your answer.",
  "اكتب هنا سؤالًا ثانيًا": "Write a second question",
  "اكتب هنا سؤالًا ثالثًا": "Write a third question",
  "هل ما زال لديك سؤال؟ نحن هنا.": "Still have a question? We're here.",
  "تواصل معنا": "Contact us",
  "الشحن والاستبدال": "Shipping and exchanges",
  "الشحن": "Shipping",
  "اكتب هنا مناطق الشحن ومواعيده وتكلفته.": "Write where you ship, when and at what cost.",
  "الاستبدال والاسترجاع": "Exchanges and returns",
  "اكتب هنا سياسة الاستبدال والاسترجاع لديك.": "Write your exchange and return policy.",
  "الدفع": "Payment",
  "اكتب هنا طرق الدفع التي تقبلها.": "Write the payment methods you accept.",
  "اكتب هنا أي ملاحظة أخيرة عن الطلبات.": "Write any last note about orders.",
  "اكتب هنا عنوان النموذج": "Write the form's title",
  "إرسال": "Send",
  "اكتب هنا مواعيد الرد وطرق التواصل الأخرى.": "Write when you reply and other ways to reach you.",
  "اكتب هنا دعوة للعميل ليبقى على تواصل معك": "Invite customers to keep in touch",
  "اكتب سطرًا يوضّح ما الذي سيصله وكم مرة.": "Write a line on what they'll receive and how often.",
  "اشترك": "Subscribe",
  "اكتب هنا الجملة التي تدعو العميل إلى الشراء": "Write the line that asks customers to act",
  "اكتب سطرًا يوضّح لماذا الآن.": "Write a line on why now.",
  "ابدأ الآن": "Get started",
  "عرض لفترة محدودة": "Limited-time offer",
  "اكتب هنا تفاصيل العرض ومدته وشروطه.": "Write the offer's details, how long it runs and its terms.",
  "اشترِ الآن": "Buy now",
  "اكتب هنا اسم العرض": "Write the offer's name",
  "اكتب اسم الباقة الأولى": "Write the first plan's name",
  "اكتب اسم الباقة الثانية": "Write the second plan's name",
  "اكتب اسم الباقة الثالثة": "Write the third plan's name",
  "اكتب هنا السعر ولمن هذه الباقة.": "Write the price and who this plan is for.",
  "اكتب هنا أول ما تتضمنه": "Write the first thing it includes",
  "اكتب هنا الشيء الثاني": "Write the second thing",
  "اكتب هنا الشيء الثالث": "Write the third thing",
  "اختر هذه الباقة": "Choose this plan",
  "اكتب عنوان القائمة": "Write the list's title",
  "اكتب هنا اسم صفحة": "Write a page name",
  "اكتب هنا اسم صفحة ثانية": "Write another page name",
  "اكتب هنا العرض الذي تريد أن يراه كل زائر": "Write the offer you want every visitor to see",
  "اكتب هنا سببًا ثانيًا يدفع العميل إلى المتابعة": "Write a second reason to keep shopping",
  "اكتب هنا ميزة ثالثة في سطر قصير": "Write a third benefit in a short line",
  "اشرح في سطرين ماذا تبيع ولمن، واترك الباقي للصور.": "Say in two lines what you sell and who it's for — let the pictures do the rest.",
  "تسوّق حسب القسم": "Shop by department",
  "اكتب سطرًا يساعد العميل على معرفة من أين يبدأ.": "Write a line that helps customers know where to start.",
  "صورة القسم": "Department picture",
  "تخفيضات": "Sale",
  "عروض": "Offers",
  "جاكيتات": "Jackets",
  "موضة": "Fashion",
  "إكسسوارات": "Accessories",
  "وصل حديثًا": "New arrivals",
  "منتجات مختارة": "Featured products",
  "اكتب سطرًا يوضّح لماذا اخترت هذه المنتجات تحديدًا.": "Write a line on why you picked these products.",
  "صورة العرض": "Offer picture",
  "اكتب هنا عنوان العرض الأول": "Write the first offer's title",
  "اكتب سطرًا قصيرًا عن هذا العرض.": "Write a short line about this offer.",
  "اكتب هنا عنوان العرض الثاني": "Write the second offer's title",
  "صورة المنتج": "Product picture",
  "اكتب هنا سطرًا تمهيديًا قصيرًا": "Write a short intro line",
  "اكتب هنا العنوان الرئيسي للعرض": "Write the offer's big headline",
  "اشرح في سطرين ما يُباع هنا، ولمن، ولماذا يستحق.": "Say in two lines what's on sale here, who it's for and why it's worth it.",
  "عرض التفاصيل": "See details",
  "العلامات التجارية لدينا": "Our brands",
  "من المدوّنة": "From the journal",
  "اكتب سطرًا يخبر العميل بما سيجده هنا.": "Write a line telling customers what they'll find here.",
  "صورة المقال": "Article picture",
  "اكتب هنا عنوان المقال": "Write the article's title",
  "اكتب سطرًا يلخّص المقال.": "Write a line summing up the article.",
  "أيقونة الخدمة": "Service icon",
  "الشحن والتوصيل": "Shipping and delivery",
  "اكتب هنا مدة التوصيل والمناطق التي تشحن إليها.": "Write delivery times and where you ship to.",
  "خدمة العملاء": "Customer service",
  "اكتب هنا مواعيد الخدمة وطريقة التواصل معك.": "Write your service hours and how to reach you.",
  "طرق الدفع": "Payment methods",
  "اكتب هنا وسائل الدفع المتاحة في متجرك.": "Write the payment methods your store offers.",
  "صورة البانر": "Banner picture",
  "اكتب سطرًا يصف هذه المجموعة.": "Write a line describing this collection.",
  "صورة المجموعة": "Collection picture",
  "اكتب هنا اسم القطعة": "Write the item's name",
  "اكتب هنا سطرين عن متجرك وما يقدّمه.": "Write two lines about your store and what it offers.",
  "عن المتجر": "About the store",
  "من نحن": "Who we are",
  "فروعنا": "Our branches",
  "حسابي": "My account",
  "طلباتي": "My orders",
  "المفضلة": "Wishlist",
  "وسائل الدفع": "Payment methods",
};

const ELEMENT_DEFAULTS_AR: Record<string, string> = {
  "New heading": "عنوان جديد",
  "Write something about your store.": "اكتب شيئًا عن متجرك.",
  "Gallery": "معرض الصور",
  "Shop now": "تسوّق الآن",
  "Send": "إرسال",
  "Featured products": "منتجات مختارة",
  "Shop by collection": "تسوّق حسب المجموعة",
  "Your cart": "سلتك",
};

const ARABIC_DIGITS = "٠١٢٣٤٥٦٧٨٩";

function translate(text: string, locale: EditorLocale): string {
  const table = locale === "en" ? PRESET_COPY_EN : ELEMENT_DEFAULTS_AR;
  const whole = table[text];
  if (whole !== undefined) return whole;
  // A numbered prompt ("١. اكتب عنوان الخطوة الأولى"): translate the words,
  // and give English its own digits.
  const numbered = /^([0-9٠-٩]+)\. (.+)$/.exec(text);
  if (numbered && table[numbered[2]] !== undefined) {
    const n =
      locale === "en"
        ? numbered[1].replace(/[٠-٩]/g, (d) => String(ARABIC_DIGITS.indexOf(d)))
        : numbered[1];
    return `${n}. ${table[numbered[2]]}`;
  }
  return text;
}

/** A preset element's starting props with every string in `locale`. */
export function localizePresetContent<T>(value: T, locale: EditorLocale): T {
  if (typeof value === "string") return translate(value, locale) as T;
  if (Array.isArray(value)) return value.map((v) => localizePresetContent(v, locale)) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([k, v]) => [
        k,
        // Links, image sources and option values are data, not copy.
        k === "href" || k === "src" || k === "url" || k === "variant" || k === "source" || k === "layout" || k === "tone" || k === "speed" || k === "name"
          ? v
          : localizePresetContent(v, locale),
      ])
    ) as T;
  }
  return value;
}
