import type { QuoteStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Quote requests (handoff 219, 275): the inbox, a request's page and its price editor. */
export const QUOTE_STRINGS = {
  en: {
    title: "Quotes",
    description: "Shoppers who buy in quantity ask for your price. Answer with a price per product and a date the offer holds until.",
    newBadge: "{count} new",
    filterLabel: "Filter quotes by status",
    tabAll: "All",
    tabNew: "New",
    tabNewCount: "New ({count})",
    tabQuoted: "Sent",
    tabAccepted: "Accepted",
    tabDeclined: "Declined",
    tabCancelled: "Cancelled",
    status_new: "New",
    status_quoted: "Quote sent",
    status_accepted: "Accepted",
    status_declined: "Declined",
    status_cancelled: "Cancelled",
    status_expired: "Expired",
    colRequest: "Request",
    colStatus: "Status",
    colProducts: "Products",
    colValidUntil: "Valid until",
    colReceived: "Received",
    colOrder: "Order",
    openOrder: "Open order",
    emptyNewTitle: "No new quote requests",
    emptyNewHint: "Shoppers ask for a quote from a product page or from their cart. A new request shows up here, and you get a notification.",
    emptyOtherTitle: "Nothing here",
    showAll: "Show all quotes",
    emptyAllTitle: "No quote requests yet",
    back: "Quotes",
    fallbackTitle: "Quote request",
    receivedOn: "Received {date}",
    customerTitle: "Customer",
    company: "Company",
    phone: "Phone",
    email: "Email",
    noEmail: "No email left",
    hasAccount: "Signed-in customer",
    openCustomer: "Open customer",
    messageTitle: "Their message",
    detailsTitle: "Quote",
    termsTitle: "Validity and note",
    quotedOn: "Sent",
    validUntil: "Valid until",
    order: "Order",
    notSet: "—",
    shopperLink: "Quote page link",
    shopperLinkHint: "It opens in the browser the shopper sent the request from.",
    copyLink: "Copy link",
    linesTitle: "Requested products",
    linesHintNew: "Set the price of one piece and the quantity you can supply. Leave a product out if you can't offer it.",
    linesHintQuoted: "This is what the shopper sees now. Change it and send again while they haven't answered.",
    linesHintClosed: "What was asked for, and what you offered.",
    unknownProduct: "Deleted product",
    requested: "Asked for {pieces}",
    shopperNote: "Note: {note}",
    include: "Include in the quote",
    includeName: "Include {name} in the quote",
    leftOut: "Left out of the quote",
    quantity: "Quantity",
    unitPrice: "Price per piece",
    listPrice: "Store price {price}",
    lineTotal: "Line total",
    total: "Quote total",
    totalHint: "Shipping is added to the order when the shopper accepts.",
    note: "Note to the shopper",
    noteHint: "Delivery time, payment terms, anything they should know.",
    validity: "Valid until",
    validityHint: "The shopper can accept until the end of this day.",
    send: "Send quote",
    sendAgain: "Send updated quote",
    sending: "Sending…",
    willEmail: "The shopper gets an email with a link to the quote.",
    noEmailHint: "The shopper left no email: tell them by phone or WhatsApp that the quote is ready.",
    wontEmailAgain: "The shopper isn't emailed again — they see the new prices on the quote page.",
    quantityError: "A whole number from {min} to {max}.",
    priceError: "Type the price in digits, zero or more.",
    linesError: "Include at least one product.",
    validityError: "Choose a day that hasn't passed.",
    sentToast: "Quote sent.",
    updatedToast: "Quote updated.",
    cancelQuote: "Cancel quote",
    cancelTitle: "Cancel {number}?",
    cancelBody: "The shopper can no longer accept it. This can't be undone.",
    cancelConfirm: "Cancel quote",
    keep: "Keep it",
    working: "Working…",
    cancelledToast: "Quote cancelled.",
    closedNotice: "This quote was closed meanwhile — this is how it stands now.",
    acceptedNote: "The shopper accepted. The order is cash on delivery at these prices, tagged “quote”.",
    declinedNote: "The shopper declined this quote.",
    cancelledNote: "You cancelled this quote.",
    expiredNote: "The quote passed its date without an answer. Send it again with a new date to reopen it.",
    viewOnly: "You can see quotes, but answering them needs permission to manage orders.",
    colProduct: "Product",
    colRequested: "Asked for",
    colOffered: "Offered",
    colListPrice: "Store price",
    colUnitPrice: "Your price",
    colLineTotal: "Total",
    searchLabel: "Search the quotes",
    searchPlaceholder: "Number, customer, company or phone",
    chipsLabel: "Quotes by status",
    colCustomer: "Customer",
    colContact: "Contact",
    peek: "Preview the quote of {who}",
    menuLabel: "Actions for this quote",
    menuOpen: "Open the request",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopyPhone: "Copy the number",
    menuCopyNumber: "Copy the quote number",
    copiedPhone: "The customer's number is copied",
    copiedNumber: "The quote number is copied",
    emptyNewDone: "A request waiting for your prices shows up here first.",
    emptyFilteredTitle: "No quote matches this search",
    clearSearch: "Clear the search",
    openStore: "Open your store",
    refreshFailed: "Couldn't refresh the list, so this is what was loaded last.",
    retry: "Try again",
    setPrices: "Set the prices",
    receivedAgo: "Received {when}",
    validUntilDate: "Valid until {date}",
    expiredOn: "Expired {date}",
    qlAsked: "What they asked for",
    qlLinesFailed: "We couldn't load the products of this request.",
    qlTimes: "× {n}",
    qlNotOffered: "Not offered",
    tools: "Quote tools",
    copyShopperLink: "Copy the quote page link",
    copiedShopperLink: "The quote page link is copied",
    factsSummary: "Sent {sent} · valid until {until}",
    factsSummaryNoDate: "Sent {sent}",
    reset: "Reset",
    totalLine: "Quote total",
    includedCount: "{included} of {total} in the quote",
    requestedShort: "Asked for",
  },
  ar: {
    title: "عروض الأسعار",
    description: "العملاء اللي بيشتروا كميات بيطلبوا سعرك. رد بسعر لكل منتج وتاريخ العرض صالح لحده.",
    newBadge: "{count} جديد",
    filterLabel: "فلتر عروض الأسعار بالحالة",
    tabAll: "الكل",
    tabNew: "جديد",
    tabNewCount: "جديد ({count})",
    tabQuoted: "اتبعت",
    tabAccepted: "اتقبل",
    tabDeclined: "اترفض",
    tabCancelled: "اتلغى",
    status_new: "جديد",
    status_quoted: "العرض اتبعت",
    status_accepted: "اتقبل",
    status_declined: "اترفض",
    status_cancelled: "اتلغى",
    status_expired: "انتهى",
    colRequest: "الطلب",
    colStatus: "الحالة",
    colProducts: "المنتجات",
    colValidUntil: "صالح لحد",
    colReceived: "وصل",
    colOrder: "الأوردر",
    openOrder: "افتح الأوردر",
    emptyNewTitle: "مفيش طلبات عروض أسعار جديدة",
    emptyNewHint: "العملاء بيطلبوا عرض سعر من صفحة المنتج أو من السلة. الطلب الجديد بيظهر هنا وبيوصلك إشعار.",
    emptyOtherTitle: "مفيش حاجة هنا",
    showAll: "اعرض كل العروض",
    emptyAllTitle: "لسه مفيش طلبات عروض أسعار",
    back: "عروض الأسعار",
    fallbackTitle: "طلب عرض سعر",
    receivedOn: "وصل {date}",
    customerTitle: "العميل",
    company: "الشركة",
    phone: "الموبايل",
    email: "الإيميل",
    noEmail: "مسابش إيميل",
    hasAccount: "عميل مسجّل دخول",
    openCustomer: "افتح العميل",
    messageTitle: "رسالته",
    detailsTitle: "العرض",
    termsTitle: "مدة العرض والملاحظة",
    quotedOn: "اتبعت",
    validUntil: "صالح لحد",
    order: "الأوردر",
    notSet: "—",
    shopperLink: "لينك صفحة العرض",
    shopperLinkHint: "بيفتح في المتصفح اللي العميل بعت منه الطلب.",
    copyLink: "انسخ اللينك",
    linesTitle: "المنتجات المطلوبة",
    linesHintNew: "حدد سعر القطعة والكمية اللي تقدر توفرها. شيل المنتج من العرض لو مش هتقدر توفره.",
    linesHintQuoted: "ده اللي العميل شايفه دلوقتي. غيّره وابعته تاني طول ما هو لسه مردش.",
    linesHintClosed: "اللي اتطلب، واللي عرضته.",
    unknownProduct: "منتج ممسوح",
    requested: "طلب {pieces}",
    shopperNote: "ملاحظة: {note}",
    include: "ضمن العرض",
    includeName: "ضيف {name} للعرض",
    leftOut: "مش ضمن العرض",
    quantity: "الكمية",
    unitPrice: "سعر القطعة",
    listPrice: "سعر المتجر {price}",
    lineTotal: "إجمالي السطر",
    total: "إجمالي العرض",
    totalHint: "الشحن بيتضاف على الأوردر لما العميل يوافق.",
    note: "ملاحظة للعميل",
    noteHint: "ميعاد التسليم، طريقة الدفع، أي حاجة لازم يعرفها.",
    validity: "صالح لحد",
    validityHint: "العميل يقدر يوافق لحد آخر اليوم ده.",
    send: "ابعت العرض",
    sendAgain: "ابعت العرض المعدّل",
    sending: "بنبعت…",
    willEmail: "هيوصل للعميل إيميل فيه لينك العرض.",
    noEmailHint: "العميل مسابش إيميل: بلّغه بالتليفون أو واتساب إن العرض جاهز.",
    wontEmailAgain: "مش هيتبعت للعميل إيميل تاني — هيشوف الأسعار الجديدة في صفحة العرض.",
    quantityError: "اكتب رقم صحيح من {min} لـ {max}.",
    priceError: "اكتب السعر بالأرقام، صفر أو أكتر.",
    linesError: "ضيف منتج واحد على الأقل للعرض.",
    validityError: "اختار يوم لسه مجاش.",
    sentToast: "العرض اتبعت.",
    updatedToast: "العرض اتحدّث.",
    cancelQuote: "الغي العرض",
    cancelTitle: "تلغي {number}؟",
    cancelBody: "العميل مش هيقدر يوافق عليه بعد كده. مينفعش ترجع في الإلغاء.",
    cancelConfirm: "الغي العرض",
    keep: "سيبه",
    working: "ثانية واحدة…",
    cancelledToast: "العرض اتلغى.",
    closedNotice: "العرض ده اتقفل في الوقت ده — دي حالته دلوقتي.",
    acceptedNote: "العميل وافق. الأوردر دفع عند الاستلام بالأسعار دي، وعليه علامة «quote».",
    declinedNote: "العميل رفض العرض ده.",
    cancelledNote: "انت لغيت العرض ده.",
    expiredNote: "العرض عدّى تاريخه من غير رد. ابعته تاني بتاريخ جديد علشان يتفتح.",
    viewOnly: "تقدر تشوف عروض الأسعار، لكن الرد عليها محتاج صلاحية إدارة الأوردرات.",
    colProduct: "المنتج",
    colRequested: "طلب",
    colOffered: "المعروض",
    colListPrice: "سعر المتجر",
    colUnitPrice: "سعرك",
    colLineTotal: "الإجمالي",
    searchLabel: "دوّر في عروض الأسعار",
    searchPlaceholder: "رقم العرض، العميل، الشركة أو الموبايل",
    chipsLabel: "عروض الأسعار حسب الحالة",
    colCustomer: "العميل",
    colContact: "تواصل",
    peek: "معاينة عرض {who}",
    menuLabel: "إجراءات العرض",
    menuOpen: "افتح الطلب",
    menuCall: "اتصل",
    menuWhatsapp: "واتساب",
    menuCopyPhone: "انسخ الرقم",
    menuCopyNumber: "انسخ رقم العرض",
    copiedPhone: "رقم العميل اتنسخ",
    copiedNumber: "رقم العرض اتنسخ",
    emptyNewDone: "أي طلب مستني أسعارك هيظهر هنا الأول.",
    emptyFilteredTitle: "مفيش عرض سعر بالبحث ده",
    clearSearch: "امسح البحث",
    openStore: "افتح متجرك",
    refreshFailed: "معرفناش نحدّث القائمة، فدي آخر حاجة اتحمّلت.",
    retry: "جرّب تاني",
    setPrices: "حدّد الأسعار",
    receivedAgo: "وصل {when}",
    validUntilDate: "صالح لحد {date}",
    expiredOn: "انتهى {date}",
    qlAsked: "المطلوب",
    qlLinesFailed: "معرفناش نجيب منتجات الطلب ده.",
    qlTimes: "× {n}",
    qlNotOffered: "مش ضمن العرض",
    tools: "أدوات العرض",
    copyShopperLink: "انسخ لينك صفحة العرض",
    copiedShopperLink: "لينك صفحة العرض اتنسخ",
    factsSummary: "اتبعت {sent} · صالح لحد {until}",
    factsSummaryNoDate: "اتبعت {sent}",
    reset: "رجّع زي ما كان",
    totalLine: "إجمالي العرض",
    includedCount: "{included} من {total} ضمن العرض",
    requestedShort: "طلب",
  },
} satisfies Messages;

export type QuoteStrings = (typeof QUOTE_STRINGS)["en"];

export const QUOTE_STATUS_TONE: Record<QuoteStatus, "warning" | "info" | "success" | "danger" | "neutral"> = {
  new: "warning",
  quoted: "info",
  accepted: "success",
  declined: "danger",
  cancelled: "neutral",
  expired: "neutral",
};

/** The label key of each status. */
export const QUOTE_STATUS_KEY: Record<QuoteStatus, keyof QuoteStrings> = {
  new: "status_new",
  quoted: "status_quoted",
  accepted: "status_accepted",
  declined: "status_declined",
  cancelled: "status_cancelled",
  expired: "status_expired",
};

/** An open quote can still be answered (again) or cancelled; an expired one is quoted past its date. */
export function isQuoteOpen(status: QuoteStatus): boolean {
  return status === "new" || status === "quoted" || status === "expired";
}
