import type { SurveyQuestionType, SurveyTexts } from "@store-builder/api-client";
import { getLocale, type Messages } from "@/i18n/LocaleContext";

/**
 * The words of the post-purchase survey in the dashboard (frontend-handoff
 * 236): its settings tab, the results page, the order page's card. The type
 * names, «ومكان لـ "حاجة تانية"» and «نتائج الاستبيان» are the handoff's own.
 */
export const SURVEY_STRINGS = {
  en: {
    title: "Post-purchase survey",
    description:
      "Ask shoppers a question or two on the thank-you page, right after they order — how they heard about you, whether they would recommend you — and read the answers in your reports.",
    on: "On",
    off: "Off",
    enabled: "Show the survey on the thank-you page",
    enabledHint: "Shoppers can skip it, and change their answers for 7 days.",
    seeResults: "See results",
    readOnlyTitle: "View only",
    readOnly: "Only the store owner or a workspace manager can change the survey.",
    questions: "Questions",
    questionsHint: "Up to {max} questions.",
    noQuestions: "No questions yet.",
    templates: "Start from a ready question:",
    question: "Question {n}",
    type: "Question type",
    type_choice: "Choice",
    type_score: "Score 0–10",
    type_text: "Text",
    typeHint_choice: "The shopper picks one answer.",
    typeHint_score: "The shopper gives a number from 0 to 10 — you get the average and the NPS.",
    typeHint_text: "The shopper writes in their own words.",
    typeChanged: "A new type starts this question's answers afresh: the old ones stop counting in the results.",
    textAr: "Question (Arabic)",
    textEn: "Question (English)",
    options: "Options",
    optionsHint: "From {min} to {max} options.",
    optionAr: "Option {n} (Arabic)",
    optionEn: "Option {n} (English)",
    addOption: "Add option",
    removeOption: "Remove option {n}",
    allowOther: "Allow other",
    allowOtherHint: "Shoppers can write their own answer when none of the options fits.",
    required: "Required",
    requiredHint: "The survey can't be sent without an answer to it.",
    addQuestion: "Add question",
    removeQuestion: "Remove question {n}",
    moveUp: "Move question {n} up",
    moveDown: "Move question {n} down",
    needText: "Write the question in Arabic or English.",
    needOptions: "This question needs at least two options.",
    needQuestion: "Add at least one question to switch the survey on.",
    fix: "Check the marked questions.",
    saved: "Survey saved.",

    resultsTitle: "Survey results",
    resultsQuestion: "What did your customers tell you?",
    scoreKpiHint: "Average of the first score question",
    settingsHint: "Add, reword or switch off the questions",
    showPeriod: "Show the last 12 months",
    questionsLabel: "Answers, question by question",
    resultsDescription: "What shoppers answered on the thank-you page — for {window}.",
    back: "Reports",
    resultsHint: "What shoppers answered on the thank-you page.",
    editQuestions: "Edit the questions",
    responses: "Responses",
    responsesHint: "Orders that answered",
    surveyOff: "The survey is switched off: shoppers don't see it now. These are the answers given while it was on.",
    notSetTitle: "No survey yet",
    notSetHint: "Add a question or two, switch the survey on, and the answers will show here.",
    setUp: "Set up the survey",
    emptyTitle: "No responses in this period",
    emptyHint: "Try a longer period, or wait for the next orders.",
    noAnswers: "Nobody answered this question in this period.",
    answers_one: "1 answer",
    answers_other: "{n} answers",
    other: "Other",
    otherTexts: "What they wrote",
    average: "Average",
    outOf: "out of {max}",
    nps: "NPS",
    npsHint: "Promoters (9–10) minus detractors (0–6)",
    promoters: "Promoters (9–10)",
    passives: "Passives (7–8)",
    detractors: "Detractors (0–6)",
    distribution: "Scores given",
    scoreCount: "{score}: {count}",
    latest: "Latest answers",
    order: "Order {number}",

    orderTitle: "Post-purchase survey",
    answeredAt: "Answered {date}",
    otherAnswer: "Other: {text}",
    scoreAnswer: "{n} out of {max}",
    allResults: "All results",
  },
  ar: {
    title: "استبيان بعد الشراء",
    description: "اسأل العميل سؤال أو اتنين في صفحة الشكر بعد ما يطلب — عرفك منين؟ هيرشّحك لصحابه؟ — وشوف الإجابات في التقارير.",
    on: "شغّال",
    off: "مقفول",
    enabled: "اعرض الاستبيان في صفحة الشكر",
    enabledHint: "العميل يقدر يتخطاه، ويقدر يغيّر إجاباته لمدة ٧ أيام.",
    seeResults: "شوف النتايج",
    readOnlyTitle: "عرض بس",
    readOnly: "صاحب المتجر أو مدير المتجر بس اللي يقدر يغيّر الاستبيان.",
    questions: "الأسئلة",
    questionsHint: "لحد {max} أسئلة.",
    noQuestions: "مفيش أسئلة لسه.",
    templates: "ابدأ بسؤال جاهز:",
    question: "سؤال {n}",
    type: "نوع السؤال",
    type_choice: "اختيار",
    type_score: "تقييم 0–10",
    type_text: "نص",
    typeHint_choice: "العميل يختار إجابة واحدة.",
    typeHint_score: "العميل يدّي رقم من ٠ لـ ١٠ — وبنحسبلك المتوسط والـ NPS.",
    typeHint_text: "العميل يكتب بكلامه.",
    typeChanged: "تغيير النوع بيبدأ إجابات السؤال من الأول: الإجابات القديمة مش هتتحسب في النتايج.",
    textAr: "السؤال (عربي)",
    textEn: "السؤال (إنجليزي)",
    options: "الاختيارات",
    optionsHint: "من {min} لـ {max} اختيار.",
    optionAr: "اختيار {n} (عربي)",
    optionEn: "اختيار {n} (إنجليزي)",
    addOption: "ضيف اختيار",
    removeOption: "امسح الاختيار {n}",
    allowOther: "ومكان لـ \"حاجة تانية\"",
    allowOtherHint: "العميل يكتب إجابته لو مش لاقيها في الاختيارات.",
    required: "إجباري",
    requiredHint: "الاستبيان مش هيتبعت من غير إجابة عليه.",
    addQuestion: "ضيف سؤال",
    removeQuestion: "امسح السؤال {n}",
    moveUp: "طلّع السؤال {n} لفوق",
    moveDown: "نزّل السؤال {n} لتحت",
    needText: "اكتب السؤال بالعربي أو الإنجليزي.",
    needOptions: "السؤال ده محتاج اختيارين على الأقل.",
    needQuestion: "ضيف سؤال واحد على الأقل عشان تشغّل الاستبيان.",
    fix: "راجع الأسئلة اللي عليها علامة.",
    saved: "الاستبيان اتحفظ.",

    resultsTitle: "نتائج الاستبيان",
    resultsQuestion: "العملاء قالولك إيه؟",
    scoreKpiHint: "متوسط أول سؤال تقييم",
    settingsHint: "ضيف أسئلة أو غيّر صياغتها أو اقفل الاستبيان",
    showPeriod: "اعرض آخر سنة",
    questionsLabel: "الإجابات سؤال بسؤال",
    resultsDescription: "إجابات العملاء في صفحة الشكر — عن {window}.",
    back: "التقارير",
    resultsHint: "إجابات العملاء على استبيان صفحة الشكر.",
    editQuestions: "عدّل الأسئلة",
    responses: "عدد الردود",
    responsesHint: "أوردرات جاوبت على الاستبيان",
    surveyOff: "الاستبيان مقفول دلوقتي والعملاء مش شايفينه. دي الإجابات اللي اتسجلت وهو شغّال.",
    notSetTitle: "مفيش استبيان لسه",
    notSetHint: "ضيف سؤال أو اتنين وشغّل الاستبيان، والإجابات هتظهر هنا.",
    setUp: "جهّز الاستبيان",
    emptyTitle: "مفيش ردود في الفترة دي",
    emptyHint: "جرّب فترة أطول، أو استنى الأوردرات الجاية.",
    noAnswers: "محدش جاوب على السؤال ده في الفترة دي.",
    answers_one: "إجابة واحدة",
    answers_two: "إجابتين",
    answers_few: "{n} إجابات",
    answers_other: "{n} إجابة",
    other: "حاجة تانية",
    otherTexts: "اللي كتبوه",
    average: "المتوسط",
    outOf: "من {max}",
    nps: "NPS",
    npsHint: "المروّجين (٩–١٠) ناقص المنتقدين (٠–٦)",
    promoters: "مروّجين (٩–١٠)",
    passives: "محايدين (٧–٨)",
    detractors: "منتقدين (٠–٦)",
    distribution: "التقييمات",
    scoreCount: "{score}: {count}",
    latest: "آخر الردود",
    order: "أوردر {number}",

    orderTitle: "استبيان بعد الشراء",
    answeredAt: "جاوب {date}",
    otherAnswer: "حاجة تانية: {text}",
    scoreAnswer: "{n} من {max}",
    allResults: "كل النتايج",
  },
} satisfies Messages;

export type SurveyStrings = (typeof SURVEY_STRINGS)["en"];

export const TYPE_KEY: Record<SurveyQuestionType, "type_choice" | "type_score" | "type_text"> = {
  choice: "type_choice",
  score: "type_score",
  text: "type_text",
};

export const TYPE_HINT_KEY: Record<SurveyQuestionType, "typeHint_choice" | "typeHint_score" | "typeHint_text"> = {
  choice: "typeHint_choice",
  score: "typeHint_score",
  text: "typeHint_text",
};

/**
 * A question's or an option's text in the dashboard's language; the other
 * language stands in when this one is empty.
 */
export function surveyTextOf(texts: SurveyTexts | null | undefined): string {
  const ar = texts?.ar?.trim() ?? "";
  const en = texts?.en?.trim() ?? "";
  return getLocale() === "ar" ? ar || en : en || ar;
}

/** Where the results open: the last 90 days, the API's own default window. */
export const SURVEY_RESULTS_PATH = "/analytics/survey";
export const SURVEY_SETTINGS_PATH = "/store-settings/survey";
