import type { Messages } from "@/i18n/LocaleContext";

/** Email suppressions (handoff 386): the Customers tab and the banner on a customer's page. */
export const SUPPRESSION_STRINGS = {
  en: {
    tab: "Suppressed emails",
    help: "An address is stopped when an email hard-bounces or the customer marks it as spam. Sign-in and security codes are always sent",
    email: "Email",
    reason: "Reason",
    detail: "Detail",
    date: "Date",
    reason_hard_bounce: "Bounce",
    reason_complaint: "Spam complaint",
    reasonFilter: "Filter by reason",
    reason_all: "All",
    search: "Search by email",
    searchPlaceholder: "The full address, like mona@example.com",
    lift: "Lift",
    liftFor: "Lift the stop on {email}",
    emptyTitle: "No suppressed addresses — your emails are getting through",
    emptyFiltered: "No suppressed address matches.",
    showAll: "Show all",
    confirmTitle: "Allow emails to {email} again?",
    confirmBody: "Sure? If the address is still wrong, the email will bounce again",
    confirm: "Allow emails again",
    lifted: "Emails go to {email} again.",
    gone: "That address was already lifted.",
    bannerBounce: "Emails to this address are stopped: it bounced",
    bannerComplaint: "Emails to this address are stopped: the customer marked them as spam",
    bannerOther: "Emails to this address are stopped",
    allow: "Allow emails again",
    since: "Since {date}",
  },
  ar: {
    tab: "عناوين موقوفة",
    help: "العنوان بيتوقف لما الإيميل يرتدّ نهائيًا أو العميل يعلّمه كمزعج. رموز الدخول والأمان بتتبعت دايمًا",
    email: "الإيميل",
    reason: "السبب",
    detail: "التفاصيل",
    date: "التاريخ",
    reason_hard_bounce: "ارتداد",
    reason_complaint: "شكوى مزعج",
    reasonFilter: "فلتر بالسبب",
    reason_all: "الكل",
    search: "دوّر بالإيميل",
    searchPlaceholder: "العنوان كامل، زي mona@example.com",
    lift: "رفع الإيقاف",
    liftFor: "ارفع الإيقاف عن {email}",
    emptyTitle: "مفيش عناوين موقوفة — كل إيميلاتك بتوصل",
    emptyFiltered: "مفيش عنوان موقوف مطابق.",
    showAll: "اعرض الكل",
    confirmTitle: "تسمح بالإرسال لـ {email} تاني؟",
    confirmBody: "متأكد؟ لو العنوان لسه غلط، الإيميل هيرتدّ تاني",
    confirm: "السماح بالإرسال تاني",
    lifted: "الإيميلات هتتبعت لـ {email} تاني.",
    gone: "العنوان ده اترفع عنه الإيقاف قبل كده.",
    bannerBounce: "الإيميلات مش بتتبعت للعنوان ده: ارتدّ",
    bannerComplaint: "الإيميلات مش بتتبعت للعنوان ده: العميل علّمها كمزعجة",
    bannerOther: "الإيميلات مش بتتبعت للعنوان ده",
    allow: "السماح بالإرسال تاني",
    since: "من {date}",
  },
} satisfies Messages;

export type SuppressionStrings = Record<keyof (typeof SUPPRESSION_STRINGS)["en"], string>;

export const suppressionReason = (t: SuppressionStrings, reason: string): string => (t as Record<string, string | undefined>)[`reason_${reason}`] ?? reason;
