import type { Messages } from "@/i18n/LocaleContext";

/** Email suppressions: the Customers tab and the banner on a customer's page. */
export const SUPPRESSION_STRINGS = {
  en: {
    tab: "Suppressed emails",
    help: "An address is stopped when an email hard-bounces or the customer marks it as spam. Sign-in and security codes are always sent",
    email: "Email",
    reason: "Reason",
    detail: "Detail",
    date: "Date",
    reason_hard_bounce: "Bounce",
    reason_complaint: "Spam complaint",
    reasonFilter: "Filter by reason",
    reason_all: "All",
    search: "Search by email",
    searchPlaceholder: "The full address, like mona@example.com",
    lift: "Lift",
    liftFor: "Lift the stop on {email}",
    emptyTitle: "No suppressed addresses — your emails are getting through",
    emptyFiltered: "No suppressed address matches.",
    showAll: "Show all",
    confirmTitle: "Allow emails to {email} again?",
    confirmBody: "Sure? If the address is still wrong, the email will bounce again",
    confirm: "Allow emails again",
    lifted: "Emails go to {email} again.",
    gone: "That address was already lifted.",
    bannerBounce: "Emails to this address are stopped: it bounced",
    bannerComplaint: "Emails to this address are stopped: the customer marked them as spam",
    bannerOther: "Emails to this address are stopped",
    allow: "Allow emails again",
    since: "Since {date}",
  },
  ar: {
    tab: "عناوين موقوفة",
    help: "يُوقَف العنوان عندما يرتدّ البريد نهائيًا أو يصنّفه العميل كرسالة مزعجة. رموز الدخول والأمان تُرسل دائمًا",
    email: "البريد الإلكتروني",
    reason: "السبب",
    detail: "التفاصيل",
    date: "التاريخ",
    reason_hard_bounce: "ارتداد",
    reason_complaint: "شكوى رسالة مزعجة",
    reasonFilter: "تصفية بالسبب",
    reason_all: "الكل",
    search: "ابحث بالبريد الإلكتروني",
    searchPlaceholder: "العنوان كاملًا، مثل mona@example.com",
    lift: "رفع الإيقاف",
    liftFor: "رفع الإيقاف عن {email}",
    emptyTitle: "لا توجد عناوين موقوفة — كل رسائلك تصل",
    emptyFiltered: "لا يوجد عنوان موقوف مطابق.",
    showAll: "عرض الكل",
    confirmTitle: "هل تسمح بالإرسال إلى {email} مرة أخرى؟",
    confirmBody: "هل أنت متأكد؟ إذا كان العنوان ما زال خاطئًا فسيرتدّ البريد مرة أخرى",
    confirm: "السماح بالإرسال مرة أخرى",
    lifted: "ستُرسل الرسائل إلى {email} مرة أخرى.",
    gone: "رُفع الإيقاف عن هذا العنوان من قبل.",
    bannerBounce: "لا تُرسل الرسائل إلى هذا العنوان: ارتدّ البريد",
    bannerComplaint: "لا تُرسل الرسائل إلى هذا العنوان: صنّفها العميل كرسائل مزعجة",
    bannerOther: "لا تُرسل الرسائل إلى هذا العنوان",
    allow: "السماح بالإرسال مرة أخرى",
    since: "منذ {date}",
  },
} satisfies Messages;

export type SuppressionStrings = Record<keyof (typeof SUPPRESSION_STRINGS)["en"], string>;

export const suppressionReason = (t: SuppressionStrings, reason: string): string => (t as Record<string, string | undefined>)[`reason_${reason}`] ?? reason;
