import type { GiftCardState, GiftCardTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Marketing → Gift cards: the list, the issue dialog, a card's
 * page and the "products sold as gift cards" setting. Arabic is the
 * merchant's Egyptian.
 */
export const GIFT_CARD_STRINGS = {
  en: {
    // list
    title: "Gift cards",
    description: "Cards with a balance your customers spend at checkout, with cash on delivery.",
    issue: "Issue gift card",
    searchLabel: "Search gift cards",
    searchPlaceholder: "Full code, last 4 or email",
    clearSearch: "Clear search",
    filterLabel: "Show gift cards",
    filterAll: "All",
    state_active: "Active",
    state_empty: "Used up",
    state_expired: "Expired",
    state_disabled: "Disabled",
    colCard: "Card",
    colBalance: "Balance",
    colState: "Status",
    colExpires: "Valid until",
    colCreated: "Issued",
    cardName: "•••• {last4}",
    noExpiry: "No end date",
    noRecipient: "No recipient",
    sourceOrder: "Bought on an order",
    sourceManual: "Issued by you",
    emptyTitle: "No gift cards yet",
    emptyHint: "Issue a card with a balance for a customer, or sell gift cards as a product from the setting below.",
    noMatchTitle: "No gift cards match",
    noMatchHint: "Try the full code, its last 4 characters or part of the recipient's email.",
    showAll: "Show all gift cards",
    balanceLinkTitle: "Where customers check their balance",
    balanceLinkHint: "Put this link in your store's menu or footer, or send it with the card.",
    // issue dialog
    issueTitle: "Issue gift card",
    issueDescription: "The code is shown once when the card is made. Save it or email it to the recipient.",
    amount: "Value",
    amountError: "Enter a value above zero.",
    expires: "Valid until (optional)",
    expiresHint: "Leave it empty for a card with no end date.",
    expiresError: "Pick a date after today.",
    recipientName: "Recipient's name (optional)",
    recipientEmail: "Recipient's email (optional)",
    emailError: "Enter a valid email, or leave it empty.",
    message: "Message to the recipient (optional)",
    messageHint: "Sent with the card. Up to 500 characters.",
    note: "Note for your team (optional)",
    noteHint: "Only your team sees it.",
    sendEmail: "Email the code to the recipient",
    sendEmailNeedsEmail: "Add the recipient's email to send it.",
    issuing: "Issuing…",
    issueSubmit: "Issue gift card",
    cancel: "Cancel",
    issuedTitle: "Gift card ready",
    saveCodeNow: "Save this code now — it won't be shown in full again",
    codeLabel: "Gift card code",
    copyCode: "Copy code",
    emailedTo: "We also emailed it to {email}.",
    issuedOf: "Worth {amount}",
    openIssued: "Open the card",
    done: "Done",
    // card page
    back: "Gift cards",
    cardTitle: "Gift card •••• {last4}",
    balance: "Balance",
    ofInitial: "of {initial}",
    validUntil: "Valid until {date}",
    expiredOn: "Expired on {date}",
    issuedOn: "Issued {date}",
    boughtOnOrder: "Bought on an order",
    openOrder: "Open the order",
    recipient: "Recipient",
    recipientNameLabel: "Name",
    recipientEmailLabel: "Email",
    messageLabel: "Message",
    noteLabel: "Team note",
    showCode: "Show code",
    showingCode: "Showing…",
    hideCode: "Hide code",
    resend: "Resend to recipient",
    resending: "Sending…",
    resent: "Sent again to {email}.",
    adjust: "Adjust balance",
    disable: "Disable card",
    enable: "Turn the card back on",
    enabling: "Turning on…",
    disableTitle: "Disable gift card •••• {last4}?",
    disableBody: "It won't be accepted at checkout until you turn it back on. Its balance stays as it is.",
    disableConfirm: "Disable card",
    disabling: "Disabling…",
    disabledToast: "The card is disabled.",
    enabledToast: "The card works again.",
    editDetails: "Edit details",
    history: "Balance history",
    historyHint: "Every change of the balance, newest first.",
    historyEmpty: "No changes yet.",
    kind_issue: "Issued",
    kind_redeem: "Spent on an order",
    kind_refund: "Returned from an order",
    kind_adjust: "Adjusted by your team",
    // With an online payment: held at checkout, then spent or given back.
    kind_hold: "Held for an order",
    kind_hold_released: "Hold released",
    kind_release: "Returned to card",
    colWhen: "When",
    colWhat: "What",
    colChange: "Change",
    colAfter: "Balance after",
    afterShort: "Left: {amount}",
    orderLink: "Order",
    disabledNotice: "This card is disabled: checkout refuses it until you turn it back on.",
    expiredNotice: "This card has expired. Set a new date from “Edit details” to use it again.",
    emptyNotice: "This card's balance is used up. Add to it with “Adjust balance”.",
    // adjust dialog
    adjustTitle: "Adjust balance",
    adjustDescription: "Now: {balance}",
    direction: "Change",
    addTo: "Add to the balance",
    takeOff: "Take off the balance",
    adjustAmount: "Amount",
    adjustNote: "Reason (optional)",
    adjustNoteHint: "Shown in the card's history.",
    newBalance: "New balance: {amount}",
    tooMuch: "You can take off at most {amount}.",
    adjustSave: "Save",
    adjustSaving: "Saving…",
    adjusted: "Balance updated.",
    // edit dialog
    editTitle: "Edit details",
    editSave: "Save",
    editSaving: "Saving…",
    saved: "Saved.",
    noChanges: "Nothing changed.",
    // settings
    settingsTitle: "Products sold as gift cards",
    settingsHint:
      "Each piece sold of these products makes a gift card worth its price, emailed to the buyer once the order is paid or delivered.",
    settingsLoading: "Loading the gift card setting…",
    noProductsSelected: "No products yet",
    chooseProducts: "Choose products",
    changeProducts: "Change",
    products_one: "1 product",
    products_other: "{n} products",
    validity: "Days a bought card stays valid",
    validityHint: "Leave it empty for no end date.",
    validityError: "Enter a number of days from 1 to 3650, or leave it empty.",
    validFor: "Valid for {days}",
    noEnd: "Bought cards have no end date",
    filterProducts: "Search products",
    noCatalog: "Add a product first, then choose it here.",
    noMatchProducts: "No products match.",
    maxProducts: "Up to {max} products.",
    pickerTitle: "Products sold as gift cards",
    settingsSave: "Save",
    settingsSaving: "Saving…",
    settingsSaved: "Saved. New orders of these products will make gift cards.",
    settingsTip: "Tip: make one product per value (200, 500 …), and say in its description that the code arrives by email.",
  },
  ar: {
    // list
    title: "بطاقات الهدايا",
    description: "بطاقات برصيد يخصمه العميل من طلبه في صفحة الدفع، مع الدفع عند الاستلام.",
    issue: "إنشاء بطاقة هدية",
    searchLabel: "ابحث في بطاقات الهدايا",
    searchPlaceholder: "الرمز كاملًا أو آخر ٤ أحرف أو البريد الإلكتروني",
    clearSearch: "مسح البحث",
    filterLabel: "عرض بطاقات الهدايا",
    filterAll: "الكل",
    state_active: "مفعّلة",
    state_empty: "نفد رصيدها",
    state_expired: "منتهية",
    state_disabled: "متوقفة",
    colCard: "البطاقة",
    colBalance: "الرصيد",
    colState: "الحالة",
    colExpires: "صالحة حتى",
    colCreated: "تاريخ الإنشاء",
    cardName: "•••• {last4}",
    noExpiry: "بلا تاريخ انتهاء",
    noRecipient: "بدون مستلم",
    sourceOrder: "اشتُريت في طلب",
    sourceManual: "أنشأتها أنت",
    emptyTitle: "لا توجد بطاقات هدايا بعد",
    emptyHint: "أنشئ بطاقة برصيد لعميل، أو بِع بطاقات الهدايا كمنتج من الإعداد في الأسفل.",
    noMatchTitle: "لا توجد بطاقات مطابقة",
    noMatchHint: "جرّب الرمز كاملًا، أو آخر ٤ أحرف منه، أو جزءًا من بريد المستلم.",
    showAll: "عرض كل البطاقات",
    balanceLinkTitle: "كيف يعرف العميل رصيده",
    balanceLinkHint: "ضع هذا الرابط في قائمة المتجر أو في التذييل، أو أرسله مع البطاقة.",
    // issue dialog
    issueTitle: "إنشاء بطاقة هدية",
    issueDescription: "يظهر الرمز مرة واحدة فقط عند إنشاء البطاقة. احفظه أو أرسله إلى بريد المستلم.",
    amount: "القيمة",
    amountError: "اكتب قيمة أكبر من صفر.",
    expires: "صالحة حتى (اختياري)",
    expiresHint: "اتركه فارغًا إذا كانت البطاقة بلا تاريخ انتهاء.",
    expiresError: "اختر تاريخًا بعد اليوم.",
    recipientName: "اسم المستلم (اختياري)",
    recipientEmail: "بريد المستلم الإلكتروني (اختياري)",
    emailError: "اكتب بريدًا إلكترونيًا صحيحًا، أو اتركه فارغًا.",
    message: "رسالة للمستلم (اختياري)",
    messageHint: "تُرسل مع البطاقة. حتى ٥٠٠ حرف.",
    note: "ملاحظة لفريقك (اختياري)",
    noteHint: "يراها فريقك فقط.",
    sendEmail: "إرسال الرمز إلى بريد المستلم",
    sendEmailNeedsEmail: "اكتب بريد المستلم لنرسله إليه.",
    issuing: "جارٍ إنشاء البطاقة…",
    issueSubmit: "إنشاء البطاقة",
    cancel: "إلغاء",
    issuedTitle: "بطاقة الهدية جاهزة",
    saveCodeNow: "احفظ هذا الرمز الآن — لن يظهر كاملًا مرة أخرى",
    codeLabel: "رمز بطاقة الهدية",
    copyCode: "نسخ الرمز",
    emailedTo: "وأرسلناه أيضًا إلى {email}.",
    issuedOf: "بقيمة {amount}",
    openIssued: "فتح البطاقة",
    done: "تم",
    // card page
    back: "بطاقات الهدايا",
    cardTitle: "بطاقة هدية •••• {last4}",
    balance: "الرصيد",
    ofInitial: "من {initial}",
    validUntil: "صالحة حتى {date}",
    expiredOn: "انتهت في {date}",
    issuedOn: "أُنشئت {date}",
    boughtOnOrder: "اشتُريت في طلب",
    openOrder: "فتح الطلب",
    recipient: "المستلم",
    recipientNameLabel: "الاسم",
    recipientEmailLabel: "البريد الإلكتروني",
    messageLabel: "الرسالة",
    noteLabel: "ملاحظة الفريق",
    showCode: "عرض الرمز",
    showingCode: "جارٍ جلب الرمز…",
    hideCode: "إخفاء الرمز",
    resend: "إعادة إرساله إلى المستلم",
    resending: "جارٍ الإرسال…",
    resent: "أُعيد إرساله إلى {email}.",
    adjust: "تعديل الرصيد",
    disable: "إيقاف البطاقة",
    enable: "تفعيل البطاقة مرة أخرى",
    enabling: "جارٍ التفعيل…",
    disableTitle: "هل تريد إيقاف بطاقة الهدية •••• {last4}؟",
    disableBody: "لن تُقبل في صفحة الدفع حتى تفعّلها مرة أخرى. سيبقى رصيدها كما هو.",
    disableConfirm: "إيقاف البطاقة",
    disabling: "جارٍ الإيقاف…",
    disabledToast: "تم إيقاف البطاقة.",
    enabledToast: "عادت البطاقة إلى العمل.",
    editDetails: "تعديل البيانات",
    history: "حركة الرصيد",
    historyHint: "كل تغيير في الرصيد، الأحدث أولًا.",
    historyEmpty: "لا توجد حركة بعد.",
    kind_issue: "أُنشئت",
    kind_redeem: "صُرف في طلب",
    kind_refund: "أُعيد من طلب",
    kind_adjust: "تعديل من فريقك",
    kind_hold: "محجوز لطلب",
    kind_hold_released: "أُلغي الحجز",
    kind_release: "أُعيد إلى البطاقة",
    colWhen: "الوقت",
    colWhat: "ما حدث",
    colChange: "التغيير",
    colAfter: "الرصيد بعده",
    afterShort: "المتبقي: {amount}",
    orderLink: "الطلب",
    disabledNotice: "هذه البطاقة متوقفة: لن تقبلها صفحة الدفع حتى تفعّلها مرة أخرى.",
    expiredNotice: "انتهت هذه البطاقة. ضع لها تاريخًا جديدًا من «تعديل البيانات» لتعمل مرة أخرى.",
    emptyNotice: "نفد رصيد هذه البطاقة. زِده من «تعديل الرصيد».",
    // adjust dialog
    adjustTitle: "تعديل الرصيد",
    adjustDescription: "الآن: {balance}",
    direction: "التعديل",
    addTo: "زيادة الرصيد",
    takeOff: "خصم من الرصيد",
    adjustAmount: "المبلغ",
    adjustNote: "السبب (اختياري)",
    adjustNoteHint: "يظهر في حركة الرصيد.",
    newBalance: "الرصيد الجديد: {amount}",
    tooMuch: "أقصى ما يمكن خصمه {amount}.",
    adjustSave: "حفظ",
    adjustSaving: "جارٍ الحفظ…",
    adjusted: "تم تعديل الرصيد.",
    // edit dialog
    editTitle: "تعديل البيانات",
    editSave: "حفظ",
    editSaving: "جارٍ الحفظ…",
    saved: "تم الحفظ.",
    noChanges: "لم يتغير شيء.",
    // settings
    settingsTitle: "منتجات تُباع كبطاقات هدايا",
    settingsHint:
      "كل قطعة تُباع من هذه المنتجات تُنشئ بطاقة هدية بسعرها، وتُرسل إلى بريد المشتري فور دفع الطلب أو تسليمه.",
    settingsLoading: "جارٍ تحميل إعداد بطاقات الهدايا…",
    noProductsSelected: "لا توجد منتجات بعد",
    chooseProducts: "اختيار المنتجات",
    changeProducts: "تغيير",
    products_one: "منتج واحد",
    products_two: "منتجان",
    products_few: "{n} منتجات",
    products_other: "{n} منتجًا",
    validity: "عدد أيام صلاحية البطاقة المشتراة",
    validityHint: "اتركه فارغًا إذا كانت بلا تاريخ انتهاء.",
    validityError: "اكتب عدد أيام من ١ إلى ٣٦٥٠، أو اتركه فارغًا.",
    validFor: "صالحة لمدة {days}",
    noEnd: "البطاقات المشتراة بلا تاريخ انتهاء",
    filterProducts: "ابحث في المنتجات",
    noCatalog: "أضف منتجًا أولًا، ثم اختره هنا.",
    noMatchProducts: "لا توجد منتجات بهذا الاسم.",
    maxProducts: "حتى {max} منتج.",
    pickerTitle: "منتجات تُباع كبطاقات هدايا",
    settingsSave: "حفظ",
    settingsSaving: "جارٍ الحفظ…",
    settingsSaved: "تم الحفظ. الطلبات الجديدة لهذه المنتجات ستُنشئ بطاقات هدايا.",
    settingsTip: "نصيحة: أنشئ منتجًا لكل قيمة (٢٠٠، ٥٠٠ …)، واكتب في وصفه أن الرمز يصل بالبريد الإلكتروني.",
  },
} satisfies Messages;

export type GiftCardStrings = (typeof GIFT_CARD_STRINGS)["en"];

export const STATE_KEY: Record<GiftCardState, keyof GiftCardStrings> = {
  active: "state_active",
  empty: "state_empty",
  expired: "state_expired",
  disabled: "state_disabled",
};

export const STATE_TONE: Record<GiftCardState, "success" | "neutral" | "warning" | "danger"> = {
  active: "success",
  empty: "neutral",
  expired: "warning",
  disabled: "danger",
};

export const KIND_KEY: Record<GiftCardTransactionKind, keyof GiftCardStrings> = {
  issue: "kind_issue",
  redeem: "kind_redeem",
  refund: "kind_refund",
  adjust: "kind_adjust",
  hold: "kind_hold",
  hold_released: "kind_hold_released",
  release: "kind_release",
};

/** "2026-12-31" (a date field) → the end of that day on this device, as ISO; "" → null. */
export function dateFieldToIso(value: string): string | null {
  if (!value) return null;
  const d = new Date(`${value}T23:59:59`);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}

/** An ISO date → "2026-12-31" in this device's calendar, for a date field. */
export function isoToDateField(iso: string | null | undefined): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

/** Tomorrow as a date field's `min`. */
export function tomorrowDateField(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return isoToDateField(d.toISOString());
}

/** A loose email check; the API has the final word. */
export const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
