import type { GiftCardState, GiftCardTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Marketing → Gift cards (handoff 189): the list, the issue dialog, a card's
 * page and the "products sold as gift cards" setting. Arabic is the
 * merchant's Egyptian, with the handoff's wording table.
 */
export const GIFT_CARD_STRINGS = {
  en: {
    // list
    title: "Gift cards",
    description: "Cards with a balance your customers spend at checkout, with cash on delivery or an online payment.",
    issue: "Issue gift card",
    searchLabel: "Search gift cards",
    searchPlaceholder: "Full code, last 4 or email",
    clearSearch: "Clear search",
    filterLabel: "Show gift cards",
    filterAll: "All",
    state_active: "Active",
    state_empty: "Used up",
    state_expired: "Expired",
    state_disabled: "Disabled",
    colCard: "Card",
    colBalance: "Balance",
    colState: "Status",
    colExpires: "Valid until",
    colCreated: "Issued",
    cardName: "•••• {last4}",
    noExpiry: "No end date",
    noRecipient: "No recipient",
    sourceOrder: "Bought on an order",
    sourceManual: "Issued by you",
    emptyTitle: "No gift cards yet",
    emptyHint: "Issue a card with a balance for a customer, or sell gift cards as a product from the setting below.",
    noMatchTitle: "No gift cards match",
    noMatchHint: "Try the full code, its last 4 characters or part of the recipient's email.",
    showAll: "Show all gift cards",
    balanceLinkTitle: "Where customers check their balance",
    balanceLinkHint: "Put this link in your store's menu or footer, or send it with the card.",
    // issue dialog
    issueTitle: "Issue gift card",
    issueDescription: "The code is shown once when the card is made. Save it or email it to the recipient.",
    amount: "Value",
    amountError: "Enter a value above zero.",
    expires: "Valid until (optional)",
    expiresHint: "Leave it empty for a card with no end date.",
    expiresError: "Pick a date after today.",
    recipientName: "Recipient's name (optional)",
    recipientEmail: "Recipient's email (optional)",
    emailError: "Enter a valid email, or leave it empty.",
    message: "Message to the recipient (optional)",
    messageHint: "Sent with the card. Up to 500 characters.",
    note: "Note for your team (optional)",
    noteHint: "Only your team sees it.",
    sendEmail: "Email the code to the recipient",
    sendEmailNeedsEmail: "Add the recipient's email to send it.",
    issuing: "Issuing…",
    issueSubmit: "Issue gift card",
    cancel: "Cancel",
    issuedTitle: "Gift card ready",
    saveCodeNow: "Save this code now — it won't be shown in full again",
    codeLabel: "Gift card code",
    copyCode: "Copy code",
    emailedTo: "We also emailed it to {email}.",
    issuedOf: "Worth {amount}",
    openIssued: "Open the card",
    done: "Done",
    // card page
    back: "Gift cards",
    cardTitle: "Gift card •••• {last4}",
    balance: "Balance",
    ofInitial: "of {initial}",
    validUntil: "Valid until {date}",
    expiredOn: "Expired on {date}",
    issuedOn: "Issued {date}",
    boughtOnOrder: "Bought on an order",
    openOrder: "Open the order",
    recipient: "Recipient",
    recipientNameLabel: "Name",
    recipientEmailLabel: "Email",
    messageLabel: "Message",
    noteLabel: "Team note",
    showCode: "Show code",
    showingCode: "Showing…",
    hideCode: "Hide code",
    resend: "Resend to recipient",
    resending: "Sending…",
    resent: "Sent again to {email}.",
    adjust: "Adjust balance",
    disable: "Disable card",
    enable: "Turn the card back on",
    enabling: "Turning on…",
    disableTitle: "Disable gift card •••• {last4}?",
    disableBody: "It won't be accepted at checkout until you turn it back on. Its balance stays as it is.",
    disableConfirm: "Disable card",
    disabling: "Disabling…",
    disabledToast: "The card is disabled.",
    enabledToast: "The card works again.",
    editDetails: "Edit details",
    history: "Balance history",
    historyHint: "Every change of the balance, newest first.",
    historyEmpty: "No changes yet.",
    kind_issue: "Issued",
    kind_redeem: "Spent on an order",
    kind_refund: "Returned from an order",
    kind_adjust: "Adjusted by your team",
    // With an online payment (handoff 201): held at checkout, then spent or given back.
    kind_hold: "Held for an order",
    kind_hold_released: "Hold released",
    kind_release: "Returned to card",
    colWhen: "When",
    colWhat: "What",
    colChange: "Change",
    colAfter: "Balance after",
    afterShort: "Left: {amount}",
    orderLink: "Order",
    disabledNotice: "This card is disabled: checkout refuses it until you turn it back on.",
    expiredNotice: "This card has expired. Set a new date from “Edit details” to use it again.",
    emptyNotice: "This card's balance is used up. Add to it with “Adjust balance”.",
    // adjust dialog
    adjustTitle: "Adjust balance",
    adjustDescription: "Now: {balance}",
    direction: "Change",
    addTo: "Add to the balance",
    takeOff: "Take off the balance",
    adjustAmount: "Amount",
    adjustNote: "Reason (optional)",
    adjustNoteHint: "Shown in the card's history.",
    newBalance: "New balance: {amount}",
    tooMuch: "You can take off at most {amount}.",
    adjustSave: "Save",
    adjustSaving: "Saving…",
    adjusted: "Balance updated.",
    // edit dialog
    editTitle: "Edit details",
    editSave: "Save",
    editSaving: "Saving…",
    saved: "Saved.",
    noChanges: "Nothing changed.",
    // settings
    settingsTitle: "Products sold as gift cards",
    settingsHint:
      "Each piece sold of these products makes a gift card worth its price, emailed to the buyer once the order is paid or delivered.",
    settingsLoading: "Loading the gift card setting…",
    noProductsSelected: "No products yet",
    chooseProducts: "Choose products",
    changeProducts: "Change",
    products_one: "1 product",
    products_other: "{n} products",
    validity: "Days a bought card stays valid",
    validityHint: "Leave it empty for no end date.",
    validityError: "Enter a number of days from 1 to 3650, or leave it empty.",
    validFor: "Valid for {days}",
    noEnd: "Bought cards have no end date",
    filterProducts: "Search products",
    noCatalog: "Add a product first, then choose it here.",
    noMatchProducts: "No products match.",
    maxProducts: "Up to {max} products.",
    pickerTitle: "Products sold as gift cards",
    settingsSave: "Save",
    settingsSaving: "Saving…",
    settingsSaved: "Saved. New orders of these products will make gift cards.",
    settingsTip: "Tip: make one product per value (200, 500 …), and say in its description that the code arrives by email.",
  },
  ar: {
    // list
    title: "كروت الهدايا",
    description: "كروت برصيد العميل بيخصمه من الأوردر في صفحة الدفع، مع الدفع عند الاستلام أو الدفع أونلاين.",
    issue: "اعمل كارت هدية",
    searchLabel: "دوّر في كروت الهدايا",
    searchPlaceholder: "الكود كامل أو آخر ٤ حروف أو الإيميل",
    clearSearch: "امسح البحث",
    filterLabel: "اعرض كروت الهدايا",
    filterAll: "الكل",
    state_active: "شغّال",
    state_empty: "رصيده خلص",
    state_expired: "انتهى",
    state_disabled: "متوقف",
    colCard: "الكارت",
    colBalance: "الرصيد",
    colState: "الحالة",
    colExpires: "صالح لحد",
    colCreated: "اتعمل",
    cardName: "•••• {last4}",
    noExpiry: "مالوش تاريخ انتهاء",
    noRecipient: "من غير مستلم",
    sourceOrder: "اتشترى في أوردر",
    sourceManual: "إنت عملته",
    emptyTitle: "لسه مفيش كروت هدايا",
    emptyHint: "اعمل كارت برصيد لعميل، أو بيع كروت هدايا كمنتج من الإعداد اللي تحت.",
    noMatchTitle: "مفيش كروت بالشكل ده",
    noMatchHint: "جرّب الكود كامل، أو آخر ٤ حروف منه، أو جزء من إيميل المستلم.",
    showAll: "اعرض كل الكروت",
    balanceLinkTitle: "العميل يعرف رصيده منين",
    balanceLinkHint: "حط اللينك ده في قايمة المتجر أو في الفوتر، أو ابعته مع الكارت.",
    // issue dialog
    issueTitle: "اعمل كارت هدية",
    issueDescription: "الكود بيظهر مرة واحدة بس لما الكارت يتعمل. احفظه أو ابعته على إيميل المستلم.",
    amount: "القيمة",
    amountError: "اكتب قيمة أكبر من صفر.",
    expires: "صالح لحد (اختياري)",
    expiresHint: "سيبه فاضي لو الكارت مالوش تاريخ انتهاء.",
    expiresError: "اختار تاريخ بعد النهارده.",
    recipientName: "اسم المستلم (اختياري)",
    recipientEmail: "إيميل المستلم (اختياري)",
    emailError: "اكتب إيميل صحيح، أو سيبه فاضي.",
    message: "رسالة للمستلم (اختياري)",
    messageHint: "بتتبعت مع الكارت. لحد ٥٠٠ حرف.",
    note: "ملاحظة لفريقك (اختياري)",
    noteHint: "فريقك بس اللي بيشوفها.",
    sendEmail: "ابعت الكود على إيميل المستلم",
    sendEmailNeedsEmail: "اكتب إيميل المستلم عشان نبعته.",
    issuing: "بنعمل الكارت…",
    issueSubmit: "اعمل الكارت",
    cancel: "إلغاء",
    issuedTitle: "كارت الهدية جاهز",
    saveCodeNow: "احفظ الكود ده دلوقتي — مش هيظهر كامل تاني",
    codeLabel: "كود كارت الهدية",
    copyCode: "انسخ الكود",
    emailedTo: "وبعتناه كمان على {email}.",
    issuedOf: "بقيمة {amount}",
    openIssued: "افتح الكارت",
    done: "تمام",
    // card page
    back: "كروت الهدايا",
    cardTitle: "كارت هدية •••• {last4}",
    balance: "الرصيد",
    ofInitial: "من {initial}",
    validUntil: "صالح لحد {date}",
    expiredOn: "انتهى يوم {date}",
    issuedOn: "اتعمل {date}",
    boughtOnOrder: "اتشترى في أوردر",
    openOrder: "افتح الأوردر",
    recipient: "المستلم",
    recipientNameLabel: "الاسم",
    recipientEmailLabel: "الإيميل",
    messageLabel: "الرسالة",
    noteLabel: "ملاحظة الفريق",
    showCode: "اعرض الكود",
    showingCode: "بنجيب الكود…",
    hideCode: "اخفي الكود",
    resend: "ابعته تاني للمستلم",
    resending: "بنبعته…",
    resent: "اتبعت تاني على {email}.",
    adjust: "عدّل الرصيد",
    disable: "وقّف الكارت",
    enable: "شغّل الكارت تاني",
    enabling: "بنشغّله…",
    disableTitle: "توقّف كارت الهدية •••• {last4}؟",
    disableBody: "مش هيتقبل في صفحة الدفع لحد ما تشغّله تاني. رصيده هيفضل زي ما هو.",
    disableConfirm: "وقّف الكارت",
    disabling: "بنوقفه…",
    disabledToast: "الكارت اتوقف.",
    enabledToast: "الكارت رجع يشتغل.",
    editDetails: "عدّل البيانات",
    history: "حركة الرصيد",
    historyHint: "كل تغيير في الرصيد، الأحدث الأول.",
    historyEmpty: "لسه مفيش حركة.",
    kind_issue: "اتعمل",
    kind_redeem: "اتصرف في أوردر",
    kind_refund: "رجع من أوردر",
    kind_adjust: "تعديل من فريقك",
    kind_hold: "محجوز لطلب",
    kind_hold_released: "اتفك الحجز",
    kind_release: "رجع للكارت",
    colWhen: "إمتى",
    colWhat: "إيه اللي حصل",
    colChange: "التغيير",
    colAfter: "الرصيد بعدها",
    afterShort: "الباقي: {amount}",
    orderLink: "الأوردر",
    disabledNotice: "الكارت ده متوقف: صفحة الدفع مش هتقبله لحد ما تشغّله تاني.",
    expiredNotice: "الكارت ده انتهى. حط له تاريخ جديد من «عدّل البيانات» عشان يشتغل تاني.",
    emptyNotice: "رصيد الكارت ده خلص. زوّده من «عدّل الرصيد».",
    // adjust dialog
    adjustTitle: "عدّل الرصيد",
    adjustDescription: "دلوقتي: {balance}",
    direction: "التعديل",
    addTo: "زوّد الرصيد",
    takeOff: "اخصم من الرصيد",
    adjustAmount: "المبلغ",
    adjustNote: "السبب (اختياري)",
    adjustNoteHint: "بيظهر في حركة الرصيد.",
    newBalance: "الرصيد الجديد: {amount}",
    tooMuch: "أقصى حاجة تقدر تخصمها {amount}.",
    adjustSave: "احفظ",
    adjustSaving: "بنحفظ…",
    adjusted: "الرصيد اتعدّل.",
    // edit dialog
    editTitle: "عدّل البيانات",
    editSave: "احفظ",
    editSaving: "بنحفظ…",
    saved: "اتحفظ.",
    noChanges: "مفيش حاجة اتغيرت.",
    // settings
    settingsTitle: "منتجات بتتباع ككروت هدايا",
    settingsHint:
      "كل قطعة بتتباع من المنتجات دي بتعمل كارت هدية بسعرها، وبيتبعت على إيميل المشتري أول ما الأوردر يتدفع أو يتسلّم.",
    settingsLoading: "بيحمّل إعداد كروت الهدايا…",
    noProductsSelected: "لسه مفيش منتجات",
    chooseProducts: "اختار المنتجات",
    changeProducts: "غيّر",
    products_one: "منتج واحد",
    products_two: "منتجين",
    products_few: "{n} منتجات",
    products_other: "{n} منتج",
    validity: "عدد أيام صلاحية الكارت اللي بيتشتري",
    validityHint: "سيبه فاضي لو مالوش تاريخ انتهاء.",
    validityError: "اكتب عدد أيام من ١ لـ ٣٦٥٠، أو سيبه فاضي.",
    validFor: "صالح لمدة {days}",
    noEnd: "الكروت اللي بتتشتري مالهاش تاريخ انتهاء",
    filterProducts: "دوّر في المنتجات",
    noCatalog: "ضيف منتج الأول، وبعدين اختاره هنا.",
    noMatchProducts: "مفيش منتجات بالاسم ده.",
    maxProducts: "لحد {max} منتج.",
    pickerTitle: "منتجات بتتباع ككروت هدايا",
    settingsSave: "احفظ",
    settingsSaving: "بنحفظ…",
    settingsSaved: "اتحفظ. الأوردرات الجديدة للمنتجات دي هتعمل كروت هدايا.",
    settingsTip: "نصيحة: اعمل منتج لكل قيمة (٢٠٠، ٥٠٠ …)، واكتب في وصفه إن الكود بيوصل على الإيميل.",
  },
} satisfies Messages;

export type GiftCardStrings = (typeof GIFT_CARD_STRINGS)["en"];

export const STATE_KEY: Record<GiftCardState, keyof GiftCardStrings> = {
  active: "state_active",
  empty: "state_empty",
  expired: "state_expired",
  disabled: "state_disabled",
};

export const STATE_TONE: Record<GiftCardState, "success" | "neutral" | "warning" | "danger"> = {
  active: "success",
  empty: "neutral",
  expired: "warning",
  disabled: "danger",
};

export const KIND_KEY: Record<GiftCardTransactionKind, keyof GiftCardStrings> = {
  issue: "kind_issue",
  redeem: "kind_redeem",
  refund: "kind_refund",
  adjust: "kind_adjust",
  hold: "kind_hold",
  hold_released: "kind_hold_released",
  release: "kind_release",
};

/** "2026-12-31" (a date field) → the end of that day on this device, as ISO; "" → null. */
export function dateFieldToIso(value: string): string | null {
  if (!value) return null;
  const d = new Date(`${value}T23:59:59`);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}

/** An ISO date → "2026-12-31" in this device's calendar, for a date field. */
export function isoToDateField(iso: string | null | undefined): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

/** Tomorrow as a date field's `min`. */
export function tomorrowDateField(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return isoToDateField(d.toISOString());
}

/** A loose email check; the API has the final word. */
export const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
