import type { Messages } from "@/i18n/LocaleContext";

/** The words of the product's photos and video (ProductImagesSection, ProductVideoSection and the tiles under ./). */
export const MEDIA_STRINGS = {
  en: {
    // Photos
    title: "Photos",
    photos_one: "1 photo",
    photos_two: "{n} photos",
    photos_few: "{n} photos",
    photos_many: "{n} photos",
    photos_other: "{n} photos",
    hint: "Drag a photo to move it. The first one is the main photo shoppers see.",
    hintTouch: "Press and hold a photo, then drag it to move it. The first one is the main photo shoppers see.",
    formats: "PNG, JPEG, GIF or WEBP. Anything over {mb} MB is made smaller before it uploads.",
    gridLabel: "Product photos",
    cover: "Main photo",
    add: "Upload photos",
    emptyTitle: "Drop photos here or tap to choose",
    emptyHint: "You can pick several at once.",
    dropHere: "Drop the photos here",
    preparing: "Preparing…",
    uploading: "Uploading…",
    uploadFailed: "Didn't upload",
    retry: "Try again",
    dismiss: "Dismiss",
    retryNamed: "Try uploading {name} again",
    dismissNamed: "Dismiss {name}",
    tile: "Photo {n} of {total}",
    tileCover: "Photo {n} of {total}, the main photo",
    menu: "Actions for photo {n}",
    makeCover: "Make it the main photo",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    remove: "Remove photo",
    removedToast: "Photo removed.",
    unsaved: "New order / photos not saved yet",
    save: "Save photos",
    savedToast: "Photos saved.",
    srRole: "movable photo",
    srInstructions:
      "Press Space or Enter to pick the photo up, move it with the arrow keys, then press Space again to put it down. Escape cancels.",
    srPicked: "Picked up photo {n} of {total}.",
    srMoved: "Now at place {n} of {total}.",
    srDropped: "Put down at place {n} of {total}.",
    srCancelled: "Cancelled. The photo is back where it was.",
    // Video
    videoTitle: "Video",
    videoHelp: "An MP4 or WebM video of the product, up to {mb} MB. It plays on the product page under the pictures.",
    videoAdd: "Upload a video",
    videoUploading: "Uploading…",
    videoPlay: "Play the video",
    videoPlayNamed: "Play video {n}",
    videoReplace: "Replace the video",
    videoRemove: "Remove video",
    videoMenu: "Actions for video {n}",
    videoTooBig: "The video is larger than {mb} MB.",
    videoWrongType: "Choose an MP4 or WebM video.",
    videoSaved: "Video saved.",
    videoReplaced: "Video replaced.",
    videoRemoved: "Video removed.",
    videoEmpty: "No video yet.",
    videoDropHere: "Drop the video here",
    videoPlayer: "Product video",
  },
  ar: {
    // الصور
    title: "الصور",
    photos_one: "صورة واحدة",
    photos_two: "صورتين",
    photos_few: "{n} صور",
    photos_many: "{n} صورة",
    photos_other: "{n} صورة",
    hint: "اسحب الصورة عشان تغيّر مكانها. أول صورة هي الرئيسية اللي العميل بيشوفها.",
    hintTouch: "دوس على الصورة شوية وبعدين اسحبها عشان تغيّر مكانها. أول صورة هي الرئيسية اللي العميل بيشوفها.",
    formats: "PNG أو JPEG أو GIF أو WEBP. أي صورة أكبر من {mb} ميجا بنصغّرها قبل ما تترفع.",
    gridLabel: "صور المنتج",
    cover: "الصورة الرئيسية",
    add: "ارفع صور",
    emptyTitle: "اسحب الصور هنا أو دوس عشان تختار",
    emptyHint: "تقدر ترفع أكتر من صورة مرة واحدة.",
    dropHere: "سيب الصور هنا",
    preparing: "بنجهّزها…",
    uploading: "بنرفعها…",
    uploadFailed: "ما اترفعتش",
    retry: "جرّب تاني",
    dismiss: "شيلها",
    retryNamed: "جرّب ترفع {name} تاني",
    dismissNamed: "شيل {name}",
    tile: "صورة {n} من {total}",
    tileCover: "صورة {n} من {total}، الصورة الرئيسية",
    menu: "إجراءات الصورة {n}",
    makeCover: "خلّيها الصورة الرئيسية",
    moveEarlier: "قدّمها",
    moveLater: "أخّرها",
    remove: "شيل الصورة",
    removedToast: "الصورة اتشالت.",
    unsaved: "ترتيب / صور جديدة لسه ما اتحفظتش",
    save: "احفظ الصور",
    savedToast: "الصور اتحفظت.",
    srRole: "صورة تتنقل",
    srInstructions: "دوس مسافة أو Enter عشان تمسك الصورة، حرّكها بالأسهم، ودوس مسافة تاني عشان تسيبها. Esc بيلغي.",
    srPicked: "مسكت الصورة {n} من {total}.",
    srMoved: "بقت في المكان {n} من {total}.",
    srDropped: "اتحطّت في المكان {n} من {total}.",
    srCancelled: "اتلغى، والصورة رجعت مكانها.",
    // الفيديو
    videoTitle: "الفيديو",
    videoHelp: "فيديو للمنتج MP4 أو WebM، لحد {mb} ميجا. بيشتغل في صفحة المنتج تحت الصور.",
    videoAdd: "ارفع فيديو",
    videoUploading: "بنرفعه…",
    videoPlay: "شغّل الفيديو",
    videoPlayNamed: "شغّل الفيديو {n}",
    videoReplace: "بدّل الفيديو",
    videoRemove: "شيل الفيديو",
    videoMenu: "إجراءات الفيديو {n}",
    videoTooBig: "الفيديو أكبر من {mb} ميجا.",
    videoWrongType: "اختار فيديو MP4 أو WebM.",
    videoSaved: "الفيديو اتحفظ.",
    videoReplaced: "الفيديو اتبدّل.",
    videoRemoved: "الفيديو اتشال.",
    videoEmpty: "مفيش فيديو لسه.",
    videoDropHere: "سيب الفيديو هنا",
    videoPlayer: "فيديو المنتج",
  },
} satisfies Messages;

export type MediaStrings = (typeof MEDIA_STRINGS)["en"];
