import type { Messages } from "@/i18n/LocaleContext";

/**
 * Offers → Price lists, the list's editor, and the hint on a customer's page
 * (handoff 205). Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const PRICE_LIST_STRINGS = {
  en: {
    // list page
    backToOffers: "Offers",
    listLabel: "Your price lists",
    openListNamed: "Open {name}",
    menuOpen: "Open the list",
    menuTurnOn: "Turn on",
    menuTurnOff: "Turn off",
    moreActions: "More actions",
    kindLabel: "Kind of list",
    scopeLabel: "Which products",
    title: "Price lists",
    description: "Lower prices for customers who carry a tag — wholesale, for one — once they sign in to your store.",
    newList: "New price list",
    emptyTitle: "No price lists yet",
    emptyHint:
      "Give your wholesale customers their own prices: add a tag such as “wholesale” to the customer, then make a price list for that tag. They see their prices as soon as they sign in.",
    colName: "List",
    colTags: "Customer tags",
    colType: "Prices",
    colScope: "On",
    colState: "Status",
    typePercent: "{percent}% off",
    typeFixed: "Fixed prices",
    scopeAll: "All products",
    scopeProducts_one: "1 product",
    scopeProducts_other: "{n} products",
    scopeVariants_one: "1 price",
    scopeVariants_other: "{n} prices",
    stateOn: "On",
    stateOff: "Off",
    toggle: "{name}: on or off",
    turnedOn: "“{name}” is on.",
    turnedOff: "“{name}” is off.",
    accountsOff: "Customer accounts are off, so nobody gets these prices: a customer has to sign in for the store to know their tags.",
    accountsOffAction: "Turn on customer accounts",
    // editor
    backToLists: "Price lists",
    newTitle: "New price list",
    editTitle: "Price list",
    basicsTitle: "Who gets these prices",
    name: "List name",
    nameHint: "Your customers see this name beside their price.",
    namePlaceholder: "Wholesale",
    nameRequired: "Write a name for the list.",
    tags: "Customer tags",
    tagsHint: "A customer with any of these tags gets this list. You add tags on the customer's page.",
    tagsPlaceholder: "wholesale",
    tagsRequired: "Add at least one tag.",
    tagCustomers_one: "“{tag}”: 1 customer",
    tagCustomers_other: "“{tag}”: {n} customers",
    tagNobody: "“{tag}”: no customer has this tag yet",
    active: "This list is on",
    activeHintOn: "Customers with its tags pay these prices once they sign in.",
    activeHintOff: "Off: everyone pays the normal prices. The list is kept as it is.",
    pricesTitle: "The prices",
    kind: "Kind of list",
    kindPercent: "Percent off",
    kindPercentHint: "One percent off every product, or off the ones you choose.",
    kindFixed: "Fixed prices",
    kindFixedHint: "Your own price for each product, and lower ones from a quantity upward.",
    kindSwitchNote: "Saving the list as “{kind}” removes what you had set the other way.",
    percent: "Percent off",
    percentHint: "From 1 to 90, off the product's normal price.",
    percentError: "Enter a whole number from 1 to 90.",
    percentUnit: "%",
    scope: "Which products",
    scopeChosen: "Products I choose",
    products: "Products",
    productsRequired: "Choose at least one product, or pick “All products”.",
    example: "For example, “{name}”: {price} becomes {yours} for these customers.",
    fixedHint: "Add a product and write its price for these customers. Add a quantity for a lower price on bigger orders.",
    addProduct: "Add a product",
    searchProducts: "Search your products",
    noMatch: "No products match.",
    alreadyAdded: "Added",
    catalogCapped: "Only your newest {n} products are listed here.",
    normalPrice: "Normal price {price}",
    fromQuantity: "From quantity",
    price: "Price",
    addTier: "Add a quantity",
    removePrice: "Remove this price",
    removeProduct: "Remove “{name}” from the list",
    copyToAll: "Use the first option's prices for all {n} options",
    copied: "The same prices are on every option now.",
    closePicker: "Close the list",
    priceRequired: "Write the price.",
    priceInvalid: "Write a valid price.",
    quantityInvalid: "A whole number from 1.",
    quantityDuplicate: "This quantity is there twice.",
    notLower: "Not lower than the normal price, so it changes nothing.",
    pricesRequired: "Add at least one product and its price.",
    tooManyPrices: "A list holds up to {max} prices. Remove some to save.",
    unknownProduct: "A product that is no longer in your store",
    pricesCount_one: "1 price",
    pricesCount_other: "{n} prices",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    created: "The price list was created.",
    fixFields: "Check the highlighted fields.",
    variant_not_in_store: "One of the products in this list is no longer in your store. Remove it and save again.",
    product_not_in_store: "One of the chosen products is no longer in your store. Untick it and save again.",
    delete: "Delete list",
    deleteTitle: "Delete “{name}”?",
    deleteHint: "Customers with its tags go back to the normal prices. Orders already placed keep the price they were placed at.",
    deleteConfirm: "Delete",
    deleted: "The price list was deleted.",
    // customer page
    customerGets: "This customer gets: {lists} prices",
    customerGetsHint_one: "Because of the tag {tags}. They pay these prices once they sign in to your store.",
    customerGetsHint_other: "Because of the tags {tags}. They pay these prices once they sign in to your store.",
    openList: "Open the price list",
    openLists: "Open price lists",
  },
  ar: {
    // list page
    backToOffers: "العروض",
    listLabel: "قوايم الأسعار بتاعتك",
    openListNamed: "افتح {name}",
    menuOpen: "افتح القايمة",
    menuTurnOn: "شغّلها",
    menuTurnOff: "وقّفها",
    moreActions: "إجراءات تانية",
    kindLabel: "نوع القايمة",
    scopeLabel: "أنهي منتجات",
    title: "قوايم الأسعار",
    description: "أسعار أقل للعملاء اللي عندهم وسم معيّن — زي عملاء الجملة — أول ما يسجّلوا دخول في متجرك.",
    newList: "قايمة أسعار جديدة",
    emptyTitle: "مفيش قوايم أسعار لسه",
    emptyHint:
      "اعمل أسعار خاصة لعملاء الجملة: ضيف وسم زي «wholesale» للعميل، وبعدين اعمل قايمة أسعار للوسم ده. العميل بيشوف أسعاره أول ما يسجّل دخول.",
    colName: "القايمة",
    colTags: "وسوم العملاء",
    colType: "الأسعار",
    colScope: "على",
    colState: "الحالة",
    typePercent: "خصم {percent}٪",
    typeFixed: "أسعار ثابتة",
    scopeAll: "كل المنتجات",
    scopeProducts_one: "منتج واحد",
    scopeProducts_two: "منتجين",
    scopeProducts_few: "{n} منتجات",
    scopeProducts_other: "{n} منتج",
    scopeVariants_one: "سعر واحد",
    scopeVariants_two: "سعرين",
    scopeVariants_few: "{n} أسعار",
    scopeVariants_other: "{n} سعر",
    stateOn: "شغّالة",
    stateOff: "متوقفة",
    toggle: "{name}: تشغيل أو إيقاف",
    turnedOn: "«{name}» بقت شغّالة.",
    turnedOff: "«{name}» اتوقفت.",
    accountsOff: "حسابات العملاء مقفولة، فمحدش هياخد الأسعار دي: العميل لازم يسجّل دخول عشان المتجر يعرف وسومه.",
    accountsOffAction: "شغّل حسابات العملاء",
    // editor
    backToLists: "قوايم الأسعار",
    newTitle: "قايمة أسعار جديدة",
    editTitle: "قايمة أسعار",
    basicsTitle: "مين ياخد الأسعار دي",
    name: "اسم القايمة",
    nameHint: "عملاءك بيشوفوا الاسم ده جنب سعرهم.",
    namePlaceholder: "جملة",
    nameRequired: "اكتب اسم للقايمة.",
    tags: "وسوم العملاء",
    tagsHint: "أي عميل عنده وسم من دول بياخد القايمة دي. الوسوم بتضيفها من صفحة العميل.",
    tagsPlaceholder: "wholesale",
    tagsRequired: "ضيف وسم واحد على الأقل.",
    tagCustomers_one: "«{tag}»: عميل واحد",
    tagCustomers_two: "«{tag}»: عميلين",
    tagCustomers_few: "«{tag}»: {n} عملاء",
    tagCustomers_other: "«{tag}»: {n} عميل",
    tagNobody: "«{tag}»: مفيش عميل عنده الوسم ده لسه",
    active: "القايمة دي شغّالة",
    activeHintOn: "العملاء اللي عندهم وسومها بيدفعوا الأسعار دي بعد ما يسجّلوا دخول.",
    activeHintOff: "متوقفة: الكل بيدفع السعر العادي. القايمة محفوظة زي ما هي.",
    pricesTitle: "الأسعار",
    kind: "نوع القايمة",
    kindPercent: "نسبة خصم",
    kindPercentHint: "نسبة خصم واحدة على كل المنتجات، أو على منتجات تختارها.",
    kindFixed: "أسعار ثابتة",
    kindFixedHint: "سعر تحدده إنت لكل منتج، وأسعار أقل كل ما الكمية تزيد.",
    kindSwitchNote: "لما تحفظ القايمة كـ«{kind}»، اللي كنت محدده بالطريقة التانية هيتشال.",
    percent: "نسبة الخصم",
    percentHint: "من ١ لـ ٩٠، من سعر المنتج العادي.",
    percentError: "اكتب رقم صحيح من ١ لـ ٩٠.",
    percentUnit: "٪",
    scope: "على أنهي منتجات",
    scopeChosen: "منتجات أختارها",
    products: "المنتجات",
    productsRequired: "اختار منتج واحد على الأقل، أو اختار «كل المنتجات».",
    example: "مثلًا «{name}»: {price} هيبقى {yours} للعملاء دول.",
    fixedHint: "ضيف منتج واكتب سعره للعملاء دول. ضيف كمية لو عايز سعر أقل للطلبات الكبيرة.",
    addProduct: "ضيف منتج",
    searchProducts: "دوّر في منتجاتك",
    noMatch: "مفيش منتجات مطابقة.",
    alreadyAdded: "متضاف",
    catalogCapped: "ظاهر هنا أحدث {n} منتج عندك بس.",
    normalPrice: "السعر العادي {price}",
    fromQuantity: "من كمية",
    price: "السعر",
    addTier: "ضيف كمية",
    removePrice: "شيل السعر ده",
    removeProduct: "شيل «{name}» من القايمة",
    copyToAll: "طبّق أسعار أول نوع على كل الأنواع ({n})",
    copied: "نفس الأسعار بقت على كل الأنواع.",
    closePicker: "اقفل القايمة",
    priceRequired: "اكتب السعر.",
    priceInvalid: "اكتب سعر صحيح.",
    quantityInvalid: "رقم صحيح من ١.",
    quantityDuplicate: "الكمية دي مكتوبة مرتين.",
    notLower: "مش أقل من السعر العادي، فمش هيغيّر حاجة.",
    pricesRequired: "ضيف منتج واحد على الأقل واكتب سعره.",
    tooManyPrices: "القايمة بتشيل لحد {max} سعر. شيل شوية عشان تحفظ.",
    unknownProduct: "منتج مبقاش موجود في متجرك",
    pricesCount_one: "سعر واحد",
    pricesCount_two: "سعرين",
    pricesCount_few: "{n} أسعار",
    pricesCount_other: "{n} سعر",
    save: "احفظ",
    saving: "بنحفظ…",
    saved: "اتحفظ.",
    created: "قايمة الأسعار اتعملت.",
    fixFields: "راجع الخانات المتعلّم عليها.",
    variant_not_in_store: "في منتج في القايمة دي مبقاش موجود في متجرك. شيله واحفظ تاني.",
    product_not_in_store: "في منتج من اللي اخترتهم مبقاش موجود في متجرك. شيل العلامة من عليه واحفظ تاني.",
    delete: "امسح القايمة",
    deleteTitle: "تمسح «{name}»؟",
    deleteHint: "العملاء اللي عندهم وسومها هيرجعوا للسعر العادي. الأوردرات اللي اتعملت قبل كده فاضلة بسعرها.",
    deleteConfirm: "امسح",
    deleted: "قايمة الأسعار اتمسحت.",
    // customer page
    customerGets: "العميل ده بياخد أسعار: {lists}",
    customerGetsHint_one: "عشان عنده الوسم {tags}. بيدفع الأسعار دي لما يسجّل دخول في متجرك.",
    customerGetsHint_two: "عشان عنده الوسمين {tags}. بيدفع الأسعار دي لما يسجّل دخول في متجرك.",
    customerGetsHint_other: "عشان عنده الوسوم {tags}. بيدفع الأسعار دي لما يسجّل دخول في متجرك.",
    openList: "افتح قايمة الأسعار",
    openLists: "افتح قوايم الأسعار",
  },
} satisfies Messages;

export type PriceListStrings = (typeof PRICE_LIST_STRINGS)["en"];
