import type { Messages } from "@/i18n/LocaleContext";

/**
 * Products → «تحديث جماعي من شيت» / Bulk update from a sheet (handoff 243,
 * with 295 and 297): the template and upload, the preview with its tabs, the
 * apply and its result, and the server's row problems said in the merchant's
 * language. Arabic is the merchant's Egyptian, with the handoff's wording.
 * Column names (sku, stock, …) stay as they are written in the sheet.
 */
export const SHEET_UPDATE_STRINGS = {
  en: {
    // entry and header
    link: "Bulk update from a sheet",
    title: "Bulk update from a sheet",
    description: "Change the stock and prices of many products at once from an Excel or CSV sheet. You see every change before anything is saved.",
    back: "Products",
    // the sheet
    sheetTitle: "Your sheet",
    sheetDescription: "One row per SKU. A blank cell leaves that value as it is.",
    col_sku: "The variant's SKU as it is in your store (required)",
    col_stock: "The new stock count",
    col_stock_change: "Units to add or take away, like 5 or -3 (not with stock on the same row)",
    col_price: "The price, like 249.50",
    col_compare_at: "The price before the discount; 0 removes it",
    col_cost: "What one unit costs you",
    limits: "A CSV or .xlsx file, up to {rows} rows and 10 MB.",
    template: "Download the template",
    chooseFile: "Choose a sheet",
    chooseAnother: "Choose another sheet",
    dropHint: "Choose your sheet, or drop the file here",
    columnsTitle: "Columns of the sheet",
    readingRows: "Reading the rows…",
    reading: "Reading {name}…",
    fileLine: "{name} · {size}",
    sizeKb: "{n} KB",
    sizeMb: "{n} MB",
    // file problems
    file_type: "The sheet has to be a CSV or an .xlsx file.",
    file_too_large: "The file is larger than 10 MB. Split it into smaller sheets.",
    file_no_sku_column: "The sheet needs a column named sku. Download the template to see the columns.",
    file_damaged: "The file is damaged — save it again or send a CSV",
    file_empty: "The file is empty.",
    file_too_many_rows: "The sheet has more than {rows} rows. Split it into smaller sheets.",
    file_unreadable: "We couldn't read this file. Save it again as a CSV and try once more.",
    // preview
    previewTitle: "What will change",
    summary: "{rows} read from the sheet.",
    rows_one: "1 row",
    rows_other: "{n} rows",
    ignoredColumns: "These columns are not updated: {list}",
    tabsLabel: "Rows of the sheet",
    tab_changes: "Changes",
    tab_unknown: "Unknown SKUs",
    tab_errors: "Errors",
    tab_failed: "Not applied",
    colRow: "Row",
    colSku: "SKU",
    colProduct: "Product",
    colStock: "Stock",
    colPrice: "Price",
    colCompareAt: "Price before discount",
    colCost: "Cost",
    colProblem: "Problem",
    change: "{from} → {to}",
    stockChangeNote: "({delta})",
    none: "None",
    unknownProduct: "Deleted product",
    belowReserved: "Below what open orders hold ({reserved})",
    noChanges: "Nothing in this sheet changes a stock count or a price.",
    noChangesWithProblems: "Nothing can be applied from this sheet. Fix the rows under the other tabs and upload it again.",
    unknownHint: "No variant in your store has these SKUs. Check how they are written.",
    errorsHint: "These rows are skipped. Fix them in the sheet and upload it again to apply them.",
    tabEmpty: "Nothing here.",
    stockChangeTiming: "Rows with stock_change are applied to the stock at that moment, so the final count can differ from the preview if orders come in meanwhile.",
    // apply
    readyToApply: "Review the changes, then apply them.",
    apply_one: "Apply 1 change",
    apply_other: "Apply {n} changes",
    applying: "Applying…",
    stillApplying: "Still applying — wait a few seconds",
    checkAgain: "Check the sheet again",
    applyUnknown: "We couldn't confirm that the update finished. Check the sheet again to see what is still different before applying.",
    // result
    resultTitle: "Result",
    applied_one: "1 variant updated.",
    applied_other: "{n} variants updated.",
    appliedNone: "Nothing was updated.",
    resultSkipped: "The rows below were not applied.",
    failedHint: "These rows were fine in the sheet but could not be saved.",
    another: "Update another sheet",
    backToProducts: "Back to products",
    // row problems (the server's, said here)
    problem_no_sku: "This row has no SKU",
    problem_duplicate_row: "This SKU is on an earlier row too",
    problem_shared_sku: "Several variants share this SKU",
    problem_stock_and_change: "Use stock or stock_change, not both",
    problem_bad_stock: "stock must be a whole number, 0 or more",
    problem_bad_stock_change: "stock_change must be a whole number other than 0, like 5 or -3",
    problem_below_zero: "Stock would go below 0",
    problem_below_zero_now: "Stock would go below 0 (it is {now} now)",
    problem_bad_price: "Type the price like 249.50",
    problem_bad_compare_at: "Type the price before discount like 249.50",
    problem_bad_cost: "Type the cost like 249.50",
    problem_zero_price: "The price can't be 0",
    problem_location_short: "Only {n} at {location}; correct the other locations' counts first",
  },
  ar: {
    link: "تحديث جماعي من شيت",
    title: "تحديث جماعي من شيت",
    description: "غيّر مخزون وأسعار منتجات كتير مرة واحدة من شيت Excel أو CSV. هتشوف كل تغيير قبل ما أي حاجة تتحفظ.",
    back: "المنتجات",
    sheetTitle: "الشيت بتاعك",
    sheetDescription: "صف لكل SKU. الخانة الفاضية بتسيب القيمة زي ما هي.",
    col_sku: "كود الصنف (SKU) زي ما هو في متجرك (مطلوب)",
    col_stock: "العدد الجديد في المخزون",
    col_stock_change: "زيادة أو نقص في القطع، زي 5 أو \u200E-3 (مش مع stock في نفس الصف)",
    col_price: "السعر، زي 249.50",
    col_compare_at: "السعر قبل الخصم، و0 بيشيله",
    col_cost: "القطعة بتكلفك كام",
    limits: "ملف CSV أو \u200E.xlsx، لحد {rows} صف و١٠ ميجا.",
    template: "نزّل القالب",
    chooseFile: "اختار شيت",
    chooseAnother: "اختار شيت تاني",
    dropHint: "اختار الشيت بتاعك، أو اسحب الملف هنا",
    columnsTitle: "أعمدة الشيت",
    readingRows: "بنقرا الصفوف…",
    reading: "بنقرا {name}…",
    fileLine: "{name} · {size}",
    sizeKb: "{n} كيلوبايت",
    sizeMb: "{n} ميجا",
    file_type: "الشيت لازم يكون ملف CSV أو \u200E.xlsx.",
    file_too_large: "الملف أكبر من ١٠ ميجا. قسّمه على شيتات أصغر.",
    file_no_sku_column: "الشيت محتاج عمود اسمه sku. نزّل القالب عشان تشوف الأعمدة.",
    file_damaged: "الملف بايظ — احفظه تاني أو ابعته CSV",
    file_empty: "الملف فاضي.",
    file_too_many_rows: "الشيت فيه أكتر من {rows} صف. قسّمه على شيتات أصغر.",
    file_unreadable: "معرفناش نقرا الملف ده. احفظه تاني كـ CSV وجرّب.",
    previewTitle: "اللي هيتغير",
    summary: "اتقرا {rows} من الشيت.",
    rows_one: "صف واحد",
    rows_two: "صفين",
    rows_few: "{n} صفوف",
    rows_other: "{n} صف",
    ignoredColumns: "الأعمدة دي مش هتتغير: {list}",
    tabsLabel: "صفوف الشيت",
    tab_changes: "التغييرات",
    tab_unknown: "SKU مش موجود",
    tab_errors: "أخطاء",
    tab_failed: "متطبّقش",
    colRow: "الصف",
    colSku: "SKU",
    colProduct: "المنتج",
    colStock: "المخزون",
    colPrice: "السعر",
    colCompareAt: "السعر قبل الخصم",
    colCost: "التكلفة",
    colProblem: "المشكلة",
    change: "{from} ← {to}",
    stockChangeNote: "({delta})",
    none: "مفيش",
    unknownProduct: "منتج محذوف",
    belowReserved: "الكمية أقل من المحجوز لأوردرات مفتوحة ({reserved})",
    noChanges: "مفيش حاجة في الشيت ده بتغيّر مخزون أو سعر.",
    noChangesWithProblems: "مفيش حاجة تتطبّق من الشيت ده. صلّح الصفوف اللي في التابات التانية وارفعه تاني.",
    unknownHint: "مفيش صنف في متجرك بالـ SKU دي. راجع كتابتها.",
    errorsHint: "الصفوف دي هتتساب. صلّحها في الشيت وارفعه تاني عشان تتطبّق.",
    tabEmpty: "مفيش حاجة هنا.",
    stockChangeTiming: "الصفوف اللي فيها stock_change بتتطبّق على المخزون وقت التنفيذ، فالعدد النهائي ممكن يختلف عن المعاينة لو جت أوردرات في النص.",
    readyToApply: "راجع التغييرات، وبعدها طبّقها.",
    apply_one: "طبّق تغيير واحد",
    apply_two: "طبّق تغييرين",
    apply_few: "طبّق {n} تغييرات",
    apply_other: "طبّق {n} تغيير",
    applying: "بنطبّق…",
    stillApplying: "لسه بيتنفذ — استنى ثواني",
    checkAgain: "راجع الشيت تاني",
    applyUnknown: "معرفناش نتأكد إن التحديث خلص. راجع الشيت تاني عشان تشوف إيه اللي لسه مختلف قبل ما تطبّق.",
    resultTitle: "النتيجة",
    applied_one: "صنف واحد اتحدّث.",
    applied_two: "صنفين اتحدّثوا.",
    applied_few: "{n} أصناف اتحدّثت.",
    applied_other: "{n} صنف اتحدّث.",
    appliedNone: "مفيش حاجة اتحدّثت.",
    resultSkipped: "الصفوف اللي تحت متطبّقتش.",
    failedHint: "الصفوف دي كانت سليمة في الشيت بس متحفظتش.",
    another: "حدّث شيت تاني",
    backToProducts: "ارجع للمنتجات",
    problem_no_sku: "الصف ده من غير SKU",
    problem_duplicate_row: "SKU مكرر في الشيت",
    problem_shared_sku: "فيه أكتر من صنف بنفس الـ SKU",
    problem_stock_and_change: "استخدم stock أو stock_change مش الاتنين",
    problem_bad_stock: "stock لازم رقم صحيح، صفر أو أكتر",
    problem_bad_stock_change: "stock_change لازم رقم صحيح غير الصفر، زي 5 أو \u200E-3",
    problem_below_zero: "المخزون هيبقى أقل من صفر",
    problem_below_zero_now: "المخزون هيبقى أقل من صفر (هو {now} دلوقتي)",
    problem_bad_price: "اكتب السعر زي 249.50",
    problem_bad_compare_at: "اكتب السعر قبل الخصم زي 249.50",
    problem_bad_cost: "اكتب التكلفة زي 249.50",
    problem_zero_price: "السعر مينفعش يبقى صفر",
    problem_location_short: "فيه {n} بس في {location}، صحّح أعداد المخازن التانية الأول",
  },
} satisfies Messages;

export type SheetUpdateStrings = Record<keyof (typeof SHEET_UPDATE_STRINGS)["en"], string>;
