import type { Messages } from "@/i18n/LocaleContext";

/**
 * Wording for Money → Ad accounts and the campaign controls on the Ad spend
 * page (handoff 261). Read with `useT(AD_ACCOUNT_STRINGS)`.
 */
export const AD_ACCOUNT_STRINGS = {
  en: {
    title: "Ad accounts",
    description: "Connect your ad platforms: their spend comes in by itself, and you can pause a campaign or change its budget from here.",
    back: "Ad spend",
    open: "Ad accounts",
    syncNow: "Sync now",
    syncing: "Syncing…",
    syncedNone: "Sync finished. No new spend came in.",
    synced: "Sync finished: {rows}.",
    rows_one: "1 spend line updated",
    rows_other: "{n} spend lines updated",
    syncFailed: "Some accounts could not be synced. The reason is on each one below.",
    syncNoAccounts: "Connect an ad account first.",
    connectionsTitle: "Connected",
    connectTitle: "Connect an ad platform",
    connectDesc: "Pick the platform and enter its keys. The keys are saved sealed and never shown again.",
    reaches: "Reaches",
    connect: "Connect",
    reconnect: "Reconnect",
    connecting: "Connecting…",
    connectDialogTitle: "Connect {name}",
    noKeys: "This one needs no keys: it is a test connection that reaches no real ad account.",
    field_accessToken: "Access token",
    fieldRequired: "Required",
    connected: "{name} is connected. Now pick the accounts to follow.",
    credentialsRejected: "The ad platform did not accept these keys. Check them and try again.",
    pickTitle: "Pick the accounts to follow",
    pickHint: "Only the accounts you pick are synced, and only their campaigns can be paused or re-budgeted from here.",
    noAccounts: "No ad accounts were found with these keys.",
    savePick: "Save",
    pickSaved: "Accounts saved.",
    disconnect: "Disconnect",
    disconnectTitle: "Disconnect {name}?",
    disconnectBody: "Its spend stops coming in and its campaigns can no longer be controlled from here. The spend already recorded stays.",
    disconnecting: "Disconnecting…",
    disconnected: "{name} is disconnected.",
    status_connected: "Connected",
    status_error: "Needs attention",
    status_disconnected: "Disconnected",
    lastSync: "Last sync {when}",
    lastError: "Last sync failed:",
    emptyTitle: "No ad platform can be connected yet",
    emptyDesc: "Until one is available, type your spend in or import the CSV your ads manager exports.",
    addSpend: "Go to ad spend",
    // Campaign controls
    controls: "Controls",
    pause: "Pause",
    resume: "Resume",
    budget: "Daily budget",
    budgetIs: "Daily budget {amount}",
    statusActive: "Running",
    statusPaused: "Paused",
    lastSet: "Changed from here {when}",
    confirmNote: "This changes it on the ad platform",
    pauseTitle: "Pause “{name}”?",
    resumeTitle: "Resume “{name}”?",
    budgetTitle: "Daily budget for “{name}”",
    account: "Ad account",
    budgetInvalid: "Enter an amount above zero",
    pausedToast: "Campaign paused.",
    resumedToast: "Campaign is running again.",
    budgetSaved: "Daily budget changed.",
    refused: "The ad platform refused the change.",
    unreachable: "We couldn't reach the ad platform. Try again in a moment.",
    notPicked: "Pick this ad account on the Ad accounts page first.",
    working: "Working…",
  },
  ar: {
    title: "حسابات الإعلانات",
    description: "اربط منصات الإعلانات بتاعتك: مصاريفها تيجي لوحدها، وتقدر توقف حملة أو تغيّر ميزانيتها من هنا.",
    back: "مصاريف الإعلانات",
    open: "حسابات الإعلانات",
    syncNow: "زامن دلوقتي",
    syncing: "بنزامن…",
    syncedNone: "المزامنة خلصت. مفيش مصاريف جديدة.",
    synced: "المزامنة خلصت: {rows}.",
    rows_one: "اتحدّث سطر مصاريف واحد",
    rows_two: "اتحدّث سطرين مصاريف",
    rows_few: "اتحدّثت {n} سطور مصاريف",
    rows_other: "اتحدّث {n} سطر مصاريف",
    syncFailed: "فيه حسابات معرفناش نزامنها. السبب مكتوب على كل حساب تحت.",
    syncNoAccounts: "اربط حساب إعلانات الأول.",
    connectionsTitle: "المربوط",
    connectTitle: "اربط منصة إعلانات",
    connectDesc: "اختار المنصة واكتب المفاتيح بتاعتها. المفاتيح بتتحفظ مقفولة ومش بتظهر تاني.",
    reaches: "بتوصل لـ",
    connect: "اربط",
    reconnect: "اربط تاني",
    connecting: "بنربط…",
    connectDialogTitle: "ربط {name}",
    noKeys: "ده مش محتاج مفاتيح: ربط تجريبي مش بيوصل لحساب إعلانات حقيقي.",
    field_accessToken: "رمز الوصول (Access token)",
    fieldRequired: "مطلوب",
    connected: "اتربط {name}. اختار دلوقتي الحسابات اللي تتابعها.",
    credentialsRejected: "منصة الإعلانات مقبلتش المفاتيح دي. راجعها وجرّب تاني.",
    pickTitle: "اختار الحسابات اللي تتابعها",
    pickHint: "الحسابات اللي تختارها بس هي اللي بتتزامن، وحملاتها بس اللي تقدر توقفها أو تغيّر ميزانيتها من هنا.",
    noAccounts: "ملقيناش حسابات إعلانات بالمفاتيح دي.",
    savePick: "حفظ",
    pickSaved: "اتحفظت الحسابات.",
    disconnect: "فصل",
    disconnectTitle: "تفصل {name}؟",
    disconnectBody: "مصاريفه هتبطّل تيجي ومش هتقدر تتحكم في حملاته من هنا. المصاريف اللي اتسجلت قبل كده هتفضل.",
    disconnecting: "بنفصل…",
    disconnected: "اتفصل {name}.",
    status_connected: "مربوط",
    status_error: "فيه مشكلة",
    status_disconnected: "مفصول",
    lastSync: "آخر مزامنة {when}",
    lastError: "آخر مزامنة فشلت:",
    emptyTitle: "لسه مفيش منصة إعلانات تتربط",
    emptyDesc: "لحد ما واحدة تبقى متاحة، اكتب مصاريفك بإيدك أو استورد ملف الـ CSV من مدير الإعلانات.",
    addSpend: "روح لمصاريف الإعلانات",
    controls: "التحكم",
    pause: "إيقاف",
    resume: "تشغيل",
    budget: "الميزانية اليومية",
    budgetIs: "الميزانية اليومية {amount}",
    statusActive: "شغّالة",
    statusPaused: "متوقفة",
    lastSet: "اتغيّرت من هنا {when}",
    confirmNote: "هيتغيّر على المنصة نفسها",
    pauseTitle: "توقف حملة «{name}»؟",
    resumeTitle: "تشغّل حملة «{name}»؟",
    budgetTitle: "الميزانية اليومية لحملة «{name}»",
    account: "الحساب الإعلاني",
    budgetInvalid: "اكتب مبلغ أكبر من صفر",
    pausedToast: "الحملة اتوقفت.",
    resumedToast: "الحملة اشتغلت تاني.",
    budgetSaved: "الميزانية اليومية اتغيّرت.",
    refused: "منصة الإعلانات رفضت التغيير.",
    unreachable: "معرفناش نوصل لمنصة الإعلانات. جرّب تاني بعد شوية.",
    notPicked: "اختار الحساب الإعلاني ده من صفحة حسابات الإعلانات الأول.",
    working: "ثانية واحدة…",
  },
} satisfies Messages;

export type AdAccountText = Record<keyof (typeof AD_ACCOUNT_STRINGS)["en"], string>;
