/**
 * Locale tables for the ads pages (AdsPage, CampaignDetailPage, adsShared).
 * Placeholders use `{name}` and are filled with `fmt()` / `fmtNodes()`.
 */
import type { Messages } from "@/i18n/LocaleContext";

/** Labels shared by several ads screens (table headers, metric names, enums). */
export const ADS_COMMON = {
  en: {
    campaign: "Campaign",
    spend: "Spend",
    orders: "Orders",
    confPct: "Conf %",
    delivPct: "Deliv %",
    cpo: "CPO",
    cpco: "CPCO",
    cpd: "CPD",
    cpc: "CPC",
    ctr: "CTR",
    roas: "ROAS",
    netProfit: "Net profit",
    net: "Net",
    verdict: "Verdict",
    tipConf: "Confirmation rate",
    tipDeliv: "Delivery rate",
    tipCpo: "Cost per order",
    tipCpco: "Cost per confirmed order",
    tipCpd: "Cost per delivered order",
    tipCpc: "Cost per click",
    tipCtr: "Click-through rate",
    tipRoas: "Delivered revenue ÷ spend",
    statusActive: "Active",
    statusPaused: "Paused",
    statusEnded: "Ended",
    accConnected: "Connected",
    accTokenExpired: "Token expired",
    accDisconnected: "Disconnected",
    fmtVideo: "Video",
    fmtImage: "Image",
    fmtCarousel: "Carousel",
    objConversions: "Conversions",
    objTraffic: "Traffic",
    objLeads: "Leads",
    profitPage: "Profit page",
    noVerdict: "No verdict yet",
  },
  ar: {
    campaign: "الحملة",
    spend: "الإنفاق",
    orders: "الطلبات",
    confPct: "التأكيد %",
    delivPct: "التسليم %",
    cpo: "CPO",
    cpco: "CPCO",
    cpd: "CPD",
    cpc: "CPC",
    ctr: "CTR",
    roas: "ROAS",
    netProfit: "صافي الربح",
    net: "الصافي",
    verdict: "القرار",
    tipConf: "معدل التأكيد",
    tipDeliv: "معدل التسليم",
    tipCpo: "تكلفة الطلب",
    tipCpco: "تكلفة الطلب المؤكَّد",
    tipCpd: "تكلفة الطلب المسلَّم",
    tipCpc: "تكلفة النقرة",
    tipCtr: "نسبة النقر إلى الظهور",
    tipRoas: "العائد الحقيقي على الإنفاق: إيراد المسلَّم ÷ الإنفاق",
    statusActive: "نشطة",
    statusPaused: "متوقفة",
    statusEnded: "منتهية",
    accConnected: "متصل",
    accTokenExpired: "انتهت صلاحية الربط",
    accDisconnected: "غير متصل",
    fmtVideo: "فيديو",
    fmtImage: "صورة",
    fmtCarousel: "دوّار",
    objConversions: "التحويلات",
    objTraffic: "الزيارات",
    objLeads: "العملاء المحتملون",
    profitPage: "صفحة الأرباح",
    noVerdict: "لا يوجد قرار بعد",
  },
} satisfies Messages;

export const ADS_PAGE = {
  en: {
    title: "Ads & media buying",
    description: "Every campaign measured on what a COD business actually keeps: cost per delivered order and net profit, not platform ROAS.",
    kpiSpendHint: "Across {n} ad accounts",
    kpiOrdersHint: "Placed, before confirmation",
    kpiCpco: "CPCO",
    kpiCpcoHint: "Spend ÷ confirmed orders",
    kpiCpd: "CPD",
    kpiCpdHint: "Spend ÷ delivered orders",
    kpiRoas: "Real ROAS",
    kpiRoasHint: "Delivered revenue only ÷ spend",
    kpiNetHint: "Revenue − spend − cost of delivered",
    chartTitle: "Spend vs revenue vs net profit",
    chartDesc: "Daily, summed across campaigns. Revenue counts delivered orders only.",
    seriesSpend: "Ad spend",
    seriesRevenue: "Delivered revenue",
    campaignsTitle: "Campaigns",
    campaignsDesc: "Last 30 days. Click a row to drill into ad sets and creatives.",
    selectedCount: "{n} selected",
    pauseSelected: "Pause selected",
    activateSelected: "Activate selected",
    searchPlaceholder: "Search campaigns or products",
    allPlatforms: "All platforms",
    allStatuses: "All statuses",
    allProducts: "All products",
    emptyTitle: "No campaigns match",
    emptyDesc: "Try clearing the filters or connect an ad account to import campaigns.",
    selectAll: "Select all",
    selectRow: "Select {name}",
    colBudget: "Budget/day",
    colBe: "BE CPD",
    tipBudget: "Daily budget",
    tipBe: "Break-even cost per delivered order",
    noProduct: "No product linked",
    verdictLegend: "Verdict: CPD below 80% of break-even → {scale}, 80–100% → {hold}, above break-even → {kill}. Break-even comes from each product's cost assumptions on the {profitLink}.",
    rulesTitle: "Rules",
    rulesDesc: "Automations that act on your campaigns using confirmation and delivery data the ad platforms never see.",
    rulePauseTitle: "Pause ad set if CPD > break-even for 2 days",
    rulePauseDesc: "Checks every morning at 09:00. Ad sets whose cost per delivered order exceeds the product's break-even CPD on two consecutive days are paused on the platform.",
    ruleScaleTitle: "Increase budget 20% if ROAS > 3 and CPD < 70% of break-even",
    ruleScaleDesc: "Once per day, capped at 2 increases per campaign per week so the algorithm has time to re-learn.",
    ruleNotifyTitle: "Notify on WhatsApp if spend > 5,000 EGP with 0 confirmed orders",
    ruleNotifyDesc: "Sends a WhatsApp alert to the workspace owner — usually a broken pixel, a dead landing page or a confirmation team backlog.",
    toastActivatedOne: "1 campaign activated.",
    toastActivatedMany: "{n} campaigns activated.",
    toastPausedOne: "1 campaign paused.",
    toastPausedMany: "{n} campaigns paused.",
    toastBudget: "Daily budget updated.",
    toastReconnected: "Ad account reconnected.",
    budgetEditTitle: "Click to edit daily budget",
    creativesCount: "· {n} creatives",
    colAdSetCreative: "Ad set / creative",
    drillNote: "Ad set and creative net profit uses the campaign's average cost per delivered order.",
    openCampaign: "Open campaign",
    connectTitle: "Connect ad account",
    connectDesc: "ZIMOS reads spend, impressions and clicks from the platform and matches them to your orders via utm_campaign, fbclid and ttclid.",
    connecting: "Connecting…",
    continueWith: "Continue with {platform}",
    step1: "1. You'll be redirected to {platform} to sign in and pick an ad account.",
    step2: "2. ZIMOS asks for read access to ads insights and write access to pause / resume and change budgets.",
    step3: "3. Spend syncs every 15 minutes; orders are attributed by click id and UTM.",
    demoNote: "Demo mode: this creates a mock account locally. No real OAuth call is made.",
    toastConnected: "{platform} ad account connected.",
    spendToday: "Spend today",
    reconnect: "Reconnect",
    synced: "Synced {time}",
    never: "never",
  },
  ar: {
    title: "الإعلانات وشراء الوسائط",
    description: "كل حملة تُقاس بما يتبقّى فعلًا لتاجر الدفع عند الاستلام: تكلفة الطلب المسلَّم وصافي الربح، لا عائد المنصة على الإنفاق.",
    kpiSpendHint: "عبر {n} حسابات إعلانية",
    kpiOrdersHint: "مُسجَّلة، قبل التأكيد",
    kpiCpco: "تكلفة الطلب المؤكَّد (CPCO)",
    kpiCpcoHint: "الإنفاق ÷ الطلبات المؤكَّدة",
    kpiCpd: "تكلفة الطلب المسلَّم (CPD)",
    kpiCpdHint: "الإنفاق ÷ الطلبات المسلَّمة",
    kpiRoas: "العائد الحقيقي على الإنفاق",
    kpiRoasHint: "إيراد الطلبات المسلَّمة فقط ÷ الإنفاق",
    kpiNetHint: "الإيراد − الإنفاق − تكلفة الطلبات المسلَّمة",
    chartTitle: "الإنفاق مقابل الإيراد مقابل صافي الربح",
    chartDesc: "يوميًا، مجمَّعًا لكل الحملات. يُحتسب الإيراد من الطلبات المسلَّمة فقط.",
    seriesSpend: "الإنفاق الإعلاني",
    seriesRevenue: "إيراد الطلبات المسلَّمة",
    campaignsTitle: "الحملات",
    campaignsDesc: "آخر 30 يومًا. انقر على أي صف لعرض المجموعات الإعلانية والإعلانات.",
    selectedCount: "تم تحديد {n}",
    pauseSelected: "أوقف المحدَّد",
    activateSelected: "فعّل المحدَّد",
    searchPlaceholder: "ابحث في الحملات أو المنتجات",
    allPlatforms: "كل المنصات",
    allStatuses: "كل الحالات",
    allProducts: "كل المنتجات",
    emptyTitle: "لا توجد حملات مطابقة",
    emptyDesc: "جرّب مسح عوامل التصفية أو اربط حسابًا إعلانيًا لاستيراد الحملات.",
    selectAll: "تحديد الكل",
    selectRow: "تحديد {name}",
    colBudget: "الميزانية/يوم",
    colBe: "CPD التعادل",
    tipBudget: "الميزانية اليومية",
    tipBe: "أقصى تكلفة للطلب المسلَّم عند نقطة التعادل",
    noProduct: "لا يوجد منتج مرتبط",
    verdictLegend: "القرار: تكلفة الطلب المسلَّم أقل من 80% من نقطة التعادل ← {scale}، ومن 80 إلى 100% ← {hold}، وأعلى من نقطة التعادل ← {kill}. تُحسب نقطة التعادل من افتراضات تكلفة كل منتج في {profitLink}.",
    rulesTitle: "القواعد الآلية",
    rulesDesc: "أتمتة تعمل على حملاتك باستخدام بيانات التأكيد والتسليم التي لا تراها المنصات الإعلانية.",
    rulePauseTitle: "أوقف المجموعة الإعلانية إذا تجاوزت تكلفة الطلب المسلَّم نقطة التعادل لمدة يومين",
    rulePauseDesc: "يتم الفحص كل صباح الساعة 09:00. تُوقَف على المنصة المجموعات الإعلانية التي تتجاوز فيها تكلفة الطلب المسلَّم نقطة تعادل المنتج ليومين متتاليين.",
    ruleScaleTitle: "زد الميزانية 20% إذا كان ROAS أعلى من 3 وتكلفة الطلب المسلَّم أقل من 70% من نقطة التعادل",
    ruleScaleDesc: "مرة واحدة يوميًا، وبحد أقصى زيادتين لكل حملة أسبوعيًا ليأخذ الخوارزم وقته في إعادة التعلّم.",
    ruleNotifyTitle: "نبّهني على WhatsApp إذا تجاوز الإنفاق 5,000 ج.م بدون أي طلب مؤكَّد",
    ruleNotifyDesc: "يُرسل تنبيهًا على WhatsApp لمالك مساحة العمل — والسبب غالبًا بكسل معطَّل أو صفحة هبوط لا تعمل أو تراكم لدى فريق التأكيد.",
    toastActivatedOne: "تم تفعيل حملة واحدة.",
    toastActivatedMany: "تم تفعيل الحملات المحدَّدة ({n}).",
    toastPausedOne: "تم إيقاف حملة واحدة.",
    toastPausedMany: "تم إيقاف الحملات المحدَّدة ({n}).",
    toastBudget: "تم تحديث الميزانية اليومية.",
    toastReconnected: "تمت إعادة ربط الحساب الإعلاني.",
    budgetEditTitle: "انقر لتعديل الميزانية اليومية",
    creativesCount: "· {n} إعلانات",
    colAdSetCreative: "المجموعة الإعلانية / الإعلان",
    drillNote: "صافي ربح المجموعات الإعلانية والإعلانات محسوب بمتوسط تكلفة الطلب المسلَّم للحملة.",
    openCampaign: "فتح الحملة",
    connectTitle: "ربط حساب إعلاني",
    connectDesc: "يقرأ ZIMOS الإنفاق ومرات الظهور والنقرات من المنصة ويطابقها مع طلباتك عبر utm_campaign وfbclid وttclid.",
    connecting: "جارٍ الربط…",
    continueWith: "المتابعة عبر {platform}",
    step1: "1. سيتم تحويلك إلى {platform} لتسجيل الدخول واختيار الحساب الإعلاني.",
    step2: "2. يطلب ZIMOS صلاحية قراءة إحصاءات الإعلانات وصلاحية الإيقاف / الاستئناف وتعديل الميزانيات.",
    step3: "3. يُزامَن الإنفاق كل 15 دقيقة، وتُنسب الطلبات عبر معرّف النقرة وUTM.",
    demoNote: "وضع تجريبي: يُنشئ هذا حسابًا وهميًا محليًا دون أي اتصال OAuth حقيقي.",
    toastConnected: "تم ربط حساب {platform} الإعلاني.",
    spendToday: "إنفاق اليوم",
    reconnect: "إعادة الربط",
    synced: "آخر مزامنة {time}",
    never: "لم تتم بعد",
  },
} satisfies Messages;

export const CAMPAIGN_PAGE = {
  en: {
    notFoundTitle: "Campaign not found",
    notFoundDesc: "It may have been removed from the ad account.",
    backToAds: "Back to ads",
    adsTitle: "Ads & media buying",
    descriptionLine: "{objective} · daily budget {budget} · last 30 days",
    spendHint: "{n} impressions",
    cpm: "CPM",
    cpmHint: "Per 1,000 impressions",
    ctr: "CTR",
    ctrHint: "CPC {v}",
    landingRate: "Landing view rate",
    landingRateHint: "Landing views ÷ clicks",
    atcRate: "ATC rate",
    atcRateHint: "Add to cart ÷ landing views",
    checkoutRate: "Checkout rate",
    checkoutRateHint: "Checkouts ÷ add to cart",
    cr: "CR",
    crHint: "Orders ÷ clicks",
    cpo: "CPO",
    cpoHint: "{n} orders placed",
    cpco: "CPCO",
    cpcoHint: "Confirmation {v}",
    cpd: "CPD",
    cpdHint: "Delivery {d} · RTO {r}",
    roas: "Real ROAS",
    roasHintBe: "Break-even {v}",
    roasHint: "Delivered revenue ÷ spend",
    netHint: "Margin {v}",
    funnelTitle: "Full funnel",
    funnelDesc: "From impression to cash in hand. Step % is relative to the previous stage.",
    stImpressions: "Impressions",
    stClicks: "Clicks",
    stLanding: "Landing views",
    stAtc: "Add to cart",
    stCheckout: "Checkout",
    stOrders: "Orders",
    stConfirmed: "Confirmed",
    stDelivered: "Delivered",
    beTitle: "Break-even calculator",
    beDesc: "Cost stack for {product}. Edit the assumptions on the {profitLink}.",
    sellingPrice: "Selling price",
    cogs: "COGS",
    shipping: "Shipping",
    carrierFee: "Carrier / COD fee",
    paymentFee: "Payment fee",
    packaging: "Packaging",
    expectedReturn: "Expected return cost ({cost} × {pct} RTO)",
    maxCpdBe: "= Max CPD at 0% margin (break-even)",
    targetMargin: "Target net margin",
    maxCpd: "Max CPD",
    minRoas: "Min ROAS",
    thisCpd: "This campaign's CPD:",
    noProductTitle: "No product linked",
    noProductDesc: "Link this campaign to a product with cost assumptions to get a break-even CPD.",
    dailyTitle: "Daily performance",
    dailyDesc: "Spend, orders and delivered revenue per day.",
    revenue: "Revenue",
    ordersFmt: "{n} orders",
    colDate: "Date",
    adSetsTitle: "Ad sets & creatives",
    adSetsDesc: "Winner = lowest CPD in the ad set, Kill = highest. Net profit uses the campaign's average cost per delivered order.",
    audience: "Audience: {v}",
    winner: "Winner",
  },
  ar: {
    notFoundTitle: "الحملة غير موجودة",
    notFoundDesc: "ربما تم حذفها من الحساب الإعلاني.",
    backToAds: "العودة إلى الإعلانات",
    adsTitle: "الإعلانات وشراء الوسائط",
    descriptionLine: "{objective} · الميزانية اليومية {budget} · آخر 30 يومًا",
    spendHint: "{n} مرة ظهور",
    cpm: "تكلفة الألف ظهور (CPM)",
    cpmHint: "لكل 1,000 مرة ظهور",
    ctr: "نسبة النقر (CTR)",
    ctrHint: "تكلفة النقرة {v}",
    landingRate: "معدل مشاهدة صفحة الهبوط",
    landingRateHint: "مشاهدات صفحة الهبوط ÷ النقرات",
    atcRate: "معدل الإضافة إلى السلة",
    atcRateHint: "الإضافة إلى السلة ÷ مشاهدات صفحة الهبوط",
    checkoutRate: "معدل بدء الدفع",
    checkoutRateHint: "بدء الدفع ÷ الإضافة إلى السلة",
    cr: "معدل التحويل (CR)",
    crHint: "الطلبات ÷ النقرات",
    cpo: "تكلفة الطلب (CPO)",
    cpoHint: "{n} طلب مُسجَّل",
    cpco: "تكلفة الطلب المؤكَّد (CPCO)",
    cpcoHint: "معدل التأكيد {v}",
    cpd: "تكلفة الطلب المسلَّم (CPD)",
    cpdHint: "معدل التسليم {d} · المرتجعات {r}",
    roas: "العائد الحقيقي على الإنفاق",
    roasHintBe: "نقطة التعادل {v}",
    roasHint: "إيراد المسلَّم ÷ الإنفاق",
    netHint: "الهامش {v}",
    funnelTitle: "مسار التحويل الكامل",
    funnelDesc: "من الظهور حتى تحصيل النقدية. نسبة كل مرحلة محسوبة من المرحلة السابقة.",
    stImpressions: "مرات الظهور",
    stClicks: "النقرات",
    stLanding: "مشاهدات صفحة الهبوط",
    stAtc: "الإضافة إلى السلة",
    stCheckout: "بدء الدفع",
    stOrders: "الطلبات",
    stConfirmed: "المؤكَّدة",
    stDelivered: "المسلَّمة",
    beTitle: "حاسبة نقطة التعادل",
    beDesc: "هيكل تكاليف {product}. عدّل الافتراضات في {profitLink}.",
    sellingPrice: "سعر البيع",
    cogs: "تكلفة البضاعة",
    shipping: "الشحن",
    carrierFee: "رسوم شركة الشحن / التحصيل",
    paymentFee: "رسوم الدفع",
    packaging: "التغليف",
    expectedReturn: "تكلفة المرتجعات المتوقعة ({cost} × {pct} مرتجعات)",
    maxCpdBe: "= أقصى تكلفة للطلب المسلَّم بهامش 0% (نقطة التعادل)",
    targetMargin: "هامش صافي الربح المستهدف",
    maxCpd: "أقصى CPD",
    minRoas: "أدنى ROAS",
    thisCpd: "تكلفة الطلب المسلَّم لهذه الحملة:",
    noProductTitle: "لا يوجد منتج مرتبط",
    noProductDesc: "اربط هذه الحملة بمنتج له افتراضات تكلفة لحساب نقطة التعادل.",
    dailyTitle: "الأداء اليومي",
    dailyDesc: "الإنفاق والطلبات وإيراد المسلَّم لكل يوم.",
    revenue: "الإيراد",
    ordersFmt: "{n} طلب",
    colDate: "التاريخ",
    adSetsTitle: "المجموعات الإعلانية والإعلانات",
    adSetsDesc: "الأفضل = أقل تكلفة طلب مسلَّم في المجموعة، وأوقف = الأعلى. صافي الربح محسوب بمتوسط تكلفة الطلب المسلَّم للحملة.",
    audience: "الجمهور: {v}",
    winner: "الأفضل",
  },
} satisfies Messages;
