import type { Messages } from "@/i18n/LocaleContext";

/** Wording for the Ad spend page: the lists, the previews, the add and import sheets. Read with `useT(ADS_STRINGS)`. */
export const ADS_STRINGS = {
  en: {
    title: "Ad spend",
    description: "Your ad spend against the orders it really delivered: real cost per delivered order and real return on spend.",
    addSpend: "Add spend",
    importCsv: "Import CSV",
    tools: "Tools",
    refresh: "Refresh",
    accounts: "Ad accounts",
    tabCampaigns: "Campaigns",
    tabEntries: "Spend entries",
    tabsLabel: "Ads view",
    searchPlaceholder: "Search by campaign name",
    searchLabel: "Search campaigns",
    spend: "Spend",
    orders: "Orders",
    confirmed: "Confirmed",
    delivered: "Delivered",
    deliveredSales: "Delivered sales",
    realCpa: "Real CPA",
    realCpaHint: "Spend ÷ delivered orders",
    realRoas: "Real ROAS",
    realRoasHint: "Delivered sales ÷ spend",
    roasChip: "Return {roas}",
    noRoas: "No return yet",
    deliveredOf: "{delivered} delivered of {orders}",
    ofOrders: "of {orders}",
    campaign: "Campaign",
    platform: "Platform",
    action: "Action",
    meta: "Meta",
    tiktok: "TikTok",
    snapchat: "Snapchat",
    google: "Google",
    pinterest: "Pinterest",
    x: "X (Twitter)",
    taboola: "Taboola",
    outbrain: "Outbrain",
    kwai: "Kwai",
    reddit: "Reddit",
    microsoft: "Microsoft Ads (Bing)",
    other: "Other",
    emptyTitle: "No ad spend recorded for this period",
    emptyDesc: "Type in what you spent per campaign, or import the CSV your ads manager exports. Orders are matched by utm_campaign, or by the ad_id in the ad's link.",
    emptySearch: "No campaign matches your search",
    clearSearch: "Clear the search",
    withoutSpendTitle: "Campaigns with orders but no spend",
    withoutSpendDesc: "These utm_campaign values brought orders. Add their spend to see their real return.",
    recordSpend: "Record its spend",
    urlTitle: "URL parameters for your ads",
    urlDesc: "Paste into the URL parameters field of each ad so orders are matched to the campaign by name.",
    copy: "Copy",
    day: "Date",
    period: "Period",
    source: "Entered",
    manual: "By hand",
    csv: "CSV",
    sync: "Sync",
    impressions: "Impressions",
    clicks: "Clicks",
    noEntries: "No spend entries in this period",
    noEntriesDesc: "Each amount you type in, import or sync shows up here, a line per day and campaign.",
    delete: "Delete",
    deleteTitle: "Delete this spend entry?",
    deleteBody: "{amount} on {day} for “{campaign}” comes out of your ad spend, and the campaign's cost and return are worked out again without it.",
    deleting: "Deleting…",
    deleted: "Entry deleted.",
    peekCampaign: "Preview the campaign {name}",
    menuCampaign: "Actions for this campaign",
    menuEntry: "Actions for this entry",
    copyName: "Copy the campaign name",
    copiedName: "The campaign name is copied",
    control: "Control from here",
    addTitle: "Add ad spend",
    addDesc: "One amount per day and campaign. Saving the same day and campaign again replaces it.",
    campaignName: "Campaign name",
    campaignHint: "Exactly as in utm_campaign",
    amount: "Amount spent",
    invalidAmount: "Type the amount in digits, e.g. 1250.50",
    required: "Type the campaign name as it is in utm_campaign.",
    dayRequired: "Pick the day the money was spent.",
    saved: "Spend saved.",
    importTitle: "Import ad spend",
    importDesc: "A CSV with the columns: Date, Platform, Campaign name, Amount spent. Impressions, Clicks, Campaign ID and Ad ID are optional. An export at ad level (with Ad ID) is added up per campaign and day, and its ads are kept so orders carrying ad_id match too.",
    chooseFile: "Choose a CSV file",
    changeFile: "Choose another file",
    defaultPlatform: "Platform (when the file has no platform column)",
    fromFile: "From the file",
    check: "Check file",
    checking: "Checking…",
    importing: "Importing…",
    importNow: "Import {n} rows",
    checkResult: "{valid} of {rows} rows are ready — total {total}.",
    rejected: "{n} rows will be skipped:",
    line: "Line {n}: {problems}",
    imported: "Imported {created} new and updated {updated}.",
    fileTooBig: "The file is larger than 1 MB. Export a shorter period and try again.",
    template: "Example",
  },
  ar: {
    title: "مصاريف الإعلانات",
    description: "اللي صرفته على الإعلانات قصاد الأوردرات اللي اتسلّمت فعلاً: التكلفة الحقيقية لكل أوردر اتسلّم والعائد الحقيقي على اللي صرفته.",
    addSpend: "ضيف مصاريف",
    importCsv: "استورد CSV",
    tools: "أدوات",
    refresh: "حدّث",
    accounts: "حسابات الإعلانات",
    tabCampaigns: "الحملات",
    tabEntries: "سجل المصاريف",
    tabsLabel: "عرض الإعلانات",
    searchPlaceholder: "دوّر باسم الحملة",
    searchLabel: "دوّر في الحملات",
    spend: "المصاريف",
    orders: "الأوردرات",
    confirmed: "اتأكد",
    delivered: "اتسلّم",
    deliveredSales: "مبيعات اتسلّمت",
    realCpa: "تكلفة الأوردر الحقيقية",
    realCpaHint: "المصاريف ÷ الأوردرات اللي اتسلّمت",
    realRoas: "العائد الحقيقي",
    realRoasHint: "المبيعات اللي اتسلّمت ÷ المصاريف",
    roasChip: "العائد {roas}",
    noRoas: "لسه مفيش عائد",
    deliveredOf: "اتسلّم {delivered} من {orders}",
    ofOrders: "من {orders}",
    campaign: "الحملة",
    platform: "المنصة",
    action: "إجراء",
    meta: "ميتا",
    tiktok: "تيك توك",
    snapchat: "سناب شات",
    google: "جوجل",
    pinterest: "بنترست",
    x: "إكس (تويتر)",
    taboola: "تابولا",
    outbrain: "أوتبرين",
    kwai: "كواي",
    reddit: "ريديت",
    microsoft: "إعلانات مايكروسوفت (Bing)",
    other: "تانية",
    emptyTitle: "مفيش مصاريف إعلانات متسجّلة في الفترة دي",
    emptyDesc: "اكتب اللي صرفته على كل حملة، أو استورد ملف الـ CSV من مدير الإعلانات. الأوردرات بتتربط بالحملة عن طريق utm_campaign أو الـ ad_id اللي في لينك الإعلان.",
    emptySearch: "مفيش حملة بالاسم ده",
    clearSearch: "امسح البحث",
    withoutSpendTitle: "حملات جابت أوردرات ومصاريفها مش متسجّلة",
    withoutSpendDesc: "قيم utm_campaign دي جابت أوردرات. سجّل مصاريفها عشان تشوف عائدها الحقيقي.",
    recordSpend: "سجّل مصاريفها",
    urlTitle: "باراميترات اللينك لإعلاناتك",
    urlDesc: "الصقها في خانة URL parameters في كل إعلان عشان الأوردرات تتنسب للحملة باسمها.",
    copy: "انسخ",
    day: "التاريخ",
    period: "الفترة",
    source: "اتسجّل",
    manual: "بالإيد",
    csv: "CSV",
    sync: "مزامنة",
    impressions: "مرات الظهور",
    clicks: "الضغطات",
    noEntries: "مفيش مصاريف متسجّلة في الفترة دي",
    noEntriesDesc: "كل مبلغ تكتبه أو تستورده أو ييجي بالمزامنة بيظهر هنا، سطر لكل يوم وحملة.",
    delete: "امسح",
    deleteTitle: "تمسح المصاريف دي؟",
    deleteBody: "{amount} بتاريخ {day} لحملة «{campaign}» هتتشال من مصاريف الإعلانات، وتكلفة الحملة وعائدها هيتحسبوا تاني من غيرها.",
    deleting: "بنمسح…",
    deleted: "المصاريف اتمسحت.",
    peekCampaign: "معاينة حملة {name}",
    menuCampaign: "إجراءات الحملة",
    menuEntry: "إجراءات المصاريف",
    copyName: "انسخ اسم الحملة",
    copiedName: "اسم الحملة اتنسخ",
    control: "التحكم من هنا",
    addTitle: "ضيف مصاريف إعلانات",
    addDesc: "مبلغ واحد لكل يوم وحملة. لو حفظت نفس اليوم والحملة تاني، المبلغ الجديد بياخد مكان القديم.",
    campaignName: "اسم الحملة",
    campaignHint: "زي ما هو في utm_campaign بالظبط",
    amount: "المبلغ اللي اتصرف",
    invalidAmount: "اكتب المبلغ بالأرقام، مثلاً 1250.50",
    required: "اكتب اسم الحملة زي ما هو في utm_campaign.",
    dayRequired: "اختار اليوم اللي المبلغ اتصرف فيه.",
    saved: "المصاريف اتحفظت.",
    importTitle: "استورد مصاريف الإعلانات",
    importDesc: "ملف CSV بالأعمدة: Date, Platform, Campaign name, Amount spent. والأعمدة Impressions و Clicks و Campaign ID و Ad ID اختيارية. الملف اللي على مستوى الإعلان (فيه Ad ID) بيتجمع لكل حملة ويوم، وإعلاناته بتتحفظ عشان الأوردرات اللي فيها ad_id تتربط برضه.",
    chooseFile: "اختار ملف CSV",
    changeFile: "اختار ملف تاني",
    defaultPlatform: "المنصة (لو الملف مفيهوش عمود للمنصة)",
    fromFile: "من الملف",
    check: "افحص الملف",
    checking: "بنفحص…",
    importing: "بنستورد…",
    importNow: "استورد {n} صف",
    checkResult: "{valid} من {rows} صف جاهزين — الإجمالي {total}.",
    rejected: "{n} صف مش هيتستوردوا:",
    line: "السطر {n}: {problems}",
    imported: "اتستورد {created} جديد واتحدّث {updated}.",
    fileTooBig: "الملف أكبر من 1 ميجا. صدّر فترة أقصر وجرّب تاني.",
    template: "مثال",
  },
} satisfies Messages;

export type AdsText = Record<keyof (typeof ADS_STRINGS)["en"], string>;
