import type { Messages } from "@/i18n/LocaleContext";

/**
 * Merge duplicate customers (handoff 248): the «عملاء ممكن يكونوا نفس الشخص»
 * card, the side-by-side, the warning and the result. Arabic is the
 * merchant's Egyptian, with the handoff's wording.
 */
export const MERGE_STRINGS = {
  en: {
    title: "Possible duplicates",
    hint: "The same email, the same last 9 digits of the phone, or the same name. Merge two records of one person so their orders are in one place.",
    reason_email: "Same email",
    reason_phone: "Same number",
    reason_name: "Same name",
    merge: "Merge",
    mergeWith: "Merge with {name}",
    noName: "Customer without a name",
    noOrders: "No orders",
    // side by side
    compareTitle: "Merge these two customers",
    compareHint: "Choose the customer to keep. Everything the other one has moves to it, and the other one is deleted.",
    thisCustomer: "This customer",
    otherCustomer: "The other customer",
    keep: "Keep this one",
    stays: "Stays",
    goes: "Will be deleted",
    name: "Name",
    phone: "Phone",
    email: "Email",
    orders: "Orders",
    since: "Customer since",
    none: "—",
    whyAlike: "Why they look alike",
    // confirmation
    confirmTitle: "Merge, and delete the duplicate?",
    confirmKeepThis: "All of the other customer's orders and data move here and it is deleted — this can't be undone",
    confirmKeepOther: "All of this customer's orders and data move to the other customer and this one is deleted — this can't be undone",
    confirmNames: "Stays: {keep}. Deleted: {duplicate}.",
    confirm: "Merge",
    merging: "Merging…",
    paymentInProgress: "One of them has an online payment in progress — try again when it's done",
    gone: "One of these customers no longer exists. Reload the page.",
    // result
    doneTitle: "Merged",
    doneBody: "{name} now holds everything of both.",
    movedTitle: "What moved",
    nothingMoved: "The duplicate had nothing to move.",
    moved_orders: "Orders",
    moved_customer_addresses: "Addresses",
    moved_customer_notes: "Notes",
    moved_customer_followups: "Follow-ups",
    moved_reviews: "Reviews",
    moved_wishlist_items: "Wishlist items",
    moved_customer_referrals: "Referrals",
    moved_customer_referral_codes: "Referral code",
    moved_quote_requests: "Quotes",
    moved_loyalty_transactions: "Points history lines",
    moved_store_credit_transactions: "Store credit history lines",
    moved_form_submissions: "Form submissions",
    moved_gift_cards: "Gift cards",
    moved_customer_subscriptions: "Subscriptions",
    moved_enrollments: "Course enrolments",
    moved_whatsapp_conversations: "WhatsApp chats",
    moved_payment_methods_saved: "Saved cards",
    moved_carts: "Carts",
    moved_discount_redemptions: "Discount uses",
    moved_privacy_requests: "Privacy requests",
    moved_other: "Other records",
    pointsAdded: "Points added",
    creditAdded: "Store credit added",
    alternatePhone: "Alternate phone now",
    done: "Done",
  },
  ar: {
    title: "عملاء ممكن يكونوا نفس الشخص",
    hint: "نفس الإيميل، أو نفس آخر ٩ أرقام من الموبايل، أو نفس الاسم. ادمج السجلّين لو هما لنفس الشخص عشان طلباته تبقى في مكان واحد.",
    reason_email: "نفس الإيميل",
    reason_phone: "نفس الرقم",
    reason_name: "نفس الاسم",
    merge: "دمج",
    mergeWith: "ادمج مع {name}",
    noName: "عميل من غير اسم",
    noOrders: "مفيش أوردرات",
    compareTitle: "دمج العميلين دول",
    compareHint: "اختار العميل اللي هيفضل. كل حاجة عند التاني هتتنقل له، والتاني هيتمسح.",
    thisCustomer: "العميل ده",
    otherCustomer: "العميل التاني",
    keep: "خلّي ده",
    stays: "هيفضل",
    goes: "هيتمسح",
    name: "الاسم",
    phone: "الموبايل",
    email: "الإيميل",
    orders: "الطلبات",
    since: "عميل من",
    none: "—",
    whyAlike: "ليه شبه بعض",
    confirmTitle: "تدمج وتمسح المكرر؟",
    confirmKeepThis: "هننقل كل طلبات وبيانات العميل التاني للعميل ده ونمسحه — مينفعش يترجع",
    confirmKeepOther: "هننقل كل طلبات وبيانات العميل ده للعميل التاني ونمسح العميل ده — مينفعش يترجع",
    confirmNames: "هيفضل: {keep}. هيتمسح: {duplicate}.",
    confirm: "ادمج",
    merging: "بندمج…",
    paymentInProgress: "في دفع أونلاين شغال لأحدهم — جرّب بعد ما يخلص",
    gone: "واحد من العميلين مبقاش موجود. اعمل تحديث للصفحة.",
    doneTitle: "اتدمجوا",
    doneBody: "{name} بقى عنده كل حاجة من الاتنين.",
    movedTitle: "اللي اتنقل",
    nothingMoved: "العميل المكرر مكانش عنده حاجة تتنقل.",
    moved_orders: "طلبات",
    moved_customer_addresses: "عناوين",
    moved_customer_notes: "ملاحظات",
    moved_customer_followups: "متابعات",
    moved_reviews: "تقييمات",
    moved_wishlist_items: "منتجات في المفضلة",
    moved_customer_referrals: "ترشيحات",
    moved_customer_referral_codes: "كود ترشيح",
    moved_quote_requests: "عروض أسعار",
    moved_loyalty_transactions: "حركات نقاط",
    moved_store_credit_transactions: "حركات رصيد",
    moved_form_submissions: "رسايل نماذج",
    moved_gift_cards: "كروت هدايا",
    moved_customer_subscriptions: "اشتراكات",
    moved_enrollments: "اشتراكات كورسات",
    moved_whatsapp_conversations: "محادثات واتساب",
    moved_payment_methods_saved: "كروت دفع محفوظة",
    moved_carts: "سلات",
    moved_discount_redemptions: "مرات استخدام خصم",
    moved_privacy_requests: "طلبات خصوصية",
    moved_other: "سجلات تانية",
    pointsAdded: "نقاط اتضافت",
    creditAdded: "رصيد اتضاف",
    alternatePhone: "الرقم البديل دلوقتي",
    done: "تمام",
  },
} satisfies Messages;

export type MergeStrings = Record<keyof (typeof MERGE_STRINGS)["en"], string>;
