import type { Messages } from "@/i18n/LocaleContext";

/**
 * Notes and follow-ups on a customer, and the «متابعاتي» list (handoff 209).
 * Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const NOTES_STRINGS = {
  en: {
    // notes
    notesTitle: "Notes",
    notesHint: "Only your team sees these. Pinned notes stay on top.",
    noteLabel: "New note",
    notePlaceholder: "Something the team should know about this customer…",
    pinNew: "Pin it to the top",
    addNote: "Add note",
    adding: "Adding…",
    noteAdded: "Note added.",
    notesEmpty: "No notes yet.",
    pinned: "Pinned",
    pin: "Pin this note",
    unpin: "Unpin this note",
    someone: "A teammate",
    editNote: "Edit this note",
    editNoteLabel: "Note",
    deleteNote: "Delete this note",
    deleteNoteTitle: "Delete this note?",
    deleteNoteBody: "It can't be brought back.",
    deleting: "Deleting…",
    noteDeleted: "Note deleted.",
    noteSaved: "Note saved.",
    notYours: "Only the person who wrote this note can change it.",
    // follow-ups
    followupsTitle: "Follow-ups",
    followupsHint: "A reminder to get back to this customer. Whoever it is assigned to is notified when its time comes.",
    addFollowup: "Add follow-up",
    whatLabel: "What to do",
    whatPlaceholder: "Call back about the wholesale order",
    whenLabel: "When",
    whoLabel: "Assigned to",
    me: "Me",
    wholeTeam: "Whole team",
    whatRequired: "Write what needs doing.",
    whenRequired: "Choose a day and a time.",
    whoInvalid: "Assign it to a teammate who can see customers.",
    followupAdded: "Follow-up added.",
    followupSaved: "Follow-up saved.",
    followupsEmpty: "No follow-ups yet.",
    overdue: "Overdue",
    doneBadge: "Done",
    markDone: "Mark “{title}” as done",
    doneToast: "Marked as done.",
    reopened: "Open again.",
    doneWhen: "Done {when}",
    editFollowup: "Edit follow-up",
    editFollowupLabel: "Edit “{title}”",
    deleteFollowup: "Delete “{title}”",
    deleteFollowupTitle: "Delete this follow-up?",
    deleteFollowupBody: "Nobody will be reminded of it.",
    followupDeleted: "Follow-up deleted.",
    // my follow-ups (Customers page)
    myHint: "Open follow-ups assigned to you, soonest first.",
    teamHint: "Every open follow-up in the store, soonest first — the whole team's too.",
    scopeLabel: "Whose follow-ups",
    scopeMine: "Mine",
    scopeTeam: "Whole team",
    overdueCount_one: "1 overdue",
    overdueCount_other: "{n} overdue",
    colDone: "Done",
    colFollowup: "Follow-up",
    colCustomer: "Customer",
    colDue: "When",
    colWho: "Assigned to",
    noName: "Customer without a name",
    myEmptyTitle: "No open follow-ups",
    myEmptyHint: "Add one from a customer's page, under “Notes & follow-ups”.",
    teamEmptyTitle: "No open follow-ups in the store",
  },
  ar: {
    notesTitle: "ملاحظات",
    notesHint: "فريقك بس اللي بيشوفها. الملاحظات المتثبّتة بتفضل فوق.",
    noteLabel: "ملاحظة جديدة",
    notePlaceholder: "حاجة الفريق محتاج يعرفها عن العميل ده…",
    pinNew: "ثبّتها فوق",
    addNote: "ضيف الملاحظة",
    adding: "بنضيف…",
    noteAdded: "الملاحظة اتضافت.",
    notesEmpty: "لسه مفيش ملاحظات.",
    pinned: "متثبّتة",
    pin: "ثبّت الملاحظة دي",
    unpin: "شيل تثبيت الملاحظة دي",
    someone: "حد من الفريق",
    editNote: "عدّل الملاحظة دي",
    editNoteLabel: "الملاحظة",
    deleteNote: "امسح الملاحظة دي",
    deleteNoteTitle: "تمسح الملاحظة دي؟",
    deleteNoteBody: "مش هترجع تاني.",
    deleting: "بنمسح…",
    noteDeleted: "الملاحظة اتمسحت.",
    noteSaved: "الملاحظة اتحفظت.",
    notYours: "اللي كتب الملاحظة دي بس هو اللي يقدر يغيّرها.",
    followupsTitle: "متابعات",
    followupsHint: "تذكير ترجع للعميل ده. اللي عليه المتابعة بيجيله إشعار لما معادها ييجي.",
    addFollowup: "ضيف متابعة",
    whatLabel: "هتعمل إيه",
    whatPlaceholder: "كلّمه تاني عن أوردر الجملة",
    whenLabel: "إمتى",
    whoLabel: "على مين",
    me: "أنا",
    wholeTeam: "كل الفريق",
    whatRequired: "اكتب المطلوب.",
    whenRequired: "اختار اليوم والساعة.",
    whoInvalid: "اختار زميل يقدر يشوف العملاء.",
    followupAdded: "المتابعة اتضافت.",
    followupSaved: "المتابعة اتحفظت.",
    followupsEmpty: "لسه مفيش متابعات.",
    overdue: "متأخرة",
    doneBadge: "خلصت",
    markDone: "علّم «{title}» إنها خلصت",
    doneToast: "اتعلّمت إنها خلصت.",
    reopened: "اتفتحت تاني.",
    doneWhen: "خلصت {when}",
    editFollowup: "عدّل المتابعة",
    editFollowupLabel: "عدّل «{title}»",
    deleteFollowup: "امسح «{title}»",
    deleteFollowupTitle: "تمسح المتابعة دي؟",
    deleteFollowupBody: "محدش هيتفكّر بيها.",
    followupDeleted: "المتابعة اتمسحت.",
    myHint: "المتابعات المفتوحة اللي عليك، الأقرب الأول.",
    teamHint: "كل المتابعات المفتوحة في المتجر، الأقرب الأول — واللي على كل الفريق كمان.",
    scopeLabel: "متابعات مين",
    scopeMine: "بتاعتي",
    scopeTeam: "كل الفريق",
    overdueCount_one: "واحدة متأخرة",
    overdueCount_two: "اتنين متأخرين",
    overdueCount_few: "{n} متأخرة",
    overdueCount_other: "{n} متأخرة",
    colDone: "خلصت",
    colFollowup: "المتابعة",
    colCustomer: "العميل",
    colDue: "إمتى",
    colWho: "على مين",
    noName: "عميل من غير اسم",
    myEmptyTitle: "مفيش متابعات مفتوحة",
    myEmptyHint: "ضيف متابعة من صفحة أي عميل، من تبويب «ملاحظات ومتابعات».",
    teamEmptyTitle: "مفيش متابعات مفتوحة في المتجر",
  },
} satisfies Messages;

export type NotesStrings = Record<keyof (typeof NOTES_STRINGS)["en"], string>;
