import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customer privacy requests (handoff 235): the customer page's «الخصوصية»
 * card and the Customers page's «طلبات الخصوصية» inbox. Arabic is the
 * merchant's Egyptian, with the handoff's wording.
 */
export const PRIVACY_STRINGS = {
  en: {
    // customer page card
    cardTitle: "Privacy",
    cardHint: "A copy of everything the store holds about this customer, or erasing their personal details when they ask.",
    exportData: "Export data",
    exporting: "Preparing…",
    exported: "The customer's data file was downloaded.",
    erase: "Erase customer",
    eraseTitle: "Erase this customer?",
    eraseBody:
      "The customer becomes “Deleted customer” with no phone, email, company, tax ID or addresses. Their orders keep amounts, items and governorate, without the name, phone, email and street. Saved cards, sign-in codes and wishlist are deleted, and they are signed out. This can't be undone.",
    eraseConfirm: "Erase customer",
    erasing: "Erasing…",
    note: "Note (optional)",
    noteHint: "Kept with the request, for example “asked by phone”.",
    openOrders: "This customer has orders still on their way — erase after delivery, or force it",
    force: "Erase anyway",
    erased: "The customer's personal details were erased.",
    alreadyErased: "This customer's personal details were erased. Their orders keep the amounts and items, without a name.",
    // requests inbox
    intro: "What shoppers asked for from their account in your store: a copy of their data, or deleting their account. Deleting waits for your decision.",
    statusLabel: "Status",
    status_pending: "Waiting",
    status_completed: "Done",
    status_declined: "Declined",
    status_all: "All",
    kindLabel: "Kind",
    kind_all: "Every kind",
    kind_erase: "Delete account",
    kind_export: "Copy of data",
    colRequester: "Requester",
    colKind: "Kind",
    colReason: "Their reason",
    colStatus: "Status",
    colAsked: "Asked",
    colDecision: "Store's note",
    colActions: "Actions",
    someone: "A shopper",
    complete: "Erase",
    completeFor: "Erase the account of {name}",
    decline: "Decline",
    declineFor: "Decline the request of {name}",
    completeTitle: "Erase the account of {name}?",
    completeConfirm: "Erase account",
    completed: "The account was erased.",
    declineTitle: "Decline this request?",
    declineBody: "The account stays as it is. The customer sees your reason next to the request in their account.",
    declineReason: "Reason",
    declineReasonRequired: "Write the reason.",
    declineConfirm: "Decline request",
    declining: "Declining…",
    declined: "The request was declined.",
    notPending: "This request was already handled. The list was refreshed.",
    emptyPendingTitle: "No requests waiting",
    emptyPendingHint: "When a shopper asks to delete their account, the request shows up here for your decision.",
    emptyTitle: "No privacy requests yet",
    emptyHint: "Shoppers ask from their account in your store, under “Privacy”.",
    emptyFiltered: "No request matches these filters.",
    showAll: "Show all requests",
  },
  ar: {
    cardTitle: "الخصوصية",
    cardHint: "نسخة من كل اللي المتجر محتفظ بيه عن العميل ده، أو مسح بياناته الشخصية لو طلب.",
    exportData: "نزّل بيانات العميل",
    exporting: "بنجهّز…",
    exported: "ملف بيانات العميل اتنزّل.",
    erase: "امسح العميل",
    eraseTitle: "تمسح العميل ده؟",
    eraseBody:
      "العميل هيبقى «Deleted customer» من غير موبايل ولا إيميل ولا شركة ولا رقم ضريبي ولا عناوين. طلباته هتفضل بمبالغها ومنتجاتها ومحافظتها، من غير الاسم والموبايل والإيميل والشارع. الكروت المحفوظة وأكواد الدخول والمفضلة هتتمسح، وهيتسجّل خروجه. مينفعش يترجع.",
    eraseConfirm: "امسح العميل",
    erasing: "بنمسح…",
    note: "ملاحظة (اختياري)",
    noteHint: "بتتحفظ مع الطلب، مثلاً: «طلب بالتليفون».",
    openOrders: "العميل عنده طلبات لسه في الطريق — امسح بعد ما تتسلّم أو اختار \"امسح برضه\"",
    force: "امسح برضه",
    erased: "بيانات العميل الشخصية اتمسحت.",
    alreadyErased: "بيانات العميل ده الشخصية اتمسحت. طلباته محفوظة بمبالغها ومنتجاتها من غير اسم.",
    intro: "اللي العملاء طلبوه من حسابهم في متجرك: نسخة من بياناتهم، أو مسح حسابهم. المسح بيستنى قرارك.",
    statusLabel: "الحالة",
    status_pending: "مستنية",
    status_completed: "اتنفّذت",
    status_declined: "اترفضت",
    status_all: "الكل",
    kindLabel: "النوع",
    kind_all: "كل الأنواع",
    kind_erase: "مسح الحساب",
    kind_export: "نسخة من البيانات",
    colRequester: "صاحب الطلب",
    colKind: "النوع",
    colReason: "سببه",
    colStatus: "الحالة",
    colAsked: "اتطلب",
    colDecision: "ملاحظة المتجر",
    colActions: "إجراءات",
    someone: "عميل",
    complete: "نفّذ المسح",
    completeFor: "نفّذ مسح حساب {name}",
    decline: "ارفض",
    declineFor: "ارفض طلب {name}",
    completeTitle: "تمسح حساب {name}؟",
    completeConfirm: "امسح الحساب",
    completed: "الحساب اتمسح.",
    declineTitle: "ترفض الطلب ده؟",
    declineBody: "الحساب هيفضل زي ما هو. العميل هيشوف السبب جنب الطلب في حسابه.",
    declineReason: "السبب",
    declineReasonRequired: "اكتب السبب.",
    declineConfirm: "ارفض الطلب",
    declining: "بنرفض…",
    declined: "الطلب اترفض.",
    notPending: "الطلب ده اتاخد فيه قرار قبل كده. القايمة اتحدّثت.",
    emptyPendingTitle: "مفيش طلبات مستنية",
    emptyPendingHint: "لما عميل يطلب مسح حسابه، الطلب هيظهر هنا عشان تقرر.",
    emptyTitle: "لسه مفيش طلبات خصوصية",
    emptyHint: "العملاء بيطلبوا من حسابهم في متجرك، من «الخصوصية».",
    emptyFiltered: "مفيش طلب بالفلاتر دي.",
    showAll: "اعرض كل الطلبات",
  },
} satisfies Messages;

export type PrivacyStrings = Record<keyof (typeof PRIVACY_STRINGS)["en"], string>;
