import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customer page → «كل اللي حصل» (handoff 250): the kinds' names and the words
 * of their one-line summaries. Arabic is the merchant's Egyptian, with the
 * handoff's labels.
 */
export const TIMELINE_STRINGS = {
  en: {
    filterLabel: "Show",
    filter_all: "All",
    filter_orders: "Orders",
    filter_notes: "Notes & follow-ups",
    filter_reviews: "Reviews & questions",
    filter_wallet: "Points & credit",
    filter_other: "Other",
    empty: "Nothing with this customer yet",
    emptyFiltered: "Nothing of this kind with this customer yet",
    showAll: "Show everything",
    // kinds
    kind_order_placed: "Order placed",
    kind_order_shipped: "Shipped",
    kind_order_delivered: "Delivered",
    kind_order_cancelled: "Cancelled",
    kind_return_requested: "Return requested",
    kind_refund: "Refund",
    kind_note: "Note",
    kind_followup: "Follow-up",
    kind_review: "Review",
    kind_question: "Product question",
    kind_loyalty: "Points",
    kind_store_credit: "Store credit",
    kind_quote: "Quote",
    kind_privacy_request: "Privacy request",
    kind_referral: "Referred a friend",
    kind_form: "Sent a form",
    kind_unknown: "Something else",
    // summaries
    testOrder: "Test order",
    waybill: "Waybill {number}",
    track: "Track",
    cancel_customer_request: "The customer asked to cancel",
    cancel_payment_expired: "The payment window ran out",
    cancel_customer_blocked: "The customer is blocked",
    return_damaged: "Damaged",
    return_defective: "Defective",
    return_wrong_item: "Wrong item",
    return_not_as_described: "Not as described",
    return_no_longer_wanted: "No longer wanted",
    return_arrived_late: "Arrived late",
    return_other: "Another reason",
    returnStatus_requested: "Waiting for approval",
    returnStatus_approved: "Approved",
    returnStatus_rejected: "Rejected",
    returnStatus_received: "Received back",
    returnStatus_refunded: "Refunded",
    refundStatus_pending: "Waiting",
    refundStatus_processed: "Paid back",
    refundStatus_failed: "Failed",
    notePinned: "Pinned",
    noteBy: "by {name}",
    followupDue: "due {when}",
    followupDone: "Done",
    followupOverdue: "Overdue",
    followupFor: "for {name}",
    rating: "{n} of 5",
    reviewStatus_pending: "Waiting for review",
    reviewStatus_approved: "Published",
    reviewStatus_rejected: "Rejected",
    questionAnswered: "Answered",
    questionWaiting: "Waiting for an answer",
    questionHidden: "Hidden",
    ledger_merge: "Moved from a merged customer",
    ledger_hold_released: "Hold given back",
    balanceAfter: "balance {amount}",
    quoteNumber: "Quote {number}",
    quoteStatus_new: "New",
    quoteStatus_quoted: "Priced",
    quoteStatus_accepted: "Accepted",
    quoteStatus_declined: "Declined",
    quoteStatus_cancelled: "Cancelled",
    quoteStatus_expired: "Expired",
    quoteValidUntil: "valid until {date}",
    privacy_export: "A copy of their data",
    privacy_erase: "Delete their account",
    privacyStatus_pending: "Waiting",
    privacyStatus_completed: "Done",
    privacyStatus_declined: "Declined",
    referralFriend: "Friend: {name}",
    referralStatus_pending: "Waiting for the friend's first order",
    referralStatus_rewarded: "Rewarded",
    referralStatus_void: "Not counted",
  },
  ar: {
    filterLabel: "اعرض",
    filter_all: "الكل",
    filter_orders: "طلبات",
    filter_notes: "ملاحظات ومتابعات",
    filter_reviews: "تقييمات وأسئلة",
    filter_wallet: "نقاط ورصيد",
    filter_other: "تاني",
    empty: "لسه مفيش حاجة مع العميل ده",
    emptyFiltered: "لسه مفيش حاجة من النوع ده مع العميل ده",
    showAll: "اعرض الكل",
    kind_order_placed: "طلب جديد",
    kind_order_shipped: "اتشحن",
    kind_order_delivered: "اتسلّم",
    kind_order_cancelled: "اتلغى",
    kind_return_requested: "طلب إرجاع",
    kind_refund: "فلوس اترجعت",
    kind_note: "ملاحظة",
    kind_followup: "متابعة",
    kind_review: "تقييم",
    kind_question: "سؤال عن منتج",
    kind_loyalty: "نقاط",
    kind_store_credit: "رصيد",
    kind_quote: "عرض سعر",
    kind_privacy_request: "طلب خصوصية",
    kind_referral: "رشّح صاحبه",
    kind_form: "بعت فورم",
    kind_unknown: "حاجة تانية",
    testOrder: "أوردر تجريبي",
    waybill: "بوليصة {number}",
    track: "تتبّع",
    cancel_customer_request: "العميل طلب الإلغاء",
    cancel_payment_expired: "مهلة الدفع خلصت",
    cancel_customer_blocked: "العميل محظور",
    return_damaged: "تالف",
    return_defective: "عيب صناعة",
    return_wrong_item: "منتج غلط",
    return_not_as_described: "مش زي الوصف",
    return_no_longer_wanted: "مبقاش عايزه",
    return_arrived_late: "اتأخر",
    return_other: "سبب تاني",
    returnStatus_requested: "مستني موافقة",
    returnStatus_approved: "اتوافق عليه",
    returnStatus_rejected: "اترفض",
    returnStatus_received: "رجع المخزن",
    returnStatus_refunded: "فلوسه اترجعت",
    refundStatus_pending: "مستني",
    refundStatus_processed: "اتدفعت",
    refundStatus_failed: "فشل",
    notePinned: "متثبّتة",
    noteBy: "كتبها {name}",
    followupDue: "معادها {when}",
    followupDone: "خلصت",
    followupOverdue: "متأخرة",
    followupFor: "على {name}",
    rating: "{n} من ٥",
    reviewStatus_pending: "مستني مراجعة",
    reviewStatus_approved: "منشور",
    reviewStatus_rejected: "مرفوض",
    questionAnswered: "اترد عليه",
    questionWaiting: "مستني رد",
    questionHidden: "مخفي",
    ledger_merge: "اتنقل من عميل اتدمج",
    ledger_hold_released: "الحجز رجع",
    balanceAfter: "الرصيد {amount}",
    quoteNumber: "عرض {number}",
    quoteStatus_new: "جديد",
    quoteStatus_quoted: "اتسعّر",
    quoteStatus_accepted: "اتقبل",
    quoteStatus_declined: "اترفض",
    quoteStatus_cancelled: "اتلغى",
    quoteStatus_expired: "انتهى",
    quoteValidUntil: "ساري لحد {date}",
    privacy_export: "نسخة من بياناته",
    privacy_erase: "مسح حسابه",
    privacyStatus_pending: "مستني",
    privacyStatus_completed: "اتنفّذ",
    privacyStatus_declined: "اترفض",
    referralFriend: "صاحبه: {name}",
    referralStatus_pending: "مستني أول طلب لصاحبه",
    referralStatus_rewarded: "أخد مكافأته",
    referralStatus_void: "متحسبش",
  },
} satisfies Messages;

export type TimelineStrings = Record<keyof (typeof TIMELINE_STRINGS)["en"], string>;
