import type { Messages } from "@/i18n/LocaleContext";

/**
 * Every word of the Rules tab, in one place: the tab, its rows and its
 * summaries all read from it through `useT(RULES_STRINGS)`.
 */
export const RULES_STRINGS = {
  en: {
    readOnlyTitle: "View only",
    readOnly: "Only the store owner or a workspace manager can change these rules.",
    readOnlyForbidden: "Your role can't change these rules, so they're shown read-only. Ask the store owner if they need changing.",
    orderRules: "Order rules",
    orderRulesHint: "Each rule is off until you switch it on, and each one has its own action.",
    visitorRules: "Where the order comes from",
    visitorRulesHint: "Checked against the shopper's internet address when they order.",
    customerRules: "The customer's history",
    customerRulesHint: "What this customer did before, here and across the platform.",
    then: "Then",
    action_flag: "Flag it for review",
    action_block: "Refuse the order",
    action_require_otp: "Ask for a code first",
    action_to_lost: "Move it to lost orders",
    duplicate_window_minutes: "Duplicate orders",
    duplicate_window_minutesHint: "The same customer orders any of the same products again within this many minutes.",
    duplicate_window_minutesUnit: "minutes",
    max_orders_per_phone_per_day: "Too many orders from one phone",
    max_orders_per_phone_per_dayHint: "The customer already placed this many orders in the last 24 hours.",
    max_orders_per_phone_per_dayUnit: "orders",
    high_rejection_threshold: "Customers who often refuse orders",
    high_rejection_thresholdHint: "The customer has rejected at least this many orders before.",
    high_rejection_thresholdUnit: "rejected orders",
    max_items_per_order: "Too many pieces of one product",
    max_items_per_orderHint: "The order holds more than this many units of the same product.",
    max_items_per_orderUnit: "pieces",
    min_minutes_between_cod_orders_per_ip: "Cash-on-delivery orders too close together",
    min_minutes_between_cod_orders_per_ipHint: "Another cash-on-delivery order came from the same internet address less than this many minutes ago.",
    min_minutes_between_cod_orders_per_ipUnit: "minutes",
    min_network_delivery_rate: "Low delivery rate",
    min_network_delivery_rateHint: "The customer's delivery rate across all stores is below this percentage.",
    min_network_delivery_rateUnit: "%",
    block_outside_country: "Orders from other countries",
    block_outside_countryHint: "The shopper is not in one of the allowed countries.",
    block_vpn: "VPN and server addresses",
    block_vpnHint: "The shopper is hiding behind a VPN or ordering from a data centre.",
    high_risk: "High-risk orders",
    high_riskHint: "The order's risk level came out as high.",
    allowedCountries: "Allowed countries",
    allowedCountriesHint: "Two-letter country codes separated by commas, for example EG, SA. Leave empty for your store's country only.",
    allowedCountriesError: "Use two-letter country codes separated by commas.",
    rangeError: "Enter a whole number from {min} to {max}.",
    otpHeading: "Phone verification",
    otpEnabled: "Ask for a code before the order is placed",
    otpEnabledHint: "The shopper gets a code and types it in. No order, stock hold or pixel event exists until the number is verified; unverified attempts go to lost orders.",
    otpChannel: "Send the code by",
    otpChannel_whatsapp: "WhatsApp (SMS if it cannot be sent)",
    otpChannel_sms: "SMS",
    otpApply: "Ask",
    otpApply_all: "Every order",
    otpApply_cod_only: "Cash-on-delivery orders only",
    otpApply_risky_only: "Risky orders only",
    otpLength: "Code length",
    otpDigits: "{n} digits",
    botCaptcha: "Add an invisible challenge",
    botCaptchaHint: "A background check the shopper never sees (Cloudflare Turnstile). It only acts once the challenge provider is connected to the platform.",
    visitorsHeading: "Visitors",
    botProtection: "Bot protection",
    botProtectionHint: "Refuses orders sent by scripts: a hidden field only a bot fills, and a check that the form was open for at least three seconds. Refused attempts go to lost orders.",
    blockedCountries: "Countries that cannot see the store",
    blockedCountriesHint: "Two-letter country codes separated by commas. Visitors from these countries see the store as unavailable. Block single addresses in the Blocked tab.",
    alwaysHeading: "Always",
    strictPhone: "Only accept real mobile numbers",
    strictPhoneHint: "A number that is not a mobile number of your store's country is refused, and the shopper is asked to correct it.",
    blockBlacklisted: "Always refuse blocked customers",
    blockBlacklistedHint: "When off, orders matching the blocked list are still placed but flagged. Manage the list in the Blocked tab.",
    save: "Save rules",
    saving: "Saving…",
    reset: "Discard changes",
    saved: "Rules saved.",
    // What a folded section says about itself.
    rulesOn_one: "1 rule on",
    rulesOn_other: "{n} rules on",
    rulesOff: "No rule is on",
    chipCount: "{on} of {total}",
    chipOn: "On",
    chipOff: "Off",
    chipCheck: "Check",
    summarySep: " · ",
    otpOffSummary: "Code verification is off",
    otpBy_whatsapp: "Code by WhatsApp",
    otpBy_sms: "Code by SMS",
    botOnSummary: "Bot protection is on",
    botOffSummary: "Bot protection is off",
    botCaptchaSummary: "invisible challenge",
    countriesHidden_one: "1 country hidden",
    countriesHidden_other: "{n} countries hidden",
    alwaysStrictSummary: "Real mobile numbers only",
    alwaysBlockSummary: "Blocked customers refused",
    alwaysNone: "Nothing here is on",
  },
  ar: {
    readOnlyTitle: "للعرض بس",
    readOnly: "صاحب المتجر أو مدير المتجر بس اللي يقدروا يغيّروا القواعد دي.",
    readOnlyForbidden: "دورك مايسمحش بتغيير القواعد دي، فهي ظاهرة للعرض بس. اطلب من صاحب المتجر لو محتاجة تعديل.",
    orderRules: "قواعد الأوردر",
    orderRulesHint: "كل قاعدة مقفولة لحد ما تشغّلها، وكل واحدة ليها تصرّفها.",
    visitorRules: "الأوردر جاي منين",
    visitorRulesHint: "بنراجعها على عنوان الإنترنت بتاع العميل وقت الأوردر.",
    customerRules: "تاريخ العميل",
    customerRulesHint: "اللي العميل ده عمله قبل كده، عندك وعلى المنصة كلها.",
    then: "التصرّف",
    action_flag: "علّم عليه للمراجعة",
    action_block: "ارفض الأوردر",
    action_require_otp: "اطلب كود الأول",
    action_to_lost: "حوّله للأوردرات المفقودة",
    duplicate_window_minutes: "أوردرات مكررة",
    duplicate_window_minutesHint: "نفس العميل طلب نفس المنتجات تاني في خلال العدد ده من الدقايق.",
    duplicate_window_minutesUnit: "دقيقة",
    max_orders_per_phone_per_day: "أوردرات كتير من نفس الموبايل",
    max_orders_per_phone_per_dayHint: "العميل عمل العدد ده من الأوردرات في آخر ٢٤ ساعة.",
    max_orders_per_phone_per_dayUnit: "أوردر",
    high_rejection_threshold: "عملاء بيرفضوا كتير",
    high_rejection_thresholdHint: "العميل رفض العدد ده من الأوردرات على الأقل قبل كده.",
    high_rejection_thresholdUnit: "أوردر مرفوض",
    max_items_per_order: "قطع كتير من نفس المنتج",
    max_items_per_orderHint: "الأوردر فيه أكتر من العدد ده من نفس المنتج.",
    max_items_per_orderUnit: "قطعة",
    min_minutes_between_cod_orders_per_ip: "أوردرات دفع عند الاستلام ورا بعض",
    min_minutes_between_cod_orders_per_ipHint: "جه أوردر دفع عند الاستلام تاني من نفس عنوان الإنترنت من أقل من العدد ده من الدقايق.",
    min_minutes_between_cod_orders_per_ipUnit: "دقيقة",
    min_network_delivery_rate: "نسبة استلام قليلة",
    min_network_delivery_rateHint: "نسبة استلام العميل على كل المتاجر أقل من النسبة دي.",
    min_network_delivery_rateUnit: "٪",
    block_outside_country: "أوردرات من بلاد تانية",
    block_outside_countryHint: "العميل مش في بلد من البلاد المسموح بيها.",
    block_vpn: "عناوين VPN وسيرفرات",
    block_vpnHint: "العميل مستخبي ورا VPN أو بيطلب من سيرفر.",
    high_risk: "أوردرات خطورتها عالية",
    high_riskHint: "مستوى خطورة الأوردر طلع «عالي».",
    allowedCountries: "البلاد المسموح بيها",
    allowedCountriesHint: "أكواد البلاد من حرفين بينهم فاصلة، زي EG, SA. سيبها فاضية لبلد متجرك بس.",
    allowedCountriesError: "اكتب أكواد بلاد من حرفين بينهم فاصلة.",
    rangeError: "اكتب رقم صحيح من {min} لـ {max}.",
    otpHeading: "تأكيد رقم الموبايل",
    otpEnabled: "اطلب كود قبل ما الأوردر يتسجّل",
    otpEnabledHint: "العميل بيوصله كود ويكتبه. مفيش أوردر ولا حجز مخزون ولا حدث بيكسل قبل ما الرقم يتأكد، والمحاولات اللي ماتأكدتش بتروح الأوردرات المفقودة.",
    otpChannel: "ابعت الكود على",
    otpChannel_whatsapp: "واتساب (ورسالة SMS لو ماتبعتش)",
    otpChannel_sms: "رسالة SMS",
    otpApply: "اطلبه من",
    otpApply_all: "كل الأوردرات",
    otpApply_cod_only: "أوردرات الدفع عند الاستلام بس",
    otpApply_risky_only: "الأوردرات الخطرة بس",
    otpLength: "طول الكود",
    otpDigits: "{n} أرقام",
    botCaptcha: "ضيف تحدّي مخفي",
    botCaptchaHint: "فحص في الخلفية العميل مش بيشوفه (Cloudflare Turnstile). بيشتغل بس بعد ما مزوّد التحدّي يتربط بالمنصة.",
    visitorsHeading: "الزوار",
    botProtection: "الحماية من البوتات",
    botProtectionHint: "بترفض الأوردرات اللي جاية من سكربتات: خانة مخفية مايملاهاش غير البوت، والتأكد إن الفورم فضل مفتوح تلات ثواني على الأقل. المحاولات المرفوضة بتروح الأوردرات المفقودة.",
    blockedCountries: "بلاد مش بتشوف المتجر",
    blockedCountriesHint: "أكواد بلاد من حرفين بينهم فاصلة. الزوار من البلاد دي بيظهرلهم المتجر مش متاح. العناوين المفردة احجبها من تبويب «المحظورين».",
    alwaysHeading: "دايمًا",
    strictPhone: "اقبل أرقام الموبايل الحقيقية بس",
    strictPhoneHint: "الرقم اللي مش رقم موبايل في بلد متجرك بيترفض، والعميل بيتطلب منه يصلّحه.",
    blockBlacklisted: "ارفض العملاء المحظورين دايمًا",
    blockBlacklistedHint: "لو مقفولة، الأوردرات اللي بتطابق قايمة المحظورين بتتسجّل بس بيتعلّم عليها. القايمة في تبويب «المحظورين».",
    save: "احفظ القواعد",
    saving: "بنحفظ…",
    reset: "سيب التغييرات",
    saved: "القواعد اتحفظت.",
    rulesOn_one: "قاعدة واحدة شغّالة",
    rulesOn_two: "قاعدتين شغّالين",
    rulesOn_few: "{n} قواعد شغّالة",
    rulesOn_other: "{n} قاعدة شغّالة",
    rulesOff: "مفيش قاعدة شغّالة",
    chipCount: "{on} من {total}",
    chipOn: "شغّال",
    chipOff: "مقفول",
    chipCheck: "راجع",
    summarySep: " · ",
    otpOffSummary: "التأكيد بكود مقفول",
    otpBy_whatsapp: "كود على واتساب",
    otpBy_sms: "كود برسالة SMS",
    botOnSummary: "حماية البوتات شغّالة",
    botOffSummary: "حماية البوتات مقفولة",
    botCaptchaSummary: "تحدّي مخفي",
    countriesHidden_one: "بلد واحدة محجوبة",
    countriesHidden_two: "بلدين محجوبين",
    countriesHidden_few: "{n} بلاد محجوبة",
    countriesHidden_other: "{n} بلد محجوبة",
    alwaysStrictSummary: "أرقام موبايل حقيقية بس",
    alwaysBlockSummary: "المحظورين بيترفضوا",
    alwaysNone: "مفيش حاجة شغّالة هنا",
  },
} satisfies Messages;

export type RulesStrings = Record<keyof typeof RULES_STRINGS.en, string>;
