/**
 * The icons of the screens ported from zimos-additions, named by what each
 * glyph means here. Every one is a lucide-react icon, like the rest of the
 * dashboard; those screens import from this file, so a glyph is changed in
 * one place.
 *
 * Decorative icons are `aria-hidden`; an icon-only button has an `aria-label`
 * through `useT`. Arrows, carets and "back" flip in RTL (`rtl:rotate-180` /
 * `rtl:-scale-x-100`); a phone, a clock or a chart does not.
 */
import type { LucideIcon, LucideProps } from "lucide-react";

export type Icon = LucideIcon;
/** The same type under a name that never collides with a local `Icon` variable. */
export type IconComponent = LucideIcon;
export type IconProps = LucideProps;

export {
  ArrowDown as IconArrowDown,
  ArrowLeft as IconArrowLeft,
  ArrowUpRight as IconArrowOut,
  ArrowUp as IconArrowUp,
  Medal as IconAward,
  Bell as IconBell,
  Ban as IconBlock,
  Newspaper as IconBlog,
  ChevronDown as IconCaretDown,
  ChevronRight as IconCaretRight,
  ChevronUp as IconCaretUp,
  MessageCircle as IconChat,
  Check as IconCheck,
  ListChecks as IconChecklist,
  MousePointerClick as IconClick,
  X as IconClose,
  Coins as IconCoins,
  Copy as IconCopy,
  Crown as IconCrown,
  Users as IconCustomers,
  Trash2 as IconDelete,
  Monitor as IconDesktop,
  Tag as IconDiscounts,
  SeparatorHorizontal as IconDivider,
  PencilRuler as IconDraft,
  Pencil as IconEdit,
  Mail as IconEmail,
  CornerDownLeft as IconEnter,
  ExternalLink as IconExternal,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  FileQuestionMark as IconFileUnknown,
  FileUp as IconFileUp,
  ListFilter as IconFilter,
  Folder as IconFolder,
  Gift as IconGift,
  Ticket as IconGiftCards,
  Heading as IconHeading,
  Heart as IconHeart,
  Image as IconImage,
  Info as IconInfo,
  KeyRound as IconKey,
  Link as IconLink,
  List as IconListView,
  Lock as IconLock,
  Images as IconMedia,
  Minus as IconMinus,
  Ellipsis as IconMoreActions,
  NotebookPen as IconNote,
  Gift as IconOffers,
  ShoppingBag as IconOrders,
  Package as IconPackage,
  AppWindow as IconPage,
  Pilcrow as IconParagraph,
  Users as IconPeople,
  Phone as IconPhone,
  Smartphone as IconPhoneDevice,
  Pin as IconPin,
  Plus as IconPlus,
  Power as IconPower,
  Box as IconProduct,
  CircleQuestionMark as IconQuestions,
  ZoomIn as IconQuickLook,
  Quote as IconQuote,
  RefreshCw as IconRefresh,
  Ruler as IconRuler,
  Scale as IconScale,
  CalendarDays as IconSchedule,
  Search as IconSearch,
  Send as IconSend,
  ShieldCheck as IconShield,
  SlidersHorizontal as IconSliders,
  LoaderCircle as IconSpinner,
  CircleCheck as IconSuccess,
  Table as IconTable,
  Ticket as IconTicket,
  Network as IconTree,
  User as IconUser,
  UserPlus as IconUserAdd,
  Wallet as IconWallet,
  TriangleAlert as IconWarning,
  MessageCircle as IconWhatsApp,
} from "lucide-react";
