import type { Messages } from "@/i18n/LocaleContext";

/**
 * Picking and packing (handoff 226, 244 + 294, 249): the orders list's "Pick
 * list" and "Packing slips", the pick-list page, the order page's "Print
 * packing slip" and "Scan to pack", and the scanning page. Arabic is the
 * merchant's Egyptian, with the handoff's own wording where it gives one; a
 * customer's order is always «أوردر».
 */
export const PACKING_STRINGS = {
  en: {
    // The orders list and the order page.
    pickList: "Pick list",
    packingSlips: "Packing slips",
    printPackingSlip: "Print packing slip",
    scanToPack: "Scan to pack",
    packed: "Packed",
    pickReady: "Pick everything ready to ship",
    pickTooMany: "A pick list takes up to {max} orders at a time. Tick fewer orders.",
    slipsTooMany: "Packing slips print for up to {max} orders at a time. Tick fewer orders.",
    preparing: "Preparing…",

    // Packing slips dialog.
    slipsDescription: "One page per order to put in the parcel: the items, their quantities and where it goes.",
    size: "Paper size",
    sizeA5: "A5 — half a sheet",
    sizeA4: "A4 — a full sheet",
    note: "Note at the bottom",
    notePlaceholder: "Thank you for ordering from us!",
    noteHint: "Optional. Printed at the bottom of every slip, and kept on this browser for next time.",
    print: "Print",
    cancel: "Cancel",
    allCancelled: "These orders are cancelled",
    skipped_one: "1 cancelled order left out",
    skipped_other: "{n} cancelled orders left out",

    // Pick list page.
    back: "Orders",
    modeReady: "Every order that is ready to ship, oldest first.",
    modeSelection: "The orders you ticked in the orders list.",
    summary: "{orders} · {pieces}",
    refresh: "Refresh",
    mainStock: "Main stock",
    pickedCount: "{done} of {total} lines picked",
    pickedOf: "{done} of {total}",
    allPicked: "Everything is picked. Next: pack the orders.",
    goPack: "Pack the orders",
    viewLabel: "What the list shows",
    viewItems: "Items",
    viewOrders: "Orders",
    forOrders: "For orders",
    timesCount: "×{count}",
    moreOrders: "+{n}",
    noSku: "No SKU",
    lot: "Lot {code}",
    lotExpires: "expires {date}",
    lotExpired: "expired",
    lotTake: "take {count}",
    ordersTitle: "Orders in this list",
    ordersHint: "Pack each order by scanning its items.",
    colOrder: "Order",
    colPieces: "Pieces",
    colAction: "Next step",
    pack: "Pack",
    packOrder: "Scan to pack order {number}",
    openOrder: "Open order {number}",
    menuLabel: "Actions for order {number}",
    copyOrder: "Copy the order number",
    copiedOrder: "The order number is copied",
    copyFailed: "We couldn't copy that. Try again.",
    showAllOrders: "Show all {count}",
    emptySelectionTitle: "No orders picked",
    emptySelectionBody: "Tick orders in the orders list and press “Pick list”, or pick everything that is ready to ship.",
    emptyReadyTitle: "Nothing is ready to ship",
    emptyReadyBody: "An order shows up here once it is confirmed and waiting to ship.",
    emptyCancelledTitle: "Nothing to pick",
    emptyCancelledBody: "The orders you ticked are cancelled.",
    goOrders: "Go to orders",

    // Scan to pack page.
    backToOrder: "Back to the order",
    backToPickList: "Back to the pick list",
    stationLabel: "Packing station",
    scanLabel: "Scan the barcode, or type the SKU",
    scanPlaceholder: "Barcode or SKU",
    scanHint: "A scanner types the code and presses Enter by itself. This box stays ready for the next item.",
    add: "Add",
    progress: "{scanned} of {expected} scanned",
    ofCount: "{scanned} of {expected}",
    currentLabel: "Scan this next",
    allScanned: "Every barcode is scanned",
    allDoneTitle: "All set",
    allDoneBody: "Every item is in the parcel. Confirm, and the order is tagged “Packed”.",
    itemsTitle: "Items in this order",
    lineDone: "Done",
    overBy: "{count} more than ordered",
    signalUnknown: "This item isn't in the order",
    signalOver: "More than ordered",
    unknownCodes: "Codes that aren't in this order",
    removeUnknown: "Remove them",
    undo: "Undo last scan",
    startOver: "Start over",
    startedOver: "Cleared. Scan this order again from the first item.",
    removedUnknown: "The codes that aren't in this order are removed.",
    confirmAll: "All scanned — confirm packed",
    confirmAnyway: "Confirm anyway",
    confirmAnywayTitle: "Pack the order without every scan?",
    summaryMissing: "{count} not scanned",
    summaryUnknown: "{count} not in the order",
    why: "Why?",
    whyHint: "For example: an item has no barcode.",
    whyRequired: "Say why the order is packed without every scan.",
    confirming: "Confirming…",
    packedTitle: "Order packed",
    packedBody: "The order now carries the “Packed” tag. Filter the orders list by it to see everything packed.",
    viewPacked: "Packed orders",
    alreadyPacked: "This order is already marked as packed.",
    cancelledTitle: "This order is cancelled",
    cancelledBody: "There is nothing to pack.",
    manualTitle: "No barcode — check by hand",
    manualHint: "These lines can't be scanned. Tick each one once it is in the parcel.",
    manualFirst: "Tick the items without a barcode first.",
    manualLeft: "{count} to tick",
    manualAllTicked: "All ticked",
    scansTitle: "Scanned so far",
    scans_one: "1 scan",
    scans_other: "{n} scans",
    removeScan: "Remove the scan {code}",
    notInOrder: "Not in the order",
    showAllScans: "Show all {count}",
    tooManyScans: "An order takes up to {max} scans. Start over.",
    notComplete: "Something is still missing, extra or wrong. Check the items.",
    checkFailed: "We couldn't check that scan. It is kept — try again.",
    retry: "Try again",
    barcode: "Barcode",
  },
  ar: {
    pickList: "قائمة التجهيز",
    packingSlips: "ورق التجهيز",
    printPackingSlip: "اطبع ورقة التجهيز",
    scanToPack: "تغليف بالسكانر",
    packed: "اتغلّف",
    pickReady: "جهّز كل الجاهز للشحن",
    pickTooMany: "قائمة التجهيز بتاخد لحد {max} أوردر في المرة. اختار أوردرات أقل.",
    slipsTooMany: "ورق التجهيز بيتطبع لحد {max} أوردر في المرة. اختار أوردرات أقل.",
    preparing: "بنجهّز…",

    slipsDescription: "ورقة لكل أوردر تتحط جوه الطرد: المنتجات وكمياتها والعنوان اللي رايحله.",
    size: "مقاس الورق",
    sizeA5: "A5 — نص ورقة",
    sizeA4: "A4 — ورقة كاملة",
    note: "رسالة في آخر الورقة",
    notePlaceholder: "شكرًا إنك اشتريت مننا!",
    noteHint: "اختياري. بتتطبع في آخر كل ورقة، وبنفتكرها على المتصفح ده للمرة الجاية.",
    print: "اطبع",
    cancel: "إلغاء",
    allCancelled: "الأوردرات دي ملغية",
    skipped_one: "اتشال أوردر ملغي واحد",
    skipped_two: "اتشال أوردرين ملغيين",
    skipped_few: "اتشال {n} أوردرات ملغية",
    skipped_other: "اتشال {n} أوردر ملغي",

    back: "الأوردرات",
    modeReady: "كل الأوردرات الجاهزة للشحن، الأقدم الأول.",
    modeSelection: "الأوردرات اللي علّمت عليها في قائمة الأوردرات.",
    summary: "{orders} · {pieces}",
    refresh: "تحديث",
    mainStock: "المخزن الرئيسي",
    pickedCount: "اتجهّز {done} من {total}",
    pickedOf: "{done} من {total}",
    allPicked: "كله اتجهّز. الخطوة الجاية: غلّف الأوردرات.",
    goPack: "غلّف الأوردرات",
    viewLabel: "القائمة بتعرض إيه",
    viewItems: "المنتجات",
    viewOrders: "الأوردرات",
    forOrders: "للأوردرات",
    timesCount: "×{count}",
    moreOrders: "+{n}",
    noSku: "من غير SKU",
    lot: "دفعة {code}",
    lotExpires: "تنتهي {date}",
    lotExpired: "منتهية",
    lotTake: "خد {count}",
    ordersTitle: "الأوردرات في القائمة دي",
    ordersHint: "غلّف كل أوردر بسكان منتجاته.",
    colOrder: "الأوردر",
    colPieces: "القطع",
    colAction: "الخطوة الجاية",
    pack: "غلّف",
    packOrder: "غلّف الأوردر {number} بالسكانر",
    openOrder: "افتح الأوردر {number}",
    menuLabel: "إجراءات الأوردر {number}",
    copyOrder: "انسخ رقم الأوردر",
    copiedOrder: "رقم الأوردر اتنسخ",
    copyFailed: "معرفناش ننسخ. جرّب تاني.",
    showAllOrders: "اعرض الـ {count} كلهم",
    emptySelectionTitle: "مفيش أوردرات مختارة",
    emptySelectionBody: "علّم على الأوردرات في قائمة الأوردرات ودوس «قائمة التجهيز»، أو جهّز كل الجاهز للشحن.",
    emptyReadyTitle: "مفيش أوردرات جاهزة للشحن",
    emptyReadyBody: "الأوردر بيظهر هنا بعد ما يتأكد ويبقى مستني الشحن.",
    emptyCancelledTitle: "مفيش حاجة تتجهّز",
    emptyCancelledBody: "الأوردرات اللي علّمت عليها ملغية.",
    goOrders: "روح للأوردرات",

    backToOrder: "رجوع للأوردر",
    backToPickList: "رجوع لقائمة التجهيز",
    stationLabel: "محطة التغليف",
    scanLabel: "اسكن الباركود أو اكتب الـ SKU",
    scanPlaceholder: "باركود أو SKU",
    scanHint: "السكانر بيكتب الكود ويدوس Enter لوحده. الخانة دي بتفضل جاهزة للمنتج اللي بعده.",
    add: "ضيف",
    progress: "اتسكن {scanned} من {expected}",
    ofCount: "{scanned} من {expected}",
    currentLabel: "الدور على",
    allScanned: "كل الباركودات اتسكنت",
    allDoneTitle: "كله تمام",
    allDoneBody: "كل المنتجات في الطرد. أكّد، والأوردر هيتعلّم عليه «اتغلّف».",
    itemsTitle: "منتجات الأوردر",
    lineDone: "تمام",
    overBy: "{count} زيادة عن المطلوب",
    signalUnknown: "المنتج ده مش في الأوردر",
    signalOver: "زيادة عن المطلوب",
    unknownCodes: "أكواد مش في الأوردر ده",
    removeUnknown: "شيلهم",
    undo: "تراجع",
    startOver: "ابدأ من الأول",
    startedOver: "اتمسح. اسكن الأوردر تاني من أول منتج.",
    removedUnknown: "الأكواد اللي مش في الأوردر ده اتشالت.",
    confirmAll: "كله تمام — تأكيد التغليف",
    confirmAnyway: "تأكيد رغم النقص",
    confirmAnywayTitle: "تغلّف الأوردر من غير ما كله يتسكن؟",
    summaryMissing: "{count} متسكنش",
    summaryUnknown: "{count} مش في الأوردر",
    why: "ليه؟",
    whyHint: "مثلًا: منتج من غير باركود.",
    whyRequired: "اكتب ليه الأوردر اتغلّف من غير ما كله يتسكن.",
    confirming: "بنأكّد…",
    packedTitle: "الأوردر اتغلّف",
    packedBody: "اتعلّم عليه «اتغلّف». فلتر قائمة الأوردرات بالتاج ده عشان تشوف كل اللي اتغلّف.",
    viewPacked: "الأوردرات اللي اتغلّفت",
    alreadyPacked: "الأوردر ده متعلّم إنه اتغلّف قبل كده.",
    cancelledTitle: "الأوردر ده ملغي",
    cancelledBody: "مفيش حاجة تتغلّف.",
    manualTitle: "من غير باركود — راجعها بإيدك",
    manualHint: "المنتجات دي مبتتسكنش. علّم على كل واحد لما تحطه في الطرد.",
    manualFirst: "علّم على المنتجات اللي من غير باركود الأول.",
    manualLeft: "لسه {count}",
    manualAllTicked: "كله اتعلّم",
    scansTitle: "اللي اتسكن",
    scans_one: "سكانة واحدة",
    scans_two: "سكانتين",
    scans_few: "{n} سكانات",
    scans_other: "{n} سكانة",
    removeScan: "شيل السكانة {code}",
    notInOrder: "مش في الأوردر",
    showAllScans: "اعرض الـ {count} كلهم",
    tooManyScans: "الأوردر بياخد لحد {max} سكانة. ابدأ من الأول.",
    notComplete: "لسه فيه نقص أو زيادة أو منتج غلط. راجع المنتجات.",
    checkFailed: "معرفناش نراجع السكانة دي. هي محفوظة — جرّب تاني.",
    retry: "جرّب تاني",
    barcode: "باركود",
  },
} satisfies Messages;

export type PackingStrings = Record<keyof (typeof PACKING_STRINGS)["en"], string>;
