import type { PriceScheduleItemState, PriceScheduleStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Scheduled sales (handoff 227): the list, the editor with its preview, a sale's page, and the product page's note. */
export const PRICE_SCHEDULE_STRINGS = {
  en: {
    back: "Offers",
    openSaleNamed: "Open {name}",
    openSaleMenu: "Open the sale",
    window: "From {from} to {to}",
    title: "Scheduled sales",
    description: "A sale that starts and ends by itself. The real prices change at the start and come back at the end, so the cart, checkout and ads all agree.",
    newSale: "New sale",
    filterLabel: "Filter sales by status",
    filterAll: "All",
    status_scheduled: "Scheduled",
    status_active: "Running",
    status_ended: "Ended",
    status_cancelled: "Cancelled",
    colSale: "Sale",
    colStatus: "Status",
    colOnSale: "On sale",
    colDiscount: "Discount",
    colStarts: "Starts",
    colEnds: "Ends",
    noEnd: "No end",
    variants_one: "1 variant",
    variants_other: "{n} variants",
    targetCollection: "Collection: {name}",
    targetCollectionUnknown: "A collection",
    changePercent: "{value}% off",
    changeAmount: "{amount} off",
    changeSet: "Price {amount}",
    emptyTitle: "No scheduled sales yet",
    emptyHint: "Set a sale up ahead of time: prices drop when it starts and come back when it ends, by themselves.",
    noMatchTitle: "No sales with this status",
    showAll: "Show all sales",
    viewOnly: "You can see scheduled sales, but setting them up needs permission to manage products.",
    // editor
    newTitle: "New sale",
    backToList: "Scheduled sales",
    name: "Sale name",
    namePlaceholder: "Weekend sale",
    nameFor: "Sale on {product}",
    onSaleTitle: "What's on sale",
    onSaleHint: "Products, single variants, or everything in one collection. A collection's products are read when the sale starts.",
    targetLabel: "Put on sale",
    target_products: "Products",
    target_variants: "Variants",
    target_collection: "Collection",
    productsLabel: "Products on sale",
    variantsLabel: "Variants on sale",
    variantsEmpty: "No variants added yet.",
    removeVariant: "Remove {name}",
    collectionLabel: "Collection on sale",
    chooseCollection: "Choose a collection",
    noCollections: "This store has no collections yet.",
    discountTitle: "The discount",
    modeLabel: "Kind of discount",
    mode_percent_off: "% off",
    mode_amount_off: "Amount off",
    mode_set_price: "Set price",
    value_percent_off: "Percent off",
    value_amount_off: "Amount off each piece",
    value_set_price: "Sale price of each piece",
    showWasPrice: "Show the old price crossed out",
    showWasPriceHint: "While the sale runs, the price before it shows crossed out beside the sale price.",
    whenTitle: "When",
    startsAt: "Starts",
    endsAt: "Ends",
    endsHint: "Leave it empty for a sale with no end.",
    clearEnd: "No end",
    storeTime: "On your store's clock ({zone}).",
    startsNowHint: "A start that has already passed starts the sale as soon as you save.",
    previewTitle: "Preview",
    previewHint: "What the sale would do to today's prices.",
    previewEmpty: "Choose what's on sale and the discount to see the prices.",
    previewNone: "Nothing here can go on sale: no active variants.",
    previewFailed: "The preview couldn't be loaded.",
    onSale_one: "1 variant on sale",
    onSale_other: "{n} variants on sale",
    more_one: "…and 1 more.",
    more_other: "…and {n} more.",
    colProduct: "Product",
    colPriceNow: "Price now",
    colSalePrice: "Sale price",
    unchanged: "No change",
    unknownProduct: "Deleted product",
    nameError: "Give the sale a name.",
    targetError: "Choose what's on sale.",
    percentError: "A whole number from 1 to 90.",
    amountError: "Enter an amount above zero.",
    priceError: "Enter a price, 0 or more.",
    startError: "Choose when the sale starts.",
    endError: "The end must be after the start, and still ahead.",
    targetGone: "Something you chose is no longer in this store. Choose again.",
    schedule: "Schedule sale",
    scheduling: "Saving…",
    createdToast: "Sale scheduled.",
    startedToast: "The sale is running — prices changed.",
    savedToast: "Sale saved.",
    lockedNotice: "This sale has started, so it can't be edited any more.",
    // a sale's page
    fallbackTitle: "Sale",
    stop: "Stop sale",
    stopTitle: "Stop “{name}”?",
    stopBody: "Prices go back now.",
    cancelSale: "Cancel sale",
    cancelTitle: "Cancel “{name}”?",
    cancelBody: "It won't start. This can't be undone.",
    keep: "Keep it",
    working: "Working…",
    stoppedToast: "Sale stopped — prices are back.",
    cancelledToast: "Sale cancelled.",
    overNotice: "This sale is already over — this is how it stands now.",
    saveFirst: "Save your changes first.",
    factsTitle: "Details",
    factOnSale: "On sale",
    factDiscount: "Discount",
    factStarts: "Starts",
    factEnds: "Ends",
    factApplied: "Prices changed",
    factReverted: "Prices went back",
    factWasPrice: "Old price",
    wasPriceShown: "Shown crossed out",
    wasPriceHidden: "Not shown",
    pricesTitle: "Prices",
    pricesHint: "Each variant's price before the sale and during it.",
    colBefore: "Before",
    colDuring: "Sale price",
    colState: "Result",
    state_applied: "On sale",
    state_restored: "Price is back",
    state_kept: "Left as it is",
    state_skipped: "Skipped",
    stateHint_kept: "The price was changed during the sale, so it was left.",
    stateHint_skipped: "Already in another running sale, or the sale changes nothing for it.",
    noItems: "This sale reached no variants.",
    neverStarted: "This sale never started, so no price changed.",
    // the product page's note
    noteTitle: "Running sale",
    onSaleUntil: "On sale until {date}",
    onSaleNoEnd: "On sale, with no end date",
    noteWarning: "A price you change now stays as you set it after the sale ends.",
    openSale: "Open the sale",
    singleVariant: "This product",
  },
  ar: {
    back: "العروض",
    openSaleNamed: "افتح {name}",
    openSaleMenu: "افتح التخفيض",
    window: "من {from} لحد {to}",
    title: "التخفيضات المجدولة",
    description: "تخفيض بيبدأ ويخلص لوحده. الأسعار نفسها بتتغير في البداية وبترجع في النهاية، فالسلة وإتمام الطلب والإعلانات كلهم بنفس السعر.",
    newSale: "تخفيض جديد",
    filterLabel: "فلتر التخفيضات بالحالة",
    filterAll: "الكل",
    status_scheduled: "مستني",
    status_active: "شغّال",
    status_ended: "خلص",
    status_cancelled: "اتلغى",
    colSale: "التخفيض",
    colStatus: "الحالة",
    colOnSale: "عليه تخفيض",
    colDiscount: "الخصم",
    colStarts: "يبدأ",
    colEnds: "يخلص",
    noEnd: "من غير نهاية",
    variants_one: "صنف واحد",
    variants_two: "صنفين",
    variants_few: "{n} أصناف",
    variants_other: "{n} صنف",
    targetCollection: "مجموعة: {name}",
    targetCollectionUnknown: "مجموعة",
    changePercent: "خصم {value}%",
    changeAmount: "خصم {amount}",
    changeSet: "السعر {amount}",
    emptyTitle: "لسه مفيش تخفيضات مجدولة",
    emptyHint: "جهّز التخفيض من بدري: الأسعار بتنزل لما يبدأ وبترجع لما يخلص، لوحدها.",
    noMatchTitle: "مفيش تخفيضات بالحالة دي",
    showAll: "اعرض كل التخفيضات",
    viewOnly: "تقدر تشوف التخفيضات المجدولة، لكن عملها محتاج صلاحية إدارة المنتجات.",
    newTitle: "تخفيض جديد",
    backToList: "التخفيضات المجدولة",
    name: "اسم التخفيض",
    namePlaceholder: "تخفيض نهاية الأسبوع",
    nameFor: "تخفيض على {product}",
    onSaleTitle: "إيه اللي عليه تخفيض",
    onSaleHint: "منتجات، أصناف بعينها، أو كل اللي في مجموعة. منتجات المجموعة بتتحدد لما التخفيض يبدأ.",
    targetLabel: "التخفيض على",
    target_products: "منتجات",
    target_variants: "أصناف",
    target_collection: "مجموعة",
    productsLabel: "المنتجات اللي عليها التخفيض",
    variantsLabel: "الأصناف اللي عليها التخفيض",
    variantsEmpty: "لسه مضفتش أصناف.",
    removeVariant: "شيل {name}",
    collectionLabel: "المجموعة اللي عليها التخفيض",
    chooseCollection: "اختار مجموعة",
    noCollections: "المتجر ده لسه مفيهوش مجموعات.",
    discountTitle: "الخصم",
    modeLabel: "نوع الخصم",
    mode_percent_off: "خصم %",
    mode_amount_off: "خصم مبلغ",
    mode_set_price: "سعر ثابت",
    value_percent_off: "نسبة الخصم",
    value_amount_off: "المبلغ المخصوم من القطعة",
    value_set_price: "سعر القطعة في التخفيض",
    showWasPrice: "اعرض السعر القديم مشطوب",
    showWasPriceHint: "طول ما التخفيض شغال، السعر اللي قبله بيظهر مشطوب جنب سعر التخفيض.",
    whenTitle: "الميعاد",
    startsAt: "يبدأ",
    endsAt: "يخلص",
    endsHint: "سيبه فاضي لو التخفيض من غير نهاية.",
    clearEnd: "من غير نهاية",
    storeTime: "بتوقيت متجرك ({zone}).",
    startsNowHint: "لو ميعاد البداية عدّى، التخفيض هيبدأ أول ما تحفظ.",
    previewTitle: "المعاينة",
    previewHint: "اللي التخفيض هيعمله في أسعار النهارده.",
    previewEmpty: "اختار اللي عليه التخفيض والخصم علشان تشوف الأسعار.",
    previewNone: "مفيش حاجة هنا ينفع عليها تخفيض: مفيش أصناف شغّالة.",
    previewFailed: "معرفناش نحمّل المعاينة.",
    onSale_one: "صنف واحد عليه تخفيض",
    onSale_two: "صنفين عليهم تخفيض",
    onSale_few: "{n} أصناف عليها تخفيض",
    onSale_other: "{n} صنف عليه تخفيض",
    more_one: "…وواحد كمان.",
    more_two: "…واتنين كمان.",
    more_few: "…و{n} كمان.",
    more_other: "…و{n} كمان.",
    colProduct: "المنتج",
    colPriceNow: "السعر دلوقتي",
    colSalePrice: "سعر التخفيض",
    unchanged: "من غير تغيير",
    unknownProduct: "منتج ممسوح",
    nameError: "اكتب اسم للتخفيض.",
    targetError: "اختار اللي عليه التخفيض.",
    percentError: "رقم صحيح من 1 لـ 90.",
    amountError: "اكتب مبلغ أكبر من صفر.",
    priceError: "اكتب سعر، صفر أو أكتر.",
    startError: "اختار ميعاد بداية التخفيض.",
    endError: "النهاية لازم تبقى بعد البداية، ولسه مجتش.",
    targetGone: "حاجة من اللي اخترته مبقتش في المتجر. اختار تاني.",
    schedule: "جدول التخفيض",
    scheduling: "بنحفظ…",
    createdToast: "التخفيض اتجدول.",
    startedToast: "التخفيض شغال — الأسعار اتغيرت.",
    savedToast: "التخفيض اتحفظ.",
    lockedNotice: "التخفيض بدأ، فمبقاش ينفع يتعدل.",
    fallbackTitle: "تخفيض",
    stop: "وقّف التخفيض",
    stopTitle: "توقّف «{name}»؟",
    stopBody: "الأسعار هترجع زي ما كانت.",
    cancelSale: "الغي التخفيض",
    cancelTitle: "تلغي «{name}»؟",
    cancelBody: "مش هيبدأ. مينفعش ترجع في الإلغاء.",
    keep: "سيبه",
    working: "ثانية واحدة…",
    stoppedToast: "التخفيض وقف — الأسعار رجعت.",
    cancelledToast: "التخفيض اتلغى.",
    overNotice: "التخفيض ده خلص خلاص — دي حالته دلوقتي.",
    saveFirst: "احفظ تعديلاتك الأول.",
    factsTitle: "التفاصيل",
    factOnSale: "عليه تخفيض",
    factDiscount: "الخصم",
    factStarts: "يبدأ",
    factEnds: "يخلص",
    factApplied: "الأسعار اتغيرت",
    factReverted: "الأسعار رجعت",
    factWasPrice: "السعر القديم",
    wasPriceShown: "ظاهر مشطوب",
    wasPriceHidden: "مش ظاهر",
    pricesTitle: "الأسعار",
    pricesHint: "سعر كل صنف قبل التخفيض ووقت التخفيض.",
    colBefore: "قبل",
    colDuring: "سعر التخفيض",
    colState: "النتيجة",
    state_applied: "عليه التخفيض",
    state_restored: "السعر رجع",
    state_kept: "اتساب زي ما هو",
    state_skipped: "اتخطى",
    stateHint_kept: "السعر اتغير وقت التخفيض، فاتساب زي ما هو.",
    stateHint_skipped: "كان في تخفيض تاني شغال، أو التخفيض مبيغيرش سعره.",
    noItems: "التخفيض ده موصلش لأي صنف.",
    neverStarted: "التخفيض ده مبدأش، فمفيش سعر اتغير.",
    noteTitle: "تخفيض شغال",
    onSaleUntil: "في تخفيض لحد {date}",
    onSaleNoEnd: "في تخفيض من غير تاريخ نهاية",
    noteWarning: "السعر اللي تغيّره دلوقتي هيفضل زي ما حطيته بعد ما التخفيض يخلص.",
    openSale: "افتح التخفيض",
    singleVariant: "المنتج ده",
  },
} satisfies Messages;

export type PriceScheduleStrings = (typeof PRICE_SCHEDULE_STRINGS)["en"];

export const SCHEDULE_STATUS_TONE: Record<PriceScheduleStatus, "info" | "success" | "neutral"> = {
  scheduled: "info",
  active: "success",
  ended: "neutral",
  cancelled: "neutral",
};

export const SCHEDULE_STATUS_KEY = {
  scheduled: "status_scheduled",
  active: "status_active",
  ended: "status_ended",
  cancelled: "status_cancelled",
} as const satisfies Record<PriceScheduleStatus, keyof PriceScheduleStrings>;

export const ITEM_STATE_TONE: Record<PriceScheduleItemState, "success" | "neutral" | "warning"> = {
  applied: "success",
  restored: "neutral",
  kept: "warning",
  skipped: "neutral",
};

export const ITEM_STATE_KEY = {
  applied: "state_applied",
  restored: "state_restored",
  kept: "state_kept",
  skipped: "state_skipped",
} as const satisfies Record<PriceScheduleItemState, keyof PriceScheduleStrings>;
