import type { AdPlatformPixel, XCapiKey, XPixelEvent } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Wording for the ad platforms added to the pixel form: X, Taboola, Outbrain,
 * Kwai, Reddit and Microsoft Ads (257). Read with
 * `useT(AD_PLATFORM_PIXEL_STRINGS)`. The field names X's developer portal
 * shows stay in English: that is what the merchant copies from.
 */
export const AD_PLATFORM_PIXEL_STRINGS = {
  en: {
    platform: "Platform",
    idLabel_x: "Pixel ID",
    idHint_x: "Pixel ID from X Ads",
    idLabel_taboola: "Account ID",
    idHint_taboola: "Account ID from Taboola Ads",
    idLabel_outbrain: "Marketer ID",
    idHint_outbrain: "Marketer ID from Outbrain",
    idLabel_kwai: "Pixel ID",
    idHint_kwai: "Pixel ID from Kwai Ads",
    idLabel_reddit: "Pixel ID",
    idHint_reddit: "Pixel ID from Reddit Ads — it starts with a2_ or t2_",
    idLabel_microsoft: "UET tag ID",
    idHint_microsoft: "UET tag ID from Microsoft Advertising",
    browserOnly: "This pixel works in the browser only",
    eventIds: "Event IDs",
    eventIdsHint: "Create each event in X Ads Manager and paste its ID here. An event without an ID isn't sent to X.",
    eventCol: "Event",
    eventIdCol: "X event ID",
    eventIdFor: "X event ID for “{event}”",
    eventIdInvalid: "An X event ID looks like tw-o1abc-o2def.",
    ev_purchase: "Purchase",
    ev_lead: "Lead",
    ev_add_to_cart: "Add to cart",
    ev_begin_checkout: "Checkout started",
    ev_add_payment_info: "Payment method chosen",
    ev_view_content: "Product view",
    ev_page_view: "Page view",
    capiEnabled: "Send events from the server (Conversions API)",
    sandboxChip: "Sandbox — not sent yet",
    sandboxHelp: "Events are built and logged only, until this platform is switched on",
    token_reddit: "Conversions access token",
    tokenHint_reddit: "From Reddit Ads → Events Manager.",
    token_microsoft: "Conversions API token",
    tokenHint_microsoft: "The UET tag's own token: Microsoft Advertising → UET tag → Conversions API.",
    tokenKeep: "A token is saved ({mask}). Leave empty to keep it.",
    tokenRequired: "Paste the token to turn server events on.",
    testMode: "Test mode",
    testModeHint: "While on, Reddit takes the events as tests and does not count them.",
    xKeys: "X API keys",
    xKeysHint: "The four keys of the X developer app that has access to your ad account.",
    xKey_consumerKey: "API Key (consumer key)",
    xKey_consumerSecret: "API Key Secret (consumer secret)",
    xKey_accessToken: "Access Token",
    xKey_accessTokenSecret: "Access Token Secret",
    xKeysKeep: "Keys are saved ({mask}). Leave all four empty to keep them.",
    xKeysRequired: "Fill in the four keys to turn server events on.",
    xKeysInvalid: "Fill in all four keys, with no spaces or colons inside.",
    xNeedsEventIds: "Conversions go to X only for the events that have an X event ID.",
    testSkipped: "X has no test event — the keys are checked with the first order",
    pixelExists: "This pixel is already added to the store.",
    pixelLimit: "The store has reached the number of pixels it can hold. Remove one you no longer use first.",
  },
  ar: {
    platform: "المنصة",
    idLabel_x: "رقم البيكسل (Pixel ID)",
    idHint_x: "رقم البيكسل من X Ads",
    idLabel_taboola: "رقم الحساب (Account ID)",
    idHint_taboola: "رقم الحساب من Taboola Ads",
    idLabel_outbrain: "رقم المعلن (Marketer ID)",
    idHint_outbrain: "رقم المعلن من Outbrain",
    idLabel_kwai: "رقم البيكسل (Pixel ID)",
    idHint_kwai: "رقم البيكسل من Kwai Ads",
    idLabel_reddit: "رقم البيكسل (Pixel ID)",
    // ‎ after each underscore keeps it on the right of "a2" / "t2" inside the Arabic sentence.
    idHint_reddit: "رقم البيكسل من Reddit Ads، يبدأ بـ a2_‎ أو t2_‎",
    idLabel_microsoft: "رقم UET tag",
    idHint_microsoft: "رقم UET tag من Microsoft Advertising",
    browserOnly: "هذا البيكسل يعمل من المتصفح فقط",
    eventIds: "رموز الأحداث",
    eventIdsHint: "أنشئ كل حدث في X Ads Manager والصق رمزه هنا. الحدث الذي ليس له رمز لا يُرسل إلى X.",
    eventCol: "الحدث",
    eventIdCol: "رمز الحدث في X",
    eventIdFor: "رمز حدث «{event}» في X",
    eventIdInvalid: "رمز الحدث في X يكون بهذا الشكل: tw-o1abc-o2def",
    ev_purchase: "شراء",
    ev_lead: "عميل محتمل",
    ev_add_to_cart: "إضافة إلى السلة",
    ev_begin_checkout: "بدء الطلب",
    ev_add_payment_info: "اختيار وسيلة الدفع",
    ev_view_content: "مشاهدة منتج",
    ev_page_view: "فتح صفحة",
    capiEnabled: "إرسال الأحداث من الخادم (Conversions API)",
    sandboxChip: "تجريبي: لا يُرسل بعد",
    sandboxHelp: "تُجهَّز الأحداث وتُسجَّل فقط، إلى أن نفعّل هذه المنصة",
    token_reddit: "رمز التحويلات (Conversions access token)",
    tokenHint_reddit: "من Reddit Ads ← Events Manager.",
    token_microsoft: "رمز Conversions API",
    tokenHint_microsoft: "رمز UET tag نفسه: Microsoft Advertising ← UET tag ← Conversions API.",
    tokenKeep: "يوجد رمز محفوظ ({mask}). اتركه فارغًا ليبقى كما هو.",
    tokenRequired: "الصق الرمز لتفعيل أحداث الخادم.",
    testMode: "وضع الاختبار",
    testModeHint: "ما دام هذا مفعّلًا، يستقبل Reddit الأحداث كتجربة ولا يحتسبها.",
    xKeys: "مفاتيح X",
    xKeysHint: "المفاتيح الأربعة لتطبيق X الذي له صلاحية على حسابك الإعلاني.",
    xKey_consumerKey: "API Key (consumer key)",
    xKey_consumerSecret: "API Key Secret (consumer secret)",
    xKey_accessToken: "Access Token",
    xKey_accessTokenSecret: "Access Token Secret",
    xKeysKeep: "توجد مفاتيح محفوظة ({mask}). اترك الأربعة فارغة لتبقى كما هي.",
    xKeysRequired: "أدخل المفاتيح الأربعة لتفعيل أحداث الخادم.",
    xKeysInvalid: "أدخل المفاتيح الأربعة كلها، بدون مسافات ولا علامة :",
    xNeedsEventIds: "تُرسل التحويلات إلى X للأحداث التي لها رمز حدث فقط.",
    testSkipped: "ليس لدى X حدث تجريبي، وسيُتحقق من المفاتيح مع أول طلب",
    pixelExists: "هذا البيكسل مضاف إلى المتجر من قبل.",
    pixelLimit: "وصل المتجر إلى الحد الأقصى لعدد البيكسلات. احذف واحدًا لا تحتاجه أولًا.",
  },
} satisfies Messages;

export type AdPlatformPixelText = Record<keyof (typeof AD_PLATFORM_PIXEL_STRINGS)["en"], string>;

export const idLabelKey = (platform: AdPlatformPixel) => `idLabel_${platform}` as const;
export const idHintKey = (platform: AdPlatformPixel) => `idHint_${platform}` as const;
export const eventKey = (event: XPixelEvent) => `ev_${event}` as const;
export const xKeyLabel = (key: XCapiKey) => `xKey_${key}` as const;
