import type { Messages } from "@/i18n/LocaleContext";

/**
 * Wording for the pixels of Marketing → Tracking tools: the list, a pixel's
 * preview and its form. Read with `useT(PIXEL_STRINGS)`.
 */
export const PIXEL_STRINGS = {
  en: {
    listTitle: "Pixels and tags",
    add: "Add pixel",
    emptyTitle: "No pixels yet",
    emptyBody: "A pixel lets your ad platform see the visits and orders of this store. Add your first one.",
    capiWarning:
      "If you are not sure what the Conversions API is, leave it off. Turning it on while the same pixel is also connected somewhere else can count every order twice.",
    eventsNote:
      "Your store sends the standard events on its own: page view, product view, add to cart, checkout started, and purchase with the real order total.",
    colPlatform: "Platform",
    colId: "ID",
    colCapi: "Server events",
    colStatus: "Status",
    colAction: "Action",
    capiOn: "On",
    capiOff: "Off",
    capiNone: "Browser only",
    chipCapiOn: "Server events on",
    chipCapiFailing: "Server events failing",
    capiError: "Last send failed: {error}",
    capiLast: "Last sent {when}",
    scope: "Applies to",
    scopeAll: "Whole store",
    scopeFunnels_one: "1 funnel",
    scopeFunnels_other: "{n} funnels",
    scopeProducts_one: "1 product",
    scopeProducts_other: "{n} products",
    active: "Running",
    paused: "Paused",
    status: "Status",
    note: "Note",
    testCodeFact: "Test event code",
    edit: "Edit",
    delete: "Delete",
    deletePixel: "Delete this pixel",
    pause: "Pause",
    resume: "Resume",
    peek: "Preview the pixel {name}",
    menuLabel: "Actions for this pixel",
    copyId: "Copy the ID",
    copiedId: "The ID is copied",
    pausedToast: "{name} is paused. It gets no events until you resume it.",
    resumedToast: "{name} is running again.",
    addTitle: "Add a pixel",
    editTitle: "Edit pixel",
    pixelId: "Pixel / tag ID",
    idRequired: "Paste the ID from your ad platform.",
    invalid: "That doesn't look like a valid ID for this platform.",
    label: "Note",
    labelHint: "Only you see this — e.g. the ad account it belongs to.",
    capiEnabled: "Also send orders from the server (Conversions API)",
    capiToken: "Access token",
    capiTokenKeep: "A token is saved ({mask}). Leave empty to keep it.",
    capiTokenGa4: "For GA4 this is the Measurement Protocol API secret.",
    capiTokenRequired: "Paste the token to turn server events on.",
    testCode: "Test event code",
    testCodeHint: "Optional. While set, server events show up under Test events instead of counting as real ones.",
    adsLabel: "Purchase conversion label",
    adsLabelHint: "Google Ads → Goals → Conversions → your action → Tag setup → the part after the slash in send_to",
    adsLeadLabel: "Lead conversion label",
    adsLeadLabelHint: "Used when the store or a funnel reports orders as Lead.",
    adsLabelInvalid: "Use 4 to 60 letters, digits, - or _.",
    adsLabelNeedsAds: "A conversion label needs a Google Ads id (AW-…)",
    scopeFunnels: "Some funnels",
    scopeProducts: "Some products",
    chooseFunnels: "Choose the funnels",
    chooseProducts: "Choose the products",
    scopeEmpty: "Nothing to choose from yet.",
    scopeRequired: "Choose at least one.",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    created: "Pixel added. It is live on your store now.",
    updated: "Pixel saved.",
    deleted: "Pixel removed.",
    deleteTitle: "Remove this pixel?",
    deleteBody: "{name} {id} will stop receiving events from your store. Events it already received stay on the ad platform.",
    deleting: "Removing…",
    test: "Send test event",
    testing: "Sending…",
    testOk: "Test event accepted by {name}.",
    testOkCode: "Test event accepted — look under Test events in {name}.",
    testFailed: "{name} refused the test event: {error}",
  },
  ar: {
    listTitle: "البيكسلات والأكواد",
    add: "ضيف بيكسل",
    emptyTitle: "لسه مفيش بيكسلات",
    emptyBody: "البيكسل بيخلّي منصة الإعلانات تشوف زيارات وأوردرات متجرك. ضيف أول واحد.",
    capiWarning:
      "لو مش متأكد إيه هو الـ Conversions API سيبه مقفول. لو شغّلته والبيكسل نفسه مربوط في مكان تاني، كل أوردر ممكن يتحسب مرتين.",
    eventsNote: "متجرك بيبعت الأحداث المعروفة لوحده: فتح صفحة، مشاهدة منتج، إضافة للسلة، بدء الأوردر، والشرا بقيمة الأوردر الحقيقية.",
    colPlatform: "المنصة",
    colId: "الرقم",
    colCapi: "أحداث السيرفر",
    colStatus: "الحالة",
    colAction: "إجراء",
    capiOn: "شغّالة",
    capiOff: "مقفولة",
    capiNone: "المتصفح بس",
    chipCapiOn: "أحداث السيرفر شغّالة",
    chipCapiFailing: "أحداث السيرفر بتفشل",
    capiError: "آخر إرسال فشل: {error}",
    capiLast: "آخر إرسال {when}",
    scope: "شغّال على",
    scopeAll: "المتجر كله",
    scopeFunnels_one: "مسار بيع واحد",
    scopeFunnels_two: "مسارين بيع",
    scopeFunnels_few: "{n} مسارات بيع",
    scopeFunnels_other: "{n} مسار بيع",
    scopeProducts_one: "منتج واحد",
    scopeProducts_two: "منتجين",
    scopeProducts_few: "{n} منتجات",
    scopeProducts_other: "{n} منتج",
    active: "شغّال",
    paused: "متوقف",
    status: "الحالة",
    note: "ملاحظة",
    testCodeFact: "كود الأحداث التجريبية",
    edit: "عدّل",
    delete: "امسح",
    deletePixel: "امسح البيكسل ده",
    pause: "وقّفه",
    resume: "شغّله",
    peek: "معاينة بيكسل {name}",
    menuLabel: "إجراءات البيكسل",
    copyId: "انسخ الرقم",
    copiedId: "الرقم اتنسخ",
    pausedToast: "{name} اتوقف. مش هيوصله أحداث لحد ما تشغّله.",
    resumedToast: "{name} اشتغل تاني.",
    addTitle: "ضيف بيكسل",
    editTitle: "عدّل البيكسل",
    pixelId: "رقم البيكسل / الكود",
    idRequired: "الصق الرقم من منصة الإعلانات بتاعتك.",
    invalid: "الرقم ده مش شكل أرقام المنصة دي. راجعه وانسخه تاني.",
    label: "ملاحظة",
    labelHint: "بتظهرلك إنت بس — زي الحساب الإعلاني اللي تبعه.",
    capiEnabled: "ابعت الأوردرات من السيرفر كمان (Conversions API)",
    capiToken: "رمز الوصول (Access token)",
    capiTokenKeep: "فيه رمز محفوظ ({mask}). سيبه فاضي علشان يفضل زي ما هو.",
    capiTokenGa4: "في GA4 ده هو الـ API secret بتاع Measurement Protocol.",
    capiTokenRequired: "الصق الرمز علشان تشغّل أحداث السيرفر.",
    testCode: "كود الأحداث التجريبية",
    testCodeHint: "اختياري. طول ما هو مكتوب، أحداث السيرفر بتظهر في Test events ومش بتتحسب حقيقية.",
    adsLabel: "ليبل تحويل الشرا",
    adsLabelHint: "في Google Ads افتح الأهداف ← التحويلات ← الإجراء بتاعك ← إعداد العلامة، وانسخ الجزء اللي بعد الـ / في send_to.",
    adsLeadLabel: "ليبل تحويل العميل المحتمل",
    adsLeadLabelHint: "بيتستخدم لما المتجر أو مسار بيع يسجّل الأوردرات كـ Lead.",
    adsLabelInvalid: "اكتب من 4 لـ 60 حرف إنجليزي أو رقم، ومسموح بالشرطة (-) والشرطة السفلية (_).",
    adsLabelNeedsAds: "الليبل محتاج رقم إعلانات جوجل (AW-…)",
    scopeFunnels: "مسارات بيع معيّنة",
    scopeProducts: "منتجات معيّنة",
    chooseFunnels: "اختار مسارات البيع",
    chooseProducts: "اختار المنتجات",
    scopeEmpty: "لسه مفيش حاجة تختار منها.",
    scopeRequired: "اختار واحد على الأقل.",
    save: "حفظ",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    created: "البيكسل اتضاف وشغّال على متجرك دلوقتي.",
    updated: "البيكسل اتحفظ.",
    deleted: "البيكسل اتمسح.",
    deleteTitle: "تمسح البيكسل ده؟",
    deleteBody: "{name} {id} مش هيوصله أحداث من متجرك تاني. الأحداث اللي وصلته قبل كده هتفضل عند المنصة.",
    deleting: "بنمسح…",
    test: "ابعت حدث تجريبي",
    testing: "بنبعت…",
    testOk: "{name} قبل الحدث التجريبي.",
    testOkCode: "الحدث التجريبي اتقبل — هتلاقيه في Test events جوّه {name}.",
    testFailed: "{name} رفض الحدث التجريبي: {error}",
  },
} satisfies Messages;

export type PixelText = Record<keyof (typeof PIXEL_STRINGS)["en"], string>;
