import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the zones and tax sections (they were one file with the page).
 * Read as `tr` (not `t`) where they are used: the tax-rate and tier loops
 * already use `t` for their item.
 */
export const STRINGS = {
  en: {
    title: "Shipping & Tax",
    description: "Shipping zones and their rates, plus the tax rates applied at checkout.",
    // shared
    name: "Name",
    amount: "Amount",
    country: "Country",
    optional: "Optional.",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    saving: "Saving…",
    working: "Working…",
    activate: "Activate",
    deactivate: "Deactivate",
    activated: '"{name}" activated.',
    deactivated: '"{name}" deactivated.',
    added: '"{name}" added.',
    deleted: '"{name}" deleted.',
    deleteTitle: 'Delete "{name}"?',
    // zones
    zonesHeading: "Shipping zones",
    zonesEmpty: "No shipping zones yet. Add your first one.",
    addZone: "Add zone",
    editZone: "Edit zone",
    saveZone: "Save zone",
    zoneSaved: "Zone saved.",
    zoneActive: "Active",
    zoneInactive: "Inactive",
    zoneNamePlaceholder: "Domestic",
    countries: "Countries",
    countriesHint: "Two-letter codes separated by commas, e.g. EG, SA.",
    noCountries: "No countries",
    deleteZoneBody:
      "Removing a zone deletes its rates too. Orders already placed keep the shipping amount they were charged.",
    deleteZoneConfirm: "Delete zone",
    // rates
    ratesEmpty: "No rates in this zone yet.",
    addRate: "Add rate",
    editRate: "Edit rate",
    saveRate: "Save rate",
    rateSaved: "Rate saved.",
    rateDeleted: "Rate deleted.",
    rateActive: "Active",
    rateInactive: "Inactive",
    colRate: "Rate",
    colType: "Type",
    colDetail: "Detail",
    colDelivery: "Delivery",
    colCarrier: "Carrier",
    colStatus: "Status",
    deleteRateBody: "This shipping rate is removed immediately. Past orders are unaffected.",
    deleteRateConfirm: "Delete rate",
    rateTypeFlat: "Flat",
    rateTypeWeight: "Weight based",
    rateTypeQuantity: "Quantity based",
    rateTypeOrderValue: "Order value based",
    rateTypeFree: "Free",
    noCharge: "No charge",
    tierCountOne: "{count} tier",
    tierCountMany: "{count} tiers",
    dayOne: "{n} day",
    dayMany: "{n} days",
    dayRange: "{min}–{max} days",
    daysFrom: "from {days}",
    daysUpTo: "up to {days}",
    // rate form
    rateNamePlaceholder: "Standard",
    rateType: "Rate type",
    freeRateNote: "A free rate has no extra settings.",
    tiers: "Tiers",
    addTier: "+ Add tier",
    removeTier: "Remove tier",
    upToGrams: "Up to (grams)",
    upToQuantity: "Up to (quantity)",
    minSubtotal: "Minimum subtotal",
    overflowAmount: "Overflow amount",
    overflowHint: "Charged when the order is heavier / larger than every tier.",
    carrierCode: "Carrier code",
    estMinDays: "Est. delivery — min days",
    estMinDaysHint: "Optional. Shown to shoppers at checkout.",
    estMaxDays: "Est. delivery — max days",
    errAmount: "Enter a valid amount.",
    errNoTiers: "Add at least one tier.",
    errTierAmount: "Every tier needs a valid amount.",
    errTierSubtotal: "Every tier needs a valid minimum subtotal.",
    errTierWeight: "Every tier needs a valid weight in grams.",
    errTierQuantity: "Every tier needs a valid quantity.",
    errDays: "Whole number of days, 0–3650.",
    errDaysOrder: "Max days can't be less than min days.",
    // tax rates
    taxHeading: "Tax rates",
    taxOffNote:
      "Tax is turned off for this store — these rates aren’t applied at checkout. Turn it on above to use them.",
    taxEmpty: "No tax rates yet. Add your first one.",
    addTax: "Add tax rate",
    editTax: "Edit tax rate",
    saveTax: "Save tax rate",
    taxSaved: "Tax rate saved.",
    taxRate: "Rate",
    appliesToShipping: "Applies to shipping",
    colPricesIncludeTax: "Prices include tax",
    pricesAlreadyIncludeTax: "Prices already include tax",
    taxNamePlaceholder: "VAT",
    countryHint: "Optional, two-letter code.",
    region: "Region",
    taxRateHint: "Percentage, e.g. 14 for 14%.",
    errPercent: "Enter a percentage of 0 or more.",
    errCountry: "Use a two-letter country code.",
    deleteTaxBody: "This tax rate is removed immediately. Past orders keep the tax they were charged.",
    deleteTaxConfirm: "Delete tax rate",
    // storewide tax switch
    taxSettingTitle: "Tax at checkout",
    taxSettingDescription: "Whether the tax rates below are added to orders.",
    chargeTax: "Charge tax at checkout",
    saveTaxSetting: "Save tax setting",
    taxSettingSaved: "Tax setting saved.",
    // sections
    zonesIntro: "The countries you ship to and what each one costs: flat, by weight, by quantity or by order value.",
    zonesEmptyTitle: "No shipping zones yet",
    zoneRates: "Rates: {n}",
    zoneOn: "{name} is active",
    rateOn: "{name} is offered",
    taxIntro: "Tax added to orders at checkout, and the rates it uses.",
    taxEmptyTitle: "No tax rates yet",
    taxOn: "Tax is now charged at checkout.",
    taxOff: "Tax is no longer charged at checkout.",
    editNamed: "Edit {name}",
    deleteNamed: "Delete {name}",
  },
  ar: {
    title: "الشحن والضرائب",
    description: "مناطق الشحن وأسعارها، ونسب الضريبة التي تُطبَّق في صفحة الدفع.",
    name: "الاسم",
    amount: "المبلغ",
    country: "الدولة",
    optional: "اختياري.",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    saving: "بنحفظ…",
    working: "بننفّذ…",
    activate: "تفعيل",
    deactivate: "إيقاف",
    activated: "تم تفعيل «{name}».",
    deactivated: "اتوقف «{name}».",
    added: "تمت إضافة «{name}».",
    deleted: "اتمسح «{name}».",
    deleteTitle: "حذف «{name}»؟",
    zonesHeading: "مناطق الشحن",
    zonesEmpty: "مفيش مناطق شحن لسه. أضف أول منطقة.",
    addZone: "إضافة منطقة",
    editZone: "تعديل المنطقة",
    saveZone: "حفظ المنطقة",
    zoneSaved: "تم حفظ المنطقة.",
    zoneActive: "نشطة",
    zoneInactive: "غير نشطة",
    zoneNamePlaceholder: "داخل مصر",
    countries: "الدول",
    countriesHint: "أكواد من حرفين مفصولة بفواصل، مثل EG, SA.",
    noCountries: "بدون دول",
    deleteZoneBody: "حذف المنطقة يحذف أسعارها أيضًا. الطلبات المسجّلة من قبل تحتفظ بمبلغ الشحن الذي حُسب عليها.",
    deleteZoneConfirm: "حذف المنطقة",
    ratesEmpty: "مفيش أسعار في هذه المنطقة لسه.",
    addRate: "إضافة سعر",
    editRate: "تعديل السعر",
    saveRate: "حفظ السعر",
    rateSaved: "تم حفظ السعر.",
    rateDeleted: "تم حذف السعر.",
    rateActive: "نشط",
    rateInactive: "غير نشط",
    colRate: "سعر الشحن",
    colType: "النوع",
    colDetail: "التفاصيل",
    colDelivery: "مدة التوصيل",
    colCarrier: "شركة الشحن",
    colStatus: "الحالة",
    deleteRateBody: "يُحذف سعر الشحن هذا فورًا. الطلبات السابقة لا تتأثر.",
    deleteRateConfirm: "حذف السعر",
    rateTypeFlat: "سعر ثابت",
    rateTypeWeight: "حسب الوزن",
    rateTypeQuantity: "حسب الكمية",
    rateTypeOrderValue: "حسب قيمة الطلب",
    rateTypeFree: "مجاني",
    noCharge: "بدون رسوم",
    tierCountOne: "شريحة واحدة",
    tierCountMany: "{count} شرائح",
    dayOne: "يوم واحد",
    dayMany: "{n} أيام",
    dayRange: "من {min} إلى {max} أيام",
    daysFrom: "ابتداءً من {days}",
    daysUpTo: "حتى {days}",
    rateNamePlaceholder: "شحن عادي",
    rateType: "نوع السعر",
    freeRateNote: "السعر المجاني ليس له إعدادات إضافية.",
    tiers: "الشرائح",
    addTier: "+ إضافة شريحة",
    removeTier: "حذف الشريحة",
    upToGrams: "حتى (جرام)",
    upToQuantity: "حتى (كمية)",
    minSubtotal: "الحد الأدنى للمجموع الفرعي",
    overflowAmount: "المبلغ عند تجاوز الشرائح",
    overflowHint: "يُحتسب عندما يكون الطلب أثقل / أكبر من كل الشرائح.",
    carrierCode: "كود شركة الشحن",
    estMinDays: "مدة التوصيل المتوقعة — أقل عدد أيام",
    estMinDaysHint: "اختياري. يظهر للعملاء في صفحة الدفع.",
    estMaxDays: "مدة التوصيل المتوقعة — أقصى عدد أيام",
    errAmount: "اكتب مبلغًا صحيحًا.",
    errNoTiers: "أضف شريحة واحدة على الأقل.",
    errTierAmount: "كل شريحة تحتاج مبلغًا صحيحًا.",
    errTierSubtotal: "كل شريحة تحتاج حدًا أدنى صحيحًا للمجموع الفرعي.",
    errTierWeight: "كل شريحة تحتاج وزنًا صحيحًا بالجرام.",
    errTierQuantity: "كل شريحة تحتاج كمية صحيحة.",
    errDays: "عدد صحيح من الأيام، من 0 إلى 3650.",
    errDaysOrder: "لا يمكن أن يكون أقصى عدد أيام أقل من أقل عدد أيام.",
    taxHeading: "نسب الضريبة",
    taxOffNote: "الضريبة متوقفة في هذا المتجر — هذه النسب لا تُطبَّق في صفحة الدفع. فعّل الضريبة من الأعلى لاستخدامها.",
    taxEmpty: "مفيش نسب ضريبة لسه. أضف أول نسبة.",
    addTax: "إضافة نسبة ضريبة",
    editTax: "تعديل نسبة الضريبة",
    saveTax: "حفظ نسبة الضريبة",
    taxSaved: "اتحفظت نسبة الضريبة.",
    taxRate: "النسبة",
    appliesToShipping: "تُطبَّق على الشحن",
    colPricesIncludeTax: "الأسعار شاملة الضريبة",
    pricesAlreadyIncludeTax: "الأسعار شاملة الضريبة بالفعل",
    taxNamePlaceholder: "ضريبة القيمة المضافة",
    countryHint: "اختياري، كود من حرفين.",
    region: "المحافظة",
    taxRateHint: "نسبة مئوية، مثل 14 لـ 14%.",
    errPercent: "اكتب نسبة مئوية تساوي 0 أو أكثر.",
    errCountry: "استخدم كود دولة من حرفين.",
    deleteTaxBody: "تُحذف نسبة الضريبة هذه فورًا. الطلبات السابقة تحتفظ بالضريبة التي حُسبت عليها.",
    deleteTaxConfirm: "حذف نسبة الضريبة",
    taxSettingTitle: "الضريبة في صفحة الدفع",
    taxSettingDescription: "حدّد هل تُضاف نسب الضريبة أدناه إلى الطلبات.",
    chargeTax: "احتساب الضريبة في صفحة الدفع",
    saveTaxSetting: "حفظ إعداد الضريبة",
    taxSettingSaved: "تم حفظ إعداد الضريبة.",
    zonesIntro: "الدول اللي بتشحن لها وسعر كل واحدة: ثابت، بالوزن، بالكمية أو بقيمة الأوردر.",
    zonesEmptyTitle: "مفيش مناطق شحن لسه",
    zoneRates: "الأسعار: {n}",
    zoneOn: "«{name}» شغّالة",
    rateOn: "«{name}» متاح",
    taxIntro: "الضريبة اللي بتتضاف على الأوردر في صفحة الدفع، ونِسَبها.",
    taxEmptyTitle: "مفيش نسب ضريبة لسه",
    taxOn: "الضريبة بقت بتتحسب في صفحة الدفع.",
    taxOff: "الضريبة اتوقفت في صفحة الدفع.",
    editNamed: "عدّل «{name}»",
    deleteNamed: "امسح «{name}»",
  },
} satisfies Messages;

export type Strings = (typeof STRINGS)["en"];
