import type { Locale } from "@/lib/i18n";
import { useStore } from "@/lib/StoreContext";

/**
 * The shopper's words for how an order reaches them: a store on holiday
 * (handoff 216), the delivery day and time slot (221) and picking the order
 * up in store (225). Kept beside the components that say them, like
 * components/tenders/tenderCopy.ts. Arabic is Egyptian, as the rest of the
 * store. Dates and times come in already formatted (lib/fulfilmentDates).
 */

const en = {
  // holiday
  holidayOn: "We're on holiday",
  holidayUntil: (date: string) => `We're on holiday until ${date}`,
  ordersPaused: "Orders are paused for now",
  pausedBody: "You can keep browsing and filling your cart. Ordering opens again when we're back.",
  pausedBodyUntil: (date: string) => `You can keep browsing and filling your cart. Ordering opens again on ${date}.`,
  shipsFrom: (date: string) => `Orders ship from ${date}`,
  shipsLater: "Orders ship once the holiday is over",
  // delivery slot
  slotTitle: "Delivery day and time",
  slotTitlePickup: "Pickup day and time",
  slotDay: "Day",
  slotTime: "Time",
  slotPickDay: "Choose the day first.",
  slotFull: "Full",
  slotRange: (from: string, to: string) => `${from} – ${to}`,
  slotChosen: (day: string, range: string) => `${day}, ${range}`,
  slotClear: "No set time",
  slotLoading: "Loading delivery times…",
  slotNone: "No delivery times are open right now.",
  slotNoneRequired: "No delivery times are open right now, so the order can't be placed yet. Try again later or contact the store.",
  slotRequired: "Choose a delivery day and time",
  slotRequiredPickup: "Choose a pickup day and time",
  slotUnavailable: "This delivery time isn't offered — choose another",
  slotTaken: "This delivery time is fully booked — choose another",
  slotNotOffered: "This store no longer takes delivery times. Check your order and place it again.",
  slotRetry: "Try again",
  slotFailed: "We couldn't load the delivery times.",
  arriving: (day: string, from: string, to: string) => `Arriving ${day}, ${from}–${to}`,
  collectOn: (day: string, from: string, to: string) => `Pick it up on ${day}, ${from}–${to}`,
  // pickup
  howTitle: "How do you want to get your order?",
  delivery: "Delivery",
  deliveryHint: "To your address",
  pickup: "Pick up in store",
  pickupHint: "Free. You collect it yourself.",
  pickupPlaces: "Where do you want to pick it up?",
  pickupUnavailableHere: "Not available here",
  pickupHours: "Hours",
  pickupHow: "How to collect",
  pickupFree: "Free",
  pickupNoAddress: "No delivery address needed: you collect the order with the code we give you.",
  pickupChoosePlace: "Choose where to pick up your order",
  pickupPlaceRefused: "Pickup isn't offered at this place — choose another",
  pickupOutOfStock: "Some items aren't available at this place — choose another place or delivery",
  pickupNowhere: "Not every item in your cart is in stock at a pickup place right now. Choose delivery.",
  pickupCodeLabel: "Pickup code",
  pickupCode: (code: string) => `Pickup code: ${code}`,
  pickupShowCode: "Show this code when you collect your order.",
  pickupFrom: "Pick up from",
  pickupPreparing: "Preparing",
  pickupReady: "Ready for pickup",
  pickupCollected: "Collected",
  pickupCancelled: "Cancelled",
  pickupPreparingNote: "We're getting your order ready. We'll tell you when you can collect it.",
  pickupReadyNote: "Your order is ready. Come and collect it.",
  pickupCollectedNote: "You collected this order.",
  pickupCancelledNote: "This order was cancelled.",
  pickupStatus: "Pickup status",
  copy: "Copy",
  copied: "Copied",
};

export type FulfilmentCopy = typeof en;

const ar: FulfilmentCopy = {
  holidayOn: "المتجر في إجازة",
  holidayUntil: (date) => `المتجر في إجازة لحد ${date}`,
  ordersPaused: "الطلبات موقوفة مؤقتًا",
  pausedBody: "تقدر تتصفح وتضيف للسلة عادي. الطلب هيتفتح تاني لما نرجع.",
  pausedBodyUntil: (date) => `تقدر تتصفح وتضيف للسلة عادي. الطلب هيتفتح تاني يوم ${date}.`,
  shipsFrom: (date) => `الطلبات هتتشحن من ${date}`,
  shipsLater: "الطلبات هتتشحن بعد الإجازة",
  slotTitle: "يوم وميعاد التوصيل",
  slotTitlePickup: "يوم وميعاد الاستلام",
  slotDay: "اليوم",
  slotTime: "الميعاد",
  slotPickDay: "اختار اليوم الأول.",
  slotFull: "محجوز",
  slotRange: (from, to) => `${from} – ${to}`,
  slotChosen: (day, range) => `${day}، ${range}`,
  slotClear: "من غير ميعاد محدد",
  slotLoading: "بنحمّل مواعيد التوصيل…",
  slotNone: "مفيش مواعيد توصيل متاحة دلوقتي.",
  slotNoneRequired: "مفيش مواعيد توصيل متاحة دلوقتي، فالطلب مش هينفع يتسجّل. جرّب تاني بعد شوية أو كلّم المتجر.",
  slotRequired: "اختار يوم وميعاد التوصيل",
  slotRequiredPickup: "اختار يوم وميعاد الاستلام",
  slotUnavailable: "الميعاد ده مش متاح — اختار ميعاد تاني",
  slotTaken: "الميعاد ده اتحجز بالكامل — اختار ميعاد تاني",
  slotNotOffered: "المتجر مبقاش بيحدد مواعيد توصيل. راجع طلبك وأكّده تاني.",
  slotRetry: "جرّب تاني",
  slotFailed: "معرفناش نحمّل مواعيد التوصيل.",
  arriving: (day, from, to) => `هيوصلك يوم ${day} بين ${from} و ${to}`,
  collectOn: (day, from, to) => `استلم طلبك يوم ${day} بين ${from} و ${to}`,
  howTitle: "تحب تستلم طلبك إزاي؟",
  delivery: "توصيل",
  deliveryHint: "لحد عنوانك",
  pickup: "استلام من الفرع",
  pickupHint: "مجانًا. بتستلم طلبك بنفسك.",
  pickupPlaces: "تحب تستلم منين؟",
  pickupUnavailableHere: "مش متوفر هنا",
  pickupHours: "المواعيد",
  pickupHow: "طريقة الاستلام",
  pickupFree: "مجانًا",
  pickupNoAddress: "مش محتاجين عنوان توصيل: هتستلم طلبك بالكود اللي هنديهولك.",
  pickupChoosePlace: "اختار المكان اللي هتستلم منه",
  pickupPlaceRefused: "الاستلام مش متاح من المكان ده — اختار مكان تاني",
  pickupOutOfStock: "في منتجات مش موجودة في الفرع ده — اختار فرع تاني أو التوصيل",
  pickupNowhere: "مش كل منتجات السلة متوفرة في مكان استلام دلوقتي. اختار التوصيل.",
  pickupCodeLabel: "كود الاستلام",
  pickupCode: (code) => `كود الاستلام: ${code}`,
  pickupShowCode: "وري الكود ده وإنت بتستلم طلبك.",
  pickupFrom: "مكان الاستلام",
  pickupPreparing: "بنجهّز طلبك",
  pickupReady: "جاهز للاستلام",
  pickupCollected: "اتسلّم",
  pickupCancelled: "اتلغى",
  pickupPreparingNote: "بنجهّز طلبك دلوقتي. هنبلّغك أول ما تقدر تستلمه.",
  pickupReadyNote: "طلبك جاهز. تعالى استلمه.",
  pickupCollectedNote: "إنت استلمت الطلب ده.",
  pickupCancelledNote: "الطلب ده اتلغى.",
  pickupStatus: "حالة الاستلام",
  copy: "انسخ",
  copied: "اتنسخ",
};

const fr: FulfilmentCopy = {
  holidayOn: "Nous sommes en congé",
  holidayUntil: (date) => `Nous sommes en congé jusqu'au ${date}`,
  ordersPaused: "Les commandes sont suspendues pour le moment",
  pausedBody: "Vous pouvez continuer à parcourir la boutique et remplir votre panier. Les commandes rouvriront à notre retour.",
  pausedBodyUntil: (date) => `Vous pouvez continuer à parcourir la boutique et remplir votre panier. Les commandes rouvriront le ${date}.`,
  shipsFrom: (date) => `Les commandes seront expédiées à partir du ${date}`,
  shipsLater: "Les commandes seront expédiées après le congé",
  slotTitle: "Jour et créneau de livraison",
  slotTitlePickup: "Jour et créneau de retrait",
  slotDay: "Jour",
  slotTime: "Créneau",
  slotPickDay: "Choisissez d'abord le jour.",
  slotFull: "Complet",
  slotRange: (from, to) => `${from} – ${to}`,
  slotChosen: (day, range) => `${day}, ${range}`,
  slotClear: "Sans créneau précis",
  slotLoading: "Chargement des créneaux de livraison…",
  slotNone: "Aucun créneau de livraison n'est disponible pour le moment.",
  slotNoneRequired: "Aucun créneau de livraison n'est disponible pour le moment : la commande ne peut pas encore être passée. Réessayez plus tard ou contactez la boutique.",
  slotRequired: "Choisissez un jour et un créneau de livraison",
  slotRequiredPickup: "Choisissez un jour et un créneau de retrait",
  slotUnavailable: "Ce créneau n'est pas proposé — choisissez-en un autre",
  slotTaken: "Ce créneau est complet — choisissez-en un autre",
  slotNotOffered: "Cette boutique ne propose plus de créneaux de livraison. Vérifiez votre commande et validez à nouveau.",
  slotRetry: "Réessayer",
  slotFailed: "Impossible de charger les créneaux de livraison.",
  arriving: (day, from, to) => `Livraison ${day}, ${from}–${to}`,
  collectOn: (day, from, to) => `À retirer ${day}, ${from}–${to}`,
  howTitle: "Comment souhaitez-vous recevoir votre commande ?",
  delivery: "Livraison",
  deliveryHint: "À votre adresse",
  pickup: "Retrait en boutique",
  pickupHint: "Gratuit. Vous venez la chercher.",
  pickupPlaces: "Où souhaitez-vous la retirer ?",
  pickupUnavailableHere: "Indisponible ici",
  pickupHours: "Horaires",
  pickupHow: "Comment retirer",
  pickupFree: "Gratuit",
  pickupNoAddress: "Aucune adresse de livraison nécessaire : vous retirez la commande avec le code que nous vous donnons.",
  pickupChoosePlace: "Choisissez où retirer votre commande",
  pickupPlaceRefused: "Le retrait n'est pas proposé à cet endroit — choisissez-en un autre",
  pickupOutOfStock: "Certains articles ne sont pas disponibles à cet endroit — choisissez un autre lieu ou la livraison",
  pickupNowhere: "Tous les articles de votre panier ne sont pas en stock dans un point de retrait pour le moment. Choisissez la livraison.",
  pickupCodeLabel: "Code de retrait",
  pickupCode: (code) => `Code de retrait : ${code}`,
  pickupShowCode: "Présentez ce code au moment du retrait.",
  pickupFrom: "Lieu de retrait",
  pickupPreparing: "En préparation",
  pickupReady: "Prête à être retirée",
  pickupCollected: "Retirée",
  pickupCancelled: "Annulée",
  pickupPreparingNote: "Nous préparons votre commande. Nous vous préviendrons dès qu'elle pourra être retirée.",
  pickupReadyNote: "Votre commande est prête. Venez la retirer.",
  pickupCollectedNote: "Vous avez retiré cette commande.",
  pickupCancelledNote: "Cette commande a été annulée.",
  pickupStatus: "État du retrait",
  copy: "Copier",
  copied: "Copié",
};

const COPY: Record<Locale, FulfilmentCopy> = { en, ar, fr };

export function fulfilmentCopy(locale: Locale): FulfilmentCopy {
  return COPY[locale] ?? en;
}

/** The copy in the page's language. */
export function useFulfilmentCopy(): FulfilmentCopy {
  return fulfilmentCopy(useStore().locale);
}
