import type { DiscountType } from "@store-builder/api-client";
import type { Locale, Messages } from "@/i18n/LocaleContext";

export const TYPE_LABELS: Record<Locale, Record<DiscountType, string>> = {
  en: {
    percentage: "Percentage off",
    fixed: "Fixed amount off",
    free_shipping: "Free shipping",
    buy_x_get_y: "Buy X get Y",
  },
  ar: {
    percentage: "خصم بنسبة مئوية",
    fixed: "خصم بمبلغ ثابت",
    free_shipping: "شحن مجاني",
    buy_x_get_y: "اشترِ X واحصل على Y",
  },
};

export const STRINGS = {
  en: {
    title: "Discounts",
    description: "Discount codes and automatic discounts applied at checkout.",
    createDiscount: "Create discount",
    editDiscount: "Edit discount",
    empty: "No discounts yet. Create your first one.",
    colCode: "Code",
    colType: "Type",
    colValue: "Value",
    colUsage: "Usage",
    colDates: "Dates",
    automatic: "Automatic",
    enable: "Enable",
    disable: "Disable",
    noDateLimit: "No date limit",
    fromDate: "From {date}",
    untilDate: "Until {date}",
    toastEnabled: "Discount enabled.",
    toastDisabled: "Discount disabled.",
    toastArchivedCode: "“{code}” archived.",
    toastArchived: "Discount archived.",
    confirmTitleCode: "Archive “{code}”?",
    confirmTitle: "Archive this discount?",
    confirmDescription:
      "A discount that has been redeemed is financial history, so it's archived rather than deleted — it stops applying at checkout and drops off active reporting.",
    confirmLabel: "Archive discount",
  },
  ar: {
    title: "كوبونات الخصم",
    description: "أكواد الخصم والخصومات التلقائية التي تُطبَّق عند إتمام الطلب.",
    createDiscount: "إنشاء خصم",
    editDiscount: "تعديل الخصم",
    empty: "لا توجد خصومات بعد. أنشئ أول خصم لك.",
    colCode: "الكود",
    colType: "النوع",
    colValue: "القيمة",
    colUsage: "عدد مرات الاستخدام",
    colDates: "التواريخ",
    automatic: "تلقائي",
    enable: "تفعيل",
    disable: "إيقاف",
    noDateLimit: "بدون تاريخ انتهاء",
    fromDate: "من {date}",
    untilDate: "حتى {date}",
    toastEnabled: "تم تفعيل الخصم.",
    toastDisabled: "تم إيقاف الخصم.",
    toastArchivedCode: "تمت أرشفة الكود «{code}».",
    toastArchived: "تمت أرشفة الخصم.",
    confirmTitleCode: "أرشفة الكود «{code}»؟",
    confirmTitle: "أرشفة هذا الخصم؟",
    confirmDescription:
      "الخصم الذي تم استخدامه يُعد جزءًا من السجل المالي، لذلك تتم أرشفته بدلًا من حذفه — فيتوقف تطبيقه عند إتمام الطلب ويختفي من التقارير النشطة.",
    confirmLabel: "أرشفة الخصم",
  },
} satisfies Messages;

export const FORM_STRINGS = {
  en: {
    code: "Code",
    codeHint: "Leave blank for an automatic discount with no code.",
    generate: "Generate",
    type: "Type",
    percentage: "Percentage",
    percentageHint: "Between 0 and 100.",
    amountOff: "Amount off",
    minimumSubtotal: "Minimum order subtotal",
    minimumSubtotalHint: "Optional — the order subtotal must reach this before the discount applies.",
    startsAt: "Starts at",
    endsAt: "Ends at",
    usageLimit: "Usage limit",
    usageLimitHint: "Total redemptions allowed.",
    perCustomerLimit: "Per-customer limit",
    perCustomerLimitHint: "Redemptions allowed per customer.",
    appliesTo: "Applies to",
    allProducts: "All products",
    specificProducts: "Specific products",
    stackable: "Can be combined with other discounts",
    saveDiscount: "Save discount",
    createDiscount: "Create discount",
    errPercentRange: "Enter a percentage between 0 and 100.",
    errAmount: "Enter a valid amount.",
    errPercentMax: "A percentage discount can't exceed 100%.",
    errWholeNumber: "Enter a whole number of 1 or more.",
    errProducts: "Select at least one product, or switch to all products.",
    toastSaved: "Discount saved.",
    toastCreatedCode: "“{code}” created.",
    toastCreatedAuto: "Automatic discount created.",
  },
  ar: {
    code: "كود الخصم",
    codeHint: "اتركه فارغًا لإنشاء خصم تلقائي بدون كود.",
    generate: "توليد كود",
    type: "النوع",
    percentage: "النسبة المئوية",
    percentageHint: "بين 0 و100.",
    amountOff: "قيمة الخصم",
    minimumSubtotal: "الحد الأدنى للطلب",
    minimumSubtotalHint: "اختياري — يجب أن يصل إجمالي الطلب إلى هذا المبلغ حتى يُطبَّق الخصم.",
    startsAt: "تاريخ البدء",
    endsAt: "تاريخ الانتهاء",
    usageLimit: "الحد الأقصى لمرات الاستخدام",
    usageLimitHint: "إجمالي عدد مرات الاستخدام المسموح بها.",
    perCustomerLimit: "الحد لكل عميل",
    perCustomerLimitHint: "عدد مرات الاستخدام المسموح بها لكل عميل.",
    appliesTo: "يُطبَّق على",
    allProducts: "كل المنتجات",
    specificProducts: "منتجات محددة",
    stackable: "يمكن دمجه مع خصومات أخرى",
    saveDiscount: "حفظ الخصم",
    createDiscount: "إنشاء خصم",
    errPercentRange: "أدخل نسبة مئوية بين 0 و100.",
    errAmount: "أدخل مبلغًا صحيحًا.",
    errPercentMax: "لا يمكن أن تتجاوز نسبة الخصم 100%.",
    errWholeNumber: "أدخل عددًا صحيحًا يساوي 1 أو أكثر.",
    errProducts: "اختر منتجًا واحدًا على الأقل، أو اختر كل المنتجات.",
    toastSaved: "تم حفظ الخصم.",
    toastCreatedCode: "تم إنشاء الكود «{code}».",
    toastCreatedAuto: "تم إنشاء الخصم التلقائي.",
  },
} satisfies Messages;

export const PICKER_STRINGS = {
  en: {
    filterPlaceholder: "Filter products…",
    selected: "{n} selected",
    noProducts: "No products yet — add one in Catalog first.",
    noMatch: "No products match.",
  },
  ar: {
    filterPlaceholder: "ابحث في المنتجات…",
    selected: "تم اختيار {n}",
    noProducts: "لا توجد منتجات بعد — أضف منتجًا من الكتالوج أولًا.",
    noMatch: "لا توجد منتجات مطابقة.",
  },
} satisfies Messages;
