import type { Messages } from "@/i18n/LocaleContext";

/** Every string of the funnel's settings sheet (FunnelGrowthPanel.tsx and its parts in this folder). */
export const SHEET_STRINGS = {
  en: {
    // shell
    open: "Funnel settings",
    title: "Funnel settings",
    parts: "Part of the settings",
    tabSettings: "Settings",
    tabEmails: "Emails",
    tabTests: "A/B tests",
    tabTestsShort: "A/B",
    tabGeo: "Countries",
    savesAlone: "These settings save on their own — not with the funnel's Save.",
    unsavedTitle: "You have changes that are not saved",
    unsavedBody: "If you go on, what you changed here is lost.",
    unsavedStay: "Keep editing",
    unsavedLeave: "Leave them",
    cancel: "Cancel",
    discard: "Discard",
    close: "Close",
    retry: "Try again",

    // settings
    settingsUnsaved: "Settings not saved yet",
    save: "Save settings",
    saving: "Saving…",
    saved: "Settings saved.",
    currency: "Funnel currency (3 letters)",
    currencyHint: "What this funnel sells in; its offers must be priced in it. Empty = the store's.",
    searchFold: "How the funnel shows in search",
    searchFoldSummary: "Title, description and icon — empty = the store's",
    seoTitle: "Search title",
    seoDescription: "Search description",
    favicon: "Icon link",
    advancedFold: "Advanced",
    advancedSummary: "Your own code on every step",
    advancedSummaryOn: "There is code on this funnel's pages",

    // tests — list
    testsIntro: "Show one step in two or more versions and keep the one that sells more. A is the page as it is now; each other version starts as a copy you then change.",
    noTests: "No test on this funnel yet",
    noTestsDesc: "Try another headline or another price on one step and let the visitors decide.",
    noSteps: "Add a step to the funnel first, then test it.",
    newTest: "New test",
    onStep: "On step: {page}",
    running: "Running",
    paused: "Paused",
    completed: "Finished",
    openTest: "Open the test «{name}»",
    visits: "Visits",
    orders: "Orders",
    rate: "Conversion",
    revenue: "Revenue",
    epc: "Per visit",
    share: "Share",
    numbersLoading: "Loading the numbers…",
    numbersFailed: "Couldn't load this test's numbers.",
    winner: "Winner",
    leader: "Ahead",
    early: "Too early — not enough visits yet to tell the versions apart.",
    closeCall: "The versions are close: no clear difference yet.",
    leaderLine: "{leader} is ahead — {pct}% sure it really converts better.",
    leaderVsLine: "{leader} is ahead — {pct}% sure it really converts better than {runnerUp}.",
    winnerLine: "{winner} won: every visitor sees its page now.",
    control: "A — original",

    // tests — create
    backToTests: "Tests",
    createTitle: "New test",
    page: "Step to test",
    stepHasTest: "{name} — already has a test",
    name: "Test name",
    namePlaceholder: "Headline test",
    auto: "Pick the winner automatically",
    autoHint: "The test ends by itself once it has enough visits.",
    afterVisits: "After this many visits",
    metric: "By",
    conversion_rate: "Conversion rate",
    revenue_per_visit: "Revenue per visit",
    create: "Start test",
    creating: "Starting…",
    created: "The test is running.",
    needsSaved: "Save the funnel first: this step has not been saved yet.",
    createUnsaved: "The test has not started yet",

    // tests — detail
    autoLine: "It picks the winner by itself after {n} visits, by {metric}.",
    pause: "Pause the test",
    resume: "Resume the test",
    pausedToast: "Test paused. Visitors see the original page.",
    resumedToast: "The test is running again.",
    makeWinner: "Make it the winner",
    winnerTitle: "Make {version} the winner?",
    winnerBody: "The test ends and every visitor sees {version}'s page. A finished test cannot be started again.",
    winnerConfirm: "End the test",
    winnerToast: "{version} won. The test is finished.",
    remove: "Delete test",
    removeTitle: "Delete the test «{name}»?",
    removeBody: "Its numbers are deleted for good and visitors go back to the step's own page.",
    removeConfirm: "Delete",
    removedToast: "Test deleted.",
    doneNote: "The funnel's own page did not change: visitors see {winner}'s page while this test exists. Delete the test and the original page shows again.",
    editPage: "Edit {key}'s page",
    versionsFold: "Versions and shares",
    versionsFoldSummary: "Add a version or move the shares",
    saveVersions: "Save versions and shares",
    versionsUnsaved: "Shares not saved yet",
    savedVersions: "Saved. New visitors are shared out the new way; visitors already in a version stay in it.",

    // tests — a version's page
    backToTest: "The test",
    pageTitle: "Version {key}'s page",
    savePage: "Save {key}'s page",
    savedPage: "{key}'s page saved. It is live for visitors in {key} at once.",
    stepGone: "This step is no longer in the funnel, so its versions cannot be edited.",

    // geo
    geoIntro: "Send visitors from some countries to another funnel — for another language, currency or shipping. Everyone else sees this one.",
    noRules: "No country redirect on this funnel",
    noRulesDesc: "Everyone sees this funnel, wherever they are.",
    ruleTo: "go to",
    active: "On",
    ruleActive: "Redirect for {countries} is on",
    removeRule: "Delete the redirect for {countries}",
    ruleRemoved: "Redirect deleted.",
    addTitle: "New redirect",
    quickPick: "Tap to pick",
    countries: "Other countries (2-letter codes, comma-separated)",
    countriesPlaceholder: "SA, AE, KW",
    target: "Send them to",
    chooseFunnel: "Choose a funnel",
    onlyPublished: "The redirect applies while the target funnel is published.",
    addRule: "Add redirect",
    adding: "Adding…",
    ruleAdded: "Redirect added.",
    geoUnsaved: "A redirect not added yet",
  },
  ar: {
    open: "إعدادات الفانل",
    title: "إعدادات الفانل",
    parts: "جزء الإعدادات",
    tabSettings: "الإعدادات",
    tabEmails: "الإيميلات",
    tabTests: "اختبارات A/B",
    tabTestsShort: "A/B",
    tabGeo: "الدول",
    savesAlone: "الإعدادات دي بتتحفظ لوحدها — مش مع حفظ الفانل.",
    unsavedTitle: "عندك تغييرات لسه ما اتحفظتش",
    unsavedBody: "لو كمّلت، اللي غيّرته هنا هيضيع.",
    unsavedStay: "كمّل تعديل",
    unsavedLeave: "سيبها",
    cancel: "إلغاء",
    discard: "تجاهل",
    close: "إغلاق",
    retry: "جرّب تاني",

    settingsUnsaved: "إعدادات لسه ما اتحفظتش",
    save: "احفظ الإعدادات",
    saving: "بنحفظ…",
    saved: "الإعدادات اتحفظت.",
    currency: "عملة الفانل (٣ حروف)",
    currencyHint: "العملة اللي الفانل بيبيع بيها؛ لازم عروضه تبقى مسعّرة بيها. لو سبتها فاضية = عملة المتجر.",
    searchFold: "شكل الفانل في البحث",
    searchFoldSummary: "العنوان والوصف والأيقونة — لو فاضيين = بتوع المتجر",
    seoTitle: "عنوان البحث",
    seoDescription: "وصف البحث",
    favicon: "رابط الأيقونة",
    advancedFold: "متقدّم",
    advancedSummary: "كود خاص بيك على كل الخطوات",
    advancedSummaryOn: "فيه كود على صفحات الفانل ده",

    testsIntro: "اعرض خطوة واحدة بنسختين أو أكتر وخلّي اللي بتبيع أكتر. A هي الصفحة زي ما هي دلوقتي؛ وكل نسخة تانية بتبدأ كنسخة منها وبعدين تعدّلها.",
    noTests: "مفيش اختبار على الفانل ده لسه",
    noTestsDesc: "جرّب عنوان تاني أو سعر تاني على خطوة واحدة، وسيب الزوار يحكموا.",
    noSteps: "ضيف خطوة للفانل الأول، وبعدين اختبرها.",
    newTest: "اختبار جديد",
    onStep: "على خطوة: {page}",
    running: "شغّال",
    paused: "متوقف",
    completed: "خلص",
    openTest: "افتح الاختبار «{name}»",
    visits: "الزيارات",
    orders: "الأوردرات",
    rate: "التحويل",
    revenue: "الإيراد",
    epc: "لكل زيارة",
    share: "النسبة",
    numbersLoading: "بنحمّل الأرقام…",
    numbersFailed: "معرفناش نحمّل أرقام الاختبار ده.",
    winner: "الفايزة",
    leader: "متقدّمة",
    early: "لسه بدري — الزيارات قليلة ومش كفاية نفرّق بين النسخ.",
    closeCall: "النسخ قريبة من بعض: مفيش فرق واضح لسه.",
    leaderLine: "{leader} متقدّمة — متأكدين {pct}% إنها بتحوّل أحسن فعلًا.",
    leaderVsLine: "{leader} متقدّمة — متأكدين {pct}% إنها بتحوّل أحسن من {runnerUp} فعلًا.",
    winnerLine: "{winner} كسبت: كل الزوار بيشوفوا صفحتها دلوقتي.",
    control: "A — الأصلية",

    backToTests: "الاختبارات",
    createTitle: "اختبار جديد",
    page: "الخطوة اللي هتختبرها",
    stepHasTest: "{name} — عليها اختبار",
    name: "اسم الاختبار",
    namePlaceholder: "اختبار العنوان",
    auto: "اختار الفايزة لوحدك",
    autoHint: "الاختبار بيخلص لوحده أول ما الزيارات تكفّي.",
    afterVisits: "بعد كام زيارة",
    metric: "حسب",
    conversion_rate: "نسبة التحويل",
    revenue_per_visit: "الإيراد لكل زيارة",
    create: "ابدأ الاختبار",
    creating: "بنبدأ…",
    created: "الاختبار شغّال.",
    needsSaved: "احفظ الفانل الأول: الخطوة دي لسه ما اتحفظتش.",
    createUnsaved: "الاختبار لسه ما بدأش",

    autoLine: "هيختار الفايزة لوحده بعد {n} زيارة، حسب {metric}.",
    pause: "وقّف الاختبار مؤقتًا",
    resume: "شغّل الاختبار تاني",
    pausedToast: "الاختبار اتوقف. الزوار بيشوفوا الصفحة الأصلية.",
    resumedToast: "الاختبار رجع يشتغل.",
    makeWinner: "خلّيها الفايزة",
    winnerTitle: "تخلّي {version} هي الفايزة؟",
    winnerBody: "الاختبار هيخلص وكل الزوار هيشوفوا صفحة {version}. الاختبار اللي خلص مش بيتشغّل تاني.",
    winnerConfirm: "خلّص الاختبار",
    winnerToast: "{version} كسبت. الاختبار خلص.",
    remove: "امسح الاختبار",
    removeTitle: "تمسح الاختبار «{name}»؟",
    removeBody: "أرقامه هتتمسح ومش هترجع، والزوار هيرجعوا يشوفوا صفحة الخطوة نفسها.",
    removeConfirm: "امسح",
    removedToast: "الاختبار اتمسح.",
    doneNote: "صفحة الفانل نفسها ما اتغيّرتش: الزوار بيشوفوا صفحة {winner} طول ما الاختبار موجود. لو مسحته، الصفحة الأصلية هترجع تظهر.",
    editPage: "عدّل صفحة {key}",
    versionsFold: "النسخ والنسب",
    versionsFoldSummary: "ضيف نسخة أو غيّر النسب",
    saveVersions: "احفظ النسخ والنسب",
    versionsUnsaved: "نسب لسه ما اتحفظتش",
    savedVersions: "اتحفظ. الزوار الجداد بيتوزّعوا بالنسب الجديدة، واللي دخل نسخة بيفضل فيها.",

    backToTest: "الاختبار",
    pageTitle: "صفحة النسخة {key}",
    savePage: "احفظ صفحة {key}",
    savedPage: "صفحة {key} اتحفظت. بتظهر فورًا للزوار اللي في {key}.",
    stepGone: "الخطوة دي مبقتش في الفانل، فمش هينفع تعدّل نسخها.",

    geoIntro: "ودّي زوار دول معيّنة لفانل تاني — للغة أو عملة أو شحن مختلف. الباقي بيشوفوا الفانل ده.",
    noRules: "مفيش تحويل حسب الدولة على الفانل ده",
    noRulesDesc: "كل الناس بتشوف الفانل ده، من أي بلد.",
    ruleTo: "يروحوا على",
    active: "شغّال",
    ruleActive: "تحويل {countries} شغّال",
    removeRule: "امسح تحويل {countries}",
    ruleRemoved: "التحويل اتمسح.",
    addTitle: "تحويل جديد",
    quickPick: "دوس عشان تختار",
    countries: "دول تانية (كود من حرفين، بينهم فاصلة)",
    countriesPlaceholder: "SA, AE, KW",
    target: "ودّيهم على",
    chooseFunnel: "اختار فانل",
    onlyPublished: "التحويل بيشتغل طول ما الفانل التاني منشور.",
    addRule: "ضيف التحويل",
    adding: "بنضيف…",
    ruleAdded: "التحويل اتضاف.",
    geoUnsaved: "تحويل لسه ما اتضافش",
  },
} satisfies Messages;
