import type { SizeChart } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Size charts (handoff 210): the list, the editor and the product page's line. */
export const SIZE_CHART_STRINGS = {
  en: {
    title: "Size charts",
    description: "A table of sizes shoppers open from the product page as “Size guide”. Attach it to products or to whole collections.",
    newChart: "New size chart",
    colName: "Chart",
    colSizes: "Sizes",
    colUnit: "Unit",
    colAttached: "Shows on",
    colUpdated: "Last change",
    unit_cm: "cm",
    unit_inch: "inch",
    unitLong_cm: "Centimetres",
    unitLong_inch: "Inches",
    rows_one: "1 size",
    rows_other: "{n} sizes",
    products_one: "1 product",
    products_other: "{n} products",
    collections_one: "1 collection",
    collections_other: "{n} collections",
    notAttached: "Not attached yet",
    emptyTitle: "No size charts yet",
    emptyHint: "Make one chart per kind of product — T-shirts, trousers, shoes — and attach it to its collection.",
    // Editor
    newTitle: "New size chart",
    editTitle: "Size chart",
    back: "Size charts",
    basicsTitle: "Name and unit",
    name: "Chart name",
    nameHint: "Only your team sees it — for example “T-shirts”.",
    unit: "The numbers are in",
    unitHint: "Shoppers can switch between cm and inch; the numbers are converted for them.",
    tableTitle: "Sizes table",
    tableHint: "The first column is the size's name (S, M, 42…). Write each heading in Arabic and English — one of them is enough.",
    headingAr: "Heading of column {n} in Arabic",
    headingEn: "Heading of column {n} in English",
    arPlaceholder: "بالعربي",
    enPlaceholder: "English",
    cell: "Row {row}, column {column}",
    addRow: "Add a size",
    addColumn: "Add a column",
    removeRow: "Remove row {n}",
    removeColumn: "Remove column {n}",
    maxRows: "A chart holds up to {max} sizes.",
    maxColumns: "A chart holds up to {max} columns.",
    noteTitle: "Note and picture",
    noteAr: "Note in Arabic",
    noteEn: "Note in English",
    noteHint: "Shown under the table, for example “Measure a T-shirt that fits you well, laid flat”.",
    image: "“How to measure” picture",
    imageHint: "Optional. Upload one, or paste a secure link (https).",
    attachTitle: "Where it shows",
    attachHint: "A chart on the product itself comes first; otherwise the product takes the chart of its collection.",
    products: "Products",
    collections: "Collections",
    searchProducts: "Search products",
    searchCollections: "Search collections",
    noProducts: "No products yet.",
    noCollections: "No collections yet.",
    noMatch: "Nothing matches this search.",
    chosen_one: "1 chosen",
    chosen_other: "{n} chosen",
    noneChosen: "None chosen",
    listPartial: "Showing the newest {count} products.",
    nameRequired: "Give the chart a name.",
    headingRequired: "Every column needs a heading in Arabic or English.",
    imageHttps: "The picture's link must start with https://.",
    attachGone: "A product or collection in this chart no longer exists. Untick it and save again.",
    save: "Save chart",
    create: "Create chart",
    saving: "Saving…",
    unsavedNew: "This chart isn't created yet",
    saved: "Size chart saved.",
    created: "Size chart created.",
    remove: "Delete chart",
    removeTitle: "Delete “{name}”?",
    removeBody: "The products it shows on will have no size guide.",
    removing: "Deleting…",
    removed: "Size chart deleted.",
    cancel: "Cancel",
    // List: search, the row's menu, Quick Look
    searchPlaceholder: "Search by chart or size",
    searchLabel: "Search size charts",
    clearSearch: "Clear the search",
    colActions: "Actions",
    rowMenu: "Actions for {name}",
    menuPeek: "Quick look",
    menuOpen: "Open and edit",
    peekNamed: "Quick look at {name}",
    openEdit: "Open and edit",
    emptyCell: "—",
    updatedOn: "Last change {date}",
    // Editor: the header's menu and what each fold holds
    more: "More",
    noteBoth: "A note and a picture",
    noteOnly: "A note, no picture",
    imageOnly: "A picture, no note",
    noteNone: "No note or picture yet",
    // Product page
    productTitle: "Size chart",
    productOwn: "Attached to this product",
    productFromCollection: "from collection {name}",
    productNone: "No size chart reaches this product. Attach one to it or to its collection.",
    openCharts: "Size charts",
  },
  ar: {
    title: "جداول المقاسات",
    description: "جدول مقاسات بيفتحه العميل من صفحة المنتج باسم «دليل المقاسات». اربطه بمنتجات أو بمجموعات كاملة.",
    newChart: "جدول مقاسات جديد",
    colName: "الجدول",
    colSizes: "المقاسات",
    colUnit: "الوحدة",
    colAttached: "بيظهر على",
    colUpdated: "آخر تعديل",
    unit_cm: "سم",
    unit_inch: "بوصة",
    unitLong_cm: "سنتيمتر",
    unitLong_inch: "بوصة",
    rows_one: "مقاس واحد",
    rows_two: "مقاسين",
    rows_few: "{n} مقاسات",
    rows_other: "{n} مقاس",
    products_one: "منتج واحد",
    products_two: "منتجين",
    products_few: "{n} منتجات",
    products_other: "{n} منتج",
    collections_one: "مجموعة واحدة",
    collections_two: "مجموعتين",
    collections_few: "{n} مجموعات",
    collections_other: "{n} مجموعة",
    notAttached: "مش مربوط بحاجة لسه",
    emptyTitle: "مفيش جداول مقاسات لسه",
    emptyHint: "اعمل جدول لكل نوع منتجات — تيشيرتات، بناطيل، أحذية — واربطه بمجموعته.",
    newTitle: "جدول مقاسات جديد",
    editTitle: "جدول مقاسات",
    back: "جداول المقاسات",
    basicsTitle: "الاسم والوحدة",
    name: "اسم الجدول",
    nameHint: "بيظهر لفريقك بس — زي «تيشيرتات».",
    unit: "الأرقام مكتوبة بالـ",
    unitHint: "العميل يقدر يبدّل بين سم وبوصة، والأرقام بتتحوّل له.",
    tableTitle: "جدول المقاسات",
    tableHint: "أول عمود هو اسم المقاس (S، M، 42…). اكتب عنوان كل عمود بالعربي والإنجليزي — واحد منهم كفاية.",
    headingAr: "عنوان العمود {n} بالعربي",
    headingEn: "عنوان العمود {n} بالإنجليزي",
    arPlaceholder: "بالعربي",
    enPlaceholder: "English",
    cell: "الصف {row}، العمود {column}",
    addRow: "ضيف مقاس",
    addColumn: "ضيف عمود",
    removeRow: "شيل الصف {n}",
    removeColumn: "شيل العمود {n}",
    maxRows: "الجدول بياخد لحد {max} مقاس.",
    maxColumns: "الجدول بياخد لحد {max} عمود.",
    noteTitle: "ملاحظة وصورة",
    noteAr: "الملاحظة بالعربي",
    noteEn: "الملاحظة بالإنجليزي",
    noteHint: "بتظهر تحت الجدول، زي «قيس تيشيرت مقاسه مظبوط عليك وهو مفرود».",
    image: "صورة «إزاي تقيس»",
    imageHint: "اختياري. ارفع صورة، أو الصق رابط آمن (https).",
    attachTitle: "بيظهر فين",
    attachHint: "الجدول المربوط بالمنتج نفسه ليه الأولوية؛ غير كده المنتج بياخد جدول مجموعته.",
    products: "المنتجات",
    collections: "المجموعات",
    searchProducts: "دوّر في المنتجات",
    searchCollections: "دوّر في المجموعات",
    noProducts: "مفيش منتجات لسه.",
    noCollections: "مفيش مجموعات لسه.",
    noMatch: "مفيش حاجة مطابقة للبحث ده.",
    chosen_one: "واحد متعلّم عليه",
    chosen_two: "اتنين متعلّم عليهم",
    chosen_few: "{n} متعلّم عليهم",
    chosen_other: "{n} متعلّم عليهم",
    noneChosen: "مفيش حاجة متعلّم عليها",
    listPartial: "ظاهر أحدث {count} منتج.",
    nameRequired: "اكتب اسم للجدول.",
    headingRequired: "كل عمود محتاج عنوان بالعربي أو بالإنجليزي.",
    imageHttps: "رابط الصورة لازم يبدأ بـ https://.",
    attachGone: "في منتج أو مجموعة في الجدول ده مبقاش موجود. شيل العلامة من عليه واحفظ تاني.",
    save: "احفظ الجدول",
    create: "اعمل الجدول",
    saving: "بنحفظ…",
    unsavedNew: "الجدول ده لسه ما اتعملش",
    saved: "اتحفظ جدول المقاسات.",
    created: "اتعمل جدول المقاسات.",
    remove: "امسح الجدول",
    removeTitle: "تمسح «{name}»؟",
    removeBody: "المنتجات اللي بيظهر عليها مش هيبقى ليها دليل مقاسات.",
    removing: "بنمسح…",
    removed: "اتمسح جدول المقاسات.",
    cancel: "إلغاء",
    searchPlaceholder: "دوّر باسم الجدول أو المقاس",
    searchLabel: "دوّر في جداول المقاسات",
    clearSearch: "امسح البحث",
    colActions: "إجراءات",
    rowMenu: "إجراءات {name}",
    menuPeek: "بصّة سريعة",
    menuOpen: "افتح وعدّل",
    peekNamed: "بصّة سريعة على {name}",
    openEdit: "افتح وعدّل",
    emptyCell: "—",
    updatedOn: "آخر تعديل {date}",
    more: "كمان",
    noteBoth: "ملاحظة وصورة",
    noteOnly: "ملاحظة من غير صورة",
    imageOnly: "صورة من غير ملاحظة",
    noteNone: "لسه مفيش ملاحظة ولا صورة",
    productTitle: "جدول المقاسات",
    productOwn: "مربوط بالمنتج ده",
    productFromCollection: "من مجموعة {name}",
    productNone: "مفيش جدول مقاسات واصل للمنتج ده. اربط واحد بيه أو بمجموعته.",
    openCharts: "جداول المقاسات",
  },
} satisfies Messages;

/** "S · M · L · XL" — the first column, for the list. */
export function sizeNames(chart: SizeChart, max = 6): string {
  const names = chart.rows.map((row) => row[0]?.trim()).filter(Boolean);
  return names.length > max ? `${names.slice(0, max).join(" · ")} …` : names.join(" · ");
}
