import type { SizeChart } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Size charts (handoff 210): the list, the editor and the product page's line. */
export const SIZE_CHART_STRINGS = {
  en: {
    title: "Size charts",
    description: "A table of sizes shoppers open from the product page as “Size guide”. Attach it to products or to whole collections.",
    newChart: "New size chart",
    colName: "Chart",
    colSizes: "Sizes",
    colUnit: "Unit",
    colAttached: "Shows on",
    colUpdated: "Last change",
    unit_cm: "cm",
    unit_inch: "inch",
    unitLong_cm: "Centimetres",
    unitLong_inch: "Inches",
    rows_one: "1 size",
    rows_other: "{n} sizes",
    products_one: "1 product",
    products_other: "{n} products",
    collections_one: "1 collection",
    collections_other: "{n} collections",
    notAttached: "Not attached yet",
    emptyTitle: "No size charts yet",
    emptyHint: "Make one chart per kind of product — T-shirts, trousers, shoes — and attach it to its collection.",
    // Editor
    newTitle: "New size chart",
    editTitle: "Size chart",
    back: "Size charts",
    basicsTitle: "Name and unit",
    name: "Chart name",
    nameHint: "Only your team sees it — for example “T-shirts”.",
    unit: "The numbers are in",
    unitHint: "Shoppers can switch between cm and inch; the numbers are converted for them.",
    tableTitle: "Sizes table",
    tableHint: "The first column is the size's name (S, M, 42…). Write each heading in Arabic and English — one of them is enough.",
    headingAr: "Heading of column {n} in Arabic",
    headingEn: "Heading of column {n} in English",
    arPlaceholder: "بالعربية",
    enPlaceholder: "English",
    cell: "Row {row}, column {column}",
    addRow: "Add a size",
    addColumn: "Add a column",
    removeRow: "Remove row {n}",
    removeColumn: "Remove column {n}",
    maxRows: "A chart holds up to {max} sizes.",
    maxColumns: "A chart holds up to {max} columns.",
    noteTitle: "Note and picture",
    noteAr: "Note in Arabic",
    noteEn: "Note in English",
    noteHint: "Shown under the table, for example “Measure a T-shirt that fits you well, laid flat”.",
    image: "“How to measure” picture",
    imageHint: "Optional. Upload one, or paste a secure link (https).",
    attachTitle: "Where it shows",
    attachHint: "A chart on the product itself comes first; otherwise the product takes the chart of its collection.",
    products: "Products",
    collections: "Collections",
    searchProducts: "Search products",
    searchCollections: "Search collections",
    noProducts: "No products yet.",
    noCollections: "No collections yet.",
    noMatch: "Nothing matches this search.",
    chosen_one: "1 chosen",
    chosen_other: "{n} chosen",
    noneChosen: "None chosen",
    listPartial: "Showing the newest {count} products.",
    nameRequired: "Give the chart a name.",
    headingRequired: "Every column needs a heading in Arabic or English.",
    imageHttps: "The picture's link must start with https://.",
    attachGone: "A product or collection in this chart no longer exists. Untick it and save again.",
    save: "Save chart",
    create: "Create chart",
    saving: "Saving…",
    unsavedNew: "This chart isn't created yet",
    saved: "Size chart saved.",
    created: "Size chart created.",
    remove: "Delete chart",
    removeTitle: "Delete “{name}”?",
    removeBody: "The products it shows on will have no size guide.",
    removing: "Deleting…",
    removed: "Size chart deleted.",
    cancel: "Cancel",
    // List: search, the row's menu, Quick Look
    searchPlaceholder: "Search by chart or size",
    searchLabel: "Search size charts",
    clearSearch: "Clear the search",
    colActions: "Actions",
    rowMenu: "Actions for {name}",
    menuPeek: "Quick look",
    menuOpen: "Open and edit",
    peekNamed: "Quick look at {name}",
    openEdit: "Open and edit",
    emptyCell: "—",
    updatedOn: "Last change {date}",
    // Editor: the header's menu and what each fold holds
    more: "More",
    noteBoth: "A note and a picture",
    noteOnly: "A note, no picture",
    imageOnly: "A picture, no note",
    noteNone: "No note or picture yet",
    // Product page
    productTitle: "Size chart",
    productOwn: "Attached to this product",
    productFromCollection: "from collection {name}",
    productNone: "No size chart reaches this product. Attach one to it or to its collection.",
    openCharts: "Size charts",
  },
  ar: {
    title: "جداول المقاسات",
    description: "جدول مقاسات يفتحه العميل من صفحة المنتج باسم «دليل المقاسات». اربطه بمنتجات أو بمجموعات كاملة.",
    newChart: "جدول مقاسات جديد",
    colName: "الجدول",
    colSizes: "المقاسات",
    colUnit: "الوحدة",
    colAttached: "يظهر على",
    colUpdated: "آخر تعديل",
    unit_cm: "سم",
    unit_inch: "بوصة",
    unitLong_cm: "سنتيمتر",
    unitLong_inch: "بوصة",
    rows_one: "مقاس واحد",
    rows_two: "مقاسان",
    rows_few: "{n} مقاسات",
    rows_other: "{n} مقاسًا",
    products_one: "منتج واحد",
    products_two: "منتجان",
    products_few: "{n} منتجات",
    products_other: "{n} منتج",
    collections_one: "مجموعة واحدة",
    collections_two: "مجموعتان",
    collections_few: "{n} مجموعات",
    collections_other: "{n} مجموعة",
    notAttached: "غير مرتبط بأي شيء بعد",
    emptyTitle: "لا توجد جداول مقاسات بعد",
    emptyHint: "أنشئ جدولًا لكل نوع من المنتجات — قمصان، سراويل، أحذية — واربطه بمجموعته.",
    newTitle: "جدول مقاسات جديد",
    editTitle: "جدول مقاسات",
    back: "جداول المقاسات",
    basicsTitle: "الاسم والوحدة",
    name: "اسم الجدول",
    nameHint: "يظهر لفريقك فقط — مثل «قمصان».",
    unit: "الأرقام مكتوبة بوحدة",
    unitHint: "يستطيع العميل التبديل بين السنتيمتر والبوصة، وتتحوّل الأرقام تلقائيًا.",
    tableTitle: "جدول المقاسات",
    tableHint: "العمود الأول هو اسم المقاس (S، M، 42…). اكتب عنوان كل عمود بالعربية والإنجليزية — يكفي أحدهما.",
    headingAr: "عنوان العمود {n} بالعربية",
    headingEn: "عنوان العمود {n} بالإنجليزية",
    arPlaceholder: "بالعربية",
    enPlaceholder: "English",
    cell: "الصف {row}، العمود {column}",
    addRow: "إضافة مقاس",
    addColumn: "إضافة عمود",
    removeRow: "إزالة الصف {n}",
    removeColumn: "إزالة العمود {n}",
    maxRows: "يتسع الجدول لـ {max} مقاسًا على الأكثر.",
    maxColumns: "يتسع الجدول لـ {max} عمودًا على الأكثر.",
    noteTitle: "ملاحظة وصورة",
    noteAr: "الملاحظة بالعربية",
    noteEn: "الملاحظة بالإنجليزية",
    noteHint: "تظهر تحت الجدول، مثل «قِس قميصًا يناسبك وهو مفرود».",
    image: "صورة «طريقة القياس»",
    imageHint: "اختياري. ارفع صورة، أو الصق رابطًا آمنًا (https).",
    attachTitle: "أين يظهر",
    attachHint: "الجدول المرتبط بالمنتج نفسه له الأولوية؛ وإلا يأخذ المنتج جدول مجموعته.",
    products: "المنتجات",
    collections: "المجموعات",
    searchProducts: "ابحث في المنتجات",
    searchCollections: "ابحث في المجموعات",
    noProducts: "لا توجد منتجات بعد.",
    noCollections: "لا توجد مجموعات بعد.",
    noMatch: "لا شيء يطابق هذا البحث.",
    chosen_one: "عنصر واحد محدد",
    chosen_two: "عنصران محددان",
    chosen_few: "{n} عناصر محددة",
    chosen_other: "{n} عنصرًا محددًا",
    noneChosen: "لا شيء محدد",
    listPartial: "يُعرض أحدث {count} منتج.",
    nameRequired: "اكتب اسمًا للجدول.",
    headingRequired: "يحتاج كل عمود إلى عنوان بالعربية أو بالإنجليزية.",
    imageHttps: "يجب أن يبدأ رابط الصورة بـ https://.",
    attachGone: "أحد المنتجات أو المجموعات في هذا الجدول لم يعد موجودًا. أزل التحديد عنه ثم احفظ مرة أخرى.",
    save: "حفظ الجدول",
    create: "إنشاء الجدول",
    saving: "جارٍ الحفظ…",
    unsavedNew: "لم يُنشأ هذا الجدول بعد",
    saved: "تم حفظ جدول المقاسات.",
    created: "تم إنشاء جدول المقاسات.",
    remove: "حذف الجدول",
    removeTitle: "هل تريد حذف «{name}»؟",
    removeBody: "المنتجات التي يظهر عليها لن يكون لها دليل مقاسات.",
    removing: "جارٍ الحذف…",
    removed: "تم حذف جدول المقاسات.",
    cancel: "إلغاء",
    searchPlaceholder: "ابحث باسم الجدول أو المقاس",
    searchLabel: "ابحث في جداول المقاسات",
    clearSearch: "مسح البحث",
    colActions: "إجراءات",
    rowMenu: "إجراءات {name}",
    menuPeek: "نظرة سريعة",
    menuOpen: "فتح وتعديل",
    peekNamed: "نظرة سريعة على {name}",
    openEdit: "فتح وتعديل",
    emptyCell: "—",
    updatedOn: "آخر تعديل {date}",
    more: "المزيد",
    noteBoth: "ملاحظة وصورة",
    noteOnly: "ملاحظة بدون صورة",
    imageOnly: "صورة بدون ملاحظة",
    noteNone: "لا توجد ملاحظة ولا صورة بعد",
    productTitle: "جدول المقاسات",
    productOwn: "مرتبط بهذا المنتج",
    productFromCollection: "من مجموعة {name}",
    productNone: "لا يوجد جدول مقاسات لهذا المنتج. اربط جدولًا به أو بمجموعته.",
    openCharts: "جداول المقاسات",
  },
} satisfies Messages;

/** "S · M · L · XL" — the first column, for the list. */
export function sizeNames(chart: SizeChart, max = 6): string {
  const names = chart.rows.map((row) => row[0]?.trim()).filter(Boolean);
  return names.length > max ? `${names.slice(0, max).join(" · ")} …` : names.join(" · ");
}
