import type { DigitalDeliveryType } from "@store-builder/api-client";
import { IconFileDown, IconKey, IconLink, type Icon } from "@/components/icons";
import { fmt, type Messages } from "@/i18n/LocaleContext";

/** Digital products (SPEC §18.2): delivery per product and the private file library. */
export const DIGITAL_STRINGS = {
  en: {
    title: "Digital products",
    description: "What the customer receives after paying: a file, a link or a licence code.",
    views: "Digital products view",
    tabProducts: "Delivery",
    tabFiles: "File library",
    searchLabel: "Search the digital products",
    searchPlaceholder: "Product name or code",
    chipsLabel: "Products by delivery",
    listLabel: "Digital products",
    all: "All",
    chipNotSet: "Needs setup",
    chipPaused: "Paused",
    chipLow: "Codes running low",
    colProduct: "Product",
    colDelivery: "Delivery",
    colStock: "Codes in stock",
    notSet: "Not set up",
    notSetHint: "Nothing is delivered yet",
    paused: "Paused",
    type_file: "File",
    type_link: "Link",
    type_license_codes: "Licence codes",
    setUp: "Set up",
    edit: "Edit",
    editName: "Set what {name} delivers",
    openProduct: "Open the product",
    menuLabel: "Actions for this product",
    stock: "{available} of {total} left",
    emptyProductsTitle: "No digital products yet",
    emptyProductsDescription: "Create a product and choose the type “Digital”. It shows up here so you can set what the customer receives.",
    newProduct: "New product",
    emptyFiltered: "No product matches this search or filter",
    clearAll: "Clear the search and filter",
    deliveryTitle: "Delivery of “{name}”",
    deliveryDescription: "Sent when the order is paid. A cash-on-delivery order is delivered once its payment is recorded.",
    type: "What the customer gets",
    file: "File",
    chooseFile: "Choose a file from the library",
    fileRequired: "Choose the file the customer downloads.",
    noFiles: "The file library is empty. Upload a file first.",
    linkUrl: "Link",
    linkHint: "A private page, a drive folder, a course — anything with an address.",
    linkRequired: "Paste the link the customer opens.",
    message: "Message to the customer",
    messageHint: "Shown on the download page.",
    maxDownloads: "Download limit",
    maxDownloadsHint: "Leave empty for no limit.",
    validHours: "Link valid for (hours)",
    validHoursHint: "Leave empty so it never expires.",
    active: "Deliver automatically",
    activeHint: "Off: nothing is sent until you turn it back on.",
    saved: "Delivery saved.",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    close: "Close",
    codesTitle: "Licence codes",
    codesHint: "One code per line. Each unit sold takes one code; codes already in stock are skipped.",
    addCodes: "Add codes",
    adding: "Adding…",
    codesAdded: "{added} codes added, {duplicates} already there.",
    codeGiven: "Given {date}",
    codeFree: "In stock",
    noCodes: "No codes yet.",
    removeCode: "Remove the code {code}",
    codeRemoved: "Code removed.",
    filesSearchLabel: "Search the files",
    filesSearchPlaceholder: "File name",
    filesList: "Files",
    upload: "Upload file",
    uploading: "Uploading…",
    uploaded: "“{name}” uploaded.",
    maxSize: "Up to {large} GB per file — above {size} MB it goes straight to storage in parts. Files are private: only a buyer's download link can open them.",
    uploadingPercent: "Uploading… {percent}%",
    cancelUpload: "Cancel the upload",
    colFile: "File",
    colSize: "Size",
    colUsed: "Used by",
    colAdded: "Added",
    usedBy_one: "1 product",
    usedBy_other: "{n} products",
    unused: "Not used",
    sizeMb: "{n} MB",
    sizeKb: "{n} KB",
    emptyFilesTitle: "The file library is empty",
    emptyFilesDescription: "Upload the e-books, templates or archives your digital products deliver.",
    emptyFilesFiltered: "No file matches this search",
    clearSearch: "Clear the search",
    delete: "Delete",
    deleteName: "Delete the file {name}",
    deleteFileTitle: "Delete “{name}”?",
    deleteFileDescription: "The file is removed for good. Customers who already bought it can no longer download it.",
    deleting: "Deleting…",
    fileDeleted: "File deleted.",
    fileInUse: "A product still delivers this file. Change its delivery first.",
    fileTooLarge: "The file is too large.",
  },
  ar: {
    title: "المنتجات الرقمية",
    description: "اللي العميل بيستلمه بعد الدفع: ملف، لينك أو كود ترخيص.",
    views: "طريقة عرض المنتجات الرقمية",
    tabProducts: "التسليم",
    tabFiles: "مكتبة الملفات",
    searchLabel: "دوّر في المنتجات الرقمية",
    searchPlaceholder: "اسم المنتج أو الكود",
    chipsLabel: "المنتجات حسب التسليم",
    listLabel: "المنتجات الرقمية",
    all: "الكل",
    chipNotSet: "محتاج تجهيز",
    chipPaused: "واقف",
    chipLow: "الأكواد قرّبت تخلص",
    colProduct: "المنتج",
    colDelivery: "التسليم",
    colStock: "الأكواد المتاحة",
    notSet: "مش متجهّز",
    notSetHint: "مفيش حاجة بتتسلّم لسه",
    paused: "واقف",
    type_file: "ملف",
    type_link: "لينك",
    type_license_codes: "أكواد ترخيص",
    setUp: "جهّز",
    edit: "عدّل",
    editName: "حدّد {name} بيسلّم إيه",
    openProduct: "افتح المنتج",
    menuLabel: "إجراءات المنتج",
    stock: "باقي {available} من {total}",
    emptyProductsTitle: "لسه مفيش منتجات رقمية",
    emptyProductsDescription: "اعمل منتج واختار النوع «رقمي». هيظهر هنا عشان تحدّد العميل بيستلم إيه.",
    newProduct: "منتج جديد",
    emptyFiltered: "مفيش منتج بالبحث أو الفلتر ده",
    clearAll: "امسح البحث والفلتر",
    deliveryTitle: "تسليم «{name}»",
    deliveryDescription: "بيتبعت لما الأوردر يتدفع. أوردر الدفع عند الاستلام بيتسلّم بعد ما دفعه يتسجّل.",
    type: "العميل بيستلم إيه",
    file: "الملف",
    chooseFile: "اختار ملف من المكتبة",
    fileRequired: "اختار الملف اللي العميل هيحمّله.",
    noFiles: "مكتبة الملفات فاضية. ارفع ملف الأول.",
    linkUrl: "اللينك",
    linkHint: "صفحة خاصة، فولدر على درايف، كورس — أي حاجة ليها عنوان.",
    linkRequired: "حط اللينك اللي العميل هيفتحه.",
    message: "رسالة للعميل",
    messageHint: "بتظهر في صفحة التحميل.",
    maxDownloads: "أقصى عدد تحميل",
    maxDownloadsHint: "سيبه فاضي لو من غير حد.",
    validHours: "اللينك شغّال لمدة (بالساعات)",
    validHoursHint: "سيبه فاضي عشان اللينك يفضل شغّال على طول.",
    active: "سلّم لوحدك",
    activeHint: "لو مقفول: مفيش حاجة بتتبعت لحد ما تشغّله تاني.",
    saved: "التسليم اتحفظ.",
    save: "حفظ",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    close: "إغلاق",
    codesTitle: "أكواد الترخيص",
    codesHint: "كود في كل سطر. كل قطعة بتتباع بتاخد كود؛ الأكواد الموجودة قبل كده مش بتتكرر.",
    addCodes: "ضيف أكواد",
    adding: "بنضيف…",
    codesAdded: "اتضاف {added} كود، و{duplicates} كانوا موجودين.",
    codeGiven: "اتسلّم {date}",
    codeFree: "متاح",
    noCodes: "لسه مفيش أكواد.",
    removeCode: "شيل الكود {code}",
    codeRemoved: "الكود اتشال.",
    filesSearchLabel: "دوّر في الملفات",
    filesSearchPlaceholder: "اسم الملف",
    filesList: "الملفات",
    upload: "ارفع ملف",
    uploading: "بنرفع…",
    uploaded: "«{name}» اترفع.",
    maxSize: "لحد {large} جيجا للملف — فوق {size} ميجا بيترفع على أجزاء للتخزين على طول. الملفات خاصة: مفيش غير لينك تحميل المشتري اللي يفتحها.",
    uploadingPercent: "بنرفع… {percent}%",
    cancelUpload: "الغي الرفع",
    colFile: "الملف",
    colSize: "الحجم",
    colUsed: "مستخدم في",
    colAdded: "اتضاف",
    usedBy_one: "منتج واحد",
    usedBy_two: "منتجين",
    usedBy_few: "{n} منتجات",
    usedBy_other: "{n} منتج",
    unused: "مش مستخدم",
    sizeMb: "{n} ميجا",
    sizeKb: "{n} كيلوبايت",
    emptyFilesTitle: "مكتبة الملفات فاضية",
    emptyFilesDescription: "ارفع الكتب والقوالب والملفات اللي منتجاتك الرقمية بتسلّمها.",
    emptyFilesFiltered: "مفيش ملف بالبحث ده",
    clearSearch: "امسح البحث",
    delete: "امسح",
    deleteName: "امسح الملف {name}",
    deleteFileTitle: "تمسح «{name}»؟",
    deleteFileDescription: "الملف هيتمسح نهائي. العملاء اللي اشتروه مش هيقدروا يحمّلوه تاني.",
    deleting: "بنمسح…",
    fileDeleted: "الملف اتمسح.",
    fileInUse: "في منتج لسه بيسلّم الملف ده. غيّر تسليمه الأول.",
    fileTooLarge: "الملف أكبر من المسموح.",
  },
} satisfies Messages;

export type DigitalStrings = (typeof DIGITAL_STRINGS)["en"];

export const TYPE_ICON: Record<DigitalDeliveryType, Icon> = { file: IconFileDown, link: IconLink, license_codes: IconKey };

/** A file's size in the viewer's digits: megabytes with one decimal, kilobytes whole. */
export function sizeText(t: DigitalStrings, bytes: number): string {
  if (bytes >= 1024 * 1024) return fmt(t.sizeMb, { n: Math.round((bytes / 1024 / 1024) * 10) / 10 });
  return fmt(t.sizeKb, { n: Math.max(1, Math.round(bytes / 1024)) });
}

/** Codes are "running low" at five or fewer left — the same line the stock chip always drew. */
export const LOW_CODES = 5;
