import type { Messages } from "@/i18n/LocaleContext";

/** Stock movement history (handoff 389): the Inventory tab and the product page's drawer. */
export const MOVEMENT_STRINGS = {
  en: {
    tab: "Stock movements",
    historyLink: "Stock history",
    historyTitle: "Stock history",
    historyOf: "Stock history: {name}",
    historyHint: "Every change to this variant's stock, newest first.",
    variant: "Variant",
    singleVariant: "The product",
    onHand: "On hand",
    reserved: "Reserved",
    available: "Available",
    openInInventory: "Open in Inventory",
    close: "Close",
    // filters
    filters: "Filter stock movements",
    product: "Product",
    allProducts: "All products",
    type: "Type",
    allTypes: "All types",
    location: "Location",
    allLocations: "All locations",
    from: "From",
    to: "To",
    clear: "Clear filters",
    rangeWrong: "The start date is after the end date.",
    exportCsv: "Export CSV",
    exportExcel: "Export Excel",
    exporting: "Preparing the file…",
    exportFailed: "The file could not be prepared. Try again.",
    // columns
    colDate: "Date",
    colType: "Type",
    colProduct: "Product",
    colChange: "Change",
    colLocation: "Location",
    colSource: "Source",
    colReason: "Reason",
    colBy: "By",
    reservedDelta: "Reserved {n}",
    // types
    type_restock: "Restock",
    type_adjustment: "Adjustment",
    type_reserve: "Reserved",
    type_release: "Released",
    type_commit: "Deducted",
    type_return_restock: "Return restock",
    // sources
    src_order: "Order {orderNumber} — {event}",
    src_orderPlain: "Order {orderNumber}",
    src_purchase_order: "Purchase order {number}",
    src_stock_count: "Stock count",
    src_return: "Return for order {orderNumber}",
    src_stock_lot: "Lot {lotCode}",
    src_location_adjustment: "Location adjustment",
    src_bulk_update: "Bulk update from a sheet",
    src_variant_table: "Variant table",
    src_manual: "Manual",
    // order events
    ev_placed: "placed",
    ev_upsell: "upsell",
    ev_edited: "edited",
    ev_reconfirmed: "reconfirmed",
    ev_reopened: "reopened",
    ev_rejected: "rejected",
    ev_cancelled: "cancelled",
    ev_payment_expired: "payment expired",
    ev_customer_blocked: "customer blocked",
    ev_returned: "returned",
    ev_reshipped: "reshipped",
    // actors
    byCustomer: "Customer",
    bySystem: "System",
    byDeleted: "Deleted user",
    empty: "No stock movements in this period",
    emptyHint: "Restocks, adjustments, orders and returns show here as they happen.",
    timezone: "Times are in the store's timezone ({zone}).",
  },
  ar: {
    tab: "حركة المخزون",
    historyLink: "سجل حركة المخزون",
    historyTitle: "سجل حركة المخزون",
    historyOf: "سجل حركة المخزون: {name}",
    historyHint: "كل تغيير حصل على مخزون النسخة دي، الأحدث الأول.",
    variant: "النسخة",
    singleVariant: "المنتج",
    onHand: "الموجود",
    reserved: "محجوز",
    available: "المتاح",
    openInInventory: "افتحه في المخزون",
    close: "إغلاق",
    filters: "فلترة حركة المخزون",
    product: "المنتج",
    allProducts: "كل المنتجات",
    type: "النوع",
    allTypes: "كل الأنواع",
    location: "المخزن",
    allLocations: "كل المخازن",
    from: "من",
    to: "إلى",
    clear: "امسح الفلاتر",
    rangeWrong: "تاريخ البداية بعد تاريخ النهاية.",
    exportCsv: "تصدير CSV",
    exportExcel: "تصدير Excel",
    exporting: "بنجهّز الملف…",
    exportFailed: "معرفناش نجهّز الملف. جرّب تاني.",
    colDate: "التاريخ",
    colType: "النوع",
    colProduct: "المنتج",
    colChange: "التغيير",
    colLocation: "المخزن",
    colSource: "المصدر",
    colReason: "السبب",
    colBy: "بواسطة",
    reservedDelta: "محجوز {n}",
    type_restock: "إضافة مخزون",
    type_adjustment: "تعديل",
    type_reserve: "حجز",
    type_release: "فك حجز",
    type_commit: "خصم",
    type_return_restock: "إرجاع للمخزون",
    src_order: "طلب {orderNumber} — {event}",
    src_orderPlain: "طلب {orderNumber}",
    src_purchase_order: "أمر شراء {number}",
    src_stock_count: "جرد",
    src_return: "مرتجع طلب {orderNumber}",
    src_stock_lot: "دفعة {lotCode}",
    src_location_adjustment: "تعديل مخزن",
    src_bulk_update: "تحديث جماعي من ملف",
    src_variant_table: "جدول النسخ",
    src_manual: "يدوي",
    ev_placed: "إنشاء",
    ev_upsell: "عرض إضافي",
    ev_edited: "تعديل",
    ev_reconfirmed: "إعادة تأكيد",
    ev_reopened: "إعادة فتح",
    ev_rejected: "رفض",
    ev_cancelled: "إلغاء",
    ev_payment_expired: "انتهاء مهلة الدفع",
    ev_customer_blocked: "حظر العميل",
    ev_returned: "مرتجع",
    ev_reshipped: "إعادة شحن",
    byCustomer: "العميل",
    bySystem: "النظام",
    byDeleted: "مستخدم محذوف",
    empty: "مفيش حركة مخزون في الفترة دي",
    emptyHint: "إضافة المخزون والتعديلات والطلبات والمرتجعات بتظهر هنا أول ما تحصل.",
    timezone: "الأوقات بتوقيت المتجر ({zone}).",
  },
} satisfies Messages;

export type MovementStrings = (typeof MOVEMENT_STRINGS)["en"];
