import type { Messages } from "@/i18n/LocaleContext";

/**
 * Every word of the create-order sheet, in one table so its zones (the
 * stepper, the three steps, the footer) say things the same way. Read with
 * `useT(CREATE_STRINGS)`.
 */
export const CREATE_STRINGS = {
  en: {
    title: "New order",
    description: "An order you take by phone, chat or in person. Prices come from your catalog.",
    // stepper
    stepsLabel: "Order steps",
    stepCustomer: "Customer",
    stepProducts: "Products",
    stepDelivery: "Delivery and payment",
    stepDeliveryShort: "Delivery",
    stepNumber: "{n}",
    stepOf: "Step {n} of {total}: {name}",
    stepDone: "Step {n} of {total}: {name}, done",
    // draft
    draftRestored: "We picked up where you left off.",
    draftClear: "Clear the draft",
    draftCleared: "The draft is cleared.",
    draftUndo: "Bring it back",
    draftPruned: "{items} left the draft: no longer on sale.",
    // customer
    phone: "Mobile number",
    phoneSample: "01XXXXXXXXX",
    phoneHint: "Type the number and we will check if they are already with you.",
    phoneRequired: "Type the customer's mobile number.",
    phoneInvalid: "This is not an Egyptian mobile: {digits} digits starting with {prefix}.",
    phoneOk: "The number looks right",
    name: "Full name",
    nameRequired: "Type the customer's name.",
    email: "Email (optional)",
    lookingUp: "Looking them up…",
    newCustomer: "New customer",
    knownCustomer: "{orders} before",
    knownNoOrders: "Already on your list, no orders yet",
    rejectedCount: "{n} rejected",
    knownBlocked: "This customer is blocked.",
    // products
    linesTitle: "In this order",
    remove: "Remove {name}",
    quantity: "Quantity",
    quantityOf: "Quantity of {name}",
    less: "One less",
    more: "One more",
    searchLabel: "Search products",
    searchPlaceholder: "Search by name or code",
    noProducts: "You have no active products yet.",
    noProductsHint: "Publish a product from Products, then come back to this order: what you typed stays here.",
    openCatalog: "Open products",
    noMatches: "No product matches “{term}”.",
    inOrder: "{n} in the order",
    stock: "{n} in stock",
    outOfStock: "Out of stock",
    variantOut: "out",
    noVariants: "This product has no variant on sale.",
    variant: "Variant",
    offer: "Offer",
    noOffer: "No offer",
    add: "Add to order",
    added: "{name} is in the order.",
    noItems: "Add at least one product.",
    // delivery and payment
    address: "Delivery address",
    useLastAddress: "Use their last address",
    governorate: "Governorate",
    chooseGovernorate: "Choose…",
    governoratesFailed: "We couldn't load the governorates.",
    retry: "Try again",
    city: "City / area",
    cityRequired: "Type the city or area.",
    addressLine: "Address",
    addressPlaceholder: "Street, building, floor, a landmark",
    addressRequired: "Type the address.",
    payment: "Payment",
    paymentMethod: "Payment method",
    extras: "Discount and shipping",
    coupon: "Discount code",
    couponHint: "Applied when you leave the field or press Enter.",
    shipping: "Shipping",
    shippingAuto: "Calculated from the governorate. Type an amount to set it yourself.",
    shippingPlaceholder: "Automatic",
    shippingInvalid: "Type the amount in numbers, or leave it empty.",
    notes: "Notes",
    notesPlaceholder: "Anything the team or the courier should know",
    summary: "Summary",
    subtotal: "Products",
    discount: "Discount",
    tax: "Tax",
    total: "Total",
    // footer
    pricing: "Calculating…",
    addToSee: "Add a product to see the total.",
    totalFailed: "We couldn't work out the total.",
    shippingLine: "Shipping {amount}",
    discountLine: "Discount {amount}",
    next: "Next",
    create: "Create order",
    creating: "Creating…",
    created: "Order {number} created.",
    closeAsk: "Close without creating the order? What you typed stays saved as a draft.",
    closeYes: "Close",
    closeNo: "Keep going",
  },
  ar: {
    title: "أوردر جديد",
    description: "أوردر بتاخده بالتليفون أو الشات أو وش لوش. الأسعار من الكتالوج.",
    // stepper
    stepsLabel: "خطوات الأوردر",
    stepCustomer: "العميل",
    stepProducts: "المنتجات",
    stepDelivery: "التوصيل والدفع",
    stepDeliveryShort: "التوصيل",
    stepNumber: "{n}",
    stepOf: "خطوة {n} من {total}: {name}",
    stepDone: "خطوة {n} من {total}: {name}، خلصت",
    // draft
    draftRestored: "كمّلنا من آخر مرة.",
    draftClear: "امسح المسودة",
    draftCleared: "المسودة اتمسحت.",
    draftUndo: "رجّعها",
    draftPruned: "شلنا {items} من المسودة عشان مبقاش متاح للبيع.",
    // customer
    phone: "رقم الموبايل",
    phoneSample: "01XXXXXXXXX",
    phoneHint: "اكتب الرقم ونشوف لو العميل ده معاك قبل كده.",
    phoneRequired: "اكتب رقم موبايل العميل.",
    phoneInvalid: "الرقم ده مش موبايل مصري: {digits} رقم ويبدأ بـ {prefix}.",
    phoneOk: "الرقم مظبوط",
    name: "الاسم بالكامل",
    nameRequired: "اكتب اسم العميل.",
    email: "الإيميل (اختياري)",
    lookingUp: "بندوّر عليه…",
    newCustomer: "عميل جديد",
    knownCustomer: "{orders} قبل كده",
    knownNoOrders: "متسجّل عندك ولسه مفيش أوردرات",
    rejectedCount: "رفض {n}",
    knownBlocked: "العميل ده محظور.",
    // products
    linesTitle: "في الأوردر ده",
    remove: "شيل {name}",
    quantity: "الكمية",
    quantityOf: "كمية {name}",
    less: "قلّل واحدة",
    more: "زوّد واحدة",
    searchLabel: "دوّر في المنتجات",
    searchPlaceholder: "دوّر بالاسم أو الكود",
    noProducts: "مفيش منتجات شغّالة لسه.",
    noProductsHint: "انشر منتج من صفحة المنتجات وارجع للأوردر ده: اللي كتبته هيفضل هنا.",
    openCatalog: "افتح المنتجات",
    noMatches: "مفيش منتج باسم «{term}».",
    inOrder: "{n} في الأوردر",
    stock: "{n} في المخزون",
    outOfStock: "خلص من المخزون",
    variantOut: "خلص",
    noVariants: "المنتج ده مفيش منه نوع متاح للبيع.",
    variant: "النوع",
    offer: "العرض",
    noOffer: "من غير عرض",
    add: "ضيف للأوردر",
    added: "{name} بقى في الأوردر.",
    noItems: "ضيف منتج واحد على الأقل.",
    // delivery and payment
    address: "عنوان التوصيل",
    useLastAddress: "استخدم آخر عنوان ليه",
    governorate: "المحافظة",
    chooseGovernorate: "اختار…",
    governoratesFailed: "معرفناش نحمّل المحافظات.",
    retry: "جرّب تاني",
    city: "المدينة / المنطقة",
    cityRequired: "اكتب المدينة أو المنطقة.",
    addressLine: "العنوان",
    addressPlaceholder: "الشارع، العمارة، الدور، علامة مميزة",
    addressRequired: "اكتب العنوان.",
    payment: "الدفع",
    paymentMethod: "طريقة الدفع",
    extras: "الخصم والشحن",
    coupon: "كود الخصم",
    couponHint: "بيتطبّق لما تخرج من الخانة أو تدوس Enter.",
    shipping: "الشحن",
    shippingAuto: "بيتحسب من المحافظة. اكتب مبلغ لو عايز تحدده بنفسك.",
    shippingPlaceholder: "تلقائي",
    shippingInvalid: "اكتب المبلغ بالأرقام، أو سيبه فاضي.",
    notes: "ملاحظات",
    notesPlaceholder: "أي حاجة الفريق أو المندوب محتاج يعرفها",
    summary: "الملخص",
    subtotal: "إجمالي المنتجات",
    discount: "الخصم",
    tax: "الضريبة",
    total: "الإجمالي",
    // footer
    pricing: "بنحسب…",
    addToSee: "ضيف منتج عشان تشوف الإجمالي.",
    totalFailed: "معرفناش نحسب الإجمالي.",
    shippingLine: "الشحن {amount}",
    discountLine: "خصم {amount}",
    next: "التالي",
    create: "أنشئ الأوردر",
    creating: "بنعمله…",
    created: "الأوردر {number} اتعمل.",
    closeAsk: "تقفل من غير ما تنشئ الأوردر؟ اللي كتبته هيفضل محفوظ كمسودة.",
    closeYes: "اقفل",
    closeNo: "كمّل",
  },
} satisfies Messages;

export type CreateStrings = Record<keyof (typeof CREATE_STRINGS)["en"], string>;
