import type { Locale, Messages } from "@/i18n/LocaleContext";
import { humanize } from "@/lib/format";

export type CancelReason = "price" | "changed_mind" | "found_cheaper" | "ordered_by_mistake" | "other";

export const STRINGS = {
  en: {
    title: "Call center",
    description: "Confirm cash-on-delivery orders by phone before they ship.",
    navAgents: "Agents",
    navLogs: "Call logs",
    navSettings: "Settings",
    statInQueue: "In queue",
    statDueNow: "Due now",
    statConfirmedToday: "Confirmed today",
    statNoAnswerToday: "No answer today",
    statAvgHandle: "Avg handle",
    myStatus: "My status",
    filterDue: "Due now",
    filterFlagged: "Flagged",
    filterMine: "Mine",
    searchPlaceholder: "Phone or order #",
    searchLabel: "Search the queue",
    next: "Next",
    nextTitle: "Claim the next due item",
    emptyFilter: "No orders match this filter.",
    loadingQueue: "Loading queue…",
    pickOrder: "Pick an order to start calling",
    pickOrderHint: "Select an order from the queue or press Next to claim the next due order. Keyboard shortcuts 1–6 record the outcome.",
    emptyQueue: "No orders waiting for confirmation",
    emptyQueueHint: "New cash-on-delivery orders appear here automatically.",
    toastLocked: "{order} was just claimed by another agent — moving to the next one.",
    lockedByOther: "Another agent is working on this order. You can view it but not record an outcome.",
    claim: "Claim this order",
    viewOrder: "Open order",
    loadingDetails: "Loading order details…",
    postponeServerNote: "The server schedules the next attempt 24 hours from now; your choice is saved in the note.",
    lastOutcome: "Last result",
    nextDue: "Next due order",
    toastQueueClear: "Queue is clear — nothing due right now.",
    toastStatus: "You are now {status}.",
    toastOutcome: "{order} — {outcome} recorded.",
    priorityFlagged: "Flagged",
    priorityHigh: "High",
    mine: "Mine",
    attemptsTitle: "{n} attempt(s)",
    assignedToYou: "Assigned to you",
    alt: "Alt:",
    hangUp: "Hang up",
    call: "Call",
    openDialer: "Open dialer",
    onCall: "On call",
    callTimer: "Call timer",
    voipBefore: "No VoIP line is connected — the timer only counts time on this screen.",
    voipAfter: "Use “Open dialer” to call from your phone.",
    riskFlags: "Risk flags: {flags}. Verify before confirming.",
    listSeparator: ", ",
    cardOrder: "Order",
    shipping: "Shipping",
    totalCod: "Total (COD)",
    source: "Source",
    created: "Created",
    attempts: "Attempts",
    cardAddress: "Delivery address",
    editAddress: "Edit address",
    toastAddress: "Address updated for this order.",
    cardHistory: "Customer history",
    histOrders: "Orders",
    histRejected: "Rejected",
    reliability: "Reliability",
    noRiskFlags: "No risk flags.",
    cardScript: "Suggested script",
    collapse: "Collapse",
    expand: "Expand",
    collapsed: "Collapsed.",
    outcome: "Outcome",
    outcomeHint: "Press the number key to record",
    note: "Note",
    sendWhatsapp: "Send WhatsApp confirmation instead",
    autoAdvance: "Auto-advances to the next due order after saving.",
    postponeTitle: "Postpone — call back when?",
    postpone1h: "In 1 hour",
    postpone3h: "In 3 hours",
    postponeTomorrow: "Tomorrow 10:00",
    phoneCopied: "Phone number copied.",
    copyFailed: "Could not copy — clipboard blocked.",
    cancelTitle: "Cancel order",
    cancelDescription: "Record why the customer is cancelling. The order is rejected and its stock released.",
    reason: "Reason",
    downsellLabel: "Offered 15% (note only)",
    downsellDescription: "Records in the note that a 15% discount was offered. No discount is applied to the order.",
    governorate: "Governorate",
    address: "Address",
  },
  ar: {
    title: "مركز الاتصال",
    description: "أكِّد طلبات الدفع عند الاستلام هاتفيًا قبل شحنها.",
    navAgents: "الموظفون",
    navLogs: "سجل المكالمات",
    navSettings: "الإعدادات",
    statInQueue: "في قائمة الانتظار",
    statDueNow: "مستحق الآن",
    statConfirmedToday: "تم تأكيده اليوم",
    statNoAnswerToday: "لم يرد اليوم",
    statAvgHandle: "متوسط مدة المكالمة",
    myStatus: "حالتي",
    filterDue: "مستحق الآن",
    filterFlagged: "مُعلَّم",
    filterMine: "طلباتي",
    searchPlaceholder: "رقم الهاتف أو رقم الطلب",
    searchLabel: "البحث في قائمة الانتظار",
    next: "التالي",
    nextTitle: "استلام الطلب المستحق التالي",
    emptyFilter: "لا توجد طلبات تطابق هذا الفلتر.",
    loadingQueue: "جارٍ تحميل قائمة الانتظار…",
    pickOrder: "اختر طلبًا لبدء الاتصال",
    pickOrderHint: "اختر طلبًا من قائمة الانتظار أو اضغط «التالي» لاستلام الطلب المستحق التالي. استخدم المفاتيح 1–6 لتسجيل نتيجة المكالمة.",
    emptyQueue: "لا توجد طلبات بانتظار التأكيد",
    emptyQueueHint: "تظهر طلبات الدفع عند الاستلام الجديدة هنا تلقائيًا.",
    toastLocked: "استلم موظف آخر الطلب {order} للتو — جارٍ الانتقال إلى الطلب التالي.",
    lockedByOther: "يعمل موظف آخر على هذا الطلب. يمكنك عرضه لكن لا يمكنك تسجيل نتيجة.",
    claim: "استلام هذا الطلب",
    viewOrder: "فتح الطلب",
    loadingDetails: "جارٍ تحميل تفاصيل الطلب…",
    postponeServerNote: "يحدد الخادم المحاولة التالية بعد 24 ساعة من الآن؛ ويُحفظ اختيارك في الملاحظة.",
    lastOutcome: "آخر نتيجة",
    nextDue: "الطلب المستحق التالي",
    toastQueueClear: "قائمة الانتظار فارغة — لا توجد طلبات مستحقة الآن.",
    toastStatus: "حالتك الآن: {status}.",
    toastOutcome: "{order} — تم تسجيل النتيجة: {outcome}.",
    priorityFlagged: "مُعلَّم",
    priorityHigh: "أولوية عالية",
    mine: "لي",
    attemptsTitle: "عدد المحاولات: {n}",
    assignedToYou: "مُسنَد إليك",
    alt: "رقم بديل:",
    hangUp: "إنهاء المكالمة",
    call: "اتصال",
    openDialer: "فتح لوحة الاتصال",
    onCall: "في مكالمة",
    callTimer: "مؤقت المكالمة",
    voipBefore: "مفيش خط VoIP متوصل — العداد بيحسب الوقت على الشاشة دي بس.",
    voipAfter: "استخدم «فتح لوحة الاتصال» عشان تتصل من موبايلك.",
    riskFlags: "مؤشرات خطر: {flags}. تحقّق قبل التأكيد.",
    listSeparator: "، ",
    cardOrder: "الطلب",
    shipping: "الشحن",
    totalCod: "الإجمالي (الدفع عند الاستلام)",
    source: "المصدر",
    created: "تاريخ الإنشاء",
    attempts: "المحاولات",
    cardAddress: "عنوان التوصيل",
    editAddress: "تعديل العنوان",
    toastAddress: "تم تحديث عنوان هذا الطلب.",
    cardHistory: "سجل العميل",
    histOrders: "الطلبات",
    histRejected: "مرفوض",
    reliability: "الموثوقية",
    noRiskFlags: "لا توجد مؤشرات خطر.",
    cardScript: "النص المقترح للمكالمة",
    collapse: "طي",
    expand: "توسيع",
    collapsed: "مطوي.",
    outcome: "نتيجة المكالمة",
    outcomeHint: "اضغط مفتاح الرقم للتسجيل",
    note: "ملاحظة",
    sendWhatsapp: "إرسال تأكيد عبر WhatsApp بدلًا من ذلك",
    autoAdvance: "ينتقل تلقائيًا إلى الطلب المستحق التالي بعد الحفظ.",
    postponeTitle: "تأجيل — متى نعاود الاتصال؟",
    postpone1h: "بعد ساعة",
    postpone3h: "بعد 3 ساعات",
    postponeTomorrow: "غدًا الساعة 10:00",
    phoneCopied: "تم نسخ رقم الهاتف.",
    copyFailed: "تعذّر النسخ — الوصول إلى الحافظة محظور.",
    cancelTitle: "إلغاء الطلب",
    cancelDescription: "سجّل سبب إلغاء العميل. سيتم رفض الطلب وإعادة المخزون.",
    reason: "السبب",
    downsellLabel: "تم عرض خصم 15% (ملاحظة فقط)",
    downsellDescription: "يُسجَّل في الملاحظة أنه تم عرض خصم 15%. لا يُطبَّق أي خصم على الطلب.",
    governorate: "المحافظة",
    address: "العنوان",
  },
} satisfies Messages;

export const CANCEL_REASON_LABELS: Record<Locale, Record<CancelReason, string>> = {
  en: {
    price: "Price too high",
    changed_mind: "Changed mind",
    found_cheaper: "Found cheaper elsewhere",
    ordered_by_mistake: "Ordered by mistake",
    other: "Other",
  },
  ar: {
    price: "السعر مرتفع",
    changed_mind: "غيّر رأيه",
    found_cheaper: "وجد سعرًا أرخص في مكان آخر",
    ordered_by_mistake: "طلب بالخطأ",
    other: "سبب آخر",
  },
};

const RISK_FLAG_LABELS: Record<Locale, Record<string, string>> = {
  en: {
    duplicate_order_window: "Duplicate order window",
  },
  ar: {
    duplicate_order_window: "طلب مكرر خلال فترة قصيرة",
  },
};

export function riskFlagLabel(flag: string, locale: Locale): string {
  return RISK_FLAG_LABELS[locale][flag] ?? humanize(flag);
}
