import type { PickupStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Click and collect (handoff 225): the Shipping tab's settings, Orders →
 * Pickups, the hand-over dialog and the order page's pickup block.
 */
export const PICKUP_STRINGS = {
  en: {
    // settings (Shipping → Store pickup)
    title: "Store pickup",
    description:
      "Customers order online and collect the order themselves: no delivery address and no shipping fee. They get a 6-digit code to show when they collect.",
    toggle: "Offer store pickup",
    hintOff: "Off: customers don't see the pickup choice at checkout.",
    hintOn: "At checkout the customer chooses between delivery and picking up in store.",
    placesTitle: "Pickup places",
    placesHint: "These are your stock locations (Inventory → Locations). A place is offered only when every item of the order is in stock there.",
    placeToggle: "Pickup at {name}",
    placeOn: "Customers can pick up here",
    placeOff: "Not a pickup place",
    instructions: "Pickup instructions",
    instructionsHint: "Shown to the customer with the code: where to go, what to bring.",
    hours: "Opening hours",
    langAr: "Arabic",
    langEn: "English",
    instructionsFor: "{name}: pickup instructions, {lang}",
    hoursFor: "{name}: opening hours, {lang}",
    instructionsPlaceholderAr: "اسأل عن شباك الاستلام ووري الكود.",
    instructionsPlaceholderEn: "Ask for the pickup counter and show your code.",
    hoursPlaceholderAr: "كل يوم من 10 الصبح لـ 10 بالليل",
    hoursPlaceholderEn: "Daily, 10am to 10pm",
    inactivePlace: "This location is switched off in Inventory, so customers won't be offered it.",
    noAddress: "No address yet. Add one in Inventory → Locations so customers can find the place.",
    manageLocations: "Manage locations",
    errNoPlace: "Turn pickup on for at least one place.",
    noLocationsTitle: "No locations yet",
    noLocationsBody: "Add a warehouse or a shop in Inventory → Locations, then offer pickup from it.",
    locationsDenied: "Your role can't read the store's locations, so pickup places can't be changed here.",
    save: "Save",
    saving: "Saving…",
    discard: "Discard",
    saved: "Saved. Customers see the change at checkout right away.",
    noManage: "Changing store pickup needs the shipping permission. Ask the store owner.",
    openQueue: "Pickups",
    // queue (Orders → Pickups)
    queueTitle: "Pickups",
    queueDescription: "Orders customers collect in store. Get each one ready, then hand it over against the customer's code.",
    backToOrders: "Orders",
    settingsLink: "Pickup settings",
    filterLabel: "Filter pickups by status",
    tabPending: "Preparing",
    tabPendingCount: "Preparing ({count})",
    tabReady: "Ready for pickup",
    tabReadyCount: "Ready for pickup ({count})",
    tabCollected: "Collected",
    tabCancelled: "Cancelled",
    tabAll: "All",
    statusPending: "Preparing",
    statusReady: "Ready for pickup",
    statusCollected: "Collected",
    statusCancelled: "Cancelled",
    placeFilter: "Place",
    allPlaces: "All places",
    colOrder: "Order",
    colPlace: "Place",
    colPlaced: "Placed",
    colTotal: "Total",
    colStatus: "Status",
    markReady: "Mark ready",
    marking: "Marking…",
    handOver: "Hand over",
    readyDone: "Order {number} is ready. The customer was emailed the place and the code.",
    readyDoneNoEmail: "Order {number} is ready. It has no email: tell the customer yourself.",
    handOverTitle: "Hand over order {number}",
    handOverBody: "Type the {n}-digit code the customer shows you.",
    codeLabel: "Pickup code",
    codeWrong: "Wrong code",
    codeIncomplete: "The code is {n} digits.",
    confirmHandOver: "Confirm handover",
    handingOver: "Handing over…",
    cancel: "Cancel",
    handedOver: "Order {number} was handed over.",
    stale: "This pickup changed in the meantime. The list was refreshed.",
    noOrderManage: "Getting pickups ready and handing them over needs the orders permission. Ask the store owner.",
    readySince: "Ready since {time}",
    collectedOn: "Collected {time}",
    payOnPickup: "Pays on pickup",
    paid: "Paid",
    customer: "Customer",
    total: "Total",
    emptyPendingTitle: "Nothing to prepare",
    emptyPendingBody: "Orders that customers choose to pick up in store show up here.",
    emptyReadyTitle: "No orders waiting for their customer",
    emptyReadyBody: "An order you mark ready waits here until it is handed over.",
    emptyOtherTitle: "No pickups here",
    showAll: "Show all pickups",
    offTitle: "Store pickup is off",
    offBody: "Turn it on in Shipping → Store pickup. At checkout the customer then chooses between delivery and picking up in store.",
    offAction: "Set up store pickup",
    loadFailed: "We couldn't load more pickups.",
    searchLabel: "Search the pickups",
    searchPlaceholder: "Order number, customer or phone",
    searchLoaded: "Searching the pickups loaded so far. Load more to look further.",
    listLabel: "Pickups",
    colCustomer: "Customer",
    colAge: "Ordered",
    colAction: "Next step",
    noName: "Customer without a name",
    peek: "Preview the pickup of {who}",
    openOrder: "Open order {number}",
    openOrderFull: "Open the order",
    menuLabel: "Actions for order {number}",
    menuOpen: "Open the order",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopyPhone: "Copy the number",
    menuCopyOrder: "Copy the order number",
    copiedPhone: "The customer's number is copied",
    copiedOrder: "The order number is copied",
    placedWhen: "Ordered {when}",
    pickupPlace: "Pickup place",
    phoneHidden: "The number is hidden for your role",
    noPhone: "No phone number",
    hintPending: "Get the order ready, then mark it ready: the customer is emailed the place and the code.",
    hintReady: "The customer shows the pickup code. Type it to hand the order over.",
    emptySearchTitle: "No pickup matches this search",
    clearSearch: "Clear the search",
    refresh: "Refresh",
    // order page
    blockTitle: "Store pickup",
    blockHint: "The customer collects this order: no delivery address, no shipping.",
    blockPlace: "Place",
  },
  ar: {
    title: "الاستلام من الفرع",
    description: "العميل يطلب أونلاين ويستلم الأوردر بنفسه: من غير عنوان توصيل ومن غير مصاريف شحن. بياخد كود من ٦ أرقام يوريه وهو بيستلم.",
    toggle: "فعّل الاستلام من الفرع",
    hintOff: "مقفول: العميل مش بيشوف اختيار الاستلام في صفحة الدفع.",
    hintOn: "في صفحة الدفع العميل بيختار بين التوصيل والاستلام من الفرع.",
    placesTitle: "أماكن الاستلام",
    placesHint: "الأماكن دي هي مخازنك (المخزون ← المخازن). المكان بيظهر للعميل بس لو كل منتجات الأوردر متوفرة فيه.",
    placeToggle: "الاستلام من {name}",
    placeOn: "العميل يقدر يستلم من هنا",
    placeOff: "مش مكان استلام",
    instructions: "تعليمات الاستلام",
    instructionsHint: "بتظهر للعميل مع الكود: يروح فين ويجيب معاه إيه.",
    hours: "مواعيد العمل",
    langAr: "بالعربي",
    langEn: "بالإنجليزي",
    instructionsFor: "{name}: تعليمات الاستلام {lang}",
    hoursFor: "{name}: مواعيد العمل {lang}",
    instructionsPlaceholderAr: "اسأل عن شباك الاستلام ووري الكود.",
    instructionsPlaceholderEn: "Ask for the pickup counter and show your code.",
    hoursPlaceholderAr: "كل يوم من 10 الصبح لـ 10 بالليل",
    hoursPlaceholderEn: "Daily, 10am to 10pm",
    inactivePlace: "المكان ده مقفول في المخزون، فمش هيتعرض على العميل.",
    noAddress: "لسه من غير عنوان. ضيف العنوان من المخزون ← المخازن عشان العميل يعرف يوصل.",
    manageLocations: "إدارة المخازن",
    errNoPlace: "شغّل الاستلام في مكان واحد على الأقل.",
    noLocationsTitle: "لسه مفيش أماكن",
    noLocationsBody: "ضيف مخزن أو فرع من المخزون ← المخازن، وبعدين شغّل الاستلام منه.",
    locationsDenied: "صلاحياتك مش بتقرا أماكن المتجر، فمش هينفع تغيّر أماكن الاستلام من هنا.",
    save: "حفظ",
    saving: "بنحفظ…",
    discard: "تجاهل",
    saved: "اتحفظ. العميل هيشوف التغيير في صفحة الدفع على طول.",
    noManage: "تغيير الاستلام من الفرع محتاج صلاحية الشحن. اطلبها من صاحب المتجر.",
    openQueue: "أوردرات الاستلام",
    queueTitle: "أوردرات الاستلام",
    queueDescription: "الأوردرات اللي العميل هيستلمها من الفرع. جهّز الأوردر، وبعدين سلّمه بالكود اللي مع العميل.",
    backToOrders: "الأوردرات",
    settingsLink: "إعدادات الاستلام",
    filterLabel: "فلتر أوردرات الاستلام بالحالة",
    tabPending: "بتتجهّز",
    tabPendingCount: "بتتجهّز ({count})",
    tabReady: "جاهزة للاستلام",
    tabReadyCount: "جاهزة للاستلام ({count})",
    tabCollected: "اتسلّمت",
    tabCancelled: "اتلغت",
    tabAll: "الكل",
    statusPending: "بيتجهّز",
    statusReady: "جاهز للاستلام",
    statusCollected: "اتسلّم",
    statusCancelled: "اتلغى",
    placeFilter: "المكان",
    allPlaces: "كل الأماكن",
    colOrder: "الأوردر",
    colPlace: "المكان",
    colPlaced: "اتطلب",
    colTotal: "الإجمالي",
    colStatus: "الحالة",
    markReady: "جاهز",
    marking: "ثانية واحدة…",
    handOver: "تسليم",
    readyDone: "الأوردر {number} جاهز، واتبعت للعميل إيميل بالمكان والكود.",
    readyDoneNoEmail: "الأوردر {number} جاهز. مفيهوش إيميل: بلّغ العميل بنفسك.",
    handOverTitle: "تسليم الأوردر {number}",
    handOverBody: "اكتب الكود اللي مع العميل ({n} أرقام).",
    codeLabel: "كود الاستلام",
    codeWrong: "الكود غلط",
    codeIncomplete: "الكود {n} أرقام.",
    confirmHandOver: "أكّد التسليم",
    handingOver: "بنسلّم…",
    cancel: "إلغاء",
    handedOver: "الأوردر {number} اتسلّم للعميل.",
    stale: "الأوردر ده حالته اتغيّرت في الوقت ده. حدّثنا القايمة.",
    noOrderManage: "تجهيز وتسليم أوردرات الاستلام محتاج صلاحية إدارة الأوردرات. اطلبها من صاحب المتجر.",
    readySince: "جاهز من {time}",
    collectedOn: "اتسلّم {time}",
    payOnPickup: "هيدفع عند الاستلام",
    paid: "مدفوع",
    customer: "العميل",
    total: "الإجمالي",
    emptyPendingTitle: "مفيش أوردرات محتاجة تجهيز",
    emptyPendingBody: "الأوردرات اللي العميل يختار يستلمها من الفرع هتظهر هنا.",
    emptyReadyTitle: "مفيش أوردرات مستنية عميلها",
    emptyReadyBody: "الأوردر اللي تعلّم عليه «جاهز» بيفضل هنا لحد ما يتسلّم.",
    emptyOtherTitle: "مفيش أوردرات استلام هنا",
    showAll: "اعرض كل أوردرات الاستلام",
    offTitle: "الاستلام من الفرع مقفول",
    offBody: "شغّله من الشحن ← الاستلام من الفرع، والعميل هيختار في صفحة الدفع بين التوصيل والاستلام من الفرع.",
    offAction: "ظبّط الاستلام من الفرع",
    loadFailed: "معرفناش نحمّل باقي أوردرات الاستلام.",
    searchLabel: "دوّر في أوردرات الاستلام",
    searchPlaceholder: "رقم الأوردر، العميل أو الموبايل",
    searchLoaded: "البحث في اللي اتحمّل لحد دلوقتي. حمّل كمان عشان تدوّر في الباقي.",
    listLabel: "أوردرات الاستلام",
    colCustomer: "العميل",
    colAge: "اتطلب",
    colAction: "الخطوة الجاية",
    noName: "عميل من غير اسم",
    peek: "معاينة استلام {who}",
    openOrder: "افتح الأوردر {number}",
    openOrderFull: "افتح الأوردر",
    menuLabel: "إجراءات الأوردر {number}",
    menuOpen: "افتح الأوردر",
    menuCall: "اتصل",
    menuWhatsapp: "واتساب",
    menuCopyPhone: "انسخ الرقم",
    menuCopyOrder: "انسخ رقم الأوردر",
    copiedPhone: "رقم العميل اتنسخ",
    copiedOrder: "رقم الأوردر اتنسخ",
    placedWhen: "اتطلب {when}",
    pickupPlace: "مكان الاستلام",
    phoneHidden: "الرقم مخفي لصلاحيتك",
    noPhone: "من غير رقم موبايل",
    hintPending: "جهّز الأوردر وبعدين علّم عليه «جاهز»: العميل هيوصله إيميل بالمكان والكود.",
    hintReady: "العميل هيوريك كود الاستلام. اكتبه عشان تسلّمه الأوردر.",
    emptySearchTitle: "مفيش أوردر استلام بالبحث ده",
    clearSearch: "امسح البحث",
    refresh: "تحديث",
    blockTitle: "استلام من الفرع",
    blockHint: "العميل هيستلم الأوردر بنفسه: مفيش عنوان توصيل ولا شحن.",
    blockPlace: "المكان",
  },
} satisfies Messages;

export type PickupStrings = Record<keyof (typeof PICKUP_STRINGS)["en"], string>;

type Tone = "neutral" | "info" | "success" | "warning" | "danger";

export const PICKUP_STATUS_KEY = {
  pending: "statusPending",
  ready: "statusReady",
  collected: "statusCollected",
  cancelled: "statusCancelled",
} as const satisfies Record<PickupStatus, keyof PickupStrings>;

export const PICKUP_STATUS_TONE: Record<PickupStatus, Tone> = {
  pending: "warning",
  ready: "info",
  collected: "success",
  cancelled: "neutral",
};

/** A place's text in the screen's language, falling back to the other one. */
export function pickupTextOf(text: { ar?: string; en?: string } | null | undefined, locale: "ar" | "en"): string {
  if (!text) return "";
  const first = locale === "ar" ? text.ar : text.en;
  const second = locale === "ar" ? text.en : text.ar;
  return (first || second || "").trim();
}
