/**
 * The dashboard's copy of the storefront's own texts (apps/storefront/src/lib/
 * i18n.ts and i18nFr.ts), for the Store texts screen: each text's key, its
 * default wording per language and the placeholders it accepts. Only the
 * sections a merchant rewords are listed. Keep it in step with the storefront
 * dictionary when a text there is added or renamed; a key missing here is
 * still applied by the storefront, it just has no row on the screen.
 */

export interface StoreTextEntry {
  /** The dictionary path, e.g. "checkout.place". */
  key: string;
  en: string;
  ar: string;
  fr: string;
  /** Placeholders the storefront fills, e.g. ["n"] for "{n}". */
  vars?: string[];
}

export type StoreTextGroupId = "common" | "product" | "form" | "bump" | "cart" | "checkout" | "upsell" | "thankYou" | "track" | "footer";

export interface StoreTextGroup {
  id: StoreTextGroupId;
  entries: StoreTextEntry[];
}

export const STORE_TEXT_GROUPS: StoreTextGroup[] = [
  {
    id: "common",
    entries: [
      { key: "common.loading", en: "Loading…", ar: "جارٍ التحميل…", fr: "Chargement…" },
      { key: "common.backToStore", en: "Back to store", ar: "العودة للمتجر", fr: "Retour à la boutique" },
      { key: "common.continueShopping", en: "Continue shopping", ar: "متابعة التسوق", fr: "Continuer mes achats" },
      { key: "common.required", en: "required", ar: "مطلوب", fr: "obligatoire" },
      { key: "common.optional", en: "optional", ar: "اختياري", fr: "facultatif" },
      { key: "common.close", en: "Close", ar: "إغلاق", fr: "Fermer" },
      { key: "common.backToTop", en: "Back to top", ar: "ارجع لفوق", fr: "Retour en haut" },
      { key: "common.home", en: "Home", ar: "الرئيسية", fr: "Accueil" },
      { key: "common.cart", en: "Cart", ar: "السلة", fr: "Panier" },
      { key: "common.trackOrder", en: "Track order", ar: "تتبع الطلب", fr: "Suivre ma commande" },
      { key: "common.language", en: "Language", ar: "اللغة", fr: "Langue" },
      { key: "common.switchToArabic", en: "Switch to Arabic", ar: "التبديل للعربية", fr: "Passer en arabe" },
      { key: "common.switchToEnglish", en: "Switch to English", ar: "التبديل للإنجليزية", fr: "Passer en anglais" },
      { key: "common.switchToFrench", en: "Switch to French", ar: "التبديل للفرنسية", fr: "Passer en français" },
      { key: "common.themeLight", en: "Switch to light mode", ar: "الوضع الفاتح", fr: "Passer en mode clair" },
      { key: "common.themeDark", en: "Switch to dark mode", ar: "الوضع الداكن", fr: "Passer en mode sombre" },
      { key: "common.cartWithCount", en: "Cart — {n} items", ar: "السلة — {n} منتج", fr: "Panier — {n} articles", vars: ["n"] },
      { key: "common.menu", en: "Menu", ar: "القائمة", fr: "Menu" },
      { key: "common.save", en: "Save {pct}%", ar: "وفّر {pct}٪", fr: "−{pct} %", vars: ["pct"] },
      { key: "common.outOfStock", en: "Out of stock", ar: "نفدت الكمية", fr: "Rupture de stock" },
      { key: "common.unavailable", en: "Unavailable", ar: "غير متاح", fr: "Indisponible" },
      { key: "common.inStock", en: "In stock", ar: "متوفر", fr: "En stock" },
      { key: "common.piece", en: "{n} pieces", ar: "{n} قطع", fr: "{n} pièces", vars: ["n"] },
    ],
  },
  {
    id: "product",
    entries: [
      { key: "product.orderNow", en: "Order now", ar: "اطلب الآن", fr: "Commander" },
      { key: "product.addToCart", en: "Add to cart", ar: "أضف للسلة", fr: "Ajouter au panier" },
      { key: "product.adding", en: "Adding…", ar: "جارٍ الإضافة…", fr: "Ajout…" },
      { key: "product.added", en: "Added to cart", ar: "تمت الإضافة للسلة", fr: "Ajouté au panier" },
      { key: "product.addFailed", en: "Couldn't add the product to your cart.", ar: "تعذّر إضافة المنتج للسلة.", fr: "Impossible d'ajouter le produit à votre panier." },
      { key: "product.unavailable", en: "Currently unavailable", ar: "غير متوفر حاليًا", fr: "Actuellement indisponible" },
      { key: "product.quantity", en: "Quantity", ar: "الكمية", fr: "Quantité" },
      { key: "product.decrease", en: "Decrease quantity", ar: "إنقاص الكمية", fr: "Diminuer la quantité" },
      { key: "product.increase", en: "Increase quantity", ar: "زيادة الكمية", fr: "Augmenter la quantité" },
      { key: "product.chooseOffer", en: "Choose your offer", ar: "اختر العرض المناسب", fr: "Choisissez votre offre" },
      { key: "product.bestValue", en: "Best value", ar: "أفضل قيمة", fr: "Meilleure affaire" },
      { key: "product.popular", en: "Most popular", ar: "الأكثر طلبًا", fr: "La plus choisie" },
      { key: "product.youSave", en: "You save {amount}", ar: "هتوفّر {amount}", fr: "Vous économisez {amount}", vars: ["amount"] },
      { key: "product.description", en: "Product details", ar: "تفاصيل المنتج", fr: "Détails du produit" },
      { key: "product.faq", en: "Frequently asked questions", ar: "الأسئلة الشائعة", fr: "Questions fréquentes" },
      { key: "product.offerEnds", en: "Offer ends in", ar: "العرض ينتهي خلال", fr: "L'offre se termine dans" },
      { key: "product.viewDetails", en: "View details", ar: "عرض التفاصيل", fr: "Voir les détails" },
      { key: "product.back", en: "Back to store", ar: "العودة للمتجر", fr: "Retour à la boutique" },
      { key: "product.compareAt", en: "Was", ar: "بدلًا من", fr: "Avant" },
      { key: "product.stickyOrder", en: "Order now — cash on delivery", ar: "اطلب الآن — الدفع عند الاستلام", fr: "Commander — paiement à la livraison" },
      { key: "product.gallery", en: "Product photos", ar: "صور المنتج", fr: "Photos du produit" },
      { key: "product.zoomImage", en: "Open the photo larger", ar: "افتح الصورة أكبر", fr: "Agrandir la photo" },
      { key: "product.previousImage", en: "Previous photo", ar: "الصورة السابقة", fr: "Photo précédente" },
      { key: "product.nextImage", en: "Next photo", ar: "الصورة التالية", fr: "Photo suivante" },
      { key: "product.closeImage", en: "Close the photo", ar: "اقفل الصورة", fr: "Fermer la photo" },
    ],
  },
  {
    id: "form",
    entries: [
      { key: "form.title", en: "Order now — pay on delivery", ar: "اطلب الآن — والدفع عند الاستلام", fr: "Commander — paiement à la livraison" },
      { key: "form.subtitle", en: "Fill in your details and we'll call you to confirm.", ar: "اكتب بياناتك وهنتصل بيك لتأكيد الطلب.", fr: "Remplissez vos informations et nous vous appellerons pour confirmer." },
      { key: "form.fullName", en: "Full name", ar: "الاسم بالكامل", fr: "Nom complet" },
      { key: "form.fullNamePlaceholder", en: "Your name", ar: "اسمك", fr: "Votre nom" },
      { key: "form.phone", en: "Mobile number", ar: "رقم الموبايل", fr: "Numéro de mobile" },
      { key: "form.phonePlaceholder", en: "01XXXXXXXXX", ar: "01XXXXXXXXX", fr: "06XXXXXXXX" },
      { key: "form.phoneHint", en: "Egyptian mobile — 11 digits starting with 010, 011, 012 or 015", ar: "رقم موبايل مصري ١١ رقم يبدأ بـ 010 أو 011 أو 012 أو 015", fr: "Un numéro de mobile valide, avec l'indicatif s'il est étranger" },
      { key: "form.altPhone", en: "Alternative number", ar: "رقم بديل", fr: "Autre numéro" },
      { key: "form.email", en: "Email", ar: "البريد الإلكتروني", fr: "E-mail" },
      { key: "form.governorate", en: "Governorate", ar: "المحافظة", fr: "Région" },
      { key: "form.chooseGovernorate", en: "Choose governorate", ar: "اختر المحافظة", fr: "Choisissez la région" },
      { key: "form.city", en: "City / area", ar: "المدينة / المنطقة", fr: "Ville / quartier" },
      { key: "form.address", en: "Detailed address", ar: "العنوان بالتفصيل", fr: "Adresse détaillée" },
      { key: "form.addressPlaceholder", en: "Street, building, floor, apartment", ar: "الشارع، رقم العمارة، الدور، الشقة", fr: "Rue, immeuble, étage, appartement" },
      { key: "form.postalCode", en: "Postal code", ar: "الرمز البريدي", fr: "Code postal" },
      { key: "form.country", en: "Country", ar: "الدولة", fr: "Pays" },
      { key: "form.nationalAddress", en: "National address (short code)", ar: "العنوان الوطني (الرمز المختصر)", fr: "Adresse nationale (code court)" },
      { key: "form.nationalAddressPlaceholder", en: "RRRD2929", ar: "RRRD2929", fr: "RRRD2929" },
      { key: "form.choose", en: "Choose", ar: "اختر", fr: "Choisir" },
      { key: "form.notes", en: "Notes", ar: "ملاحظات", fr: "Remarques" },
      { key: "form.notesPlaceholder", en: "Anything the courier should know", ar: "أي تفاصيل تساعد المندوب", fr: "Une information utile pour le livreur" },
      { key: "form.submit", en: "Confirm order", ar: "تأكيد الطلب", fr: "Confirmer la commande" },
      { key: "form.submitting", en: "Placing your order…", ar: "جارٍ تأكيد الطلب…", fr: "Envoi de votre commande…" },
      { key: "form.total", en: "Total", ar: "الإجمالي", fr: "Total" },
      { key: "form.errors.fullName", en: "Please enter your name.", ar: "من فضلك اكتب اسمك.", fr: "Veuillez saisir votre nom." },
      { key: "form.errors.phone", en: "Enter a valid Egyptian mobile number: 11 digits starting with 01.", ar: "اكتب رقم موبايل مصري صحيح: 11 رقم يبدأ بـ 01.", fr: "Saisissez un numéro de mobile valide." },
      { key: "form.errors.altPhone", en: "The alternative number isn't a valid Egyptian mobile.", ar: "الرقم البديل مش رقم موبايل مصري صحيح.", fr: "L'autre numéro n'est pas un numéro de mobile valide." },
      { key: "form.errors.governorate", en: "Please choose your governorate.", ar: "من فضلك اختر المحافظة.", fr: "Veuillez choisir votre région." },
      { key: "form.errors.city", en: "Please enter your city or area.", ar: "من فضلك اكتب المدينة أو المنطقة.", fr: "Veuillez saisir votre ville ou quartier." },
      { key: "form.errors.address", en: "Please enter your detailed address.", ar: "من فضلك اكتب العنوان بالتفصيل.", fr: "Veuillez saisir votre adresse détaillée." },
      { key: "form.errors.email", en: "That email address doesn't look right.", ar: "البريد الإلكتروني غير صحيح.", fr: "Cette adresse e-mail ne semble pas correcte." },
      { key: "form.errors.emailRequired", en: "Please enter your email address.", ar: "من فضلك اكتب بريدك الإلكتروني.", fr: "Veuillez saisir votre adresse e-mail." },
      { key: "form.errors.postalCode", en: "Please enter your postal code.", ar: "من فضلك اكتب الرمز البريدي.", fr: "Veuillez saisir votre code postal." },
      { key: "form.errors.country", en: "Please choose your country.", ar: "من فضلك اختر الدولة.", fr: "Veuillez choisir votre pays." },
      { key: "form.errors.required", en: "This field is required.", ar: "الحقل ده مطلوب.", fr: "Ce champ est obligatoire." },
      { key: "form.errors.phoneIntl", en: "Enter a valid mobile number with the country code.", ar: "اكتب رقم موبايل صحيح بكود الدولة.", fr: "Saisissez un numéro de mobile valide avec l'indicatif du pays." },
      { key: "form.errors.notes", en: "Please shorten your note.", ar: "من فضلك اختصر الملاحظة شوية.", fr: "Veuillez raccourcir votre remarque." },
      { key: "form.errors.summary", en: "Please fix {n} fields below.", ar: "من فضلك صحّح {n} حقول.", fr: "Veuillez corriger {n} champs ci-dessous.", vars: ["n"] },
      { key: "form.errors.emptyCart", en: "Your cart is empty.", ar: "سلة التسوق فاضية.", fr: "Votre panier est vide." },
      { key: "form.errors.generic", en: "We couldn't place your order. Please try again.", ar: "تعذّر إتمام الطلب، حاول تاني.", fr: "Impossible d'enregistrer votre commande. Veuillez réessayer." },
      { key: "form.errors.rejected", en: "Sorry, we couldn't place this order online. Please contact the store and we'll gladly help you complete it.", ar: "عذرًا، مش قادرين نكمّل الطلب ده أونلاين. تواصل مع المتجر وهيساعدوك تكمّله بكل سرور.", fr: "Désolé, nous ne pouvons pas enregistrer cette commande en ligne. Contactez la boutique, nous vous aiderons volontiers à la finaliser." },
      { key: "form.errors.customFields", en: "A product in your cart is missing a detail, or its photo expired. Remove it and add it again from its page.", ar: "منتج في السلة ناقصه بيانات أو صورته انتهت صلاحيتها. شيله وضيفه تاني من صفحته.", fr: "Un produit de votre panier a une information manquante ou sa photo a expiré. Retirez-le puis ajoutez-le à nouveau depuis sa page." },
      { key: "form.errors.bumpUnavailable", en: "The add-on you ticked is no longer available, so we took it off. Place the order again without it.", ar: "الإضافة اللي اخترتها مبقتش متاحة، فشلناها من الطلب. أكّد الطلب تاني من غيرها.", fr: "Le complément coché n'est plus disponible, nous l'avons retiré. Passez à nouveau la commande sans lui." },
      { key: "form.errors.unavailable", en: "This product is unavailable right now.", ar: "المنتج غير متوفر حاليًا.", fr: "Ce produit est indisponible pour le moment." },
    ],
  },
  {
    id: "bump",
    entries: [
      { key: "bump.title", en: "Add to your order", ar: "أضف لطلبك", fr: "Ajouter à votre commande" },
      { key: "bump.yes", en: "Yes, add it", ar: "أيوه، ضيفه", fr: "Oui, l'ajouter" },
      { key: "bump.only", en: "Only {price}", ar: "بـ {price} بس", fr: "Seulement {price}", vars: ["price"] },
      { key: "bump.giftName", en: "Premium gift wrapping", ar: "تغليف هدية مميز", fr: "Emballage cadeau premium" },
      { key: "bump.giftDescription", en: "Gift-ready packaging with a handwritten card.", ar: "تغليف جاهز للإهداء مع كارت مكتوب بخط اليد.", fr: "Un emballage prêt à offrir avec une carte manuscrite." },
      { key: "bump.addedNote", en: "Order bump requested: {name}", ar: "طلب إضافة: {name}", fr: "Complément demandé : {name}", vars: ["name"] },
    ],
  },
  {
    id: "cart",
    entries: [
      { key: "cart.title", en: "Your cart", ar: "سلة التسوق", fr: "Votre panier" },
      { key: "cart.empty", en: "Your cart is empty.", ar: "سلة التسوق فاضية.", fr: "Votre panier est vide." },
      { key: "cart.emptyHint", en: "Browse the store and add something you love.", ar: "تصفّح المتجر وضيف اللي يعجبك.", fr: "Parcourez la boutique et ajoutez ce qui vous plaît." },
      { key: "cart.loading", en: "Loading your cart…", ar: "جارٍ تحميل السلة…", fr: "Chargement de votre panier…" },
      { key: "cart.remove", en: "Remove", ar: "حذف", fr: "Retirer" },
      { key: "cart.removeFailed", en: "Couldn't remove the item.", ar: "تعذّر حذف المنتج.", fr: "Impossible de retirer l'article." },
      { key: "cart.updateFailed", en: "Couldn't update the quantity.", ar: "تعذّر تحديث الكمية.", fr: "Impossible de modifier la quantité." },
      { key: "cart.perUnit", en: "{price} each", ar: "{price} للقطعة", fr: "{price} l'unité", vars: ["price"] },
      { key: "cart.priceChanged", en: "Price changed since you added it", ar: "السعر اتغيّر من وقت ما أضفته", fr: "Le prix a changé depuis votre ajout" },
      { key: "cart.subtotal", en: "Subtotal", ar: "الإجمالي المبدئي", fr: "Sous-total" },
      { key: "cart.checkout", en: "Checkout", ar: "إتمام الطلب", fr: "Commander" },
      { key: "cart.item", en: "Product", ar: "منتج", fr: "Produit" },
      { key: "cart.summary", en: "Order summary", ar: "ملخص الطلب", fr: "Récapitulatif" },
      { key: "cart.shippingAtCheckout", en: "Calculated at checkout", ar: "يُحسب عند إتمام الطلب", fr: "Calculée à la commande" },
      { key: "cart.shipTo", en: "Ship to", ar: "الشحن لـ", fr: "Livrer à" },
      { key: "cart.shipToPlaceholder", en: "Choose your governorate", ar: "اختار المحافظة", fr: "Choisissez votre région" },
    ],
  },
  {
    id: "checkout",
    entries: [
      { key: "checkout.title", en: "Checkout", ar: "إتمام الطلب", fr: "Commande" },
      { key: "checkout.backToCart", en: "Back to cart", ar: "الرجوع للسلة", fr: "Retour au panier" },
      { key: "checkout.contact", en: "Contact details", ar: "بيانات التواصل", fr: "Coordonnées" },
      { key: "checkout.shipping", en: "Shipping address", ar: "عنوان الشحن", fr: "Adresse de livraison" },
      { key: "checkout.payment", en: "Payment method", ar: "طريقة الدفع", fr: "Mode de paiement" },
      { key: "checkout.cod", en: "Cash on delivery", ar: "الدفع عند الاستلام", fr: "Paiement à la livraison" },
      { key: "checkout.codHint", en: "Pay the courier in cash when your order arrives.", ar: "ادفع كاش للمندوب لما طلبك يوصل.", fr: "Payez le livreur en espèces à la réception." },
      { key: "checkout.summary", en: "Order summary", ar: "ملخص الطلب", fr: "Récapitulatif" },
      { key: "checkout.subtotal", en: "Subtotal", ar: "الإجمالي المبدئي", fr: "Sous-total" },
      { key: "checkout.shippingFee", en: "Shipping", ar: "الشحن", fr: "Livraison" },
      { key: "checkout.shippingOnConfirmation", en: "Confirmed when we call you", ar: "بيتأكد وقت مكالمة التأكيد", fr: "Confirmée lors de notre appel" },
      { key: "checkout.shippingPickGovernorate", en: "Calculated after you choose your area", ar: "بيتحسب بعد ما تختار منطقتك", fr: "Calculée après le choix de votre région" },
      { key: "checkout.shippingCalculating", en: "Calculating…", ar: "جارٍ الحساب…", fr: "Calcul…" },
      { key: "checkout.shippingFree", en: "Free", ar: "مجانًا", fr: "Gratuite" },
      { key: "checkout.freeShippingHint", en: "Add {amount} more for free shipping", ar: "ضيف {amount} كمان والشحن يبقى مجاني", fr: "Encore {amount} pour la livraison gratuite", vars: ["amount"] },
      { key: "checkout.freeShippingReached", en: "Your order ships free", ar: "طلبك شحنه مجاني", fr: "Votre commande est livrée gratuitement" },
      { key: "checkout.discount", en: "Discount", ar: "الخصم", fr: "Remise" },
      { key: "checkout.discountCode", en: "Discount code", ar: "كود الخصم", fr: "Code promo" },
      { key: "checkout.apply", en: "Apply", ar: "تطبيق", fr: "Appliquer" },
      { key: "checkout.discountPending", en: "Code «{code}» will be applied when your order is confirmed.", ar: "هيتم تطبيق الكود «{code}» عند تأكيد الطلب.", fr: "Le code « {code} » sera appliqué à la confirmation de votre commande.", vars: ["code"] },
      { key: "checkout.removeCode", en: "Remove code", ar: "إزالة الكود", fr: "Retirer le code" },
      { key: "checkout.bundleSaving", en: "Bundle saving", ar: "توفير العرض", fr: "Économie du lot" },
      { key: "checkout.total", en: "Total", ar: "الإجمالي", fr: "Total" },
      { key: "checkout.totalEstimate", en: "Estimated total", ar: "الإجمالي التقديري", fr: "Total estimé" },
      { key: "checkout.place", en: "Place order", ar: "تأكيد الطلب", fr: "Passer la commande" },
      { key: "checkout.placing", en: "Placing your order…", ar: "جارٍ تأكيد الطلب…", fr: "Envoi de votre commande…" },
      { key: "checkout.finalNote", en: "Final amounts are confirmed on the confirmation call.", ar: "المبالغ النهائية بتتأكد في مكالمة التأكيد.", fr: "Les montants définitifs sont confirmés lors de l'appel de confirmation." },
    ],
  },
  {
    id: "upsell",
    entries: [
      { key: "upsell.save", en: "You save {amount}", ar: "هتوفّر {amount}", fr: "Vous économisez {amount}", vars: ["amount"] },
      { key: "funnel.offerBadge", en: "One-time offer", ar: "عرض لمرة واحدة", fr: "Offre unique" },
      { key: "funnel.offerHint", en: "It's added as a second order linked to yours — pay on delivery.", ar: "هيتسجّل كطلب تاني مرتبط بطلبك — والدفع عند الاستلام.", fr: "Elle est ajoutée comme une deuxième commande liée à la vôtre — paiement à la livraison." },
      { key: "funnel.offerJoinsHint", en: "It's added to your order — one delivery, pay on delivery.", ar: "هيتضاف لطلبك نفسه — شحنة واحدة والدفع عند الاستلام.", fr: "Elle est ajoutée à votre commande — une seule livraison, paiement à la livraison." },
      { key: "funnel.accept", en: "Yes, add it", ar: "أيوه، ضيفه", fr: "Oui, l'ajouter" },
      { key: "funnel.accepting", en: "Adding it…", ar: "بنضيفه…", fr: "Ajout…" },
      { key: "funnel.decline", en: "No thanks", ar: "لا شكرًا", fr: "Non merci" },
      { key: "funnel.offerGone", en: "This offer is no longer available.", ar: "العرض ده مبقاش متاح.", fr: "Cette offre n'est plus disponible." },
      { key: "funnel.offerOutOfStock", en: "Sorry, this offer just sold out.", ar: "للأسف العرض ده خلص حالًا.", fr: "Désolé, cette offre vient d'être épuisée." },
      { key: "funnel.offerNeedsOrder", en: "This offer needs an order first — please complete your order.", ar: "العرض ده محتاج طلب الأول — كمّل طلبك الأول.", fr: "Cette offre nécessite d'abord une commande — veuillez finaliser votre commande." },
    ],
  },
  {
    id: "thankYou",
    entries: [
      { key: "thankYou.title", en: "Thank you! Your order is placed", ar: "شكرًا! طلبك اتسجل", fr: "Merci ! Votre commande est passée" },
      { key: "thankYou.orderNumber", en: "Order number", ar: "رقم الطلب", fr: "Numéro de commande" },
      { key: "thankYou.received", en: "We received your order.", ar: "استلمنا طلبك.", fr: "Nous avons bien reçu votre commande." },
      { key: "thankYou.callNotice", en: "We'll call or WhatsApp you to confirm your order before shipping.", ar: "هنتصل بيك أو نكلمك واتساب لتأكيد الطلب قبل الشحن.", fr: "Nous vous appellerons ou vous écrirons sur WhatsApp pour confirmer avant l'expédition." },
      { key: "thankYou.onPhone", en: "on", ar: "على الرقم", fr: "au" },
      { key: "thankYou.summary", en: "Order summary", ar: "ملخص الطلب", fr: "Récapitulatif" },
      { key: "thankYou.subtotal", en: "Subtotal", ar: "الإجمالي المبدئي", fr: "Sous-total" },
      { key: "thankYou.shipping", en: "Shipping", ar: "الشحن", fr: "Livraison" },
      { key: "thankYou.discount", en: "Discount", ar: "الخصم", fr: "Remise" },
      { key: "thankYou.total", en: "Total", ar: "الإجمالي", fr: "Total" },
      { key: "thankYou.payOnDelivery", en: "Pay on delivery", ar: "الدفع عند الاستلام", fr: "À payer à la livraison" },
      { key: "thankYou.whatsapp", en: "Chat with us on WhatsApp", ar: "كلمنا واتساب", fr: "Discuter avec nous sur WhatsApp" },
      { key: "thankYou.whatsappMessage", en: "Hello {store}, I just placed order {number}.", ar: "أهلًا {store}، لسه عامل طلب رقم {number}.", fr: "Bonjour {store}, je viens de passer la commande n° {number}.", vars: ["store", "number"] },
      { key: "thankYou.share", en: "Share the store", ar: "شارك المتجر", fr: "Partager la boutique" },
      { key: "thankYou.shareWhatsapp", en: "Share on WhatsApp", ar: "شارك على واتساب", fr: "Partager sur WhatsApp" },
      { key: "thankYou.copyLink", en: "Copy link", ar: "نسخ الرابط", fr: "Copier le lien" },
      { key: "thankYou.copied", en: "Link copied", ar: "تم نسخ الرابط", fr: "Lien copié" },
      { key: "thankYou.shareNative", en: "Share", ar: "مشاركة", fr: "Partager" },
      { key: "thankYou.shareText", en: "I just ordered from {store}!", ar: "لسه طالب من {store}!", fr: "Je viens de commander chez {store} !", vars: ["store"] },
      { key: "thankYou.track", en: "Track your order", ar: "تتبع طلبك", fr: "Suivre votre commande" },
      { key: "thankYou.moreProducts", en: "You may also like", ar: "ممكن يعجبك كمان", fr: "Vous aimerez aussi" },
      { key: "thankYou.backToStore", en: "Back to store", ar: "العودة للمتجر", fr: "Retour à la boutique" },
      { key: "thankYou.steps", en: "What happens next", ar: "الخطوات الجاية", fr: "La suite" },
      { key: "timeline.placed", en: "Order placed", ar: "تم الطلب", fr: "Commande passée" },
      { key: "timeline.placedHint", en: "We received your order.", ar: "استلمنا طلبك.", fr: "Nous avons reçu votre commande." },
      { key: "timeline.confirmation", en: "Confirmation", ar: "التأكيد", fr: "Confirmation" },
      { key: "timeline.confirmationHint", en: "We call or WhatsApp you to confirm.", ar: "هنكلمك تليفون أو واتساب للتأكيد.", fr: "Nous vous appelons ou vous écrivons sur WhatsApp pour confirmer." },
      { key: "timeline.shipped", en: "Shipped", ar: "تم الشحن", fr: "Expédiée" },
      { key: "timeline.shippedHint", en: "Your order is on the way.", ar: "طلبك في الطريق.", fr: "Votre commande est en route." },
      { key: "timeline.delivered", en: "Delivered", ar: "تم التوصيل", fr: "Livrée" },
      { key: "timeline.deliveredHint", en: "Pay the courier on delivery.", ar: "ادفع للمندوب عند الاستلام.", fr: "Payez le livreur à la réception." },
      { key: "timeline.current", en: "Current step", ar: "الخطوة الحالية", fr: "Étape en cours" },
      { key: "timeline.done", en: "Completed", ar: "مكتملة", fr: "Terminée" },
    ],
  },
  {
    id: "track",
    entries: [
      { key: "track.title", en: "Track your order", ar: "تتبع طلبك", fr: "Suivre votre commande" },
      { key: "track.subtitle", en: "Enter the mobile number and order number you used.", ar: "اكتب رقم الموبايل ورقم الطلب اللي استخدمتهم.", fr: "Saisissez le numéro de mobile et le numéro de commande utilisés." },
      { key: "track.orderNumber", en: "Order number", ar: "رقم الطلب", fr: "Numéro de commande" },
      { key: "track.orderNumberPlaceholder", en: "e.g. 1024", ar: "مثال: 1024", fr: "ex. 1024" },
      { key: "track.submit", en: "Track order", ar: "تتبع الطلب", fr: "Suivre la commande" },
      { key: "track.searching", en: "Looking up your order…", ar: "جارٍ البحث عن طلبك…", fr: "Recherche de votre commande…" },
      { key: "track.notFound", en: "We couldn't find an order with these details. Check the number and try again.", ar: "مش لاقيين طلب بالبيانات دي. راجع الرقم وجرّب تاني.", fr: "Aucune commande trouvée avec ces informations. Vérifiez le numéro et réessayez." },
      { key: "track.status", en: "Order status", ar: "حالة الطلب", fr: "Statut de la commande" },
      { key: "track.lastUpdate", en: "Last update", ar: "آخر تحديث", fr: "Dernière mise à jour" },
      { key: "track.items", en: "Items", ar: "المنتجات", fr: "Articles" },
      { key: "track.subtotal", en: "Subtotal", ar: "الإجمالي المبدئي", fr: "Sous-total" },
      { key: "track.discount", en: "Discount", ar: "الخصم", fr: "Remise" },
      { key: "track.shipping", en: "Shipping", ar: "الشحن", fr: "Livraison" },
      { key: "track.total", en: "Total", ar: "الإجمالي", fr: "Total" },
      { key: "track.errors.orderNumber", en: "Please enter your order number.", ar: "من فضلك اكتب رقم الطلب.", fr: "Veuillez saisir votre numéro de commande." },
      { key: "track.errors.invalid", en: "Check your mobile number and order number, then try again.", ar: "راجع رقم الموبايل ورقم الطلب وجرّب تاني.", fr: "Vérifiez votre numéro de mobile et votre numéro de commande, puis réessayez." },
      { key: "track.errors.rateLimited", en: "Too many attempts. Please try again in a few minutes.", ar: "حاولت مرات كتير. جرّب تاني بعد شوية.", fr: "Trop de tentatives. Veuillez réessayer dans quelques minutes." },
      { key: "track.errors.rateLimitedIn", en: "Too many attempts. Please try again in {minutes} minutes.", ar: "حاولت مرات كتير. جرّب تاني بعد {minutes} دقيقة.", fr: "Trop de tentatives. Veuillez réessayer dans {minutes} minutes.", vars: ["minutes"] },
      { key: "track.errors.failed", en: "Something went wrong looking up your order. Please try again.", ar: "حصلت مشكلة وإحنا بندور على طلبك. جرّب تاني.", fr: "Une erreur s'est produite lors de la recherche de votre commande. Veuillez réessayer." },
    ],
  },
  {
    id: "footer",
    entries: [
      { key: "footer.links", en: "Store", ar: "المتجر", fr: "Boutique" },
      { key: "footer.pages", en: "Pages", ar: "صفحات", fr: "Pages" },
      { key: "footer.help", en: "Help", ar: "المساعدة", fr: "Aide" },
      { key: "footer.poweredBy", en: "Powered by", ar: "مدعوم من", fr: "Propulsé par" },
      { key: "footer.rights", en: "© {year} {store}. All rights reserved.", ar: "© {year} {store}. جميع الحقوق محفوظة.", fr: "© {year} {store}. Tous droits réservés.", vars: ["store", "year"] },
    ],
  },
];
