import type { SpecKeyName } from "@store-builder/api-client";
import { getLocale, type Messages } from "@/i18n/LocaleContext";

/** Product specifications: the store's list of specifications and a product's values. */
export const SPEC_STRINGS = {
  en: {
    back: "Products",
    title: "Specifications",
    description: "The facts shoppers compare products by — screen size, memory, material. Define them once here, then fill them in on each product.",
    add: "Add specification",
    emptyTitle: "No specifications yet",
    emptyHint: "Add the first one, for example “Material” or “Screen size”. It then appears on every product's page here, ready to fill in.",
    colName: "Specification",
    colUnit: "Unit",
    colFilter: "Store filter",
    colOrder: "Order",
    colActions: "Actions",
    filterOn: "Shoppers can filter by it",
    filterOff: "Not a filter",
    noUnit: "—",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    edit: "Edit",
    editNamed: "Edit {name}",
    rowMenu: "Actions for {name}",
    menuUp: "Move up",
    menuDown: "Move down",
    remove: "Delete",
    limit: "A store has at most {max} specifications.",
    countOf: "{count} of {max}",
    viewOnly: "You can see the specifications, but changing them needs permission to manage products.",
    // dialog
    addTitle: "New specification",
    editTitle: "Edit specification",
    nameAr: "Name in Arabic",
    nameEn: "Name in English",
    nameHint: "Fill in at least one. Shoppers see the one in their language.",
    unit: "Unit",
    unitHint: "Optional — shown after the value: GB, cm, kg.",
    unitPlaceholder: "GB",
    filterable: "Use as a store filter",
    filterableHint: "Shoppers can narrow products by this specification's values.",
    nameRequired: "Write the name in at least one language.",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    addedToast: "Specification added.",
    savedToast: "Specification saved.",
    deleteTitle: "Delete “{name}”?",
    deleteBody: "Its values are removed from every product. This can't be undone.",
    deleting: "Deleting…",
    deletedToast: "Specification deleted.",
    moveFailed: "The order wasn't saved — try again.",
    // the product page's section
    productTitle: "Specifications",
    productHint: "This product's value for each specification. Leave one empty and it isn't shown.",
    manage: "Manage specifications",
    valuePlaceholder: "No value",
    saveValues: "Save specifications",
    valuesSaved: "Specifications saved.",
    unknownKey: "A specification was deleted meanwhile. The list was read again.",
  },
  ar: {
    back: "المنتجات",
    title: "المواصفات",
    description: "الخصائص التي يقارن بها العميل المنتجات — مقاس الشاشة، الذاكرة، الخامة. عرّفها هنا مرة واحدة، ثم املأها في كل منتج.",
    add: "إضافة مواصفة",
    emptyTitle: "لا توجد مواصفات بعد",
    emptyHint: "أضف أول مواصفة، مثل «الخامة» أو «مقاس الشاشة». ستظهر بعدها في صفحة كل منتج هنا لتملأها.",
    colName: "المواصفة",
    colUnit: "الوحدة",
    colFilter: "فلتر في المتجر",
    colOrder: "الترتيب",
    colActions: "إجراءات",
    filterOn: "يستطيع العميل التصفية بها",
    filterOff: "ليست فلترًا",
    noUnit: "—",
    moveUp: "نقل {name} إلى الأعلى",
    moveDown: "نقل {name} إلى الأسفل",
    edit: "تعديل",
    editNamed: "تعديل {name}",
    rowMenu: "إجراءات {name}",
    menuUp: "نقل إلى الأعلى",
    menuDown: "نقل إلى الأسفل",
    remove: "حذف",
    limit: "يتسع المتجر لـ {max} مواصفة على الأكثر.",
    countOf: "{count} من {max}",
    viewOnly: "يمكنك عرض المواصفات، لكن تغييرها يحتاج إلى صلاحية إدارة المنتجات.",
    addTitle: "مواصفة جديدة",
    editTitle: "تعديل المواصفة",
    nameAr: "الاسم بالعربية",
    nameEn: "الاسم بالإنجليزية",
    nameHint: "اكتب أحدهما على الأقل. يرى العميل الاسم بلغته.",
    unit: "الوحدة",
    unitHint: "اختياري — تظهر بعد القيمة: جيجا، سم، كجم.",
    unitPlaceholder: "جيجا",
    filterable: "فلتر في المتجر",
    filterableHint: "يستطيع العميل تصفية المنتجات بقيم هذه المواصفة.",
    nameRequired: "اكتب الاسم بلغة واحدة على الأقل.",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    addedToast: "تمت إضافة المواصفة.",
    savedToast: "تم حفظ المواصفة.",
    deleteTitle: "هل تريد حذف «{name}»؟",
    deleteBody: "ستُزال قيمها من كل المنتجات. لا يمكن التراجع عن الحذف.",
    deleting: "جارٍ الحذف…",
    deletedToast: "تم حذف المواصفة.",
    moveFailed: "لم يُحفظ الترتيب — حاول مرة أخرى.",
    productTitle: "المواصفات",
    productHint: "قيمة هذا المنتج في كل مواصفة. ما تتركه فارغًا لا يظهر.",
    manage: "إدارة المواصفات",
    valuePlaceholder: "بدون قيمة",
    saveValues: "حفظ المواصفات",
    valuesSaved: "تم حفظ المواصفات.",
    unknownKey: "حُذفت مواصفة في هذه الأثناء. أُعيد تحميل القائمة.",
  },
} satisfies Messages;

/** A specification's name in the dashboard's language, else in the other one. */
export function specKeyName(name: SpecKeyName | null | undefined): string {
  const ar = name?.ar?.trim() ?? "";
  const en = name?.en?.trim() ?? "";
  return getLocale() === "ar" ? ar || en : en || ar;
}
