import type { SpecKeyName } from "@store-builder/api-client";
import { getLocale, type Messages } from "@/i18n/LocaleContext";

/** Product specifications (handoff 231): the store's list of specifications and a product's values. */
export const SPEC_STRINGS = {
  en: {
    back: "Products",
    title: "Specifications",
    description: "The facts shoppers compare products by — screen size, memory, material. Define them once here, then fill them in on each product.",
    add: "Add specification",
    emptyTitle: "No specifications yet",
    emptyHint: "Add the first one, for example “Material” or “Screen size”. It then appears on every product's page here, ready to fill in.",
    colName: "Specification",
    colUnit: "Unit",
    colFilter: "Store filter",
    colOrder: "Order",
    colActions: "Actions",
    filterOn: "Shoppers can filter by it",
    filterOff: "Not a filter",
    noUnit: "—",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    edit: "Edit",
    editNamed: "Edit {name}",
    rowMenu: "Actions for {name}",
    menuUp: "Move up",
    menuDown: "Move down",
    remove: "Delete",
    limit: "A store has at most {max} specifications.",
    countOf: "{count} of {max}",
    viewOnly: "You can see the specifications, but changing them needs permission to manage products.",
    // dialog
    addTitle: "New specification",
    editTitle: "Edit specification",
    nameAr: "Name in Arabic",
    nameEn: "Name in English",
    nameHint: "Fill in at least one. Shoppers see the one in their language.",
    unit: "Unit",
    unitHint: "Optional — shown after the value: GB, cm, kg.",
    unitPlaceholder: "GB",
    filterable: "Use as a store filter",
    filterableHint: "Shoppers can narrow products by this specification's values.",
    nameRequired: "Write the name in at least one language.",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    addedToast: "Specification added.",
    savedToast: "Specification saved.",
    deleteTitle: "Delete “{name}”?",
    deleteBody: "Its values are removed from every product. This can't be undone.",
    deleting: "Deleting…",
    deletedToast: "Specification deleted.",
    moveFailed: "The order wasn't saved — try again.",
    // the product page's section
    productTitle: "Specifications",
    productHint: "This product's value for each specification. Leave one empty and it isn't shown.",
    manage: "Manage specifications",
    valuePlaceholder: "No value",
    saveValues: "Save specifications",
    valuesSaved: "Specifications saved.",
    unknownKey: "A specification was deleted meanwhile. The list was read again.",
  },
  ar: {
    back: "المنتجات",
    title: "المواصفات",
    description: "الحاجات اللي العميل بيقارن بيها المنتجات — مقاس الشاشة، الذاكرة، الخامة. عرّفها هنا مرة واحدة، وبعدين املاها في كل منتج.",
    add: "ضيف مواصفة",
    emptyTitle: "لسه مفيش مواصفات",
    emptyHint: "ضيف أول واحدة، زي «الخامة» أو «مقاس الشاشة». هتظهر بعدها في صفحة كل منتج هنا علشان تملاها.",
    colName: "المواصفة",
    colUnit: "الوحدة",
    colFilter: "فلتر في المتجر",
    colOrder: "الترتيب",
    colActions: "إجراءات",
    filterOn: "العميل يقدر يفلتر بيها",
    filterOff: "مش فلتر",
    noUnit: "—",
    moveUp: "طلّع {name} لفوق",
    moveDown: "نزّل {name} لتحت",
    edit: "عدّل",
    editNamed: "عدّل {name}",
    rowMenu: "إجراءات {name}",
    menuUp: "طلّعها لفوق",
    menuDown: "نزّلها لتحت",
    remove: "امسح",
    limit: "المتجر بياخد لحد {max} مواصفة.",
    countOf: "{count} من {max}",
    viewOnly: "تقدر تشوف المواصفات، لكن تغييرها محتاج صلاحية إدارة المنتجات.",
    addTitle: "مواصفة جديدة",
    editTitle: "تعديل المواصفة",
    nameAr: "الاسم بالعربي",
    nameEn: "الاسم بالإنجليزي",
    nameHint: "اكتب واحد على الأقل. العميل بيشوف الاسم بلغته.",
    unit: "الوحدة",
    unitHint: "اختياري — بتظهر بعد القيمة: جيجا، سم، كجم.",
    unitPlaceholder: "جيجا",
    filterable: "فلتر في المتجر",
    filterableHint: "العميل يقدر يصفّي المنتجات بقيم المواصفة دي.",
    nameRequired: "اكتب الاسم بلغة واحدة على الأقل.",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "بنحفظ…",
    addedToast: "المواصفة اتضافت.",
    savedToast: "المواصفة اتحفظت.",
    deleteTitle: "تمسح «{name}»؟",
    deleteBody: "قيمها هتتشال من كل المنتجات. مينفعش ترجع في المسح.",
    deleting: "بنمسح…",
    deletedToast: "المواصفة اتمسحت.",
    moveFailed: "الترتيب ما اتحفظش — جرّب تاني.",
    productTitle: "المواصفات",
    productHint: "قيمة المنتج ده في كل مواصفة. اللي تسيبها فاضية مش بتظهر.",
    manage: "إدارة المواصفات",
    valuePlaceholder: "من غير قيمة",
    saveValues: "احفظ المواصفات",
    valuesSaved: "المواصفات اتحفظت.",
    unknownKey: "مواصفة اتمسحت في الوقت ده. القايمة اتقرت من جديد.",
  },
} satisfies Messages;

/** A specification's name in the dashboard's language, else in the other one. */
export function specKeyName(name: SpecKeyName | null | undefined): string {
  const ar = name?.ar?.trim() ?? "";
  const en = name?.en?.trim() ?? "";
  return getLocale() === "ar" ? ar || en : en || ar;
}
