import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the new-funnel wizard: three questions — what you sell, which
 * offer, which template — then «ابني الفانل». Also the share-code dialog and
 * the "I have a code" screen. Egyptian Arabic, second person, short.
 */
export const WIZARD_STRINGS = {
  en: {
    // Frame
    progress: "Question {n} of {total}",
    back: "Back",
    next: "Next",
    cancel: "Cancel",
    build: "Build the funnel",
    building: "Building…",
    // 1. Product
    q1: "What do you sell?",
    q1Hint: "The funnel's pages follow this product. You can change it later, page by page.",
    searchProducts: "Search your products",
    searchProductsPlaceholder: "Product name",
    products: "Your products",
    picked: "Chosen",
    change: "Change",
    noPrice: "No price yet",
    noProductsTitle: "No products yet",
    noProductsBody: "A funnel sells one product. Add it first, then come back here.",
    addProduct: "Add a product first",
    withoutProduct: "Continue without a product",
    withoutProductHint: "The pages will show the store's newest product until you choose one.",
    noProductPicked: "No product chosen",
    noMatch: "No product with that name.",
    productsFailed: "Couldn't load your products.",
    retry: "Try again",
    moreProducts: "Showing the first {n}. Type a name to find the rest.",
    haveCode: "I have a funnel code",
    onlyLeads: "I'm not selling — I collect customer numbers",
    // 2. Offer
    q2: "Which offer?",
    q2Hint: "What the order form sells with, and whether the shopper sees one more offer after ordering.",
    orderForm: "The order form",
    orderFormOffer: "Sells with the product's main offer: {offer}",
    orderFormPrice: "Sells at the product's price: {price}",
    orderFormPlain: "Sells at the product's price, with no offer.",
    orderFormNoProduct: "Sells the product each page shows.",
    productOffers: "The product's offers",
    mainOffer: "Main",
    manageOffers: "Edit the product's offers",
    upsell: "Offer after the order (upsell)",
    upsellHint: "Right after the order is placed, one more offer the shopper accepts in one tap. It adds an offer step to the funnel.",
    upsellWhich: "What will you offer?",
    upsellLater: "I'll choose it in the editor",
    upsellLaterHint: "The funnel can't be published until the offer step has an offer.",
    fromThisProduct: "From this product",
    otherOffers: "Other offers in the store",
    noOffers: "The store has no active offers yet. Build the funnel now and choose the offer in the editor once you add one.",
    offersFailed: "Couldn't load the offers. You can still choose one in the editor.",
    offerOf: "{offer} — {product}",
    // 3. Template
    q3: "Which look?",
    q3Hint: "A ready funnel to start from. Everything in it can be changed after.",
    q3LeadsHint: "A form that collects names and numbers, then a thank-you page.",
    name: "Funnel name",
    nameRequired: "Give the funnel a name.",
    moreDetails: "Link and currency",
    link: "Link",
    linkHint: "Letters, numbers and hyphens. Leave it empty and one is made from the name.",
    linkInvalid: "Use 3 to 63 small letters, numbers and hyphens.",
    currency: "Currency",
    currencyHint: "The funnel sells in this currency: its products and offers have to be priced in it before you publish.",
    storeCurrency: "{code} (the store's)",
    aiNeedsProduct: "The AI writes the page from a product. Go back and choose one.",
    chooseProduct: "Choose a product",
    summary: "You're building",
    summaryProduct: "Product: {name}",
    summaryNoProduct: "No product chosen yet",
    summaryUpsell: "With an offer after the order",
    summaryNoUpsell: "No offer after the order",
    summaryLeads: "Collects customer numbers",
    // Results
    created: "“{name}” is ready.",
    createdPartial: "The funnel was made, but not all of its pages came with it: {message}",
    productByHand: "The funnel is ready, but not everything was written ({message}). Check the product on its pages in the editor.",
    q1Missing: "Choose a product, or continue without one.",
    steps: "Wizard steps",
    offerByHand: "The funnel is ready, but the offer didn't reach the offer step. Choose it there in the editor.",
    planLimit: "Upgrade the plan",
    // By code
    codeTitle: "Copy a funnel by code",
    codeBody: "The code another merchant gave you. You get the funnel's pages and links, without their products or orders.",
    code: "Funnel code",
    importIt: "Copy the funnel",
    importing: "Copying…",
    imported: "“{name}” copied — {steps} pages. Choose your products before you publish.",
    // Share by code
    shareTitle: "Share this funnel by code",
    shareDescription: "Give this code to another merchant. They get a copy of the funnel's pages and links — not your products, offers or orders.",
    shareStop: "Stop sharing",
    shareStopped: "Sharing stopped. The old code no longer works.",
    shareCode: "Share by code",
    copy: "Copy the code",
    codeLoading: "Getting the code…",
    close: "Close",
  },
  ar: {
    progress: "سؤال {n} من {total}",
    back: "رجوع",
    next: "التالي",
    cancel: "إلغاء",
    build: "ابني الفانل",
    building: "بنبنيه…",
    q1: "بتبيع إيه؟",
    q1Hint: "صفحات الفانل هتمشي على المنتج ده. تقدر تغيّره بعدين صفحة صفحة.",
    searchProducts: "دوّر في منتجاتك",
    searchProductsPlaceholder: "اسم المنتج",
    products: "منتجاتك",
    picked: "اخترته",
    change: "غيّر",
    noPrice: "لسه من غير سعر",
    noProductsTitle: "لسه معندكش منتجات",
    noProductsBody: "الفانل بيبيع منتج واحد. ضيفه الأول وارجع هنا.",
    addProduct: "ضيف منتج الأول",
    withoutProduct: "كمّل من غير منتج",
    withoutProductHint: "الصفحات هتعرض أحدث منتج في المتجر لحد ما تختار.",
    noProductPicked: "من غير منتج",
    noMatch: "مفيش منتج بالاسم ده.",
    productsFailed: "معرفناش نجيب منتجاتك.",
    retry: "جرّب تاني",
    moreProducts: "دي أول {n}. اكتب اسم عشان تلاقي الباقي.",
    haveCode: "معايا كود فانل",
    onlyLeads: "مش ببيع — بجمع أرقام عملاء",
    q2: "أنهي عرض؟",
    q2Hint: "فورم الأوردر هيبيع بإيه، وهل العميل يشوف عرض كمان بعد ما يطلب.",
    orderForm: "فورم الأوردر",
    orderFormOffer: "هيبيع بالعرض الأساسي للمنتج: {offer}",
    orderFormPrice: "هيبيع بسعر المنتج: {price}",
    orderFormPlain: "هيبيع بسعر المنتج، من غير عرض.",
    orderFormNoProduct: "هيبيع المنتج اللي كل صفحة بتعرضه.",
    productOffers: "عروض المنتج",
    mainOffer: "الأساسي",
    manageOffers: "عدّل عروض المنتج",
    upsell: "عرض بعد الشراء (upsell)",
    upsellHint: "أول ما الأوردر يتعمل، عرض كمان العميل يوافق عليه بضغطة واحدة. بيضيف خطوة عرض للفانل.",
    upsellWhich: "هتعرض عليه إيه؟",
    upsellLater: "هختاره من المحرر",
    upsellLaterHint: "الفانل مش هيتنشر غير لما خطوة العرض يبقى فيها عرض.",
    fromThisProduct: "من المنتج ده",
    otherOffers: "عروض تانية في المتجر",
    noOffers: "لسه مفيش عروض شغّالة في المتجر. ابني الفانل دلوقتي واختار العرض من المحرر لما تضيف واحد.",
    offersFailed: "معرفناش نجيب العروض. تقدر تختار العرض من المحرر.",
    offerOf: "{offer} — {product}",
    q3: "أنهي شكل؟",
    q3Hint: "فانل جاهز تبدأ منه. كل حاجة فيه تتغيّر بعدين.",
    q3LeadsHint: "فورم بيجمع الأسماء والأرقام، وبعده صفحة شكر.",
    name: "اسم الفانل",
    nameRequired: "اكتب اسم للفانل.",
    moreDetails: "اللينك والعملة",
    link: "اللينك",
    linkHint: "حروف وأرقام وشرطات. سيبه فاضي وهيتعمل من الاسم.",
    linkInvalid: "استخدم من ٣ لـ ٦٣ حرف صغير وأرقام وشرطات.",
    currency: "العملة",
    currencyHint: "الفانل بيبيع بالعملة دي: لازم منتجاته وعروضه تكون متسعّرة بيها قبل النشر.",
    storeCurrency: "{code} (عملة المتجر)",
    aiNeedsProduct: "الذكاء الاصطناعي بيكتب الصفحة من منتج. ارجع واختار واحد.",
    chooseProduct: "اختار منتج",
    summary: "هتبني",
    summaryProduct: "المنتج: {name}",
    summaryNoProduct: "لسه من غير منتج",
    summaryUpsell: "فيه عرض بعد الشراء",
    summaryNoUpsell: "من غير عرض بعد الشراء",
    summaryLeads: "بيجمع أرقام عملاء",
    created: "«{name}» جاهز.",
    createdPartial: "الفانل اتعمل، بس مش كل صفحاته اتضافت: {message}",
    productByHand: "الفانل جاهز، بس مش كل حاجة اتكتبت ({message}). راجع المنتج في صفحاته من المحرر.",
    q1Missing: "اختار منتج، أو كمّل من غير منتج.",
    steps: "خطوات المعالج",
    offerByHand: "الفانل جاهز، بس العرض ماوصلش لخطوة العرض. اختاره هناك من المحرر.",
    planLimit: "رقّي الباقة",
    codeTitle: "انسخ فانل بكود",
    codeBody: "الكود اللي تاجر تاني إداهولك. هتاخد صفحات الفانل ووصلاته، من غير منتجاته ولا أوردراته.",
    code: "كود الفانل",
    importIt: "انسخ الفانل",
    importing: "بننسخه…",
    imported: "«{name}» اتنسخ — {steps} صفحات. اختار منتجاتك قبل ما تنشره.",
    shareTitle: "شارك الفانل ده بكود",
    shareDescription: "ادّي الكود ده لتاجر تاني. هياخد نسخة من صفحات الفانل ووصلاته — من غير منتجاتك ولا عروضك ولا أوردراتك.",
    shareStop: "وقّف المشاركة",
    shareStopped: "المشاركة وقفت. الكود القديم مبقاش شغّال.",
    shareCode: "شاركه بكود",
    copy: "انسخ الكود",
    codeLoading: "بنجيب الكود…",
    close: "اقفل",
  },
} satisfies Messages;

export type WizardStrings = (typeof WIZARD_STRINGS)["en"];
