import type { Locale, Messages } from "@/i18n/LocaleContext";
import type { ConversionOfferType } from "@/mock/types";

export type OfferTabKey = "all" | ConversionOfferType;

export const OFFER_TYPES: ConversionOfferType[] = ["order_bump", "post_purchase_upsell", "cross_sell", "downsell", "bundle"];

export const TYPE_LABEL: Record<Locale, Record<ConversionOfferType, string>> = {
  en: {
    order_bump: "Order bump",
    post_purchase_upsell: "Post-purchase upsell",
    cross_sell: "Cross-sell",
    downsell: "Downsell",
    bundle: "Bundle",
  },
  ar: {
    order_bump: "عرض إضافي عند الدفع",
    post_purchase_upsell: "عرض بعد الشراء",
    cross_sell: "منتجات مقترحة",
    downsell: "عرض بديل",
    bundle: "باقة",
  },
};

export const TYPE_HINT: Record<Locale, Record<ConversionOfferType, string>> = {
  en: {
    order_bump: "A one-click add-on shown as a checkbox on the checkout page.",
    post_purchase_upsell: "Shown right after the order is placed — accepted with one tap, no re-entering details.",
    cross_sell: "Related products suggested in the cart drawer (“customers also bought”).",
    downsell: "A discount offered when the customer tries to cancel or declines an upsell.",
    bundle: "Quantity breaks — buy more of the same product for a bigger discount.",
  },
  ar: {
    order_bump: "إضافة بنقرة واحدة تظهر كخانة اختيار في صفحة إتمام الطلب.",
    post_purchase_upsell: "يظهر مباشرة بعد تأكيد الطلب ويُقبل بلمسة واحدة دون إعادة إدخال البيانات.",
    cross_sell: "منتجات ذات صلة تُقترح داخل السلة («العملاء اشتروا أيضًا»).",
    downsell: "خصم يُعرض عندما يحاول العميل إلغاء الطلب أو يرفض العرض بعد الشراء.",
    bundle: "خصم الكمية — كلما اشترى العميل قطعًا أكثر من نفس المنتج زاد الخصم.",
  },
};

export const TAB_LABEL: Record<Locale, Record<OfferTabKey, string>> = {
  en: {
    all: "All",
    order_bump: "Order bumps",
    post_purchase_upsell: "Post-purchase upsells",
    cross_sell: "Cross-sell",
    downsell: "Downsell",
    bundle: "Bundles",
  },
  ar: {
    all: "الكل",
    order_bump: "عروض إضافية عند الدفع",
    post_purchase_upsell: "عروض بعد الشراء",
    cross_sell: "منتجات مقترحة",
    downsell: "عروض بديلة",
    bundle: "باقات",
  },
};

/** Stored trigger labels written by the form (kept in English for data stability). */
export const TRIGGER_ANY_PRODUCT = "Any product";
export const TRIGGER_ANY_ORDER_ON_CANCEL = "Any order on cancel";

export const PAGE_STRINGS = {
  en: {
    title: "Offers & bundles",
    description: "Order bumps, upsells, cross-sells and quantity bundles that lift average order value.",
    createOffer: "Create offer",
    editOffer: "Edit offer",
    kpiRevenue: "Extra revenue from offers",
    kpiRevenueHint: "All time, accepted offers only",
    kpiRate: "Acceptance rate",
    kpiRateHint: "Accepted ÷ impressions",
    kpiActive: "Active offers",
    kpiActiveHint: "{n} total",
    emptyAll: "No offers yet. Create your first one.",
    emptyType: "No “{type}” offers yet.",
    colOffer: "Offer",
    colType: "Type",
    colTrigger: "Trigger",
    colOffered: "Offered",
    colDiscount: "Discount",
    colImpressions: "Impressions → accepted",
    colRevenue: "Revenue",
    toggleAria: "Enable or disable “{name}”",
    editAria: "Edit “{name}”",
    deleteAria: "Delete “{name}”",
    toastEnabled: "Offer enabled.",
    toastDisabled: "Offer disabled.",
    toastDeleted: "Offer deleted.",
    confirmTitleNamed: "Delete “{name}”?",
    confirmTitle: "Delete offer?",
    confirmDescription: "The offer stops showing immediately. Historical revenue stays in reports.",
    confirmLabel: "Delete offer",
    anyProduct: "Any product",
    anyOrderOnCancel: "Any order on cancel",
    pctOff: "{pct}% off",
    amountOff: "{amount} off",
    noDiscount: "No discount",
    tier: "{q}× → {pct}%",
  },
  ar: {
    title: "العروض والباقات",
    description: "عروض إضافية عند الدفع، وعروض بعد الشراء، ومنتجات مقترحة، وباقات بخصم الكمية لرفع متوسط قيمة الطلب.",
    createOffer: "إنشاء عرض",
    editOffer: "تعديل العرض",
    kpiRevenue: "إيرادات إضافية من العروض",
    kpiRevenueHint: "منذ البداية، العروض المقبولة فقط",
    kpiRate: "معدل القبول",
    kpiRateHint: "المقبولة ÷ مرات الظهور",
    kpiActive: "العروض النشطة",
    kpiActiveHint: "الإجمالي {n}",
    emptyAll: "لا توجد عروض بعد. أنشئ أول عرض لك.",
    emptyType: "لا توجد عروض من نوع «{type}» بعد.",
    colOffer: "العرض",
    colType: "النوع",
    colTrigger: "يظهر عند",
    colOffered: "المنتجات المعروضة",
    colDiscount: "الخصم",
    colImpressions: "مرات الظهور ← المقبولة",
    colRevenue: "الإيرادات",
    toggleAria: "تفعيل أو تعطيل «{name}»",
    editAria: "تعديل «{name}»",
    deleteAria: "حذف «{name}»",
    toastEnabled: "تم تفعيل العرض.",
    toastDisabled: "تم تعطيل العرض.",
    toastDeleted: "تم حذف العرض.",
    confirmTitleNamed: "حذف «{name}»؟",
    confirmTitle: "حذف العرض؟",
    confirmDescription: "سيتوقف ظهور العرض فورًا، وتبقى الإيرادات السابقة في التقارير.",
    confirmLabel: "حذف العرض",
    anyProduct: "أي منتج",
    anyOrderOnCancel: "أي طلب عند الإلغاء",
    pctOff: "خصم {pct}%",
    amountOff: "خصم {amount}",
    noDiscount: "بدون خصم",
    tier: "{q} قطع: خصم {pct}%",
  },
} satisfies Messages;

export const FORM_STRINGS = {
  en: {
    offerType: "Offer type",
    name: "Name",
    namePlaceholder: "Internal name",
    headline: "Headline",
    headlineHint: "What the customer sees. Arabic is fine.",
    headlinePlaceholder: "Add … at a special price — one-time offer",
    triggerProducts: "Trigger products",
    triggerHint: "Show this offer when the cart contains any of these. Leave empty for all products.",
    offeredProducts: "Offered products",
    qty: "Qty",
    qtyAria: "Quantity of {name}",
    quantityTiers: "Quantity tiers",
    buy: "Buy",
    get: "get",
    off: "off",
    tierQtyAria: "Tier {n} quantity",
    tierPctAria: "Tier {n} discount percentage",
    removeTier: "Remove tier",
    addTier: "Add tier",
    discount: "Discount",
    noDiscount: "No discount",
    percentageOff: "Percentage off",
    fixedOff: "Fixed amount off",
    percentage: "Percentage",
    amountOff: "Amount off",
    saveOffer: "Save offer",
    createOffer: "Create offer",
    preview: "Preview",
    previewNote: "Approximation of how the offer renders in the storefront checkout.",
    errName: "Give the offer a name.",
    errHeadline: "Write the headline customers will see.",
    errOffered: "Pick at least one product to offer.",
    errPercent: "Enter a percentage between 0 and 100.",
    errAmount: "Enter a valid amount.",
    errTiers: "Each tier needs a quantity of 2+ and a percentage between 0 and 100.",
    toastSaved: "Offer saved.",
    toastCreated: "Offer created.",
  },
  ar: {
    offerType: "نوع العرض",
    name: "الاسم",
    namePlaceholder: "اسم داخلي",
    headline: "العنوان",
    headlineHint: "النص الذي يراه العميل. يمكنك الكتابة بالعربية.",
    headlinePlaceholder: "أضف … بخصم خاص — عرض لمرة واحدة",
    triggerProducts: "المنتجات التي تُظهر العرض",
    triggerHint: "يظهر العرض عندما تحتوي السلة على أي من هذه المنتجات. اتركها فارغة لتطبيقه على كل المنتجات.",
    offeredProducts: "المنتجات المعروضة",
    qty: "الكمية",
    qtyAria: "كمية {name}",
    quantityTiers: "شرائح خصم الكمية",
    buy: "اشترِ",
    get: "واحصل على خصم",
    off: "",
    tierQtyAria: "كمية الشريحة {n}",
    tierPctAria: "نسبة خصم الشريحة {n}",
    removeTier: "حذف الشريحة",
    addTier: "إضافة شريحة",
    discount: "الخصم",
    noDiscount: "بدون خصم",
    percentageOff: "خصم بنسبة مئوية",
    fixedOff: "خصم بمبلغ ثابت",
    percentage: "النسبة",
    amountOff: "قيمة الخصم",
    saveOffer: "حفظ العرض",
    createOffer: "إنشاء العرض",
    preview: "معاينة",
    previewNote: "معاينة تقريبية لشكل العرض في صفحة إتمام الطلب بالمتجر.",
    errName: "أدخل اسمًا للعرض.",
    errHeadline: "اكتب العنوان الذي سيراه العملاء.",
    errOffered: "اختر منتجًا واحدًا على الأقل لعرضه.",
    errPercent: "أدخل نسبة بين 0 و100.",
    errAmount: "أدخل مبلغًا صحيحًا.",
    errTiers: "كل شريحة تحتاج كمية 2 أو أكثر ونسبة بين 0 و100.",
    toastSaved: "تم حفظ العرض.",
    toastCreated: "تم إنشاء العرض.",
  },
} satisfies Messages;

export const PREVIEW_STRINGS = {
  en: {
    headlinePlaceholder: "Your headline appears here",
    offeredProduct: "Offered product",
    bumpCheck: "Yes, add this to my order",
    placeOrder: "Place order — COD",
    orderPlaced: "Order placed",
    waitBeforeYouGo: "Wait — before you go",
    oneTimeOffer: "One-time offer",
    keepOrder: "Keep my order",
    cancelAnyway: "Cancel anyway",
    yesAdd: "Yes, add it",
    noThanks: "No thanks",
    addToCart: "Add to cart",
    cart: "Cart",
  },
  ar: {
    headlinePlaceholder: "سيظهر العنوان هنا",
    offeredProduct: "المنتج المعروض",
    bumpCheck: "نعم، أضف هذا إلى طلبي",
    placeOrder: "تأكيد الطلب — الدفع عند الاستلام",
    orderPlaced: "تم تأكيد الطلب",
    waitBeforeYouGo: "انتظر — قبل أن تغادر",
    oneTimeOffer: "عرض لمرة واحدة",
    keepOrder: "احتفظ بطلبي",
    cancelAnyway: "إلغاء على أي حال",
    yesAdd: "نعم، أضفه",
    noThanks: "لا، شكرًا",
    addToCart: "أضف إلى السلة",
    cart: "السلة",
  },
} satisfies Messages;
