import type { Messages } from "@/i18n/LocaleContext";

/** Refunds of the prepaid balance, on the Usage tab. */
export const REFUND_STRINGS = {
  en: {
    title: "Get unused balance back",
    rule: "You can get back up to {share} of each top-up you paid, while it's still in your balance. Gifts and corrections from Zimos aren't refundable.",
    max: "Up to {amount} now",
    min: "At least {amount}",
    request: "Request a refund",
    belowMin: "There's less than {min} you can get back right now.",
    debt: "Your balance is below zero. Top it up to clear what you owe before asking for a refund.",
    openRequested: "Your refund of {amount} is waiting for review. It's held off your balance until then.",
    openApproved: "Your refund of {amount} was approved. Zimos will send it to you soon.",
    cancel: "Cancel the request",
    cancelled: "Request cancelled. The amount is back on your balance.",
    historyTitle: "Your refund requests",
    status_requested: "Waiting for review",
    status_approved: "Approved",
    status_rejected: "Rejected",
    status_cancelled: "Cancelled",
    status_paid: "Paid to you",
    rejectedNote: "Reason: {note}",
    dialogTitle: "Request a refund",
    amount: "Amount (EGP)",
    amountHint: "Between {min} and {max}.",
    amountInvalid: "Enter an amount between {min} and {max}.",
    method: "Send it to",
    method_instapay: "InstaPay",
    method_wallet: "Mobile wallet",
    account: "InstaPay address or wallet number",
    accountRequired: "Enter where to send it.",
    send: "Send the request",
    dialogCancel: "Cancel",
    sending: "Sending…",
    sent: "Request sent. The amount is held off your balance until Zimos reviews it.",
    errOpen: "You already have a refund request open. Wait for it, or cancel it first.",
    errTooHigh: "That's more than you can get back right now: up to {max}.",
    errTooLow: "The least you can ask for is {min}.",
    errNotOnPlan: "Refunds are for stores on pay per order or with a prepaid balance.",
    errDisabled: "Refunds aren't available right now.",
  },
  ar: {
    title: "استرداد الرصيد غير المستخدم",
    rule: "يمكنك استرداد حتى {share} من كل شحنة دفعتها، ما دامت في رصيدك. الهدايا والتصحيحات من Zimos لا تُسترد.",
    max: "حتى {amount} الآن",
    min: "{amount} على الأقل",
    request: "اطلب استردادًا",
    belowMin: "المبلغ الذي يمكنك استرداده الآن أقل من {min}.",
    debt: "رصيدك أقل من صفر. اشحنه لسداد المستحق قبل طلب استرداد.",
    openRequested: "طلب استرداد {amount} قيد المراجعة. المبلغ محجوز من رصيدك حتى ذلك الحين.",
    openApproved: "تمت الموافقة على استرداد {amount}. سيحوّله لك فريق Zimos قريبًا.",
    cancel: "إلغاء الطلب",
    cancelled: "أُلغي الطلب وعاد المبلغ إلى رصيدك.",
    historyTitle: "طلبات الاسترداد",
    status_requested: "قيد المراجعة",
    status_approved: "تمت الموافقة",
    status_rejected: "مرفوض",
    status_cancelled: "ملغى",
    status_paid: "تم التحويل إليك",
    rejectedNote: "السبب: {note}",
    dialogTitle: "طلب استرداد",
    amount: "المبلغ (ج.م.)",
    amountHint: "بين {min} و{max}.",
    amountInvalid: "أدخل مبلغًا بين {min} و{max}.",
    method: "يُحوَّل إلى",
    method_instapay: "إنستاباي",
    method_wallet: "محفظة إلكترونية",
    account: "عنوان إنستاباي أو رقم المحفظة",
    accountRequired: "أدخل أين يُحوَّل المبلغ.",
    send: "إرسال الطلب",
    dialogCancel: "إلغاء",
    sending: "جارٍ الإرسال…",
    sent: "تم إرسال الطلب. المبلغ محجوز من رصيدك حتى يراجعه فريق Zimos.",
    errOpen: "لديك طلب استرداد مفتوح بالفعل. انتظره أو ألغِه أولًا.",
    errTooHigh: "هذا أكثر مما يمكنك استرداده الآن: حتى {max}.",
    errTooLow: "أقل مبلغ يمكنك طلبه هو {min}.",
    errNotOnPlan: "الاسترداد متاح للمتاجر على خطة الدفع لكل طلب أو التي لديها رصيد.",
    errDisabled: "الاسترداد غير متاح حاليًا.",
  },
} satisfies Messages;

export type RefundText = Record<keyof (typeof REFUND_STRINGS)["en"], string>;
