import type { Messages } from "@/i18n/LocaleContext";

/** The Subscription section's own words (the moved Settings parts keep theirs, in billingParts). */
export const SUBSCRIPTION_STRINGS = {
  en: {
    title: "Subscription",
    description: "Your Zimos plan, how much of it you use, and its invoices.",
    tabsLabel: "Subscription sections",
    plansTab: "Plans",
    usageTab: "Usage",
    invoicesTab: "Invoices",
    noAccess: "Only the store's owner or its accountant can see and manage its subscription.",
    // Plans
    currentPlan: "Your current plan",
    notOffered: "Not offered any more",
    saveYearly: "Save {amount} a year",
    insteadOf: "instead of {price}",
    startTrial: "Start the free trial ({days})",
    choosePlan: "Choose this plan",
    contactSupport: "Contact support to switch",
    trialStarted: "Your free trial has started.",
    planChanged: "Your plan has been changed.",
    payNow: "Pay now",
    trialUsed: "This account has already had its free trial.",
    noTrial: "This plan has no free trial.",
    planNotAvailable: "This plan isn't available any more.",
    openCharge: "A payment is open for your current plan. Settle it first (Invoices tab).",
    needsSupport: "While a paid subscription runs, your plan is changed through Zimos support.",
    trialNote: "Your store is a draft. Start a free trial of any plan to publish it — once per account, with nothing to pay.",
    trialEndNote: "When the trial ends nothing is charged automatically: you'll be reminded, and you pay when you choose.",
    paidNote: "To switch plan while your paid subscription runs, contact Zimos support.",
    code: "Discount or voucher code",
    codePlaceholder: "e.g. CAIRO10",
    check: "Check",
    checking: "Checking…",
    withCode: "With {code}: {price}",
    applyCode: "Apply to my store",
    applying: "Applying…",
    codeApplied: "The code is applied to your store.",
    storeCode: "Code {code}: {discount}",
    codeInactive: "Code {code} is no longer active, so it gives no discount.",
    payPerOrder: "Pay per order",
    payPerOrderBody: "No monthly fee: a small fee on each order, from a prepaid balance.",
    comingSoon: "Coming soon",
    // Usage
    storesUsage: "Stores",
    funnelsUsage: "Funnels created this month",
    ofMax: "{used} of {max}",
    unlimitedUsage: "{used} — unlimited",
    resetsOn: "Resets on {date}",
    // Invoices
    noInvoices: "No invoices yet.",
    invoiceDate: "Date",
    invoicePeriod: "Period",
    invoiceAmount: "Amount",
    invoiceStatus: "Status",
    statusPaid: "Paid",
    statusPending: "Due",
    statusFailed: "Failed",
    periodRange: "{start} – {end}",
    discountLine: "{discount} off",
    previous: "Previous",
    next: "Next",
    pageOf: "Page {page} of {pages}",
    // Settings link
    settingsTitle: "Plan and billing",
    settingsBody: "Your plan, its usage, invoices, payments and referral code are now in Subscription.",
    settingsOpen: "Open Subscription",
  },
  ar: {
    title: "الاشتراك",
    description: "خطتك في Zimos، ومقدار استخدامك لها، وفواتيرها.",
    tabsLabel: "أقسام الاشتراك",
    plansTab: "الخطط",
    usageTab: "الاستخدام",
    invoicesTab: "الفواتير",
    noAccess: "لا يطّلع على اشتراك المتجر ولا يديره إلا مالكه أو المحاسب.",
    currentPlan: "خطتك الحالية",
    notOffered: "لم تعد معروضة",
    saveYearly: "وفّر {amount} سنويًا",
    insteadOf: "بدلًا من {price}",
    startTrial: "ابدأ التجربة المجانية ({days})",
    choosePlan: "اختر هذه الخطة",
    contactSupport: "تواصل مع الدعم للتبديل",
    trialStarted: "بدأت فترتك التجريبية المجانية.",
    planChanged: "تم تغيير خطتك.",
    payNow: "ادفع الآن",
    trialUsed: "استخدم هذا الحساب فترته التجريبية المجانية بالفعل.",
    noTrial: "هذه الخطة بلا فترة تجريبية مجانية.",
    planNotAvailable: "هذه الخطة لم تعد متاحة.",
    openCharge: "هناك دفعة مفتوحة لخطتك الحالية. سدّدها أولًا من تبويب الفواتير.",
    needsSupport: "أثناء سريان اشتراك مدفوع يجري تغيير الخطة عبر دعم Zimos.",
    trialNote: "متجرك مسودة. ابدأ فترة تجريبية مجانية لأي خطة لنشره، مرة واحدة لكل حساب ودون أي دفع.",
    trialEndNote: "عند انتهاء الفترة التجريبية لا يُخصم أي مبلغ تلقائيًا: سننبهك، وتدفع حين تختار.",
    paidNote: "لتبديل خطتك أثناء سريان اشتراكك المدفوع، تواصل مع دعم Zimos.",
    code: "كود خصم أو قسيمة",
    // Latin only: it sits in a left-to-right code field.
    codePlaceholder: "CAIRO10",
    check: "تحقق",
    checking: "جارٍ التحقق…",
    withCode: "مع {code}: {price}",
    applyCode: "طبّقه على متجري",
    applying: "جارٍ التطبيق…",
    codeApplied: "تم تطبيق الكود على متجرك.",
    storeCode: "الكود {code}: {discount}",
    codeInactive: "الكود {code} لم يعد نشطًا، لذلك لا يمنح خصمًا.",
    payPerOrder: "الدفع لكل طلب",
    payPerOrderBody: "بلا اشتراك شهري: رسوم بسيطة على كل طلب تُخصم من رصيد مسبق الدفع.",
    comingSoon: "قريبًا",
    storesUsage: "المتاجر",
    funnelsUsage: "مسارات البيع المنشأة هذا الشهر",
    ofMax: "{used} من {max}",
    unlimitedUsage: "{used} — غير محدود",
    resetsOn: "يُعاد العدّ في {date}",
    noInvoices: "لا توجد فواتير بعد.",
    invoiceDate: "التاريخ",
    invoicePeriod: "الفترة",
    invoiceAmount: "المبلغ",
    invoiceStatus: "الحالة",
    statusPaid: "مدفوعة",
    statusPending: "مستحقة",
    statusFailed: "فشلت",
    periodRange: "{start} – {end}",
    discountLine: "خصم {discount}",
    previous: "السابق",
    next: "التالي",
    pageOf: "الصفحة {page} من {pages}",
    settingsTitle: "الخطة والفوترة",
    settingsBody: "خطتك واستخدامها وفواتيرها ومدفوعاتها وكود الإحالة أصبحت كلها في قسم الاشتراك.",
    settingsOpen: "فتح قسم الاشتراك",
  },
} satisfies Messages;

export type SubscriptionText = Record<keyof (typeof SUBSCRIPTION_STRINGS)["en"], string>;
