import type { Messages } from "@/i18n/LocaleContext";

/** The prepaid balance and the pay-per-order plan, in the Subscription section. */
export const WALLET_STRINGS = {
  en: {
    walletTitle: "Prepaid balance",
    walletBody: "On the pay-per-order plan, each order's fee comes from this balance.",
    balance: "Balance",
    feePerOrder: "Fee per order",
    ordersLeft: "Orders left",
    ordersLeftValue: "{left} ({before} before the overdraft)",
    thisMonth: "This month",
    thisMonthValue: "{amount} for {orders} orders",
    cairoNote: "Cairo time",
    topUp: "Top up",
    phaseLow: "Your balance is running low: fewer than {count} orders are left before the overdraft. Top it up so your store keeps selling.",
    phaseOverdraft: "Your balance is at or below zero. Your store keeps selling until the {overdraft} overdraft runs out. Top it up now.",
    phaseExhausted: "Your balance has run out, so your store has stopped taking orders. Top it up to reopen it.",
    notOnFeePlan: "Your store isn't on the pay-per-order plan, so no fee is taken from this balance.",
    ledgerTitle: "Balance history",
    ledgerEmpty: "No movements yet.",
    type_topup: "Top-up",
    type_order_fee: "Order fee",
    type_order_fee_reversal: "Fee returned",
    type_order_fee_recharge: "Fee charged again",
    type_free_orders_grant: "Free orders from Zimos",
    type_adjustment: "Correction by Zimos",
    type_gift: "Gift from Zimos (not refundable)",
    type_refund_hold: "Refund requested (held)",
    type_refund_release: "Refund returned to your balance",
    type_refund_paid: "Refund sent to you",
    type_move_payment_credit: "Payment for a cancelled plan move, added to your balance",
    freeOrder: "Free order",
    freeOrderReturned: "Free order returned",
    freeOrdersValue: "{count} free orders",
    freeOrdersLeft: "Free orders left",
    freeOrdersLeftValue: "{left} of {total}",
    debt: "Owed",
    debtNote: "Up to {limit}",
    phaseDebt: "Your balance is below zero. New orders keep coming until you owe {limit}. Top it up now.",
    phaseLimitReached: "Your balance has reached its limit, so new orders are refused. Your store stays open. Top it up to take orders again.",
    cardHint: "Pay {amount} on {name}'s secure page. Your balance goes up as soon as the payment is confirmed.",
    cardPay: "Pay by card",
    cardOpening: "Opening the payment page…",
    cardStartFailed: "The payment page couldn't be opened. Try again in a few minutes, or top up by transfer.",
    cardNotOnPlan: "Topping up by card is for stores on the pay-per-order plan.",
    cardPaid: "Your card payment was confirmed and your balance was topped up.",
    cardPending: "We're waiting for the payment to be confirmed. Your balance goes up as soon as it is.",
    cardFailed: "The card payment didn't go through. Nothing was charged to your balance; you can try again.",
    cardProblem: "The payment arrived with a different amount. The Zimos team will check it; contact support if needed.",
    cardTopupsTitle: "Card top-ups",
    cardStatusPaid: "Credited",
    cardStatusOpen: "Waiting",
    cardStatusFailed: "Not paid",
    cardStatusProblem: "Under review",
    orderRef: "Order {number}",
    topupsTitle: "Your top-ups",
    topupTitle: "Top up your balance",
    topupAmount: "Amount you'll send (EGP)",
    topupAmountHint: "Between {min} and {max}.",
    topupAmountInvalid: "Enter an amount between {min} and {max}.",
    topupNext: "Continue",
    topupSent: "Sent. Your balance goes up once the Zimos team checks the transfer.",
    topupTooMany: "You have {count} top-ups under review. Wait until one is reviewed.",
    topupDisabled: "Topping up isn't available right now.",
    noManualMethod: "There's no way to top up by transfer right now. Contact Zimos support.",
    changeAmount: "Change the amount",
    // The pay-per-order card
    ppoFee: "{fee} per order",
    ppoChoose: "Choose pay per order",
    ppoChoosing: "Choosing…",
    ppoChosen: "Your store is now on pay per order. Top up your balance from the Usage tab.",
    ppoCurrent: "Your current plan",
    ppoSupport: "Contact support to switch",
    ppoBalanceHint: "No monthly fee. Each order's fee comes from a prepaid balance you top up.",
    ppoOpenCharge: "A payment is open for your current plan. Settle it first (Invoices tab).",
    ppoNeedsSupport: "While a paid subscription runs, your plan is changed through Zimos support.",
  },
  ar: {
    walletTitle: "الرصيد المدفوع مسبقًا",
    walletBody: "في خطة الدفع لكل طلب، يُخصم رسم كل طلب من هذا الرصيد.",
    balance: "الرصيد",
    feePerOrder: "الرسم لكل طلب",
    ordersLeft: "الطلبات المتبقية",
    ordersLeftValue: "{left} ({before} قبل السحب على المكشوف)",
    thisMonth: "هذا الشهر",
    thisMonthValue: "{amount} مقابل {orders} طلبًا",
    cairoNote: "بتوقيت القاهرة",
    topUp: "اشحن الرصيد",
    phaseLow: "رصيدك يقترب من النفاد: تبقّى أقل من {count} طلبًا قبل السحب على المكشوف. اشحنه ليواصل متجرك البيع.",
    phaseOverdraft: "رصيدك صفر أو أقل. يواصل متجرك البيع حتى ينفد السحب على المكشوف البالغ {overdraft}. اشحنه الآن.",
    phaseExhausted: "نفد رصيدك، فتوقّف متجرك عن استقبال الطلبات. اشحنه لإعادة فتحه.",
    notOnFeePlan: "متجرك ليس على خطة الدفع لكل طلب، لذلك لا يُخصم أي رسم من هذا الرصيد.",
    ledgerTitle: "سجل الرصيد",
    ledgerEmpty: "لا توجد حركات بعد.",
    type_topup: "شحن",
    type_order_fee: "رسم طلب",
    type_order_fee_reversal: "رسم مُسترد",
    type_order_fee_recharge: "رسم مخصوم من جديد",
    type_free_orders_grant: "طلبات مجانية من Zimos",
    type_adjustment: "تصحيح من Zimos",
    type_gift: "هدية من Zimos (لا تُسترد)",
    type_refund_hold: "طلب استرداد (محجوز)",
    type_refund_release: "استرداد عاد إلى رصيدك",
    type_refund_paid: "تم تحويل الاسترداد إليك",
    type_move_payment_credit: "دفعة لانتقال خطة ملغى، أُضيفت إلى رصيدك",
    freeOrder: "طلب مجاني",
    freeOrderReturned: "طلب مجاني مُسترد",
    freeOrdersValue: "{count} طلبات مجانية",
    freeOrdersLeft: "الطلبات المجانية المتبقية",
    freeOrdersLeftValue: "{left} من {total}",
    debt: "المستحق عليك",
    debtNote: "حتى {limit}",
    phaseDebt: "رصيدك أقل من صفر. تستمر الطلبات الجديدة حتى يبلغ المستحق عليك {limit}. اشحنه الآن.",
    phaseLimitReached: "بلغ رصيدك الحد، لذلك تُرفض الطلبات الجديدة. يبقى متجرك مفتوحًا. اشحنه لتعود الطلبات.",
    cardHint: "ادفع {amount} في صفحة {name} الآمنة. يزيد رصيدك فور تأكيد الدفع.",
    cardPay: "ادفع بالبطاقة",
    cardOpening: "جارٍ فتح صفحة الدفع…",
    cardStartFailed: "تعذّر فتح صفحة الدفع. حاول بعد دقائق، أو اشحن بالتحويل.",
    cardNotOnPlan: "الشحن بالبطاقة متاح للمتاجر على خطة الدفع لكل طلب.",
    cardPaid: "تم تأكيد الدفع بالبطاقة وشُحن رصيدك.",
    cardPending: "ننتظر تأكيد الدفع. يزيد رصيدك فور تأكيده.",
    cardFailed: "لم يتم الدفع بالبطاقة. لم يتغيّر رصيدك، ويمكنك المحاولة مجددًا.",
    cardProblem: "وصل الدفع بمبلغ مختلف. سيراجعه فريق Zimos؛ تواصل مع الدعم عند الحاجة.",
    cardTopupsTitle: "الشحن بالبطاقة",
    cardStatusPaid: "أُضيف للرصيد",
    cardStatusOpen: "قيد الانتظار",
    cardStatusFailed: "لم يُدفع",
    cardStatusProblem: "قيد المراجعة",
    orderRef: "الطلب {number}",
    topupsTitle: "طلبات الشحن",
    topupTitle: "اشحن رصيدك",
    topupAmount: "المبلغ الذي ستحوّله (ج.م.)",
    topupAmountHint: "بين {min} و{max}.",
    topupAmountInvalid: "أدخل مبلغًا بين {min} و{max}.",
    topupNext: "متابعة",
    topupSent: "تم الإرسال. يزيد رصيدك بعد أن يراجع فريق Zimos التحويل.",
    topupTooMany: "لديك {count} طلبات شحن قيد المراجعة. انتظر حتى تُراجَع إحداها.",
    topupDisabled: "شحن الرصيد غير متاح حاليًا.",
    noManualMethod: "لا تتوفر حاليًا طريقة للشحن بالتحويل. تواصل مع دعم Zimos.",
    changeAmount: "تغيير المبلغ",
    ppoFee: "{fee} لكل طلب",
    ppoChoose: "اختر الدفع لكل طلب",
    ppoChoosing: "جارٍ الاختيار…",
    ppoChosen: "أصبح متجرك على خطة الدفع لكل طلب. اشحن رصيدك من تبويب الاستخدام.",
    ppoCurrent: "خطتك الحالية",
    ppoSupport: "تواصل مع الدعم للتبديل",
    ppoBalanceHint: "بلا اشتراك شهري. يُخصم رسم كل طلب من رصيد مدفوع مسبقًا تشحنه.",
    ppoOpenCharge: "هناك دفعة مفتوحة لخطتك الحالية. سدّدها أولًا من تبويب الفواتير.",
    ppoNeedsSupport: "أثناء سريان اشتراك مدفوع يجري تغيير الخطة عبر دعم Zimos.",
  },
} satisfies Messages;

export type WalletText = Record<keyof (typeof WALLET_STRINGS)["en"], string>;
