import type { Messages } from "@/i18n/LocaleContext";

/** The words of the variants section: the grid, the phone cards, their menus and the sheets (VariantsSection and ./). */
export const VARIANT_STRINGS = {
  en: {
    title: "Variants",
    description: "Each buyable row: its size / colour, price and stock. Press a figure to change it in place.",
    count_one: "1 variant",
    count_two: "{n} variants",
    count_few: "{n} variants",
    count_many: "{n} variants",
    count_other: "{n} variants",
    add: "Add variant",
    editAll: "Edit all in a table",
    empty: "No variants yet. Add at least one so the product can be sold.",
    notTrackedNote: "Stock: {state}. This product never runs out, so there is no quantity to edit.",
    colVariant: "Variant",
    single: "Default",
    colSku: "SKU",
    colPrice: "Price",
    colCompareAt: "Before discount",
    colStock: "Stock",
    colStatus: "Status",
    colActions: "Actions",
    reserved: "{n} reserved",
    archivedWithProduct: "Archived with product",
    archivedWithProductHint: "Comes back when the product is restored.",
    statusOf: "{name}: on sale",
    statusNowActive: "The variant is active again.",
    statusNowArchived: "The variant is archived.",
    statusFailed: "The status didn't change. {reason}",
    priceSaved: "Price changed.",
    compareSaved: "Price before discount changed.",
    skuSaved: "SKU changed.",
    stockSaved: "Stock updated.",
    priceRequired: "Type the price.",
    stockRequired: "Type the quantity.",
    stockNegative: "Stock can't go below zero.",
    skuTooLong: "Keep the SKU to {max} characters or fewer.",
    skuTaken: "That SKU is already used by another variant.",
    menu: "Actions for {name}",
    editEverything: "Edit everything",
    archive: "Archive variant…",
    restore: "Make it active again",
    addTitle: "Add variant",
    editTitle: "Edit variant",
    sheetAdd: "Add variant",
    sheetSave: "Save variant",
    sheetSaving: "Saving…",
    deleteTitle: "Archive this variant?",
    deleteDescription:
      "It's archived, not removed, so order lines and inventory history that reference it stay intact. Shoppers stop seeing it.",
    deleteConfirm: "Archive variant",
    working: "Archiving…",
    cancel: "Cancel",
    archivedToast: "Variant archived.",
    addedToast: "Variant added.",
    savedToast: "Variant saved.",
  },
  ar: {
    title: "المتغيرات",
    description: "كل صف قابل للشراء: المقاس / اللون وسعره ومخزونه. دوس على أي رقم عشان تعدّله في مكانه.",
    count_one: "متغير واحد",
    count_two: "متغيرين",
    count_few: "{n} متغيرات",
    count_many: "{n} متغير",
    count_other: "{n} متغير",
    add: "ضيف متغير",
    editAll: "عدّل الكل في جدول",
    empty: "مفيش متغيرات لسه. ضيف متغير واحد على الأقل عشان المنتج يتباع.",
    notTrackedNote: "المخزون: {state}. المنتج ده مبيخلصش، فمفيش كمية تتعدّل.",
    colVariant: "المتغير",
    single: "الافتراضي",
    colSku: "SKU",
    colPrice: "السعر",
    colCompareAt: "قبل الخصم",
    colStock: "المخزون",
    colStatus: "الحالة",
    colActions: "إجراءات",
    reserved: "{n} محجوز",
    archivedWithProduct: "مؤرشف مع المنتج",
    archivedWithProductHint: "بيرجع لما المنتج يرجع.",
    statusOf: "{name}: شغّال",
    statusNowActive: "المتغير رجع شغّال.",
    statusNowArchived: "المتغير اتأرشف.",
    statusFailed: "الحالة ما اتغيّرتش. {reason}",
    priceSaved: "السعر اتغيّر.",
    compareSaved: "السعر قبل الخصم اتغيّر.",
    skuSaved: "الـ SKU اتغيّر.",
    stockSaved: "المخزون اتحدّث.",
    priceRequired: "اكتب السعر.",
    stockRequired: "اكتب الكمية.",
    stockNegative: "المخزون ما ينفعش يبقى أقل من صفر.",
    skuTooLong: "خلّي الـ SKU {max} حرف أو أقل.",
    skuTaken: "الـ SKU ده مستخدم لمتغير تاني.",
    menu: "إجراءات {name}",
    editEverything: "عدّل كل حاجة",
    archive: "أرشف المتغير…",
    restore: "رجّعه شغّال",
    addTitle: "ضيف متغير",
    editTitle: "تعديل المتغير",
    sheetAdd: "ضيف المتغير",
    sheetSave: "احفظ المتغير",
    sheetSaving: "بنحفظ…",
    deleteTitle: "تأرشف المتغير ده؟",
    deleteDescription:
      "بيتأرشف ومش بيتمسح، فبنود الأوردرات وسجل المخزون اللي عليه بيفضلوا زي ما هم. العملاء مش هيشوفوه.",
    deleteConfirm: "أرشف المتغير",
    working: "بنأرشف…",
    cancel: "إلغاء",
    archivedToast: "المتغير اتأرشف.",
    addedToast: "المتغير اتضاف.",
    savedToast: "المتغير اتحفظ.",
  },
} satisfies Messages;

export type VariantStrings = (typeof VARIANT_STRINGS)["en"];
