import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the funnels list (/funnels): the page, its stat cards, a row,
 * the row's menu and the two confirmations. Arabic is Egyptian, second
 * person, short: «الفانل», «خطوة», «أوردر», «عرض بعد الشراء».
 */
export const FUNNEL_LIST_STRINGS = {
  en: {
    title: "Funnels",
    description: "A short path from an ad to an order: landing page, order form, an offer after the order, thank you.",
    newFunnel: "New funnel",
    tools: "Tools",
    marketplace: "Template marketplace",
    myTemplates: "My templates",
    importByCode: "I have a funnel code",
    refresh: "Refresh",
    // Stats
    stats: "All funnels in the period",
    kpiVisits: "Visits",
    kpiOrders: "Orders",
    kpiRevenue: "Revenue",
    kpiRevenueHint: "With offers after the order",
    kpiConversion: "Conversion",
    kpiConversionHint: "Orders ÷ visits",
    statsUnavailable: "The numbers couldn't be loaded",
    statsNoAccess: "Your role can't see the numbers. The store owner can give you the reports permission.",
    // Toolbar and chips
    search: "Search funnels",
    searchPlaceholder: "Funnel name",
    statuses: "Funnel status",
    all: "All",
    statusDraft: "Draft",
    statusPublished: "Live",
    statusPaused: "Paused",
    // Rows
    list: "Funnels",
    colFunnel: "Funnel",
    colStatus: "Status",
    colSteps: "Steps",
    colVisits: "Visits",
    colOrders: "Orders",
    colConversion: "Conv.",
    colRevenue: "Revenue",
    colUpdated: "Last edit",
    steps_one: "1 step",
    steps_other: "{n} steps",
    visits_one: "1 visit",
    visits_other: "{n} visits",
    orders_one: "1 order",
    orders_other: "{n} orders",
    edited: "Edited {date}",
    open: "Open",
    openFunnel: "Open “{name}”",
    select: "Select “{name}”",
    selectAll: "Select all the funnels shown",
    selectAllShort: "Select all",
    menuLabel: "Actions for “{name}”",
    // Menu
    preview: "Preview",
    copyLink: "Copy the link",
    report: "Report",
    publish: "Publish",
    pause: "Pause",
    resume: "Resume",
    duplicate: "Duplicate",
    shareCode: "Share by code",
    shareMarket: "Share to the marketplace",
    delete: "Delete",
    // Toasts
    toastLive: "“{name}” is live.",
    toastPaused: "“{name}” paused.",
    toastResumed: "“{name}” is live again.",
    toastPublishBlocked: "“{name}” can't be published yet ({n} problems). Open it and fix them.",
    toastDuplicatedAs: "Copied as “{name}”.",
    toastDuplicatePartial: "The copy was made, but not every step or link came with it: {message}",
    toastCopied: "Link copied.",
    toastCopyFailed: "Couldn't copy.",
    toastDeleted: "Moved to trash",
    copySuffix: "{name} (copy)",
    // Delete
    deleteTitle: "Delete “{name}”?",
    deleteTitlePlain: "Delete the funnel?",
    deleteDescription: "It moves to the trash, where you can restore it for 30 days. Its link stops working right away.",
    deleteConfirm: "Move to trash",
    // Empty
    emptyTitle: "No funnels yet",
    emptyDescription: "A funnel takes a shopper from your ad to an order on one short path, and offers them something more after they order.",
    emptyAction: "Make your first funnel",
    noMatchTitle: "No funnel matches",
    noMatchBody: "Try another name or another status.",
    showAll: "Show all",
    // Plan limit
    upgrade: "Upgrade the plan",
  },
  ar: {
    title: "الفانلز",
    description: "طريق قصير من الإعلان للأوردر: صفحة هبوط، فورم الأوردر، عرض بعد الشراء، وشكرًا.",
    newFunnel: "فانل جديد",
    tools: "أدوات",
    marketplace: "سوق التمبلتات",
    myTemplates: "تمبلتاتي",
    importByCode: "معايا كود فانل",
    refresh: "حدّث",
    stats: "كل الفانلز في الفترة",
    kpiVisits: "الزيارات",
    kpiOrders: "الأوردرات",
    kpiRevenue: "المبيعات",
    kpiRevenueHint: "بعروض بعد الشراء",
    kpiConversion: "التحويل",
    kpiConversionHint: "الأوردرات ÷ الزيارات",
    statsUnavailable: "معرفناش نجيب الأرقام",
    statsNoAccess: "دورك مش بيشوف الأرقام. صاحب المتجر يقدر يديك صلاحية التقارير.",
    search: "دوّر في الفانلز",
    searchPlaceholder: "اسم الفانل",
    statuses: "حالة الفانل",
    all: "الكل",
    statusDraft: "مسودة",
    statusPublished: "شغّال",
    statusPaused: "متوقف",
    list: "الفانلز",
    colFunnel: "الفانل",
    colStatus: "الحالة",
    colSteps: "الخطوات",
    colVisits: "الزيارات",
    colOrders: "الأوردرات",
    colConversion: "التحويل",
    colRevenue: "المبيعات",
    colUpdated: "آخر تعديل",
    steps_one: "خطوة واحدة",
    steps_two: "خطوتين",
    steps_few: "{n} خطوات",
    steps_other: "{n} خطوة",
    visits_one: "زيارة واحدة",
    visits_two: "زيارتين",
    visits_few: "{n} زيارات",
    visits_other: "{n} زيارة",
    orders_one: "أوردر واحد",
    orders_two: "أوردرين",
    orders_few: "{n} أوردرات",
    orders_other: "{n} أوردر",
    edited: "اتعدّل {date}",
    open: "افتح",
    openFunnel: "افتح «{name}»",
    select: "حدّد «{name}»",
    selectAll: "حدّد كل الفانلز اللي ظاهرة",
    selectAllShort: "حدّد الكل",
    menuLabel: "إجراءات «{name}»",
    preview: "عاين",
    copyLink: "انسخ اللينك",
    report: "التقرير",
    publish: "انشره",
    pause: "وقّفه",
    resume: "شغّله تاني",
    duplicate: "اعمل نسخة",
    shareCode: "شاركه بكود",
    shareMarket: "شاركه في سوق التمبلتات",
    delete: "امسحه",
    toastLive: "«{name}» بقى شغّال.",
    toastPaused: "«{name}» اتوقف.",
    toastResumed: "«{name}» رجع شغّال.",
    toastPublishBlocked: "«{name}» مينفعش يتنشر لسه ({n} مشاكل). افتحه وصلّحها.",
    toastDuplicatedAs: "اتعملت نسخة باسم «{name}».",
    toastDuplicatePartial: "النسخة اتعملت، بس مش كل الخطوات أو الوصلات اتنقلت: {message}",
    toastCopied: "اللينك اتنسخ.",
    toastCopyFailed: "معرفناش ننسخ.",
    toastDeleted: "اتنقل لسلة المحذوفات",
    copySuffix: "{name} (نسخة)",
    deleteTitle: "تمسح «{name}»؟",
    deleteTitlePlain: "تمسح الفانل؟",
    deleteDescription: "هيتنقل لسلة المحذوفات وتقدر ترجعه خلال 30 يوم. الرابط هيوقف فورًا.",
    deleteConfirm: "انقل للمحذوفات",
    emptyTitle: "لسه معندكش فانلز",
    emptyDescription: "الفانل بياخد العميل من إعلانك لحد الأوردر في طريق واحد قصير، وبيعرض عليه حاجة زيادة بعد ما يطلب.",
    emptyAction: "اعمل أول فانل",
    noMatchTitle: "مفيش فانل بالشكل ده",
    noMatchBody: "جرّب اسم تاني أو حالة تانية.",
    showAll: "اعرض الكل",
    upgrade: "رقّي الباقة",
  },
} satisfies Messages;

export type FunnelListStrings = (typeof FUNNEL_LIST_STRINGS)["en"];
