import type { Messages } from "@/i18n/LocaleContext";

/** A variant's price history on the product page (handoff 234). */
export const PRICE_HISTORY_STRINGS = {
  en: {
    title: "Price history",
    hint: "Every change of the price or the compare-at price, however it was made: the editor, a bulk edit, a scheduled sale.",
    variantLabel: "Variant",
    singleVariant: "This product",
    current: "Price now",
    compareAt: "Compare-at price",
    lowest30: "Lowest in the last 30 days",
    lowest30Shown: "Shoppers see this beside the sale price.",
    lowest30Idle: "Shoppers see it once the variant is on sale.",
    none: "None",
    legendLabel: "What the lines show",
    legendPrice: "Price",
    legendCompareAt: "Compare-at price",
    chartSummary: "The price of {name} over the last {days} days.",
    changesTitle: "Changes",
    colDate: "When",
    colPrice: "Price",
    colCompareAt: "Compare-at price",
    emptyChanges: "No change in the last {days} days.",
    showAll: "Show all {count} changes",
    showFewer: "Show fewer",
  },
  ar: {
    title: "تاريخ السعر",
    hint: "كل تغيير في السعر أو السعر قبل الخصم، أيًا كان اتعمل منين: التعديل، التعديل المجمّع، أو تخفيض مجدول.",
    variantLabel: "الصنف",
    singleVariant: "المنتج ده",
    current: "السعر دلوقتي",
    compareAt: "السعر قبل الخصم",
    lowest30: "أقل سعر في آخر 30 يوم",
    lowest30Shown: "العميل بيشوفه جنب سعر التخفيض.",
    lowest30Idle: "العميل بيشوفه لما الصنف يبقى عليه تخفيض.",
    none: "مفيش",
    legendLabel: "الخطوط بتوضّح إيه",
    legendPrice: "السعر",
    legendCompareAt: "السعر قبل الخصم",
    chartSummary: "سعر {name} في آخر {days} يوم.",
    changesTitle: "التغييرات",
    colDate: "إمتى",
    colPrice: "السعر",
    colCompareAt: "السعر قبل الخصم",
    emptyChanges: "مفيش تغيير في آخر {days} يوم.",
    showAll: "اعرض كل التغييرات ({count})",
    showFewer: "اعرض أقل",
  },
} satisfies Messages;
