import type { Messages } from "@/i18n/LocaleContext";

export const STRINGS = {
  en: {
    title: "Affiliates & marketers",
    description: "Give creators and groups a referral code, track every order they send, and pay commissions on delivered COD.",
    addAffiliate: "Add affiliate",
    editAffiliate: "Edit affiliate",
    kpiActive: "Active affiliates",
    kpiActiveHint: "{n} total",
    kpiOrders: "Orders via affiliates",
    kpiOrdersHint: "All time",
    kpiDelivered: "Delivered",
    kpiDeliveredHint: "{pct}% of referred orders",
    kpiOwed: "Commissions owed",
    kpiOwedHint: "Earned minus paid",
    emptyTitle: "No affiliates yet",
    emptyDescription: "Add your first marketer to start tracking referrals.",
    colAffiliate: "Affiliate",
    colCode: "Code",
    colCommission: "Commission",
    colClicks: "Clicks",
    colOrders: "Orders",
    colDelivered: "Delivered",
    colConv: "Conv.",
    colEarned: "Earned",
    colPaid: "Paid",
    colOwed: "Owed",
    fixed: "{amount} fixed",
    payOnDeliveredShort: "on delivered",
    payOnConfirmedShort: "on confirmed",
    pay: "Pay",
    code: "Code",
    link: "Link",
    signupLink: "Signup link",
    copiedToast: "{label} copied.",
    copyAria: "Copy {label}",
    copyFailed: "Couldn't copy. Select the text and copy it manually.",
    deliveredCaption: "{n} delivered",
    toastActive: "{name} is active.",
    toastPaused: "{name} paused.",
    toastPaid: "Paid {amount} to {name}.",
    programSettings: "Program settings",
    programSettingsDesc: "How referrals are attributed and counted.",
    publicSignup: "Public signup page",
    publicSignupDesc: "Let marketers apply themselves and get a code instantly.",
    cookieWindow: "Cookie window",
    cookieWindowDesc: "Orders within this many days of the click count for the affiliate.",
    daysOption: "{n} days",
    countDelivered: "Count only delivered orders",
    countDeliveredDesc: "Commissions accrue after the courier confirms delivery, not on confirmation.",
    topAffiliates: "Top affiliates",
    topAffiliatesDesc: "By delivered orders.",
    nothingToRank: "Nothing to rank yet.",
    theirLink: "Their link:",
    payTitle: "Pay {name}?",
    payDescription: "Marks {amount} as paid. Send the transfer via InstaPay or Vodafone Cash first.",
    markPaid: "Mark as paid",
    // form
    name: "Name",
    namePlaceholder: "e.g. Nour — TikTok",
    phone: "Phone",
    phoneHint: "Used for payouts and WhatsApp updates.",
    referralCode: "Referral code",
    referralCodeHint: "Auto-generated from the name; customers type it at checkout or use the link.",
    regenerate: "Regenerate",
    commissionType: "Commission type",
    percentageOfOrder: "Percentage of order",
    fixedPerOrder: "Fixed per order",
    percentage: "Percentage",
    amountPerOrder: "Amount per order",
    payOn: "Pay on",
    payOnHint: "Delivered is safer for COD — no commission on returned orders.",
    deliveredOrder: "Delivered order",
    confirmedOrder: "Confirmed order",
    errName: "Name is required.",
    errPhone: "Phone is required.",
    errCode: "Code is required.",
    errPercent: "Enter a percentage above 0.",
    errAmount: "Enter a valid amount.",
    errMaxPercent: "Can't exceed 100%.",
    toastSaved: "Affiliate saved.",
    toastAdded: "{name} added with code {code}.",
    saveAffiliate: "Save affiliate",
  },
  ar: {
    title: "المسوّقون بالعمولة",
    description: "امنح صنّاع المحتوى والمجموعات رابط إحالة وكودًا خاصًا، وتابع كل طلب يرسلونه، وادفع العمولة على طلبات الدفع عند الاستلام التي تم توصيلها.",
    addAffiliate: "إضافة مسوّق",
    editAffiliate: "تعديل المسوّق",
    kpiActive: "المسوّقون النشطون",
    kpiActiveHint: "الإجمالي {n}",
    kpiOrders: "الطلبات المُحالة",
    kpiOrdersHint: "كل الفترات",
    kpiDelivered: "تم التوصيل",
    kpiDeliveredHint: "{pct}% من الطلبات المُحالة",
    kpiOwed: "العمولات المستحقة",
    kpiOwedHint: "المكتسب ناقص المدفوع",
    emptyTitle: "لا يوجد مسوّقون بعد",
    emptyDescription: "أضف أول مسوّق لبدء تتبّع الإحالات.",
    colAffiliate: "المسوّق",
    colCode: "الكود",
    colCommission: "العمولة",
    colClicks: "النقرات",
    colOrders: "الطلبات",
    colDelivered: "تم التوصيل",
    colConv: "التحويل",
    colEarned: "المكتسب",
    colPaid: "المدفوع",
    colOwed: "المستحقات",
    fixed: "{amount} ثابتة",
    payOnDeliveredShort: "عند التوصيل",
    payOnConfirmedShort: "عند التأكيد",
    pay: "دفع",
    code: "الكود",
    link: "رابط الإحالة",
    signupLink: "رابط التسجيل",
    copiedToast: "تم نسخ {label}.",
    copyAria: "نسخ {label}",
    copyFailed: "تعذّر النسخ. حدّد النص وانسخه يدويًا.",
    deliveredCaption: "{n} تم توصيلها",
    toastActive: "{name} نشط الآن.",
    toastPaused: "تم إيقاف {name} مؤقتًا.",
    toastPaid: "تم دفع {amount} إلى {name}.",
    programSettings: "إعدادات البرنامج",
    programSettingsDesc: "طريقة نسب الإحالات واحتسابها.",
    publicSignup: "صفحة تسجيل عامة",
    publicSignupDesc: "اسمح للمسوّقين بالتقديم بأنفسهم والحصول على كود فورًا.",
    cookieWindow: "مدة تتبّع الإحالة",
    cookieWindowDesc: "الطلبات التي تتم خلال هذا العدد من الأيام بعد النقر تُحتسب للمسوّق.",
    daysOption: "{n} يومًا",
    countDelivered: "احتساب الطلبات التي تم توصيلها فقط",
    countDeliveredDesc: "تُستحق العمولة بعد تأكيد شركة الشحن للتوصيل، وليس عند تأكيد الطلب.",
    topAffiliates: "أفضل المسوّقين",
    topAffiliatesDesc: "حسب الطلبات التي تم توصيلها.",
    nothingToRank: "لا توجد بيانات للترتيب بعد.",
    theirLink: "رابط الإحالة:",
    payTitle: "دفع مستحقات {name}؟",
    payDescription: "سيتم تسجيل {amount} كمدفوعة. أرسل التحويل عبر InstaPay أو فودافون كاش أولًا.",
    markPaid: "تسجيل كمدفوع",
    name: "الاسم",
    namePlaceholder: "مثال: نور — TikTok",
    phone: "رقم الهاتف",
    phoneHint: "يُستخدم للدفعات وتحديثات WhatsApp.",
    referralCode: "كود الإحالة",
    referralCodeHint: "يُنشأ تلقائيًا من الاسم؛ يكتبه العملاء عند الدفع أو يستخدمون رابط الإحالة.",
    regenerate: "إنشاء كود جديد",
    commissionType: "نوع العمولة",
    percentageOfOrder: "نسبة من قيمة الطلب",
    fixedPerOrder: "مبلغ ثابت لكل طلب",
    percentage: "النسبة",
    amountPerOrder: "المبلغ لكل طلب",
    payOn: "استحقاق العمولة عند",
    payOnHint: "التوصيل أكثر أمانًا مع الدفع عند الاستلام — لا عمولة على الطلبات المرتجعة.",
    deliveredOrder: "توصيل الطلب",
    confirmedOrder: "تأكيد الطلب",
    errName: "الاسم مطلوب.",
    errPhone: "رقم الهاتف مطلوب.",
    errCode: "الكود مطلوب.",
    errPercent: "أدخل نسبة أكبر من 0.",
    errAmount: "أدخل مبلغًا صحيحًا.",
    errMaxPercent: "لا يمكن أن تتجاوز النسبة 100%.",
    toastSaved: "تم حفظ المسوّق.",
    toastAdded: "تمت إضافة {name} بالكود {code}.",
    saveAffiliate: "حفظ المسوّق",
  },
} satisfies Messages;
