import type { Messages } from "@/i18n/LocaleContext";

export const AFFILIATE_STRINGS = {
  en: {
    title: "Affiliates",
    description: "Marketers who sell your products for a commission. A commission is earned when the order is delivered and cancelled if it comes back.",
    add: "Add affiliate",

    howTitle: "How it works",
    step1: "Add the marketer",
    step1Desc: "Their name, phone number and what they earn per order.",
    step2: "Send them their link",
    step2Desc: "One link for the store, plus the portal where they follow their orders.",
    step3: "Orders come in through the link",
    step3Desc: "Each order placed through it is recorded in their name.",
    step4: "Pay on delivery",
    step4Desc: "The commission is due once the order is delivered. Pay them, then record it here.",

    tabs: "Affiliates view",
    tabAffiliates: "Affiliates",
    tabCommissions: "Commissions",
    tabPayouts: "Payments",
    kpiDue: "To pay now",
    kpiPending: "Waiting for delivery",
    kpiPaid: "Paid so far",
    kpiActive: "Active affiliates",
    dueCount: "{count} to pay",

    portal: "Affiliate portal",
    portalHint: "One address for all your affiliates: they sign in with their phone and see their links, orders and balance.",
    openPortal: "Open",
    copyLink: "Copy link",

    colAffiliate: "Affiliate",
    colRate: "Commission",
    colOrders: "Orders",
    colPending: "Waiting",
    colDue: "To pay",
    colPaid: "Paid",
    colActions: "Actions",
    perOrder: "{amount} per order",
    paused: "Paused",
    share: "Send link",
    pay: "Pay",
    more: "More actions for {name}",
    viewCommissions: "View commissions",
    edit: "Edit",
    pause: "Pause",
    resume: "Resume",
    remove: "Delete",
    pausedToast: "{name} is paused. Their links stop earning.",
    resumedToast: "{name} is active again.",
    removeTitle: "Delete {name}?",
    removeDescription: "Their link stops working. This cannot be undone.",
    removeConfirm: "Delete",
    removing: "Deleting…",
    removedToast: "Affiliate deleted.",
    hasCommissions: "This affiliate has commissions, so they cannot be deleted. Pause them instead.",

    emptyTitle: "No affiliates yet",
    emptyDescription: "Add a marketer, give them their link, and every delivered order that came through it earns them a commission.",

    createTitle: "Add an affiliate",
    editTitle: "Edit affiliate",
    sectionWho: "Who they are",
    sectionLink: "Their link",
    sectionRate: "What they earn",
    name: "Name",
    phone: "Phone",
    phoneHint: "They sign in to the portal with this number.",
    code: "Code",
    codeHint: "Letters, digits, - and _. It is the end of their link.",
    linkPreview: "Their link",
    type: "Commission type",
    type_percent: "Percentage of the products' value",
    type_fixed: "Fixed amount per order",
    percentValue: "Percentage (%)",
    fixedValue: "Amount per order ({currency})",
    example: "On products worth {base} they earn {amount}.",
    active: "Active",
    activeHint: "A paused affiliate cannot sign in and their links stop earning.",
    notes: "Note",
    notesHint: "Only you see it.",
    saved: "Affiliate saved.",
    codeTaken: "Another affiliate already uses that code.",
    phoneTaken: "Another affiliate already uses that phone number.",
    invalidPhone: "Enter a valid phone number.",

    shareTitle: "Send {name} their link",
    shareDescription: "This is step 2: they need the link to sell and the portal to follow their orders.",
    theirLink: "Their store link",
    theirLinkHint: "Every order placed through it counts for them.",
    portalLink: "Portal",
    portalLinkHint: "They sign in with {phone}.",
    whatsapp: "Send on WhatsApp",
    whatsappMessage:
      "Hello {name}, this is your link to sell our products:\n{link}\n\nFollow your orders and your commission here, signing in with your phone number:\n{portal}",
    done: "Done",

    payTitle: "Pay {name} {amount}?",
    payDescription: "Send the money first, then record it. Their approved commissions become paid.",
    payMethod: "How you paid",
    method_none: "Not specified",
    method_vodafone_cash: "Vodafone Cash",
    method_instapay: "InstaPay",
    method_bank_transfer: "Bank transfer",
    method_cash: "Cash",
    method_other: "Other",
    payNote: "Note",
    payNoteHint: "A reference or transfer number, if you have one.",
    payConfirm: "I paid them",
    paying: "Saving…",
    paidToast: "Payment of {amount} recorded.",
    nothingToPay: "Nothing to pay: no approved commission is waiting.",

    colOrder: "Order",
    colDate: "Date",
    colBase: "Products' value",
    colAmount: "Commission",
    colStatus: "Status",
    status_pending: "Waiting for delivery",
    status_approved: "To pay",
    status_paid: "Paid",
    status_void: "Cancelled",
    statusFilter: "Status",
    anyStatus: "Any status",
    affiliateFilter: "Affiliate",
    anyAffiliate: "All affiliates",
    emptyCommissions: "No commissions yet.",
    emptyCommissionsFiltered: "No commissions match these filters.",
    clearFilters: "Clear filters",

    payoutsFor: "Payments to",
    colMethod: "Method",
    colNote: "Note",
    emptyPayouts: "No payment recorded for this affiliate yet.",
    pickAffiliate: "Add an affiliate to record payments.",
  },
  ar: {
    title: "المسوّقون بالعمولة",
    description: "مسوّقون يبيعون منتجاتك مقابل عمولة. تُستحق العمولة عند تسليم الطلب وتُلغى إذا رجع.",
    add: "إضافة مسوّق",

    howTitle: "الطريقة",
    step1: "أضف المسوّق",
    step1Desc: "اسمه ورقم هاتفه وما يكسبه عن كل طلب.",
    step2: "أرسل له رابطه",
    step2Desc: "رابط واحد للمتجر، ومعه البوابة التي يتابع منها طلباته.",
    step3: "الطلبات تأتي من الرابط",
    step3Desc: "كل طلب يتم من رابطه يُسجَّل باسمه.",
    step4: "ادفع عند التسليم",
    step4Desc: "تُستحق العمولة بعد تسليم الطلب. ادفع له ثم سجّل الدفع هنا.",

    tabs: "طريقة عرض المسوّقين",
    tabAffiliates: "المسوّقون",
    tabCommissions: "العمولات",
    tabPayouts: "المدفوعات",
    kpiDue: "مستحق الدفع الآن",
    kpiPending: "في انتظار التسليم",
    kpiPaid: "المدفوع حتى الآن",
    kpiActive: "مسوّقون نشطون",
    dueCount: "{count} مستحق لهم",

    portal: "بوابة المسوّقين",
    portalHint: "عنوان واحد لكل المسوّقين: يدخلون برقم الهاتف ويرون روابطهم وطلباتهم ورصيدهم.",
    openPortal: "فتح",
    copyLink: "نسخ الرابط",

    colAffiliate: "المسوّق",
    colRate: "العمولة",
    colOrders: "الطلبات",
    colPending: "في الانتظار",
    colDue: "مستحق",
    colPaid: "مدفوع",
    colActions: "الإجراءات",
    perOrder: "{amount} لكل طلب",
    paused: "متوقف",
    share: "إرسال الرابط",
    pay: "دفع",
    more: "إجراءات أخرى لـ {name}",
    viewCommissions: "عرض العمولات",
    edit: "تعديل",
    pause: "إيقاف مؤقت",
    resume: "تفعيل",
    remove: "حذف",
    pausedToast: "تم إيقاف {name}. روابطه لم تعد تكسب عمولة.",
    resumedToast: "تم تفعيل {name} من جديد.",
    removeTitle: "حذف {name}؟",
    removeDescription: "رابطه سيتوقف عن العمل. لا يمكن التراجع عن الحذف.",
    removeConfirm: "حذف",
    removing: "بنمسح…",
    removedToast: "تم حذف المسوّق.",
    hasCommissions: "لهذا المسوّق عمولات مسجّلة، فلا يمكن حذفه. أوقفه مؤقتًا بدلًا من ذلك.",

    emptyTitle: "لا يوجد مسوّقون بعد",
    emptyDescription: "أضف مسوّقًا وأعطه رابطه، وكل طلب مُسلَّم جاء عن طريقه يكسبه عمولة.",

    createTitle: "إضافة مسوّق",
    editTitle: "تعديل المسوّق",
    sectionWho: "بياناته",
    sectionLink: "رابطه",
    sectionRate: "ما يكسبه",
    name: "الاسم",
    phone: "الهاتف",
    phoneHint: "يدخل به إلى البوابة.",
    code: "الكود",
    codeHint: "حروف إنجليزية وأرقام و - و _. يظهر في آخر رابطه.",
    linkPreview: "رابطه",
    type: "نوع العمولة",
    type_percent: "نسبة من قيمة المنتجات",
    type_fixed: "مبلغ ثابت لكل طلب",
    percentValue: "النسبة (%)",
    fixedValue: "المبلغ لكل طلب ({currency})",
    example: "على منتجات قيمتها {base} يكسب {amount}.",
    active: "نشط",
    activeHint: "المسوّق المتوقف لا يستطيع الدخول، وروابطه لا تكسب عمولة.",
    notes: "ملاحظة",
    notesHint: "تظهر لك أنت فقط.",
    saved: "تم حفظ المسوّق.",
    codeTaken: "يوجد مسوّق آخر بنفس الكود.",
    phoneTaken: "يوجد مسوّق آخر بنفس رقم الهاتف.",
    invalidPhone: "اكتب رقم هاتف صحيح.",

    shareTitle: "أرسل إلى {name} رابطه",
    shareDescription: "هذه هي الخطوة 2: يحتاج الرابط ليبيع، والبوابة ليتابع طلباته.",
    theirLink: "رابط المتجر الخاص به",
    theirLinkHint: "كل طلب يتم من هذا الرابط يُحسب له.",
    portalLink: "البوابة",
    portalLinkHint: "يدخل بالرقم {phone}.",
    whatsapp: "إرسال على واتساب",
    whatsappMessage:
      "أهلاً {name}، هذا رابطك لتسويق منتجاتنا:\n{link}\n\nتابع طلباتك وعمولتك من هنا، وادخل برقم هاتفك:\n{portal}",
    done: "تم",

    payTitle: "دفع {amount} إلى {name}؟",
    payDescription: "أرسل المبلغ أولًا ثم سجّله هنا. عمولاته المستحقة تصبح مدفوعة.",
    payMethod: "طريقة الدفع",
    method_none: "غير محددة",
    method_vodafone_cash: "فودافون كاش",
    method_instapay: "إنستاباي",
    method_bank_transfer: "تحويل بنكي",
    method_cash: "نقدًا",
    method_other: "أخرى",
    payNote: "ملاحظة",
    payNoteHint: "رقم مرجعي أو رقم التحويل إن وُجد.",
    payConfirm: "دفعت له",
    paying: "بنحفظ…",
    paidToast: "تم تسجيل دفع {amount}.",
    nothingToPay: "لا يوجد ما يُدفع: لا توجد عمولة مستحقة.",

    colOrder: "الطلب",
    colDate: "التاريخ",
    colBase: "قيمة المنتجات",
    colAmount: "العمولة",
    colStatus: "الحالة",
    status_pending: "في انتظار التسليم",
    status_approved: "مستحقة",
    status_paid: "مدفوعة",
    status_void: "ملغاة",
    statusFilter: "الحالة",
    anyStatus: "كل الحالات",
    affiliateFilter: "المسوّق",
    anyAffiliate: "كل المسوّقين",
    emptyCommissions: "لا توجد عمولات بعد.",
    emptyCommissionsFiltered: "لا توجد عمولات تطابق هذه التصفية.",
    clearFilters: "إلغاء التصفية",

    payoutsFor: "المدفوعات إلى",
    colMethod: "الطريقة",
    colNote: "ملاحظة",
    emptyPayouts: "لم يُسجَّل دفع لهذا المسوّق بعد.",
    pickAffiliate: "أضف مسوّقًا لتسجّل المدفوعات.",
  },
} satisfies Messages;

/** How the merchant paid: the stored value, and the string key that names it. */
export const PAYOUT_METHODS = ["vodafone_cash", "instapay", "bank_transfer", "cash", "other"] as const;
export type PayoutMethod = (typeof PAYOUT_METHODS)[number];
