import type { Messages } from "@/i18n/LocaleContext";

/** Marketing → Affiliates (SPEC §20.3). Arabic is the merchant's Egyptian, second person, short. */
export const AFFILIATE_STRINGS = {
  en: {
    title: "Affiliates",
    description: "Marketers who sell your products for a commission. A commission is earned when the order is delivered and cancelled if it comes back.",
    add: "Add affiliate",
    tools: "Tools",

    howTitle: "How it works",
    step1: "Add the marketer",
    step1Desc: "Their name, phone number and what they earn per order.",
    step2: "Send them their link",
    step2Desc: "One link for the store, plus the portal where they follow their orders.",
    step3: "Orders come in through the link",
    step3Desc: "Each order placed through it is recorded in their name.",
    step4: "Pay on delivery",
    step4Desc: "The commission is due once the order is delivered. Pay them, then record it here.",

    tabs: "Affiliates view",
    tabAffiliates: "Affiliates",
    tabCommissions: "Commissions",
    tabPayouts: "Payments",
    kpiDue: "To pay now",
    kpiPending: "Waiting for delivery",
    kpiPaid: "Paid so far",
    kpiActive: "Active affiliates",
    dueCount_one: "1 affiliate to pay",
    dueCount_other: "{n} affiliates to pay",

    portal: "Affiliate portal",
    portalHint: "One address for all your affiliates: they sign in with their phone and see their links, orders and balance.",
    openPortal: "Open the affiliate portal",
    copyPortal: "Copy the portal link",
    portalCopied: "The portal link is copied",
    copyLink: "Copy link",
    linkCopied: "Their link is copied",

    searchLabel: "Search affiliates",
    searchPlaceholder: "Name, phone or code",
    noMatchTitle: "No affiliate matches",
    noMatchHint: "Try another name, phone number or code.",
    showAll: "Show all",

    colAffiliate: "Affiliate",
    colRate: "Commission",
    colOrders: "Orders",
    colPending: "Waiting",
    colDue: "To pay",
    colPaid: "Paid",
    colActions: "Actions",
    perOrder: "{amount} per order",
    percentRate: "{n}%",
    paused: "Paused",
    active: "Active",
    share: "Send link",
    pay: "Pay",
    payAmount: "Pay {amount}",
    more: "More actions for {name}",
    peek: "Preview {name}",
    viewCommissions: "View commissions",
    viewPayouts: "View payments",
    edit: "Edit",
    pause: "Pause",
    resume: "Resume",
    remove: "Delete",
    call: "Call",
    whatsappChat: "WhatsApp",
    pausedToast: "{name} is paused. Their link stops earning.",
    resumedToast: "{name} is active again.",
    removeTitle: "Delete {name}?",
    removeDescription: "Their link stops working and they can no longer sign in to the portal. This cannot be undone.",
    removeConfirm: "Delete affiliate",
    removing: "Deleting…",
    removedToast: "Affiliate deleted.",
    hasCommissions: "This affiliate has commissions, so they cannot be deleted. Pause them instead.",

    emptyTitle: "No affiliates yet",
    emptyDescription: "Add a marketer, give them their link, and every delivered order that came through it earns them a commission.",

    qlTotals: "Their numbers",
    qlLinks: "Their links",
    qlNote: "Your note",
    qlSince: "Added on {date}",

    createTitle: "Add an affiliate",
    editTitle: "Edit affiliate",
    sectionWho: "Who they are",
    sectionLink: "Their link",
    sectionRate: "What they earn",
    name: "Name",
    nameError: "Write the marketer's name (2 letters at least).",
    phone: "Phone",
    phoneHint: "They sign in to the portal with this number.",
    phoneError: "Write their mobile number.",
    code: "Code",
    codeHint: "Letters, digits, - and _. It is the end of their link.",
    codeError: "Write a code of 2 characters at least: English letters, digits, - or _.",
    linkPreview: "Their link",
    type: "Commission type",
    type_percent: "Percent",
    type_fixed: "Fixed amount",
    typeHint_percent: "A percentage of the products' value in each order.",
    typeHint_fixed: "The same amount for every order.",
    percentValue: "Percentage (%)",
    percentError: "Write a percentage above 0, up to 100.",
    fixedValue: "Amount per order ({currency})",
    fixedError: "Write an amount above zero.",
    example: "On products worth {base} they earn {amount}.",
    activeLabel: "Active",
    activeHint: "A paused affiliate cannot sign in and their links stop earning.",
    notes: "Note",
    notesHint: "Only you see it.",
    save: "Save",
    saveNew: "Add and send the link",
    saving: "Saving…",
    cancel: "Cancel",
    saved: "Affiliate saved.",
    fixFields: "Check the highlighted fields.",
    codeTaken: "Another affiliate already uses that code. Choose a different one.",
    phoneTaken: "Another affiliate already uses that phone number.",
    invalidPhone: "This is not a valid phone number. Write it with the country code, like +201001234567.",

    shareTitle: "Send {name} their link",
    shareDescription: "They need the link to sell, and the portal to follow their orders.",
    theirLink: "Their store link",
    theirLinkHint: "Every order placed through it counts for them.",
    portalLink: "Portal",
    portalLinkHint: "They sign in with {phone}.",
    whatsapp: "Send on WhatsApp",
    whatsappMessage:
      "Hello {name}, this is your link to sell our products:\n{link}\n\nFollow your orders and your commission here, signing in with your phone number:\n{portal}",
    done: "Done",

    payTitle: "Pay {name} {amount}?",
    payDescription: "Send the money first, then record it here. Their commissions that are due become paid — this cannot be undone.",
    payMethod: "How you paid",
    method_none: "Not specified",
    method_vodafone_cash: "Vodafone Cash",
    method_instapay: "InstaPay",
    method_bank_transfer: "Bank transfer",
    method_cash: "Cash",
    method_other: "Other",
    payNote: "Note",
    payNoteHint: "A reference or transfer number, if you have one.",
    payConfirm: "I paid them",
    paying: "Saving…",
    paidToast: "Payment of {amount} recorded.",
    nothingToPay: "Nothing to pay: no commission is due yet.",

    colOrder: "Order",
    colDate: "Date",
    colBase: "Products' value",
    colAmount: "Commission",
    colStatus: "Status",
    openOrder: "Open order {number}",
    baseOf: "On products worth {amount}",
    status_pending: "Waiting for delivery",
    status_approved: "To pay",
    status_paid: "Paid",
    status_void: "Cancelled",
    statusFilter: "Commissions by status",
    anyStatus: "All",
    affiliateFilter: "Affiliate",
    anyAffiliate: "All affiliates",
    emptyCommissions: "No commissions yet",
    emptyCommissionsHint: "When an order comes in through an affiliate's link, its commission shows up here.",
    emptyCommissionsFiltered: "No commissions match",
    clearFilters: "Show all commissions",

    payoutsFor: "Payments to",
    colMethod: "Method",
    colNote: "Note",
    emptyPayouts: "No payment recorded for {name} yet",
    emptyPayoutsHint: "When you pay them what is due and record it, the payment shows up here.",
    pickAffiliate: "Add an affiliate to record payments.",
  },
  ar: {
    title: "المسوّقون بالعمولة",
    description: "مسوّقين بيبيعوا منتجاتك بعمولة. العمولة بتستحق لما الأوردر يتسلّم، وبتتلغي لو رجع.",
    add: "ضيف مسوّق",
    tools: "أدوات",

    howTitle: "بتمشي إزاي",
    step1: "ضيف المسوّق",
    step1Desc: "اسمه ورقم موبايله وبياخد كام على كل أوردر.",
    step2: "ابعتله اللينك بتاعه",
    step2Desc: "لينك واحد للمتجر، ومعاه البوابة اللي بيتابع منها أوردراته.",
    step3: "الأوردرات بتيجي من اللينك",
    step3Desc: "كل أوردر يتعمل من اللينك بيتسجّل باسمه.",
    step4: "ادفعله بعد التسليم",
    step4Desc: "العمولة بتستحق بعد ما الأوردر يتسلّم. ادفعله وسجّل الدفع هنا.",

    tabs: "طريقة عرض المسوّقين",
    tabAffiliates: "المسوّقين",
    tabCommissions: "العمولات",
    tabPayouts: "المدفوعات",
    kpiDue: "مستحق الدفع دلوقتي",
    kpiPending: "مستني التسليم",
    kpiPaid: "اتدفع لحد دلوقتي",
    kpiActive: "مسوّقين شغّالين",
    dueCount_one: "مسوّق واحد ليه فلوس",
    dueCount_two: "مسوّقين ليهم فلوس",
    dueCount_few: "{n} مسوّقين ليهم فلوس",
    dueCount_other: "{n} مسوّق ليهم فلوس",

    portal: "بوابة المسوّقين",
    portalHint: "عنوان واحد لكل المسوّقين: بيدخلوا برقم الموبايل ويشوفوا لينكاتهم وأوردراتهم ورصيدهم.",
    openPortal: "افتح بوابة المسوّقين",
    copyPortal: "انسخ لينك البوابة",
    portalCopied: "لينك البوابة اتنسخ",
    copyLink: "انسخ اللينك",
    linkCopied: "اللينك بتاعه اتنسخ",

    searchLabel: "دوّر في المسوّقين",
    searchPlaceholder: "الاسم أو الموبايل أو الكود",
    noMatchTitle: "مفيش مسوّق بالشكل ده",
    noMatchHint: "جرّب اسم أو رقم موبايل أو كود تاني.",
    showAll: "اعرض الكل",

    colAffiliate: "المسوّق",
    colRate: "العمولة",
    colOrders: "الأوردرات",
    colPending: "مستني",
    colDue: "مستحق",
    colPaid: "اتدفع",
    colActions: "الإجراءات",
    perOrder: "{amount} على كل أوردر",
    percentRate: "{n}٪",
    paused: "واقف",
    active: "شغّال",
    share: "ابعت اللينك",
    pay: "ادفع",
    payAmount: "ادفع {amount}",
    more: "إجراءات {name}",
    peek: "معاينة {name}",
    viewCommissions: "شوف عمولاته",
    viewPayouts: "شوف مدفوعاته",
    edit: "عدّل",
    pause: "وقّفه مؤقتًا",
    resume: "شغّله تاني",
    remove: "امسح",
    call: "اتصل",
    whatsappChat: "واتساب",
    pausedToast: "{name} اتوقّف. اللينك بتاعه مش هيكسب عمولة.",
    resumedToast: "{name} رجع شغّال.",
    removeTitle: "تمسح {name}؟",
    removeDescription: "اللينك بتاعه هيقف ومش هيعرف يدخل البوابة. المسح مالوش رجوع.",
    removeConfirm: "امسح المسوّق",
    removing: "بنمسح…",
    removedToast: "المسوّق اتمسح.",
    hasCommissions: "المسوّق ده عليه عمولات متسجّلة، فمينفعش يتمسح. وقّفه مؤقتًا بدل كده.",

    emptyTitle: "لسه مفيش مسوّقين",
    emptyDescription: "ضيف مسوّق وادّيه اللينك بتاعه، وكل أوردر يتسلّم جاي منه يكسّبه عمولة.",

    qlTotals: "أرقامه",
    qlLinks: "لينكاته",
    qlNote: "ملاحظتك",
    qlSince: "اتضاف يوم {date}",

    createTitle: "ضيف مسوّق",
    editTitle: "عدّل المسوّق",
    sectionWho: "بياناته",
    sectionLink: "اللينك بتاعه",
    sectionRate: "بياخد كام",
    name: "الاسم",
    nameError: "اكتب اسم المسوّق (حرفين على الأقل).",
    phone: "الموبايل",
    phoneHint: "بيدخل بيه على البوابة.",
    phoneError: "اكتب رقم موبايله.",
    code: "الكود",
    codeHint: "حروف إنجليزي وأرقام و - و _. بيظهر في آخر اللينك بتاعه.",
    codeError: "اكتب كود من حرفين على الأقل: حروف إنجليزي أو أرقام أو - أو _.",
    linkPreview: "اللينك بتاعه",
    type: "نوع العمولة",
    type_percent: "نسبة",
    type_fixed: "مبلغ ثابت",
    typeHint_percent: "نسبة من قيمة المنتجات في كل أوردر.",
    typeHint_fixed: "نفس المبلغ على كل أوردر.",
    percentValue: "النسبة (٪)",
    percentError: "اكتب نسبة أكبر من صفر ولحد ١٠٠.",
    fixedValue: "المبلغ على كل أوردر ({currency})",
    fixedError: "اكتب مبلغ أكبر من صفر.",
    example: "على منتجات قيمتها {base} بياخد {amount}.",
    activeLabel: "شغّال",
    activeHint: "المسوّق الواقف مش بيعرف يدخل، واللينك بتاعه مش بيكسب عمولة.",
    notes: "ملاحظة",
    notesHint: "بتظهرلك إنت بس.",
    save: "احفظ",
    saveNew: "ضيفه وابعت اللينك",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    saved: "المسوّق اتحفظ.",
    fixFields: "راجع الخانات المتعلّم عليها.",
    codeTaken: "فيه مسوّق تاني بنفس الكود. اختار كود غيره.",
    phoneTaken: "فيه مسوّق تاني بنفس رقم الموبايل.",
    invalidPhone: "ده مش رقم موبايل صحيح. اكتبه بكود الدولة، زي ‎+201001234567.",

    shareTitle: "ابعت لـ {name} اللينك بتاعه",
    shareDescription: "محتاج اللينك عشان يبيع، والبوابة عشان يتابع أوردراته.",
    theirLink: "لينك المتجر بتاعه",
    theirLinkHint: "كل أوردر يتعمل من اللينك ده بيتحسبله.",
    portalLink: "البوابة",
    portalLinkHint: "بيدخل بالرقم {phone}.",
    whatsapp: "ابعت على واتساب",
    whatsappMessage:
      "أهلاً {name}، ده اللينك بتاعك لتسويق منتجاتنا:\n{link}\n\nتابع أوردراتك وعمولتك من هنا، وادخل برقم موبايلك:\n{portal}",
    done: "تمام",

    payTitle: "تدفع {amount} لـ {name}؟",
    payDescription: "ابعتله الفلوس الأول وبعدين سجّلها هنا. عمولاته المستحقة هتبقى مدفوعة — وده مالوش رجوع.",
    payMethod: "دفعت إزاي",
    method_none: "مش محدّدة",
    method_vodafone_cash: "فودافون كاش",
    method_instapay: "إنستاباي",
    method_bank_transfer: "تحويل بنكي",
    method_cash: "كاش",
    method_other: "طريقة تانية",
    payNote: "ملاحظة",
    payNoteHint: "رقم مرجعي أو رقم التحويل لو معاك.",
    payConfirm: "دفعتله",
    paying: "بنحفظ…",
    paidToast: "اتسجّل دفع {amount}.",
    nothingToPay: "مفيش حاجة تتدفع: لسه مفيش عمولة مستحقة.",

    colOrder: "الأوردر",
    colDate: "التاريخ",
    colBase: "قيمة المنتجات",
    colAmount: "العمولة",
    colStatus: "الحالة",
    openOrder: "افتح الأوردر {number}",
    baseOf: "على منتجات بـ {amount}",
    status_pending: "مستني التسليم",
    status_approved: "مستحقة",
    status_paid: "اتدفعت",
    status_void: "اتلغت",
    statusFilter: "العمولات بالحالة",
    anyStatus: "الكل",
    affiliateFilter: "المسوّق",
    anyAffiliate: "كل المسوّقين",
    emptyCommissions: "لسه مفيش عمولات",
    emptyCommissionsHint: "لما أوردر ييجي من لينك مسوّق، عمولته هتظهر هنا.",
    emptyCommissionsFiltered: "مفيش عمولات بالشكل ده",
    clearFilters: "اعرض كل العمولات",

    payoutsFor: "مدفوعات",
    colMethod: "الطريقة",
    colNote: "ملاحظة",
    emptyPayouts: "لسه ما سجّلتش دفع لـ {name}",
    emptyPayoutsHint: "لما تدفعله المستحق وتسجّله، الدفع هيظهر هنا.",
    pickAffiliate: "ضيف مسوّق عشان تسجّل مدفوعاته.",
  },
} satisfies Messages;

export type AffiliateStrings = (typeof AFFILIATE_STRINGS)["en"];

/** How the merchant paid: the stored value, and the string key that names it. */
export const PAYOUT_METHODS = ["vodafone_cash", "instapay", "bank_transfer", "cash", "other"] as const;
export type PayoutMethod = (typeof PAYOUT_METHODS)[number];
