import type { StoreCreditTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Store credit balances, the credit card on a customer's page and
 * the refund dialog's "where does it go" choice (handoff 204, with the
 * gift-card and points payments of 201 and 203). Arabic is the merchant's
 * Egyptian, with the handoff's wording.
 */
export const STORE_CREDIT_STRINGS = {
  en: {
    // page
    title: "Store credit balances",
    description: "Money your customers hold at the store. You give it from a customer's page, or by refunding an order as store credit.",
    statOutstanding: "Total credit customers hold",
    statCustomers: "Customers with credit",
    spendTitle: "Customers can spend credit at checkout",
    spendHintOn: "A signed-in customer can pay with their credit, with cash on delivery or an online payment.",
    spendHintOff: "Off: balances stay as they are, but checkout doesn't take them.",
    spendSavedOn: "Customers can spend their credit at checkout.",
    spendSavedOff: "Checkout no longer takes store credit.",
    accountsOff: "Customer accounts are off, so nobody can spend their credit: spending needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    searchLabel: "Search customers with credit",
    searchPlaceholder: "Name, phone or email",
    clearSearch: "Clear search",
    colCustomer: "Customer",
    colBalance: "Credit",
    noName: "No name",
    emptyTitle: "No customer holds credit",
    emptyHint: "Open a customer and choose “Add credit”, or refund an order as store credit from its page.",
    openCustomers: "Open customers",
    noMatchTitle: "No customers match",
    noMatchHint: "Try another name, phone number or email.",
    showAll: "Show all",
    capped: "Showing the {n} biggest balances.",
    customerGets: "A customer with credit pays from it at checkout. You give it from their page, or by refunding an order as credit.",
    colContact: "Contact",
    peek: "Preview the credit of {name}",
    menuLabel: "Actions for {name}",
    menuOpen: "Open the customer",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopy: "Copy the number",
    copied: "The customer's number is copied",
    qlOpen: "Open the customer",
    qlHint: "Credit is added or taken on the customer's page.",
    qlAfter: "Balance after: {amount}",
    qlOrder: "Open the order",
    qlFailed: "We couldn't load this customer's credit history.",
    // customer card
    cardTitle: "Store credit",
    cardHint: "Money this customer holds at your store and spends at checkout.",
    addCredit: "Add credit",
    takeCredit: "Take credit",
    history: "Credit history",
    historyEmpty: "No credit given or spent yet.",
    kind_grant: "Added by your team",
    kind_adjust: "Taken off by your team",
    kind_refund_credit: "Order refunded as credit",
    kind_redeem: "Spent on an order",
    kind_hold: "Held for an unpaid order",
    kind_release: "Given back",
    kind_refund: "Back from a refund",
    kind_referral: "Reward for inviting a friend",
    // add / take dialog
    addTitle: "Add store credit",
    takeTitle: "Take store credit",
    dialogDescription: "Now: {balance}",
    amount: "Amount",
    amountError: "Enter an amount above zero.",
    tooMuch: "The balance is {balance}: that is the most you can take.",
    newBalance: "New balance: {balance}",
    note: "Reason",
    noteHint: "Kept with the change in this history.",
    noteError: "Write the reason for this change.",
    cancel: "Cancel",
    addSave: "Add credit",
    takeSave: "Take credit",
    saving: "Saving…",
    added: "{amount} added to the customer's credit.",
    taken: "{amount} taken off the customer's credit.",
    // refund dialog
    destination: "Where does the refund go?",
    toMoney: "Refund money",
    toMoneyHintGateway: "Back to the customer's card or wallet through the gateway.",
    toMoneyHintManual: "You hand it back yourself (cash or transfer); this records it.",
    toCredit: "Refund as store credit",
    toCreditHint: "Goes onto the customer's credit to spend on a next order — up to {max}",
    toGiftCard: "Back to gift card {card}",
    toGiftCardPlain: "Back to the gift card",
    toGiftCardHint: "The part this order paid with the card — up to {max}",
    toPoints: "Back as loyalty points",
    toPointsHint: "The part this order paid with points — up to {max}",
    toCreditPayment: "Back to store credit",
    toCreditPaymentHint: "The part this order paid with store credit — up to {max}",
    reasonRequired: "Write the reason: a refund to store credit is saved with it.",
    noCustomer: "This order has no customer to give the credit to.",
    otherCurrency: "Store credit is in your store's own currency only, and this order is in another one.",
    // payments list
    paymentPoints: "Loyalty points",
    paymentCredit: "Store credit",
  },
  ar: {
    // page
    title: "أرصدة العملاء",
    description: "فلوس عملاءك شايلينها عندك في المتجر. بتضيفها من صفحة العميل، أو لما ترجّع أوردر كرصيد في المتجر.",
    statOutstanding: "إجمالي رصيد العملاء",
    statCustomers: "عملاء عندهم رصيد",
    spendTitle: "العملاء يقدروا يستخدموا رصيدهم في الدفع",
    spendHintOn: "العميل اللي مسجّل دخول يقدر يدفع من رصيده، مع الدفع عند الاستلام أو الدفع أونلاين.",
    spendHintOff: "مقفول: الأرصدة فاضلة زي ما هي، بس صفحة الدفع مش بتقبلها.",
    spendSavedOn: "العملاء يقدروا يستخدموا رصيدهم في الدفع.",
    spendSavedOff: "صفحة الدفع مبقتش تقبل رصيد المتجر.",
    accountsOff: "حسابات العملاء مقفولة، فمحدش هيقدر يصرف رصيده: الصرف محتاج العميل يسجّل دخول.",
    accountsOffAction: "شغّل حسابات العملاء",
    searchLabel: "دوّر في العملاء اللي عندهم رصيد",
    searchPlaceholder: "الاسم أو الموبايل أو الإيميل",
    clearSearch: "امسح البحث",
    colCustomer: "العميل",
    colBalance: "الرصيد",
    noName: "من غير اسم",
    emptyTitle: "مفيش عملاء عندهم رصيد",
    emptyHint: "افتح صفحة عميل واختار «إضافة رصيد»، أو رجّع أوردر كرصيد في المتجر من صفحته.",
    openCustomers: "افتح العملاء",
    noMatchTitle: "مفيش عملاء بالشكل ده",
    noMatchHint: "جرّب اسم أو رقم موبايل أو إيميل تاني.",
    showAll: "اعرض الكل",
    capped: "معروض أكبر {n} رصيد.",
    customerGets: "العميل اللي عنده رصيد بيدفع منه في صفحة الدفع. بتضيفه من صفحته، أو لما ترجّع أوردر كرصيد.",
    colContact: "التواصل",
    peek: "معاينة رصيد {name}",
    menuLabel: "إجراءات {name}",
    menuOpen: "افتح العميل",
    menuCall: "اتصل",
    menuWhatsapp: "واتساب",
    menuCopy: "انسخ الرقم",
    copied: "رقم العميل اتنسخ",
    qlOpen: "افتح صفحة العميل",
    qlHint: "الرصيد بيتزوّد أو يتخصم من صفحة العميل.",
    qlAfter: "الرصيد بعدها: {amount}",
    qlOrder: "افتح الأوردر",
    qlFailed: "معرفناش نحمّل حركة رصيد العميل ده.",
    // customer card
    cardTitle: "رصيد المتجر",
    cardHint: "فلوس العميل ده شايلها عندك في المتجر وبيصرفها في صفحة الدفع.",
    addCredit: "إضافة رصيد",
    takeCredit: "خصم رصيد",
    history: "حركة الرصيد",
    historyEmpty: "لسه مفيش رصيد اتضاف أو اتصرف.",
    kind_grant: "إضافة من فريقك",
    kind_adjust: "خصم من فريقك",
    kind_refund_credit: "أوردر اترجّع كرصيد",
    kind_redeem: "اتصرف في أوردر",
    kind_hold: "محجوز لأوردر لسه ما اتدفعش",
    kind_release: "رجع للعميل",
    kind_refund: "رجع من استرداد",
    kind_referral: "مكافأة دعوة صاحب",
    // add / take dialog
    addTitle: "إضافة رصيد",
    takeTitle: "خصم رصيد",
    dialogDescription: "دلوقتي: {balance}",
    amount: "المبلغ",
    amountError: "اكتب مبلغ أكبر من صفر.",
    tooMuch: "الرصيد {balance}: ده أقصى حاجة تقدر تخصمها.",
    newBalance: "الرصيد الجديد: {balance}",
    note: "السبب",
    noteHint: "بيتحفظ مع التعديل في حركة الرصيد هنا.",
    noteError: "اكتب سبب التعديل.",
    cancel: "إلغاء",
    addSave: "ضيف الرصيد",
    takeSave: "اخصم الرصيد",
    saving: "بنحفظ…",
    added: "اتضاف {amount} لرصيد العميل.",
    taken: "اتخصم {amount} من رصيد العميل.",
    // refund dialog
    destination: "الترجيع يروح فين؟",
    toMoney: "ترجيع فلوس",
    toMoneyHintGateway: "بترجع لكارت أو محفظة العميل عن طريق بوابة الدفع.",
    toMoneyHintManual: "بترجّعها إنت بنفسك (كاش أو تحويل)، وده بيسجّلها.",
    toCredit: "ترجيع كرصيد في المتجر",
    toCreditHint: "بيتضاف لرصيد العميل يصرفه في أوردر جاي — لحد {max}",
    toGiftCard: "يرجع لكارت الهدية {card}",
    toGiftCardPlain: "يرجع لكارت الهدية",
    toGiftCardHint: "الجزء اللي الأوردر ده دفعه بالكارت — لحد {max}",
    toPoints: "يرجع نقط ولاء",
    toPointsHint: "الجزء اللي الأوردر ده دفعه بالنقط — لحد {max}",
    toCreditPayment: "يرجع لرصيد المتجر",
    toCreditPaymentHint: "الجزء اللي الأوردر ده دفعه من رصيد المتجر — لحد {max}",
    reasonRequired: "اكتب السبب: الترجيع كرصيد بيتحفظ معاه.",
    noCustomer: "الأوردر ده مالوش عميل يتضاف له الرصيد.",
    otherCurrency: "رصيد المتجر بعملة متجرك بس، والأوردر ده بعملة تانية.",
    // payments list
    paymentPoints: "نقط ولاء",
    paymentCredit: "رصيد المتجر",
  },
} satisfies Messages;

export type StoreCreditStrings = (typeof STORE_CREDIT_STRINGS)["en"];

export const STORE_CREDIT_KIND_KEY: Record<StoreCreditTransactionKind, keyof StoreCreditStrings> = {
  grant: "kind_grant",
  adjust: "kind_adjust",
  refund_credit: "kind_refund_credit",
  redeem: "kind_redeem",
  hold: "kind_hold",
  release: "kind_release",
  refund: "kind_refund",
  referral: "kind_referral",
};
