import type { StoreCreditTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Store credit balances, the credit card on a customer's page and
 * the refund dialog's "where does it go" choice (with the gift-card and points
 * payments). Arabic is formal, as the rest of the dashboard.
 */
export const STORE_CREDIT_STRINGS = {
  en: {
    // page
    title: "Store credit balances",
    description: "Money your customers hold at the store. You give it from a customer's page, or by refunding an order as store credit.",
    statOutstanding: "Total credit customers hold",
    statCustomers: "Customers with credit",
    spendTitle: "Customers can spend credit at checkout",
    spendHintOn: "A signed-in customer can pay with their credit, with cash on delivery.",
    spendHintOff: "Off: balances stay as they are, but checkout doesn't take them.",
    spendSavedOn: "Customers can spend their credit at checkout.",
    spendSavedOff: "Checkout no longer takes store credit.",
    accountsOff: "Customer accounts are off, so nobody can spend their credit: spending needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    searchLabel: "Search customers with credit",
    searchPlaceholder: "Name, phone or email",
    clearSearch: "Clear search",
    colCustomer: "Customer",
    colBalance: "Credit",
    noName: "No name",
    emptyTitle: "No customer holds credit",
    emptyHint: "Open a customer and choose “Add credit”, or refund an order as store credit from its page.",
    openCustomers: "Open customers",
    noMatchTitle: "No customers match",
    noMatchHint: "Try another name, phone number or email.",
    showAll: "Show all",
    capped: "Showing the {n} biggest balances.",
    customerGets: "A customer with credit pays from it at checkout. You give it from their page, or by refunding an order as credit.",
    colContact: "Contact",
    peek: "Preview the credit of {name}",
    menuLabel: "Actions for {name}",
    menuOpen: "Open the customer",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopy: "Copy the number",
    copied: "The customer's number is copied",
    qlOpen: "Open the customer",
    qlHint: "Credit is added or taken on the customer's page.",
    qlAfter: "Balance after: {amount}",
    qlOrder: "Open the order",
    qlFailed: "We couldn't load this customer's credit history.",
    // customer card
    cardTitle: "Store credit",
    cardHint: "Money this customer holds at your store and spends at checkout.",
    addCredit: "Add credit",
    takeCredit: "Take credit",
    history: "Credit history",
    historyEmpty: "No credit given or spent yet.",
    kind_grant: "Added by your team",
    kind_adjust: "Taken off by your team",
    kind_refund_credit: "Order refunded as credit",
    kind_redeem: "Spent on an order",
    kind_hold: "Held for an unpaid order",
    kind_release: "Given back",
    kind_refund: "Back from a refund",
    kind_referral: "Reward for inviting a friend",
    // add / take dialog
    addTitle: "Add store credit",
    takeTitle: "Take store credit",
    dialogDescription: "Now: {balance}",
    amount: "Amount",
    amountError: "Enter an amount above zero.",
    tooMuch: "The balance is {balance}: that is the most you can take.",
    newBalance: "New balance: {balance}",
    note: "Reason",
    noteHint: "Kept with the change in this history.",
    noteError: "Write the reason for this change.",
    cancel: "Cancel",
    addSave: "Add credit",
    takeSave: "Take credit",
    saving: "Saving…",
    added: "{amount} added to the customer's credit.",
    taken: "{amount} taken off the customer's credit.",
    // refund dialog
    destination: "Where does the refund go?",
    toMoney: "Refund money",
    toMoneyHintGateway: "Back to the customer's card or wallet through the gateway.",
    toMoneyHintManual: "You hand it back yourself (cash or transfer); this records it.",
    toCredit: "Refund as store credit",
    toCreditHint: "Goes onto the customer's credit to spend on a next order, up to {max}",
    toGiftCard: "Back to gift card {card}",
    toGiftCardPlain: "Back to the gift card",
    toGiftCardHint: "The part this order paid with the card, up to {max}",
    toPoints: "Back as loyalty points",
    toPointsHint: "The part this order paid with points, up to {max}",
    toCreditPayment: "Back to store credit",
    toCreditPaymentHint: "The part this order paid with store credit, up to {max}",
    reasonRequired: "Write the reason: a refund to store credit is saved with it.",
    noCustomer: "This order has no customer to give the credit to.",
    otherCurrency: "Store credit is in your store's own currency only, and this order is in another one.",
    // payments list
    paymentPoints: "Loyalty points",
    paymentCredit: "Store credit",
  },
  ar: {
    // page
    title: "أرصدة العملاء",
    description: "مبالغ يحتفظ بها عملاؤك لديك في المتجر. تضيفها من صفحة العميل، أو عند استرداد طلب في صورة رصيد في المتجر.",
    statOutstanding: "إجمالي رصيد العملاء",
    statCustomers: "عملاء لديهم رصيد",
    spendTitle: "يمكن للعملاء استخدام رصيدهم في الدفع",
    spendHintOn: "العميل الذي سجّل الدخول يمكنه الدفع من رصيده، مع الدفع عند الاستلام.",
    spendHintOff: "متوقف: الأرصدة تبقى كما هي، لكن صفحة الدفع لا تقبلها.",
    spendSavedOn: "يمكن للعملاء استخدام رصيدهم في الدفع.",
    spendSavedOff: "صفحة الدفع لم تعد تقبل رصيد المتجر.",
    accountsOff: "حسابات العملاء متوقفة، لذلك لن يستطيع أحد استخدام رصيده: الاستخدام يتطلب تسجيل دخول العميل.",
    accountsOffAction: "تفعيل حسابات العملاء",
    searchLabel: "البحث في العملاء الذين لديهم رصيد",
    searchPlaceholder: "الاسم أو رقم الهاتف أو البريد الإلكتروني",
    clearSearch: "مسح البحث",
    colCustomer: "العميل",
    colBalance: "الرصيد",
    noName: "بدون اسم",
    emptyTitle: "لا يوجد عملاء لديهم رصيد",
    emptyHint: "افتح صفحة عميل واختر «إضافة رصيد»، أو استرد طلبًا في صورة رصيد في المتجر من صفحته.",
    openCustomers: "فتح العملاء",
    noMatchTitle: "لا يوجد عملاء مطابقون",
    noMatchHint: "جرّب اسمًا أو رقم هاتف أو بريدًا إلكترونيًا آخر.",
    showAll: "عرض الكل",
    capped: "يُعرض أكبر {n} رصيد.",
    customerGets: "العميل الذي لديه رصيد يدفع منه في صفحة الدفع. تضيفه من صفحته، أو عند استرداد طلب في صورة رصيد.",
    colContact: "التواصل",
    peek: "معاينة رصيد {name}",
    menuLabel: "إجراءات {name}",
    menuOpen: "فتح العميل",
    menuCall: "اتصال",
    menuWhatsapp: "واتساب",
    menuCopy: "نسخ الرقم",
    copied: "تم نسخ رقم العميل",
    qlOpen: "فتح صفحة العميل",
    qlHint: "يُضاف الرصيد أو يُخصم من صفحة العميل.",
    qlAfter: "الرصيد بعدها: {amount}",
    qlOrder: "فتح الطلب",
    qlFailed: "تعذّر تحميل حركة رصيد هذا العميل.",
    // customer card
    cardTitle: "رصيد المتجر",
    cardHint: "مبلغ يحتفظ به هذا العميل لديك في المتجر ويستخدمه في صفحة الدفع.",
    addCredit: "إضافة رصيد",
    takeCredit: "خصم رصيد",
    history: "حركة الرصيد",
    historyEmpty: "لم يُضف رصيد أو يُستخدم بعد.",
    kind_grant: "إضافة من فريقك",
    kind_adjust: "خصم من فريقك",
    kind_refund_credit: "طلب استُرد في صورة رصيد",
    kind_redeem: "استُخدم في طلب",
    kind_hold: "محجوز لطلب لم يُدفع بعد",
    kind_release: "أُعيد إلى العميل",
    kind_refund: "أُعيد من استرداد",
    kind_referral: "مكافأة دعوة صديق",
    // add / take dialog
    addTitle: "إضافة رصيد",
    takeTitle: "خصم رصيد",
    dialogDescription: "الآن: {balance}",
    amount: "المبلغ",
    amountError: "أدخل مبلغًا أكبر من صفر.",
    tooMuch: "الرصيد {balance}: هذا أقصى ما يمكن خصمه.",
    newBalance: "الرصيد الجديد: {balance}",
    note: "السبب",
    noteHint: "يُحفظ مع التعديل في حركة الرصيد هنا.",
    noteError: "أدخل سبب التعديل.",
    cancel: "إلغاء",
    addSave: "إضافة الرصيد",
    takeSave: "خصم الرصيد",
    saving: "جارٍ الحفظ…",
    added: "تمت إضافة {amount} إلى رصيد العميل.",
    taken: "تم خصم {amount} من رصيد العميل.",
    // refund dialog
    destination: "إلى أين يذهب الاسترداد؟",
    toMoney: "استرداد نقدي",
    toMoneyHintGateway: "يعود إلى بطاقة العميل أو محفظته عبر بوابة الدفع.",
    toMoneyHintManual: "تعيده أنت بنفسك (نقدًا أو بتحويل)، وهذا يسجّله.",
    toCredit: "استرداد في صورة رصيد في المتجر",
    toCreditHint: "يُضاف إلى رصيد العميل ليستخدمه في طلب قادم، حتى {max}",
    toGiftCard: "يعود إلى بطاقة الهدية {card}",
    toGiftCardPlain: "يعود إلى بطاقة الهدية",
    toGiftCardHint: "الجزء الذي دُفع من هذا الطلب ببطاقة الهدية، حتى {max}",
    toPoints: "يعود نقاط ولاء",
    toPointsHint: "الجزء الذي دُفع من هذا الطلب بالنقاط، حتى {max}",
    toCreditPayment: "يعود إلى رصيد المتجر",
    toCreditPaymentHint: "الجزء الذي دُفع من هذا الطلب من رصيد المتجر، حتى {max}",
    reasonRequired: "أدخل السبب: يُحفظ مع الاسترداد في صورة رصيد.",
    noCustomer: "هذا الطلب ليس له عميل يُضاف إليه الرصيد.",
    otherCurrency: "رصيد المتجر بعملة متجرك فقط، وهذا الطلب بعملة أخرى.",
    // payments list
    paymentPoints: "نقاط ولاء",
    paymentCredit: "رصيد المتجر",
  },
} satisfies Messages;

export type StoreCreditStrings = (typeof STORE_CREDIT_STRINGS)["en"];

export const STORE_CREDIT_KIND_KEY: Record<StoreCreditTransactionKind, keyof StoreCreditStrings> = {
  grant: "kind_grant",
  adjust: "kind_adjust",
  refund_credit: "kind_refund_credit",
  redeem: "kind_redeem",
  hold: "kind_hold",
  release: "kind_release",
  refund: "kind_refund",
  referral: "kind_referral",
};
