import type { Messages } from "@/i18n/LocaleContext";

/**
 * Business customers (handoff 228) and paying later on account (handoff 229):
 * the two cards on a customer's page, «سجّل دفعة», the «حسابات الآجل» list,
 * the company lines on an order and the manual order's on-account choice.
 * Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const B2B_STRINGS = {
  en: {
    // shared
    viewOnly: "Your role can see this but not change it.",
    noName: "No name",
    // customer page: business details
    businessTitle: "Business details",
    businessHint: "For a customer who buys as a company. The company and tax ID print on their invoices.",
    companyName: "Company name",
    taxId: "Tax ID",
    taxExempt: "Tax exempt",
    taxExemptOn: "No tax is added to their orders when they order signed in, or when your team enters the order for them. A price that already includes tax stays as it is.",
    taxExemptOff: "Tax is added to their orders as usual.",
    exemptNote: "Exemption note",
    exemptNotePlaceholder: "Exemption certificate seen, no. …",
    exemptNoteHint: "For your team only: what you checked before exempting them.",
    businessSaved: "Business details saved.",
    // customer page: pay on account
    onAccountTitle: "Pay on account",
    onAccountHint: "This customer orders now and pays later, within the terms you set.",
    onAccountEnable: "Let this customer pay later on account",
    onAccountEnableHint: "They choose it at checkout when signed in, and your team can pick it on an order created for them. The courier collects nothing.",
    creditLimit: "Credit limit",
    creditLimitHint: "The most they may owe at one time. Leave it empty for no limit.",
    creditLimitError: "Enter an amount, or leave it empty for no limit.",
    terms: "Pays within",
    termsUnit: "days",
    termsHint: "Counted from the day of the order.",
    termsError: "Enter a whole number of days from {min} to {max}.",
    onAccountSavedOn: "This customer can now pay later on account.",
    onAccountSavedOff: "Paying later is off for this customer. What they already owe stays as it is.",
    onAccountSaved: "Pay-on-account terms saved.",
    offButOwes: "Paying later is off for this customer, but these orders are still owed.",
    statOwed: "Owes now",
    statOverdue: "Overdue",
    statAvailable: "Available",
    noLimit: "No limit",
    ordersTitle: "On-account orders",
    ordersEmpty: "No on-account orders yet.",
    colOrder: "Order",
    colDue: "Due date",
    colTotal: "Total",
    colLeft: "Left to pay",
    orderedOn: "Ordered {date}",
    dueOn: "Due {date}",
    overdue: "Overdue",
    paid: "Paid",
    leftShort: "Left: {amount}",
    showAllOrders: "Show all {n} orders",
    showFewerOrders: "Show fewer",
    // record a payment
    recordPayment: "Record payment",
    recordTitle: "Record a payment",
    recordDescription: "Order {number} · left to pay {due}",
    amount: "Amount",
    amountHint: "At most {max}.",
    amountError: "Enter an amount above zero, up to {max}.",
    amountTooMuch: "That is more than what is left to pay. We updated the amount left.",
    reference: "Reference",
    referenceHint: "Optional: the transfer or cheque number.",
    cancel: "Cancel",
    recordSave: "Record payment",
    recordSaving: "Recording…",
    recorded: "Payment of {amount} recorded. Left to pay: {due}.",
    recordedPaid: "Payment of {amount} recorded. The order is fully paid.",
    notOnAccount: "This order isn't paid on account.",
    orderCancelled: "This order is cancelled, so no payment can be recorded on it.",
    // customers → on-account balances
    balancesTab: "On-account balances",
    balancesHint: "Customers who pay later: what each one owes, what is late and when the next payment is due.",
    filterLabel: "Filter on-account balances",
    filterAll: "All",
    filterOverdue: "Overdue only",
    totalOwed: "Total owed",
    totalOverdue: "Total overdue",
    colCustomer: "Customer",
    colOwed: "Owes",
    colOverdue: "Overdue",
    colNextDue: "Next due date",
    colLimit: "Credit limit",
    colTerms: "Terms",
    nothingDue: "Nothing due",
    emptyTitle: "No customers pay on account yet",
    emptyHint: "Open a customer and turn on “Pay on account” to let them order now and pay later.",
    emptyAction: "Open customers",
    emptyOverdueTitle: "Nobody is late",
    emptyOverdueHint: "Every on-account order is still within its terms.",
    showAll: "Show all",
    capped: "Showing the first {n} customers.",
    // order page
    orderCompany: "Company",
    orderTaxId: "Tax ID",
    orderTaxExempt: "Tax exempt",
    orderOnAccountTitle: "Pay on account",
    orderOnAccountHint: "The courier collects nothing for this order: the customer pays you later.",
    orderDue: "Due date",
    orderLeft: "Left to pay",
    orderPaidSoFar: "Paid so far",
    orderFullyPaid: "Fully paid.",
    // manual order
    manualOption: "Pay later on account ({days})",
    manualOptionSameDay: "Pay later on account (due the same day)",
    manualAvailable: "Available: {amount}",
    manualNoLimit: "No credit limit",
    manualOwes: "Owes now: {amount}",
    manualExempt: "This customer is tax exempt: no tax is added to this order.",
  },
  ar: {
    viewOnly: "دورك يقدر يشوف ده بس، مش يغيّره.",
    noName: "من غير اسم",
    businessTitle: "بيانات الشركة",
    businessHint: "للعميل اللي بيشتري باسم شركة. اسم الشركة والرقم الضريبي بيتطبعوا في فواتيره.",
    companyName: "اسم الشركة",
    taxId: "الرقم الضريبي",
    taxExempt: "معفى من الضريبة",
    taxExemptOn: "مفيش ضريبة بتتضاف على أوردراته لما يطلب وهو مسجّل دخول، أو لما فريقك يدخّل الأوردر باسمه. السعر اللي شامل الضريبة بيفضل زي ما هو.",
    taxExemptOff: "الضريبة بتتضاف على أوردراته عادي.",
    exemptNote: "ملاحظة الإعفاء",
    exemptNotePlaceholder: "شوفت شهادة الإعفاء رقم …",
    exemptNoteHint: "لفريقك بس: إيه اللي راجعته قبل ما تعفيه.",
    businessSaved: "اتحفظت بيانات الشركة.",
    onAccountTitle: "الدفع الآجل",
    onAccountHint: "العميل ده يطلب دلوقتي ويدفع بعدين، في المهلة اللي تحددها.",
    onAccountEnable: "اسمح للعميل ده يدفع آجل",
    onAccountEnableHint: "بيختاره في صفحة الدفع وهو مسجّل دخول، وفريقك يقدر يختاره في أوردر بيعمله باسمه. المندوب مش بيحصّل حاجة.",
    creditLimit: "حد الائتمان",
    creditLimitHint: "أقصى مبلغ يبقى عليه في نفس الوقت. سيبه فاضي لو من غير حد.",
    creditLimitError: "اكتب مبلغ، أو سيبه فاضي لو من غير حد.",
    terms: "يدفع خلال",
    termsUnit: "يوم",
    termsHint: "بتتحسب من يوم الأوردر.",
    termsError: "اكتب عدد أيام صحيح من {min} لـ {max}.",
    onAccountSavedOn: "العميل ده بقى يقدر يدفع آجل.",
    onAccountSavedOff: "الدفع الآجل اتقفل للعميل ده. اللي عليه فاضل زي ما هو.",
    onAccountSaved: "اتحفظت شروط الدفع الآجل.",
    offButOwes: "الدفع الآجل مقفول للعميل ده، بس الأوردرات دي لسه عليه.",
    statOwed: "عليه دلوقتي",
    statOverdue: "متأخر",
    statAvailable: "المتاح",
    noLimit: "من غير حد",
    ordersTitle: "أوردرات الآجل",
    ordersEmpty: "لسه مفيش أوردرات آجل.",
    colOrder: "الأوردر",
    colDue: "تاريخ الاستحقاق",
    colTotal: "الإجمالي",
    colLeft: "الباقي",
    orderedOn: "اتطلب {date}",
    dueOn: "مستحق {date}",
    overdue: "متأخر",
    paid: "مدفوع",
    leftShort: "الباقي: {amount}",
    showAllOrders: "اعرض كل الأوردرات ({n})",
    showFewerOrders: "اعرض أقل",
    recordPayment: "سجّل دفعة",
    recordTitle: "تسجيل دفعة",
    recordDescription: "أوردر {number} · الباقي {due}",
    amount: "المبلغ",
    amountHint: "بحد أقصى {max}.",
    amountError: "اكتب مبلغ أكبر من صفر ولحد {max}.",
    amountTooMuch: "المبلغ أكبر من الباقي على الأوردر. حدّثنا لك الباقي.",
    reference: "المرجع",
    referenceHint: "اختياري: رقم التحويل أو الشيك.",
    cancel: "إلغاء",
    recordSave: "سجّل الدفعة",
    recordSaving: "بنسجّل…",
    recorded: "اتسجّلت دفعة {amount}. الباقي: {due}.",
    recordedPaid: "اتسجّلت دفعة {amount}. الأوردر اتدفع كله.",
    notOnAccount: "الأوردر ده مش دفع آجل.",
    orderCancelled: "الأوردر ده ملغي، فمينفعش تتسجّل عليه دفعة.",
    balancesTab: "حسابات الآجل",
    balancesHint: "العملاء اللي بيدفعوا آجل: كل واحد عليه كام، وإيه اللي اتأخر، وأقرب دفعة مستحقة إمتى.",
    filterLabel: "تصفية حسابات الآجل",
    filterAll: "الكل",
    filterOverdue: "المتأخرين بس",
    totalOwed: "إجمالي اللي عليهم",
    totalOverdue: "إجمالي المتأخر",
    colCustomer: "العميل",
    colOwed: "عليه",
    colOverdue: "متأخر",
    colNextDue: "أقرب استحقاق",
    colLimit: "حد الائتمان",
    colTerms: "المهلة",
    nothingDue: "مفيش حاجة مستحقة",
    emptyTitle: "لسه مفيش عملاء بيدفعوا آجل",
    emptyHint: "افتح صفحة عميل وشغّل «الدفع الآجل» عشان يطلب دلوقتي ويدفع بعدين.",
    emptyAction: "افتح العملاء",
    emptyOverdueTitle: "مفيش حد متأخر",
    emptyOverdueHint: "كل أوردرات الآجل لسه في مهلتها.",
    showAll: "اعرض الكل",
    capped: "معروض أول {n} عميل.",
    orderCompany: "الشركة",
    orderTaxId: "الرقم الضريبي",
    orderTaxExempt: "معفى من الضريبة",
    orderOnAccountTitle: "الدفع الآجل",
    orderOnAccountHint: "المندوب مش بيحصّل حاجة في الأوردر ده: العميل بيدفع لك بعدين.",
    orderDue: "تاريخ الاستحقاق",
    orderLeft: "الباقي",
    orderPaidSoFar: "المدفوع لحد دلوقتي",
    orderFullyPaid: "اتدفع كله.",
    manualOption: "دفع آجل (خلال {days})",
    manualOptionSameDay: "دفع آجل (مستحق في نفس اليوم)",
    manualAvailable: "المتاح: {amount}",
    manualNoLimit: "من غير حد ائتمان",
    manualOwes: "عليه دلوقتي: {amount}",
    manualExempt: "العميل ده معفى من الضريبة: الأوردر من غير ضريبة.",
  },
} satisfies Messages;

export type B2bStrings = (typeof B2B_STRINGS)["en"];
