/** The console shell (menu and top bar), English and Arabic (MSA). */
export const SHELL_STRINGS = {
  en: {
    platformAdmin: "Platform Admin",
    mainNav: "Main",
    navigation: "Navigation",
    openNav: "Open navigation",
    closeNav: "Close navigation",
    environment: "Environment",
    development: "Development",
    staging: "Staging",
    searchPlaceholder: "Search workspaces…",
    searchLabel: "Search workspaces by name or address",
    noMatch: "No workspaces match “{query}”.",
    signOut: "Sign out",
    switchLanguage: "التبديل إلى العربية",
    languageShort: "ع",
  },
  ar: {
    platformAdmin: "إدارة المنصة",
    mainNav: "القائمة الرئيسية",
    navigation: "التنقل",
    openNav: "فتح القائمة",
    closeNav: "إغلاق القائمة",
    environment: "البيئة",
    development: "تطوير",
    staging: "تجريبية",
    searchPlaceholder: "ابحث في المتاجر…",
    searchLabel: "ابحث في المتاجر بالاسم أو العنوان",
    noMatch: "لا توجد متاجر تطابق «{query}».",
    signOut: "تسجيل الخروج",
    switchLanguage: "Switch to English",
    languageShort: "EN",
  },
};

/** Menu labels in Arabic, by their English label (lib/nav.ts). Missing ones stay English. */
export const NAV_LABELS_AR: Record<string, string> = {
  Overview: "نظرة عامة",
  Notifications: "الإشعارات",
  "Site traffic": "زيارات الموقع",
  Merchants: "التجار",
  Workspaces: "المتاجر",
  Users: "المستخدمون",
  Subscriptions: "الاشتراكات",
  Plans: "الخطط",
  "Transfer proofs": "إثباتات التحويل",
  "Payment methods": "طرق الدفع",
  Referrals: "الإحالات",
  Agents: "الوكلاء",
  "My referrals": "إحالاتي",
  Marketplace: "السوق",
  Templates: "القوالب",
  Themes: "الثيمات",
  Suppliers: "الموردون",
  Apps: "التطبيقات",
  Operations: "العمليات",
  Carriers: "شركات الشحن",
  "Payment gateways": "بوابات الدفع",
  "WhatsApp numbers": "أرقام واتساب",
  Risk: "المخاطر",
  "Fraud signals": "إشارات الاحتيال",
  "Blocklist (global)": "قائمة الحظر (عامة)",
  Support: "الدعم",
  Tickets: "التذاكر",
  Announcements: "الإعلانات",
  "Service listings": "قوائم الخدمات",
  System: "النظام",
  "Feature flags": "مفاتيح الميزات",
  "Audit log": "سجل التدقيق",
  "System health": "حالة النظام",
  "Admin users": "المسؤولون",
};
