import type { BillingInterval, CustomerSubscriptionStatus, ProductBillingPlan } from "@store-builder/api-client";
import { fmt, type Messages } from "@/i18n/LocaleContext";
import { countOf, pluralOf } from "@/lib/plural";

/** Subscriptions (SPEC §18.1): the list of what renews, and how each product is sold. */
export const SUBSCRIPTION_STRINGS = {
  en: {
    title: "Subscriptions",
    description: "Products your customers pay for every period, or in installments, on a saved card.",
    views: "Subscriptions view",
    tabList: "Subscriptions",
    tabPlans: "Product plans",
    kpisLabel: "Subscriptions in figures",
    kpiActive: "Active",
    kpiActiveHint: "{amount} per period",
    kpiNew: "New this month",
    kpiNewHint: "Started this month",
    kpiRevenue: "Collected",
    kpiRevenueHint: "First orders and renewals",
    searchLabel: "Search the subscriptions",
    searchPlaceholder: "Customer, phone or product",
    chipsLabel: "Subscriptions by status",
    anyStatus: "All",
    listLabel: "Subscriptions",
    colCustomer: "Customer",
    colPlan: "Plan",
    colNext: "Next charge",
    colStatus: "Status",
    colActions: "Actions",
    kind_subscription: "Subscription",
    kind_installments: "Installments",
    every_week: "weekly",
    every_month: "monthly",
    every_year: "yearly",
    everyN: "every {n} {unit}",
    unit_week: "weeks",
    unit_month: "months",
    unit_year: "years",
    installmentsLeft: "{made} of {total} paid",
    status_trialing: "Trial",
    status_active: "Active",
    status_past_due: "Payment failed",
    status_paused: "Paused",
    status_cancelled: "Cancelled",
    status_completed: "Completed",
    noCard: "No saved card",
    cardSaved: "Saved",
    retry: "Attempt {n} failed",
    none: "—",
    times: "× {n}",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel subscription",
    copyPortal: "Copy the customer's link",
    copiedPortal: "The customer's link is copied",
    portalHint: "The customer's own page: change the card, or cancel.",
    firstOrder: "First order",
    lastOrder: "Latest order",
    openOrder: "Open order",
    openFirstOrder: "Open the first order",
    openCustomer: "Open the customer",
    peek: "Preview the subscription of {who}",
    menuLabel: "Actions for this subscription",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopyPhone: "Copy the number",
    copiedPhone: "The customer's number is copied",
    qlProduct: "Product",
    qlPlan: "Plan",
    qlNext: "Next charge",
    qlCard: "Card",
    qlFailed: "Last failure",
    qlStarted: "Started",
    qlPaid: "Payments made",
    qlPortal: "Customer's link",
    qlCustomer: "Customer",
    emptyTitle: "No subscriptions yet",
    emptyDescription: "Put a product on a plan in “Product plans”. When a customer pays for it by card, the subscription starts here.",
    emptyStatus: "No subscriptions with this status",
    showAll: "Show all",
    emptySearch: "No subscription matches this search",
    clearSearch: "Clear the search",
    refreshFailed: "Couldn't refresh the list, so this is what was loaded last.",
    retryLoad: "Try again",
    cancelTitle: "Cancel {who}'s subscription to {product}?",
    cancelDescription: "The customer is not charged again. Orders already paid are not refunded, and this can't be undone.",
    cancelling: "Cancelling…",
    keep: "Keep it",
    pausedToast: "Subscription paused.",
    resumedToast: "Subscription resumed.",
    cancelledToast: "Subscription cancelled.",
    plansIntro: "The product's price is what each payment charges. Plans need a card payment on a gateway that can save cards; a cash-on-delivery order never starts one.",
    plansSearchLabel: "Search the products",
    plansSearchPlaceholder: "Product name",
    plansChips: "Products by how they are sold",
    plansList: "Product plans",
    planAll: "All",
    colProductName: "Product",
    colCurrent: "How it is sold",
    once: "Sold once",
    planOf: "{kind}, {every}",
    planPayments: "{payments}, {every}",
    pay_one: "1 payment",
    pay_other: "{n} payments",
    planTrial: "{days} free trial",
    edit: "Change",
    editName: "Change how {name} is sold",
    openProduct: "Open the product",
    planTitle: "How “{name}” is sold",
    mode: "Payment model",
    mode_once: "One payment",
    mode_subscription: "Subscription",
    mode_installments: "Installments",
    modeHint_once: "The customer pays once, as usual.",
    modeHint_subscription: "Charged every period until it is cancelled.",
    modeHint_installments: "The same amount, a fixed number of times.",
    interval: "Every",
    int_week: "Week",
    int_month: "Month",
    int_year: "Year",
    payments: "Number of payments",
    paymentsError: "Type a number from {min} to {max}.",
    trialDays: "Free trial (days)",
    trialHint: "Optional, up to {max} days. The first order charges nothing for the product and the first charge comes after the trial. One trial per customer; the gateway must be able to save a card without a payment when nothing else is due.",
    trialError: "Type a number of days from {min} to {max}, or leave it empty.",
    planSaved: "Plan saved.",
    save: "Save",
    saving: "Saving…",
    cancelEdit: "Cancel",
    emptyPlans: "No products yet",
    emptyPlansHint: "Add a product first, then choose how it is sold here.",
    addProduct: "Add a product",
    emptyPlansFiltered: "No product matches this search or filter",
    clearFilters: "Clear the search and filter",
  },
  ar: {
    title: "الاشتراكات",
    description: "منتجات عملاؤك بيدفعوا تمنها كل فترة أو بالتقسيط، على كارت محفوظ.",
    views: "طريقة عرض الاشتراكات",
    tabList: "الاشتراكات",
    tabPlans: "خطط المنتجات",
    kpisLabel: "الاشتراكات بالأرقام",
    kpiActive: "شغّالة",
    kpiActiveHint: "{amount} كل فترة",
    kpiNew: "جديدة الشهر ده",
    kpiNewHint: "بدأت الشهر ده",
    kpiRevenue: "اتحصّل",
    kpiRevenueHint: "من أول أوردر والتجديدات",
    searchLabel: "دوّر في الاشتراكات",
    searchPlaceholder: "العميل، الموبايل أو المنتج",
    chipsLabel: "الاشتراكات حسب الحالة",
    anyStatus: "الكل",
    listLabel: "الاشتراكات",
    colCustomer: "العميل",
    colPlan: "الخطة",
    colNext: "الخصم الجاي",
    colStatus: "الحالة",
    colActions: "إجراءات",
    kind_subscription: "اشتراك",
    kind_installments: "تقسيط",
    every_week: "كل أسبوع",
    every_month: "كل شهر",
    every_year: "كل سنة",
    everyN: "كل {n} {unit}",
    unit_week: "أسابيع",
    unit_month: "شهور",
    unit_year: "سنين",
    installmentsLeft: "اتدفع {made} من {total}",
    status_trialing: "تجربة",
    status_active: "شغّال",
    status_past_due: "الدفع فشل",
    status_paused: "واقف",
    status_cancelled: "اتلغى",
    status_completed: "خلص",
    noCard: "مفيش كارت محفوظ",
    cardSaved: "محفوظ",
    retry: "المحاولة {n} فشلت",
    none: "—",
    times: "× {n}",
    pause: "وقّفه",
    resume: "شغّله تاني",
    cancel: "الغي الاشتراك",
    copyPortal: "انسخ لينك العميل",
    copiedPortal: "لينك العميل اتنسخ",
    portalHint: "صفحة العميل نفسه: يغيّر الكارت أو يلغي.",
    firstOrder: "أول أوردر",
    lastOrder: "آخر أوردر",
    openOrder: "افتح الأوردر",
    openFirstOrder: "افتح أول أوردر",
    openCustomer: "افتح صفحة العميل",
    peek: "معاينة اشتراك {who}",
    menuLabel: "إجراءات الاشتراك",
    menuCall: "اتصل",
    menuWhatsapp: "واتساب",
    menuCopyPhone: "انسخ الرقم",
    copiedPhone: "رقم العميل اتنسخ",
    qlProduct: "المنتج",
    qlPlan: "الخطة",
    qlNext: "الخصم الجاي",
    qlCard: "الكارت",
    qlFailed: "آخر فشل",
    qlStarted: "بدأ",
    qlPaid: "دفعات اتدفعت",
    qlPortal: "لينك العميل",
    qlCustomer: "العميل",
    emptyTitle: "لسه مفيش اشتراكات",
    emptyDescription: "حط منتج على خطة من «خطط المنتجات». أول ما عميل يدفع تمنه بالكارت، الاشتراك هيظهر هنا.",
    emptyStatus: "مفيش اشتراكات بالحالة دي",
    showAll: "اعرض الكل",
    emptySearch: "مفيش اشتراك بالبحث ده",
    clearSearch: "امسح البحث",
    refreshFailed: "معرفناش نحدّث القائمة، فدي آخر حاجة اتحمّلت.",
    retryLoad: "جرّب تاني",
    cancelTitle: "تلغي اشتراك {who} في {product}؟",
    cancelDescription: "مش هيتخصم من العميل تاني. الأوردرات اللي اتدفعت مش بترجع، ومينفعش ترجع في الإلغاء.",
    cancelling: "بنلغي…",
    keep: "سيبه",
    pausedToast: "الاشتراك وقف.",
    resumedToast: "الاشتراك اشتغل تاني.",
    cancelledToast: "الاشتراك اتلغى.",
    plansIntro: "سعر المنتج هو اللي بيتخصم في كل دفعة. الخطط محتاجة دفع بالكارت على بوابة بتحفظ الكروت؛ أوردر الدفع عند الاستلام مش بيبدأ خطة.",
    plansSearchLabel: "دوّر في المنتجات",
    plansSearchPlaceholder: "اسم المنتج",
    plansChips: "المنتجات حسب طريقة البيع",
    plansList: "خطط المنتجات",
    planAll: "الكل",
    colProductName: "المنتج",
    colCurrent: "طريقة البيع",
    once: "دفعة واحدة",
    planOf: "{kind}، {every}",
    planPayments: "{payments}، {every}",
    pay_one: "دفعة واحدة",
    pay_two: "دفعتين",
    pay_few: "{n} دفعات",
    pay_other: "{n} دفعة",
    planTrial: "تجربة مجانية {days}",
    edit: "غيّر",
    editName: "غيّر طريقة بيع {name}",
    openProduct: "افتح المنتج",
    planTitle: "طريقة بيع «{name}»",
    mode: "طريقة الدفع",
    mode_once: "دفعة واحدة",
    mode_subscription: "اشتراك",
    mode_installments: "تقسيط",
    modeHint_once: "العميل بيدفع مرة واحدة زي العادي.",
    modeHint_subscription: "بيتخصم كل فترة لحد ما الاشتراك يتلغي.",
    modeHint_installments: "نفس المبلغ، عدد محدد من المرات.",
    interval: "كل قد إيه",
    int_week: "أسبوع",
    int_month: "شهر",
    int_year: "سنة",
    payments: "عدد الدفعات",
    paymentsError: "اكتب عدد من {min} لـ {max}.",
    trialDays: "تجربة مجانية (بالأيام)",
    trialHint: "اختياري، لحد {max} يوم. أول أوردر مش بيتحسب فيه المنتج وأول خصم بييجي بعد التجربة. تجربة واحدة لكل عميل؛ ولازم بوابة الدفع تقدر تحفظ الكارت من غير دفع لو مفيش مبلغ تاني مستحق.",
    trialError: "اكتب عدد أيام من {min} لـ {max}، أو سيبه فاضي.",
    planSaved: "الخطة اتحفظت.",
    save: "حفظ",
    saving: "بنحفظ…",
    cancelEdit: "إلغاء",
    emptyPlans: "لسه مفيش منتجات",
    emptyPlansHint: "ضيف منتج الأول، وبعدين اختار طريقة بيعه من هنا.",
    addProduct: "ضيف منتج",
    emptyPlansFiltered: "مفيش منتج بالبحث أو الفلتر ده",
    clearFilters: "امسح البحث والفلتر",
  },
} satisfies Messages;

export type SubscriptionStrings = (typeof SUBSCRIPTION_STRINGS)["en"];

export const SUBSCRIPTION_STATUSES: readonly CustomerSubscriptionStatus[] = ["active", "trialing", "past_due", "paused", "cancelled", "completed"];

export const SUBSCRIPTION_STATUS_TONE: Record<CustomerSubscriptionStatus, "success" | "warning" | "danger" | "neutral" | "info"> = {
  trialing: "info",
  active: "success",
  past_due: "warning",
  paused: "neutral",
  cancelled: "danger",
  completed: "info",
};

/** «كل شهر», or «كل ٣ شهور» when the period is more than one. */
export function everyText(t: SubscriptionStrings, interval: BillingInterval, count: number): string {
  return count <= 1 ? t[`every_${interval}`] : fmt(t.everyN, { n: count, unit: t[`unit_${interval}`] });
}

/** How a product is sold, in a few words: «اشتراك، كل شهر · تجربة مجانية ٧ أيام», «٣ دفعات، كل شهر», «دفعة واحدة». */
export function planText(t: SubscriptionStrings, plan: ProductBillingPlan | null): string {
  if (!plan) return t.once;
  const every = everyText(t, plan.interval, plan.intervalCount ?? 1);
  if (plan.mode === "installments") return fmt(t.planPayments, { payments: pluralOf(t, "pay", plan.payments), every });
  const text = fmt(t.planOf, { kind: t.kind_subscription, every });
  return plan.trialDays ? `${text} · ${fmt(t.planTrial, { days: countOf("day", plan.trialDays) })}` : text;
}
