import type { Messages } from "@/i18n/LocaleContext";

/**
 * Every word of the «الإعلانات» tab of the reports hub (AdsTab.tsx and the parts in this folder).
 * Read with `useT(ADS_STRINGS)`. Counted words (`campaigns_*`, `accounts_*`) go through
 * `pluralOf` from @/lib/plural; orders through `countOf("order", n)`.
 */
export const ADS_STRINGS = {
  en: {
    // The tab
    note: "Every figure here covers the period you picked only — campaigns have no earlier period to compare with.",
    noteSourcesOnly: "Campaign spend and profit aren't part of your role — this shows where your orders came from.",

    // Stat cards
    kpiSpend: "Ad spend",
    kpiSpendHint: "Recorded for {campaigns}",
    campaigns_one: "1 campaign",
    campaigns_other: "{n} campaigns",
    kpiOrders: "Orders",
    kpiOrdersHint: "Came through these campaigns' links",
    kpiDelivered: "Delivered",
    kpiDeliveredHint: "Out of {orders}",
    kpiCpd: "Cost per delivered order",
    kpiCpdHint: "Spend ÷ delivered orders",
    kpiCpdNone: "No campaign order delivered yet",
    kpiRoas: "Return on ad spend",
    kpiRoasHint: "Delivered sales {amount} ÷ spend",
    kpiRoasNone: "Delivered sales ÷ spend",
    kpiVisitors: "Visitors",
    kpiVisitorsHint: "Everyone who visited in the period",
    kpiAllOrdersHint: "Every order in the period, whatever its source",
    kpiDeliveredSales: "Delivered sales",
    kpiDeliveredSalesHint: "Out of {amount} ordered",

    // The chart
    chartTitle: "Each campaign: what it cost, what came back",
    chartNote: "Delivered sales of each campaign beside what was spent on it — the biggest spenders; the rest are in the table.",
    chartSummary: "Delivered sales of each campaign against its ad spend",
    chartRow: "{name}: spent {spend}, brought back {sales} in delivered sales",
    barSpend: "Spend: {amount}",
    barSales: "Delivered sales: {amount}",
    legendSales: "Delivered sales",
    legendSpend: "Spend",
    salesChartTitle: "Sales day by day",
    salesChartNote: "Sales of the orders placed each day — every source together.",
    salesChartEmpty: "No sales in this period.",

    // The table
    groupLabel: "Break the table down by",
    modeAds: "Campaigns",
    modeSource: "Source",
    modeMedium: "Medium",
    modeCampaign: "Link campaign",
    modeContent: "Ad",
    tableTitleAds: "Campaign by campaign",
    tableCaptionAds:
      "Campaigns with recorded spend: spend, orders, confirmed, delivered, returned, delivered sales, cost per delivered order, return on spend and net profit.",
    tableNoteAds: "A campaign's orders are the ones whose link carried its name — the last link before buying.",
    tableNoteProfit: "Net profit shows only for a campaign whose orders are recorded under its exact name.",
    tableNoteCoverage: "Only {rate} of the delivered pieces have a cost, so profit reads higher than it really is.",
    tableTitleBy: "By {dimension}",
    tableCaptionBy:
      "Visitors, orders and sales by {dimension}, from your ad links. This view has different columns from the campaigns view.",
    tableNoteLast:
      "Each order counts once, for the last link the customer came through before buying. The columns here differ from the campaigns view.",
    tableNoteFirst:
      "Each order counts once, for the first link that brought the customer to the store. The columns here differ from the campaigns view.",
    totalsLine: "Total: {orders} · sales {sales} · of which delivered {delivered}",
    totalsRoas: " · return {roas}",
    noSpendHint: "Record your ad spend to see the return and the cost per delivered order here.",
    colCampaign: "Campaign",
    colPlatform: "Platform",
    platformOther: "Other platform",
    colSource: "Source (utm_source)",
    colMedium: "Medium (utm_medium)",
    colLinkCampaign: "Link campaign (utm_campaign)",
    colContent: "Ad (utm_content)",
    colSpend: "Spend",
    colOrders: "Orders",
    colConfirmed: "Confirmed",
    colDelivered: "Delivered",
    colReturned: "Returned",
    colDeliveredSales: "Delivered sales",
    colCpd: "Cost per delivered order",
    colRoas: "Return on spend",
    colProfit: "Net profit",
    colVisitors: "Visitors",
    colSales: "Sales",
    colConversion: "Conversion",
    colAov: "Average order",
    hintOrders: "Every order the campaign brought in the period, cancelled ones included",
    hintConfirmed: "Orders confirmed with the customer",
    hintReturned: "Orders that came back from the courier",
    hintCpd: "Spend ÷ delivered orders",
    hintRoas: "Delivered sales ÷ spend",
    hintProfit:
      "Sales of the delivered orders minus product cost, shipping, fees and the campaign's spend. Orders still on the way aren't counted.",
    hintSales: "Sales of the orders that weren't cancelled",
    hintConversion: "Orders ÷ visitors",
    hintSpendBy: "Spend recorded under this platform or campaign name",
    profitUnreadable: "This campaign's orders aren't recorded under its name, so its profit can't be worked out",
    untracked: "No UTM (direct, phone, by hand)",
    emptyAds: "No campaign has spend in this period.",
    emptyBy: "No visits or orders in this period. Put UTM parameters on your ad links and the sources show up here.",
    emptyFiltered: "Nothing matches this filter.",
    touchLabel: "Credit the sale to",
    touchLast: "Last touch",
    touchFirst: "First touch",
    funnelLabel: "Store or sales funnel",
    allStore: "Whole store",
    drillSource: "Show the campaigns of {name}",
    drillCampaign: "Show the ads of {name}",
    chipSource: "Source: {name}",
    chipCampaign: "Link campaign: {name}",
    chipClear: "Remove the filter — {label}",
    attributionDenied: "Order sources aren't part of your role.",
    attributionFailed: "We couldn't load the sources.",
    profitFailed: "We couldn't load the profit of each campaign.",
    partError: "We couldn't load this part.",
    partDenied: "This part isn't part of your role.",
    loadingPart: "Loading…",

    // The sentence
    outOfTenOrders: "{n} of every {ten} orders",
    sayWinnerProfit:
      "Campaign “{name}” is the one making money: {amount} left after the product, shipping and ads — if you raise a budget, raise this one.",
    sayWinnerProfitAndReturns:
      "Campaign “{name}” is the one making money ({amount} left), but {rate} from campaign “{other}” come back — review its ad or pause it.",
    sayWinnerRoas: "Campaign “{name}” has the best return: {spend} spent on it brought back {sales} in delivered sales.",
    sayWinnerRoasAndReturns:
      "Campaign “{name}” has the best return ({spend} spent, {sales} back), but {rate} from campaign “{other}” come back — review its ad or pause it.",
    sayReturnsOnly: "{rate} from campaign “{name}” come back — review its ad or pause it.",
    sayLoserProfit: "Campaign “{name}” is losing money: {amount} lost after the product, shipping and ads — pause it or change its ad.",
    sayLoserRoas:
      "Campaign “{name}” is losing money: {spend} spent on it brought back only {sales} in delivered sales — pause it or change its ad.",
    sayNoOrders: "You spent {spend} and no order is recorded under your campaigns — check that each ad's link carries the campaign's name.",
    sayThin: "Too early to judge: no campaign has {min} finished (delivered or returned) in this period yet.",
    sayEven: "No campaign clearly makes or loses money in this period.",
    sayUntracked: "{rate} have no known source — put UTM parameters on your ad links to see which ad sells.",
    sayTopSource: "Most delivered sales came from “{name}”: {amount} from {orders}.",
    sayThinSources: "Not enough orders in this period to judge the sources yet.",
    actionCampaigns: "Open the campaigns",
    actionBuilder: "Open the link builder",

    // No spend recorded
    emptyTitle: "No ad spend recorded for this period",
    emptyDescUnmatched:
      "{campaigns} brought {orders} and their spend isn't recorded — once it is, you'll see which campaign makes money.",
    emptyDescConnected: "Your ad account is connected, but no spend came in for this period. Sync it, or type the spend in yourself.",
    emptyDescConnect:
      "Connect your ad account and the spend comes in by itself — or type it in from the Ad spend page. Then you'll see what each campaign cost and what came back.",
    emptyDescRecord:
      "Record what you spent on ads — by hand, or with the file from your ads manager — and you'll see what each campaign cost and what came back.",
    actionConnect: "Connect your ad account",
    actionRecord: "Record ad spend",
    sourcesEmptyTitle: "No visits or orders in this period",
    sourcesEmptyDesc: "Put UTM parameters on your ad links — the link builder writes them for you — and the sources show up here.",

    // More detail
    moreSourcesTitle: "Order sources from your links",
    moreSourcesSummary: "By source, medium, link campaign and ad",
    moreUnmatchedTitle: "Campaigns with orders but no recorded spend",
    moreUnmatchedSummary: "Record their spend to see what they return",
    colCampaignInLink: "Campaign in the link (utm_campaign)",
    moreProfitTitle: "Profit campaign by campaign",
    moreProfitSummary: "From the profit statement: after the product, shipping, fees and ads",
    moreProfitEmpty: "No finished orders in this period yet.",
    colMargin: "Margin",
    colCosts: "Costs",
    colAdsCost: "Ads",
    colProjected: "Projected profit",
    colMaxCpa: "Most you can pay in ads per order",
    hintCosts: "The product, both shipping legs and the fees",
    hintProjected: "If the open orders get delivered at your usual delivery rate",
    hintMaxCpa: "Ad cost per order before you lose money",
    noCampaign: "No campaign",
    moreDailyTitle: "Spend and sales day by day",
    moreDailySummary: "Ad spend beside the store's delivered sales",
    dailyNote:
      "Sales here are of every order placed that day and since delivered — not only orders from ads — and the last days' orders are still on the way.",
    dailySales: "Delivered sales (whole store)",
    dailySpend: "Ad spend",
    dailySummary: "Ad spend and the store's delivered sales, day by day",
    dailyEmpty: "No spend and no delivered sales in this period.",
    moreEntriesTitle: "Spend log",
    moreEntriesSummary: "Every amount recorded: by day, platform and campaign",
    entriesNote: "To add or delete an amount, open the Ad spend page.",
    entriesCapped: "Showing the latest {shown} of {total} — the rest are on the Ad spend page.",
    entriesEmpty: "No spend recorded in this period.",
    colDay: "Date",
    colImpressions: "Impressions",
    colClicks: "Clicks",
    colEntered: "Entered",
    enteredManual: "By hand",
    enteredCsv: "CSV file",
    enteredSync: "Sync",
    moreTrafficTitle: "Visitors and sales day by day",
    moreTrafficSummary: "The store's visitors and sales each day of the period",
    visitorsChart: "Visitors per day",
    salesChart: "Sales per day",
    chartOf: "{what} for {window}",
    moreChannelsTitle: "Sales by channel",
    moreChannelsSummary: "Source and medium together: sessions, orders and sales",
    colChannel: "Channel",
    colSessions: "Sessions",
    direct: "Direct",
    channelsEmpty: "No visits in this period.",
    moreUrlTitle: "Ad link parameters (UTM)",
    moreUrlSummary: "Paste them on each ad so its orders are recorded under the campaign",
    urlDesc: "Paste into the URL parameters field of each ad.",
    copy: "Copy",

    // Links out
    linkSpend: "Record ad spend",
    linkSpendDesc: "Type an amount or import a file, pause a campaign or change its budget",
    linkAccounts: "Ad accounts",
    linkAccountsOn: "{accounts} followed — sync the spend or connect another platform",
    linkAccountsPick: "Connected — pick the accounts to follow so their spend comes in",
    linkAccountsProblem: "A connection has a problem — open it to see why",
    linkAccountsOff: "Connect an ad platform and the spend comes in by itself",
    accounts_one: "1 account",
    accounts_other: "{n} accounts",
    linkProfit: "Profit statement",
    linkProfitDesc: "Profit after every cost: day by day and product by product",
    linkCosts: "Product costs",
    linkCostsDesc: "The piece cost, shipping and fees the profit is worked out from",
    linkBuilder: "Ad link builder",
    linkBuilderDesc: "Writes the UTM parameters of each ad for you",
  },
  ar: {
    // The tab
    note: "كل رقم هنا عن الفترة اللي اخترتها بس — الحملات مالهاش فترة قبلها نقارن بيها.",
    noteSourcesOnly: "مصاريف الحملات وأرباحها مش ضمن صلاحياتك — هنا مصادر الأوردرات بس.",

    // Stat cards
    kpiSpend: "المصاريف",
    kpiSpendHint: "المتسجّل على {campaigns}",
    campaigns_one: "حملة واحدة",
    campaigns_two: "حملتين",
    campaigns_few: "{n} حملات",
    campaigns_other: "{n} حملة",
    kpiOrders: "الأوردرات",
    kpiOrdersHint: "جت من روابط الحملات دي",
    kpiDelivered: "اتسلّمت",
    kpiDeliveredHint: "من أصل {orders}",
    kpiCpd: "تكلفة أوردر اتسلّم",
    kpiCpdHint: "المصاريف ÷ الأوردرات اللي اتسلّمت",
    kpiCpdNone: "لسه مفيش أوردر اتسلّم من الحملات",
    kpiRoas: "العائد على المصاريف",
    kpiRoasHint: "مبيعات اتسلّمت {amount} ÷ المصاريف",
    kpiRoasNone: "مبيعات اتسلّمت ÷ المصاريف",
    kpiVisitors: "الزوار",
    kpiVisitorsHint: "كل اللي زاروا المتجر في الفترة",
    kpiAllOrdersHint: "كل أوردرات الفترة من أي مصدر",
    kpiDeliveredSales: "مبيعات اتسلّمت",
    kpiDeliveredSalesHint: "من مبيعات {amount} اتطلبت",

    // The chart
    chartTitle: "كل حملة: صرفت كام ورجّعت كام",
    chartNote: "مبيعات كل حملة اللي اتسلّمت جنب اللي اتصرف عليها — أكتر الحملات صرفًا، والباقي في الجدول.",
    chartSummary: "مبيعات كل حملة اللي اتسلّمت قدام مصاريفها",
    chartRow: "{name}: صرفت {spend} ورجّعت {sales} مبيعات اتسلّمت",
    barSpend: "المصاريف: {amount}",
    barSales: "مبيعات اتسلّمت: {amount}",
    legendSales: "مبيعات اتسلّمت",
    legendSpend: "المصاريف",
    salesChartTitle: "المبيعات يوم بيوم",
    salesChartNote: "مبيعات أوردرات كل يوم — كل المصادر مع بعض.",
    salesChartEmpty: "مفيش مبيعات في الفترة دي.",

    // The table
    groupLabel: "قسّم الجدول حسب",
    modeAds: "الحملات",
    modeSource: "المصدر",
    modeMedium: "الوسيط",
    modeCampaign: "حملة الرابط",
    modeContent: "الإعلان",
    tableTitleAds: "حملة بحملة",
    tableCaptionAds:
      "الحملات اللي ليها مصاريف متسجّلة: المصاريف والأوردرات واللي اتأكد واتسلّم ورجع، ومبيعاتها اللي اتسلّمت، وتكلفة الأوردر اللي اتسلّم والعائد وصافي الربح.",
    tableNoteAds: "أوردرات الحملة هي اللي جت من رابط فيه اسمها — آخر رابط قبل الشرا.",
    tableNoteProfit: "صافي الربح بيظهر بس للحملة اللي أوردراتها متسجّلة باسمها بالظبط.",
    tableNoteCoverage: "{rate} بس من القطع اللي اتسلّمت ليها تكلفة، فالربح طالع أعلى من الحقيقي.",
    tableTitleBy: "حسب {dimension}",
    tableCaptionBy: "الزوار والأوردرات والمبيعات حسب {dimension} من روابط إعلاناتك. أعمدة العرض ده غير أعمدة الحملات.",
    tableNoteLast: "كل أوردر محسوب مرة واحدة على آخر رابط دخل منه العميل قبل ما يشتري. الأعمدة هنا غير أعمدة الحملات.",
    tableNoteFirst: "كل أوردر محسوب مرة واحدة على أول رابط جاب العميل للمتجر. الأعمدة هنا غير أعمدة الحملات.",
    totalsLine: "الإجمالي: {orders} · مبيعات {sales} · اتسلّم منها {delivered}",
    totalsRoas: " · العائد {roas}",
    noSpendHint: "سجّل مصاريف الإعلانات عشان يظهر هنا العائد وتكلفة الأوردر اللي اتسلّم.",
    colCampaign: "الحملة",
    colPlatform: "المنصة",
    platformOther: "منصة تانية",
    colSource: "المصدر (utm_source)",
    colMedium: "الوسيط (utm_medium)",
    colLinkCampaign: "حملة الرابط (utm_campaign)",
    colContent: "الإعلان (utm_content)",
    colSpend: "المصاريف",
    colOrders: "الأوردرات",
    colConfirmed: "اتأكدت",
    colDelivered: "اتسلّمت",
    colReturned: "رجعت",
    colDeliveredSales: "مبيعات اتسلّمت",
    colCpd: "تكلفة أوردر اتسلّم",
    colRoas: "العائد",
    colProfit: "صافي الربح",
    colVisitors: "الزوار",
    colSales: "المبيعات",
    colConversion: "التحويل",
    colAov: "متوسط الأوردر",
    hintOrders: "كل أوردر جابته الحملة في الفترة، حتى اللي اتلغى",
    hintConfirmed: "أوردرات اتأكدت مع العميل",
    hintReturned: "أوردرات رجعت من المندوب",
    hintCpd: "المصاريف ÷ الأوردرات اللي اتسلّمت",
    hintRoas: "مبيعات اتسلّمت ÷ المصاريف",
    hintProfit: "مبيعات الأوردرات اللي اتسلّمت ناقص تكلفة المنتج والشحن والرسوم ومصاريف الحملة. الأوردرات اللي لسه في الطريق مش محسوبة.",
    hintSales: "مبيعات الأوردرات اللي ما اتلغتش",
    hintConversion: "الأوردرات ÷ الزوار",
    hintSpendBy: "المصاريف المتسجّلة باسم المنصة أو الحملة دي",
    profitUnreadable: "أوردرات الحملة دي مش متسجّلة باسمها، فمش قادرين نحسب ربحها",
    untracked: "من غير UTM (مباشر، تليفون، بإيدك)",
    emptyAds: "مفيش حملة ليها مصاريف في الفترة دي.",
    emptyBy: "مفيش زيارات ولا أوردرات في الفترة دي. حط معاملات UTM في روابط إعلاناتك والمصادر تظهر هنا.",
    emptyFiltered: "مفيش حاجة بالفلتر ده.",
    touchLabel: "احسب البيعة على",
    touchLast: "آخر لمسة",
    touchFirst: "أول لمسة",
    funnelLabel: "المتجر أو مسار البيع",
    allStore: "المتجر كله",
    drillSource: "اعرض حملات {name}",
    drillCampaign: "اعرض إعلانات {name}",
    chipSource: "المصدر: {name}",
    chipCampaign: "حملة الرابط: {name}",
    chipClear: "شيل الفلتر — {label}",
    attributionDenied: "مصادر الأوردرات مش ضمن صلاحياتك.",
    attributionFailed: "معرفناش نحمّل المصادر.",
    profitFailed: "معرفناش نحمّل ربح كل حملة.",
    partError: "معرفناش نحمّل الجزء ده.",
    partDenied: "الجزء ده مش ضمن صلاحياتك.",
    loadingPart: "بنحمّل…",

    // The sentence
    outOfTenOrders: "{n} من كل {ten} أوردرات",
    sayWinnerProfit: "حملة «{name}» هي اللي بتكسّب: فضّل منها {amount} بعد المنتج والشحن والإعلان — لو هتزوّد ميزانية، زوّدها هنا.",
    sayWinnerProfitAndReturns:
      "حملة «{name}» هي اللي بتكسّب (فضّل منها {amount})، لكن حملة «{other}» بيرجع منها {rate} — راجع إعلانها أو وقّفها.",
    sayWinnerRoas: "حملة «{name}» أحسن عائد: صرفت عليها {spend} ورجّعت {sales} مبيعات اتسلّمت.",
    sayWinnerRoasAndReturns:
      "حملة «{name}» أحسن عائد (صرفت {spend} ورجّعت {sales})، لكن حملة «{other}» بيرجع منها {rate} — راجع إعلانها أو وقّفها.",
    sayReturnsOnly: "حملة «{name}» بيرجع منها {rate} — راجع إعلانها أو وقّفها.",
    sayLoserProfit: "حملة «{name}» بتخسّر: خسرت {amount} بعد المنتج والشحن والإعلان — وقّفها أو غيّر إعلانها.",
    sayLoserRoas: "حملة «{name}» بتخسّر: صرفت عليها {spend} ورجّعت {sales} بس مبيعات اتسلّمت — وقّفها أو غيّر إعلانها.",
    sayNoOrders: "صرفت {spend} ومفيش أوردر اتسجّل على حملاتك — اتأكد إن رابط كل إعلان فيه اسم الحملة.",
    sayThin: "لسه بدري نحكم: مفيش حملة خلص منها {min} (اتسلّمت أو رجعت) في الفترة دي.",
    sayEven: "مفيش حملة باين إنها بتكسّب أو بتخسّر بوضوح في الفترة دي.",
    sayUntracked: "{rate} مش معروف جاية منين — حط معاملات UTM في روابط إعلاناتك عشان تعرف أنهي إعلان بيبيع.",
    sayTopSource: "أكتر مبيعات اتسلّمت جاية من «{name}»: {amount} من {orders}.",
    sayThinSources: "لسه مفيش أوردرات كفاية في الفترة دي نحكم منها على المصادر.",
    actionCampaigns: "افتح الحملات",
    actionBuilder: "افتح منشئ الروابط",

    // No spend recorded
    emptyTitle: "مفيش مصاريف إعلانات متسجّلة في الفترة دي",
    emptyDescUnmatched: "في {campaigns} جابت {orders} ومصاريفها مش متسجّلة — لما المصاريف تتسجّل هتعرف أنهي حملة بتكسّب.",
    emptyDescConnected: "حساب الإعلانات مربوط، بس مفيش مصاريف وصلت عن الفترة دي. زامنه أو اكتب المصاريف بإيدك.",
    emptyDescConnect:
      "اربط حساب الإعلانات والمصاريف تيجي لوحدها — أو اكتبها بإيدك من صفحة مصاريف الإعلانات. ساعتها تشوف كل حملة صرفت كام ورجّعت كام.",
    emptyDescRecord: "سجّل اللي صرفته على الإعلانات — بإيدك أو بالملف من مدير الإعلانات — وساعتها تشوف كل حملة صرفت كام ورجّعت كام.",
    actionConnect: "اربط حساب الإعلانات",
    actionRecord: "سجّل مصاريف الإعلانات",
    sourcesEmptyTitle: "مفيش زيارات ولا أوردرات في الفترة دي",
    sourcesEmptyDesc: "حط معاملات UTM في روابط إعلاناتك — منشئ الروابط بيكتبهالك — والمصادر تظهر هنا.",

    // More detail
    moreSourcesTitle: "مصادر الأوردرات من روابطك",
    moreSourcesSummary: "حسب المصدر والوسيط وحملة الرابط والإعلان",
    moreUnmatchedTitle: "حملات جابت أوردرات ومصاريفها مش متسجّلة",
    moreUnmatchedSummary: "سجّل مصاريفها عشان تعرف بترجّع كام",
    colCampaignInLink: "الحملة في الرابط (utm_campaign)",
    moreProfitTitle: "الربح حملة بحملة",
    moreProfitSummary: "من قائمة الأرباح: بعد المنتج والشحن والرسوم والإعلان",
    moreProfitEmpty: "لسه مفيش أوردرات خلصت في الفترة دي.",
    colMargin: "الهامش",
    colCosts: "التكاليف",
    colAdsCost: "الإعلانات",
    colProjected: "الربح المتوقع",
    colMaxCpa: "أقصى تكلفة إعلان للأوردر",
    hintCosts: "المنتج والشحن رايح جاي والرسوم",
    hintProjected: "لو الأوردرات المفتوحة اتسلّمت بنسبة التسليم المعتادة عندك",
    hintMaxCpa: "تدفع في الإعلان لحد كده للأوردر قبل ما تخسر",
    noCampaign: "من غير حملة",
    moreDailyTitle: "المصاريف والمبيعات يوم بيوم",
    moreDailySummary: "مصاريف الإعلانات جنب مبيعات المتجر اللي اتسلّمت",
    dailyNote: "المبيعات هنا لكل أوردرات اليوم اللي اتسلّمت، مش أوردرات الإعلانات بس — وأوردرات الأيام الأخيرة لسه في الطريق.",
    dailySales: "مبيعات اتسلّمت (المتجر كله)",
    dailySpend: "مصاريف الإعلانات",
    dailySummary: "مصاريف الإعلانات ومبيعات المتجر اللي اتسلّمت يوم بيوم",
    dailyEmpty: "مفيش مصاريف ولا مبيعات اتسلّمت في الفترة دي.",
    moreEntriesTitle: "سجل المصاريف",
    moreEntriesSummary: "كل مبلغ اتسجّل: باليوم والمنصة والحملة",
    entriesNote: "عشان تضيف مبلغ أو تمسحه، افتح صفحة مصاريف الإعلانات.",
    entriesCapped: "معروض أحدث {shown} من {total} — الباقي في صفحة مصاريف الإعلانات.",
    entriesEmpty: "مفيش مصاريف متسجّلة في الفترة دي.",
    colDay: "التاريخ",
    colImpressions: "مرات الظهور",
    colClicks: "النقرات",
    colEntered: "اتسجّل إزاي",
    enteredManual: "بإيدك",
    enteredCsv: "ملف CSV",
    enteredSync: "مزامنة",
    moreTrafficTitle: "الزوار والمبيعات يوم بيوم",
    moreTrafficSummary: "زوار المتجر ومبيعاته كل يوم في الفترة",
    visitorsChart: "الزوار كل يوم",
    salesChart: "المبيعات كل يوم",
    chartOf: "{what} في الفترة {window}",
    moreChannelsTitle: "المبيعات حسب القناة",
    moreChannelsSummary: "المصدر والوسيط مع بعض: زيارات وأوردرات ومبيعات",
    colChannel: "القناة",
    colSessions: "الزيارات",
    direct: "مباشر",
    channelsEmpty: "مفيش زيارات في الفترة دي.",
    moreUrlTitle: "معاملات روابط الإعلانات (UTM)",
    moreUrlSummary: "الصقها في كل إعلان عشان أوردراته تتسجّل باسم الحملة",
    urlDesc: "الصقها في خانة معاملات الرابط في كل إعلان.",
    copy: "انسخ",

    // Links out
    linkSpend: "سجّل مصاريف الإعلانات",
    linkSpendDesc: "اكتب مبلغ أو استورد ملف، ووقّف حملة أو غيّر ميزانيتها",
    linkAccounts: "حسابات الإعلانات",
    linkAccountsOn: "بتتابع {accounts} — زامن المصاريف أو اربط منصة تانية",
    linkAccountsPick: "مربوط — اختار الحسابات اللي تتابعها عشان مصاريفها تيجي",
    linkAccountsProblem: "في مشكلة في الربط — افتحها وشوف السبب",
    linkAccountsOff: "اربط منصة إعلانات والمصاريف تيجي لوحدها",
    accounts_one: "حساب واحد",
    accounts_two: "حسابين",
    accounts_few: "{n} حسابات",
    accounts_other: "{n} حساب",
    linkProfit: "قائمة الأرباح",
    linkProfitDesc: "الربح بعد كل التكاليف: يوم بيوم ومنتج بمنتج",
    linkCosts: "تكاليف المنتجات",
    linkCostsDesc: "تكلفة القطعة والشحن والرسوم اللي الربح بيتحسب منها",
    linkBuilder: "منشئ روابط الإعلانات",
    linkBuilderDesc: "بيكتبلك معاملات UTM لكل إعلان",
  },
} satisfies Messages;

/** The tab's words in the active language, as `useT(ADS_STRINGS)` returns them. */
export type AdsText = Record<keyof (typeof ADS_STRINGS)["en"], string>;
