import { useT, type Messages } from "@/i18n/LocaleContext";

/**
 * Builder chrome copy. Arabic is simple, respectful Egyptian Arabic; the
 * store content inside the preview follows the store language instead.
 */
export const BUILDER_STRINGS = {
  en: {
    back: "Back to websites",
    columnHighlight: "Highlight (featured offer)",
    mediaLibrary: "Image library",
    mediaFromLibrary: "From library",
    mediaAll: "All",
    mediaUploads: "Uploaded",
    mediaProducts: "Products",
    mediaPages: "On your pages",
    mediaEmpty: "No images yet. Upload one and it will show up here.",
    mediaPick: "Use this image",
    mediaPickMany: "Add {n} images",
    mediaNote: "Shows images uploaded to your store, your product photos and images already used on your pages.",
    mediaLoadMore: "Load more",
    mediaDelete: "Delete image",
    mediaDeleteConfirm: "Delete this image from your uploads? Pages or products still using it will show a broken image.",
    mediaDeleted: "Image deleted",
    mediaLoadFailed: "Couldn’t load your uploaded images.",
    mediaRetry: "Try again",
    allNiches: "All",
    themesCount: "{n} themes",
    conflictTitle: "Someone else changed this store",
    conflictBody: "These pages were saved from another tab or by a teammate after you opened the builder.",
    conflictPages: "Changed pages:",
    conflictReload: "Load their version",
    conflictOverwrite: "Save mine over it",
    conflictReloaded: "Loaded the latest version",
    more: "More",
    dragToMove: "Drag to move into any column",
    selectedCount: "{n} sections selected",
    multiHint: "Ctrl or Shift + click to pick several sections",
    copy: "Copy (Ctrl+C)",
    paste: "Paste (Ctrl+V)",
    copied: "Copied — open any page and press Ctrl+V",
    pasted: "Pasted",
    nothingToPaste: "Nothing copied yet",
    clearSelection: "Clear selection",
    deletedMany: "{n} sections deleted",
    pageAddedUndo: "Page added",
    pageRestored: "Page restored",
    openPanels: "Sections, add & theme",
    openInspector: "Settings",
    pages: "Pages",
    addPage: "Add page",
    deletePage: "Delete page",
    deletePageTitle: "Delete this page?",
    deletePageBody: '"{title}" and everything on it will be deleted for good.',
    pageCreated: "Page added",
    pageDeleted: "Page deleted",
    deviceDesktop: "Desktop",
    deviceTablet: "Tablet",
    deviceMobile: "Mobile",
    zoomFit: "Fit to screen",
    zoom100: "Actual size",
    undo: "Undo (Ctrl+Z)",
    redo: "Redo (Ctrl+Shift+Z)",
    statusSaved: "All changes saved",
    statusSaving: "Saving…",
    statusDirty: "Unsaved changes",
    statusError: "Couldn't save",
    save: "Save",
    previewLive: "Preview live store",
    publish: "Publish",
    history: "History",
    previewLang: "Preview language",
    guideOpen: "Guide",

    tabSections: "Sections",
    tabAdd: "Add",
    tabTheme: "Theme",

    sectionsHint: "Drag a section and drop it where you want it",
    noSections: "No sections on this page yet.",
    dragHandle: "Drag {name}",
    hide: "Hide",
    show: "Show",
    duplicate: "Duplicate",
    delete: "Delete",
    rename: "Rename",
    moveUp: "Move up",
    moveDown: "Move down",
    addBelow: "Add section below",
    hiddenBadge: "Hidden",

    searchSections: "Search sections…",
    addSectionAria: "Add {name}",
    addElementAria: "Add element {name}",
    dragToCanvas: "Drag into the preview or press +",
    elementsTitle: "Elements",
    elementsHint: "Select a section first, then drag an element into a column or press +",
    noResults: "No sections match your search.",

    themesTitle: "Themes",
    applyTheme: "Apply",
    currentTheme: "Current",
    colorsTitle: "Colors",
    colorPrimary: "Main color",
    colorSecondary: "Accent",
    colorBackground: "Background",
    colorSurface: "Soft background",
    colorText: "Text",
    colorMuted: "Soft text",
    colorBorder: "Borders",
    buttonTextAuto: "Button text color: automatic",
    colorButtonText: "Button text",
    contrastLow: "Hard to read (contrast {ratio}:1). Try a darker or lighter color.",
    fontsTitle: "Fonts",
    fontArabic: "Arabic font",
    fontLatin: "English font",
    baseSize: "Text size",
    shapeTitle: "Shape & buttons",
    radius: "Corners",
    buttonStyle: "Button style",
    buttonShape: "Button shape",
    density: "Spacing",
    headerTitle: "Header",
    headerLayout: "Logo position",
    sticky: "Sticky header",
    showSearch: "Show search",
    announcement: "Announcement bar",
    announcementText: "Announcement text",
    announcementLink: "Announcement link",
    announcementBg: "Bar color",
    announcementFg: "Bar text color",
    footerTitle: "Footer",
    footerColumns: "Columns",
    footerAbout: "About text",
    showSocial: "Show social links",
    socialLinks: "Social links",
    platform: "Platform",
    url: "Link",
    addLink: "Add link",
    paymentBadges: "Payment badges (comma separated)",
    copyright: "Copyright text (empty = automatic)",
    productCardTitle: "Product cards",
    imageRatio: "Image shape",
    showCompare: "Show price before discount",
    quickOrder: "Quick order button",
    themeTooLarge: "Theme settings are too large to save ({size} of 5000 characters). Shorten the footer or announcement text.",
    themeTooManyKeys: "Theme settings have too many fields (max 50).",
    optSharp: "Sharp",
    optSoft: "Soft",
    optRounded: "Rounded",
    optPill: "Pill",
    optSolid: "Solid",
    optOutline: "Outline",
    optSoftBtn: "Soft",
    optSquare: "Square",
    optRoundedBtn: "Rounded",
    optPillBtn: "Pill",
    optCompact: "Compact",
    optComfortable: "Comfortable",
    optAiry: "Airy",
    optLogoStart: "Start",
    optLogoCenter: "Center",
    optRatioSquare: "Square",
    optRatioPortrait: "Portrait",

    applyThemeTitle: "Apply the {name} theme?",
    applyThemeBody: "This changes colors and fonts, and can also replace your pages.",
    applyStyleOnly: "Apply style only",
    applyStylePages: "Apply style + replace pages",
    applyPagesNote: "Replaces Home, About, Contact and the product/collection templates. You can undo.",
    themeApplied: "Theme applied",

    previewTitle: "Store preview",
    emptyPageTitle: "This page is empty",
    emptyPageBody: "Start with a ready theme or add your first section.",
    chooseTheme: "Choose a theme",
    addFirstSection: "Add your first section",
    dropHere: "Drop here",
    kindSection: "Section",
    kindRow: "Row",
    kindColumn: "Column",
    kindElement: "Element",

    inspectorTitle: "Settings",
    nothingSelected: "Click anything in the preview to edit it",
    sectionLabel: "Name in the list",
    variantLabel: "Design",
    tone: "Background style",
    width: "Content width",
    padding: "Spacing",
    align: "Alignment",
    backgroundImage: "Background image",
    decor: "Decorative shapes",
    anchor: "Anchor id (for #links)",
    anchorHint: "English letters, numbers and dashes only",
    hideSection: "Hide on the store",
    hideOnMobile: "Hide on mobile",
    hideOnDesktop: "Hide on desktop",
    rowLayout: "Layout",
    columns: "Columns",
    mobileColumns: "Columns on mobile",
    verticalCenter: "Center vertically",
    reverse: "Swap sides",
    columnCard: "Show as card",
    columnSpan: "Width (of 12)",
    rowsInSection: "Rows",
    columnsInRow: "Columns",
    elementsInColumn: "Elements",
    deletedToast: "Deleted",
    undoAction: "Undo",
    toneDefault: "Plain",
    toneSurface: "Light",
    toneSoft: "Soft color",
    tonePrimary: "Main color",
    toneSecondary: "Accent",
    toneDark: "Dark",
    toneGradient: "Gradient",
    widthNarrow: "Narrow",
    widthDefault: "Normal",
    widthWide: "Wide",
    widthFull: "Full",
    padNone: "None",
    padSm: "S",
    padMd: "M",
    padLg: "L",
    alignStart: "Start",
    alignCenter: "Center",
    layoutGrid: "Grid",
    layoutCards: "Cards",
    layoutSteps: "Steps",
    layoutLogos: "Logos",

    chooseLink: "Pick a link…",
    linkPages: "Pages",
    linkProducts: "Products",
    linkCollections: "Collections",
    linkAllProducts: "All products",
    linkTrack: "Track order",
    linkWhatsapp: "WhatsApp chat",
    linkExternal: "External link (https://…)",
    linkInvalid: "This link won't work. Use /page, https://…, tel: or mailto:",
    whatsappNumber: "WhatsApp number with country code",
    addItem: "Add",
    removeItem: "Remove",
    question: "Question",
    answer: "Answer",
    noProduct: "Newest product (automatic)",
    allCollections: "All products",
    tableHint: "The first row is the header",
    addRow: "Add row",
    addColumn: "Add column",
    endsAtPast: "Pick a future date — the countdown hides once it ends.",
    required: "Needed to show on the store",
    richBullet: "• Bullet",
    richParagraph: "New paragraph",
    richFormatNote: "Shows as plain text on the store — use new lines and • bullets for structure.",
    none: "None",

    publishTitle: "Publish your store?",
    publishBody: "We'll save your changes first, then every page goes live.",
    publishing: "Publishing…",
    published: "Your store is live — version {n}",
    cantPublish: "The store can't be published yet:",
    saveBlocked: "Fix these before saving:",

    historyTitle: "Published versions",
    historyEmpty: "Nothing published yet.",
    historyLive: "Live",
    historyVersion: "Version {n}",
    historyPages: "{n} pages",
    rollback: "Make live",
    rollbackConfirm: "Yes, make version {n} live",
    rollbackBody: "The live store will show this version. Your current draft stays as it is.",
    rolledBack: "Version {n} is live again",

    guideTitle: "Build your store in 4 steps",
    guideProgress: "{done} of 4 done",
    guideStep1: "Choose a theme",
    guideStep2: "Change colors and font",
    guideStep3: "Edit texts and images",
    guideStep4: "Publish your store",
    guideStep1Body: "Pick a ready look from the Theme tab.",
    guideStep2Body: "Make it match your brand.",
    guideStep3Body: "Click any text in the preview and type.",
    guideStep4Body: "When you're happy, publish it.",
    guideGo: "Go",
    guideDismiss: "Hide guide",

    err402: "Your subscription isn't active, so this is paused. Renew it from Billing.",
    err403: "You don't have permission to do this. Ask the store owner.",
    err409: "This conflicts with something that already exists (for example a page with the same link).",
    err422: "Some data isn't valid:",
    loadFailed: "Couldn't load the store.",
    retry: "Try again",
    leaveTitle: "Leave the builder?",
    leaveBody: "Some changes aren't saved yet.",
    saveAndLeave: "Save and leave",
    leaveAnyway: "Leave without saving",
    smallScreenTitle: "The builder works best on a laptop",
    smallScreenBody: "Open it on a wider screen for the best experience.",
    continueAnyway: "Continue anyway",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading your store…",
  },
  ar: {
    back: "رجوع للمواقع",
    columnHighlight: "تمييز (العرض المقترح)",
    mediaLibrary: "مكتبة الصور",
    mediaFromLibrary: "من المكتبة",
    mediaAll: "الكل",
    mediaUploads: "اللي رفعتها",
    mediaProducts: "صور المنتجات",
    mediaPages: "في صفحاتك",
    mediaEmpty: "لسه مفيش صور. ارفع صورة وهتظهر هنا.",
    mediaPick: "استخدم الصورة دي",
    mediaPickMany: "ضيف {n} صور",
    mediaNote: "بتعرض الصور اللي رفعتها على متجرك، وصور منتجاتك، والصور المستخدمة في صفحاتك.",
    mediaLoadMore: "هات أكتر",
    mediaDelete: "امسح الصورة",
    mediaDeleteConfirm: "تمسح الصورة دي من الصور اللي رفعتها؟ أي صفحة أو منتج لسه بيستخدمها هتظهر فيه الصورة بايظة.",
    mediaDeleted: "اتمسحت الصورة",
    mediaLoadFailed: "مقدرناش نجيب الصور اللي رفعتها.",
    mediaRetry: "جرّب تاني",
    allNiches: "الكل",
    themesCount: "{n} ثيم",
    conflictTitle: "فيه حد تاني عدّل المتجر",
    conflictBody: "الصفحات دي اتحفظت من تبويب تاني أو من حد في الفريق بعد ما فتحت المحرر.",
    conflictPages: "الصفحات اللي اتغيرت:",
    conflictReload: "حمّل نسختهم",
    conflictOverwrite: "احفظ نسختي فوقها",
    conflictReloaded: "اتحمّلت آخر نسخة",
    more: "المزيد",
    dragToMove: "اسحبه لأي عمود",
    selectedCount: "{n} أقسام متحددة",
    multiHint: "دوس Ctrl أو Shift مع الضغط علشان تختار كذا قسم",
    copy: "نسخ (Ctrl+C)",
    paste: "لصق (Ctrl+V)",
    copied: "اتنسخ — افتح أي صفحة ودوس Ctrl+V",
    pasted: "اتلزق",
    nothingToPaste: "لسه مانسختش حاجة",
    clearSelection: "إلغاء التحديد",
    deletedMany: "اتمسح {n} أقسام",
    pageAddedUndo: "الصفحة اتضافت",
    pageRestored: "الصفحة رجعت",
    openPanels: "الأقسام والإضافة والثيم",
    openInspector: "الإعدادات",
    pages: "الصفحات",
    addPage: "ضيف صفحة",
    deletePage: "امسح الصفحة",
    deletePageTitle: "تمسح الصفحة دي؟",
    deletePageBody: "صفحة «{title}» وكل اللي فيها هتتمسح خالص.",
    pageCreated: "الصفحة اتضافت",
    pageDeleted: "الصفحة اتمسحت",
    deviceDesktop: "كمبيوتر",
    deviceTablet: "تابلت",
    deviceMobile: "موبايل",
    zoomFit: "على قد الشاشة",
    zoom100: "الحجم الحقيقي",
    undo: "تراجع (Ctrl+Z)",
    redo: "إعادة (Ctrl+Shift+Z)",
    statusSaved: "كل التغييرات محفوظة",
    statusSaving: "بيحفظ…",
    statusDirty: "فيه تعديلات",
    statusError: "الحفظ ماتمّش",
    save: "احفظ",
    previewLive: "شوف المتجر",
    publish: "انشر",
    history: "النسخ السابقة",
    previewLang: "لغة المعاينة",
    guideOpen: "الدليل",

    tabSections: "الأقسام",
    tabAdd: "إضافة",
    tabTheme: "الثيم",

    sectionsHint: "اسحب القسم وحطه في المكان اللي عايزه",
    noSections: "مفيش أقسام في الصفحة دي لسه.",
    dragHandle: "اسحب {name}",
    hide: "إخفاء",
    show: "إظهار",
    duplicate: "تكرار",
    delete: "مسح",
    rename: "غيّر الاسم",
    moveUp: "لفوق",
    moveDown: "لتحت",
    addBelow: "ضيف قسم تحته",
    hiddenBadge: "مخفي",

    searchSections: "دوّر على قسم…",
    addSectionAria: "ضيف {name}",
    addElementAria: "ضيف عنصر {name}",
    dragToCanvas: "اسحبه للمعاينة أو دوس +",
    elementsTitle: "عناصر",
    elementsHint: "اختار قسم الأول، وبعدين اسحب العنصر جوه عمود أو دوس +",
    noResults: "مفيش أقسام بالاسم ده.",

    themesTitle: "الثيمات",
    applyTheme: "طبّق",
    currentTheme: "الحالي",
    colorsTitle: "الألوان",
    colorPrimary: "اللون الأساسي",
    colorSecondary: "اللون المساعد",
    colorBackground: "الخلفية",
    colorSurface: "خلفية هادية",
    colorText: "النص",
    colorMuted: "نص خفيف",
    colorBorder: "الحدود",
    buttonTextAuto: "لون كلام الزرار: تلقائي",
    colorButtonText: "كلام الزرار",
    contrastLow: "صعب يتقري (التباين {ratio}:1). جرّب لون أغمق أو أفتح.",
    fontsTitle: "الخطوط",
    fontArabic: "الخط العربي",
    fontLatin: "الخط الإنجليزي",
    baseSize: "حجم الكلام",
    shapeTitle: "الشكل والزراير",
    radius: "الحواف",
    buttonStyle: "شكل الزرار",
    buttonShape: "حواف الزرار",
    density: "المسافات",
    headerTitle: "الهيدر",
    headerLayout: "مكان اللوجو",
    sticky: "الهيدر ثابت فوق",
    showSearch: "إظهار البحث",
    announcement: "شريط الإعلان",
    announcementText: "كلام الإعلان",
    announcementLink: "لينك الإعلان",
    announcementBg: "لون الشريط",
    announcementFg: "لون كلام الشريط",
    footerTitle: "الفوتر",
    footerColumns: "عدد الأعمدة",
    footerAbout: "نبذة عن المتجر",
    showSocial: "إظهار السوشيال ميديا",
    socialLinks: "لينكات السوشيال",
    platform: "المنصة",
    url: "اللينك",
    addLink: "ضيف لينك",
    paymentBadges: "طرق الدفع (افصل بينها بفاصلة)",
    copyright: "حقوق النشر (سيبه فاضي يتكتب تلقائي)",
    productCardTitle: "كروت المنتجات",
    imageRatio: "شكل الصورة",
    showCompare: "إظهار السعر قبل الخصم",
    quickOrder: "زرار اطلب بسرعة",
    themeTooLarge: "إعدادات الثيم كبيرة ومش هتتحفظ ({size} من 5000 حرف). قصّر كلام الفوتر أو الإعلان.",
    themeTooManyKeys: "إعدادات الثيم فيها حقول كتير (أقصى حاجة 50).",
    optSharp: "حادة",
    optSoft: "ناعمة",
    optRounded: "مدوّرة",
    optPill: "مدوّرة خالص",
    optSolid: "مليان",
    optOutline: "إطار",
    optSoftBtn: "هادي",
    optSquare: "مربع",
    optRoundedBtn: "مدوّر",
    optPillBtn: "كبسولة",
    optCompact: "قريبة",
    optComfortable: "مريحة",
    optAiry: "واسعة",
    optLogoStart: "على الجنب",
    optLogoCenter: "في النص",
    optRatioSquare: "مربعة",
    optRatioPortrait: "طولية",

    applyThemeTitle: "تطبّق ثيم {name}؟",
    applyThemeBody: "هيغيّر الألوان والخطوط، وممكن كمان يستبدل صفحاتك.",
    applyStyleOnly: "طبّق الشكل بس",
    applyStylePages: "طبّق الشكل واستبدل الصفحات",
    applyPagesNote: "هيستبدل الرئيسية ومن نحن وتواصل معنا وقوالب المنتج والأقسام. تقدر تتراجع.",
    themeApplied: "الثيم اتطبّق",

    previewTitle: "معاينة المتجر",
    emptyPageTitle: "الصفحة دي فاضية",
    emptyPageBody: "ابدأ بثيم جاهز أو ضيف أول قسم.",
    chooseTheme: "اختار ثيم",
    addFirstSection: "ضيف أول قسم",
    dropHere: "حطه هنا",
    kindSection: "قسم",
    kindRow: "صف",
    kindColumn: "عمود",
    kindElement: "عنصر",

    inspectorTitle: "الإعدادات",
    nothingSelected: "دوس على أي حاجة في المعاينة علشان تعدّلها",
    sectionLabel: "الاسم في القائمة",
    variantLabel: "التصميم",
    tone: "لون الخلفية",
    width: "عرض المحتوى",
    padding: "المسافة",
    align: "المحاذاة",
    backgroundImage: "صورة الخلفية",
    decor: "أشكال زينة",
    anchor: "اسم الرابط (لروابط #)",
    anchorHint: "حروف إنجليزي وأرقام وشرطات بس",
    hideSection: "إخفاء من المتجر",
    hideOnMobile: "إخفاء على الموبايل",
    hideOnDesktop: "إخفاء على الكمبيوتر",
    rowLayout: "الترتيب",
    columns: "الأعمدة",
    mobileColumns: "الأعمدة على الموبايل",
    verticalCenter: "في النص رأسيًا",
    reverse: "اعكس الجهات",
    columnCard: "اعرضه ككارت",
    columnSpan: "العرض (من 12)",
    rowsInSection: "الصفوف",
    columnsInRow: "الأعمدة",
    elementsInColumn: "العناصر",
    deletedToast: "اتمسح",
    undoAction: "تراجع",
    toneDefault: "عادي",
    toneSurface: "فاتح",
    toneSoft: "لون هادي",
    tonePrimary: "اللون الأساسي",
    toneSecondary: "اللون المساعد",
    toneDark: "غامق",
    toneGradient: "متدرّج",
    widthNarrow: "ضيق",
    widthDefault: "عادي",
    widthWide: "عريض",
    widthFull: "بعرض الشاشة",
    padNone: "من غير",
    padSm: "صغيرة",
    padMd: "متوسطة",
    padLg: "كبيرة",
    alignStart: "البداية",
    alignCenter: "النص",
    layoutGrid: "شبكة",
    layoutCards: "كروت",
    layoutSteps: "خطوات",
    layoutLogos: "شعارات",

    chooseLink: "اختار لينك…",
    linkPages: "الصفحات",
    linkProducts: "المنتجات",
    linkCollections: "الأقسام",
    linkAllProducts: "كل المنتجات",
    linkTrack: "تتبع الطلب",
    linkWhatsapp: "شات واتساب",
    linkExternal: "لينك خارجي (https://…)",
    linkInvalid: "اللينك ده مش هيشتغل. استخدم /صفحة أو https://… أو tel: أو mailto:",
    whatsappNumber: "رقم الواتساب بكود الدولة",
    addItem: "ضيف",
    removeItem: "شيل",
    question: "السؤال",
    answer: "الإجابة",
    noProduct: "أحدث منتج (تلقائي)",
    allCollections: "كل المنتجات",
    tableHint: "أول صف هو العناوين",
    addRow: "ضيف صف",
    addColumn: "ضيف عمود",
    endsAtPast: "اختار ميعاد جاي — العداد بيختفي بعد ما يخلص.",
    required: "لازم يتملي علشان يظهر في المتجر",
    richBullet: "• نقطة",
    richParagraph: "فقرة جديدة",
    richFormatNote: "بيظهر في المتجر كنص عادي — استخدم سطور جديدة ونقط • للتنظيم.",
    none: "من غير",

    publishTitle: "تنشر متجرك؟",
    publishBody: "هنحفظ تعديلاتك الأول، وبعدين كل الصفحات هتظهر للناس.",
    publishing: "بينشر…",
    published: "اتنشر المتجر — النسخة {n}",
    cantPublish: "المتجر مش هينفع يتنشر لسه:",
    saveBlocked: "صلّح دول الأول قبل الحفظ:",

    historyTitle: "النسخ المنشورة",
    historyEmpty: "لسه مفيش حاجة اتنشرت.",
    historyLive: "شغّالة دلوقتي",
    historyVersion: "النسخة {n}",
    historyPages: "{n} صفحات",
    rollback: "رجّعها",
    rollbackConfirm: "أيوه، رجّع النسخة {n}",
    rollbackBody: "المتجر هيعرض النسخة دي. المسودة اللي بتعدّلها هتفضل زي ما هي.",
    rolledBack: "النسخة {n} رجعت تشتغل",

    guideTitle: "ابني متجرك في 4 خطوات",
    guideProgress: "خلّصت {done} من 4",
    guideStep1: "اختار ثيم",
    guideStep2: "غيّر الألوان والخط",
    guideStep3: "عدّل النصوص والصور",
    guideStep4: "انشر متجرك",
    guideStep1Body: "اختار شكل جاهز من تبويب الثيم.",
    guideStep2Body: "خليه شبه البراند بتاعك.",
    guideStep3Body: "دوس على أي كلام في المعاينة واكتب.",
    guideStep4Body: "لما يعجبك، انشره.",
    guideGo: "يلا",
    guideDismiss: "اخفي الدليل",

    err402: "اشتراكك مش مفعّل، علشان كده ده واقف. جدده من صفحة الاشتراك.",
    err403: "معندكش صلاحية تعمل ده. اطلب من صاحب المتجر.",
    err409: "فيه تعارض مع حاجة موجودة (زي صفحة بنفس اللينك).",
    err422: "فيه بيانات مش صحيحة:",
    loadFailed: "مقدرناش نحمّل المتجر.",
    retry: "جرّب تاني",
    leaveTitle: "تخرج من المحرر؟",
    leaveBody: "فيه تعديلات لسه متحفظتش.",
    saveAndLeave: "احفظ واخرج",
    leaveAnyway: "اخرج من غير حفظ",
    smallScreenTitle: "المحرر أحسن على لابتوب",
    smallScreenBody: "افتحه على شاشة أعرض علشان تشتغل براحتك.",
    continueAnyway: "كمّل برضه",
    cancel: "إلغاء",
    close: "قفل",
    loading: "بنحمّل متجرك…",
  },
} satisfies Messages;

export type BuilderStrings = (typeof BUILDER_STRINGS)["en"];

export function useBuilderT(): BuilderStrings {
  return useT(BUILDER_STRINGS);
}
