import type { Messages } from "@/i18n/LocaleContext";

/** Frequently bought together (handoff 223): the settings card on the cross-sell screen and the product page's "Bought with". */
export const BOUGHT_TOGETHER_STRINGS = {
  en: {
    // settings (Offers → Cross-sell)
    title: "Bought together",
    description:
      "When no rule of yours fits, the store suggests what real orders show was bought together. The pairs are worked out every night, and each time you save here.",
    enabled: "Suggest what was bought together",
    enabledHint: "Off: only your own rules suggest products.",
    windowDays: "Look back (days)",
    windowDaysHint: "Orders older than this are left out. 30 to 1,095.",
    minOrders: "Minimum shared orders",
    minOrdersHint: "Two products are suggested together from this many orders. 1 to 100.",
    excluded: "Never suggest these products",
    excludedHint: "They stay out of the worked-out suggestions. Your own rules can still show them.",
    windowDaysError: "A whole number from 30 to 1,095.",
    minOrdersError: "A whole number from 1 to 100.",
    excludedGone: "A product in the list is no longer in this store. The list was read again.",
    pairs_one: "1 pair of products",
    pairs_other: "{n} pairs of products",
    lastUpdated: "Last updated",
    never: "Not worked out yet",
    updateNow: "Update now",
    updating: "Updating…",
    updatedToast: "Updated.",
    save: "Save",
    saving: "Saving…",
    discard: "Discard",
    savedToast: "Saved — the suggestions were worked out again.",
    viewOnly: "Changing these settings needs permission to manage products.",
    // the product page
    productTitle: "Bought with",
    productHint: "What this product was bought with, from real orders. Shoppers see them as “Frequently bought together” on its page.",
    inOrders_one: "in 1 order",
    inOrders_other: "in {n} orders",
    dontSuggest: "Don't suggest",
    dontSuggestName: "Don't suggest {name}",
    notSuggested: "Not suggested",
    switchedOff: "Bought-together suggestions are switched off for this store.",
    pin: "Pin products",
    pinHint: "Choose the products yourself: a rule of yours wins over the worked-out list.",
    pinned: "Pinned by your rule “{rule}”",
    pinnedManage: "Manage in Cross-sell",
    toggleFailed: "That wasn't saved — try again.",
    settingsLink: "Bought-together settings",
  },
  ar: {
    title: "بيتشروا مع بعض",
    description:
      "لما مفيش قاعدة من قواعدك تنطبق، المتجر بيقترح اللي الأوردرات الحقيقية بتقول إنه اتشرى مع بعض. الأزواج بتتحسب كل ليلة، ومع كل حفظ هنا.",
    enabled: "اقترح اللي اتشرى مع بعض",
    enabledHint: "لو مقفول: قواعدك انت بس اللي بتقترح منتجات.",
    windowDays: "آخر كام يوم",
    windowDaysHint: "الأوردرات الأقدم من كده مش بتتحسب. من 30 لـ 1,095.",
    minOrders: "أقل عدد طلبات مشتركة",
    minOrdersHint: "المنتجين بيتقترحوا مع بعض من أول العدد ده من الأوردرات. من 1 لـ 100.",
    excluded: "متقترحش المنتجات دي أبدًا",
    excludedHint: "مش بتدخل في الاقتراحات المحسوبة. قواعدك انت لسه تقدر تعرضها.",
    windowDaysError: "رقم صحيح من 30 لـ 1,095.",
    minOrdersError: "رقم صحيح من 1 لـ 100.",
    excludedGone: "منتج في القايمة مبقاش في المتجر. القايمة اتقرت من جديد.",
    pairs_one: "زوج منتجات واحد",
    pairs_two: "زوجين منتجات",
    pairs_few: "{n} أزواج منتجات",
    pairs_other: "{n} زوج منتجات",
    lastUpdated: "آخر تحديث",
    never: "لسه متحسبتش",
    updateNow: "حدّث دلوقتي",
    updating: "بنحدّث…",
    updatedToast: "اتحدّثت.",
    save: "حفظ",
    saving: "بنحفظ…",
    discard: "تجاهل",
    savedToast: "اتحفظ — الاقتراحات اتحسبت من جديد.",
    viewOnly: "تغيير الإعدادات دي محتاج صلاحية إدارة المنتجات.",
    productTitle: "بيتشري مع",
    productHint: "المنتج ده اتشرى مع إيه، من أوردرات حقيقية. العميل بيشوفهم في صفحته تحت «بيتشروا مع بعض».",
    inOrders_one: "في طلب واحد",
    inOrders_two: "في طلبين",
    inOrders_few: "في {n} طلبات",
    inOrders_other: "في {n} طلب",
    dontSuggest: "متقترحوش",
    dontSuggestName: "متقترحش {name}",
    notSuggested: "مش بيتقترح",
    switchedOff: "اقتراحات «بيتشروا مع بعض» مقفولة للمتجر ده.",
    pin: "ثبّت منتجات",
    pinHint: "اختار المنتجات بنفسك: قاعدتك بتكسب القايمة المحسوبة.",
    pinned: "متثبتة بقاعدتك «{rule}»",
    pinnedManage: "عدّلها من المنتجات المقترحة",
    toggleFailed: "ما اتحفظش — جرّب تاني.",
    settingsLink: "إعدادات «بيتشروا مع بعض»",
  },
} satisfies Messages;
