import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty & rewards → VIP tiers, and the tier card on a
 * customer's page (handoff 218). Arabic is the merchant's Egyptian, with the
 * handoff's wording.
 */
export const VIP_STRINGS = {
  en: {
    // page
    title: "VIP tiers",
    description: "Customers move up by what they spent, or how many orders they placed, on delivered orders — and each tier gives them something.",
    stateOn: "Running",
    stateOff: "Off",
    accountsOff: "Customer accounts are off, so nobody gets a tier's perks: the store has to know who is ordering, and that needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "How customers move up",
    enable: "Turn on VIP tiers",
    enableHintOn: "A signed-in customer gets their tier's perks at checkout.",
    enableHintOff: "Off: nobody gets a tier's perks. The tiers below are kept as they are.",
    basis: "Tiers are reached",
    basisSpent: "By amount spent",
    basisSpentHint: "What the customer paid on delivered orders, less anything refunded.",
    basisOrders: "By number of orders",
    basisOrdersHint: "How many of the customer's orders were delivered.",
    window: "Count the last",
    windowUnit: "days",
    windowHint: "Only orders from this many days back count, so a customer who stops buying moves down. Leave it empty to count every order ever.",
    windowError: "Enter a number of days from 30 to 1825, or leave it empty.",
    tiersTitle: "The tiers",
    tiersHint: "Up to {max} tiers. A customer is in the highest tier they reach.",
    tierN: "Tier {n}",
    nameAr: "Name in Arabic",
    nameEn: "Name in English",
    nameError: "Write the tier's name in Arabic or in English.",
    thresholdSpent: "Reached at",
    thresholdOrders: "Reached at (orders)",
    thresholdSpentError: "Enter the amount this tier starts from.",
    thresholdOrdersError: "Enter a whole number of orders, from 1.",
    thresholdDuplicate: "Two tiers can't start from the same number.",
    percentOff: "Percent off",
    percentHint: "0 to 50. Off the normal price of products.",
    percentError: "Enter a whole number from 0 to 50.",
    percentUnit: "%",
    freeShipping: "Free shipping",
    multiplier: "Loyalty points",
    multiplierHint: "Points earned on an order, multiplied.",
    multiplierNone: "×1 (no change)",
    multiplierOption: "×{n}",
    removeTier: "Remove tier {n}",
    addTier: "Add a tier",
    noTiers: "No tiers yet. Add the first one — Silver from a few orders, say.",
    tiersRequired: "Add at least one tier before turning VIP tiers on.",
    summarySpent: "Customers who spent {amount} on delivered orders{window} get: {perks}.",
    summaryOrders: "Customers with {orders} delivered{window} get: {perks}.",
    summaryWindow: " in the last {days}",
    perkPercent: "{n}% off",
    perkShipping: "free shipping",
    perkPoints: "{n}× loyalty points",
    perkNone: "the badge only — add a perk",
    perkJoin: ", ",
    loyaltyOff: "The loyalty programme isn't running, so the points multiplier does nothing until you turn it on.",
    loyaltyOffAction: "Open loyalty points",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. VIP tiers are running.",
    savedOff: "Saved. VIP tiers are off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "A customer who buys more moves up a tier, and each tier gives them a discount, free shipping or more points.",
    tierSummarySpent: "From {amount} · {perks}",
    tierSummaryOrders: "From {orders} · {perks}",
    tierNoThreshold: "Where it starts isn't set yet",
    tierNeedsFix: "Needs a fix",
    tierRemoved: "{name} removed. Save to keep the change.",
    tiersFull: "You have the most tiers a store can have ({max}).",
    membersLink: "A customer's tier",
    membersLinkHint: "On the customer's page: the tier they are in and how far the next one is.",
    // customer card
    cardTitle: "VIP tier",
    cardHint: "From this customer's delivered orders.",
    noTier: "No tier yet",
    topTier: "At the highest tier.",
    perks: "Gets: {perks}",
    noPerks: "This tier gives nothing yet.",
    standingSpent: "{orders} delivered, worth {amount}",
    nextSpent: "{amount} more to {name}",
    nextOrders_one: "1 more order to {name}",
    nextOrders_other: "{n} more orders to {name}",
    progress: "Progress to {name}",
    manage: "Edit tiers",
  },
  ar: {
    // page
    title: "مستويات VIP",
    description: "العملاء بيطلعوا مستوى حسب اللي دفعوه، أو عدد أوردراتهم اللي اتسلّمت — وكل مستوى بيدّيهم ميزة.",
    stateOn: "شغّالة",
    stateOff: "مقفولة",
    accountsOff: "حسابات العملاء مقفولة، فمحدش هياخد مميزات مستواه: المتجر لازم يعرف مين اللي بيشتري، وده محتاج العميل يسجّل دخول.",
    accountsOffAction: "شغّل حسابات العملاء",
    settingsTitle: "العملاء بيطلعوا مستوى إزاي",
    enable: "شغّل مستويات VIP",
    enableHintOn: "العميل اللي مسجّل دخول بياخد مميزات مستواه في صفحة الدفع.",
    enableHintOff: "مقفولة: محدش بياخد مميزات. المستويات اللي تحت محفوظة زي ما هي.",
    basis: "العميل بيوصل للمستوى",
    basisSpent: "حسب المبلغ",
    basisSpentHint: "اللي العميل دفعه في الأوردرات اللي اتسلّمت، من غير اللي اترجّعله.",
    basisOrders: "حسب عدد الأوردرات",
    basisOrdersHint: "عدد أوردرات العميل اللي اتسلّمت.",
    window: "احسب آخر",
    windowUnit: "يوم",
    windowHint: "الأوردرات اللي في المدة دي بس هي اللي بتتحسب، فالعميل اللي يبطّل يشتري ينزل مستوى. سيبه فاضي عشان تتحسب كل أوردراته من الأول.",
    windowError: "اكتب عدد أيام من ٣٠ لـ ١٨٢٥، أو سيبه فاضي.",
    tiersTitle: "المستويات",
    tiersHint: "لحد {max} مستويات. العميل بيبقى في أعلى مستوى وصله.",
    tierN: "المستوى {n}",
    nameAr: "الاسم بالعربي",
    nameEn: "الاسم بالإنجليزي",
    nameError: "اكتب اسم المستوى بالعربي أو بالإنجليزي.",
    thresholdSpent: "بيبدأ من",
    thresholdOrders: "بيبدأ من (عدد الأوردرات)",
    thresholdSpentError: "اكتب المبلغ اللي المستوى ده بيبدأ منه.",
    thresholdOrdersError: "اكتب عدد أوردرات صحيح، من ١.",
    thresholdDuplicate: "مينفعش مستويين يبدأوا من نفس الرقم.",
    percentOff: "نسبة الخصم",
    percentHint: "من ٠ لـ ٥٠. من سعر المنتجات العادي.",
    percentError: "اكتب رقم صحيح من ٠ لـ ٥٠.",
    percentUnit: "٪",
    freeShipping: "شحن مجاني",
    multiplier: "نقط الولاء",
    multiplierHint: "النقط اللي بيكسبها من الأوردر، مضروبة.",
    multiplierNone: "×١ (من غير تغيير)",
    multiplierOption: "×{n}",
    removeTier: "شيل المستوى {n}",
    addTier: "ضيف مستوى",
    noTiers: "مفيش مستويات لسه. ضيف أول مستوى — فضي من كام أوردر مثلًا.",
    tiersRequired: "ضيف مستوى واحد على الأقل قبل ما تشغّل مستويات VIP.",
    summarySpent: "العملاء اللي دفعوا {amount} في أوردرات اتسلّمت{window} بياخدوا: {perks}.",
    summaryOrders: "العملاء اللي اتسلّملهم {orders}{window} بياخدوا: {perks}.",
    summaryWindow: " في آخر {days}",
    perkPercent: "خصم {n}٪",
    perkShipping: "شحن مجاني",
    perkPoints: "نقط ولاء ×{n}",
    perkNone: "الشارة بس — ضيف ميزة",
    perkJoin: "، ",
    loyaltyOff: "برنامج الولاء مش شغّال، فمضاعفة النقط مش هتعمل حاجة لحد ما تشغّله.",
    loyaltyOffAction: "افتح نقط الولاء",
    save: "احفظ",
    saving: "بنحفظ…",
    saved: "اتحفظ.",
    savedOn: "اتحفظ. مستويات VIP شغّالة.",
    savedOff: "اتحفظ. مستويات VIP مقفولة.",
    fixFields: "راجع الخانات المتعلّم عليها.",
    customerGets: "العميل اللي بيشتري أكتر بيطلع مستوى، وكل مستوى بيدّيه خصم أو شحن مجاني أو نقط أكتر.",
    tierSummarySpent: "من {amount} · {perks}",
    tierSummaryOrders: "من {orders} · {perks}",
    tierNoThreshold: "لسه ما حدّدتش بيبدأ من كام",
    tierNeedsFix: "محتاج تعديل",
    tierRemoved: "{name} اتشال. احفظ عشان التغيير يثبت.",
    tiersFull: "وصلت لأقصى عدد مستويات ({max}).",
    membersLink: "مستوى عميل معيّن",
    membersLinkHint: "في صفحة العميل: هو في أنهي مستوى وفاضله كام على اللي بعده.",
    // customer card
    cardTitle: "مستوى VIP",
    cardHint: "من أوردرات العميل ده اللي اتسلّمت.",
    noTier: "لسه ما وصلش لأي مستوى",
    topTier: "في أعلى مستوى.",
    perks: "بياخد: {perks}",
    noPerks: "المستوى ده لسه مفيهوش مميزات.",
    standingSpent: "اتسلّمله {orders} بقيمة {amount}",
    nextSpent: "فاضل {amount} لـ {name}",
    nextOrders_one: "فاضل أوردر واحد لـ {name}",
    nextOrders_two: "فاضل أوردرين لـ {name}",
    nextOrders_few: "فاضل {n} أوردرات لـ {name}",
    nextOrders_other: "فاضل {n} أوردر لـ {name}",
    progress: "التقدّم لـ {name}",
    manage: "تعديل المستويات",
  },
} satisfies Messages;

export type VipStrings = (typeof VIP_STRINGS)["en"];
