import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty & rewards → VIP tiers, and the tier card on a
 * customer's page. Arabic is formal, as the rest of the dashboard.
 */
export const VIP_STRINGS = {
  en: {
    // page
    title: "VIP tiers",
    description: "Customers move up by what they spent, or how many orders they placed, on delivered orders, and each tier gives them something.",
    stateOn: "Running",
    stateOff: "Off",
    accountsOff: "Customer accounts are off, so nobody gets a tier's perks: the store has to know who is ordering, and that needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "How customers move up",
    enable: "Turn on VIP tiers",
    enableHintOn: "A signed-in customer gets their tier's perks at checkout.",
    enableHintOff: "Off: nobody gets a tier's perks. The tiers below are kept as they are.",
    basis: "Tiers are reached",
    basisSpent: "By amount spent",
    basisSpentHint: "What the customer paid on delivered orders, less anything refunded.",
    basisOrders: "By number of orders",
    basisOrdersHint: "How many of the customer's orders were delivered.",
    window: "Count the last",
    windowUnit: "days",
    windowHint: "Only orders from this many days back count, so a customer who stops buying moves down. Leave it empty to count every order ever.",
    windowError: "Enter a number of days from 30 to 1825, or leave it empty.",
    tiersTitle: "The tiers",
    tiersHint: "Up to {max} tiers. A customer is in the highest tier they reach.",
    tierN: "Tier {n}",
    nameAr: "Name in Arabic",
    nameEn: "Name in English",
    nameError: "Write the tier's name in Arabic or in English.",
    thresholdSpent: "Reached at",
    thresholdOrders: "Reached at (orders)",
    thresholdSpentError: "Enter the amount this tier starts from.",
    thresholdOrdersError: "Enter a whole number of orders, from 1.",
    thresholdDuplicate: "Two tiers can't start from the same number.",
    percentOff: "Percent off",
    percentHint: "0 to 50. Off the normal price of products.",
    percentError: "Enter a whole number from 0 to 50.",
    percentUnit: "%",
    freeShipping: "Free shipping",
    multiplier: "Loyalty points",
    multiplierHint: "Points earned on an order, multiplied.",
    multiplierNone: "×1 (no change)",
    multiplierOption: "×{n}",
    removeTier: "Remove tier {n}",
    addTier: "Add a tier",
    noTiers: "No tiers yet. Add the first one: Silver from a few orders, say.",
    tiersRequired: "Add at least one tier before turning VIP tiers on.",
    summarySpent: "Customers who spent {amount} on delivered orders{window} get: {perks}.",
    summaryOrders: "Customers with {orders} delivered{window} get: {perks}.",
    summaryWindow: " in the last {days}",
    perkPercent: "{n}% off",
    perkShipping: "free shipping",
    perkPoints: "{n}× loyalty points",
    perkNone: "the badge only. Add a perk",
    perkJoin: ", ",
    loyaltyOff: "The loyalty programme isn't running, so the points multiplier does nothing until you turn it on.",
    loyaltyOffAction: "Open loyalty points",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. VIP tiers are running.",
    savedOff: "Saved. VIP tiers are off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "A customer who buys more moves up a tier, and each tier gives them a discount, free shipping or more points.",
    tierSummarySpent: "From {amount} · {perks}",
    tierSummaryOrders: "From {orders} · {perks}",
    tierNoThreshold: "Where it starts isn't set yet",
    tierNeedsFix: "Needs a fix",
    tierRemoved: "{name} removed. Save to keep the change.",
    tiersFull: "You have the most tiers a store can have ({max}).",
    membersLink: "A customer's tier",
    membersLinkHint: "On the customer's page: the tier they are in and how far the next one is.",
    // customer card
    cardTitle: "VIP tier",
    cardHint: "From this customer's delivered orders.",
    noTier: "No tier yet",
    topTier: "At the highest tier.",
    perks: "Gets: {perks}",
    noPerks: "This tier gives nothing yet.",
    standingSpent: "{orders} delivered, worth {amount}",
    nextSpent: "{amount} more to {name}",
    nextOrders_one: "1 more order to {name}",
    nextOrders_other: "{n} more orders to {name}",
    progress: "Progress to {name}",
    manage: "Edit tiers",
  },
  ar: {
    // page
    title: "مستويات VIP",
    description: "يرتقي العملاء في المستويات بحسب ما دفعوه أو عدد طلباتهم التي تم تسليمها، ولكل مستوى ميزة.",
    stateOn: "مفعّلة",
    stateOff: "متوقفة",
    accountsOff: "حسابات العملاء متوقفة، لذلك لن يحصل أحد على مزايا مستواه: يجب أن يعرف المتجر من يشتري، وهذا يتطلب تسجيل دخول العميل.",
    accountsOffAction: "تفعيل حسابات العملاء",
    settingsTitle: "كيف يرتقي العملاء في المستويات",
    enable: "تفعيل مستويات VIP",
    enableHintOn: "العميل الذي سجّل الدخول يحصل على مزايا مستواه في صفحة الدفع.",
    enableHintOff: "متوقفة: لا أحد يحصل على مزايا. المستويات أدناه محفوظة كما هي.",
    basis: "يصل العميل إلى المستوى",
    basisSpent: "بحسب المبلغ",
    basisSpentHint: "ما دفعه العميل في الطلبات التي تم تسليمها، بعد خصم ما استُرد له.",
    basisOrders: "بحسب عدد الطلبات",
    basisOrdersHint: "عدد طلبات العميل التي تم تسليمها.",
    window: "احتساب آخر",
    windowUnit: "يومًا",
    windowHint: "تُحتسب الطلبات التي في هذه المدة فقط، فالعميل الذي يتوقف عن الشراء ينزل مستوى. اتركه فارغًا لاحتساب كل طلباته منذ البداية.",
    windowError: "أدخل عدد أيام من ٣٠ إلى ١٨٢٥، أو اتركه فارغًا.",
    tiersTitle: "المستويات",
    tiersHint: "حتى {max} مستويات. يكون العميل في أعلى مستوى وصل إليه.",
    tierN: "المستوى {n}",
    nameAr: "الاسم بالعربية",
    nameEn: "الاسم بالإنجليزية",
    nameError: "أدخل اسم المستوى بالعربية أو بالإنجليزية.",
    thresholdSpent: "يبدأ من",
    thresholdOrders: "يبدأ من (عدد الطلبات)",
    thresholdSpentError: "أدخل المبلغ الذي يبدأ منه هذا المستوى.",
    thresholdOrdersError: "أدخل عدد طلبات صحيحًا، من ١.",
    thresholdDuplicate: "لا يمكن أن يبدأ مستويان من الرقم نفسه.",
    percentOff: "نسبة الخصم",
    percentHint: "من ٠ إلى ٥٠. من سعر المنتجات العادي.",
    percentError: "أدخل رقمًا صحيحًا من ٠ إلى ٥٠.",
    percentUnit: "٪",
    freeShipping: "شحن مجاني",
    multiplier: "نقاط الولاء",
    multiplierHint: "النقاط التي يكسبها من الطلب، مضاعفة.",
    multiplierNone: "×١ (دون تغيير)",
    multiplierOption: "×{n}",
    removeTier: "حذف المستوى {n}",
    addTier: "إضافة مستوى",
    noTiers: "لا توجد مستويات بعد. أضف أول مستوى، مثلًا «فضي» من عدد معيّن من الطلبات.",
    tiersRequired: "أضف مستوى واحدًا على الأقل قبل تفعيل مستويات VIP.",
    summarySpent: "العملاء الذين دفعوا {amount} في طلبات تم تسليمها{window} يحصلون على: {perks}.",
    summaryOrders: "العملاء الذين استلموا {orders}{window} يحصلون على: {perks}.",
    summaryWindow: " في آخر {days}",
    perkPercent: "خصم {n}٪",
    perkShipping: "شحن مجاني",
    perkPoints: "نقاط ولاء ×{n}",
    perkNone: "الشارة فقط. أضف ميزة",
    perkJoin: "، ",
    loyaltyOff: "برنامج الولاء غير مفعّل، لذلك لن يكون لمضاعفة النقاط أثر حتى تفعّله.",
    loyaltyOffAction: "فتح نقاط الولاء",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ.",
    savedOn: "تم الحفظ. مستويات VIP مفعّلة.",
    savedOff: "تم الحفظ. مستويات VIP متوقفة.",
    fixFields: "راجع الحقول المشار إليها.",
    customerGets: "العميل الذي يشتري أكثر يرتقي مستوى، ولكل مستوى خصم أو شحن مجاني أو نقاط أكثر.",
    tierSummarySpent: "من {amount} · {perks}",
    tierSummaryOrders: "من {orders} · {perks}",
    tierNoThreshold: "لم تحدد بعد من أين يبدأ",
    tierNeedsFix: "يحتاج إلى تعديل",
    tierRemoved: "تم حذف {name}. احفظ لتثبيت التغيير.",
    tiersFull: "وصلت إلى الحد الأقصى لعدد المستويات ({max}).",
    membersLink: "مستوى عميل معيّن",
    membersLinkHint: "في صفحة العميل: مستواه الحالي وما يتبقى له للوصول إلى المستوى التالي.",
    // customer card
    cardTitle: "مستوى VIP",
    cardHint: "من طلبات هذا العميل التي تم تسليمها.",
    noTier: "لم يصل إلى أي مستوى بعد",
    topTier: "في أعلى مستوى.",
    perks: "يحصل على: {perks}",
    noPerks: "هذا المستوى ليست له مزايا بعد.",
    standingSpent: "استلم {orders} بقيمة {amount}",
    nextSpent: "يتبقى {amount} للوصول إلى {name}",
    nextOrders_one: "يتبقى طلب واحد للوصول إلى {name}",
    nextOrders_two: "يتبقى طلبان للوصول إلى {name}",
    nextOrders_few: "يتبقى {n} طلبات للوصول إلى {name}",
    nextOrders_other: "يتبقى {n} طلبًا للوصول إلى {name}",
    progress: "التقدّم نحو {name}",
    manage: "تعديل المستويات",
  },
} satisfies Messages;

export type VipStrings = (typeof VIP_STRINGS)["en"];
