import type { Locale, Messages } from "@/i18n/LocaleContext";
import type { BlockedEntry, FlaggedOrder, FraudRuleKey } from "@/mock/types";

export const STRINGS = {
  en: {
    title: "Fraud protection",
    description: "Fake order blocker — stop COD orders that will never be delivered before they cost you shipping.",
    kpiBlockedToday: "Blocked today",
    kpiBlockedTodayHint: "Orders rejected by rules",
    kpiBlockedMonth: "Blocked this month",
    kpiBlockedMonthHint: "Month to date",
    kpiAwaiting: "Awaiting review",
    kpiAwaitingHint: "Flagged orders needing a decision",
    kpiSaved: "Est. shipping saved",
    kpiSavedHint: "~45 EGP per avoided failed delivery",
    phoneTitle: "Egyptian phone validation",
    phoneHelpA: "A valid Egyptian mobile number is 11 digits and starts with",
    phoneHelpB:
      "(Vodafone, Etisalat, Orange, WE). Anything else — wrong length, landlines, repeated digits like 01000000000 — is rejected at checkout when the “Invalid phone” rule is on.",
    tabRules: "Rules",
    tabFlagged: "Flagged orders",
    tabBlocklist: "Blocklist",
    // Rules tab
    savedToast: "Fraud settings saved.",
    valueAria: "{label} value",
    whenMatches: "When a rule matches",
    whenMatchesHint: "Blacklisted phones are always blocked regardless of this setting.",
    flagForReview: "Flag for review",
    flagForReviewHint: "Order is accepted but held in the Flagged queue until an agent approves it.",
    blockNow: "Block immediately",
    blockNowHint: "Checkout shows an error and the order is never created.",
    saveRules: "Save rules",
    // Flagged tab
    approvedToast: "{order} approved — sent to confirmation.",
    blockedToast: "{order} blocked.",
    filterAwaiting: "Awaiting review",
    filterApproved: "Approved",
    filterBlocked: "Blocked",
    emptyFlagged: "Nothing to review — all clear.",
    colOrder: "Order",
    colCustomer: "Customer",
    colPhone: "Phone",
    colTotal: "Total",
    colTriggered: "Triggered rules",
    colFlagged: "Flagged",
    invalidPhone: "Not a valid Egyptian mobile number",
    approve: "Approve",
    block: "Block",
    resolved: "Resolved",
    // Blocklist tab
    removedToast: "Removed from blocklist.",
    entriesSummary: "{n} entries · matched orders are blocked before checkout completes.",
    addToBlocklist: "Add to blocklist",
    emptyBlocklist: "Blocklist is empty.",
    colType: "Type",
    colValue: "Value",
    colReason: "Reason",
    colSource: "Source",
    colHits: "Hits",
    colAdded: "Added",
    remove: "Remove",
    unblockTitle: "Unblock {value}?",
    removeEntryTitle: "Remove entry?",
    unblockDescription: "Orders from this value will be accepted again.",
    sourceRule: "Rule",
    sourceManual: "Manual",
    // Block form
    errEmpty: "Enter a value to block.",
    errPhone: "Enter an 11-digit Egyptian number starting with 010, 011, 012 or 015.",
    errEmail: "Enter a valid email address.",
    errIp: "Enter an IPv4 address or CIDR range, e.g. 197.54.12.0/24.",
    addedToast: "Added to blocklist.",
    typePhone: "Phone number",
    typeIp: "IP address / range",
    typeEmail: "Email",
    reasonHint: "Shown to your team next to blocked orders.",
    reasonPlaceholder: "Fake orders from the ad landing page",
    adding: "Adding…",
  },
  ar: {
    title: "الحماية من الاحتيال",
    description: "مانع الطلبات الوهمية — أوقف طلبات الدفع عند الاستلام التي لن تُسلَّم أبدًا قبل أن تكلفك رسوم الشحن.",
    kpiBlockedToday: "محظورة اليوم",
    kpiBlockedTodayHint: "طلبات رفضتها القواعد",
    kpiBlockedMonth: "محظورة هذا الشهر",
    kpiBlockedMonthHint: "منذ بداية الشهر",
    kpiAwaiting: "بانتظار المراجعة",
    kpiAwaitingHint: "طلبات مُعلَّمة تحتاج إلى قرار",
    kpiSaved: "توفير الشحن التقديري",
    kpiSavedHint: "حوالي 45 جنيهًا لكل شحنة فاشلة تم تجنبها",
    phoneTitle: "التحقق من أرقام الهواتف المصرية",
    phoneHelpA: "رقم الموبايل المصري الصحيح يتكون من 11 رقمًا ويبدأ بـ",
    phoneHelpB:
      "(فودافون، اتصالات، أورنج، WE). أي رقم آخر — طول خاطئ، أو خط أرضي، أو أرقام مكررة مثل 01000000000 — يُرفض عند إتمام الطلب عند تفعيل قاعدة «رقم غير صالح».",
    tabRules: "القواعد",
    tabFlagged: "الطلبات المُعلَّمة",
    tabBlocklist: "قائمة الحظر",
    savedToast: "تم حفظ إعدادات الحماية من الاحتيال.",
    valueAria: "قيمة {label}",
    whenMatches: "عند تطابق قاعدة",
    whenMatchesHint: "الأرقام الموجودة في قائمة الحظر تُحظر دائمًا بغض النظر عن هذا الإعداد.",
    flagForReview: "تعليم للمراجعة",
    flagForReviewHint: "يُقبل الطلب لكنه يبقى في قائمة الطلبات المُعلَّمة حتى يوافق عليه أحد الموظفين.",
    blockNow: "حظر فوري",
    blockNowHint: "تظهر رسالة خطأ عند إتمام الطلب ولا يُنشأ الطلب أبدًا.",
    saveRules: "حفظ القواعد",
    approvedToast: "تمت الموافقة على {order} — أُرسل إلى التأكيد.",
    blockedToast: "تم حظر {order}.",
    filterAwaiting: "بانتظار المراجعة",
    filterApproved: "تمت الموافقة",
    filterBlocked: "محظور",
    emptyFlagged: "لا يوجد ما يحتاج إلى مراجعة — كل شيء على ما يرام.",
    colOrder: "الطلب",
    colCustomer: "العميل",
    colPhone: "الهاتف",
    colTotal: "الإجمالي",
    colTriggered: "القواعد المُفعَّلة",
    colFlagged: "تاريخ التعليم",
    invalidPhone: "ليس رقم موبايل مصريًا صالحًا",
    approve: "موافقة",
    block: "حظر",
    resolved: "تمت المعالجة",
    removedToast: "تمت الإزالة من قائمة الحظر.",
    entriesSummary: "{n} إدخال · الطلبات المطابقة تُحظر قبل إتمامها.",
    addToBlocklist: "إضافة إلى قائمة الحظر",
    emptyBlocklist: "قائمة الحظر فارغة.",
    colType: "النوع",
    colValue: "القيمة",
    colReason: "السبب",
    colSource: "المصدر",
    colHits: "مرات التطابق",
    colAdded: "تاريخ الإضافة",
    remove: "إزالة",
    unblockTitle: "إلغاء حظر {value}؟",
    removeEntryTitle: "إزالة الإدخال؟",
    unblockDescription: "سيتم قبول الطلبات من هذه القيمة مرة أخرى.",
    sourceRule: "قاعدة",
    sourceManual: "يدوي",
    errEmpty: "أدخل قيمة لحظرها.",
    errPhone: "أدخل رقمًا مصريًا من 11 رقمًا يبدأ بـ 010 أو 011 أو 012 أو 015.",
    errEmail: "أدخل بريدًا إلكترونيًا صالحًا.",
    errIp: "أدخل عنوان IPv4 أو نطاق CIDR، مثل 197.54.12.0/24.",
    addedToast: "تمت الإضافة إلى قائمة الحظر.",
    typePhone: "رقم الهاتف",
    typeIp: "عنوان IP / نطاق",
    typeEmail: "البريد الإلكتروني",
    reasonHint: "يظهر لفريقك بجوار الطلبات المحظورة.",
    reasonPlaceholder: "طلبات وهمية من صفحة الإعلان",
    adding: "جارٍ الإضافة…",
  },
} satisfies Messages;

export interface RuleCopy {
  label: string;
  short: string;
  description: string;
  unit: string | null;
}

export const RULE_COPY: Record<Locale, Record<FraudRuleKey, RuleCopy>> = {
  en: {
    block_blacklisted_phone: { label: "Block blacklisted phones", short: "Blacklisted phone", description: "Any order from a phone on the blocklist is blocked immediately.", unit: null },
    duplicate_order_window: { label: "Prevent duplicate orders", short: "Duplicate order", description: "Same phone + same product within a short window counts as a duplicate.", unit: "minutes" },
    max_orders_per_phone_per_day: { label: "Max orders per phone per day", short: "Too many orders", description: "More than this many orders in one day is flagged as suspicious.", unit: "orders" },
    block_invalid_phone_format: { label: "Reject invalid phone numbers", short: "Invalid phone", description: "An Egyptian number must start with 010/011/012/015 and be 11 digits.", unit: null },
    high_rejection_customer: { label: "High-rejection customer", short: "High rejection rate", description: "Customers whose rejection/return rate is above this threshold are flagged.", unit: "% rejected" },
    require_otp_high_value: { label: "OTP for high-value orders", short: "OTP required", description: "Orders above this amount require a verification code sent to the phone.", unit: "EGP" },
    block_ip_country_mismatch: { label: "IP outside the shipping country", short: "IP mismatch", description: "When the IP is from a different country than the shipping address.", unit: null },
  },
  ar: {
    block_blacklisted_phone: { label: "حظر الأرقام في قائمة الحظر", short: "رقم محظور", description: "أي طلب من رقم موجود في قائمة الحظر يُحظر فورًا.", unit: null },
    duplicate_order_window: { label: "منع الطلبات المكررة", short: "طلب مكرر", description: "نفس الرقم مع نفس المنتج خلال فترة قصيرة يُعتبر طلبًا مكررًا.", unit: "دقيقة" },
    max_orders_per_phone_per_day: { label: "الحد الأقصى للطلبات من نفس الرقم يوميًا", short: "طلبات كثيرة", description: "تجاوز هذا العدد في يوم واحد يُعلَّم كطلب مشبوه.", unit: "طلبات" },
    block_invalid_phone_format: { label: "رفض الأرقام غير الصالحة", short: "رقم غير صالح", description: "الرقم المصري يجب أن يبدأ بـ 010/011/012/015 ويتكون من 11 رقمًا.", unit: null },
    high_rejection_customer: { label: "عميل بنسبة رفض مرتفعة", short: "نسبة رفض مرتفعة", description: "يُعلَّم العميل إذا تجاوزت نسبة الرفض/المرتجع لديه هذا الحد.", unit: "% رفض" },
    require_otp_high_value: { label: "رمز تحقق OTP للطلبات الكبيرة", short: "يتطلب OTP", description: "الطلبات التي تتجاوز هذا المبلغ تتطلب رمز تحقق يُرسل إلى الهاتف.", unit: "جنيه" },
    block_ip_country_mismatch: { label: "IP من خارج دولة الشحن", short: "عدم تطابق IP", description: "عندما يكون عنوان IP من دولة مختلفة عن عنوان الشحن.", unit: null },
  },
};

export const FLAG_STATUS_LABEL: Record<Locale, Record<FlaggedOrder["status"], string>> = {
  en: { flagged: "Flagged", approved: "Approved", blocked: "Blocked" },
  ar: { flagged: "مُعلَّم", approved: "تمت الموافقة", blocked: "محظور" },
};

export const ENTRY_TYPE_LABEL: Record<Locale, Record<BlockedEntry["type"], string>> = {
  en: { phone: "Phone", ip: "IP", email: "Email" },
  ar: { phone: "هاتف", ip: "IP", email: "بريد" },
};
