import { useT, type Messages } from "@/i18n/LocaleContext";

/*
 * Every word of «رحلة الأوردر» in the reports hub (../JourneyTab.tsx and the
 * files beside this one). Egyptian Arabic, second person, short. Plural forms
 * follow lib/plural.ts (`<key>_one / _two / _few / _other`); `{ten}` is the
 * number 10, written through `fmt` so it takes the language's digits.
 *
 * Rates are worded «٥ من كل ١٠» in sentences and written as percentages in
 * the cards and the tables.
 */
export const JOURNEY_STRINGS = {
  en: {
    note: "This period's orders, and how far they have got by now — with no comparison to the period before.",

    // ------------------------------------------------------------- KPIs --
    confirmationRate: "Confirmation rate",
    confirmationHint: "{confirmed} of {orders} cash on delivery confirmed",
    confirmationNone: "No cash-on-delivery orders in this period",
    deliveryRate: "Delivery rate",
    deliveryHint: "{delivered} of {orders} shipped were delivered",
    returnRate: "Return rate",
    returnHint: "{returned} of {orders} shipped came back or failed",
    shippedNone: "Nothing has shipped yet",
    confirmTime: "Average time to confirm",
    confirmTimeHint: "From the order to the confirmation call",
    confirmTimeNone: "No order has been confirmed yet",
    deliveryTimeHint: "Delivery then takes {days} on average",
    deliveryTime: "Average time to deliver",

    // ------------------------------------------------------------ chart --
    chartTitle: "The journey of this period's orders",
    chartNote: "Of {orders} placed in the period: how many reached each step.",
    chartCod: "\"Confirmed\" counts cash-on-delivery orders only ({orders}).",
    chartEmpty: "No orders in this period yet.",
    stepsLabel: "An order's four steps, from placed to delivered",
    ordered: "Ordered",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    rateConfirmed: "confirmed",
    rateDelivered: "delivered",
    rateConfirmedHint: "Confirmation rate: confirmed, out of the cash-on-delivery orders",
    rateDeliveredHint: "Delivery rate: delivered, out of the shipped orders",
    rateNone: "No rate yet: there is nothing to work it out from",
    barTitle: "{label}: {orders}",
    legendReturned: "Came back or failed",
    legendOnTheWay: "Still on the way",

    // ------------------------------------------------------------ table --
    tableSwitch: "Break the table down by",
    byPlace: "By governorate",
    byCourier: "By courier",
    placeCaption: "Orders by governorate",
    courierCaption: "Orders by courier",
    placeNote: "The period's orders by shipping address. Delivered so far: {delivered} of {total} ordered.",
    courierNote: "The orders each courier carried. Delivered so far: {delivered} of {total} ordered.",
    colPlace: "Governorate",
    colCourier: "Courier",
    colOrders: "Orders",
    colConfirmed: "Confirmed",
    colShipped: "Shipped",
    colDelivered: "Delivered",
    colReturned: "Returned",
    colConfirmation: "Confirmation rate",
    colDelivery: "Delivery rate",
    colReturn: "Return rate",
    colDays: "Avg. delivery days",
    colSales: "Delivered sales",
    hintOrders: "Orders placed in the period",
    hintConfirmed: "Cash-on-delivery orders that were confirmed",
    hintShipped: "Orders handed to a courier",
    hintDelivered: "Orders that reached the customer",
    hintReturned: "Came back, or the delivery failed",
    hintConfirmation: "Confirmed, out of the cash-on-delivery orders",
    hintDelivery: "Delivered, out of the shipped orders",
    hintReturn: "Came back or failed, out of the shipped orders",
    hintDays: "From the day it shipped to the day it was delivered",
    hintSales: "The total of the orders that reached the customer",
    placeEmpty: "No order of this period has a governorate in its address.",
    courierEmpty: "No order of this period has left with a courier yet.",
    thinSample: "Fewer than {min} — this rate is not steady yet",
    manualCourier: "Manual shipping",

    // --------------------------------------------------------- sentence --
    ofTen_one: "1 in {ten}",
    ofTen_two: "2 in {ten}",
    ofTen_other: "{n} in {ten}",
    sayEmpty: "No orders in this period. Pick a longer period to see the journey.",
    sayTooFew: "Only {orders} in this period — too early to judge. From {min} up, this line names where orders are lost.",
    sayConfirmLow: "Confirmation loses the most: {lost} cash-on-delivery orders never get confirmed (of {orders}) — call sooner, or ask for a deposit.",
    sayConfirmMild: "Confirmation is the weakest step: {lost} cash-on-delivery orders never get confirmed — call customers sooner.",
    sayConfirmNone: "Almost no cash-on-delivery order gets confirmed (of {orders}) — call sooner, or ask for a deposit.",
    sayPlace: "Delivery in {name} works {share} ({shipped} shipped), against {average} overall — try another courier there, or ask for a deposit.",
    sayPlaceNone: "Delivery in {name} almost never works ({shipped} shipped), against {average} overall — try another courier there, or ask for a deposit.",
    sayCourier: "{worst} delivers {worstShare} and {best} delivers {bestShare} — move more orders to {best}.",
    sayCourierNone: "{worst} delivers almost nothing and {best} delivers {bestShare} — move more orders to {best}.",
    sayDelivery: "Delivery is the weakest step: {lost} shipped orders are not received — check the courier, and confirm the address before shipping.",
    sayDeliveryNone: "Almost no shipped order is received — check the courier, and confirm the address before shipping.",
    sayGoodBoth: "The journey is running well: {confirmed} get confirmed and {delivered} get delivered.",
    sayGoodConfirm: "Confirmation is running well: {confirmed} get confirmed.",
    sayGoodDelivery: "Delivery is running well: {delivered} of the shipped get delivered.",
    sayTailOnTheWay: "Too early to judge delivery: most of what shipped is still on the way.",
    sayTailNotShipped: "Not enough has shipped yet to judge delivery by.",
    sayNoRates: "There is not enough to work a rate out from in this period yet.",
    actConfirm: "Open confirmations",
    actShipping: "Shipping settings",
    actReturns: "Open returns",

    // ----------------------------------------------------- more: stages --
    nowTitle: "Where the orders are now",
    nowSummary: "Every order of the period, by its stage today",
    stage_pending_confirmation: "Waiting for confirmation",
    stage_needs_follow_up: "Needs follow-up",
    stage_awaiting_payment: "Awaiting payment",
    stage_ready_to_ship: "Ready to ship",
    stage_shipped: "With the courier",
    stage_out_for_delivery: "Out for delivery",
    stage_delivered: "Delivered",
    stage_delivery_failed: "Delivery failed",
    stage_returned: "Returned",
    stage_cancelled: "Cancelled",
    nowEmpty: "No orders in this period yet.",

    // ------------------------------------------------ more: unconfirmed --
    openTitle: "What happened to the unconfirmed",
    openSummary: "No answer · refused · postponed · not called yet",
    openPending: "Not called yet",
    openUnreachable: "Didn't answer",
    openPostponed: "Asked for a later call",
    openRejected: "Refused",
    openEmpty: "Nothing is waiting, unanswered, postponed or refused in this period.",
    openSource: "Counted from the orders summary, which includes test orders — so it can differ a little from the figures above.",
    openAction: "Open confirmations",

    // --------------------------------------------------- more: products --
    productsTitle: "By product",
    productsSummary: "Delivery and return rate of each product",
    productsCaption: "Delivery and returns by product",
    productsNote: "Both rates are in pieces: delivered and returned, out of the pieces that shipped.",
    colProduct: "Product",
    colUnits: "Pieces",
    productsEmpty: "No product was ordered in this period.",

    // ---------------------------------------------------- more: sources --
    sourcesTitle: "By source",
    sourcesSummary: "Orders confirmed and delivered from each source",
    sourcesCaption: "Orders by source",
    sourcesNote: "An order counts for the last source its customer came from. \"Confirmed\" counts cash on delivery only.",
    colSource: "Source",
    sourceNone: "No source (direct, phone, manual)",
    sourcesEmpty: "No orders in this period yet.",

    // ---------------------------------------------------- more: returns --
    returnsTitle: "Why orders come back",
    returnsSummary: "Return reasons, and the money refunded",
    returnsRequests: "Returns opened",
    returnsPieces: "Pieces asked back",
    returnsRefunded: "Refunded",
    returnsRefundCount: "Refunds processed",
    returns_one: "1 return",
    returns_other: "{n} returns",
    reason_damaged: "Damaged",
    reason_defective: "Defective",
    reason_wrong_item: "Wrong item",
    reason_not_as_described: "Not as described",
    reason_no_longer_wanted: "No longer wanted",
    reason_arrived_late: "Arrived late",
    reason_other: "Other reason",
    reasonCaption: "{units} · {completed} received or refunded · {rejected} rejected",
    returnsEmpty: "No returns were opened in this period.",
    returnsByReason: "By reason",
    returnsTopProducts: "Products that come back most",
    returnsUnnamed: "Unnamed product",
    returnsOpen: "Open the returns report",

    // ------------------------------------------------ more: lost orders --
    lostTitle: "Orders that were never finished",
    lostSummary: "Started at checkout and left — and the ones you won back",
    lostAbandoned: "Started and left",
    lostValue: "Value left behind",
    lostRecovered: "Won back",
    lostRecoveryRate: "Recovery rate",
    lostUncontacted: "Not contacted yet",
    lostOpen: "Open unfinished orders",

    // ------------------------------------------------------ more: times --
    timesTitle: "When orders come in",
    timesSummary: "By weekday and hour — for the confirmation calls",
    timesHint: "By weekday and hour, in the store's time. Darker is busier.",
    timesPeak: "Busiest: {day} around {hour} ({orders}).",
    timesEmpty: "No orders in this period yet.",
    timesOpen: "Open the order-times report",
    days: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",

    // --------------------------------------------------- more: insights --
    notesTitle: "What else the numbers say",
    notesSummary: "Notes worked out from this period's figures",
    notesEmpty: "Nothing else stands out in this period.",
    note_low_confirmation: "Only {share} of {orders} cash on delivery were confirmed. Call sooner, or ask for a deposit.",
    note_weak_governorate: "{name}: delivery works {share}, against {average} overall ({orders} shipped). Consider a deposit there.",
    note_strong_governorate: "{name} is your most reliable governorate: delivery works {share}, against {average} overall.",
    note_carrier_gap: "{best} delivers {bestShare}, {worst} only {worstShare}. Move more orders to {best}.",
    note_abandoned_uncontacted: "{orders} never finished, worth {value}, and nobody has contacted them yet.",
    note_peak_time: "Orders peak on {day} around {hour} — plan campaigns and confirmation calls for then.",

    // ------------------------------------------------------- part states --
    partLoading: "Loading…",
    partError: "We couldn't load this part.",
    retry: "Try again",

    // ------------------------------------------------------------ links --
    linkReturnsReport: "Returns report",
    linkReturnsReportHint: "Why orders come back, and the products that come back most",
    linkTimes: "Order times",
    linkTimesHint: "Days and hours orders arrive, with the confirmation rate of each slot",
    linkConfirm: "Order confirmation",
    linkConfirmHint: "Call the orders that are waiting",
    linkReturns: "Returns",
    linkReturnsHint: "Receive what came back and refund it",
    linkLost: "Unfinished orders",
    linkLostHint: "Reach the customers who left at checkout",
    linkShipping: "Shipping",
    linkShippingHint: "Couriers, shipping prices and areas",
  },
  ar: {
    note: "أوردرات الفترة دي ووصلت لحد فين دلوقتي — من غير مقارنة بالفترة اللي قبلها.",

    // ------------------------------------------------------------- KPIs --
    confirmationRate: "نسبة التأكيد",
    confirmationHint: "اتأكد {confirmed} من {orders} دفع عند الاستلام",
    confirmationNone: "مفيش أوردرات دفع عند الاستلام في الفترة دي",
    deliveryRate: "نسبة التسليم",
    deliveryHint: "اتسلّم {delivered} من {orders} اتشحن",
    returnRate: "نسبة المرتجع",
    returnHint: "رجع أو فشل {returned} من {orders} اتشحن",
    shippedNone: "لسه مفيش حاجة اتشحنت",
    confirmTime: "متوسط وقت التأكيد",
    confirmTimeHint: "من وقت الأوردر لحد مكالمة التأكيد",
    confirmTimeNone: "لسه مفيش أوردر اتأكد",
    deliveryTimeHint: "والتوصيل بعدها بياخد {days} في المتوسط",
    deliveryTime: "متوسط وقت التوصيل",

    // ------------------------------------------------------------ chart --
    chartTitle: "رحلة أوردرات الفترة",
    chartNote: "من {orders} اتطلبوا في الفترة: كام منهم وصل لكل خطوة.",
    chartCod: "«اتأكد» بيعدّ أوردرات الدفع عند الاستلام بس ({orders}).",
    chartEmpty: "مفيش أوردرات في الفترة دي لسه.",
    stepsLabel: "خطوات الأوردر الأربعة، من أول ما اتطلب لحد ما اتسلّم",
    ordered: "اتطلب",
    confirmed: "اتأكد",
    shipped: "اتشحن",
    delivered: "اتسلّم",
    rateConfirmed: "اتأكدوا",
    rateDelivered: "استلموا",
    rateConfirmedHint: "نسبة التأكيد: اللي اتأكد من أوردرات الدفع عند الاستلام",
    rateDeliveredHint: "نسبة التسليم: اللي اتسلّم من اللي اتشحن",
    rateNone: "لسه مفيش نسبة: مفيش أوردرات تتحسب منها",
    barTitle: "{label}: {orders}",
    legendReturned: "رجع أو فشل تسليمه",
    legendOnTheWay: "لسه في الطريق",

    // ------------------------------------------------------------ table --
    tableSwitch: "قسّم الجدول بـ",
    byPlace: "بالمحافظة",
    byCourier: "بشركة الشحن",
    placeCaption: "الأوردرات بالمحافظة",
    courierCaption: "الأوردرات بشركة الشحن",
    placeNote: "أوردرات الفترة حسب عنوان الشحن. اتسلّم منها لحد دلوقتي بـ {delivered} من {total} اتطلبت.",
    courierNote: "الأوردرات اللي خرجت مع كل شركة شحن. اتسلّم لحد دلوقتي بـ {delivered} من {total} اتطلبت.",
    colPlace: "المحافظة",
    colCourier: "شركة الشحن",
    colOrders: "الأوردرات",
    colConfirmed: "اتأكد",
    colShipped: "اتشحن",
    colDelivered: "اتسلّم",
    colReturned: "رجع",
    colConfirmation: "نسبة التأكيد",
    colDelivery: "نسبة التسليم",
    colReturn: "نسبة المرتجع",
    colDays: "متوسط أيام التوصيل",
    colSales: "مبيعات اتسلّمت",
    hintOrders: "الأوردرات اللي اتطلبت في الفترة",
    hintConfirmed: "أوردرات دفع عند الاستلام اتأكدت",
    hintShipped: "أوردرات خرجت مع شركة شحن",
    hintDelivered: "أوردرات وصلت للعميل",
    hintReturned: "رجع، أو فشل تسليمه",
    hintConfirmation: "اللي اتأكد من أوردرات الدفع عند الاستلام",
    hintDelivery: "اللي اتسلّم من اللي اتشحن",
    hintReturn: "اللي رجع أو فشل تسليمه من اللي اتشحن",
    hintDays: "من يوم الشحن ليوم التسليم",
    hintSales: "إجمالي الأوردرات اللي وصلت للعميل",
    placeEmpty: "مفيش أوردر في الفترة دي عنوانه فيه محافظة.",
    courierEmpty: "مفيش أوردر في الفترة دي خرج مع شركة شحن لسه.",
    thinSample: "أقل من {min} — النسبة دي لسه مش ثابتة",
    manualCourier: "شحن يدوي",

    // --------------------------------------------------------- sentence --
    ofTen_one: "واحد من كل {ten}",
    ofTen_two: "اتنين من كل {ten}",
    ofTen_other: "{n} من كل {ten}",
    sayEmpty: "مفيش أوردرات في الفترة دي. اختار فترة أطول عشان تشوف الرحلة.",
    sayTooFew: "{orders} بس في الفترة دي — لسه بدري نحكم. من {min} وطالع هنقولك هنا الأوردرات بتضيع فين.",
    sayConfirmLow: "التأكيد بيضيّع أكتر حاجة: {lost} من أوردرات الدفع عند الاستلام ما بيتأكدوش (من {orders}) — اتصل بالعملاء أسرع أو اطلب مقدم.",
    sayConfirmMild: "التأكيد أضعف خطوة: {lost} من أوردرات الدفع عند الاستلام ما بيتأكدوش — اتصل بالعملاء أسرع.",
    sayConfirmNone: "تقريبًا ولا أوردر دفع عند الاستلام بيتأكد (من {orders}) — اتصل بالعملاء أسرع أو اطلب مقدم.",
    sayPlace: "التوصيل في {name} بينجح {share} ({shipped} اتشحن) والمتوسط عندك {average} — جرّب شركة شحن تانية هناك أو اطلب مقدم.",
    sayPlaceNone: "التوصيل في {name} تقريبًا ما بينجحش ({shipped} اتشحن) والمتوسط عندك {average} — جرّب شركة شحن تانية هناك أو اطلب مقدم.",
    sayCourier: "{worst} بتسلّم {worstShare} و{best} بتسلّم {bestShare} — حوّل أوردرات أكتر لـ {best}.",
    sayCourierNone: "{worst} تقريبًا ما بتسلّمش و{best} بتسلّم {bestShare} — حوّل أوردرات أكتر لـ {best}.",
    sayDelivery: "التوصيل أضعف خطوة: {lost} من اللي بيتشحن ما بيتسلّمش — راجع شركة الشحن وأكّد العنوان قبل الشحن.",
    sayDeliveryNone: "تقريبًا ولا أوردر من اللي بيتشحن بيتسلّم — راجع شركة الشحن وأكّد العنوان قبل الشحن.",
    sayGoodBoth: "الرحلة ماشية كويس: {confirmed} بيتأكدوا و{delivered} بيستلموا.",
    sayGoodConfirm: "التأكيد ماشي كويس: {confirmed} بيتأكدوا.",
    sayGoodDelivery: "التوصيل ماشي كويس: {delivered} من اللي بيتشحن بيستلموا.",
    sayTailOnTheWay: "التوصيل لسه بدري عليه: أغلب اللي اتشحن لسه في الطريق.",
    sayTailNotShipped: "لسه مفيش شحن كفاية نحكم بيه على التوصيل.",
    sayNoRates: "لسه مفيش أوردرات كفاية نحسب منها نسبة في الفترة دي.",
    actConfirm: "افتح التأكيدات",
    actShipping: "إعدادات الشحن",
    actReturns: "افتح المرتجعات",

    // ----------------------------------------------------- more: stages --
    nowTitle: "الأوردرات دلوقتي فين",
    nowSummary: "كل أوردرات الفترة حسب حالتها النهارده",
    stage_pending_confirmation: "مستني تأكيد",
    stage_needs_follow_up: "محتاج متابعة",
    stage_awaiting_payment: "مستني الدفع",
    stage_ready_to_ship: "جاهز للشحن",
    stage_shipped: "مع شركة الشحن",
    stage_out_for_delivery: "خرج للتسليم",
    stage_delivered: "اتسلّم",
    stage_delivery_failed: "فشل التسليم",
    stage_returned: "مرتجع",
    stage_cancelled: "ملغي",
    nowEmpty: "مفيش أوردرات في الفترة دي لسه.",

    // ------------------------------------------------ more: unconfirmed --
    openTitle: "اللي ما اتأكدش حصل فيه إيه",
    openSummary: "ما ردّوش · رفضوا · أجّلوا · لسه ما اتكلموش",
    openPending: "لسه ما اتكلموش",
    openUnreachable: "ما ردّوش",
    openPostponed: "أجّلوا",
    openRejected: "رفضوا",
    openEmpty: "مفيش حاجة مستنية أو ما ردّتش أو اتأجّلت أو اترفضت في الفترة دي.",
    openSource: "العدّ ده من ملخص الأوردرات، وبيحسب أوردرات التجربة كمان — فممكن يفرق شوية عن الأرقام اللي فوق.",
    openAction: "افتح التأكيدات",

    // --------------------------------------------------- more: products --
    productsTitle: "بالمنتج",
    productsSummary: "نسبة التسليم والمرتجع لكل منتج",
    productsCaption: "التسليم والمرتجع بالمنتج",
    productsNote: "النسبتين بالقطع: اللي اتسلّم واللي رجع من القطع اللي اتشحنت.",
    colProduct: "المنتج",
    colUnits: "القطع",
    productsEmpty: "مفيش منتج اتطلب في الفترة دي.",

    // ---------------------------------------------------- more: sources --
    sourcesTitle: "بالمصدر",
    sourcesSummary: "الأوردرات اللي اتأكدت واتسلّمت من كل مصدر",
    sourcesCaption: "الأوردرات بالمصدر",
    sourcesNote: "الأوردر بيتحسب لآخر مصدر جه منه العميل. «اتأكد» بيعدّ الدفع عند الاستلام بس.",
    colSource: "المصدر",
    sourceNone: "من غير مصدر (مباشر، تليفون، يدوي)",
    sourcesEmpty: "مفيش أوردرات في الفترة دي لسه.",

    // ---------------------------------------------------- more: returns --
    returnsTitle: "المرتجعات بترجع ليه",
    returnsSummary: "أسباب المرتجعات والفلوس اللي اترجعت",
    returnsRequests: "مرتجعات اتفتحت",
    returnsPieces: "قطع مطلوب إرجاعها",
    returnsRefunded: "فلوس اترجعت",
    returnsRefundCount: "عمليات إرجاع فلوس",
    returns_one: "مرتجع واحد",
    returns_two: "مرتجعين",
    returns_few: "{n} مرتجعات",
    returns_other: "{n} مرتجع",
    reason_damaged: "تالف",
    reason_defective: "عيب صناعة",
    reason_wrong_item: "منتج غلط",
    reason_not_as_described: "مش زي الوصف",
    reason_no_longer_wanted: "مبقاش عايزه",
    reason_arrived_late: "اتأخر",
    reason_other: "سبب تاني",
    reasonCaption: "{units} · {completed} اتستلم أو اترجّعت فلوسه · {rejected} اترفض",
    returnsEmpty: "مفيش مرتجعات اتفتحت في الفترة دي.",
    returnsByReason: "بالسبب",
    returnsTopProducts: "أكتر منتجات بترجع",
    returnsUnnamed: "منتج من غير اسم",
    returnsOpen: "افتح تقرير المرتجعات",

    // ------------------------------------------------ more: lost orders --
    lostTitle: "أوردرات ما كملتش",
    lostSummary: "اللي بدأوا الأوردر ومشيوا — واللي رجّعتهم",
    lostAbandoned: "بدأوا وما كملوش",
    lostValue: "قيمة اللي اتساب",
    lostRecovered: "رجّعتهم",
    lostRecoveryRate: "نسبة اللي رجعوا",
    lostUncontacted: "لسه ما اتكلمتش معاهم",
    lostOpen: "افتح الأوردرات اللي ما كملتش",

    // ------------------------------------------------------ more: times --
    timesTitle: "الأوردرات بتيجي إمتى",
    timesSummary: "باليوم والساعة — عشان مكالمات التأكيد",
    timesHint: "باليوم والساعة بتوقيت المتجر. الأغمق زحمة أكتر.",
    timesPeak: "أكتر وقت: {day} حوالي الساعة {hour} ({orders}).",
    timesEmpty: "مفيش أوردرات في الفترة دي لسه.",
    timesOpen: "افتح تقرير أوقات الأوردرات",
    days: "الأحد,الإثنين,الثلاثاء,الأربعاء,الخميس,الجمعة,السبت",

    // --------------------------------------------------- more: insights --
    notesTitle: "الأرقام بتقول إيه كمان",
    notesSummary: "ملاحظات محسوبة من أرقام الفترة",
    notesEmpty: "مفيش حاجة تانية ملفتة في الفترة دي.",
    note_low_confirmation: "{share} بس من {orders} دفع عند الاستلام اتأكدوا. اتصل أسرع أو اطلب مقدم.",
    note_weak_governorate: "{name}: التوصيل بينجح {share} والمتوسط عندك {average} ({orders} اتشحن). جرّب الدفع المقدم هناك.",
    note_strong_governorate: "{name} أحسن محافظة عندك: التوصيل بينجح {share} والمتوسط {average}.",
    note_carrier_gap: "{best} بتسلّم {bestShare} و{worst} {worstShare} بس. حوّل أوردرات أكتر لـ {best}.",
    note_abandoned_uncontacted: "{orders} ما كملتش بقيمة {value}، ولسه محدش كلّم أصحابها.",
    note_peak_time: "أكتر وقت بتيجي فيه الأوردرات: {day} حوالي الساعة {hour} — خلّي الحملات ومكالمات التأكيد وقتها.",

    // ------------------------------------------------------- part states --
    partLoading: "بنحمّل…",
    partError: "معرفناش نحمّل الجزء ده.",
    retry: "جرّب تاني",

    // ------------------------------------------------------------ links --
    linkReturnsReport: "تقرير المرتجعات",
    linkReturnsReportHint: "الأوردرات بترجع ليه، وأكتر منتجات بترجع",
    linkTimes: "أوقات الأوردرات",
    linkTimesHint: "الأيام والساعات اللي الأوردرات بتيجي فيها، ونسبة التأكيد في كل وقت",
    linkConfirm: "تأكيد الأوردرات",
    linkConfirmHint: "كلّم الأوردرات اللي مستنية",
    linkReturns: "المرتجعات",
    linkReturnsHint: "استلم اللي رجع ورجّع فلوسه",
    linkLost: "أوردرات ما كملتش",
    linkLostHint: "كلّم العملاء اللي مشيوا من صفحة الدفع",
    linkShipping: "الشحن",
    linkShippingHint: "شركات الشحن والأسعار والمناطق",
  },
} satisfies Messages;

/** The tab's strings in the dashboard's language. */
export type JourneyT = Record<keyof (typeof JOURNEY_STRINGS)["en"], string>;

export function useJourneyT(): JourneyT {
  return useT(JOURNEY_STRINGS);
}
