import type { LessonKind } from "@store-builder/api-client";
import { IconDocument, IconFileDown, IconPlayCircle, type Icon } from "@/components/icons";
import type { Messages } from "@/i18n/LocaleContext";

/** Courses (SPEC §18.3): the list, and one course's lessons, settings and students. */
export const COURSE_STRINGS = {
  en: {
    title: "Courses",
    description: "Lessons your customers unlock by buying a product. They sign in on your store with their phone number.",
    add: "New course",
    searchLabel: "Search the courses",
    searchPlaceholder: "Course title",
    chipsLabel: "Courses by status",
    listLabel: "Courses",
    all: "All",
    emptyTitle: "No courses yet",
    emptyDescription: "Create a course, add its lessons, link it to the product that sells it, and publish.",
    emptyFiltered: "No course matches this search or status",
    clearAll: "Clear the search and status",
    lessons_one: "1 lesson",
    lessons_other: "{n} lessons",
    students_one: "1 student",
    students_other: "{n} students",
    chapters_one: "1 chapter",
    chapters_other: "{n} chapters",
    draft: "Draft",
    published: "Published",
    colCourse: "Course",
    colStatus: "Status",
    colLessons: "Lessons",
    colStudents: "Students",
    colCreated: "Created",
    open: "Open",
    openName: "Open the course {name}",
    menuLabel: "Actions for this course",
    copyLink: "Copy the course page link",
    copiedLink: "The course page link is copied",
    createTitle: "New course",
    createDescription: "Start with the title. Lessons, the product that sells it and publishing come next.",
    name: "Course title",
    nameError: "Type the course title.",
    create: "Create the course",
    creating: "Creating…",
    cancel: "Cancel",
    back: "Courses",
    tools: "Course tools",
    tabs: "Course sections",
    tabLessons: "Lessons",
    tabSettings: "Settings",
    tabStudents: "Students",
    publish: "Publish",
    unpublish: "Back to draft",
    publishedToast: "The course is published.",
    draftToast: "The course is back to draft.",
    courseEmpty: "Add at least one lesson before publishing.",
    viewPage: "Open the course page",
    delete: "Delete course",
    deleteTitle: "Delete “{name}”?",
    deleteDescription: "The course and all its lessons are removed for good. This can't be undone.",
    deleteConfirm: "Delete",
    hasStudents: "Students are enrolled in this course. Put it back to draft instead.",
    deleting: "Deleting…",
    deletedToast: "The course is deleted.",
    addModule: "Add a chapter",
    addLesson: "Add a lesson",
    moduleTitle: "Chapter title",
    moduleTitleError: "Type the chapter title.",
    untitledChapter: "New chapter",
    chapterTools: "Chapter tools",
    lessonTools: "Lesson tools",
    lessonTitle: "Lesson title",
    lessonTitleError: "Type the lesson title.",
    untitledLesson: "Lesson with no title",
    editLesson: "Edit lesson",
    editLessonName: "Edit the lesson {name}",
    newLesson: "New lesson",
    kind: "Type",
    kind_video: "Video",
    kind_text: "Text",
    kind_file: "File",
    videoUrl: "Video link",
    videoHint: "The player link from YouTube, Vimeo or Bunny.",
    body: "Text",
    bodyHintVideo: "Optional: shown under the video.",
    file: "File",
    chooseFile: "Choose a file from the library",
    noFiles: "The file library is empty. Upload the file in Digital products first.",
    duration: "Minutes",
    dripDays: "Release after (days)",
    dripHint: "Zero means it opens as soon as they enroll.",
    dripAfter: "After {days}",
    freePreview: "Free preview",
    freePreviewHint: "Anyone can open it, without buying.",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    removeLesson: "Remove lesson",
    removeChapter: "Remove chapter",
    lessonRemoved: "Lesson removed.",
    chapterRemoved: "Chapter removed.",
    done: "Done",
    saveOutline: "Save lessons",
    outlineUnsaved: "The lessons have changes that aren't saved yet",
    outlineSaved: "Lessons saved.",
    noModulesTitle: "No chapters yet",
    noModules: "A course is chapters, and each chapter holds its lessons. Add the first chapter.",
    noLessons: "No lessons in this chapter yet.",
    settingsTitle: "Course details",
    settingsSaved: "Course saved.",
    courseDescription: "Description",
    cover: "Cover picture link",
    coverHint: "The address of a picture, starting with https://",
    product: "Sold through",
    noProduct: "Not linked to a product",
    productHint: "Whoever pays for this product is enrolled automatically.",
    studentLink: "Course page",
    studentLinkHint: "Where students sign in and watch.",
    copy: "Copy link",
    enrollTitle: "Give access",
    enrollDescription: "They get the course without buying it. They sign in with this phone number.",
    phone: "Phone",
    phoneRequired: "Type the phone number.",
    invalidPhone: "Type the whole phone number, in digits.",
    studentName: "Name (optional)",
    enroll: "Give access",
    enrolling: "Adding…",
    enrolledToast: "Access given.",
    studentsSearchLabel: "Search the students",
    studentsSearchPlaceholder: "Name or phone",
    studentsChips: "Students by access",
    studentsList: "Students",
    stActive: "Has access",
    stRevoked: "Access removed",
    noStudentsTitle: "No students yet",
    noStudents: "A student shows up here when they buy the course's product, or when you give them access yourself.",
    noStudentsFiltered: "No student matches this search or filter",
    colStudent: "Student",
    colSource: "How they got in",
    colEnrolled: "Enrolled",
    colProgress: "Progress",
    colAction: "Access",
    progress: "{done} of {total}",
    progressLabel: "Finished {done} of {total} lessons",
    source_order: "Bought it",
    source_manual: "Added by you",
    revoke: "Remove access",
    restore: "Give back",
    revoked: "Access removed",
    revokedOn: "Removed {date}",
    revokedToast: "Access removed.",
    restoredToast: "Access given back.",
    peekStudent: "Preview the student {who}",
    studentMenu: "Actions for this student",
    openCustomer: "Open the customer",
    openOrder: "Open order",
    qlOrder: "Order",
    menuCall: "Call",
    menuWhatsapp: "WhatsApp",
    menuCopyPhone: "Copy the number",
    copiedPhone: "The student's number is copied",
    none: "—",
  },
  ar: {
    title: "الكورسات",
    description: "دروس عملاؤك بيفتحوها لما يشتروا منتج. بيدخلوا من متجرك برقم الموبايل.",
    add: "كورس جديد",
    searchLabel: "دوّر في الكورسات",
    searchPlaceholder: "اسم الكورس",
    chipsLabel: "الكورسات حسب الحالة",
    listLabel: "الكورسات",
    all: "الكل",
    emptyTitle: "لسه مفيش كورسات",
    emptyDescription: "اعمل كورس، ضيف دروسه، اربطه بالمنتج اللي بيبيعه، وانشره.",
    emptyFiltered: "مفيش كورس بالبحث أو الحالة دي",
    clearAll: "امسح البحث والحالة",
    lessons_one: "درس واحد",
    lessons_two: "درسين",
    lessons_few: "{n} دروس",
    lessons_other: "{n} درس",
    students_one: "طالب واحد",
    students_two: "طالبين",
    students_few: "{n} طلاب",
    students_other: "{n} طالب",
    chapters_one: "فصل واحد",
    chapters_two: "فصلين",
    chapters_few: "{n} فصول",
    chapters_other: "{n} فصل",
    draft: "مسودة",
    published: "منشور",
    colCourse: "الكورس",
    colStatus: "الحالة",
    colLessons: "الدروس",
    colStudents: "الطلاب",
    colCreated: "اتعمل",
    open: "افتح",
    openName: "افتح كورس {name}",
    menuLabel: "إجراءات الكورس",
    copyLink: "انسخ لينك صفحة الكورس",
    copiedLink: "لينك صفحة الكورس اتنسخ",
    createTitle: "كورس جديد",
    createDescription: "ابدأ بالاسم. الدروس والمنتج اللي بيبيعه والنشر بييجوا بعد كده.",
    name: "اسم الكورس",
    nameError: "اكتب اسم الكورس.",
    create: "اعمل الكورس",
    creating: "بنعمله…",
    cancel: "إلغاء",
    back: "الكورسات",
    tools: "أدوات الكورس",
    tabs: "أقسام الكورس",
    tabLessons: "الدروس",
    tabSettings: "الإعدادات",
    tabStudents: "الطلاب",
    publish: "انشر",
    unpublish: "رجّعه مسودة",
    publishedToast: "الكورس اتنشر.",
    draftToast: "الكورس رجع مسودة.",
    courseEmpty: "ضيف درس واحد على الأقل قبل النشر.",
    viewPage: "افتح صفحة الكورس",
    delete: "امسح الكورس",
    deleteTitle: "تمسح «{name}»؟",
    deleteDescription: "الكورس وكل دروسه هيتمسحوا نهائي. مينفعش ترجّعهم.",
    deleteConfirm: "امسح",
    hasStudents: "في طلاب مسجّلين في الكورس ده. رجّعه مسودة بدل ما تمسحه.",
    deleting: "بنمسح…",
    deletedToast: "الكورس اتمسح.",
    addModule: "ضيف فصل",
    addLesson: "ضيف درس",
    moduleTitle: "اسم الفصل",
    moduleTitleError: "اكتب اسم الفصل.",
    untitledChapter: "فصل جديد",
    chapterTools: "أدوات الفصل",
    lessonTools: "أدوات الدرس",
    lessonTitle: "اسم الدرس",
    lessonTitleError: "اكتب اسم الدرس.",
    untitledLesson: "درس من غير اسم",
    editLesson: "عدّل الدرس",
    editLessonName: "عدّل درس {name}",
    newLesson: "درس جديد",
    kind: "النوع",
    kind_video: "فيديو",
    kind_text: "نص",
    kind_file: "ملف",
    videoUrl: "لينك الفيديو",
    videoHint: "لينك المشغّل من يوتيوب أو فيميو أو Bunny.",
    body: "النص",
    bodyHintVideo: "اختياري: بيظهر تحت الفيديو.",
    file: "الملف",
    chooseFile: "اختار ملف من المكتبة",
    noFiles: "مكتبة الملفات فاضية. ارفع الملف من «المنتجات الرقمية» الأول.",
    duration: "الدقايق",
    dripDays: "يتفتح بعد (أيام)",
    dripHint: "صفر يعني يتفتح أول ما الطالب يسجّل.",
    dripAfter: "بعد {days}",
    freePreview: "معاينة مجانية",
    freePreviewHint: "أي حد يقدر يفتحه من غير ما يشتري.",
    moveUp: "طلّعه لفوق",
    moveDown: "نزّله لتحت",
    remove: "شيل",
    removeLesson: "شيل الدرس",
    removeChapter: "شيل الفصل",
    lessonRemoved: "الدرس اتشال.",
    chapterRemoved: "الفصل اتشال.",
    done: "تمام",
    saveOutline: "احفظ الدروس",
    outlineUnsaved: "في تعديلات على الدروس لسه ما اتحفظتش",
    outlineSaved: "الدروس اتحفظت.",
    noModulesTitle: "لسه مفيش فصول",
    noModules: "الكورس فصول، وكل فصل فيه دروسه. ضيف أول فصل.",
    noLessons: "لسه مفيش دروس في الفصل ده.",
    settingsTitle: "بيانات الكورس",
    settingsSaved: "الكورس اتحفظ.",
    courseDescription: "الوصف",
    cover: "لينك صورة الغلاف",
    coverHint: "عنوان صورة، بيبدأ بـ https://",
    product: "بيتباع عن طريق",
    noProduct: "مش مربوط بمنتج",
    productHint: "أي حد يدفع تمن المنتج ده بيتسجّل في الكورس لوحده.",
    studentLink: "صفحة الكورس",
    studentLinkHint: "المكان اللي الطلاب بيدخلوا ويتفرجوا منه.",
    copy: "انسخ اللينك",
    enrollTitle: "ادّي صلاحية",
    enrollDescription: "هياخد الكورس من غير ما يشتريه. بيدخل برقم الموبايل ده.",
    phone: "الموبايل",
    phoneRequired: "اكتب رقم الموبايل.",
    invalidPhone: "اكتب رقم الموبايل كامل، بالأرقام.",
    studentName: "الاسم (اختياري)",
    enroll: "ادّي صلاحية",
    enrolling: "بنضيفه…",
    enrolledToast: "الصلاحية اتضافت.",
    studentsSearchLabel: "دوّر في الطلاب",
    studentsSearchPlaceholder: "الاسم أو الموبايل",
    studentsChips: "الطلاب حسب الصلاحية",
    studentsList: "الطلاب",
    stActive: "معاه صلاحية",
    stRevoked: "الصلاحية مسحوبة",
    noStudentsTitle: "لسه مفيش طلاب",
    noStudents: "الطالب بيظهر هنا لما يشتري منتج الكورس، أو لما تدّيه صلاحية بنفسك.",
    noStudentsFiltered: "مفيش طالب بالبحث أو الفلتر ده",
    colStudent: "الطالب",
    colSource: "دخل إزاي",
    colEnrolled: "اتسجّل",
    colProgress: "التقدّم",
    colAction: "الصلاحية",
    progress: "{done} من {total}",
    progressLabel: "خلّص {done} من {total} درس",
    source_order: "اشترى",
    source_manual: "ضفته إنت",
    revoke: "اسحب الصلاحية",
    restore: "رجّعها",
    revoked: "الصلاحية مسحوبة",
    revokedOn: "اتسحبت {date}",
    revokedToast: "الصلاحية اتسحبت.",
    restoredToast: "الصلاحية رجعت.",
    peekStudent: "معاينة الطالب {who}",
    studentMenu: "إجراءات الطالب",
    openCustomer: "افتح صفحة العميل",
    openOrder: "افتح الأوردر",
    qlOrder: "الأوردر",
    menuCall: "اتصل",
    menuWhatsapp: "واتساب",
    menuCopyPhone: "انسخ الرقم",
    copiedPhone: "رقم الطالب اتنسخ",
    none: "—",
  },
} satisfies Messages;

export type CourseStrings = (typeof COURSE_STRINGS)["en"];

/** The glyph of each kind of lesson. A play button is not a direction: it is never mirrored. */
export const LESSON_ICON: Record<LessonKind, Icon> = {
  video: IconPlayCircle,
  text: IconDocument,
  file: IconFileDown,
};

/** The session cache of the courses list and of one course (lib/useCachedAsync). */
export const coursesCacheKey = (workspaceId: string) => `courses:${workspaceId}:list`;
export const courseCacheKey = (workspaceId: string, courseId: string) => `courses:${workspaceId}:one:${courseId}`;

/** The address of one course's editor: the list's own route with the course in the query (and its section in `tab`). */
export const courseHref = (courseId: string) => `/courses?course=${encodeURIComponent(courseId)}`;
