import type { StockForecastFilter, StockForecastSettings, StockForecastStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Inventory → «توقّع المخزون» / Stock forecast (handoff 224): the list with
 * its filter chips, the settings dialog, the purchase-order dialog and the
 * product page's card. Arabic is the merchant's Egyptian, with the handoff's
 * wording. A setting's sentence carries `{n}` where its number field goes.
 */
export const FORECAST_STRINGS = {
  en: {
    // tab
    hint: "How long your stock lasts at the pace it sells. Tick what you want to order, then create a purchase order.",
    hintViewOnly: "How long your stock lasts at the pace it sells, and what to order before it runs out.",
    settings: "Forecast settings",
    filterLabel: "Show variants",
    filterAll: "All",
    status_out: "Out",
    status_reorder_now: "Reorder now",
    status_soon: "Running low",
    status_ok: "OK",
    status_no_sales: "No sales",
    filter_needs_order: "Needs ordering",
    chipCount: "{label} ({n})",
    basis: "Worked out from sales over the last {window}, a supplier lead time of {lead}, {cover} of cover and a safety margin of {safety}.",
    // table
    colProduct: "Product",
    colAvailable: "Available",
    colIncoming: "Incoming",
    colPerDay: "Sold per day",
    colDaysLeft: "Days left",
    colRunsOut: "Runs out on",
    colReorderBy: "Reorder by",
    colSuggested: "Suggested quantity",
    singleVariant: "One variant",
    selectAll: "Select all the variants shown",
    selectRow: "Select {name}",
    quantityFor: "Quantity to order of {name}",
    quantityEmpty: "Nothing to order for this one — type a quantity",
    quantityError: "Enter a whole number above zero.",
    firstRows: "Showing the first {n} of {total} variants. Choose a status to see the rest.",
    viewOnly: "Your role can see the forecast but not change it.",
    // empty
    emptyTitle: "No stock-tracked products yet",
    emptyHint: "The forecast covers the products whose quantity you track. Turn on quantity tracking on a product to see it here.",
    noMatchTitle: "Nothing with this status",
    showAll: "Show all variants",
    // selection
    selected_one: "1 variant selected",
    selected_other: "{n} variants selected",
    createPo: "Create purchase order",
    clearSelection: "Clear",
    fixQuantities: "Type a quantity for every variant you selected.",
    // purchase order dialog
    poTitle: "Create purchase order",
    poDescription: "A draft purchase order with the quantities you chose. You can edit it before you order.",
    supplier: "Supplier",
    chooseSupplier: "Choose a supplier…",
    supplierError: "Choose a supplier.",
    noSuppliers: "You have no suppliers yet. Add one first.",
    addSupplierLink: "Add a supplier",
    suppliersFailed: "Couldn't load your suppliers.",
    retry: "Try again",
    receiveAt: "Receive at",
    defaultLocation: "{name} (default)",
    linesTitle: "What will be ordered",
    lineQuantity: "× {n}",
    poSubmit: "Create purchase order",
    poCreating: "Creating…",
    poCreated: "Purchase order {number} was created as a draft.",
    lineNothing: "{name}: nothing to order for this one — type a quantity.",
    lineNotTracked: "{name}: this product isn't stock-tracked or isn't in this store any more.",
    cancel: "Cancel",
    // settings dialog
    settingsTitle: "Forecast settings",
    settingsDescription: "These numbers decide when you are told to reorder, and how much.",
    set_windowDays: "Sales over the last {n} days",
    set_leadTimeDays: "Supplier lead time (days)",
    set_coverDays: "Stock to cover (days)",
    set_safetyDays: "Safety margin (days)",
    rangeHint: "From {min} to {max}",
    rangeError: "Enter a whole number from {min} to {max}.",
    save: "Save",
    saving: "Saving…",
    settingsSaved: "Forecast settings saved.",
    // product page card
    cardTitle: "Stock forecast",
    cardDescription: "How long this product's stock lasts at the pace it sells.",
    lineLeft: "{days} left — reorder by {date}",
    lineLeftNow: "{days} left — reorder now",
    lineOut: "Out of stock — reorder now",
    lineOutIdle: "Out of stock",
    lineNoSales: "No sales in the last {days}",
    incomingNote: "{n} on the way",
    suggestedNote: "Suggested order: {n}",
    openForecast: "Open the stock forecast",
  },
  ar: {
    hint: "مخزونك يكفي قد إيه بمعدل بيعه. علّم على اللي عايز تطلبه، وبعدها اعمل أمر شراء.",
    hintViewOnly: "مخزونك يكفي قد إيه بمعدل بيعه، وإيه اللي يتطلب قبل ما يخلص.",
    settings: "إعدادات التوقّع",
    filterLabel: "اعرض الأنواع",
    filterAll: "الكل",
    status_out: "خلص",
    status_reorder_now: "اطلب دلوقتي",
    status_soon: "قرّب يخلص",
    status_ok: "تمام",
    status_no_sales: "مفيش مبيعات",
    filter_needs_order: "محتاج طلب",
    chipCount: "{label} ({n})",
    basis: "محسوب على مبيعات آخر {window}، والمورّد بيوصّل في {lead}، والمخزون يكفي {cover}، وهامش أمان {safety}.",
    colProduct: "المنتج",
    colAvailable: "المتاح",
    colIncoming: "جاي في الطريق",
    colPerDay: "بيتباع في اليوم",
    colDaysLeft: "يكفي كام يوم",
    colRunsOut: "هيخلص يوم",
    colReorderBy: "اطلب قبل",
    colSuggested: "الكمية المقترحة",
    singleVariant: "نوع واحد",
    selectAll: "اختار كل الأنواع المعروضة",
    selectRow: "اختار {name}",
    quantityFor: "الكمية اللي هتطلبها من {name}",
    quantityEmpty: "مفيش حاجة تتطلب للصنف ده — اكتب كمية",
    quantityError: "اكتب رقم صحيح أكبر من صفر.",
    firstRows: "ظاهر أول {n} نوع من {total}. اختار حالة عشان تشوف الباقي.",
    viewOnly: "صلاحياتك تشوف التوقّع بس من غير تعديل.",
    emptyTitle: "لسه مفيش منتجات مخزونها متتبّع",
    emptyHint: "التوقّع بيشتغل على المنتجات اللي بتتابع كميتها. فعّل متابعة الكمية في المنتج عشان يظهر هنا.",
    noMatchTitle: "مفيش أنواع بالحالة دي",
    showAll: "اعرض كل الأنواع",
    selected_one: "نوع واحد مختار",
    selected_two: "نوعين مختارين",
    selected_few: "{n} أنواع مختارة",
    selected_other: "{n} نوع مختار",
    createPo: "اعمل أمر شراء",
    clearSelection: "شيل الاختيار",
    fixQuantities: "اكتب كمية لكل نوع اخترته.",
    poTitle: "اعمل أمر شراء",
    poDescription: "أمر شراء مسودة بالكميات اللي اخترتها. تقدر تعدّله قبل ما تطلبه.",
    supplier: "المورد",
    chooseSupplier: "اختار مورد…",
    supplierError: "اختار مورد.",
    noSuppliers: "لسه معندكش موردين. ضيف مورد الأول.",
    addSupplierLink: "ضيف مورد",
    suppliersFailed: "معرفناش نحمّل الموردين.",
    retry: "جرّب تاني",
    receiveAt: "الاستلام في",
    defaultLocation: "{name} (الأساسي)",
    linesTitle: "اللي هيتطلب",
    lineQuantity: "× {n}",
    poSubmit: "اعمل أمر الشراء",
    poCreating: "بنعمله…",
    poCreated: "أمر الشراء {number} اتعمل كمسودة.",
    lineNothing: "{name}: مفيش حاجة تتطلب للصنف ده — اكتب كمية.",
    lineNotTracked: "{name}: المنتج ده مخزونه مش متتبّع أو مبقاش في المتجر.",
    cancel: "إلغاء",
    settingsTitle: "إعدادات التوقّع",
    settingsDescription: "الأرقام دي بتحدد إمتى نقولك اطلب، وتطلب كام.",
    set_windowDays: "احسب المبيعات من آخر {n} يوم",
    set_leadTimeDays: "المورّد بيوصّل في {n} يوم",
    set_coverDays: "عايز المخزون يكفي {n} يوم",
    set_safetyDays: "هامش أمان {n} يوم",
    rangeHint: "من {min} لـ {max}",
    rangeError: "اكتب رقم صحيح من {min} لـ {max}.",
    save: "حفظ",
    saving: "بنحفظ…",
    settingsSaved: "إعدادات التوقّع اتحفظت.",
    cardTitle: "توقّع المخزون",
    cardDescription: "مخزون المنتج ده يكفي قد إيه بمعدل بيعه.",
    lineLeft: "يكفي {days} — اطلب قبل {date}",
    lineLeftNow: "يكفي {days} — اطلب دلوقتي",
    lineOut: "خلص — اطلب دلوقتي",
    lineOutIdle: "خلص",
    lineNoSales: "مفيش مبيعات في آخر {days}",
    incomingNote: "جاي في الطريق {n}",
    suggestedNote: "المقترح تطلب {n}",
    openForecast: "افتح توقّع المخزون",
  },
} satisfies Messages;

export type ForecastStrings = Record<keyof (typeof FORECAST_STRINGS)["en"], string>;
type Key = keyof (typeof FORECAST_STRINGS)["en"];

export const FORECAST_STATUS_KEY: Record<StockForecastStatus, Key> = {
  out: "status_out",
  reorder_now: "status_reorder_now",
  soon: "status_soon",
  ok: "status_ok",
  no_sales: "status_no_sales",
};

/** A filter chip's label: a status, or "needs ordering". */
export const FORECAST_FILTER_KEY: Record<StockForecastFilter, Key> = { ...FORECAST_STATUS_KEY, needs_order: "filter_needs_order" };

/** Nothing left or late to order, running low, fine, or not selling. The word says it; the colour only helps. */
export const FORECAST_STATUS_TONE: Record<StockForecastStatus, "danger" | "warning" | "success" | "neutral"> = {
  out: "danger",
  reorder_now: "danger",
  soon: "warning",
  ok: "success",
  no_sales: "neutral",
};

export const FORECAST_SETTING_KEY: Record<keyof StockForecastSettings, Key> = {
  windowDays: "set_windowDays",
  leadTimeDays: "set_leadTimeDays",
  coverDays: "set_coverDays",
  safetyDays: "set_safetyDays",
};
