import type { Messages } from "@/i18n/LocaleContext";

/** The words of the real-profit page (/profit): its header, the three views, the statement and the way out. */
export const PROFIT_STRINGS = {
  en: {
    title: "Real profit",
    description: "What is left after the product, both shipping legs, fees and ads — counted on delivered orders, not on placed ones.",
    more: "More about profit",
    costs: "Costs",
    costsHint: "What every order really costs you",
    adSpend: "Ad spend",
    adSpendHint: "Record what you paid for ads, day by day",
    hub: "Sales & profit report",
    hubHint: "Sales, the order journey and the other reports",
    settlements: "Courier settlements",
    settlementsHint: "What couriers hold and what reached you",

    rangeLabel: "Date range",
    yesterday: "Yesterday",
    lastDays: "Last {n} days",
    versionLabel: "Profit version",
    actual: "Actual",
    projected: "Projected",
    actualHint: "Finished orders only: delivered or returned.",
    projectedHint: "Adds open orders, assuming {rate} of them get delivered (your delivery rate).",
    projectedNoHistory: "Adds open orders, assuming all of them get delivered — no delivery history yet.",

    netProfit: "Net profit",
    netProfitHint: "After the product, shipping, fees and ads",
    margin: "Profit margin",
    marginHint: "Net profit out of delivered sales",
    maxCpa: "Most you can pay in ads per order",
    maxCpaHint: "Ad cost per placed order before you lose money",
    deliveryRate: "Delivery rate",
    deliveryHint: "{delivered} delivered · {returned} returned · {open} open",

    noCostsSet: "Shipping, return and fee costs are all zero. Set them once to see your real profit.",
    setCosts: "Set costs",
    coverageNone: "None of the delivered pieces has a unit cost, so the profit here reads higher than it really is.",
    coveragePartial: "Only {rate} of the delivered pieces have a unit cost; the rest count as zero cost.",
    openCosts: "Add unit costs",

    perDay: "Net profit day by day",
    perDayNote: "A day that lost money hangs under the line, in red.",
    topProducts: "Net profit by product",
    topCampaigns: "Net profit by campaign",
    topNote: "The top {n} — the rest are in the table.",
    chartEmpty: "Nothing to draw for this period yet.",
    chartSummary: "Net profit for each row, the largest first",

    groupLabel: "Break the profit down by",
    byDay: "By day",
    byProduct: "By product",
    byCampaign: "By campaign",
    dayCaption: "Profit day by day",
    productCaption: "Profit product by product",
    campaignCaption: "Profit campaign by campaign",
    productAdsNote: "Ad spend can't be split per product, so it only appears in the total.",
    colDay: "Day",
    colProduct: "Product",
    colCampaign: "Campaign",
    colNet: "Net profit",
    colMargin: "Margin",
    colRevenue: "Revenue",
    colCosts: "Costs",
    colCostsHint: "The product, both shipping legs, fees and ZIMOS fees",
    colAds: "Ad spend",
    colDelivered: "Delivered",
    colReturned: "Returned",
    colMaxCpa: "Max ad cost per order",
    noCampaign: "No campaign",
    noRows: "No finished orders in this period yet.",

    answerUp: "You kept {amount} — {pct} of every pound you sold.",
    answerDown: "You lost {amount} on what you sold.",
    answerNone: "No finished orders in this period yet.",
    answerBiggest: "The biggest cost was {cost}: {pct} of your sales.",
    cost_costOfGoods: "the products themselves",
    cost_shipping: "shipping and returns",
    cost_fees: "collection and gateway fees",
    cost_adSpend: "ads",
    cost_zimosFees: "ZIMOS fees",

    statement: "Profit statement",
    statementSummary: "From delivered sales down to net profit",
    revenue: "Delivered revenue",
    costOfGoods: "Cost of goods (delivered)",
    shipping: "Outbound shipping (all shipped)",
    returnShipping: "Return shipping",
    fees: "Collection and gateway fees",
    adSpendLine: "Ad spend",
    zimosFees: "ZIMOS fees",
    zimosPerOrderHint: "ZIMOS fee per order, from your prepaid balance",

    emptyTitle: "No finished orders in this period yet",
    emptyHint: "Profit is counted once an order is delivered or comes back. Try a longer period, or wait for the next deliveries.",
    emptyLonger: "Show the last {n} days",
    emptyOrders: "See the orders",
  },
  ar: {
    title: "الأرباح الحقيقية",
    description: "اللي بيفضلك بعد المنتج والشحن رايح جاي والرسوم والإعلانات — محسوب على الأوردرات اللي اتسلّمت، مش اللي اتسجّلت.",
    more: "كمان عن الأرباح",
    costs: "التكاليف",
    costsHint: "كل أوردر بيكلّفك كام فعلاً",
    adSpend: "مصاريف الإعلانات",
    adSpendHint: "سجّل اللي دفعته في الإعلانات يوم بيوم",
    hub: "تقرير المبيعات والربح",
    hubHint: "المبيعات ورحلة الأوردر وباقي التقارير",
    settlements: "تحصيل شركات الشحن",
    settlementsHint: "اللي عند شركات الشحن واللي وصلك",

    rangeLabel: "الفترة",
    yesterday: "إمبارح",
    lastDays: "آخر {n} يوم",
    versionLabel: "نسخة الربح",
    actual: "الفعلي",
    projected: "المتوقَّع",
    actualHint: "الأوردرات اللي خلصت بس: اتسلّمت أو رجعت.",
    projectedHint: "بيضيف الأوردرات المفتوحة على أساس إن {rate} منها هيتسلّم (نسبة التسليم عندك).",
    projectedNoHistory: "بيضيف الأوردرات المفتوحة على أساس إنها كلها هتتسلّم — لسه مفيش سجل تسليم.",

    netProfit: "صافي الربح",
    netProfitHint: "بعد المنتج والشحن والرسوم والإعلانات",
    margin: "هامش الربح",
    marginHint: "صافي الربح من مبيعات اللي اتسلّم",
    maxCpa: "أقصى تكلفة إعلان للأوردر",
    maxCpaHint: "تدفع في الإعلان لحد كده للأوردر قبل ما تخسر",
    deliveryRate: "نسبة التسليم",
    deliveryHint: "{delivered} اتسلّم · {returned} رجع · {open} مفتوح",

    noCostsSet: "مصاريف الشحن والمرتجعات والرسوم كلها صفر. اكتبها مرة واحدة عشان تشوف ربحك الحقيقي.",
    setCosts: "حدّد التكاليف",
    coverageNone: "مفيش تكلفة مكتوبة لأي قطعة اتسلّمت، فالربح هنا طالع أعلى من الحقيقي.",
    coveragePartial: "{rate} بس من القطع اللي اتسلّمت ليها تكلفة، والباقي محسوب بتكلفة صفر.",
    openCosts: "اكتب تكلفة القطع",

    perDay: "صافي الربح يوم بيوم",
    perDayNote: "اليوم اللي خسر بينزل تحت الخط بالأحمر.",
    topProducts: "صافي الربح بالمنتج",
    topCampaigns: "صافي الربح بالحملة",
    topNote: "أعلى {n} — والباقي في الجدول.",
    chartEmpty: "لسه مفيش حاجة تترسم في الفترة دي.",
    chartSummary: "صافي الربح لكل صف، الأكبر في الأول",

    groupLabel: "قسّم الربح حسب",
    byDay: "باليوم",
    byProduct: "بالمنتج",
    byCampaign: "بالحملة",
    dayCaption: "الربح يوم بيوم",
    productCaption: "الربح منتج بمنتج",
    campaignCaption: "الربح حملة بحملة",
    productAdsNote: "مصاريف الإعلانات ما بتتقسّمش على المنتجات، فبتظهر في الإجمالي بس.",
    colDay: "اليوم",
    colProduct: "المنتج",
    colCampaign: "الحملة",
    colNet: "صافي الربح",
    colMargin: "الهامش",
    colRevenue: "المبيعات",
    colCosts: "التكاليف",
    colCostsHint: "المنتج والشحن رايح جاي والرسوم ورسوم زيموس",
    colAds: "الإعلانات",
    colDelivered: "اتسلّم",
    colReturned: "رجع",
    colMaxCpa: "أقصى تكلفة إعلان للأوردر",
    noCampaign: "من غير حملة",
    noRows: "لسه مفيش أوردرات خلصت في الفترة دي.",

    answerUp: "فضلك {amount} — يعني {pct} من كل جنيه بعته.",
    answerDown: "خسرت {amount} على اللي بعته.",
    answerNone: "لسه مفيش أوردرات خلصت في الفترة دي.",
    answerBiggest: "أكبر مصروف كان {cost}: {pct} من مبيعاتك.",
    cost_costOfGoods: "تكلفة المنتجات نفسها",
    cost_shipping: "الشحن والمرتجعات",
    cost_fees: "رسوم التحصيل وبوابات الدفع",
    cost_adSpend: "الإعلانات",
    cost_zimosFees: "رسوم زيموس",

    statement: "قائمة الأرباح",
    statementSummary: "من مبيعات اللي اتسلّم لحد صافي الربح",
    revenue: "مبيعات الأوردرات اللي اتسلّمت",
    costOfGoods: "تكلفة البضاعة (اللي اتسلّمت)",
    shipping: "شحن الرايح (لكل اللي اتشحن)",
    returnShipping: "شحن المرتجعات",
    fees: "رسوم التحصيل وبوابات الدفع",
    adSpendLine: "مصاريف الإعلانات",
    zimosFees: "رسوم زيموس",
    zimosPerOrderHint: "رسوم ZIMOS لكل أوردر من رصيدك المدفوع مقدمًا",

    emptyTitle: "لسه مفيش أوردرات خلصت في الفترة دي",
    emptyHint: "الربح بيتحسب أول ما الأوردر يتسلّم أو يرجع. جرّب فترة أطول، أو استنى التسليمات الجاية.",
    emptyLonger: "اعرض آخر {n} يوم",
    emptyOrders: "شوف الأوردرات",
  },
} satisfies Messages;

export type ProfitStrings = (typeof PROFIT_STRINGS)["en"];
export type ProfitKey = keyof ProfitStrings;

/** Which statement is on screen: finished orders only, or with the open ones weighted in. */
export type ProfitVersion = "actual" | "projected";
