import type { BlockedEntryScope } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Every word of the Blocked tab: the tab, its rows and its two sheets read it through `useT(BLOCKED_STRINGS)`. */
export const BLOCKED_STRINGS = {
  en: {
    add: "Add",
    addLong: "Block something",
    importCsv: "Import",
    typeFilter: "Blocked entries by type",
    listLabel: "Blocked entries",
    all: "All",
    type_phone: "Phone",
    type_ip: "IP address",
    type_email: "Email",
    type_device: "Device",
    type_name_address: "Name + address",
    scope_orders: "Ordering",
    scope_otp: "Verification codes",
    scope_visit: "Visiting the store",
    scopeFilter: "Blocked from",
    scopeChip: "Blocked from: {scope}",
    showResults: "Show the results",
    search: "Search the blocked entries",
    searchPlaceholder: "Number, IP, name or reason",
    colValue: "Blocked",
    colScope: "Blocked from",
    colReason: "Reason",
    colAdded: "Added",
    noReason: "—",
    addedOn: "Added {date}",
    by: "by {name}",
    viewCustomer: "Open customer",
    remove: "Unblock",
    removeTitle: "Unblock {value}?",
    removeDescription: "It will no longer be blocked from this. A blocked phone's customer is un-blacklisted too.",
    removing: "Unblocking…",
    cancel: "Cancel",
    removed: "{value} is no longer blocked.",
    menuLabel: "Actions for this entry",
    menuCopy: "Copy it",
    copied: "Copied",
    emptyTitle: "Nothing is blocked yet",
    emptyDescription: "Block a phone, an IP, an email, a device or a name and address — from ordering, from verification codes, or from seeing the store.",
    emptyFiltered: "Nothing matches this search or these filters.",
    clearAll: "Clear the search and filters",
    addTitle: "Block something",
    addDescription: "Blocking something that is already blocked only updates its reason.",
    what: "What to block",
    value_phone: "Phone number",
    value_ip: "IP address",
    value_email: "Email address",
    value_device: "Device ID",
    name: "Customer name",
    address: "Address",
    nameAddressHint: "Matches orders with this name and this street address, however they are spaced or punctuated.",
    blockFrom: "Block from",
    reason: "Reason (optional)",
    reasonPlaceholder: "Refused three deliveries",
    valueRequired: "Fill this in.",
    valueInvalid_phone: "Enter a valid phone number.",
    valueInvalid_ip: "Enter a valid IP address.",
    valueInvalid_email: "Enter a valid email address.",
    valueInvalid_device: "A device ID is 8 to 128 characters.",
    valueInvalid_name_address: "Enter both a name and an address.",
    scopeRequired: "Choose at least one.",
    save: "Block",
    saving: "Blocking…",
    added: "{value} is now blocked.",
    importTitle: "Import a blocklist",
    importDescription:
      "A CSV file with one entry per line. With a header row, the columns are read by name: type, value, scope, reason, name, address. Without one, the first column is the value and the second the reason.",
    file: "CSV file",
    defaultType: "Type, for rows that do not say",
    defaultScope: "Block from, for rows that do not say",
    chooseFile: "Choose a file first.",
    fileTooBig: "The file is too large (1 MB at most).",
    runImport: "Import",
    importing: "Importing…",
    importDone: "{imported} added, {updated} already there, {skipped} skipped.",
    importErrors: "Lines that were skipped",
    line: "Line {n}: {message}",
    close: "Close",
  },
  ar: {
    add: "ضيف",
    addLong: "احظر حاجة جديدة",
    importCsv: "استورد",
    typeFilter: "المحظورين حسب النوع",
    listLabel: "قايمة المحظورين",
    all: "الكل",
    type_phone: "رقم موبايل",
    type_ip: "عنوان IP",
    type_email: "إيميل",
    type_device: "جهاز",
    type_name_address: "اسم + عنوان",
    scope_orders: "الأوردرات",
    scope_otp: "أكواد التأكيد",
    scope_visit: "زيارة المتجر",
    scopeFilter: "محظور من",
    scopeChip: "محظور من: {scope}",
    showResults: "اعرض النتايج",
    search: "دوّر في المحظورين",
    searchPlaceholder: "رقم، IP، اسم أو سبب",
    colValue: "المحظور",
    colScope: "محظور من",
    colReason: "السبب",
    colAdded: "اتضاف",
    noReason: "—",
    addedOn: "اتضاف {date}",
    by: "بواسطة {name}",
    viewCustomer: "افتح العميل",
    remove: "فك الحظر",
    removeTitle: "تفك الحظر عن {value}؟",
    removeDescription: "مش هيفضل محظور من ده. ولو رقم موبايل، صاحبه هيتشال من المحظورين كمان.",
    removing: "بنفك الحظر…",
    cancel: "إلغاء",
    removed: "اتفك الحظر عن {value}.",
    menuLabel: "إجراءات المحظور",
    menuCopy: "انسخه",
    copied: "اتنسخ",
    emptyTitle: "مفيش حد محظور لسه",
    emptyDescription: "احظر رقم موبايل، IP، إيميل، جهاز أو اسم وعنوان — من الأوردرات، من أكواد التأكيد، أو من إنه يشوف المتجر.",
    emptyFiltered: "مفيش نتايج بالبحث أو الفلاتر دي.",
    clearAll: "امسح البحث والفلاتر",
    addTitle: "احظر حاجة جديدة",
    addDescription: "لو محظور قبل كده، السبب بس هو اللي بيتحدّث.",
    what: "هتحظر إيه",
    value_phone: "رقم الموبايل",
    value_ip: "عنوان IP",
    value_email: "الإيميل",
    value_device: "رقم الجهاز (ID)",
    name: "اسم العميل",
    address: "العنوان",
    nameAddressHint: "بيطابق الأوردرات اللي عليها الاسم ده والعنوان ده، مهما اختلفت المسافات وعلامات الترقيم.",
    blockFrom: "احظره من",
    reason: "السبب (اختياري)",
    reasonPlaceholder: "رفض الاستلام تلات مرات",
    valueRequired: "املا الخانة دي.",
    valueInvalid_phone: "اكتب رقم موبايل صح.",
    valueInvalid_ip: "اكتب عنوان IP صح.",
    valueInvalid_email: "اكتب إيميل صح.",
    valueInvalid_device: "رقم الجهاز من ٨ لـ ١٢٨ حرف.",
    valueInvalid_name_address: "اكتب الاسم والعنوان مع بعض.",
    scopeRequired: "اختار واحدة على الأقل.",
    save: "احظر",
    saving: "بنحظر…",
    added: "{value} اتحظر.",
    importTitle: "استورد قايمة محظورين",
    importDescription:
      "ملف CSV فيه محظور في كل سطر. لو فيه صف عناوين، الأعمدة بتتقرا بأساميها: type, value, scope, reason, name, address. ولو مفيش، العمود الأول هو القيمة والتاني هو السبب.",
    file: "ملف CSV",
    defaultType: "النوع، للسطور اللي مش كاتباه",
    defaultScope: "محظور من، للسطور اللي مش كاتباه",
    chooseFile: "اختار ملف الأول.",
    fileTooBig: "الملف كبير أوي (١ ميجا بالكتير).",
    runImport: "استورد",
    importing: "بنستورد…",
    importDone: "اتضاف {imported}، {updated} موجودين قبل كده، واتفوّت {skipped}.",
    importErrors: "سطور اتفوّتت",
    line: "سطر {n}: {message}",
    close: "اقفل",
  },
} satisfies Messages;

/** Isolates an LTR value (a phone, an IP) inside a sentence of either direction. */
export function isolate(value: string): string {
  return `\u2066${value}\u2069`;
}

/** The tone of the "blocked from" chip: ordering is the heavy one. */
export const SCOPE_TONE: Record<BlockedEntryScope, "danger" | "warning" | "neutral"> = {
  orders: "danger",
  otp: "warning",
  visit: "neutral",
};
