import type { ShopperQuote } from "@store-builder/api-client";

/**
 * The shopper's wording for quote requests (frontend-handoff 219, 275): the
 * "Request a quote" form on the product page and the cart, and the quote's
 * own page. Read with `pickText(QUOTE_TEXT, locale)`.
 */
export const QUOTE_TEXT = {
  en: {
    // The entry and the form
    lead: "Buying in quantity?",
    link: "Request a quote",
    title: "Request a quote",
    intro: "Tell us what you need and how many. We'll come back with a price for your quantity.",
    quantities: "Quantities",
    quantityOf: (name: string) => `Quantity of ${name}`,
    noQuantity: "Add a quantity for at least one item.",
    quantityMax: "The most for one item is 100,000.",
    tooManyLines: "A request takes up to 50 items. Clear the quantity of some.",
    yourDetails: "Your details",
    name: "Full name",
    phone: "Mobile number",
    email: "Email",
    emailHint: "We'll email you when the quote is ready.",
    company: "Company",
    message: "Message",
    messagePlaceholder: "Delivery date, packaging, anything we should know…",
    send: "Send request",
    sending: "Sending…",
    cancel: "Cancel",
    nameError: "Write your name.",
    emailError: "That email doesn't look right. Fix it or leave it empty.",
    tooMany: "You've sent several requests. Try again in a while.",
    unavailable: "One of these products is no longer available.",
    failed: "Your request wasn't sent — try again.",
    sentTitle: "We got it — we'll send you a quote",
    sentNumber: (number: string) => `Request ${number}`,
    sentEmail: "We'll email you when it's ready.",
    sentNoEmail: "Come back to it from this device to see the quote.",
    follow: "Follow your request",
    done: "Done",
    // The quote's page
    metaTitle: "Your quote",
    heading: (number: string) => `Quote ${number}`,
    status: {
      new: "Waiting for the store's prices",
      quoted: "Your quote is ready",
      accepted: "Accepted",
      declined: "Declined",
      cancelled: "Cancelled",
      expired: "Expired",
    } satisfies Record<ShopperQuote["status"], string>,
    newHint: "We received your request. The store will set its prices, and you'll see them here.",
    expiredHint: "This quote has expired — ask for a new one",
    declinedHint: "You declined this quote. You can ask for a new one any time.",
    cancelledHint: "The store cancelled this quote. You can ask for a new one.",
    acceptedTitle: "Quote accepted — your order is placed",
    acceptedOrder: (number: string) => `Order ${number}`,
    acceptedTotal: (total: string) => `Total with shipping: ${total}, paid on delivery.`,
    acceptedHint: "The store will contact you to confirm the delivery.",
    trackOrder: "Track your order",
    items: "What you asked for",
    quantity: "Quantity",
    askedFor: (n: string) => `You asked for ${n}`,
    listPrice: "Store price",
    yourPrice: "Your price",
    each: "each",
    lineTotal: "Total",
    notOffered: "Not included in this quote",
    unknownProduct: "A product that is no longer sold",
    total: "Quote total",
    plusShipping: "Shipping is added by your address. You pay on delivery.",
    validUntil: (date: string) => `Valid until ${date}`,
    storeNote: "Note from the store",
    yourMessage: "Your message",
    accept: "Accept and order",
    decline: "Decline",
    addressTitle: "Where should we deliver?",
    orderNotes: "Notes for the order",
    accepting: "Placing your order…",
    declineTitle: "Decline this quote?",
    declineBody: "The store is told you're not going ahead. You can ask for a new quote any time.",
    confirmDecline: "Yes, decline",
    keep: "Keep the quote",
    declining: "Declining…",
    closedMeanwhile: "This quote changed while you were here — this is how it stands now.",
    missingTitle: "We can't open this quote here",
    missingBody: "A quote opens only in the browser the request was sent from. Open this link on that device, or ask for a new quote.",
    loadFailed: "We couldn't load the quote. Check your connection and try again.",
    retry: "Try again",
    loading: "Loading your quote…",
    backToStore: "Back to the store",
    addressProblem: "Check the delivery address and try again.",
    stockProblem: "The store doesn't have all of this quantity right now. Contact the store to update the quote.",
  },
  ar: {
    lead: "بتشتري كمية؟",
    link: "اطلب عرض سعر",
    title: "اطلب عرض سعر",
    intro: "قولّنا محتاج إيه وكام قطعة، وهنرد عليك بسعر للكمية دي.",
    quantities: "الكميات",
    quantityOf: (name: string) => `كمية ${name}`,
    noQuantity: "اكتب كمية لمنتج واحد على الأقل.",
    quantityMax: "أقصى كمية للمنتج الواحد 100,000.",
    tooManyLines: "الطلب بياخد لحد 50 منتج. امسح كمية بعضهم.",
    yourDetails: "بياناتك",
    name: "الاسم بالكامل",
    phone: "رقم الموبايل",
    email: "الإيميل",
    emailHint: "هنبعتلك إيميل لما العرض يجهز.",
    company: "الشركة",
    message: "رسالة",
    messagePlaceholder: "ميعاد التسليم، التغليف، أي حاجة لازم نعرفها…",
    send: "ابعت الطلب",
    sending: "بنبعت…",
    cancel: "إلغاء",
    nameError: "اكتب اسمك.",
    emailError: "الإيميل ده مش مظبوط. صلّحه أو سيبه فاضي.",
    tooMany: "بعت طلبات كتير. جرّب تاني بعد شوية.",
    unavailable: "منتج من دول مبقاش متاح.",
    failed: "الطلب ما اتبعتش — جرّب تاني.",
    sentTitle: "وصلنا طلبك، هنرد عليك بعرض سعر",
    sentNumber: (number: string) => `طلب رقم ${number}`,
    sentEmail: "هنبعتلك إيميل لما يجهز.",
    sentNoEmail: "ارجعله من نفس الجهاز علشان تشوف العرض.",
    follow: "تابع طلبك",
    done: "تمام",
    metaTitle: "عرض السعر",
    heading: (number: string) => `عرض سعر ${number}`,
    status: {
      new: "مستني سعر المتجر",
      quoted: "عرض السعر جاهز",
      accepted: "اتقبل",
      declined: "اترفض",
      cancelled: "اتلغى",
      expired: "انتهى",
    } satisfies Record<ShopperQuote["status"], string>,
    newHint: "طلبك وصل. المتجر هيحدد أسعاره وهتشوفها هنا.",
    expiredHint: "عرض السعر انتهى — اطلب واحد جديد",
    declinedHint: "انت رفضت العرض ده. تقدر تطلب عرض جديد في أي وقت.",
    cancelledHint: "المتجر لغى العرض ده. تقدر تطلب عرض جديد.",
    acceptedTitle: "تم قبول العرض وطلبك اتسجل",
    acceptedOrder: (number: string) => `طلب رقم ${number}`,
    acceptedTotal: (total: string) => `الإجمالي بالشحن: ${total}، الدفع عند الاستلام.`,
    acceptedHint: "المتجر هيتواصل معاك لتأكيد التوصيل.",
    trackOrder: "تتبّع طلبك",
    items: "اللي طلبته",
    quantity: "الكمية",
    askedFor: (n: string) => `طلبت ${n}`,
    listPrice: "سعر المتجر",
    yourPrice: "سعرك",
    each: "للقطعة",
    lineTotal: "الإجمالي",
    notOffered: "مش ضمن العرض ده",
    unknownProduct: "منتج مبقاش بيتباع",
    total: "إجمالي العرض",
    plusShipping: "الشحن بيتضاف حسب عنوانك. الدفع عند الاستلام.",
    validUntil: (date: string) => `صالح لحد ${date}`,
    storeNote: "ملاحظة من المتجر",
    yourMessage: "رسالتك",
    accept: "موافق — اطلب",
    decline: "رفض",
    addressTitle: "نوصّل الطلب فين؟",
    orderNotes: "ملاحظات على الطلب",
    accepting: "بنسجّل طلبك…",
    declineTitle: "ترفض العرض ده؟",
    declineBody: "المتجر هيعرف إنك مش مكمّل. تقدر تطلب عرض جديد في أي وقت.",
    confirmDecline: "أيوه، ارفض",
    keep: "خلّي العرض",
    declining: "بنرفض…",
    closedMeanwhile: "العرض اتغيّر وانت هنا — دي حالته دلوقتي.",
    missingTitle: "مش قادرين نفتح العرض ده من هنا",
    missingBody: "العرض بيفتح بس من المتصفح اللي اتبعت منه الطلب. افتح اللينك من نفس الجهاز، أو اطلب عرض جديد.",
    loadFailed: "معرفناش نحمّل العرض. اتأكد من النت وجرّب تاني.",
    retry: "جرّب تاني",
    loading: "بنحمّل عرض السعر…",
    backToStore: "ارجع للمتجر",
    addressProblem: "راجع عنوان التوصيل وجرّب تاني.",
    stockProblem: "الكمية دي مش متاحة كلها عند المتجر دلوقتي. كلّم المتجر يعدّل العرض.",
  },
};

export type QuoteText = (typeof QUOTE_TEXT)["en"];
