import type { CustomerReferralStatus, CustomerReferralVoidReason } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty & rewards → Refer a friend, and the invites card on a
 * customer's page. Arabic is formal, as the rest of the dashboard.
 */
export const REFERRAL_STRINGS = {
  en: {
    // page
    title: "Refer a friend",
    description: "A customer shares their own link; the friend gets an offer on a first order, and the customer is rewarded once that order is delivered.",
    stateOn: "Running",
    stateOff: "Off",
    accountsOff: "Customer accounts are off, so no customer can get an invite link: the link lives in the customer's account on your store.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "Programme settings",
    settingsHint: "You set every number. The reward is given when the friend's order is delivered; a cancelled or returned order cancels the invite.",
    enable: "Turn on “refer a friend”",
    enableHintOn: "Signed-in customers find their invite link in their account on your store.",
    enableHintOff: "Off: invite links stop working. Rewards already given stay as they are.",
    friendTitle: "What the friend gets on a first order",
    friendPercent: "Percent off",
    friendPercentHint: "0 to 50, off the normal price of products.",
    friendPercentError: "Enter a whole number from 0 to 50.",
    percentUnit: "%",
    friendShipping: "Free shipping",
    friendRequired: "Give the friend a percent off, free shipping, or both.",
    rewardTitle: "What your customer gets",
    rewardCredit: "Store credit",
    rewardCreditHint: "Money they can spend at checkout.",
    rewardPoints: "Loyalty points",
    rewardPointsHint: "Added to their points balance.",
    rewardPointsNeedsLoyalty: "The loyalty programme is off. Turn it on to reward with points.",
    openLoyalty: "Open loyalty points",
    rewardAmount: "Credit for each friend",
    rewardAmountError: "Enter the credit your customer gets, from 0.01.",
    rewardPointsAmount: "Points for each friend",
    rewardPointsError: "Enter a whole number of points, from 1.",
    minOrder: "Smallest order that earns the reward",
    minOrderHint: "The friend's order total. Leave it empty and any order counts.",
    minOrderError: "Enter a valid amount, or leave it empty.",
    maxRewards: "Most friends one customer is rewarded for",
    maxRewardsHint: "From 1 to 1000. Leave it empty for no limit.",
    maxRewardsError: "Enter a whole number from 1 to 1000, or leave it empty.",
    preview: "Your customers read",
    previewLine: "Your friend gets {friend}; you get {reward} once it's delivered",
    friendPercentPart: "{n}% off their first order",
    friendShippingPart: "free shipping on their first order",
    friendBothPart: "{n}% off and free shipping on their first order",
    rewardCreditPart: "{amount} credit",
    points_one: "1 point",
    points_other: "{n} points",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. “Refer a friend” is running.",
    savedOff: "Saved. “Refer a friend” is off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "The friend gets an offer on a first order; your customer is rewarded once it is delivered.",
    groupLimits: "Limits",
    rewardKind: "Reward them with",
    // invites
    invitesTitle: "Invites",
    invitesHint: "Every first order placed with an invite link.",
    filterLabel: "Filter invites by status",
    filterAll: "All",
    status_pending: "Waiting for delivery",
    status_rewarded: "Rewarded",
    status_void: "Cancelled",
    void_cancelled: "The order was cancelled",
    void_returned: "The order was returned",
    void_below_minimum: "The order was under the minimum",
    void_limit_reached: "The customer had reached the most rewards",
    void_program_off: "The programme was off, or had no reward set",
    colInviter: "Invited by",
    colFriend: "Friend",
    colOrder: "Friend's order",
    colStatus: "Status",
    colReward: "Reward",
    colDate: "Date",
    noName: "No name",
    invitesEmptyTitle: "No invites yet",
    invitesEmptyHint: "When a friend orders through a customer's link, the invite shows up here.",
    invitesNoMatch: "No invites with this status.",
    total_one: "1 invite",
    total_other: "{n} invites",
    chipsLabel: "Invites by status",
    showAll: "Show all invites",
    peek: "Preview the invite by {name}",
    menuLabel: "Actions for this invite",
    menuInviter: "Open the inviter",
    menuFriend: "Open the friend",
    menuOrder: "Open the order",
    menuCopy: "Copy the order number",
    copied: "The order number is copied",
    qlTitle: "Invite by {name}",
    qlTotal: "Order total",
    qlInvitedOn: "Order placed",
    qlRewardedOn: "Rewarded on",
    qlNoReward: "Nothing given yet",
    qlNoOrder: "The order is no longer there",
    openOrder: "Open the order",
    openCustomer: "Open the customer",
    // customer card
    cardTitle: "Invites",
    cardHint: "Friends this customer invited, and the invite they came in by.",
    invited: "Invited {name}",
    invitedBy: "Came in by {name}'s invite",
    orderLink: "Order {number}",
  },
  ar: {
    // page
    title: "ادعُ صديقك",
    description: "يشارك العميل رابطه؛ يحصل صديقه على عرض على أول طلب، ويحصل العميل على مكافأته عند تسليم هذا الطلب.",
    stateOn: "مفعّل",
    stateOff: "متوقف",
    accountsOff: "حسابات العملاء متوقفة، لذلك لن يستطيع أي عميل الحصول على رابط دعوة: الرابط موجود في حساب العميل على متجرك.",
    accountsOffAction: "تفعيل حسابات العملاء",
    settingsTitle: "إعدادات البرنامج",
    settingsHint: "أنت من يحدد كل رقم. تُضاف المكافأة عند تسليم طلب الصديق، وإذا أُلغي الطلب أو أُرجع تُلغى الدعوة.",
    enable: "تفعيل «ادعُ صديقك»",
    enableHintOn: "العملاء الذين سجّلوا الدخول يجدون رابط الدعوة في حسابهم على متجرك.",
    enableHintOff: "متوقف: روابط الدعوة لن تعمل. المكافآت التي مُنحت سابقًا تبقى كما هي.",
    friendTitle: "ما يحصل عليه الصديق على أول طلب",
    friendPercent: "نسبة الخصم",
    friendPercentHint: "من ٠ إلى ٥٠، من سعر المنتجات العادي.",
    friendPercentError: "أدخل رقمًا صحيحًا من ٠ إلى ٥٠.",
    percentUnit: "٪",
    friendShipping: "شحن مجاني",
    friendRequired: "امنح الصديق نسبة خصم أو شحنًا مجانيًا أو كليهما.",
    rewardTitle: "ما يحصل عليه عميلك",
    rewardCredit: "رصيد في المتجر",
    rewardCreditHint: "مبلغ يستخدمه في صفحة الدفع.",
    rewardPoints: "نقاط ولاء",
    rewardPointsHint: "تُضاف إلى رصيد نقاطه.",
    rewardPointsNeedsLoyalty: "برنامج الولاء متوقف. فعّله لتكافئ بالنقاط.",
    openLoyalty: "فتح نقاط الولاء",
    rewardAmount: "الرصيد عن كل صديق",
    rewardAmountError: "أدخل الرصيد الذي يحصل عليه عميلك، من ٠٫٠١.",
    rewardPointsAmount: "النقاط عن كل صديق",
    rewardPointsError: "أدخل عدد نقاط صحيحًا، من ١.",
    minOrder: "أقل طلب يستحق المكافأة",
    minOrderHint: "إجمالي طلب الصديق. اتركه فارغًا فيُحتسب أي طلب.",
    minOrderError: "أدخل مبلغًا صحيحًا، أو اتركه فارغًا.",
    maxRewards: "أقصى عدد أصدقاء يُكافأ العميل عليهم",
    maxRewardsHint: "من ١ إلى ١٠٠٠. اتركه فارغًا إذا لم يكن هناك حد أقصى.",
    maxRewardsError: "أدخل رقمًا صحيحًا من ١ إلى ١٠٠٠، أو اتركه فارغًا.",
    preview: "سيقرأ عملاؤك",
    previewLine: "يحصل صديقك على {friend}، وتحصل أنت على {reward} عند استلامه الطلب",
    friendPercentPart: "خصم {n}٪ على أول طلب",
    friendShippingPart: "شحن مجاني على أول طلب",
    friendBothPart: "خصم {n}٪ وشحن مجاني على أول طلب",
    rewardCreditPart: "{amount} رصيد",
    points_one: "نقطة واحدة",
    points_two: "نقطتان",
    points_few: "{n} نقاط",
    points_other: "{n} نقطة",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ.",
    savedOn: "تم الحفظ. «ادعُ صديقك» مفعّل.",
    savedOff: "تم الحفظ. «ادعُ صديقك» متوقف.",
    fixFields: "راجع الحقول المشار إليها.",
    customerGets: "يحصل الصديق على عرض على أول طلب، ويحصل عميلك على مكافأته عند تسليم الطلب.",
    groupLimits: "الحدود",
    rewardKind: "المكافأة بـ",
    // invites
    invitesTitle: "الدعوات",
    invitesHint: "كل أول طلب تم عبر رابط دعوة.",
    filterLabel: "تصفية الدعوات بحسب الحالة",
    filterAll: "الكل",
    status_pending: "بانتظار التوصيل",
    status_rewarded: "تمت المكافأة",
    status_void: "ملغاة",
    void_cancelled: "أُلغي الطلب",
    void_returned: "أُرجع الطلب",
    void_below_minimum: "الطلب أقل من الحد الأدنى",
    void_limit_reached: "كان العميل قد وصل إلى أقصى عدد مكافآت",
    void_program_off: "كان البرنامج متوقفًا، أو دون مكافأة",
    colInviter: "الداعي",
    colFriend: "الصديق",
    colOrder: "طلب الصديق",
    colStatus: "الحالة",
    colReward: "المكافأة",
    colDate: "التاريخ",
    noName: "بدون اسم",
    invitesEmptyTitle: "لا توجد دعوات بعد",
    invitesEmptyHint: "عندما يطلب صديق عبر رابط عميل، ستظهر الدعوة هنا.",
    invitesNoMatch: "لا توجد دعوات بهذه الحالة.",
    total_one: "دعوة واحدة",
    total_two: "دعوتان",
    total_few: "{n} دعوات",
    total_other: "{n} دعوة",
    chipsLabel: "الدعوات بحسب الحالة",
    showAll: "عرض كل الدعوات",
    peek: "معاينة دعوة {name}",
    menuLabel: "إجراءات الدعوة",
    menuInviter: "فتح الداعي",
    menuFriend: "فتح الصديق",
    menuOrder: "فتح الطلب",
    menuCopy: "نسخ رقم الطلب",
    copied: "تم نسخ رقم الطلب",
    qlTitle: "دعوة {name}",
    qlTotal: "إجمالي الطلب",
    qlInvitedOn: "تاريخ الطلب",
    qlRewardedOn: "تاريخ المكافأة",
    qlNoReward: "لم تُمنح مكافأة بعد",
    qlNoOrder: "الطلب لم يعد موجودًا",
    openOrder: "فتح الطلب",
    openCustomer: "فتح العميل",
    // customer card
    cardTitle: "الدعوات",
    cardHint: "الأصدقاء الذين دعاهم هذا العميل، والدعوة التي جاء عبرها.",
    invited: "دعا {name}",
    invitedBy: "جاء بدعوة من {name}",
    orderLink: "طلب {number}",
  },
} satisfies Messages;

export type ReferralStrings = (typeof REFERRAL_STRINGS)["en"];

export const REFERRAL_STATUS_KEY: Record<CustomerReferralStatus, keyof ReferralStrings> = {
  pending: "status_pending",
  rewarded: "status_rewarded",
  void: "status_void",
};

export const REFERRAL_STATUS_TONE: Record<CustomerReferralStatus, "warning" | "success" | "neutral"> = {
  pending: "warning",
  rewarded: "success",
  void: "neutral",
};

export const REFERRAL_VOID_KEY: Record<CustomerReferralVoidReason, keyof ReferralStrings> = {
  cancelled: "void_cancelled",
  returned: "void_returned",
  below_minimum: "void_below_minimum",
  limit_reached: "void_limit_reached",
  program_off: "void_program_off",
};
