import type { CustomerReferralStatus, CustomerReferralVoidReason } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty & rewards → Refer a friend, and the invites card on a
 * customer's page (handoff 222). Arabic is the merchant's Egyptian, with the
 * handoff's wording.
 */
export const REFERRAL_STRINGS = {
  en: {
    // page
    title: "Refer a friend",
    description: "A customer shares their own link; the friend gets an offer on a first order, and the customer is rewarded once that order is delivered.",
    stateOn: "Running",
    stateOff: "Off",
    accountsOff: "Customer accounts are off, so no customer can get an invite link: the link lives in the customer's account on your store.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "Programme settings",
    settingsHint: "You set every number. The reward is given when the friend's order is delivered; a cancelled or returned order cancels the invite.",
    enable: "Turn on “refer a friend”",
    enableHintOn: "Signed-in customers find their invite link in their account on your store.",
    enableHintOff: "Off: invite links stop working. Rewards already given stay as they are.",
    friendTitle: "What the friend gets on a first order",
    friendPercent: "Percent off",
    friendPercentHint: "0 to 50, off the normal price of products.",
    friendPercentError: "Enter a whole number from 0 to 50.",
    percentUnit: "%",
    friendShipping: "Free shipping",
    friendRequired: "Give the friend a percent off, free shipping, or both.",
    rewardTitle: "What your customer gets",
    rewardCredit: "Store credit",
    rewardCreditHint: "Money they can spend at checkout.",
    rewardPoints: "Loyalty points",
    rewardPointsHint: "Added to their points balance.",
    rewardPointsNeedsLoyalty: "The loyalty programme is off. Turn it on to reward with points.",
    openLoyalty: "Open loyalty points",
    rewardAmount: "Credit for each friend",
    rewardAmountError: "Enter the credit your customer gets, from 0.01.",
    rewardPointsAmount: "Points for each friend",
    rewardPointsError: "Enter a whole number of points, from 1.",
    minOrder: "Smallest order that earns the reward",
    minOrderHint: "The friend's order total. Leave it empty and any order counts.",
    minOrderError: "Enter a valid amount, or leave it empty.",
    maxRewards: "Most friends one customer is rewarded for",
    maxRewardsHint: "From 1 to 1000. Leave it empty for no limit.",
    maxRewardsError: "Enter a whole number from 1 to 1000, or leave it empty.",
    preview: "Your customers read",
    previewLine: "Your friend gets {friend}; you get {reward} once it's delivered",
    friendPercentPart: "{n}% off their first order",
    friendShippingPart: "free shipping on their first order",
    friendBothPart: "{n}% off and free shipping on their first order",
    rewardCreditPart: "{amount} credit",
    points_one: "1 point",
    points_other: "{n} points",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. “Refer a friend” is running.",
    savedOff: "Saved. “Refer a friend” is off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "The friend gets an offer on a first order; your customer is rewarded once it is delivered.",
    groupLimits: "Limits",
    rewardKind: "Reward them with",
    // invites
    invitesTitle: "Invites",
    invitesHint: "Every first order placed with an invite link.",
    filterLabel: "Filter invites by status",
    filterAll: "All",
    status_pending: "Waiting for delivery",
    status_rewarded: "Rewarded",
    status_void: "Cancelled",
    void_cancelled: "The order was cancelled",
    void_returned: "The order was returned",
    void_below_minimum: "The order was under the minimum",
    void_limit_reached: "The customer had reached the most rewards",
    void_program_off: "The programme was off, or had no reward set",
    colInviter: "Invited by",
    colFriend: "Friend",
    colOrder: "Friend's order",
    colStatus: "Status",
    colReward: "Reward",
    colDate: "Date",
    noName: "No name",
    invitesEmptyTitle: "No invites yet",
    invitesEmptyHint: "When a friend orders through a customer's link, the invite shows up here.",
    invitesNoMatch: "No invites with this status.",
    total_one: "1 invite",
    total_other: "{n} invites",
    chipsLabel: "Invites by status",
    showAll: "Show all invites",
    peek: "Preview the invite by {name}",
    menuLabel: "Actions for this invite",
    menuInviter: "Open the inviter",
    menuFriend: "Open the friend",
    menuOrder: "Open the order",
    menuCopy: "Copy the order number",
    copied: "The order number is copied",
    qlTitle: "Invite by {name}",
    qlTotal: "Order total",
    qlInvitedOn: "Order placed",
    qlRewardedOn: "Rewarded on",
    qlNoReward: "Nothing given yet",
    qlNoOrder: "The order is no longer there",
    openOrder: "Open the order",
    openCustomer: "Open the customer",
    // customer card
    cardTitle: "Invites",
    cardHint: "Friends this customer invited, and the invite they came in by.",
    invited: "Invited {name}",
    invitedBy: "Came in by {name}'s invite",
    orderLink: "Order {number}",
  },
  ar: {
    // page
    title: "ادعي صاحبك",
    description: "العميل بيشارك اللينك بتاعه؛ صاحبه ياخد عرض على أول أوردر، والعميل ياخد مكافأته لما الأوردر ده يتسلّم.",
    stateOn: "شغّال",
    stateOff: "مقفول",
    accountsOff: "حسابات العملاء مقفولة، فمفيش عميل هيعرف ياخد لينك دعوة: اللينك موجود في حساب العميل على متجرك.",
    accountsOffAction: "شغّل حسابات العملاء",
    settingsTitle: "إعدادات البرنامج",
    settingsHint: "إنت اللي بتحدد كل رقم. المكافأة بتتضاف لما أوردر الصاحب يتسلّم، ولو الأوردر اتلغى أو اترجّع الدعوة بتتلغي.",
    enable: "شغّل «ادعي صاحبك»",
    enableHintOn: "العملاء اللي مسجّلين دخول بيلاقوا لينك الدعوة في حسابهم على متجرك.",
    enableHintOff: "مقفول: لينكات الدعوة مش هتشتغل. المكافآت اللي اتدّت قبل كده فاضلة زي ما هي.",
    friendTitle: "الصاحب ياخد إيه على أول أوردر",
    friendPercent: "نسبة الخصم",
    friendPercentHint: "من ٠ لـ ٥٠، من سعر المنتجات العادي.",
    friendPercentError: "اكتب رقم صحيح من ٠ لـ ٥٠.",
    percentUnit: "٪",
    friendShipping: "شحن مجاني",
    friendRequired: "ادّي الصاحب نسبة خصم أو شحن مجاني أو الاتنين.",
    rewardTitle: "عميلك ياخد إيه",
    rewardCredit: "رصيد في المتجر",
    rewardCreditHint: "فلوس يصرفها في صفحة الدفع.",
    rewardPoints: "نقط ولاء",
    rewardPointsHint: "بتتضاف على رصيد نقطه.",
    rewardPointsNeedsLoyalty: "برنامج الولاء مقفول. شغّله عشان تكافئ بالنقط.",
    openLoyalty: "افتح نقط الولاء",
    rewardAmount: "الرصيد عن كل صاحب",
    rewardAmountError: "اكتب الرصيد اللي عميلك ياخده، من ٠٫٠١.",
    rewardPointsAmount: "النقط عن كل صاحب",
    rewardPointsError: "اكتب عدد نقط صحيح، من ١.",
    minOrder: "أقل أوردر يستاهل المكافأة",
    minOrderHint: "إجمالي أوردر الصاحب. سيبه فاضي وأي أوردر يتحسب.",
    minOrderError: "اكتب مبلغ صحيح، أو سيبه فاضي.",
    maxRewards: "أقصى عدد أصحاب العميل يتكافئ عليهم",
    maxRewardsHint: "من ١ لـ ١٠٠٠. سيبه فاضي لو مفيش حد أقصى.",
    maxRewardsError: "اكتب رقم صحيح من ١ لـ ١٠٠٠، أو سيبه فاضي.",
    preview: "عملاءك هيقروا",
    previewLine: "صاحبك ياخد {friend}، وانت تاخد {reward} لما يوصله",
    friendPercentPart: "خصم {n}٪ على أول أوردر",
    friendShippingPart: "شحن مجاني على أول أوردر",
    friendBothPart: "خصم {n}٪ وشحن مجاني على أول أوردر",
    rewardCreditPart: "{amount} رصيد",
    points_one: "نقطة واحدة",
    points_two: "نقطتين",
    points_few: "{n} نقط",
    points_other: "{n} نقطة",
    save: "احفظ",
    saving: "بنحفظ…",
    saved: "اتحفظ.",
    savedOn: "اتحفظ. «ادعي صاحبك» شغّال.",
    savedOff: "اتحفظ. «ادعي صاحبك» مقفول.",
    fixFields: "راجع الخانات المتعلّم عليها.",
    customerGets: "الصاحب ياخد عرض على أول أوردر، وعميلك ياخد مكافأته لما الأوردر يتسلّم.",
    groupLimits: "الحدود",
    rewardKind: "كافئه بـ",
    // invites
    invitesTitle: "الدعوات",
    invitesHint: "كل أول أوردر اتعمل بلينك دعوة.",
    filterLabel: "فلترة الدعوات بالحالة",
    filterAll: "الكل",
    status_pending: "مستني التوصيل",
    status_rewarded: "اتكافئ",
    status_void: "اتلغى",
    void_cancelled: "الأوردر اتلغى",
    void_returned: "الأوردر اترجّع",
    void_below_minimum: "الأوردر أقل من الحد الأدنى",
    void_limit_reached: "العميل كان وصل لأقصى عدد مكافآت",
    void_program_off: "البرنامج كان مقفول، أو من غير مكافأة",
    colInviter: "اللي دعا",
    colFriend: "الصاحب",
    colOrder: "أوردر الصاحب",
    colStatus: "الحالة",
    colReward: "المكافأة",
    colDate: "التاريخ",
    noName: "من غير اسم",
    invitesEmptyTitle: "مفيش دعوات لسه",
    invitesEmptyHint: "لما صاحب يطلب من لينك عميل، الدعوة هتظهر هنا.",
    invitesNoMatch: "مفيش دعوات بالحالة دي.",
    total_one: "دعوة واحدة",
    total_two: "دعوتين",
    total_few: "{n} دعوات",
    total_other: "{n} دعوة",
    chipsLabel: "الدعوات بالحالة",
    showAll: "اعرض كل الدعوات",
    peek: "معاينة دعوة {name}",
    menuLabel: "إجراءات الدعوة",
    menuInviter: "افتح اللي دعا",
    menuFriend: "افتح الصاحب",
    menuOrder: "افتح الأوردر",
    menuCopy: "انسخ رقم الأوردر",
    copied: "رقم الأوردر اتنسخ",
    qlTitle: "دعوة {name}",
    qlTotal: "إجمالي الأوردر",
    qlInvitedOn: "تاريخ الأوردر",
    qlRewardedOn: "اتكافئ يوم",
    qlNoReward: "لسه ما اتدّاش حاجة",
    qlNoOrder: "الأوردر مبقاش موجود",
    openOrder: "افتح الأوردر",
    openCustomer: "افتح العميل",
    // customer card
    cardTitle: "الدعوات",
    cardHint: "الأصحاب اللي العميل ده دعاهم، والدعوة اللي هو جه منها.",
    invited: "دعا {name}",
    invitedBy: "جه بدعوة من {name}",
    orderLink: "أوردر {number}",
  },
} satisfies Messages;

export type ReferralStrings = (typeof REFERRAL_STRINGS)["en"];

export const REFERRAL_STATUS_KEY: Record<CustomerReferralStatus, keyof ReferralStrings> = {
  pending: "status_pending",
  rewarded: "status_rewarded",
  void: "status_void",
};

export const REFERRAL_STATUS_TONE: Record<CustomerReferralStatus, "warning" | "success" | "neutral"> = {
  pending: "warning",
  rewarded: "success",
  void: "neutral",
};

export const REFERRAL_VOID_KEY: Record<CustomerReferralVoidReason, keyof ReferralStrings> = {
  cancelled: "void_cancelled",
  returned: "void_returned",
  below_minimum: "void_below_minimum",
  limit_reached: "void_limit_reached",
  program_off: "void_program_off",
};
