import type { TeamChannelProvider } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";
import { notificationTypeLabel, type NotificationStrings } from "@/lib/notificationText";

/** Team channels (handoff 378): the words of the section, its form and its recent messages. */
export const TEAM_CHANNEL_STRINGS = {
  en: {
    title: "Team channels",
    description: "Send the store's alerts to a Telegram group, a Slack channel or a Discord channel you share with your team, media buyer or fulfilment partner.",
    add: "Add channel",
    sandbox: "Test mode — messages are not really sent",
    unavailable: "Not available yet",
    empty: "No channel yet",
    emptyBody: "Add a Telegram group, a Slack channel or a Discord channel and choose which alerts it gets.",
    limit: "Up to 10 team channels",
    limitReached: "This store has its 10 channels. Delete one to add another.",
    provider_telegram: "Telegram",
    provider_slack: "Slack",
    provider_discord: "Discord",
    working: "Working",
    problem: "Problem: {error}",
    problemPlain: "Problem with the last message",
    paused: "Paused",
    notTried: "Nothing sent yet",
    lastSent: "Last message {when}",
    active: "Send alerts to this channel",
    activeHint: "Off pauses the channel without deleting it.",
    pausedByServer: "Paused after 10 failed messages in a row. Check the channel, then switch it back on.",
    noTypes: "No alert chosen",
    test: "Send a test message",
    testing: "Sending…",
    testSent: "The test message was sent to {name}.",
    testSentSandbox: "Test mode: the message was recorded, not really sent.",
    testFailed: "The test message did not arrive: {error}",
    testFailedPlain: "The test message did not arrive.",
    edit: "Edit",
    delete: "Delete",
    recent: "Recent messages",
    deleteTitle: "Delete the channel “{name}”?",
    deleteBody: "It stops getting alerts. Automations that message it will fail on that step.",
    deleted: "The channel was deleted.",
    switchedOn: "The channel is on.",
    switchedOff: "The channel is paused.",
    // form
    addTitle: "Add channel",
    editTitle: "Edit channel",
    providerLabel: "Where do the alerts go?",
    name: "Name",
    namePlaceholder: "Orders group",
    nameRequired: "Type a name for the channel.",
    language: "Message language",
    lang_ar: "Arabic",
    lang_en: "English",
    types: "Alerts this channel gets",
    typesRequired: "Choose at least one alert.",
    botToken: "Bot token",
    chatId: "Group id",
    webhookUrl: "Webhook URL",
    keep: "Leave empty to keep it",
    help_telegram: "1) Message @BotFather, send /newbot and copy the token. 2) Add the bot to your group. 3) Get the group id from @RawDataBot.",
    help_slack: "At api.slack.com/apps, create an app, turn on Incoming Webhooks, pick the channel and copy the URL.",
    help_discord: "Channel settings → Integrations → Webhooks → New Webhook → Copy URL.",
    err_botToken: "Paste the token @BotFather gave you",
    err_chatId: "The group or channel id, like -1001234567890 or @mychannel",
    err_webhook_slack: "A Slack incoming-webhook URL",
    err_webhook_discord: "A Discord webhook URL",
    err_types: "This alert can't go to a team channel",
    err_forbidden: "You can't route this alert",
    err_unavailable: "Team channels are not available right now. Try again in a while.",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    created: "The channel was added. Send a test message to check it.",
    saved: "The channel was saved.",
    // deliveries
    recentTitle: "Recent messages — {name}",
    recentHint: "The last 50 messages, kept for 30 days.",
    recentEmpty: "Nothing was sent to this channel yet.",
    delivery_sent: "Sent",
    delivery_failed: "Failed",
    delivery_test: "Test message",
    delivery_automation_step: "Automation message",
    close: "Close",
    // alert types the notification table has no words for yet
    type_automation: "Automation",
    type_payment_disputed: "Disputed payments",
    type_subscription_renewal_paused: "Subscription renewals paused",
  },
  ar: {
    title: "قنوات الفريق",
    description: "ابعت تنبيهات المتجر لجروب تيليجرام أو قناة Slack أو Discord بتشاركها مع فريقك أو الميديا باير أو شريك التجهيز.",
    add: "أضف قناة",
    sandbox: "وضع تجريبي — الرسائل مش بتتبعت فعلاً",
    unavailable: "غير متاح حاليًا",
    empty: "مفيش قنوات لسه",
    emptyBody: "ضيف جروب تيليجرام أو قناة Slack أو Discord واختار التنبيهات اللي توصلها.",
    limit: "الحد الأقصى ١٠ قنوات",
    limitReached: "المتجر فيه ١٠ قنوات. امسح واحدة عشان تضيف غيرها.",
    provider_telegram: "تيليجرام",
    provider_slack: "Slack",
    provider_discord: "Discord",
    working: "شغّالة",
    problem: "فيه مشكلة: {error}",
    problemPlain: "فيه مشكلة في آخر رسالة",
    paused: "متوقفة",
    notTried: "لسه متبعتش حاجة",
    lastSent: "آخر رسالة {when}",
    active: "ابعت التنبيهات للقناة دي",
    activeHint: "لو قفلتها القناة بتقف من غير ما تتمسح.",
    pausedByServer: "اتوقفت بعد ١٠ رسايل فشلت ورا بعض. راجع القناة وشغّلها تاني.",
    noTypes: "مفيش تنبيه متختار",
    test: "إرسال رسالة تجريبية",
    testing: "بنبعت…",
    testSent: "الرسالة التجريبية اتبعتت لـ {name}.",
    testSentSandbox: "وضع تجريبي: الرسالة اتسجّلت ومتبعتتش فعلاً.",
    testFailed: "الرسالة التجريبية ما وصلتش: {error}",
    testFailedPlain: "الرسالة التجريبية ما وصلتش.",
    edit: "تعديل",
    delete: "حذف",
    recent: "آخر الرسائل",
    deleteTitle: "تمسح القناة «{name}»؟",
    deleteBody: "مش هيوصلها تنبيهات تاني، والأتمتة اللي بتبعتلها هتفشل في الخطوة دي.",
    deleted: "القناة اتمسحت.",
    switchedOn: "القناة اشتغلت.",
    switchedOff: "القناة اتوقفت.",
    addTitle: "أضف قناة",
    editTitle: "تعديل القناة",
    providerLabel: "التنبيهات تروح فين؟",
    name: "الاسم",
    namePlaceholder: "جروب الأوردرات",
    nameRequired: "اكتب اسم للقناة.",
    language: "لغة الرسائل",
    lang_ar: "العربية",
    lang_en: "English",
    types: "التنبيهات اللي توصل القناة دي",
    typesRequired: "اختار تنبيه واحد على الأقل.",
    botToken: "توكن البوت",
    chatId: "رقم الجروب",
    webhookUrl: "لينك الـ Webhook",
    keep: "سيبه فاضي لو مش هتغيّره",
    help_telegram: "١) كلّم ‎@BotFather واعمل ‎/newbot وانسخ التوكن. ٢) ضيف البوت للجروب. ٣) هات رقم الجروب من ‎@RawDataBot.",
    help_slack: "من api.slack.com/apps اعمل App وفعّل Incoming Webhooks واختار القناة وانسخ اللينك.",
    help_discord: "إعدادات القناة ← Integrations ← Webhooks ← New Webhook ← Copy URL.",
    err_botToken: "الصق التوكن اللي أداهولك ‎@BotFather",
    err_chatId: "رقم الجروب أو القناة، زي ‎-1001234567890 أو ‎@mychannel",
    err_webhook_slack: "لينك Incoming Webhook من Slack",
    err_webhook_discord: "لينك Webhook من Discord",
    err_types: "النوع ده ما ينفعش يتبعت لقناة",
    err_forbidden: "مش مسموح لك توجّه التنبيه ده",
    err_unavailable: "قنوات الفريق مش متاحة دلوقتي. جرّب تاني بعد شوية.",
    save: "حفظ",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    created: "القناة اتضافت. ابعت رسالة تجريبية عشان تتأكد.",
    saved: "القناة اتحفظت.",
    recentTitle: "آخر الرسائل — {name}",
    recentHint: "آخر ٥٠ رسالة، وبتفضل ٣٠ يوم.",
    recentEmpty: "لسه متبعتش حاجة للقناة دي.",
    delivery_sent: "اتبعتت",
    delivery_failed: "فشلت",
    delivery_test: "رسالة تجريبية",
    delivery_automation_step: "رسالة من الأتمتة",
    close: "إغلاق",
    type_automation: "أتمتة",
    type_payment_disputed: "مدفوعات عليها نزاع",
    type_subscription_renewal_paused: "تجديد اشتراكات متوقف",
  },
} satisfies Messages;

export type TeamChannelStrings = Record<keyof (typeof TEAM_CHANNEL_STRINGS)["en"], string>;

export const providerLabel = (t: TeamChannelStrings, provider: TeamChannelProvider | string): string =>
  (t as Record<string, string | undefined>)[`provider_${provider}`] ?? provider;

/**
 * An alert type in words: this file's own word first («أتمتة» for `automation`,
 * as the handoff asks), then the label the notification table uses, then the
 * code itself for a type neither knows.
 */
export function alertTypeLabel(t: TeamChannelStrings, nt: NotificationStrings, type: string): string {
  const own = (t as Record<string, string | undefined>)[`type_${type.replace(/\./g, "_")}`];
  if (own) return own;
  return notificationTypeLabel(nt, type as Parameters<typeof notificationTypeLabel>[1]);
}
