import type { Messages } from "@/i18n/LocaleContext";

/*
 * Every word of the «المبيعات والربح» tab. Egyptian Arabic, second person,
 * short. Counted words ({orders}, {items}) come whole from lib/plural.ts and
 * amounts are dropped in as elements, so no sentence carries a digit of its
 * own. Both languages list the same keys.
 */
export const SALES_STRINGS = {
  en: {
    note: "Sales count the orders placed in this period. Net profit counts the orders that finished: delivered or returned.",
    retry: "Try again",
    partLoading: "Loading…",
    partFailed: "This part didn't load.",
    partDenied: "This part isn't included in your role.",

    // The KPI strip
    kpiSales: "Total sales",
    kpiSalesHint: "After discounts and refunds, shipping included",
    kpiOrders: "Orders",
    kpiOrdersHint: "Orders placed in this period",
    kpiAov: "Average order",
    kpiAovHint: "Sales ÷ number of orders",
    kpiDelivered: "Delivered sales",
    kpiDeliveredHint: "The money that actually comes in",
    kpiProfit: "Net profit",
    kpiProfitEstimate: "Net profit · estimate",
    kpiBeforeCost: "Left before product cost",
    vsYear: "vs the same days last year",
    profitNone: "No orders in this period to work your profit out from yet.",
    profitOpenRate: "Estimate: includes the orders still on the way, at your delivery rate ({rate}).",
    profitOpenNoRate: "Estimate: counts the orders still on the way as if every one arrives — there are no deliveries yet to work your rate out from.",
    profitMargin: "You keep {n} of every {of} in delivered sales.",
    profitLossWhy: "Shipping, returns and ads cost more than you earned.",
    profitPlain: "From the orders that finished in this period: delivered or returned.",
    beforeCostHint: "Not profit: your product costs are missing.",
    beforeCostOpenHint: "Not profit: your product costs are missing. Includes the orders still on the way.",
    profitFailed: "We couldn't load your net profit.",

    // Product costs are incomplete (the home's wording)
    noRealProfit: "We can't tell you your real profit until you enter what your products cost.",
    costsMissing: "This profit is incomplete — {items} without a cost.",
    costsCoverage: "This profit is incomplete — only {pct} of the pieces delivered have a cost.",
    costsMaybe: "{items} in your store without a cost — the real profit may be lower.",
    costsMissingShort: "{items} without a cost.",
    costsCoverageShort: "Only {pct} of the pieces delivered have a cost.",
    completeCosts: "Complete the costs",

    // The chart
    chartTitle: "{metric}, {by}",
    chartSummary: "{metric} over the period",
    metricLabel: "Show on the chart",
    metricSales: "Sales",
    metricOrders: "Orders",
    metricAov: "Average order",
    metricDelivered: "Delivered sales",
    byHour: "hour by hour",
    byDay: "day by day",
    byWeek: "week by week",
    byMonth: "month by month",
    thisPeriod: "This period",
    basisPrevious: "the period before",
    basisYear: "the same days last year",
    chartWindows: "{current} against {previous} (the dashed line)",
    chartNoCompare: "No comparison — pick one at the top to see the second line.",
    chartEmpty: "Nothing was sold in this period to draw.",

    // The table
    colHour: "Hour",
    colDay: "Day",
    colWeek: "Week",
    colMonth: "Month",
    colOrders: "Orders",
    colSales: "Sales",
    colSalesHint: "Value of the orders placed then",
    colDelivered: "Delivered",
    colDeliveredHint: "Of those orders, the value that reached the customer",
    colAov: "Average order",
    colVisits: "Visits",
    colConversion: "Conversion",
    colConversionHint: "Orders ÷ visits",
    colProfit: "Net profit",
    colProfitHint: "From the profit report for the same day",
    tableNote: "Each row counts the orders placed in it. Conversion = orders ÷ visits.",
    tableNoteProfit: "Net profit comes from the profit report for the same day.",
    tableNoteEstimate: "Net profit comes from the profit report for the same day, estimated for orders still on the way.",
    tableEmpty: "Nothing was sold in this period.",

    // The one sentence
    sayEmpty: "No orders in this period — there is nothing to say about sales yet.",
    sayThin: "Too early to tell: only {orders} in this period. From {min} up we can say where sales are heading.",
    sayAloneOff: "You sold {sales} from {orders} in this period. Pick a comparison at the top and we'll say whether that is up or down.",
    sayAloneNoBase: "You sold {sales} from {orders} in this period. There weren't enough sales in {basis} to measure against.",
    sayFlat: "Your sales are about steady: {sales} against {previous} in {basis}.",
    sayUp: "Your sales are up {pct} on {basis}: {sales} instead of {previous}.",
    sayDown: "Your sales are down {pct} on {basis}: {sales} instead of {previous}.",
    upOrders: "The main reason: orders themselves rose {pct}.",
    upVisits: "The main reason: visits rose {pct}, so more orders came in.",
    upConversion: "The main reason: more of your visitors are ordering — {n} of every {of} of them now place an order.",
    upBasket: "The main reason: each order got bigger — the average is {aov} instead of {before}.",
    downOrders: "The main reason: orders themselves fell {pct}.",
    downVisits: "The main reason: visits fell {pct} — check your ads.",
    downConversion: "The main reason: fewer of your visitors are ordering — only {n} of every {of} of them place an order. See where the store loses them.",
    downBasket: "The main reason: each order got smaller — the average is {aov} instead of {before}. Try an offer that grows the cart.",
    peak: "Orders come in most on {day} around {hour} — put your ads and confirmation calls there.",
    openAds: "Open the ads report",
    openStore: "Open the store report",
    openOffers: "Open offers",

    // More: the profit in detail
    secProfit: "The profit in detail",
    sumProfitKept: "You kept {amount} after every cost",
    sumProfitLost: "You lost {amount}",
    sumProfitKeptEstimate: "Expected: you keep {amount} after every cost",
    sumProfitLostEstimate: "Expected: you lose {amount}",
    sumProfitFloor: "Product costs are missing — not profit yet",
    sumProfitNone: "No finished orders in this period yet",
    versionLabel: "Profit version",
    actual: "Actual",
    projected: "Projected",
    actualHint: "Finished orders only: delivered or returned.",
    projectedHint: "Adds the open orders, assuming {rate} of them get delivered (your delivery rate).",
    projectedNoHistory: "Adds the open orders as if all of them get delivered — no delivery history yet.",
    answerUp: "You kept {amount} — that is {n} of every {of} you sold.",
    answerDown: "You lost {amount} on what you sold.",
    answerNone: "No finished orders in this period yet.",
    answerBiggest: "The biggest cost was {cost}: {n} of every {of} of your sales.",
    costGoods: "the products themselves",
    costShipping: "shipping and returns",
    costFees: "collection and gateway fees",
    costAds: "ads",
    costZimos: "ZIMOS fees",
    noCostsSet: "Shipping, return and fee costs are all zero. Set them once on the costs page to see your real profit.",
    setCosts: "Set the costs",
    coveragePartial: "{pct} of the pieces delivered have a cost; the rest count as zero cost.",
    margin: "Profit margin",
    marginHint: "Net profit ÷ delivered revenue",
    maxCpa: "Most you can pay in ads per order",
    maxCpaHint: "Ad cost per order before you lose money",
    deliveryRate: "Delivery rate",
    deliveryCounts: "{delivered} delivered · {returned} returned · {open} open",
    statement: "Profit statement",
    stRevenue: "Revenue of delivered orders",
    stGoods: "Cost of goods (delivered)",
    stGoodsMissing: "Cost of goods",
    stMissing: "missing",
    stShipping: "Outbound shipping (everything shipped)",
    stReturn: "Return shipping",
    stFees: "Collection and gateway fees",
    stAds: "Ads",
    stZimos: "ZIMOS fees",
    stZimosPerOrder: "ZIMOS fee per order, from your prepaid balance",
    stNet: "Net profit",
    stBeforeCost: "Left before product cost",
    perDay: "Net profit day by day",
    perDayNote: "A bar under the line is a loss.",
    perDayEmpty: "No profit or loss on any day of this period.",
    dayTable: "Profit day by day",
    colNet: "Net profit",
    colMargin: "Margin",
    colRevenue: "Revenue",
    colCosts: "Costs",
    colCostsHint: "Product, both shipping legs and fees",
    colAds: "Ads",
    colDeliveredOrders: "Delivered",
    colReturnedOrders: "Returned",
    dayEmpty: "No finished orders in this period yet.",

    // More: how the total is built
    secBreakdown: "How total sales add up",
    sumBreakdown: "Before discounts, discounts, refunds, shipping",
    grossSales: "Sales before discounts",
    discounts: "Discounts",
    refunds: "Refunds",
    netSales: "Net sales",
    shippingCharged: "Shipping paid by customers",
    totalSales: "Total sales",

    // More: payment methods
    secPayments: "Payment methods",
    sumPayments: "Sales by how the customer paid",
    payCaption: "{orders} · {share} of sales",
    payEmpty: "Nothing was sold in this period.",
    pay_cod: "Cash on delivery",
    pay_card: "Card",
    pay_wallet: "Wallet",
    pay_valu: "valU installments",
    pay_kiosk: "Kiosk (Aman / Masary)",
    pay_paypal: "PayPal",
    pay_bank_transfer: "Bank transfer",

    // More: channels and devices
    secChannels: "Channels",
    sumChannels: "Where the visits that bought came from",
    colChannel: "Channel",
    direct: "Direct",
    channelsEmpty: "No visits in this period yet.",
    secDevices: "Devices",
    sumDevices: "Phone or computer",
    colDevice: "Device",
    dev_mobile: "Mobile",
    dev_laptop: "Laptop",
    dev_desktop: "Desktop",
    dev_tablet: "Tablet",
    dev_unknown: "Unknown",

    // More: when orders come in
    secTimes: "When orders come in",
    sumTimes: "By weekday and hour",
    timesPeak: "Busiest: {day} {hour}",
    timesHint: "By weekday and hour, in the store's time. Darker is busier.",
    timesEmpty: "No orders in this period.",

    // More: cash collected (the old summary)
    secCash: "How much was actually collected?",
    sumCash: "Cash collected, gross profit, delivered orders, visitors",
    collected: "Cash collected",
    collectedHint: "Payments recorded on orders",
    grossProfit: "Gross profit",
    grossProfitHint: "Before shipping, fees and ads",
    grossProfitMissing: "Product costs are missing — we won't call it profit",
    grossProfitPartial: "Only {pct} of the pieces have a cost — the figure is incomplete",
    deliveredOrders: "Orders delivered",
    deliveredOrdersHint: "Reached the customer",
    visitors: "Visitors",
    visitorsHint: "Different people who visited the store",
    cashNote:
      "Gross profit = delivered product sales minus discounts, product cost and refunds — before shipping, fees and ads. The net profit above takes those off too.",
    cashBreakdown: "Where the money stands",
    rowGross: "Gross sales",
    rowGrossSub: "Every order placed, minus cancelled and rejected",
    rowDelivered: "Delivered sales",
    rowDeliveredSub: "Orders that reached the customer",
    rowCollected: "Cash collected",
    rowCollectedSub: "Payments recorded",
    rowRefunded: "Refunds",
    rowRefundedSub: "Money given back to customers",
    rowDiscounts: "Discounts",
    rowDiscountsSub: "On delivered orders",
    rowShipping: "Shipping charged",
    rowShippingSub: "On delivered orders",
    summarySource: "These figures come from the store summary: it counts every order except cancelled and rejected ones, so they can differ a little from the figures above.",
    heldTitle: "Still with the couriers",
    heldSome: "{amount} for {orders} delivered and not settled yet — everything they owe you so far, not only this period.",
    heldNone: "No courier is holding your money right now.",
    heldFailed: "We couldn't load your cash with the couriers.",
    openSettlements: "Open settlements",

    // More: orders by status (the old summary)
    secStatus: "Orders by status",
    sumStatus: "Where this period's orders stand now",
    statusNote: "This period's orders, by where they are now.",
    statusPending: "Waiting for confirmation",
    statusConfirmed: "Confirmed",
    statusPostponed: "Postponed",
    statusUnreachable: "No answer",
    statusRejected: "Rejected",
    statusCancelled: "Cancelled",
    statusDelivered: "Delivered",
    statusReturned: "Returned",
    statusEmpty: "No orders in this period.",

    // Links out
    linkProfit: "Profit report",
    linkProfitDesc: "Profit by product and by campaign, actual and projected",
    linkCosts: "Product costs",
    linkCostsDesc: "Unit cost, shipping and fees",
    linkSettlements: "Settlements",
    linkSettlementsDesc: "Your money with the couriers, and what has reached you",
    linkAds: "Ad spend",
    linkAdsDesc: "Record what you spent so the profit comes out right",
    linkTax: "Tax report",
    linkTaxDesc: "Tax collected, month by month and governorate by governorate",
    linkCartOffers: "Cart offers and gifts",
    linkCartOffersDesc: "The orders and sales each offer brought",
  },
  ar: {
    note: "المبيعات محسوبة من الأوردرات اللي اتعملت في الفترة. صافي الربح محسوب من الأوردرات اللي خلصت: اتسلّمت أو رجعت.",
    retry: "جرّب تاني",
    partLoading: "بنحمّل…",
    partFailed: "الجزء ده ما اتحمّلش.",
    partDenied: "الجزء ده مش ضمن صلاحياتك.",

    // The KPI strip
    kpiSales: "إجمالي المبيعات",
    kpiSalesHint: "بعد الخصومات والمرتجع، ومعاها الشحن",
    kpiOrders: "الأوردرات",
    kpiOrdersHint: "الأوردرات اللي اتعملت في الفترة",
    kpiAov: "متوسط الأوردر",
    kpiAovHint: "المبيعات ÷ عدد الأوردرات",
    kpiDelivered: "مبيعات اتسلّمت",
    kpiDeliveredHint: "الفلوس اللي بتدخل فعلاً",
    kpiProfit: "صافي الربح",
    kpiProfitEstimate: "صافي الربح · تقديري",
    kpiBeforeCost: "الباقي قبل تكلفة المنتج",
    vsYear: "عن نفس الأيام السنة اللي فاتت",
    profitNone: "لسه مفيش أوردرات في الفترة دي نحسب منها ربحك.",
    profitOpenRate: "تقديري: شامل الأوردرات اللي لسه في الطريق بنسبة التسليم بتاعتك ({rate}).",
    profitOpenNoRate: "تقديري: شامل الأوردرات اللي لسه في الطريق على إنها كلها هتتسلّم — لسه مفيش تسليمات نحسب منها نسبتك.",
    profitMargin: "بيفضلّك {n} من كل {of} من مبيعات اللي اتسلّم.",
    profitLossWhy: "الشحن والمرتجعات والإعلانات أكتر من اللي كسبته.",
    profitPlain: "من الأوردرات اللي خلصت في الفترة: اتسلّمت أو رجعت.",
    beforeCostHint: "ده مش ربح — تكلفة منتجاتك ناقصة.",
    beforeCostOpenHint: "ده مش ربح — تكلفة منتجاتك ناقصة. شامل الأوردرات اللي لسه في الطريق.",
    profitFailed: "معرفناش نجيب صافي الربح.",

    // Product costs are incomplete (the home's wording)
    noRealProfit: "مش هنقدر نقولك ربحك الحقيقي لحد ما تكتب تكلفة المنتجات.",
    costsMissing: "الربح ده ناقص — {items} من غير تكلفة.",
    costsCoverage: "الربح ده ناقص — {pct} بس من القطع اللي اتسلّمت ليها تكلفة.",
    costsMaybe: "{items} في متجرك من غير تكلفة — الربح الحقيقي ممكن يطلع أقل.",
    costsMissingShort: "{items} من غير تكلفة.",
    costsCoverageShort: "{pct} بس من القطع اللي اتسلّمت ليها تكلفة.",
    completeCosts: "كمّل التكاليف",

    // The chart
    chartTitle: "{metric} {by}",
    chartSummary: "{metric} على مدار الفترة",
    metricLabel: "اعرض في الرسم",
    metricSales: "المبيعات",
    metricOrders: "الأوردرات",
    metricAov: "متوسط الأوردر",
    metricDelivered: "مبيعات اتسلّمت",
    byHour: "ساعة بساعة",
    byDay: "يوم بيوم",
    byWeek: "أسبوع بأسبوع",
    byMonth: "شهر بشهر",
    thisPeriod: "الفترة دي",
    basisPrevious: "الفترة اللي قبلها",
    basisYear: "نفس الأيام السنة اللي فاتت",
    chartWindows: "{current} قصاد {previous} (الخط المتقطّع)",
    chartNoCompare: "من غير مقارنة — اختار مقارنة من فوق عشان تشوف الخط التاني.",
    chartEmpty: "مفيش مبيعات في الفترة دي نرسمها.",

    // The table
    colHour: "الساعة",
    colDay: "اليوم",
    colWeek: "الأسبوع",
    colMonth: "الشهر",
    colOrders: "الأوردرات",
    colSales: "المبيعات",
    colSalesHint: "قيمة الأوردرات اللي اتعملت في الوقت ده",
    colDelivered: "اتسلّم",
    colDeliveredHint: "من أوردرات الوقت ده، قيمة اللي وصل للعميل",
    colAov: "متوسط الأوردر",
    colVisits: "الزيارات",
    colConversion: "التحويل",
    colConversionHint: "أوردرات ÷ زيارات",
    colProfit: "صافي الربح",
    colProfitHint: "من تقرير الأرباح لنفس اليوم",
    tableNote: "كل صف بيعدّ الأوردرات اللي اتعملت فيه. التحويل = أوردرات ÷ زيارات.",
    tableNoteProfit: "صافي الربح من تقرير الأرباح لنفس اليوم.",
    tableNoteEstimate: "صافي الربح من تقرير الأرباح لنفس اليوم، وتقديري للأوردرات اللي لسه في الطريق.",
    tableEmpty: "مفيش مبيعات في الفترة دي.",

    // The one sentence
    sayEmpty: "مفيش أوردرات في الفترة دي — مفيش حاجة نقولها عن المبيعات لسه.",
    sayThin: "لسه بدري نحكم: {orders} بس في الفترة دي. من أول {min} نقدر نقولك المبيعات رايحة فين.",
    sayAloneOff: "بعت بـ {sales} من {orders} في الفترة دي. اختار مقارنة من فوق عشان نقولك زادت ولا قلّت.",
    sayAloneNoBase: "بعت بـ {sales} من {orders} في الفترة دي. مفيش مبيعات كفاية في {basis} نقيس عليها.",
    sayFlat: "مبيعاتك ثابتة تقريباً: {sales} قصاد {previous} في {basis}.",
    sayUp: "مبيعاتك زادت {pct} عن {basis}: {sales} بدل {previous}.",
    sayDown: "مبيعاتك قلّت {pct} عن {basis}: {sales} بدل {previous}.",
    upOrders: "السبب الأساسي: الأوردرات نفسها زادت {pct}.",
    upVisits: "السبب الأساسي: الزيارات زادت {pct} فجت أوردرات أكتر.",
    upConversion: "السبب الأساسي: اللي بيزوروا المتجر بقوا يطلبوا أكتر — {n} من كل {of} منهم بيعملوا أوردر.",
    upBasket: "السبب الأساسي: الأوردر الواحد كبر — متوسطه بقى {aov} بدل {before}.",
    downOrders: "السبب الأساسي: الأوردرات نفسها قلّت {pct}.",
    downVisits: "السبب الأساسي: الزيارات قلّت {pct} — راجع إعلاناتك.",
    downConversion: "السبب الأساسي: اللي بيزوروا المتجر بقوا يطلبوا أقل — {n} من كل {of} منهم بس بيعملوا أوردر. شوف المتجر بيخسرهم فين.",
    downBasket: "السبب الأساسي: الأوردر الواحد صغر — متوسطه بقى {aov} بدل {before}. جرّب عرض يكبّر السلة.",
    peak: "أكتر وقت بتيجي فيه الأوردرات: {day} حوالي {hour} — ركّز إعلاناتك ومكالمات التأكيد ساعتها.",
    openAds: "افتح تقرير الإعلانات",
    openStore: "افتح تقرير المتجر",
    openOffers: "افتح العروض",

    // More: the profit in detail
    secProfit: "الربح بالتفصيل",
    sumProfitKept: "فضلك {amount} بعد كل المصاريف",
    sumProfitLost: "خسرت {amount}",
    sumProfitKeptEstimate: "متوقَّع يفضلك {amount} بعد كل المصاريف",
    sumProfitLostEstimate: "متوقَّع تخسر {amount}",
    sumProfitFloor: "تكلفة المنتجات ناقصة — لسه مش ربح",
    sumProfitNone: "لسه مفيش أوردرات خلصت في الفترة دي",
    versionLabel: "نسخة الربح",
    actual: "الفعلي",
    projected: "المتوقَّع",
    actualHint: "الأوردرات اللي خلصت بس: اتسلّمت أو رجعت.",
    projectedHint: "بيزوّد الأوردرات المفتوحة على أساس إن {rate} منها هيتسلّم (نسبة التسليم بتاعتك).",
    projectedNoHistory: "بيزوّد الأوردرات المفتوحة على إنها كلها هتتسلّم — لسه مفيش سجل تسليم.",
    answerUp: "فضلك {amount} — يعني {n} من كل {of} بعتهم.",
    answerDown: "خسرت {amount} على اللي بعته.",
    answerNone: "لسه مفيش أوردرات خلصت في الفترة دي.",
    answerBiggest: "أكبر مصروف كان {cost}: {n} من كل {of} من مبيعاتك.",
    costGoods: "تكلفة المنتجات نفسها",
    costShipping: "الشحن والمرتجعات",
    costFees: "رسوم التحصيل وبوابات الدفع",
    costAds: "الإعلانات",
    costZimos: "رسوم زيموس",
    noCostsSet: "تكاليف الشحن والمرتجعات والرسوم كلها صفر. حدّدها مرة واحدة من صفحة التكاليف عشان تشوف ربحك الحقيقي.",
    setCosts: "حدّد التكاليف",
    coveragePartial: "{pct} من القطع اللي اتسلّمت ليها تكلفة؛ الباقي محسوب بتكلفة صفر.",
    margin: "هامش الربح",
    marginHint: "صافي الربح ÷ إيراد اللي اتسلّم",
    maxCpa: "أقصى تكلفة إعلان للأوردر",
    maxCpaHint: "تدفع في الإعلان لحد كده للأوردر قبل ما تخسر",
    deliveryRate: "نسبة التسليم",
    deliveryCounts: "{delivered} اتسلّم · {returned} رجع · {open} لسه مفتوح",
    statement: "قائمة الأرباح",
    stRevenue: "إيراد الأوردرات اللي اتسلّمت",
    stGoods: "تكلفة البضاعة (اللي اتسلّم)",
    stGoodsMissing: "تكلفة البضاعة",
    stMissing: "ناقصة",
    stShipping: "شحن الذهاب (لكل اللي اتشحن)",
    stReturn: "شحن المرتجعات",
    stFees: "رسوم التحصيل وبوابات الدفع",
    stAds: "الإعلانات",
    stZimos: "رسوم ZIMOS",
    stZimosPerOrder: "رسوم ZIMOS لكل أوردر من رصيدك المدفوع مقدمًا",
    stNet: "صافي الربح",
    stBeforeCost: "الباقي قبل تكلفة المنتج",
    perDay: "صافي الربح يوم بيوم",
    perDayNote: "العمود اللي تحت الخط خسارة.",
    perDayEmpty: "مفيش ربح ولا خسارة في أيام الفترة دي.",
    dayTable: "الربح يوم بيوم",
    colNet: "صافي الربح",
    colMargin: "الهامش",
    colRevenue: "الإيراد",
    colCosts: "التكاليف",
    colCostsHint: "المنتج والشحن رايح جاي والرسوم",
    colAds: "الإعلانات",
    colDeliveredOrders: "اتسلّم",
    colReturnedOrders: "رجع",
    dayEmpty: "لسه مفيش أوردرات خلصت في الفترة دي.",

    // More: how the total is built
    secBreakdown: "المبيعات اتكوّنت إزاي",
    sumBreakdown: "قبل الخصم، الخصومات، المرتجع، الشحن",
    grossSales: "المبيعات قبل الخصم",
    discounts: "الخصومات",
    refunds: "المبالغ اللي رجعت",
    netSales: "صافي المبيعات",
    shippingCharged: "الشحن اللي دفعه العملاء",
    totalSales: "إجمالي المبيعات",

    // More: payment methods
    secPayments: "طرق الدفع",
    sumPayments: "المبيعات حسب العميل دفع إزاي",
    payCaption: "{orders} · {share} من المبيعات",
    payEmpty: "مفيش مبيعات في الفترة دي.",
    pay_cod: "الدفع عند الاستلام",
    pay_card: "كارت",
    pay_wallet: "محفظة",
    pay_valu: "تقسيط valU",
    pay_kiosk: "الدفع في الكشك (أمان / مصاري)",
    pay_paypal: "باي بال",
    pay_bank_transfer: "تحويل بنكي",

    // More: channels and devices
    secChannels: "القنوات",
    sumChannels: "الزيارات اللي اشترت جت منين",
    colChannel: "القناة",
    direct: "مباشر",
    channelsEmpty: "مفيش زيارات في الفترة دي لسه.",
    secDevices: "الأجهزة",
    sumDevices: "موبايل ولا كمبيوتر",
    colDevice: "الجهاز",
    dev_mobile: "موبايل",
    dev_laptop: "لابتوب",
    dev_desktop: "كمبيوتر مكتبي",
    dev_tablet: "تابلت",
    dev_unknown: "مش معروف",

    // More: when orders come in
    secTimes: "الأوردرات بتيجي إمتى",
    sumTimes: "حسب اليوم والساعة",
    timesPeak: "أزحم وقت: {day} {hour}",
    timesHint: "حسب اليوم والساعة بتوقيت المتجر. الأغمق أزحم.",
    timesEmpty: "مفيش أوردرات في الفترة دي.",

    // More: cash collected (the old summary)
    secCash: "اتحصّل كام فعلاً؟",
    sumCash: "المبالغ المحصّلة، إجمالي الربح، اللي اتسلّم، والزوار",
    collected: "اتحصّل فعلاً",
    collectedHint: "المدفوعات المسجّلة على الأوردرات",
    grossProfit: "إجمالي الربح",
    grossProfitHint: "قبل الشحن والرسوم والإعلانات",
    grossProfitMissing: "تكلفة المنتجات ناقصة — مش هنسميه ربح",
    grossProfitPartial: "{pct} بس من القطع ليها تكلفة — الرقم ناقص",
    deliveredOrders: "أوردرات اتسلّمت",
    deliveredOrdersHint: "وصلت للعميل",
    visitors: "الزوار",
    visitorsHint: "ناس مختلفة زارت المتجر",
    cashNote:
      "إجمالي الربح = مبيعات المنتجات اللي اتسلّمت ناقص الخصومات وتكلفة المنتجات والمرتجع — قبل الشحن والرسوم والإعلانات. صافي الربح اللي فوق بيخصمهم كمان.",
    cashBreakdown: "الفلوس واقفة فين",
    rowGross: "إجمالي المبيعات",
    rowGrossSub: "كل الأوردرات اللي اتعملت، من غير الملغي والمرفوض",
    rowDelivered: "مبيعات اتسلّمت",
    rowDeliveredSub: "الأوردرات اللي وصلت للعميل",
    rowCollected: "اتحصّل فعلاً",
    rowCollectedSub: "المدفوعات المسجّلة",
    rowRefunded: "المبالغ اللي رجعت",
    rowRefundedSub: "فلوس رجعت للعملاء",
    rowDiscounts: "الخصومات",
    rowDiscountsSub: "على الأوردرات اللي اتسلّمت",
    rowShipping: "الشحن اللي اتحصّل",
    rowShippingSub: "على الأوردرات اللي اتسلّمت",
    summarySource: "الأرقام دي من ملخّص المتجر: بيعدّ كل الأوردرات من غير الملغي والمرفوض، فممكن تختلف شوية عن الأرقام اللي فوق.",
    heldTitle: "لسه عند شركات الشحن",
    heldSome: "{amount} عن {orders} اتسلّموا ولسه ما اتسوّوش — ده كل اللي ليك عندهم لحد دلوقتي، مش الفترة دي بس.",
    heldNone: "مفيش فلوس ليك عند شركات الشحن دلوقتي.",
    heldFailed: "معرفناش نجيب فلوسك عند شركات الشحن.",
    openSettlements: "افتح التسويات",

    // More: orders by status (the old summary)
    secStatus: "الأوردرات حسب الحالة",
    sumStatus: "أوردرات الفترة واقفة فين دلوقتي",
    statusNote: "أوردرات الفترة دي حسب حالتها دلوقتي.",
    statusPending: "مستني تأكيد",
    statusConfirmed: "اتأكد",
    statusPostponed: "متأجل",
    statusUnreachable: "مبيردش",
    statusRejected: "مرفوض",
    statusCancelled: "ملغي",
    statusDelivered: "اتسلّم",
    statusReturned: "مرتجع",
    statusEmpty: "مفيش أوردرات في الفترة دي.",

    // Links out
    linkProfit: "تقرير الأرباح",
    linkProfitDesc: "الربح بالمنتج وبالحملة، فعلي ومتوقَّع",
    linkCosts: "تكاليف المنتجات",
    linkCostsDesc: "تكلفة القطعة والشحن والرسوم",
    linkSettlements: "التسويات",
    linkSettlementsDesc: "فلوسك عند شركات الشحن واللي وصلك منها",
    linkAds: "مصاريف الإعلانات",
    linkAdsDesc: "سجّل اللي صرفته عشان الربح يطلع مظبوط",
    linkTax: "تقرير الضريبة",
    linkTaxDesc: "الضريبة المحصّلة شهر بشهر ومحافظة بمحافظة",
    linkCartOffers: "عروض السلة والهدايا",
    linkCartOffersDesc: "كل عرض جاب أوردرات ومبيعات قد إيه",
  },
} satisfies Messages;

export type SalesStrings = (typeof SALES_STRINGS)["en"];
export type SalesKey = keyof SalesStrings;
