import type { Messages } from "@/i18n/LocaleContext";

/**
 * Delivery date and time slots (handoff 221): the Shipping tab's settings,
 * Orders → Delivery schedule, and the order page's delivery time.
 */
export const DELIVERY_SLOT_STRINGS = {
  en: {
    // settings (Shipping → Delivery times)
    title: "Time slots customers choose from",
    description:
      "At checkout the customer picks a delivery day and a time slot from the ones you set here. The choice is kept on the order and printed on the waybill.",
    toggle: "Let customers choose a delivery day and time",
    hintOff: "Off: customers don't choose a delivery time.",
    hintOn: "Days and times are in your store's own time zone.",
    required: "Customers must choose a time",
    requiredOn: "An order can't be placed without a delivery time.",
    requiredOff: "Customers can order without choosing a time.",
    earliest: "Earliest",
    earliestHint: "The first day a customer can pick, counted from the day they order.",
    today: "Today",
    tomorrow: "Tomorrow",
    inDays: "In {days}",
    cutoff: "Order cutoff time",
    cutoffHint: "Orders placed after this time get the next day as their earliest day.",
    cutoffNoneHint: "No cutoff: every order of the day gets the same earliest day.",
    cutoffClear: "No cutoff",
    notice: "Notice for a same-day slot (minutes)",
    noticeHint: "A slot today is offered only when it starts at least this long after the order. 0 to 1440.",
    horizon: "Days ahead",
    horizonHint: "How many days of slots the customer can choose from. 1 to 60.",
    weeklyTitle: "Weekly slots",
    weeklyHint: "Each day has its own slots. A day with no slot has no delivery.",
    noSlots: "No delivery",
    addSlot: "Add slot",
    addSlotOn: "Add a slot on {day}",
    removeSlot: "Remove slot",
    removeSlotOn: "Remove slot {n} on {day}",
    slotFrom: "From",
    slotTo: "To",
    slotFromOn: "Slot {n} on {day}: starts at",
    slotToOn: "Slot {n} on {day}: ends at",
    capacity: "Orders per slot",
    capacityOn: "Slot {n} on {day}: orders per slot",
    capacityHint: "Empty = unlimited",
    unlimited: "Unlimited",
    copyToEmpty: "Copy to empty days",
    copyToEmptyOn: "Copy {day}'s slots to the days that have none",
    maxSlots: "At most {max} slots a day.",
    errTime: "Enter when the slot starts and ends.",
    errOrder: "A slot must end after it starts.",
    errCapacity: "Enter a number from 1 to 10,000, or leave it empty.",
    errHorizon: "Enter a number of days from 1 to 60.",
    errNotice: "Enter minutes from 0 to 1440.",
    errNoSlots: "Add at least one slot before you turn this on.",
    closedTitle: "Closed days",
    closedHint: "Tap a day with no delivery (a holiday, a day off). Tap it again to reopen it.",
    closedNone: "No closed days.",
    closedList: "Closed:",
    reopenDay: "Reopen {day}",
    dayClosed: "{day}, closed",
    dayNoSlots: "{day}, no slots this weekday",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    closedMax: "At most {max} closed days.",
    noteTitle: "Note under the slots",
    noteHint: "Shown to the customer under the slots at checkout.",
    noteAr: "Arabic",
    noteEn: "English",
    notePlaceholderAr: "التوصيل من 10 الصبح",
    notePlaceholderEn: "Delivery from 10am",
    save: "Save",
    saving: "Saving…",
    discard: "Discard",
    saved: "Saved. Customers see the new slots at checkout right away.",
    fixFirst: "Fix the marked fields first.",
    noManage: "Changing delivery slots needs the store settings permission. Ask the store owner.",
    openSchedule: "Delivery schedule",
    // schedule (Orders → Delivery schedule)
    scheduleTitle: "Delivery schedule",
    scheduleDescription: "The orders booked into each day and slot.",
    backToOrders: "Orders",
    rangeLabel: "Days shown",
    range7: "7 days",
    range14: "14 days",
    range30: "30 days",
    fromDay: "From",
    jumpToday: "Today",
    earlier: "Earlier",
    later: "Later",
    ordersBooked_one: "1 order booked in these days",
    ordersBooked_two: "2 orders booked in these days",
    ordersBooked_few: "{n} orders booked in these days",
    ordersBooked_other: "{n} orders booked in these days",
    noneBooked: "No orders booked in these days yet.",
    slotCount: "{count} of {capacity}",
    slotCountUnlimited_one: "1 order",
    slotCountUnlimited_two: "2 orders",
    slotCountUnlimited_few: "{n} orders",
    slotCountUnlimited_other: "{n} orders",
    slotEmpty: "No orders",
    slotFull: "Full",
    slotOver: "Over capacity",
    slotGone: "This slot is no longer in your weekly slots",
    closedDay: "Closed day",
    todayBadge: "Today",
    colOrder: "Order",
    colCustomer: "Customer",
    colTotal: "Total",
    offTitle: "Customers don't choose a delivery time yet",
    offBody: "Turn on delivery slots and set the week's times in Shipping → Delivery times. Booked orders then show up here by day and slot.",
    offAction: "Set up delivery slots",
    noWeekTitle: "No slots in the week yet",
    noWeekBody: "Add the days and times you deliver in Shipping → Delivery times.",
    nothingTitle: "Nothing to deliver in these days",
    nothingBody: "No slots and no booked orders between these dates.",
    settingsLink: "Slot settings",
    slots_one: "1 slot",
    slots_other: "{n} slots",
    daySummary: "{orders} · {slots}",
    openOrder: "Open order {number}",
    noCustomer: "Customer without a name",
    backToToday: "Back to today",
    daysLabel: "Days and their slots",
    // order page
    deliveryTime: "Delivery time",
    change: "Change",
    setTime: "Set a time",
    noTime: "The customer didn't choose a delivery time.",
    dialogTitle: "Change the delivery time",
    dialogSetTitle: "Set a delivery time",
    day: "Day",
    slot: "Slot",
    pickDayFirst: "Pick a day to see its slots.",
    noSlotsThatDay: "No slots on this day of the week. Pick another day.",
    closedThatDay: "This day is marked closed in your slot settings. You can still book it.",
    booked: "{count} of {capacity} booked",
    bookedUnlimited: "{count} booked",
    full: "Full",
    saveTime: "Save time",
    removeTime: "Remove the time",
    cancel: "Cancel",
    fullConfirmTitle: "This slot is full — book anyway?",
    fullConfirmBody: "{slot} on {day} already holds as many orders as it takes.",
    bookAnyway: "Book anyway",
    chooseAnother: "Choose another",
    timeSaved: "Delivery time changed.",
    timeRemoved: "Delivery time removed.",
    slotMissing: "That slot isn't on this day any more. Pick another one.",
    noOrderManage: "Changing the delivery time needs the orders permission. Ask the store owner.",
    slotsLoadFailed: "We couldn't load your delivery slots.",
    retry: "Try again",
  },
  ar: {
    title: "مواعيد يختار منها العميل",
    description: "في صفحة الدفع العميل بيختار يوم وميعاد التوصيل من المواعيد اللي تحددها هنا. الاختيار بيتحفظ مع الأوردر وبيتطبع على البوليصة.",
    toggle: "خلّي العميل يختار يوم وميعاد التوصيل",
    hintOff: "مقفولة: العميل مش بيختار ميعاد توصيل.",
    hintOn: "الأيام والمواعيد بتوقيت متجرك.",
    required: "لازم العميل يختار ميعاد",
    requiredOn: "الأوردر مش هيتسجّل من غير ميعاد توصيل.",
    requiredOff: "العميل يقدر يطلب من غير ما يختار ميعاد.",
    earliest: "أقرب يوم",
    earliestHint: "أول يوم العميل يقدر يختاره، محسوب من يوم الأوردر.",
    today: "النهارده",
    tomorrow: "بكرة",
    inDays: "بعد {days}",
    cutoff: "آخر ميعاد للأوردر",
    cutoffHint: "الأوردرات بعد الساعة دي أقرب يوم ليها بيتأخر يوم.",
    cutoffNoneHint: "من غير: كل أوردرات اليوم ليها نفس أقرب يوم.",
    cutoffClear: "من غير ميعاد",
    notice: "ميعاد النهارده يبدأ بعد كام دقيقة",
    noticeHint: "ميعاد النهارده بيظهر بس لو هيبدأ بعد المدة دي من وقت الأوردر. من ٠ لـ ١٤٤٠ دقيقة.",
    horizon: "عدد الأيام قدّام",
    horizonHint: "العميل بيختار من مواعيد كام يوم قدّام. من ١ لـ ٦٠.",
    weeklyTitle: "مواعيد الأسبوع",
    weeklyHint: "كل يوم ليه مواعيده. اليوم اللي من غير ميعاد مفيش فيه توصيل.",
    noSlots: "مفيش توصيل",
    addSlot: "ضيف ميعاد",
    addSlotOn: "ضيف ميعاد يوم {day}",
    removeSlot: "امسح الميعاد",
    removeSlotOn: "امسح الميعاد {n} يوم {day}",
    slotFrom: "من",
    slotTo: "لـ",
    slotFromOn: "الميعاد {n} يوم {day}: بيبدأ",
    slotToOn: "الميعاد {n} يوم {day}: بينتهي",
    capacity: "عدد الأوردرات في الميعاد",
    capacityOn: "الميعاد {n} يوم {day}: عدد الأوردرات في الميعاد",
    capacityHint: "فاضي = من غير حد",
    unlimited: "من غير حد",
    copyToEmpty: "انسخ للأيام الفاضية",
    copyToEmptyOn: "انسخ مواعيد {day} للأيام اللي مفيهاش مواعيد",
    maxSlots: "أقصى عدد {max} ميعاد في اليوم.",
    errTime: "اكتب الميعاد بيبدأ وبينتهي إمتى.",
    errOrder: "الميعاد لازم ينتهي بعد ما يبدأ.",
    errCapacity: "اكتب عدد من ١ لـ ١٠٠٠٠، أو سيبها فاضية.",
    errHorizon: "اكتب عدد أيام من ١ لـ ٦٠.",
    errNotice: "اكتب دقايق من ٠ لـ ١٤٤٠.",
    errNoSlots: "ضيف ميعاد واحد على الأقل قبل ما تشغّلها.",
    closedTitle: "أيام مقفولة",
    closedHint: "دوس على اليوم اللي مفيش فيه توصيل (إجازة، عيد). دوس عليه تاني عشان ترجّعه.",
    closedNone: "مفيش أيام مقفولة.",
    closedList: "مقفول:",
    reopenDay: "رجّع {day}",
    dayClosed: "{day}، مقفول",
    dayNoSlots: "{day}، اليوم ده من الأسبوع مفيهوش مواعيد",
    prevMonth: "الشهر اللي فات",
    nextMonth: "الشهر الجاي",
    closedMax: "أقصى عدد {max} يوم مقفول.",
    noteTitle: "ملحوظة تحت المواعيد",
    noteHint: "بتظهر للعميل تحت المواعيد في صفحة الدفع.",
    noteAr: "بالعربي",
    noteEn: "بالإنجليزي",
    notePlaceholderAr: "التوصيل من 10 الصبح",
    notePlaceholderEn: "Delivery from 10am",
    save: "حفظ",
    saving: "بنحفظ…",
    discard: "تجاهل",
    saved: "اتحفظ. العملاء هيشوفوا المواعيد الجديدة في صفحة الدفع على طول.",
    fixFirst: "صلّح الخانات اللي عليها علامة الأول.",
    noManage: "تغيير مواعيد التوصيل محتاج صلاحية إعدادات المتجر. اطلبها من صاحب المتجر.",
    openSchedule: "جدول التوصيل",
    scheduleTitle: "جدول التوصيل",
    scheduleDescription: "الأوردرات المحجوزة في كل يوم وميعاد.",
    backToOrders: "الأوردرات",
    rangeLabel: "عدد الأيام المعروضة",
    range7: "٧ أيام",
    range14: "١٤ يوم",
    range30: "٣٠ يوم",
    fromDay: "من يوم",
    jumpToday: "النهارده",
    earlier: "قبل كده",
    later: "بعد كده",
    ordersBooked_one: "أوردر واحد محجوز في الأيام دي",
    ordersBooked_two: "أوردرين محجوزين في الأيام دي",
    ordersBooked_few: "{n} أوردرات محجوزة في الأيام دي",
    ordersBooked_other: "{n} أوردر محجوز في الأيام دي",
    noneBooked: "لسه مفيش أوردرات محجوزة في الأيام دي.",
    slotCount: "{count} من {capacity}",
    slotCountUnlimited_one: "أوردر واحد",
    slotCountUnlimited_two: "أوردرين",
    slotCountUnlimited_few: "{n} أوردرات",
    slotCountUnlimited_other: "{n} أوردر",
    slotEmpty: "مفيش أوردرات",
    slotFull: "مليان",
    slotOver: "فوق العدد",
    slotGone: "الميعاد ده مبقاش في مواعيد الأسبوع",
    closedDay: "يوم مقفول",
    todayBadge: "النهارده",
    colOrder: "الأوردر",
    colCustomer: "العميل",
    colTotal: "الإجمالي",
    offTitle: "العميل لسه مش بيختار ميعاد توصيل",
    offBody: "شغّل مواعيد التوصيل وحدد مواعيد الأسبوع من الشحن ← مواعيد التوصيل. الأوردرات المحجوزة هتظهر هنا باليوم والميعاد.",
    offAction: "ظبّط مواعيد التوصيل",
    noWeekTitle: "لسه مفيش مواعيد في الأسبوع",
    noWeekBody: "ضيف الأيام والمواعيد اللي بتوصّل فيها من الشحن ← مواعيد التوصيل.",
    nothingTitle: "مفيش توصيل في الأيام دي",
    nothingBody: "مفيش مواعيد ولا أوردرات محجوزة بين التاريخين دول.",
    settingsLink: "إعدادات المواعيد",
    slots_one: "ميعاد واحد",
    slots_two: "ميعادين",
    slots_few: "{n} مواعيد",
    slots_other: "{n} ميعاد",
    daySummary: "{orders} · {slots}",
    openOrder: "افتح الأوردر {number}",
    noCustomer: "عميل من غير اسم",
    backToToday: "ارجع للنهارده",
    daysLabel: "الأيام ومواعيدها",
    deliveryTime: "ميعاد التوصيل",
    change: "تغيير",
    setTime: "حدّد ميعاد",
    noTime: "العميل مختارش ميعاد توصيل.",
    dialogTitle: "تغيير ميعاد التوصيل",
    dialogSetTitle: "تحديد ميعاد التوصيل",
    day: "اليوم",
    slot: "الميعاد",
    pickDayFirst: "اختار اليوم عشان تشوف مواعيده.",
    noSlotsThatDay: "اليوم ده من الأسبوع مفيهوش مواعيد. اختار يوم تاني.",
    closedThatDay: "اليوم ده متعلّم مقفول في إعدادات المواعيد. تقدر تحجز فيه برضه.",
    booked: "محجوز {count} من {capacity}",
    bookedUnlimited: "محجوز {count}",
    full: "مليان",
    saveTime: "احفظ الميعاد",
    removeTime: "شيل الميعاد",
    cancel: "إلغاء",
    fullConfirmTitle: "الميعاد مليان — احجز برضه؟",
    fullConfirmBody: "ميعاد {slot} يوم {day} فيه كل الأوردرات اللي بياخدها.",
    bookAnyway: "احجز برضه",
    chooseAnother: "اختار ميعاد تاني",
    timeSaved: "اتغيّر ميعاد التوصيل.",
    timeRemoved: "اتشال ميعاد التوصيل.",
    slotMissing: "الميعاد ده مبقاش موجود في اليوم ده. اختار ميعاد تاني.",
    noOrderManage: "تغيير ميعاد التوصيل محتاج صلاحية إدارة الأوردرات. اطلبها من صاحب المتجر.",
    slotsLoadFailed: "معرفناش نحمّل مواعيد التوصيل.",
    retry: "جرّب تاني",
  },
} satisfies Messages;

export type DeliverySlotText = Record<keyof (typeof DELIVERY_SLOT_STRINGS)["en"], string>;
