import type { MarketplaceCategory, MarketplaceLanguage, MarketplaceSubmissionStatus } from "@store-builder/api-client";
import { pluralOf } from "@/lib/plural";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * The template marketplace's words (handoff 192), shared by the browse
 * grid, the preview, "Use this template", "Share to marketplace" and "Your
 * templates". Arabic follows the handoff's wording table: «سوق القوالب»,
 * «استخدم القالب ده», «شارك في سوق القوالب», «مستني المراجعة / منشور / محتاج
 * تعديل / اتسحب», «ابعته تاني», «اسحبه».
 */
export const MARKET_STRINGS = {
  en: {
    title: "Template marketplace",
    description: "Funnels other merchants built and we reviewed. Take a free copy and change whatever you like.",
    backToFunnels: "Funnels",
    sections: "Template marketplace sections",
    tabBrowse: "Templates",
    tabMine: "Your templates",
    share: "Share to marketplace",
    // Browse
    search: "Search templates",
    searchPlaceholder: "A name or a word like perfume",
    clearSearch: "Clear search",
    category: "Kind",
    all: "All",
    sort: "Order",
    sortPopular: "Most used",
    sortNew: "Newest",
    language: "Language",
    anyLanguage: "Any language",
    lang_ar: "Arabic",
    lang_en: "English",
    lang_fr: "French",
    cat_ecommerce: "Selling products",
    cat_lead_generation: "Collecting leads",
    cat_webinar: "Webinar",
    cat_digital_product: "Digital product",
    cat_course: "Course",
    cat_service: "Service",
    cat_event: "Event",
    cat_other: "Other",
    by: "By {author}",
    pages_one: "1 page",
    pages_other: "{n} pages",
    used_one: "used once",
    used_other: "used {n} times",
    usedNone: "not used yet",
    preview: "Preview",
    previewOf: "Preview “{name}”",
    use: "Use this template",
    chosen: "Chosen",
    pickThis: "Choose this template",
    pickHint: "Pick a template here, then your product, name and link in the next steps.",
    choose: "Choose “{name}”",
    emptyTitle: "No templates in the marketplace yet",
    emptyBody: "Templates show up here once merchants share their funnels and we review them. You could be the first.",
    noneFitTitle: "No template matches",
    noneFitBody: "Try another word, kind or language.",
    clearFilters: "Clear filters",
    // Preview
    previewTitle: "Template preview",
    pagesLabel: "Template pages",
    device: "Preview size",
    desktop: "Computer",
    mobile: "Phone",
    livePreview: "{name} — {page}",
    onThisPage: "On this page",
    emptyPage: "This page is still empty.",
    notCopied: "Products and offers are not copied — pick yours after",
    close: "Close",
    // Use
    useTitle: "Use “{name}”",
    useBody: "You get a new draft funnel with its {pages}, and change everything from the editor.",
    funnelName: "Funnel name",
    planNote: "It counts as a new funnel on your plan.",
    using: "Making your copy…",
    usedToast: "“{name}” is ready — pick your products and offers before you publish.",
    // Share / edit
    shareBody: "Once we review it, any store can take a free copy of its pages and links — never your products, offers or orders.",
    editTitle: "Edit “{name}”",
    funnel: "Funnel",
    funnelPick: "Choose a funnel",
    funnelTaken: "{name} — already shared",
    alreadyShared: "This funnel is already in the marketplace or waiting for review. Change it from “Your templates”.",
    openMine: "Open “Your templates”",
    noFunnels: "You have no funnels yet. Build one first, then share it.",
    name: "Template name",
    nameHint: "{min} to {max} characters.",
    nameInvalid: "The name has to be {min} to {max} characters.",
    categoryLabel: "What is it for?",
    descriptionLabel: "Description (optional)",
    descriptionHint: "What it sells and why it works. Up to {max} characters.",
    tags: "Search words (optional)",
    tagsHint: "Up to {max} words people search for, like perfume or ramadan.",
    tagsPlaceholder: "Type a word, then Enter",
    tagsLabel: "Search words",
    picture: "Picture (optional)",
    pictureHint: "An https link to a wide picture. It shows on the template's card.",
    pictureInvalid: "The picture link has to start with https://.",
    author: "Shown as the author",
    authorHint: "Left empty, your store's name shows: {store}.",
    templateLanguage: "Template language",
    snapshotNote: "We copy the funnel's pages now. Later edits reach the template only when you press “Resubmit”.",
    unsavedNote: "You have unsaved changes in the editor. Save them first if they should be in the template.",
    listedNote: "This template is listed. If you change it, it goes back to review and leaves the marketplace until we approve it again.",
    send: "Send for review",
    sending: "Sending…",
    sent: "“{name}” was sent for review. Follow it in “Your templates”.",
    saving: "Saving…",
    save: "Save",
    saved: "Saved.",
    savedBackToReview: "Saved — it's back in review.",
    cancel: "Cancel",
    // Your templates
    status_pending: "Pending review",
    status_approved: "Listed",
    status_rejected: "Needs changes",
    status_withdrawn: "Withdrawn",
    hint_pending: "We're reviewing it. Once approved, every store sees it in the marketplace.",
    hint_approved: "Listed in the marketplace.",
    hint_rejected: "Change the funnel, then press “Resubmit”.",
    hint_withdrawn: "Out of the marketplace. Funnels already copied from it stay with their stores.",
    reviewNote: "Reviewer's note",
    fromFunnel: "From the funnel {name}",
    funnelDeleted: "Its funnel was deleted",
    sentOn: "Sent {date}",
    reviewedOn: "Reviewed {date}",
    edit: "Edit",
    resubmit: "Resubmit",
    withdraw: "Withdraw",
    shareAgain: "Share again",
    resubmitTitle: "Resubmit “{name}”?",
    resubmitBody: "We take a fresh copy of the funnel's pages now and send it for review.",
    resubmitListed: "Until we approve it again, it's out of the marketplace.",
    resubmitted: "Sent for review again.",
    withdrawTitle: "Withdraw “{name}”?",
    withdrawBody: "It leaves the marketplace right away and can't be changed again. Funnels already copied from it stay with their stores.",
    withdrawn: "Withdrawn.",
    mineEmptyTitle: "You haven't shared a template yet",
    mineEmptyBody: "Share a funnel that sells well. Once we review it, any store can copy it — without your products, offers or orders.",
  },
  ar: {
    title: "سوق القوالب",
    description: "مسارات بيع عملها تجار تانيين وراجعناها. خد نسخة ببلاش وغيّر فيها اللي انت عايزه.",
    backToFunnels: "مسارات البيع",
    sections: "أقسام سوق القوالب",
    tabBrowse: "القوالب",
    tabMine: "قوالبك",
    share: "شارك في سوق القوالب",
    search: "دوّر على قالب",
    searchPlaceholder: "اسم أو كلمة زي برفان",
    clearSearch: "امسح البحث",
    category: "النوع",
    all: "الكل",
    sort: "الترتيب",
    sortPopular: "الأكتر استخدامًا",
    sortNew: "الأحدث",
    language: "اللغة",
    anyLanguage: "كل اللغات",
    lang_ar: "عربي",
    lang_en: "إنجليزي",
    lang_fr: "فرنساوي",
    cat_ecommerce: "بيع منتجات",
    cat_lead_generation: "جمع عملاء",
    cat_webinar: "ويبينار",
    cat_digital_product: "منتج رقمي",
    cat_course: "كورس",
    cat_service: "خدمة",
    cat_event: "إيفنت",
    cat_other: "حاجة تانية",
    by: "من {author}",
    pages_one: "صفحة واحدة",
    pages_two: "صفحتين",
    pages_few: "{n} صفحات",
    pages_other: "{n} صفحة",
    used_one: "اتستخدم مرة واحدة",
    used_two: "اتستخدم مرتين",
    used_few: "اتستخدم {n} مرات",
    used_other: "اتستخدم {n} مرة",
    usedNone: "لسه محدش استخدمه",
    preview: "معاينة",
    previewOf: "معاينة «{name}»",
    use: "استخدم القالب ده",
    chosen: "اخترته",
    pickThis: "اختار القالب ده",
    pickHint: "اختار قالب من هنا، وفي الخطوات الجاية اختار منتجك واسم مسار البيع ورابطه.",
    choose: "اختار «{name}»",
    emptyTitle: "لسه مفيش قوالب في السوق",
    emptyBody: "القوالب بتظهر هنا أول ما التجار يشاركوا مسارات بيعهم ونراجعها. ممكن تبقى انت الأول.",
    noneFitTitle: "مفيش قالب بالبحث ده",
    noneFitBody: "جرّب كلمة تانية، أو نوع أو لغة تانية.",
    clearFilters: "امسح الفلاتر",
    previewTitle: "معاينة القالب",
    pagesLabel: "صفحات القالب",
    device: "حجم المعاينة",
    desktop: "كمبيوتر",
    mobile: "موبايل",
    livePreview: "{name} — {page}",
    onThisPage: "في الصفحة دي",
    emptyPage: "الصفحة دي لسه فاضية.",
    notCopied: "المنتجات والعروض مش بتتنقل — اختار بتوعك بعدين",
    close: "اقفل",
    useTitle: "استخدم «{name}»",
    useBody: "هيتعمل لك مسار بيع جديد كمسودة فيه {pages}، وتغيّر فيه كل حاجة من المحرر.",
    funnelName: "اسم مسار البيع",
    planNote: "بيتحسب مسار بيع جديد في باقتك.",
    using: "بنعمل نسختك…",
    usedToast: "«{name}» جاهز — اختار منتجاتك وعروضك قبل ما تنشره.",
    shareBody: "بعد ما نراجعه، أي متجر يقدر ياخد نسخة ببلاش من صفحاته وروابطه — من غير منتجاتك ولا عروضك ولا أوردراتك.",
    editTitle: "عدّل «{name}»",
    funnel: "مسار البيع",
    funnelPick: "اختار مسار بيع",
    funnelTaken: "{name} — متشارك قبل كده",
    alreadyShared: "مسار البيع ده متبعت قبل كده، وهو منشور أو مستني المراجعة. عدّله من «قوالبك».",
    openMine: "افتح «قوالبك»",
    noFunnels: "لسه معندكش مسارات بيع. اعمل واحد الأول وبعدين شاركه.",
    name: "اسم القالب",
    nameHint: "من {min} لـ {max} حرف.",
    nameInvalid: "الاسم لازم يكون من {min} لـ {max} حرف.",
    categoryLabel: "القالب ده لإيه؟",
    descriptionLabel: "الوصف (اختياري)",
    descriptionHint: "بيبيع إيه وليه بينجح. لحد {max} حرف.",
    tags: "كلمات للبحث (اختياري)",
    tagsHint: "لحد {max} كلمات الناس بتدوّر بيها، زي برفان أو رمضان.",
    tagsPlaceholder: "اكتب كلمة واضغط Enter",
    tagsLabel: "كلمات البحث",
    picture: "صورة (اختياري)",
    pictureHint: "رابط https لصورة بالعرض. بتظهر على كارت القالب.",
    pictureInvalid: "رابط الصورة لازم يبدأ بـ https://.",
    author: "اسم الناشر",
    authorHint: "لو سبته فاضي هيظهر اسم متجرك: {store}.",
    templateLanguage: "لغة القالب",
    snapshotNote: "بناخد نسخة من صفحات مسار البيع دلوقتي. أي تعديل بعد كده مش هيوصل للقالب غير لما تضغط «ابعته تاني».",
    unsavedNote: "عندك تعديلات مش محفوظة في المحرر. احفظها الأول لو عايزها تبقى في القالب.",
    listedNote: "القالب ده منشور. لو غيّرت فيه حاجة هيرجع للمراجعة ويختفي من السوق لحد ما نوافق عليه تاني.",
    send: "ابعته للمراجعة",
    sending: "بنبعته…",
    sent: "اتبعت «{name}» للمراجعة. تابعه من «قوالبك».",
    saving: "بنحفظ…",
    save: "احفظ",
    saved: "اتحفظ.",
    savedBackToReview: "اتحفظ ورجع للمراجعة.",
    cancel: "إلغاء",
    status_pending: "مستني المراجعة",
    status_approved: "منشور",
    status_rejected: "محتاج تعديل",
    status_withdrawn: "اتسحب",
    hint_pending: "بنراجعه. أول ما نوافق عليه هيظهر في السوق لكل المتاجر.",
    hint_approved: "منشور في السوق.",
    hint_rejected: "عدّل مسار البيع وبعدين اضغط «ابعته تاني».",
    hint_withdrawn: "اتشال من السوق. مسارات البيع اللي اتنسخت منه فاضلة عند أصحابها.",
    reviewNote: "ملاحظة المراجعة",
    fromFunnel: "من مسار البيع «{name}»",
    funnelDeleted: "مسار البيع بتاعه اتمسح",
    sentOn: "اتبعت {date}",
    reviewedOn: "اتراجع {date}",
    edit: "عدّل",
    resubmit: "ابعته تاني",
    withdraw: "اسحبه",
    shareAgain: "شاركه تاني",
    resubmitTitle: "تبعت «{name}» تاني؟",
    resubmitBody: "هناخد نسخة جديدة من صفحات مسار البيع دلوقتي ونبعتها للمراجعة.",
    resubmitListed: "لحد ما نوافق عليه تاني، مش هيظهر في السوق.",
    resubmitted: "اتبعت للمراجعة تاني.",
    withdrawTitle: "تسحب «{name}»؟",
    withdrawBody: "هيتشال من السوق على طول ومش هتقدر تعدّله تاني. مسارات البيع اللي اتنسخت منه فاضلة عند أصحابها.",
    withdrawn: "اتسحب.",
    mineEmptyTitle: "لسه مشاركتش قوالب",
    mineEmptyBody: "شارك مسار بيع بيبيع كويس عندك. بعد ما نراجعه، أي متجر يقدر ياخد نسخة منه — من غير منتجاتك ولا عروضك ولا أوردراتك.",
  },
} satisfies Messages;

export type MarketStrings = (typeof MARKET_STRINGS)["en"];

export const LANGUAGES: MarketplaceLanguage[] = ["ar", "en", "fr"];

export const categoryLabel = (t: MarketStrings, c: MarketplaceCategory): string => t[`cat_${c}`];
export const languageLabel = (t: MarketStrings, l: MarketplaceLanguage): string => t[`lang_${l}`];
export const statusLabel = (t: MarketStrings, s: MarketplaceSubmissionStatus): string => t[`status_${s}`];

export const STATUS_TONE: Record<MarketplaceSubmissionStatus, "warning" | "success" | "danger" | "neutral"> = {
  pending: "warning",
  approved: "success",
  rejected: "danger",
  withdrawn: "neutral",
};

/** «٣ صفحات · اتستخدم مرتين» — the counts on a card, in the viewer's digits. */
export function countsLine(t: MarketStrings, stepCount: number, usesCount: number): string {
  const used = usesCount === 0 ? t.usedNone : pluralOf(t, "used", usesCount);
  return `${pluralOf(t, "pages", stepCount)} · ${used}`;
}
