import type { Messages } from "@/i18n/LocaleContext";

/** The words of the online payments ledger (handoff 384): transactions, payouts, a payout's page. */
export const LEDGER_STRINGS = {
  en: {
    pageTitle: "Online payments",
    pageDescription: "Every gateway payment and refund, what the gateway kept, what reached you, and the payout that sent it to your bank. Cash on delivery and transfers are not here.",
    back: "Payments",
    tabsLabel: "Online payments sections",
    tabTransactions: "Transactions",
    tabPayouts: "Payouts",
    tabDisputes: "Disputes",
    linkToLedger: "Transactions, payouts and disputes",
    linkToLedgerHint: "The ledger of your online payments, with gateway fees",
    // filters
    filters: "Filters",
    gateway: "Gateway",
    method: "Method",
    status: "Status",
    type: "Type",
    from: "From",
    to: "To",
    test: "Test",
    testHint: "Show test-mode payments instead of live ones",
    any: "All",
    clear: "Clear filters",
    status_captured: "Captured",
    status_refunded: "Refunded",
    status_failed: "Failed",
    status_pending: "Pending",
    type_payment: "Payment",
    type_refund: "Refund",
    // summary
    captured: "Captured",
    refunded: "Refunded",
    fees: "Gateway fees",
    net: "Net",
    feesPending: "{n} payments are still waiting for their fee",
    // table
    colDate: "Date",
    colOrder: "Order",
    colType: "Type",
    colStatus: "Status",
    colGateway: "Gateway",
    colAmount: "Amount",
    colFee: "Fee",
    colNet: "Net",
    colPayout: "Payout",
    feeUnknown: "The gateway hasn't reported the fee yet",
    openOrder: "Open order {number}",
    openPayout: "Open the payout",
    noOrder: "No order",
    loadMore: "Load more",
    emptyTitle: "No online payments yet",
    emptyHint: "Payments shoppers make by card or wallet through your gateway show here, with the gateway's fee.",
    noMatchTitle: "Nothing matches these filters",
    noMatchHint: "Change the filters or the dates to see more.",
    // export
    exportMenu: "Export",
    exporting: "Exporting…",
    exportCsv: "Export CSV",
    exportXlsx: "Export Excel",
    exported: "The file was downloaded.",
    fromAfterTo: "The start date is after the end date.",
    // payouts
    payoutsHint: "Payouts are fetched from the gateway once a day",
    colArrival: "Arrival date",
    colFees: "Fees",
    colPayments: "Payments",
    colRefunds: "Refunds",
    payout_pending: "Pending",
    payout_in_transit: "In transit",
    payout_paid: "Paid",
    payout_failed: "Failed",
    payout_canceled: "Canceled",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    refreshed: "Payouts refreshed.",
    refreshedRecently: "Refreshed a moment ago",
    gatewayProblem: "{gateway}: {message}",
    payoutsEmptyTitle: "No payouts yet",
    payoutsEmptyHint: "No payouts yet — only Stripe and the Sandbox report payouts for now",
    // payout page
    payoutTitle: "Payout {amount}",
    payoutBack: "Payouts",
    arrival: "Arrival date",
    gatewayId: "Gateway's id",
    copyId: "Copy id",
    sumPayments: "Payments",
    sumRefunds: "Refunds",
    sumFees: "Fees",
    sumUnmatched: "Not from ZIMOS",
    sumUnmatchedHint: "Gateway adjustments or fees, or sales made outside the store",
    sumTotal: "Total",
    paymentsIn: "Payments in this payout",
    refundsIn: "Refunds in this payout",
    noneIn: "None",
    summary: "Summary",
    gatewayFee: "Gateway fee {fee}",
  },
  ar: {
    pageTitle: "المدفوعات الأونلاين",
    pageDescription: "كل دفعة واسترداد عن طريق البوابة، البوابة خدت كام، وصلّك كام، والتحويل اللي نزّلها على حسابك البنكي. الدفع عند الاستلام والتحويلات مش هنا.",
    back: "المدفوعات",
    tabsLabel: "أقسام المدفوعات الأونلاين",
    tabTransactions: "المعاملات",
    tabPayouts: "التحويلات البنكية",
    tabDisputes: "النزاعات",
    linkToLedger: "المعاملات والتحويلات البنكية والنزاعات",
    linkToLedgerHint: "سجل مدفوعاتك الأونلاين ورسوم البوابة",
    filters: "الفلاتر",
    gateway: "البوابة",
    method: "الطريقة",
    status: "الحالة",
    type: "النوع",
    from: "من",
    to: "إلى",
    test: "تجريبي",
    testHint: "اعرض مدفوعات وضع التجربة بدل الحقيقية",
    any: "الكل",
    clear: "امسح الفلاتر",
    status_captured: "مدفوع",
    status_refunded: "مسترد",
    status_failed: "فشل",
    status_pending: "قيد التنفيذ",
    type_payment: "دفعة",
    type_refund: "استرداد",
    captured: "المحصّل",
    refunded: "المسترد",
    fees: "رسوم البوابة",
    net: "الصافي",
    feesPending: "{n} دفعات رسومها لسه ما وصلتش",
    colDate: "التاريخ",
    colOrder: "الطلب",
    colType: "النوع",
    colStatus: "الحالة",
    colGateway: "البوابة",
    colAmount: "المبلغ",
    colFee: "الرسوم",
    colNet: "الصافي",
    colPayout: "التحويل",
    feeUnknown: "الرسوم لسه ما وصلتش من البوابة",
    openOrder: "افتح الطلب {number}",
    openPayout: "افتح التحويل",
    noOrder: "من غير طلب",
    loadMore: "تحميل المزيد",
    emptyTitle: "مفيش مدفوعات أونلاين لسه",
    emptyHint: "الدفعات اللي العملاء بيدفعوها بالكارت أو المحفظة عن طريق البوابة بتظهر هنا ومعاها رسوم البوابة.",
    noMatchTitle: "مفيش حاجة مطابقة للفلاتر دي",
    noMatchHint: "غيّر الفلاتر أو التواريخ عشان تشوف أكتر.",
    exportMenu: "تصدير",
    exporting: "بنصدّر…",
    exportCsv: "تصدير CSV",
    exportXlsx: "تصدير Excel",
    exported: "الملف اتحمّل.",
    fromAfterTo: "تاريخ البداية بعد تاريخ النهاية.",
    payoutsHint: "بنجيب التحويلات من البوابة مرة كل يوم",
    colArrival: "تاريخ الوصول",
    colFees: "الرسوم",
    colPayments: "مدفوعات",
    colRefunds: "استردادات",
    payout_pending: "معلّق",
    payout_in_transit: "في الطريق",
    payout_paid: "وصل",
    payout_failed: "فشل",
    payout_canceled: "اتلغى",
    refresh: "تحديث",
    refreshing: "بنحدّث…",
    refreshed: "التحويلات اتحدّثت.",
    refreshedRecently: "اتحدّث من شوية",
    gatewayProblem: "{gateway}: {message}",
    payoutsEmptyTitle: "مفيش تحويلات لسه",
    payoutsEmptyHint: "مفيش تحويلات لسه — Stripe والـ Sandbox بس اللي بيبعتوا التحويلات دلوقتي",
    payoutTitle: "تحويل {amount}",
    payoutBack: "التحويلات البنكية",
    arrival: "تاريخ الوصول",
    gatewayId: "رقم التحويل عند البوابة",
    copyId: "انسخ الرقم",
    sumPayments: "المدفوعات",
    sumRefunds: "الاستردادات",
    sumFees: "الرسوم",
    sumUnmatched: "مش من زيموس",
    sumUnmatchedHint: "تسويات أو رسوم من البوابة أو مبيعات من برّه المتجر",
    sumTotal: "الإجمالي",
    paymentsIn: "المدفوعات اللي في التحويل",
    refundsIn: "الاستردادات اللي في التحويل",
    noneIn: "مفيش",
    summary: "الملخص",
    gatewayFee: "رسوم البوابة {fee}",
  },
} satisfies Messages;

export type LedgerStrings = (typeof LEDGER_STRINGS)["en"];

export const LEDGER_PATH = "/payments/transactions";
export const PAYOUT_PATH = (id: string) => `/payments/payouts/${id}`;

/** Gateways a store can connect (the filter's choices); any other code a row carries still shows by its own name. */
export const LEDGER_GATEWAYS = ["paymob", "kashier", "stripe", "paypal", "sandbox"] as const;
export const LEDGER_METHODS = ["card", "wallet", "valu", "kiosk", "paypal"] as const;

export const LEDGER_STATUS_TONE = { captured: "success", refunded: "neutral", failed: "danger", pending: "warning" } as const;
export const PAYOUT_STATUS_TONE = { pending: "warning", in_transit: "info", paid: "success", failed: "danger", canceled: "neutral" } as const;
