import type { Messages } from "@/i18n/LocaleContext";

/** The trash for funnels, websites and pages (handoff 373): the page, its link and the errors it names. */
export const TRASH_STRINGS = {
  en: {
    title: "Trash",
    hint: "Anything in the trash is deleted for good after 30 days",
    hintDays: "Anything in the trash is deleted for good after {n} days",
    backFunnels: "Funnels",
    backWebsite: "Online store",
    link: "Trash",
    linkCount: "Trash ({n})",
    tabs: "Kind",
    all: "All",
    funnels: "Funnels",
    websites: "Websites",
    pages: "Pages",
    kind_funnel: "Funnel",
    kind_website: "Website",
    kind_page: "Page",
    colName: "Name",
    colKind: "Kind",
    colDeleted: "Deleted",
    colPurge: "Deleted for good on",
    colActions: "Actions",
    by: "by {name}",
    pageOf: "{path} · {website}",
    wasPublished: "Was live",
    restore: "Restore",
    restoring: "Restoring…",
    purge: "Delete for good",
    purgeTitle: "Delete “{name}” for good?",
    purgeBodyFunnel: "This can't be undone. Orders keep the funnel's name.",
    purgeBody: "This can't be undone.",
    purging: "Deleting…",
    cancel: "Cancel",
    restored: "“{name}” is back.",
    restoredLive: "“{name}” is back and live again.",
    purged: "“{name}” was deleted for good.",
    needsPublish: "Restoring it puts it live, which needs the publish permission",
    websiteFirst: "Restore its website first",
    emptyTitle: "The trash is empty",
    emptyKind: "Nothing of this kind is in the trash.",
    refresh: "Refresh",
    PAGE_PATH_IN_TRASH: "A page in the trash uses this path. Restore it or delete it for good first",
    WEBSITE_HAS_DOMAINS: "This is the store's only website and its domains point at it. Remove the domains first",
    WEBSITE_IN_TRASH: "Restore its website first",
    NOT_FOUND: "It is no longer in the trash.",
    FUNNEL_SUBDOMAIN_TAKEN: "Another funnel uses its link now. Change that funnel's link first.",
    moved: "Moved to trash",
  },
  ar: {
    title: "سلة المحذوفات",
    hint: "أي حاجة في السلة بتتمسح نهائيًا بعد 30 يوم",
    hintDays: "أي حاجة في السلة بتتمسح نهائيًا بعد {n} يوم",
    backFunnels: "الفانلز",
    backWebsite: "المتجر الإلكتروني",
    link: "سلة المحذوفات",
    linkCount: "سلة المحذوفات ({n})",
    tabs: "النوع",
    all: "الكل",
    funnels: "الفانلز",
    websites: "المواقع",
    pages: "الصفحات",
    kind_funnel: "فانل",
    kind_website: "موقع",
    kind_page: "صفحة",
    colName: "الاسم",
    colKind: "النوع",
    colDeleted: "اتحذف",
    colPurge: "هيتمسح نهائيًا",
    colActions: "إجراءات",
    by: "بواسطة {name}",
    pageOf: "{path} · {website}",
    wasPublished: "كان منشور",
    restore: "استرجاع",
    restoring: "بنرجّعه…",
    purge: "حذف نهائي",
    purgeTitle: "تمسح «{name}» نهائيًا؟",
    purgeBodyFunnel: "مش هتقدر ترجعه تاني. الطلبات هتفضل شايلة اسم الفانل.",
    purgeBody: "مش هتقدر ترجعه تاني.",
    purging: "بنمسح…",
    cancel: "إلغاء",
    restored: "«{name}» رجع.",
    restoredLive: "«{name}» رجع وبقى منشور تاني.",
    purged: "«{name}» اتمسح نهائيًا.",
    needsPublish: "محتاج صلاحية النشر علشان ترجعه",
    websiteFirst: "ارجع الموقع الأول",
    emptyTitle: "سلة المحذوفات فاضية",
    emptyKind: "مفيش حاجة من النوع ده في السلة.",
    refresh: "حدّث",
    PAGE_PATH_IN_TRASH: "فيه صفحة في سلة المحذوفات على الرابط ده. ارجعها أو امسحها نهائيًا الأول",
    WEBSITE_HAS_DOMAINS: "ده الموقع الوحيد والدومينات مربوطة بيه. شيل الدومينات الأول",
    WEBSITE_IN_TRASH: "ارجع الموقع الأول",
    NOT_FOUND: "مبقاش موجود في السلة.",
    FUNNEL_SUBDOMAIN_TAKEN: "فيه فانل تاني بياخد الرابط ده دلوقتي. غيّر رابط الفانل ده الأول.",
    moved: "اتنقل لسلة المحذوفات",
  },
} satisfies Messages;

/** Every list of the trash shares one remembered answer; a delete or a restore forgets it. */
export const trashCacheKey = (workspaceId: string) => `trash:${workspaceId}`;
