import type { StockLotStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Inventory → «الدفعات والصلاحية» / Lots & expiry (handoff 230): the list with
 * its tabs, receiving a lot, editing one, writing units off, the expiry
 * warning, and the product page's card. Arabic is the merchant's Egyptian,
 * with the handoff's wording.
 */
export const LOT_STRINGS = {
  en: {
    // tab
    hint: "Batches of a product with a lot code and an expiry date. Orders take from the lot that expires first.",
    receive: "Receive a lot",
    alertSettings: "Expiry warning",
    filterLabel: "Show lots",
    status_active: "Active",
    status_expiring: "Expiring soon",
    status_expired: "Expired",
    status_empty: "Used up",
    // table
    colProduct: "Product",
    colLot: "Lot",
    colExpiry: "Expiry",
    colRemaining: "Remaining / received",
    colLocation: "Location",
    colActions: "Actions",
    remainingOf: "{remaining} of {received}",
    noExpiry: "No expiry date",
    expiredBadge: "Expired",
    expiresToday: "Expires today",
    expiresIn: "{days} left",
    writtenOffBadge: "Written off",
    purchaseOrder: "Purchase order {number}",
    purchaseOrderPlain: "Purchase order",
    unknownProduct: "Deleted product",
    defaultLocationShort: "{name} (default)",
    deletedLocation: "Deleted location",
    edit: "Edit",
    writeOff: "Write off",
    firstRows: "Showing the first {n} lots.",
    viewOnly: "Your role can see the lots but not change them.",
    // empty
    empty_active_title: "No lots yet",
    empty_active_hint: "Receive a lot with a code and an expiry date. Orders then take from the lot that expires first.",
    empty_expiring_title: "No lots expiring soon",
    empty_expiring_hint: "A lot counts as expiring soon {days} before its date.",
    empty_expired_title: "No expired lots",
    empty_expired_hint: "Lots that pass their date with units left show here, to write off.",
    empty_empty_title: "No used-up lots",
    empty_empty_hint: "Lots whose units were all sold or written off show here.",
    // receive dialog
    receiveTitle: "Receive a lot",
    receiveDescription: "Record a batch with its lot code and expiry date.",
    product: "Product",
    productError: "Choose the product.",
    lotCode: "Lot code",
    lotCodePlaceholder: "A-10",
    lotCodeError: "Enter the lot code.",
    expiresOn: "Expiry date (optional)",
    expiresHint: "Leave it empty for a lot without a date.",
    expiresPast: "This date has already passed: the lot will be listed as expired.",
    quantity: "Quantity",
    quantityError: "Enter a whole number above zero.",
    location: "Location",
    addToStock: "Add to stock",
    addToStockOn: "These units are added to the product's stock.",
    addToStockOff: "Nothing is added: the lot labels units you already have.",
    purchaseOrderField: "Purchase order (optional)",
    noPurchaseOrder: "No purchase order",
    purchaseOrderOption: "{number} — {supplier}",
    countedTwice: "Units received on that purchase order are already in your stock. Turn off “Add to stock” so they aren't counted twice.",
    note: "Note (optional)",
    receiveSubmit: "Receive lot",
    saving: "Saving…",
    received: "Lot received and added to stock.",
    labelled: "Lot recorded.",
    onlyUnlabelled: "Only {n} units are on hand without a lot",
    cancel: "Cancel",
    // edit dialog
    editTitle: "Edit lot",
    editDescription: "Correct the code, the expiry date or the note. The quantity changes with orders and write-offs.",
    save: "Save",
    saved: "Lot saved.",
    // write-off dialog
    writeOffTitle: "Write off",
    writeOffConfirm: "These units leave stock",
    remaining: "Left in this lot",
    writeOffQuantity: "Quantity to write off",
    writeOffQuantityError: "Enter a number from 1 to {n}.",
    reason: "Reason (optional)",
    reasonPlaceholder: "Expired",
    writeOffSubmit: "Write off",
    writingOff: "Writing off…",
    writtenOff: "{pieces} written off and taken out of stock.",
    lotNotEnough: "This lot has only {n} units left.",
    lotChanged: "This lot no longer has that many units. The list shows it as it is now.",
    stockShort: "Your stock itself holds fewer units than that. Write off less, or correct the stock first.",
    // expiry warning dialog
    alertTitle: "Expiry warning",
    alertDescription: "You get a notification and an email when a lot is about to expire.",
    alertSentence: "Warn me {n} days before expiry",
    alertRange: "From 1 to 365",
    alertError: "Enter a whole number from 1 to 365.",
    alertSaved: "Expiry warning saved.",
    // product page card
    cardTitle: "Lots & expiry",
    cardDescription: "This product's lots that still hold units, the first to go on top.",
    cardRemaining: "{pieces} left",
    singleVariant: "One variant",
    manageLots: "Manage lots",
  },
  ar: {
    hint: "دفعات المنتج بكود الدفعة وتاريخ الصلاحية. الأوردرات بتاخد من الدفعة اللي هتنتهي الأول.",
    receive: "استلام دفعة",
    alertSettings: "تنبيه الصلاحية",
    filterLabel: "اعرض الدفعات",
    status_active: "شغالة",
    status_expiring: "قربت تنتهي",
    status_expired: "منتهية",
    status_empty: "خلصت",
    colProduct: "المنتج",
    colLot: "الدفعة",
    colExpiry: "الصلاحية",
    colRemaining: "الباقي / المستلم",
    colLocation: "المخزن",
    colActions: "إجراءات",
    remainingOf: "{remaining} من {received}",
    noExpiry: "من غير تاريخ صلاحية",
    expiredBadge: "منتهية",
    expiresToday: "بتنتهي النهارده",
    expiresIn: "فاضل {days}",
    writtenOffBadge: "اتشطبت",
    purchaseOrder: "أمر الشراء {number}",
    purchaseOrderPlain: "أمر الشراء",
    unknownProduct: "منتج محذوف",
    defaultLocationShort: "{name} (الأساسي)",
    deletedLocation: "مخزن محذوف",
    edit: "تعديل",
    writeOff: "إعدام / شطب",
    firstRows: "ظاهر أول {n} دفعة.",
    viewOnly: "صلاحياتك تشوف الدفعات بس من غير تعديل.",
    empty_active_title: "لسه مفيش دفعات",
    empty_active_hint: "استلم دفعة بكودها وتاريخ صلاحيتها، والأوردرات هتاخد من الدفعة اللي هتنتهي الأول.",
    empty_expiring_title: "مفيش دفعات قربت تنتهي",
    empty_expiring_hint: "الدفعة بتتحسب إنها قربت تنتهي قبل تاريخها بـ {days}.",
    empty_expired_title: "مفيش دفعات منتهية",
    empty_expired_hint: "الدفعات اللي تاريخها عدّى ولسه فيها قطع بتظهر هنا عشان تشطبها.",
    empty_empty_title: "مفيش دفعات خلصت",
    empty_empty_hint: "الدفعات اللي قطعها اتباعت كلها أو اتشطبت بتظهر هنا.",
    receiveTitle: "استلام دفعة",
    receiveDescription: "سجّل دفعة بكودها وتاريخ صلاحيتها.",
    product: "المنتج",
    productError: "اختار المنتج.",
    lotCode: "كود الدفعة",
    lotCodePlaceholder: "A-10",
    lotCodeError: "اكتب كود الدفعة.",
    expiresOn: "تاريخ الصلاحية (اختياري)",
    expiresHint: "سيبه فاضي لو الدفعة ملهاش تاريخ.",
    expiresPast: "التاريخ ده عدّى: الدفعة هتظهر كمنتهية.",
    quantity: "الكمية",
    quantityError: "اكتب رقم صحيح أكبر من صفر.",
    location: "المخزن",
    addToStock: "ضيفها للمخزون",
    addToStockOn: "القطع دي هتتضاف لمخزون المنتج.",
    addToStockOff: "مفيش حاجة هتتضاف: الدفعة بتتسجّل على قطع موجودة عندك.",
    purchaseOrderField: "أمر الشراء (اختياري)",
    noPurchaseOrder: "من غير أمر شراء",
    purchaseOrderOption: "{number} — {supplier}",
    countedTwice: "القطع اللي استلمتها من أمر الشراء ده دخلت مخزونك خلاص. اقفل «ضيفها للمخزون» عشان متتحسبش مرتين.",
    note: "ملاحظة (اختياري)",
    receiveSubmit: "استلم الدفعة",
    saving: "بنحفظ…",
    received: "الدفعة اتسجّلت واتضافت للمخزون.",
    labelled: "الدفعة اتسجّلت.",
    onlyUnlabelled: "فيه بس {n} قطعة من غير دفعة",
    cancel: "إلغاء",
    editTitle: "تعديل الدفعة",
    editDescription: "صحّح الكود أو تاريخ الصلاحية أو الملاحظة. الكمية بتتغير مع الأوردرات والشطب.",
    save: "حفظ",
    saved: "الدفعة اتحفظت.",
    writeOffTitle: "إعدام / شطب",
    writeOffConfirm: "الكمية دي هتخرج من المخزون",
    remaining: "الباقي في الدفعة",
    writeOffQuantity: "الكمية اللي هتتشطب",
    writeOffQuantityError: "اكتب رقم من ١ لـ {n}.",
    reason: "السبب (اختياري)",
    reasonPlaceholder: "منتهية الصلاحية",
    writeOffSubmit: "اشطب",
    writingOff: "بنشطب…",
    writtenOff: "اتشطب {pieces} وخرج من المخزون.",
    lotNotEnough: "الدفعة فاضل فيها {n} قطعة بس.",
    lotChanged: "الدفعة مبقاش فيها الكمية دي. القايمة بتعرضها زي ما هي دلوقتي.",
    stockShort: "المخزون نفسه فيه أقل من كده. اشطب كمية أقل، أو صحّح المخزون الأول.",
    alertTitle: "تنبيه الصلاحية",
    alertDescription: "هيوصلك إشعار وإيميل لما دفعة تقرّب تنتهي.",
    alertSentence: "نبّهني قبل الانتهاء بـ {n} يوم",
    alertRange: "من ١ لـ ٣٦٥",
    alertError: "اكتب رقم صحيح من ١ لـ ٣٦٥.",
    alertSaved: "تنبيه الصلاحية اتحفظ.",
    cardTitle: "الدفعات والصلاحية",
    cardDescription: "دفعات المنتج ده اللي لسه فيها قطع، واللي هتطلع الأول فوق.",
    cardRemaining: "فاضل {pieces}",
    singleVariant: "نوع واحد",
    manageLots: "إدارة الدفعات",
  },
} satisfies Messages;

export type LotStrings = Record<keyof (typeof LOT_STRINGS)["en"], string>;
type Key = keyof (typeof LOT_STRINGS)["en"];

export const LOT_STATUS_KEY: Record<StockLotStatus, Key> = {
  active: "status_active",
  expiring: "status_expiring",
  expired: "status_expired",
  empty: "status_empty",
};

export const LOT_EMPTY_TITLE: Record<StockLotStatus, Key> = {
  active: "empty_active_title",
  expiring: "empty_expiring_title",
  expired: "empty_expired_title",
  empty: "empty_empty_title",
};

export const LOT_EMPTY_HINT: Record<StockLotStatus, Key> = {
  active: "empty_active_hint",
  expiring: "empty_expiring_hint",
  expired: "empty_expired_hint",
  empty: "empty_empty_hint",
};
