import type { Locale, Messages } from "@/i18n/LocaleContext";
import type { Category, PageLang, SectionKey, Tone } from "./types";

export const STRINGS = {
  en: {
    title: "Landing page generator",
    description: "Turn a product brief into a cash-on-delivery landing page saved to your website.",
    honestyTitle: "Smart template draft — not AI",
    honestyBody:
      "The copy is assembled from a hand-written template library using only what you enter here. AI writing will plug in later. Review every line before publishing.",
    stepProduct: "1. Product",
    stepBrief: "2. Brief",
    stepStyle: "3. Style",
    stepTarget: "4. Where to save",
    pickProduct: "Product from your catalog",
    manualEntry: "Enter manually (no catalog product)",
    productHint: "Picking a product fills in name, price, images and description, and links the order form to it.",
    noProducts: "No products in your catalog yet — you can still enter details manually.",
    manualWarning:
      "Without a catalog product the page can't take an order: order buttons will link to your store home. Pick a product to enable the real COD order form.",
    productName: "Product name",
    price: "Price",
    compareAt: "Compare-at price (optional)",
    compareAtHint: "Only if you really sold it at this price before.",
    shortDescription: "Short description (optional)",
    images: "Images",
    uploadImage: "Upload image",
    uploading: "Uploading…",
    removeImage: "Remove image",
    benefits: "Key benefits (3–6)",
    benefitPlaceholder: "e.g. Cuts prep time in half",
    addBenefit: "Add benefit",
    remove: "Remove",
    audience: "Who it's for",
    audiencePlaceholder: "e.g. busy mothers",
    problem: "Main problem it solves",
    problemPlaceholder: "e.g. messy kitchen counters",
    box: "What's in the box (optional)",
    boxHint: "One item per line.",
    delivery: "Delivery promise",
    deliveryPlaceholder: "e.g. 2–4 days",
    returns: "Return policy",
    returnsPlaceholder: "e.g. 14 days",
    guarantee: "Guarantee (optional)",
    guaranteeHint: "Your own words, shown as written. Only promise what you honour.",
    quotes: "Real customer quotes (optional, up to 3)",
    quotesHint: "Only paste quotes customers actually sent you. The social proof section only appears if you add one.",
    quote: "Quote",
    author: "Customer name",
    addQuote: "Add quote",
    faqs: "Extra FAQ (optional)",
    question: "Question",
    answer: "Answer",
    addFaq: "Add question",
    pageLang: "Page language",
    langHint: "Store navigation and the product card use your store's language setting.",
    tone: "Tone",
    category: "Category",
    accent: "Accent colour",
    accentHint: "Defaults to your brand colour. The live storefront currently uses the brand colour from Settings; this accent is saved with the page and used in the preview.",
    sectionsLabel: "Sections",
    needsQuotes: "add a quote",
    needsBox: "add box contents",
    stickyHint: "The storefront has no sticky element yet, so this is added as a closing order button.",
    countdown: "Countdown to a real end date",
    countdownDesc: "Off by default. Only enable for an offer that genuinely ends.",
    countdownEnd: "Offer ends at",
    countdownWarn:
      "The storefront timer counts down from when each visitor opens the page, so the real end date is written into its label and the hours are recalculated each time you save. Turn it off once the offer ends.",
    website: "Website",
    noWebsites: "You don't have a website yet.",
    createWebsite: "Create website",
    creatingWebsite: "Creating…",
    websiteCreated: "Website created.",
    pageTitle: "Page title",
    slug: "Page URL",
    slugHint: "Latin letters, numbers and dashes, e.g. summer-blender.",
    existingPage: "A page already exists at this URL — saving will replace its draft (the live version changes only when you publish).",
    newPage: "A new page will be created at this URL.",
    preview: "Live preview",
    mobile: "Mobile",
    desktop: "Desktop",
    regenerate: "Regenerate copy",
    shuffle: "Shuffle this section",
    editHint: "Click any heading, paragraph or button text to edit it. Shuffling a section replaces your edits in it.",
    orderNow: "Order now",
    productNote: "Real price, image and order button come from your catalog on the storefront.",
    noProduct: "Pick a catalog product to show the order card here.",
    countdownNote: "Preview — the storefront timer ticks live.",
    saveDraft: "Save as draft page",
    savePublish: "Save & publish",
    saving: "Saving…",
    publishing: "Publishing…",
    openEditor: "Open in editor",
    viewLive: "View live",
    publishTitle: "Publish the whole website?",
    publishBody:
      "Publishing snapshots the saved drafts of every page on this website, not just this one. Any unpublished changes on other pages will go live too.",
    publishConfirm: "Save & publish",
    fixErrors: "Fix the highlighted fields before saving.",
    savedNew: "Draft page created.",
    savedUpdate: "Page draft updated.",
    publishedToast: "Website published.",
    savedButPublishFailed: "The draft was saved, but publishing failed:",
    errSubscription: "Your subscription isn't active, so this action is blocked. Renew your plan in Billing and try again.",
    errPermission: "Your role doesn't allow this. Ask the store owner for website edit/publish permission.",
    errPathTaken: "Another page already uses this URL.",
    errInvalid: "The server rejected the page:",
    required: "Required.",
    errPrice: "Enter a price greater than 0.",
    errCompare: "Must be higher than the price.",
    errBenefits: "Add at least 3 benefits.",
    errSlug: "Use lowercase Latin letters, numbers and dashes.",
    errSlugReserved: "This URL is reserved by the store. Pick another.",
    errCountdown: "Pick a future date within one year.",
    errProductPublish: "Pick a catalog product before publishing so the page can take orders.",
    errWebsite: "Choose or create a website.",
  },
  ar: {
    title: "مولّد صفحات الهبوط",
    description: "حوّل وصف منتجك إلى صفحة هبوط بالدفع عند الاستلام تُحفظ في موقعك.",
    honestyTitle: "مسودة قالب ذكي — ليست ذكاءً اصطناعيًا",
    honestyBody:
      "النصوص مركّبة من مكتبة قوالب مكتوبة يدويًا باستخدام ما تُدخله هنا فقط. الكتابة بالذكاء الاصطناعي ستُضاف لاحقًا. راجع كل سطر قبل النشر.",
    stepProduct: "١. المنتج",
    stepBrief: "٢. تفاصيل المنتج",
    stepStyle: "٣. الأسلوب",
    stepTarget: "٤. مكان الحفظ",
    pickProduct: "منتج من متجرك",
    manualEntry: "إدخال يدوي (بدون منتج من المتجر)",
    productHint: "اختيار منتج يملأ الاسم والسعر والصور والوصف، ويربط نموذج الطلب به.",
    noProducts: "لا توجد منتجات في متجرك بعد — يمكنك إدخال التفاصيل يدويًا.",
    manualWarning:
      "بدون منتج من المتجر لن تستقبل الصفحة طلبات: أزرار الطلب ستوجّه إلى الصفحة الرئيسية للمتجر. اختر منتجًا لتفعيل نموذج الطلب بالدفع عند الاستلام.",
    productName: "اسم المنتج",
    price: "السعر",
    compareAt: "السعر قبل الخصم (اختياري)",
    compareAtHint: "فقط إذا كنت تبيعه بهذا السعر فعلًا من قبل.",
    shortDescription: "وصف مختصر (اختياري)",
    images: "الصور",
    uploadImage: "رفع صورة",
    uploading: "جارٍ الرفع…",
    removeImage: "إزالة الصورة",
    benefits: "أهم المميزات (٣–٦)",
    benefitPlaceholder: "مثال: يختصر وقت التحضير للنصف",
    addBenefit: "إضافة ميزة",
    remove: "إزالة",
    audience: "لمن هذا المنتج",
    audiencePlaceholder: "مثال: الأمهات المشغولات",
    problem: "المشكلة الأساسية التي يحلها",
    problemPlaceholder: "مثال: فوضى أسطح المطبخ",
    box: "محتويات العلبة (اختياري)",
    boxHint: "عنصر في كل سطر.",
    delivery: "مدة التوصيل",
    deliveryPlaceholder: "مثال: ٢–٤ أيام",
    returns: "سياسة الإرجاع",
    returnsPlaceholder: "مثال: ١٤ يومًا",
    guarantee: "الضمان (اختياري)",
    guaranteeHint: "بكلماتك أنت، ويُعرض كما كتبته. لا تَعِد إلا بما تلتزم به.",
    quotes: "آراء عملاء حقيقية (اختياري، حتى ٣)",
    quotesHint: "الصق فقط آراء أرسلها لك عملاء فعلًا. قسم آراء العملاء لا يظهر إلا إذا أضفت رأيًا.",
    quote: "نص الرأي",
    author: "اسم العميل",
    addQuote: "إضافة رأي",
    faqs: "أسئلة شائعة إضافية (اختياري)",
    question: "السؤال",
    answer: "الإجابة",
    addFaq: "إضافة سؤال",
    pageLang: "لغة الصفحة",
    langHint: "قائمة المتجر وبطاقة المنتج تستخدم لغة المتجر من الإعدادات.",
    tone: "النبرة",
    category: "الفئة",
    accent: "لون التمييز",
    accentHint: "افتراضيًا لون علامتك التجارية. المتجر المباشر يستخدم حاليًا لون العلامة من الإعدادات؛ هذا اللون يُحفظ مع الصفحة ويُستخدم في المعاينة.",
    sectionsLabel: "الأقسام",
    needsQuotes: "أضف رأيًا",
    needsBox: "أضف محتويات العلبة",
    stickyHint: "لا يوجد عنصر زر ثابت في المتجر بعد، لذا يُضاف كزر طلب ختامي.",
    countdown: "عدّاد تنازلي لتاريخ انتهاء حقيقي",
    countdownDesc: "متوقف افتراضيًا. فعّله فقط لعرض ينتهي فعلًا.",
    countdownEnd: "ينتهي العرض في",
    countdownWarn:
      "عدّاد المتجر يبدأ من لحظة فتح كل زائر للصفحة، لذلك نكتب تاريخ الانتهاء الحقيقي في نصه ونعيد حساب الساعات عند كل حفظ. أوقفه بعد انتهاء العرض.",
    website: "الموقع",
    noWebsites: "ليس لديك موقع بعد.",
    createWebsite: "إنشاء موقع",
    creatingWebsite: "جارٍ الإنشاء…",
    websiteCreated: "تم إنشاء الموقع.",
    pageTitle: "عنوان الصفحة",
    slug: "رابط الصفحة",
    slugHint: "أحرف لاتينية وأرقام وشرطات، مثل summer-blender.",
    existingPage: "توجد صفحة بهذا الرابط — الحفظ سيستبدل مسودتها (النسخة المنشورة لا تتغير إلا عند النشر).",
    newPage: "سيتم إنشاء صفحة جديدة بهذا الرابط.",
    preview: "معاينة مباشرة",
    mobile: "موبايل",
    desktop: "كمبيوتر",
    regenerate: "إعادة توليد النصوص",
    shuffle: "تبديل نص هذا القسم",
    editHint: "اضغط على أي عنوان أو فقرة أو نص زر لتعديله. تبديل القسم يلغي تعديلاتك فيه.",
    orderNow: "اطلب الآن",
    productNote: "السعر والصورة وزر الطلب الحقيقية تأتي من متجرك عند العرض.",
    noProduct: "اختر منتجًا من المتجر لعرض بطاقة الطلب هنا.",
    countdownNote: "معاينة — العدّاد يعمل مباشرة في المتجر.",
    saveDraft: "حفظ كمسودة",
    savePublish: "حفظ ونشر",
    saving: "جارٍ الحفظ…",
    publishing: "جارٍ النشر…",
    openEditor: "فتح في المحرّر",
    viewLive: "عرض الصفحة المنشورة",
    publishTitle: "نشر الموقع بالكامل؟",
    publishBody:
      "النشر يأخذ لقطة من المسودات المحفوظة لكل صفحات هذا الموقع، وليس هذه الصفحة فقط. أي تعديلات غير منشورة في صفحات أخرى ستُنشر أيضًا.",
    publishConfirm: "حفظ ونشر",
    fixErrors: "صحّح الحقول المحددة قبل الحفظ.",
    savedNew: "تم إنشاء مسودة الصفحة.",
    savedUpdate: "تم تحديث مسودة الصفحة.",
    publishedToast: "تم نشر الموقع.",
    savedButPublishFailed: "تم حفظ المسودة، لكن فشل النشر:",
    errSubscription: "اشتراكك غير نشط، لذا هذا الإجراء محظور. جدّد باقتك من صفحة الفواتير ثم حاول مرة أخرى.",
    errPermission: "دورك لا يسمح بهذا. اطلب من مالك المتجر صلاحية تعديل/نشر الموقع.",
    errPathTaken: "هناك صفحة أخرى تستخدم هذا الرابط.",
    errInvalid: "رفض الخادم الصفحة:",
    required: "مطلوب.",
    errPrice: "أدخل سعرًا أكبر من صفر.",
    errCompare: "يجب أن يكون أعلى من السعر.",
    errBenefits: "أضف ٣ مميزات على الأقل.",
    errSlug: "استخدم أحرفًا لاتينية صغيرة وأرقامًا وشرطات.",
    errSlugReserved: "هذا الرابط محجوز للمتجر. اختر رابطًا آخر.",
    errCountdown: "اختر تاريخًا مستقبليًا خلال سنة.",
    errProductPublish: "اختر منتجًا من المتجر قبل النشر لكي تستقبل الصفحة الطلبات.",
    errWebsite: "اختر موقعًا أو أنشئ واحدًا.",
  },
} satisfies Messages;

export const SECTION_LABELS: Record<Locale, Record<SectionKey, string>> = {
  en: {
    hero: "Hero",
    benefits: "Benefits",
    how: "How it works",
    box: "What's in the box",
    proof: "Social proof",
    guarantee: "Guarantee & trust",
    faq: "FAQ",
    cta: "Order form CTA",
    sticky: "Closing order button",
  },
  ar: {
    hero: "الواجهة",
    benefits: "المميزات",
    how: "طريقة الطلب",
    box: "محتويات العلبة",
    proof: "آراء العملاء",
    guarantee: "الضمان والثقة",
    faq: "الأسئلة الشائعة",
    cta: "نموذج الطلب",
    sticky: "زر طلب ختامي",
  },
};

export const TONE_LABELS: Record<Locale, Record<Tone, string>> = {
  en: { confident: "Confident", friendly: "Friendly", premium: "Premium", urgent: "Urgent (honest)" },
  ar: { confident: "واثق", friendly: "ودود", premium: "راقٍ", urgent: "محفّز (بصدق)" },
};

export const CATEGORY_LABELS: Record<Locale, Record<Category, string>> = {
  en: { fashion: "Fashion", electronics: "Electronics", home: "Home & kitchen", beauty: "Beauty", food: "Food", kids: "Kids", other: "Other" },
  ar: { fashion: "أزياء", electronics: "إلكترونيات", home: "المنزل والمطبخ", beauty: "تجميل", food: "أغذية", kids: "أطفال", other: "أخرى" },
};

export const LANG_LABELS: Record<Locale, Record<PageLang, string>> = {
  en: { "ar-eg": "Arabic (Egyptian-friendly)", "ar-gulf": "Arabic (Gulf)", en: "English" },
  ar: { "ar-eg": "عربي (مناسب لمصر)", "ar-gulf": "عربي (خليجي)", en: "إنجليزي" },
};
