export const STRINGS = {
  en: {
    pageTitle: "Set up your store",
    stepOf: "Step {n} of {total}",
    back: "Back",
    skip: "Skip for now",
    continue: "Continue",
    saving: "Saving…",
    exit: "Exit setup",
    skippedTag: "Skipped",

    // stepper labels
    basicsLabel: "Store basics",
    lookLabel: "Look",
    productLabel: "First product",
    deliveryLabel: "Delivery",
    launchLabel: "Launch",

    // step 1
    basicsTitle: "Tell us about your store",
    basicsSubtitle: "You can change all of this later in settings.",
    storeName: "Store name",
    storeNamePlaceholder: "e.g. Nour Boutique",
    nameTooShort: "Store name must be at least 2 characters.",
    slug: "Store address",
    slugHint: "Lowercase English letters, numbers and hyphens.",
    slugChecking: "Checking availability…",
    slugAvailable: "Available",
    slugCurrent: "This is your store's current address",
    slugAuto: "An address will be generated automatically — you can set one in English letters.",
    reason_invalid_format: "Use lowercase letters, numbers and hyphens only, and don't start or end with a hyphen.",
    reason_too_short: "Must be at least 3 characters.",
    reason_too_long: "Must be at most 63 characters.",
    reason_reserved: "That address is reserved.",
    reason_taken: "That address is already taken.",
    currency: "Currency",
    currencyNote: "Used for your first product's price.",
    language: "Store language",
    langAr: "العربية",
    langEn: "English",
    whatSell: "What do you sell?",
    cat_fashion: "Fashion",
    cat_electronics: "Electronics",
    cat_home: "Home & kitchen",
    cat_beauty: "Beauty",
    cat_food: "Food",
    cat_other: "Other",
    basicsError: "We couldn't save your store. Please try again.",

    // step 2
    lookTitle: "Choose a look",
    lookSubtitle: "Pick a ready-made design for your storefront. You can edit every page later.",
    blankName: "Start blank",
    blankDesc: "A simple home page with your store name and products.",
    blankTagline: "Welcome to our store",
    templatesError: "We couldn't load templates.",
    retry: "Try again",
    noTemplates: "No templates are available right now. You can start blank.",
    pickOne: "Choose a design or skip this step.",
    lookCreated: "Your website was created from “{name}”.",
    lookError: "We couldn't create your website.",
    tpl_ecommerce: "Store",
    tpl_general: "General",
    tpl_other: "Template",
    selected: "Selected",
    previewCta: "Shop now",

    // step 3
    productTitle: "Add your first product",
    productSubtitle: "Start with one product — you can add variants and more photos later.",
    productName: "Product name",
    productNamePlaceholder: "e.g. Cotton summer dress",
    price: "Price",
    compareAt: "Compare-at price",
    compareHint: "Optional — the original price shown crossed out.",
    compareInvalid: "Must be higher than the price.",
    priceInvalid: "Enter a valid price.",
    stock: "Stock quantity",
    stockInvalid: "Enter a whole number of 0 or more.",
    description: "Short description",
    image: "Product photo",
    imageHint: "PNG, JPEG, GIF or WEBP, up to 5 MB. Optional.",
    chooseImage: "Choose photo",
    replaceImage: "Replace",
    removeImage: "Remove",
    uploading: "Uploading…",
    uploadError: "We couldn't upload that photo.",
    requiredField: "This field is required.",
    productSaved: "“{name}” was added to your catalog and is active.",
    addAnother: "Add another product",
    productError: "We couldn't save the product.",

    // step 4
    deliveryTitle: "Delivery & payment",
    deliverySubtitle: "Where do you deliver, and how much do customers pay for delivery?",
    governorates: "Governorates you deliver to",
    selectAll: "Select all",
    selectedCount: "{n} of {total} selected",
    pickGovernorate: "Select at least one governorate.",
    fee: "Flat delivery fee",
    feeHint: "Charged once per order in the selected governorates. Enter 0 for free delivery.",
    feeInvalid: "Enter a valid amount.",
    cod: "Cash on delivery",
    codNote:
      "Cash on delivery is the default payment method at checkout, so there's nothing to save here. Online payment options are in Payments.",
    deliverySaved: "Delivery zone saved.",
    deliveryError: "We couldn't save delivery settings.",
    zoneName: "Egypt — onboarding",
    rateName: "Standard delivery",

    // step 5
    launchTitle: "Ready to launch",
    launchSubtitle: "Here's what you've set up. Publish your store to make it visible to customers.",
    sumStore: "Store",
    sumLook: "Look",
    sumProduct: "First product",
    sumDelivery: "Delivery",
    sumPayment: "Payment",
    blankLook: "Blank website",
    notSet: "Not set up",
    deliverySummary: "{n} governorates · {fee}",
    allEgypt: "All of Egypt · {fee}",
    codOn: "Cash on delivery",
    edit: "Edit",
    publish: "Publish my store",
    publishing: "Publishing…",
    published: "Your store is live.",
    publishError: "Your store couldn't be published yet:",
    needWebsite: "Choose a look first to publish your store.",
    chooseLook: "Choose a look",
    storeUrl: "Storefront address",
    copy: "Copy",
    copied: "Copied",
    open: "Open",
    goDashboard: "Go to dashboard",
  },
  ar: {
    pageTitle: "جهّز متجرك",
    stepOf: "الخطوة {n} من {total}",
    back: "رجوع",
    skip: "تخطَّ الآن",
    continue: "متابعة",
    saving: "جارٍ الحفظ…",
    exit: "الخروج من الإعداد",
    skippedTag: "تم التخطي",

    basicsLabel: "أساسيات المتجر",
    lookLabel: "الشكل",
    productLabel: "أول منتج",
    deliveryLabel: "التوصيل",
    launchLabel: "الإطلاق",

    basicsTitle: "عرّفنا على متجرك",
    basicsSubtitle: "يمكنك تغيير كل ذلك لاحقًا من الإعدادات.",
    storeName: "اسم المتجر",
    storeNamePlaceholder: "مثال: بوتيك نور",
    nameTooShort: "يجب ألا يقل اسم المتجر عن حرفين.",
    slug: "عنوان المتجر",
    slugHint: "حروف إنجليزية صغيرة وأرقام وشرطات.",
    slugChecking: "جارٍ التحقق من التوفر…",
    slugAvailable: "متاح",
    slugCurrent: "هذا هو العنوان الحالي لمتجرك",
    slugAuto: "سيُنشأ عنوان تلقائيًا — ويمكنك كتابة عنوان بحروف إنجليزية.",
    reason_invalid_format: "استخدم حروفًا صغيرة وأرقامًا وشرطات فقط، دون شرطة في البداية أو النهاية.",
    reason_too_short: "يجب ألا يقل عن 3 أحرف.",
    reason_too_long: "يجب ألا يزيد عن 63 حرفًا.",
    reason_reserved: "هذا العنوان محجوز.",
    reason_taken: "هذا العنوان مستخدم بالفعل.",
    currency: "العملة",
    currencyNote: "تُستخدم لسعر أول منتج.",
    language: "لغة المتجر",
    langAr: "العربية",
    langEn: "English",
    whatSell: "ماذا تبيع؟",
    cat_fashion: "أزياء",
    cat_electronics: "إلكترونيات",
    cat_home: "المنزل والمطبخ",
    cat_beauty: "تجميل",
    cat_food: "أطعمة",
    cat_other: "أخرى",
    basicsError: "تعذّر حفظ متجرك. حاول مرة أخرى.",

    lookTitle: "اختر شكل متجرك",
    lookSubtitle: "اختر تصميمًا جاهزًا لواجهة متجرك. يمكنك تعديل كل الصفحات لاحقًا.",
    blankName: "ابدأ من الصفر",
    blankDesc: "صفحة رئيسية بسيطة باسم متجرك ومنتجاتك.",
    blankTagline: "أهلًا بك في متجرنا",
    templatesError: "تعذّر تحميل القوالب.",
    retry: "حاول مرة أخرى",
    noTemplates: "لا توجد قوالب متاحة حاليًا. يمكنك البدء من الصفر.",
    pickOne: "اختر تصميمًا أو تخطَّ هذه الخطوة.",
    lookCreated: "تم إنشاء موقعك من «{name}».",
    lookError: "تعذّر إنشاء موقعك.",
    tpl_ecommerce: "متجر",
    tpl_general: "عام",
    tpl_other: "قالب",
    selected: "مُختار",
    previewCta: "تسوّق الآن",

    productTitle: "أضف أول منتج",
    productSubtitle: "ابدأ بمنتج واحد — يمكنك إضافة خيارات وصور أخرى لاحقًا.",
    productName: "اسم المنتج",
    productNamePlaceholder: "مثال: فستان صيفي قطن",
    price: "السعر",
    compareAt: "السعر قبل الخصم",
    compareHint: "اختياري — السعر الأصلي يظهر مشطوبًا.",
    compareInvalid: "يجب أن يكون أعلى من السعر.",
    priceInvalid: "أدخل سعرًا صحيحًا.",
    stock: "الكمية في المخزون",
    stockInvalid: "أدخل عددًا صحيحًا يساوي 0 أو أكثر.",
    description: "وصف مختصر",
    image: "صورة المنتج",
    imageHint: "PNG أو JPEG أو GIF أو WEBP حتى 5 ميجابايت. اختياري.",
    chooseImage: "اختر صورة",
    replaceImage: "استبدال",
    removeImage: "إزالة",
    uploading: "جارٍ الرفع…",
    uploadError: "تعذّر رفع الصورة.",
    requiredField: "هذا الحقل مطلوب.",
    productSaved: "تمت إضافة «{name}» إلى منتجاتك وهو نشط.",
    addAnother: "أضف منتجًا آخر",
    productError: "تعذّر حفظ المنتج.",

    deliveryTitle: "التوصيل والدفع",
    deliverySubtitle: "إلى أين توصّل، وكم يدفع العميل مقابل التوصيل؟",
    governorates: "المحافظات التي توصّل إليها",
    selectAll: "تحديد الكل",
    selectedCount: "تم تحديد {n} من {total}",
    pickGovernorate: "حدّد محافظة واحدة على الأقل.",
    fee: "رسوم توصيل ثابتة",
    feeHint: "تُحتسب مرة واحدة لكل طلب في المحافظات المحددة. أدخل 0 للتوصيل المجاني.",
    feeInvalid: "أدخل مبلغًا صحيحًا.",
    cod: "الدفع عند الاستلام",
    codNote:
      "الدفع عند الاستلام هو طريقة الدفع الافتراضية عند إتمام الطلب، لذلك لا يوجد ما يُحفظ هنا. خيارات الدفع الإلكتروني في صفحة المدفوعات.",
    deliverySaved: "تم حفظ منطقة التوصيل.",
    deliveryError: "تعذّر حفظ إعدادات التوصيل.",
    zoneName: "مصر — الإعداد الأولي",
    rateName: "توصيل قياسي",

    launchTitle: "جاهز للإطلاق",
    launchSubtitle: "هذا ما جهّزته. انشر متجرك ليظهر لعملائك.",
    sumStore: "المتجر",
    sumLook: "الشكل",
    sumProduct: "أول منتج",
    sumDelivery: "التوصيل",
    sumPayment: "الدفع",
    blankLook: "موقع فارغ",
    notSet: "لم يُجهَّز",
    deliverySummary: "{n} محافظة · {fee}",
    allEgypt: "كل محافظات مصر · {fee}",
    codOn: "الدفع عند الاستلام",
    edit: "تعديل",
    publish: "انشر متجري",
    publishing: "جارٍ النشر…",
    published: "متجرك الآن متاح للعملاء.",
    publishError: "تعذّر نشر متجرك بعد:",
    needWebsite: "اختر شكلًا لمتجرك أولًا حتى تتمكن من النشر.",
    chooseLook: "اختر الشكل",
    storeUrl: "عنوان واجهة المتجر",
    copy: "نسخ",
    copied: "تم النسخ",
    open: "فتح",
    goDashboard: "الذهاب إلى لوحة التحكم",
  },
};

export type OnboardingStrings = (typeof STRINGS)["en"];
