import type { Messages } from "@/i18n/LocaleContext";

/**
 * Settings → Subscription: plans, the referral code, charges, transfer
 * proofs and the prepaid balance (handoff items 333–336). Money placeholders
 * ({amount}, {fee}, {min}…) take an already formatted amount with its currency.
 */
export const BILLING_STRINGS = {
  en: {
    tabsLabel: "Subscription sections",
    tabPlans: "Plans",
    tabBalance: "Balance",
    tabCharges: "Charges",
    tabProofs: "Transfer proofs",
    // plans
    cycleMonthly: "Monthly",
    cycleYearly: "Yearly (2 months free)",
    cycleLabel: "Billing cycle",
    perMonth: "a month",
    perYear: "a year",
    free: "Free",
    codeDiscount: "Code discount {amount}",
    currentPlan: "Your current plan",
    privatePlan: "Private plan",
    choosePlan: "Choose this plan",
    choosing: "Changing…",
    planChanged: "Your plan is changed",
    planUnchanged: "You're already on this plan and cycle.",
    supportNote: "To change plan while a paid subscription runs, contact support",
    openTicket: "Open a support ticket",
    startTrial: "Start a {days}-day free trial",
    trialStarted: "Your free trial has started",
    trialUsed: "You've already used your free trial",
    noTrialOnPlan: "This plan has no free trial",
    // referral code
    referralCode: "Referral code",
    codePlaceholder: "e.g. CAIRO10",
    tryCode: "Try the code",
    trying: "Checking…",
    useCode: "Use this code",
    using: "Applying…",
    codeApplied: "Referral code applied.",
    codePreviewed: "Prices below show {code}. It is not attached until you use it.",
    codeAttached: "Attached to your subscription",
    percentOff: "{value}% off each payment",
    fixedOff: "{amount} off each payment",
    noDiscount: "No discount — it records who referred you.",
    codeInactive: "This code is no longer active, so it gives no discount on new payments.",
    REFERRAL_CODE_INVALID: "That code isn't valid — check it and try again",
    SELF_REFERRAL: "You can't use your own referral code on your store",
    REFERRAL_CODE_ALREADY_SET: "This store already has a referral code.",
    RATE_LIMITED: "Too many tries — wait a minute and try again",
    PLAN_NOT_AVAILABLE: "This plan isn't available right now",
    OPEN_CHARGE_EXISTS: "There's an open charge on your current plan — settle it first",
    // pay per order
    ppoTitle: "Pay per order",
    ppoBody: "{fee} per order from your prepaid balance — no monthly fee",
    ppoChoose: "Switch to pay per order",
    ppoConfirmTitle: "Switch to pay per order?",
    ppoConfirm: "{fee} comes off your balance with every new order, and goes back if the order is cancelled or rejected before it ships",
    ppoChanged: "You're on pay per order now",
    ppoSupport: "Contact support to move to pay per order",
    WALLET_DISABLED: "Pay per order isn't available right now.",
    EMAIL_NOT_VERIFIED: "Confirm your email first, then try again.",
    // charges
    charges: "Charges",
    period: "Period",
    amount: "Amount",
    gross: "Plan price {amount}",
    discount: "Discount {amount}",
    paid: "Paid",
    status: "Status",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusFailed: "Failed",
    paidOn: "Paid on",
    noCharges: "No charges yet",
    previous: "Previous",
    next: "Next",
    pageOf: "Page {page} of {pages}",
    // pay dialog
    pay: "Pay",
    payTitle: "Pay your subscription",
    amountDue: "Amount due",
    discountLine: "Plan price {gross}, less {discount} with your code",
    methodLabel: "Payment method",
    payOnline: "Pay online",
    opening: "Opening the payment page…",
    transferVia: "Transfer {amount} via {method}",
    sendTo: "Send to",
    copy: "Copy",
    openPaymentLink: "Open the payment link",
    senderPhone: "The mobile number you sent from",
    senderPhoneHint: "An Egyptian number, e.g. 01012345678",
    screenshot: "Transfer screenshot",
    screenshotHint: "JPEG, PNG or WebP, up to 8 MB",
    chooseFile: "Choose a picture",
    changeFile: "Change the picture",
    sendProof: "Send the transfer proof",
    sending: "Sending…",
    proofSent: "We received your transfer proof — we'll check it and confirm",
    noWayToPay: "No way to pay is available right now — contact support",
    close: "Close",
    cancel: "Cancel",
    CHARGE_AMOUNT_CHANGED: "The amount changed to {amount} — check it and send again",
    INVALID_SENDER_PHONE: "Enter a valid Egyptian mobile number",
    NO_FILE: "Attach the transfer screenshot",
    UNSUPPORTED_MEDIA_TYPE: "The screenshot must be JPEG, PNG or WebP",
    FILE_TOO_LARGE: "The screenshot is larger than 8 MB",
    PROOF_IMAGE_DUPLICATE: "This screenshot was already sent — send the screenshot of this transfer",
    PROOF_ALREADY_OPEN: "A proof for this charge is already waiting for review",
    TOO_MANY_OPEN_PROOFS: "You have 3 proofs waiting for review — wait until we check them",
    PROOF_RATE_LIMITED: "Too many tries — try again later",
    PAYMENT_METHOD_NOT_AVAILABLE: "This payment method isn't available right now",
    MANUAL_PRICING:
      "Your subscription is free or discounted by Zimos — there's nothing to pay here. If the period has ended, contact support",
    NOTHING_TO_PAY: "Nothing is due right now.",
    CHARGE_NOT_PENDING: "This charge was settled in the meantime. Reload the page.",
    MANUAL_PAYMENT_CURRENCY_UNSUPPORTED: "Transfers are only for plans priced in Egyptian pounds.",
    payByTransferHint: "Pay one period of your plan by InstaPay or a mobile wallet and send us the transfer's screenshot.",
    // proofs
    proofs: "Transfer proofs",
    date: "Date",
    method: "Method",
    purpose: "For",
    purposeInvoice: "Subscription",
    purposeTopup: "Balance top-up",
    proofPending: "Under review",
    proofApproved: "Approved",
    proofRejected: "Rejected",
    rejectReason: "Reason: {note}",
    payAgain: "Pay again",
    topUpAgain: "Top up again",
    noProofs: "No transfer proofs",
    // balance
    balanceTitle: "Balance",
    yourBalance: "Your balance: {balance}",
    enoughFor: "Enough for about {orders} orders",
    thisMonth: "This month: {fees} for {orders} orders",
    toppedUp: "Topped up in total: {amount}",
    feePerOrder: "{fee} per order",
    readOnlyBalance: "Top-ups are switched off right now. Your balance is shown as it is.",
    topUp: "Top up",
    topUpTitle: "Top up your balance",
    amountSent: "Amount you sent",
    amountRange: "From {min} to {max}",
    sendTopup: "Send the top-up proof",
    topupSent: "We received your top-up proof — it's added to your balance once checked",
    TOPUP_AMOUNT_OUT_OF_RANGE: "The amount must be between {min} and {max}",
    TOO_MANY_OPEN_TOPUPS: "You have 3 proofs waiting for review — wait until we check them",
    noTransferMethod: "No transfer method is available right now — contact support",
    activity: "Balance activity",
    type: "Type",
    typeTopup: "Top-up",
    typeFee: "Order fee",
    typeReversal: "Fee returned",
    typeRecharge: "Order fee (again)",
    order: "Order",
    balanceAfter: "Balance after",
    noActivity: "No activity yet",
    // banner
    bannerLow: "Your balance is running low — enough for {orders} orders. Top up now",
    bannerOverdraft: "Your balance is below zero — the store stops after {orders} more orders",
    bannerExhausted: "Your store stopped taking orders because the balance ran out — top up to reopen it",
    // plan feature gate
    featureRequired: "Your plan doesn't include {feature} — upgrade your plan to use it",
    seePlans: "See plans",
  },
  ar: {
    tabsLabel: "أقسام الاشتراك",
    tabPlans: "الباقات",
    tabBalance: "الرصيد",
    tabCharges: "الفواتير",
    tabProofs: "إثباتات التحويل",
    cycleMonthly: "شهري",
    cycleYearly: "سنوي (شهرين مجانًا)",
    cycleLabel: "دورة الفوترة",
    perMonth: "في الشهر",
    perYear: "في السنة",
    free: "مجانًا",
    codeDiscount: "خصم الكود {amount}",
    currentPlan: "باقتك الحالية",
    privatePlan: "باقة خاصة",
    choosePlan: "اختار الباقة دي",
    choosing: "بنغيّر…",
    planChanged: "اتغيرت باقتك",
    planUnchanged: "إنت على الباقة والدورة دي بالفعل.",
    supportNote: "لتغيير الباقة أثناء اشتراك مدفوع تواصل مع الدعم",
    openTicket: "افتح تذكرة دعم",
    startTrial: "ابدأ تجربة مجانية {days} يوم",
    trialStarted: "بدأت تجربتك المجانية",
    trialUsed: "استخدمت التجربة المجانية قبل كده",
    noTrialOnPlan: "الباقة دي مالهاش تجربة مجانية",
    referralCode: "كود الإحالة",
    codePlaceholder: "مثال: CAIRO10",
    tryCode: "جرّب الكود",
    trying: "بنراجع…",
    useCode: "استخدم الكود",
    using: "بنطبّق…",
    codeApplied: "تم تطبيق كود الإحالة.",
    codePreviewed: "الأسعار تحت بكود {code}. الكود مش هيتسجل على اشتراكك غير لما تستخدمه.",
    codeAttached: "متسجل على اشتراكك",
    percentOff: "خصم {value}% على كل دفعة",
    fixedOff: "خصم {amount} على كل دفعة",
    noDiscount: "بدون خصم — بيسجل بس مين اللي رشّحك.",
    codeInactive: "الكود ده مبقاش شغال، فمفيش خصم على الدفعات الجديدة.",
    REFERRAL_CODE_INVALID: "الكود ده مش صالح — راجعه وجرّب تاني",
    SELF_REFERRAL: "مينفعش تستخدم كود الإحالة بتاعك على متجرك",
    REFERRAL_CODE_ALREADY_SET: "المتجر ده عليه كود إحالة بالفعل.",
    RATE_LIMITED: "محاولات كتير — استنى دقيقة وجرّب تاني",
    PLAN_NOT_AVAILABLE: "الباقة دي مش متاحة دلوقتي",
    OPEN_CHARGE_EXISTS: "فيه فاتورة مفتوحة على باقتك الحالية — ادفعها الأول",
    ppoTitle: "ادفع على قد طلباتك",
    ppoBody: "{fee} على كل طلب، من رصيدك المدفوع مقدمًا — من غير اشتراك شهري",
    ppoChoose: "اختار الدفع بالطلب",
    ppoConfirmTitle: "تحوّل للدفع بالطلب؟",
    ppoConfirm: "هتتخصم {fee} من رصيدك مع كل طلب جديد، وتترجع لو الطلب اتلغى أو اترفض قبل الشحن",
    ppoChanged: "بقيت على الدفع بالطلب",
    ppoSupport: "تواصل مع الدعم عشان تغيّر لباقة الدفع بالطلب",
    WALLET_DISABLED: "الدفع بالطلب مش متاح دلوقتي.",
    EMAIL_NOT_VERIFIED: "أكّد بريدك الإلكتروني الأول وجرّب تاني.",
    charges: "الفواتير",
    period: "الفترة",
    amount: "المبلغ",
    gross: "سعر الباقة {amount}",
    discount: "خصم {amount}",
    paid: "المدفوع",
    status: "الحالة",
    statusPaid: "مدفوعة",
    statusPending: "في الانتظار",
    statusFailed: "فشلت",
    paidOn: "تاريخ الدفع",
    noCharges: "لا توجد فواتير بعد",
    previous: "السابق",
    next: "التالي",
    pageOf: "صفحة {page} من {pages}",
    pay: "ادفع",
    payTitle: "ادفع اشتراكك",
    amountDue: "المبلغ المطلوب",
    discountLine: "سعر الباقة {gross}، وخصم {discount} بكودك",
    methodLabel: "طريقة الدفع",
    payOnline: "ادفع أونلاين",
    opening: "بنفتح صفحة الدفع…",
    transferVia: "حوّل {amount} على {method}",
    sendTo: "رقم التحويل",
    copy: "نسخ",
    openPaymentLink: "افتح لينك الدفع",
    senderPhone: "رقم الموبايل اللي حوّلت منه",
    senderPhoneHint: "رقم مصري، مثال: 01012345678",
    screenshot: "صورة التحويل (سكرين شوت)",
    screenshotHint: "JPEG أو PNG أو WebP، لحد 8 ميجا",
    chooseFile: "اختار صورة",
    changeFile: "غيّر الصورة",
    sendProof: "أرسل إثبات التحويل",
    sending: "بنبعت…",
    proofSent: "وصلنا إثبات التحويل — هنراجعه ونأكدلك",
    noWayToPay: "مفيش طريقة دفع متاحة دلوقتي — تواصل مع الدعم",
    close: "إغلاق",
    cancel: "إلغاء",
    CHARGE_AMOUNT_CHANGED: "المبلغ اتغير لـ {amount} — راجعه وابعت تاني",
    INVALID_SENDER_PHONE: "اكتب رقم موبايل مصري صحيح",
    NO_FILE: "ارفع صورة التحويل",
    UNSUPPORTED_MEDIA_TYPE: "الصورة لازم تكون JPEG أو PNG أو WebP",
    FILE_TOO_LARGE: "الصورة أكبر من 8 ميجا",
    PROOF_IMAGE_DUPLICATE: "الصورة دي اتبعتت قبل كده — ابعت صورة التحويل ده",
    PROOF_ALREADY_OPEN: "فيه إثبات تحويل للفاتورة دي مستني المراجعة",
    TOO_MANY_OPEN_PROOFS: "عندك 3 إثباتات مستنية المراجعة — استنى لما نراجعها",
    PROOF_RATE_LIMITED: "محاولات كتير — جرّب بعد شوية",
    PAYMENT_METHOD_NOT_AVAILABLE: "طريقة الدفع دي مش متاحة دلوقتي",
    MANUAL_PRICING: "اشتراكك مجاني أو بخصم من زيموس — مفيش حاجة تدفعها هنا. لو الفترة خلصت تواصل مع الدعم",
    NOTHING_TO_PAY: "مفيش مبلغ مستحق حاليًا.",
    CHARGE_NOT_PENDING: "الفاتورة دي اتسوّت في الأثناء. حمّل الصفحة تاني.",
    MANUAL_PAYMENT_CURRENCY_UNSUPPORTED: "التحويل متاح للباقات المسعّرة بالجنيه المصري بس.",
    payByTransferHint: "ادفع فترة واحدة من باقتك بإنستا باي أو محفظة إلكترونية، وابعتلنا صورة التحويل.",
    proofs: "إثباتات التحويل",
    date: "التاريخ",
    method: "الطريقة",
    purpose: "الغرض",
    purposeInvoice: "الاشتراك",
    purposeTopup: "شحن رصيد",
    proofPending: "في المراجعة",
    proofApproved: "اتقبل",
    proofRejected: "اترفض",
    rejectReason: "سبب الرفض: {note}",
    payAgain: "ادفع تاني",
    topUpAgain: "اشحن تاني",
    noProofs: "مفيش إثباتات تحويل",
    balanceTitle: "الرصيد",
    yourBalance: "رصيدك: {balance}",
    enoughFor: "يكفي حوالي {orders} طلب",
    thisMonth: "رسوم الشهر ده: {fees} على {orders} طلب",
    toppedUp: "إجمالي الشحن: {amount}",
    feePerOrder: "{fee} على كل طلب",
    readOnlyBalance: "الشحن مقفول دلوقتي. رصيدك ظاهر زي ما هو.",
    topUp: "اشحن رصيدك",
    topUpTitle: "اشحن رصيدك",
    amountSent: "المبلغ اللي حوّلته",
    amountRange: "من {min} لحد {max}",
    sendTopup: "أرسل إثبات الشحن",
    topupSent: "وصلنا إثبات الشحن — هيتضاف للرصيد بعد المراجعة",
    TOPUP_AMOUNT_OUT_OF_RANGE: "المبلغ لازم يكون من {min} لحد {max}",
    TOO_MANY_OPEN_TOPUPS: "عندك 3 إثباتات مستنية المراجعة — استنى لما نراجعها",
    noTransferMethod: "مفيش طريقة تحويل متاحة دلوقتي — تواصل مع الدعم",
    activity: "حركة الرصيد",
    type: "النوع",
    typeTopup: "شحن",
    typeFee: "رسوم طلب",
    typeReversal: "استرجاع رسوم",
    typeRecharge: "رسوم طلب (تاني)",
    order: "الطلب",
    balanceAfter: "الرصيد بعدها",
    noActivity: "مفيش حركة لسه",
    bannerLow: "رصيدك قرب يخلص — يكفي {orders} طلب. اشحن دلوقتي",
    bannerOverdraft: "رصيدك بالسالب — المتجر هيقف بعد {orders} طلب",
    bannerExhausted: "المتجر وقف يستقبل طلبات لأن الرصيد خلص — اشحن عشان يرجع",
    featureRequired: "باقتك مش فيها {feature} — رقّي باقتك عشان تستخدمها",
    seePlans: "شوف الباقات",
  },
} satisfies Messages;

export type BillingText = Record<keyof (typeof BILLING_STRINGS)["en"], string>;

/** Where the Subscription section lives, and its inner tabs (`?billing=`). */
export const SUBSCRIPTION_PATH = "/settings?tab=billing";
export const BALANCE_PATH = "/settings?tab=billing&billing=balance";
export const TOPUP_PATH = "/settings?tab=billing&billing=balance&topup=1";
