import type { Messages } from "@/i18n/LocaleContext";

/** Account → Developers (frontend-handoff 265, 267): the list, the form, the secrets and the guide. */
export const PARTNER_APP_STRINGS = {
  en: {
    title: "Developers",
    description: "Build an app that ZIMOS stores install with one approval. Register it here and take its keys.",
    back: "Settings",
    newApp: "New app",
    listTitle: "My apps",
    emptyTitle: "No apps yet",
    emptyBody: "Register your first app to get its Client ID and Client Secret.",
    limitNote: "You have {max} apps, the most one account can hold. Delete one you no longer need to add another.",
    status_development: "In development",
    status_published: "Published",
    status_suspended: "Suspended",
    developmentNote: "In development: only stores you are a member of can install it, until ZIMOS publishes it.",
    suspendedNote: "ZIMOS suspended this app: no store can install it and it was removed from the stores that had it.",
    clientId: "Client ID",
    copyClientId: "Copy Client ID",
    copySecret: "Copy Client Secret",
    copied: "Copied",
    permissionsCount: "{count} permission(s)",
    callbacksCount: "{count} callback URL(s)",
    hasPage: "Has a page in the dashboard",
    edit: "Edit",
    installs: "Installs",
    rotate: "New secret",
    remove: "Delete",
    // Form
    createTitle: "New app",
    editTitle: "Edit {name}",
    name: "App name",
    nameHint: "What merchants see when they approve it.",
    nameError: "Write a name of 2 to 80 characters.",
    appDescription: "Description",
    appDescriptionHint: "One or two sentences on what the app does for the store.",
    iconUrl: "Icon URL",
    iconUrlHint: "A square image on an https address.",
    appUrl: "Page URL",
    appUrlHint: "Your app's page, opened inside the dashboard in a frame. Leave it empty if the app has no page.",
    redirectUris: "Callback URLs",
    redirectUrisHint: "Where the merchant goes back to after approving. Up to 10; https only (http://localhost while developing), without #.",
    redirectUriLabel: "Callback URL {n}",
    addRedirect: "Add another URL",
    removeRedirect: "Remove URL {n}",
    redirectRequired: "Add at least one callback URL.",
    redirectInvalid: "Use an https address (http only for localhost), without #.",
    redirectDuplicate: "This URL is already in the list.",
    uninstallUrl: "Uninstall URL",
    uninstallUrlHint: "We call it when a store removes your app.",
    uninstallGuide: "How the notice is signed",
    httpsOnly: "The address must start with https://",
    publicOnly: "Use a public https address: we can't call a private or local one.",
    permissions: "Permissions",
    permissionsHint: "What the app may ask a store for. Ask for no more than it needs: the merchant sees this list.",
    permissionsRequired: "Tick at least one permission.",
    resource_orders: "Orders",
    resource_products: "Products",
    resource_categories: "Categories",
    resource_customers: "Customers",
    resource_discounts: "Discounts",
    resource_shipping_areas: "Shipping",
    resource_webhooks: "Webhooks",
    resource_analytics: "Reports",
    resource_funnels: "Funnels",
    save: "Save",
    saving: "Saving…",
    create: "Create app",
    creating: "Creating…",
    cancel: "Cancel",
    saved: "{name} was saved.",
    // Secrets
    createdTitle: "Copy your app's keys",
    rotatedTitle: "Copy the new Client Secret",
    secretBody: "The Client Secret is shown once: it won't appear again. Keep it on your server only — if it's lost, make a new one.",
    clientSecret: "Client Secret",
    shownOnce: "Shown once",
    done: "Done",
    rotateTitle: "Make a new Client Secret for {name}?",
    rotateBody: "The current secret stops working at once. Update your app's server with the new one right after.",
    rotateConfirm: "Make a new secret",
    working: "Working…",
    // Installs
    installsTitle: "Stores that installed {name}",
    installsEmpty: "No store has installed this app yet.",
    installedOn: "Installed {date}",
    unnamedStore: "Store",
    close: "Close",
    // Delete
    deleteTitle: "Delete {name}?",
    deleteBody: "It is uninstalled from every store that has it and its keys stop working. This can't be undone.",
    deleteConfirm: "Delete app",
    deleted: "{name} was deleted.",
    // Guide
    guideTitle: "How it works",
    guideIntro: "The steps your app follows, from the approval to the token.",
    apiReference: "API reference",
    guide1: "Register your app above: you get a {clientId} and a {clientSecret}. A new app is in development — only stores you are a member of can install it, until ZIMOS publishes it.",
    guide2: "Send the merchant to the approval page. The callback must be exactly one you registered, and the permissions a part of your app's.",
    guide3: "They come back to your callback with a {code} (or {denied}). Check {state}. The code lasts 10 minutes and works once.",
    guide4: "From your server, swap the code for an {token}. Use it on the public API with the approved permissions, until the store removes your app or you leave it. A new approval replaces the token.",
    guide5: "Your page in the dashboard (the page URL) opens in a frame with these parameters. {hmac} is the {algo}, with your {clientSecret}, of the other parameters sorted by name and joined as {pairs}. Refuse a {timestamp} older than 5 minutes.",
    guide6: "To leave a store, revoke it yourself.",
    guide7: "The uninstall notice (the uninstall URL): when a store removes your app we send this, signed in the {header} header: the {algo} of the raw body with your {clientSecret}. Answer {ok}; we retry for up to a day. It is not sent when the merchant approves you again. {reason} is one of: {reasons}.",
    // Settings → My account card
    cardTitle: "Developer apps",
    cardBody: "Building an app for ZIMOS stores? Register it and get its keys.",
    cardOpen: "Open",
  },
  ar: {
    title: "المطوّرين",
    description: "اعمل تطبيق متاجر زيموس تثبّته بموافقة واحدة. سجّله هنا وخد مفاتيحه.",
    back: "الإعدادات",
    newApp: "تطبيق جديد",
    listTitle: "تطبيقاتي",
    emptyTitle: "لسه مفيش تطبيقات",
    emptyBody: "سجّل أول تطبيق ليك عشان تاخد الـ Client ID والـ Client Secret بتوعه.",
    limitNote: "عندك {max} تطبيق، وده أقصى عدد للحساب الواحد. احذف تطبيق مش محتاجه عشان تضيف واحد تاني.",
    status_development: "تحت التطوير",
    status_published: "منشور",
    status_suspended: "موقوف",
    developmentNote: "تحت التطوير: المتاجر اللي إنت عضو فيها بس هي اللي تقدر تثبّته، لحد ما زيموس ينشره.",
    suspendedNote: "زيموس وقّف التطبيق ده: مفيش متجر يقدر يثبّته، واتشال من المتاجر اللي كانت مثبّتاه.",
    clientId: "Client ID",
    copyClientId: "انسخ Client ID",
    copySecret: "انسخ Client Secret",
    copied: "اتنسخ",
    permissionsCount: "{count} صلاحية",
    callbacksCount: "{count} رابط رجوع",
    hasPage: "ليه صفحة جوه لوحة التحكم",
    edit: "تعديل",
    installs: "المتاجر المثبّتة",
    rotate: "Secret جديد",
    remove: "حذف",
    createTitle: "تطبيق جديد",
    editTitle: "تعديل {name}",
    name: "اسم التطبيق",
    nameHint: "اللي التاجر بيشوفه وهو بيوافق عليه.",
    nameError: "اكتب اسم من حرفين لـ ٨٠ حرف.",
    appDescription: "الوصف",
    appDescriptionHint: "جملة أو اتنين عن اللي التطبيق بيعمله للمتجر.",
    iconUrl: "رابط الأيقونة",
    iconUrlHint: "صورة مربّعة على رابط https.",
    appUrl: "رابط صفحة التطبيق",
    appUrlHint: "صفحة تطبيقك، بتتفتح جوه لوحة التحكم في فريم. سيبه فاضي لو التطبيق مالوش صفحة.",
    redirectUris: "روابط الرجوع (Callback)",
    redirectUrisHint: "المكان اللي التاجر بيرجعله بعد ما يوافق. لحد ١٠ روابط؛ https بس (و http://localhost وإنت بتجرّب)، ومن غير #.",
    redirectUriLabel: "رابط الرجوع {n}",
    addRedirect: "ضيف رابط كمان",
    removeRedirect: "شيل الرابط {n}",
    redirectRequired: "ضيف رابط رجوع واحد على الأقل.",
    redirectInvalid: "اكتب رابط https (و http لـ localhost بس)، ومن غير #.",
    redirectDuplicate: "الرابط ده موجود في القايمة.",
    uninstallUrl: "لينك إلغاء التثبيت",
    uninstallUrlHint: "بنبعتله لما متجر يشيل تطبيقك.",
    uninstallGuide: "إزاي الإشعار بيتوقّع",
    httpsOnly: "الرابط لازم يبدأ بـ https://",
    publicOnly: "اكتب رابط https عام: منقدرش نبعت لعنوان داخلي أو على جهازك.",
    permissions: "الصلاحيات",
    permissionsHint: "اللي التطبيق ممكن يطلبه من المتجر. اطلب اللي محتاجه بس: التاجر بيشوف القايمة دي.",
    permissionsRequired: "اختار صلاحية واحدة على الأقل.",
    resource_orders: "الطلبات",
    resource_products: "المنتجات",
    resource_categories: "التصنيفات",
    resource_customers: "العملاء",
    resource_discounts: "الخصومات",
    resource_shipping_areas: "الشحن",
    resource_webhooks: "Webhooks",
    resource_analytics: "التقارير",
    resource_funnels: "مسارات البيع",
    save: "حفظ",
    saving: "بنحفظ…",
    create: "إنشاء التطبيق",
    creating: "بيتعمل…",
    cancel: "إلغاء",
    saved: "اتحفظ {name}.",
    createdTitle: "انسخ مفاتيح تطبيقك",
    rotatedTitle: "انسخ الـ Client Secret الجديد",
    secretBody: "الـ Client Secret بيظهر مرة واحدة: مش هيظهر تاني. خلّيه على السيرفر بتاعك بس — ولو ضاع، اعمل واحد جديد.",
    clientSecret: "Client Secret",
    shownOnce: "مش هيظهر تاني",
    done: "تمام",
    rotateTitle: "تعمل Client Secret جديد لـ {name}؟",
    rotateBody: "الـ Secret الحالي هيبطّل يشتغل فورًا. حدّث سيرفر تطبيقك بالجديد على طول.",
    rotateConfirm: "اعمل Secret جديد",
    working: "بننفّذ…",
    installsTitle: "المتاجر اللي مثبّتة {name}",
    installsEmpty: "مفيش متجر ثبّت التطبيق ده لسه.",
    installedOn: "اتثبّت {date}",
    unnamedStore: "متجر",
    close: "إغلاق",
    deleteTitle: "تحذف {name}؟",
    deleteBody: "هيتشال من كل المتاجر اللي مثبّتاه ومفاتيحه هتقف. مينفعش ترجع فيها.",
    deleteConfirm: "احذف التطبيق",
    deleted: "اتحذف {name}.",
    guideTitle: "إزاي بيشتغل",
    guideIntro: "الخطوات اللي تطبيقك بيمشي عليها، من الموافقة لحد التوكن.",
    apiReference: "توثيق الـ API",
    guide1: "سجّل تطبيقك فوق: بتاخد {clientId} و {clientSecret}. التطبيق الجديد بيبقى تحت التطوير — المتاجر اللي إنت عضو فيها بس تقدر تثبّته، لحد ما زيموس ينشره.",
    guide2: "ابعت التاجر لصفحة الموافقة. رابط الرجوع لازم يكون واحد من اللي سجّلتهم بالظبط، والصلاحيات جزء من صلاحيات تطبيقك.",
    guide3: "بيرجع لرابط الرجوع بتاعك ومعاه {code} (أو {denied}). راجع الـ {state}. الكود بيفضل ١٠ دقايق وبيشتغل مرة واحدة.",
    guide4: "من السيرفر بتاعك، بدّل الكود بـ {token}. استخدمه على الـ API العام بالصلاحيات اللي اتوافق عليها، لحد ما المتجر يشيل تطبيقك أو إنت تسيبه. أي موافقة جديدة بتبدّل التوكن.",
    guide5: "صفحتك جوه لوحة التحكم (رابط صفحة التطبيق) بتتفتح في فريم بالباراميترز دي. الـ {hmac} هو {algo} بالـ {clientSecret} بتاعك لباقي الباراميترز، مترتّبة بالاسم ومتوصّلة بالشكل {pairs}. ارفض أي {timestamp} أقدم من ٥ دقايق.",
    guide6: "عشان تسيب متجر، الغي الربط من عندك.",
    guide7: "إشعار إلغاء التثبيت (لينك إلغاء التثبيت): لما متجر يشيل تطبيقك بنبعت الطلب ده، متوقّع في الهيدر {header}: وهو {algo} للـ body الخام بالـ {clientSecret} بتاعك. رد بـ {ok}؛ بنعيد المحاولة لحد يوم. مش بيتبعت لما التاجر يوافق عليك تاني. الـ {reason} واحد من: {reasons}.",
    cardTitle: "تطبيقات المطوّرين",
    cardBody: "بتعمل تطبيق لمتاجر زيموس؟ سجّله وخد مفاتيحه.",
    cardOpen: "افتح",
  },
} satisfies Messages;

export type PartnerAppText = Record<keyof (typeof PARTNER_APP_STRINGS)["en"], string>;

/** The most apps one developer account holds (backend partnerApps MAX_APPS_PER_DEVELOPER). */
export const PARTNER_APP_LIMIT = 20;

/** Where Account → Developers lives (under Settings, so the sidebar and the top bar stay on it), and its guide's anchor. */
export const DEVELOPERS_PATH = "/settings/developers";
export const GUIDE_ANCHOR = "partner-apps-guide";
