import type { LoyaltyTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty programme, and the points card on a customer's page.
 * Arabic is formal, as the rest of the dashboard.
 */
export const LOYALTY_STRINGS = {
  en: {
    // page
    title: "Loyalty programme",
    description: "Customers earn points on every delivered order and spend them at checkout.",
    stateOn: "Running",
    stateOff: "Off",
    stateIncomplete: "Needs setting up",
    statCustomers: "Customers with points",
    statPoints: "Points not spent yet",
    statWorth: "What they are worth",
    statWorthNone: "Set the value of a point",
    accountsOff: "Customer accounts are off, so customers can earn points but can't spend them: spending needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "Programme settings",
    settingsHint: "You set every number. Points are added when an order is delivered and taken back if it is returned or cancelled.",
    enable: "Turn on the loyalty programme",
    enableHintOn: "Customers earn points on delivered orders and can use them at checkout once they sign in.",
    enableHintOff: "Off: nobody earns or spends points. Balances customers already have stay as they are.",
    earn: "Points per {unit}",
    earnHint: "How many points a customer earns for every {unit} they pay for products. From 0.01 to 1000.",
    earnError: "Enter a number from 0.01 to 1000, with at most 2 decimals.",
    value: "Value of a point",
    valueHint: "What one point takes off an order when it is spent.",
    valueError: "Enter the value of one point, from 0.01.",
    valueExample: "{n} points = {amount}",
    summaryLine: "A customer who pays {spend} earns {points} worth {worth}",
    minPoints: "Fewest points to use on an order",
    minPointsHint: "A customer needs at least this many points before they can spend any.",
    minPointsError: "Enter a whole number from 1.",
    maxPercent: "Most of an order points can pay",
    maxPercentHint: "100 lets points pay a whole order; 50 lets them pay up to half of it.",
    maxPercentError: "Enter a whole number from 1 to 100.",
    percentUnit: "%",
    expiry: "Points expire after",
    expiryUnit: "days without activity",
    expiryHint: "Days with no points earned or spent. Leave it empty and points never expire.",
    expiryError: "Enter a number of days from 30 to 1825, or leave it empty.",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. The loyalty programme is running.",
    savedOff: "Saved. The loyalty programme is off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "A customer earns points on every delivered order and spends them as a discount at checkout.",
    groupEarn: "Earning points",
    groupSpend: "Spending points",
    groupExpiry: "When points expire",
    holdersTitle: "Points your customers hold",
    holdersLink: "One customer's points",
    holdersLinkHint: "On the customer's page: the balance, its history, and adding or taking points.",
    // customer card
    cardTitle: "Loyalty points",
    cardHint: "Earned on delivered orders, spent at checkout.",
    points_one: "1 point",
    points_other: "{n} points",
    worth: "Worth {amount}",
    expiresOn: "Expires on {date} if nothing is earned or spent",
    adjust: "Add or take points",
    history: "Points history",
    historyEmpty: "No points earned or spent yet.",
    kind_earn: "Earned on an order",
    kind_redeem: "Spent on an order",
    kind_hold: "Held for an unpaid order",
    kind_release: "Given back",
    kind_refund: "Back from a refund",
    kind_reverse: "Taken back (order returned or cancelled)",
    kind_expire: "Expired",
    kind_adjust: "Changed by your team",
    kind_referral: "Reward for inviting a friend",
    // adjust dialog
    adjustTitle: "Add or take points",
    adjustDescription: "Now: {balance}",
    direction: "Change",
    addPoints: "Add points",
    takePoints: "Take points",
    pointsLabel: "Points",
    pointsError: "Enter a whole number of points, from 1.",
    tooMany: "This customer has {balance}: that is the most you can take.",
    newBalance: "New balance: {balance}",
    note: "Reason",
    noteHint: "Kept with the change in this history.",
    noteError: "Write the reason for this change.",
    cancel: "Cancel",
    adjustSave: "Save",
    adjustSaving: "Saving…",
    added: "{points} added.",
    taken: "{points} taken off.",
    nothingMoved: "Nothing changed: the balance was already empty.",
  },
  ar: {
    // page
    title: "برنامج الولاء",
    description: "يكسب العملاء نقاطًا عن كل طلب يتم تسليمه، ويستخدمونها في صفحة الدفع.",
    stateOn: "مفعّل",
    stateOff: "متوقف",
    stateIncomplete: "يحتاج إلى إعداد",
    statCustomers: "عملاء لديهم نقاط",
    statPoints: "نقاط لم تُستخدم بعد",
    statWorth: "قيمتها",
    statWorthNone: "حدّد قيمة النقطة",
    accountsOff: "حسابات العملاء متوقفة، لذلك سيكسب العملاء نقاطًا لكنهم لن يستطيعوا استخدامها: الاستخدام يتطلب تسجيل دخول العميل.",
    accountsOffAction: "تفعيل حسابات العملاء",
    settingsTitle: "إعدادات البرنامج",
    settingsHint: "أنت من يحدد كل رقم. تُضاف النقاط عند تسليم الطلب، وتُسحب إذا أُرجع الطلب أو أُلغي.",
    enable: "تفعيل برنامج الولاء",
    enableHintOn: "يكسب العملاء نقاطًا عن الطلبات التي تم تسليمها، ويمكنهم استخدامها في الدفع بعد تسجيل الدخول.",
    enableHintOff: "متوقف: لا أحد يكسب نقاطًا أو يستخدمها. نقاط العملاء الحالية تبقى كما هي.",
    earn: "عدد النقاط لكل {unit}",
    earnHint: "عدد النقاط التي يكسبها العميل عن كل {unit} يدفعه في المنتجات. من ٠٫٠١ إلى ١٠٠٠.",
    earnError: "أدخل رقمًا من ٠٫٠١ إلى ١٠٠٠، بحد أقصى رقمين بعد العلامة العشرية.",
    value: "قيمة النقطة",
    valueHint: "المبلغ الذي تخصمه النقطة الواحدة من الطلب عند استخدامها.",
    valueError: "أدخل قيمة النقطة الواحدة، من ٠٫٠١.",
    valueExample: "{n} نقطة = {amount}",
    summaryLine: "العميل الذي يدفع {spend} يكسب {points} قيمتها {worth}",
    minPoints: "أقل عدد نقاط يُستخدم في الطلب",
    minPointsHint: "يجب أن يملك العميل هذا العدد على الأقل ليستخدم نقاطه.",
    minPointsError: "أدخل رقمًا صحيحًا من ١.",
    maxPercent: "أقصى نسبة من الطلب تُدفع بالنقاط",
    maxPercentHint: "١٠٠ تعني أن النقاط تدفع الطلب كاملًا، و٥٠ تعني حتى نصفه.",
    maxPercentError: "أدخل رقمًا صحيحًا من ١ إلى ١٠٠.",
    percentUnit: "٪",
    expiry: "تنتهي النقاط بعد",
    expiryUnit: "يومًا دون شراء",
    expiryHint: "عدد الأيام التي لا يكسب فيها العميل نقاطًا ولا يستخدمها. اتركه فارغًا فلا تنتهي النقاط.",
    expiryError: "أدخل عدد أيام من ٣٠ إلى ١٨٢٥، أو اتركه فارغًا.",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ.",
    savedOn: "تم الحفظ. برنامج الولاء مفعّل.",
    savedOff: "تم الحفظ. برنامج الولاء متوقف.",
    fixFields: "راجع الحقول المشار إليها.",
    customerGets: "يكسب العميل نقاطًا عن كل طلب يتم تسليمه، ويستخدمها خصمًا في صفحة الدفع.",
    groupEarn: "كسب النقاط",
    groupSpend: "استخدام النقاط",
    groupExpiry: "متى تنتهي النقاط",
    holdersTitle: "نقاط عملائك",
    holdersLink: "نقاط عميل معيّن",
    holdersLinkHint: "في صفحة العميل: رصيده وحركة نقاطه، مع إمكانية الإضافة أو الخصم.",
    // customer card
    cardTitle: "نقاط الولاء",
    cardHint: "يكسبها من الطلبات التي تم تسليمها، ويستخدمها في صفحة الدفع.",
    points_one: "نقطة واحدة",
    points_two: "نقطتان",
    points_few: "{n} نقاط",
    points_other: "{n} نقطة",
    worth: "قيمتها {amount}",
    expiresOn: "تنتهي يوم {date} إذا لم يكسب نقاطًا أو يستخدمها",
    adjust: "إضافة/خصم نقاط",
    history: "حركة النقاط",
    historyEmpty: "لم تُكسب نقاط أو تُستخدم بعد.",
    kind_earn: "كسبها من طلب",
    kind_redeem: "استُخدمت في طلب",
    kind_hold: "محجوزة لطلب لم يُدفع بعد",
    kind_release: "أُعيدت إلى العميل",
    kind_refund: "أُعيدت من استرداد",
    kind_reverse: "سُحبت (أُرجع الطلب أو أُلغي)",
    kind_expire: "انتهت",
    kind_adjust: "تعديل من فريقك",
    kind_referral: "مكافأة دعوة صديق",
    // adjust dialog
    adjustTitle: "إضافة/خصم نقاط",
    adjustDescription: "الآن: {balance}",
    direction: "التعديل",
    addPoints: "إضافة نقاط",
    takePoints: "خصم نقاط",
    pointsLabel: "عدد النقاط",
    pointsError: "أدخل عدد نقاط صحيحًا، من ١.",
    tooMany: "لدى العميل {balance}: هذا أقصى ما يمكن خصمه.",
    newBalance: "الرصيد الجديد: {balance}",
    note: "السبب",
    noteHint: "يُحفظ مع التعديل في حركة النقاط هنا.",
    noteError: "أدخل سبب التعديل.",
    cancel: "إلغاء",
    adjustSave: "حفظ",
    adjustSaving: "جارٍ الحفظ…",
    added: "تمت إضافة {points}.",
    taken: "تم خصم {points}.",
    nothingMoved: "لم يتغير شيء: الرصيد كان صفرًا.",
  },
} satisfies Messages;

export type LoyaltyStrings = (typeof LOYALTY_STRINGS)["en"];

export const LOYALTY_KIND_KEY: Record<LoyaltyTransactionKind, keyof LoyaltyStrings> = {
  earn: "kind_earn",
  redeem: "kind_redeem",
  hold: "kind_hold",
  release: "kind_release",
  refund: "kind_refund",
  reverse: "kind_reverse",
  expire: "kind_expire",
  adjust: "kind_adjust",
  referral: "kind_referral",
};

/** Western digits for whatever digits were typed (an Arabic keyboard types ٠–٩ and the Arabic decimal mark). */
export function toAsciiDigits(raw: string): string {
  return raw
    .replace(/[٠-٩]/g, (d) => String("٠١٢٣٤٥٦٧٨٩".indexOf(d)))
    .replace(/[۰-۹]/g, (d) => String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))
    .replace(/٫/g, ".")
    .trim();
}

/** A whole number within [min, max], or null. */
export function parseWhole(raw: string, min: number, max: number): number | null {
  const ascii = toAsciiDigits(raw);
  if (!/^\d{1,9}$/.test(ascii)) return null;
  const n = Number(ascii);
  return n >= min && n <= max ? n : null;
}
