import type { LoyaltyTransactionKind } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Customers → Loyalty programme, and the points card on a customer's page
 * (handoff 203). Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const LOYALTY_STRINGS = {
  en: {
    // page
    title: "Loyalty programme",
    description: "Customers earn points on every delivered order and spend them at checkout.",
    stateOn: "Running",
    stateOff: "Off",
    stateIncomplete: "Needs setting up",
    statCustomers: "Customers with points",
    statPoints: "Points not spent yet",
    statWorth: "What they are worth",
    statWorthNone: "Set the value of a point",
    accountsOff: "Customer accounts are off, so customers can earn points but can't spend them: spending needs a signed-in customer.",
    accountsOffAction: "Turn on customer accounts",
    settingsTitle: "Programme settings",
    settingsHint: "You set every number. Points are added when an order is delivered and taken back if it is returned or cancelled.",
    enable: "Turn on the loyalty programme",
    enableHintOn: "Customers earn points on delivered orders and can use them at checkout once they sign in.",
    enableHintOff: "Off: nobody earns or spends points. Balances customers already have stay as they are.",
    earn: "Points per {unit}",
    earnHint: "How many points a customer earns for every {unit} they pay for products. From 0.01 to 1000.",
    earnError: "Enter a number from 0.01 to 1000, with at most 2 decimals.",
    value: "Value of a point",
    valueHint: "What one point takes off an order when it is spent.",
    valueError: "Enter the value of one point, from 0.01.",
    valueExample: "{n} points = {amount}",
    summaryLine: "A customer who pays {spend} earns {points} worth {worth}",
    minPoints: "Fewest points to use on an order",
    minPointsHint: "A customer needs at least this many points before they can spend any.",
    minPointsError: "Enter a whole number from 1.",
    maxPercent: "Most of an order points can pay",
    maxPercentHint: "100 lets points pay a whole order; 50 lets them pay up to half of it.",
    maxPercentError: "Enter a whole number from 1 to 100.",
    percentUnit: "%",
    expiry: "Points expire after",
    expiryUnit: "days without activity",
    expiryHint: "Days with no points earned or spent. Leave it empty and points never expire.",
    expiryError: "Enter a number of days from 30 to 1825, or leave it empty.",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    savedOn: "Saved. The loyalty programme is running.",
    savedOff: "Saved. The loyalty programme is off.",
    fixFields: "Check the highlighted fields.",
    customerGets: "A customer earns points on every delivered order and spends them as a discount at checkout.",
    groupEarn: "Earning points",
    groupSpend: "Spending points",
    groupExpiry: "When points expire",
    holdersTitle: "Points your customers hold",
    holdersLink: "One customer's points",
    holdersLinkHint: "On the customer's page: the balance, its history, and adding or taking points.",
    // customer card
    cardTitle: "Loyalty points",
    cardHint: "Earned on delivered orders, spent at checkout.",
    points_one: "1 point",
    points_other: "{n} points",
    worth: "Worth {amount}",
    expiresOn: "Expires on {date} if nothing is earned or spent",
    adjust: "Add or take points",
    history: "Points history",
    historyEmpty: "No points earned or spent yet.",
    kind_earn: "Earned on an order",
    kind_redeem: "Spent on an order",
    kind_hold: "Held for an unpaid order",
    kind_release: "Given back",
    kind_refund: "Back from a refund",
    kind_reverse: "Taken back (order returned or cancelled)",
    kind_expire: "Expired",
    kind_adjust: "Changed by your team",
    kind_referral: "Reward for inviting a friend",
    // adjust dialog
    adjustTitle: "Add or take points",
    adjustDescription: "Now: {balance}",
    direction: "Change",
    addPoints: "Add points",
    takePoints: "Take points",
    pointsLabel: "Points",
    pointsError: "Enter a whole number of points, from 1.",
    tooMany: "This customer has {balance}: that is the most you can take.",
    newBalance: "New balance: {balance}",
    note: "Reason",
    noteHint: "Kept with the change in this history.",
    noteError: "Write the reason for this change.",
    cancel: "Cancel",
    adjustSave: "Save",
    adjustSaving: "Saving…",
    added: "{points} added.",
    taken: "{points} taken off.",
    nothingMoved: "Nothing changed: the balance was already empty.",
  },
  ar: {
    // page
    title: "برنامج الولاء",
    description: "العملاء بيكسبوا نقط على كل أوردر يتسلّم، وبيصرفوها في صفحة الدفع.",
    stateOn: "شغّال",
    stateOff: "مقفول",
    stateIncomplete: "ناقصه إعداد",
    statCustomers: "عملاء عندهم نقط",
    statPoints: "نقط لسه ما اتصرفتش",
    statWorth: "قيمتها",
    statWorthNone: "حدّد قيمة النقطة",
    accountsOff: "حسابات العملاء مقفولة، فالعملاء هيكسبوا نقط بس مش هيقدروا يصرفوها: الصرف محتاج العميل يسجّل دخول.",
    accountsOffAction: "شغّل حسابات العملاء",
    settingsTitle: "إعدادات البرنامج",
    settingsHint: "إنت اللي بتحدد كل رقم. النقط بتتضاف لما الأوردر يتسلّم، وبتترجع لو الأوردر اترجّع أو اتلغى.",
    enable: "شغّل برنامج الولاء",
    enableHintOn: "العملاء بيكسبوا نقط على الأوردرات اللي اتسلّمت، ويقدروا يستخدموها في الدفع بعد ما يسجّلوا دخول.",
    enableHintOff: "مقفول: محدش بيكسب ولا بيصرف نقط. النقط اللي عند العملاء فاضلة زي ما هي.",
    earn: "كل {unit} = كام نقطة",
    earnHint: "عدد النقط اللي العميل بيكسبها على كل {unit} بيدفعه في المنتجات. من ٠٫٠١ لـ ١٠٠٠.",
    earnError: "اكتب رقم من ٠٫٠١ لـ ١٠٠٠، بحد أقصى رقمين بعد العلامة.",
    value: "قيمة النقطة",
    valueHint: "النقطة الواحدة بتخصم كام من الأوردر لما العميل يصرفها.",
    valueError: "اكتب قيمة النقطة الواحدة، من ٠٫٠١.",
    valueExample: "{n} نقطة = {amount}",
    summaryLine: "العميل اللي يدفع {spend} بيكسب {points} قيمتها {worth}",
    minPoints: "أقل عدد نقط يتستخدم في الأوردر",
    minPointsHint: "العميل لازم يكون معاه العدد ده على الأقل عشان يصرف نقطه.",
    minPointsError: "اكتب رقم صحيح من ١.",
    maxPercent: "أقصى نسبة من الأوردر تتدفع بالنقط",
    maxPercentHint: "١٠٠ يعني النقط تدفع الأوردر كله، و٥٠ يعني لحد نصه.",
    maxPercentError: "اكتب رقم صحيح من ١ لـ ١٠٠.",
    percentUnit: "٪",
    expiry: "النقط بتنتهي بعد",
    expiryUnit: "يوم من غير شرا",
    expiryHint: "عدد الأيام من غير ما العميل يكسب أو يصرف نقط. سيبه فاضي والنقط ما تنتهيش.",
    expiryError: "اكتب عدد أيام من ٣٠ لـ ١٨٢٥، أو سيبه فاضي.",
    save: "احفظ",
    saving: "بنحفظ…",
    saved: "اتحفظ.",
    savedOn: "اتحفظ. برنامج الولاء شغّال.",
    savedOff: "اتحفظ. برنامج الولاء مقفول.",
    fixFields: "راجع الخانات المتعلّم عليها.",
    customerGets: "العميل بيكسب نقط على كل أوردر يتسلّم، وبيصرفها خصم في صفحة الدفع.",
    groupEarn: "كسب النقط",
    groupSpend: "صرف النقط",
    groupExpiry: "النقط بتنتهي إمتى",
    holdersTitle: "النقط اللي عند عملاءك",
    holdersLink: "نقط عميل معيّن",
    holdersLinkHint: "في صفحة العميل: رصيده وحركة نقطه، وتزوّد أو تخصم منها.",
    // customer card
    cardTitle: "نقط الولاء",
    cardHint: "بيكسبها من الأوردرات اللي اتسلّمت، وبيصرفها في صفحة الدفع.",
    points_one: "نقطة واحدة",
    points_two: "نقطتين",
    points_few: "{n} نقط",
    points_other: "{n} نقطة",
    worth: "قيمتها {amount}",
    expiresOn: "بتنتهي يوم {date} لو مكسبش أو صرفش نقط",
    adjust: "إضافة/خصم نقط",
    history: "حركة النقط",
    historyEmpty: "لسه مفيش نقط اتكسبت أو اتصرفت.",
    kind_earn: "كسبها من أوردر",
    kind_redeem: "اتصرفت في أوردر",
    kind_hold: "محجوزة لأوردر لسه ما اتدفعش",
    kind_release: "رجعت للعميل",
    kind_refund: "رجعت من استرداد",
    kind_reverse: "اتسحبت (الأوردر اترجّع أو اتلغى)",
    kind_expire: "انتهت",
    kind_adjust: "تعديل من فريقك",
    kind_referral: "مكافأة دعوة صاحب",
    // adjust dialog
    adjustTitle: "إضافة/خصم نقط",
    adjustDescription: "دلوقتي: {balance}",
    direction: "التعديل",
    addPoints: "زوّد نقط",
    takePoints: "اخصم نقط",
    pointsLabel: "عدد النقط",
    pointsError: "اكتب عدد نقط صحيح، من ١.",
    tooMany: "العميل معاه {balance}: ده أقصى حاجة تقدر تخصمها.",
    newBalance: "الرصيد الجديد: {balance}",
    note: "السبب",
    noteHint: "بيتحفظ مع التعديل في حركة النقط هنا.",
    noteError: "اكتب سبب التعديل.",
    cancel: "إلغاء",
    adjustSave: "احفظ",
    adjustSaving: "بنحفظ…",
    added: "اتضاف {points}.",
    taken: "اتخصم {points}.",
    nothingMoved: "مفيش حاجة اتغيرت: الرصيد كان فاضي.",
  },
} satisfies Messages;

export type LoyaltyStrings = (typeof LOYALTY_STRINGS)["en"];

export const LOYALTY_KIND_KEY: Record<LoyaltyTransactionKind, keyof LoyaltyStrings> = {
  earn: "kind_earn",
  redeem: "kind_redeem",
  hold: "kind_hold",
  release: "kind_release",
  refund: "kind_refund",
  reverse: "kind_reverse",
  expire: "kind_expire",
  adjust: "kind_adjust",
  referral: "kind_referral",
};

/** Western digits for whatever digits were typed (an Arabic keyboard types ٠–٩ and the Arabic decimal mark). */
export function toAsciiDigits(raw: string): string {
  return raw
    .replace(/[٠-٩]/g, (d) => String("٠١٢٣٤٥٦٧٨٩".indexOf(d)))
    .replace(/[۰-۹]/g, (d) => String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))
    .replace(/٫/g, ".")
    .trim();
}

/** A whole number within [min, max], or null. */
export function parseWhole(raw: string, min: number, max: number): number | null {
  const ascii = toAsciiDigits(raw);
  if (!/^\d{1,9}$/.test(ascii)) return null;
  const n = Number(ascii);
  return n >= min && n <= max ? n : null;
}
