import type { Messages } from "@/i18n/LocaleContext";

/** Storefront search (handoff 211): the "Store search" report, the synonyms page and the "Add a synonym" dialog. */
export const SEARCH_STRINGS = {
  en: {
    // Analytics → Store search
    title: "Store search",
    description: "What shoppers type into your store's search, what they open, and what finds nothing.",
    synonymsLink: "Search synonyms",
    searches: "Searches",
    searchers: "Shoppers who searched",
    noResults: "Searches with no results",
    noResultsShare: "{percent} of searches",
    clickRate: "Opened a result",
    clickRateHint_one: "1 result opened",
    clickRateHint_other: "{n} results opened",
    clickRateNone: "No search had results",
    topTitle: "Top searches",
    topHint: "The words searched most, with how many products they find and how often a result is opened.",
    colQuery: "Search",
    colSearches: "Searches",
    colResults: "Results",
    colClicks: "Opened",
    colRate: "Rate",
    servedAs: "shown as “{term}”",
    servedAsTitle: "Found nothing itself, so its synonym's results were shown.",
    noneTitle: "Searches with no results",
    noneHint: "Shoppers looked for these and found nothing. Add the product, or a synonym that points to what you do sell.",
    times_one: "Searched once",
    times_other: "Searched {n} times",
    lastOn: "last on {date}",
    addSynonym: "Add a synonym",
    noneEmpty: "Every search found something in this period.",
    clickedTitle: "Most opened from search",
    clickedHint: "The products shoppers open after searching.",
    opens_one: "opened once",
    opens_other: "opened {n} times",
    clickedEmpty: "No result was opened from a search in this period.",
    emptyTitle: "No searches in this period",
    emptyHint: "When shoppers use the search box in your store, what they looked for shows up here.",
    kept: "Searches are kept for 180 days.",
    // Add a synonym
    addTitle: "A synonym for “{query}”",
    addDescription: "When a search for “{query}” finds nothing, shoppers get the results of the word you write here.",
    addTerm: "A word you do have products for",
    addTermHint: "For example a product's name, or the same word in the other language.",
    addSame: "Write a different word from the search itself.",
    addRequired: "Write the word to search instead.",
    addGroupFull: "That word's group already has {max} words. Remove one on the Search synonyms page first.",
    addTooMany: "The store already has {max} groups. Remove one on the Search synonyms page first.",
    addBoth: "“{query}” and “{term}” are each in a different group already. Merge them on the Search synonyms page.",
    addSave: "Add synonym",
    addSaving: "Adding…",
    addDone: "Synonym added: “{query}” = “{term}”.",
    addExists: "“{query}” and “{term}” are already synonyms.",
    cancel: "Cancel",
    // Products → Search synonyms
    synTitle: "Search synonyms",
    synDescription: "When a word finds nothing, we try its synonyms.",
    synHint: "Put the words that mean the same thing in one group — Arabic and English spellings, short names, common misspellings.",
    groupsTitle: "Groups of words",
    group: "Group {n}",
    groupPlaceholder: "Write a word and press Enter",
    groupHint: "2 to {max} words. A word belongs to one group only.",
    addGroup: "Add a group",
    removeGroup: "Remove group {n}",
    groupTooSmall: "A group needs at least two words.",
    groupClash: "“{term}” is in two groups. Keep it in one.",
    maxGroups: "A store holds up to {max} groups.",
    synEmptyTitle: "No synonyms yet",
    synEmptyHint: "For example: تيشيرت = t-shirt = tee. A shopper who searches for one finds the products named with another.",
    synSaved: "Synonyms saved.",
    save: "Save synonyms",
    saving: "Saving…",
    openReport: "See what shoppers search for",
  },
  ar: {
    title: "البحث في المتجر",
    description: "العملاء بيكتبوا إيه في بحث متجرك، بيفتحوا إيه، وإيه اللي مابيلاقوهوش.",
    synonymsLink: "مرادفات البحث",
    searches: "عمليات البحث",
    searchers: "عملاء دوّروا",
    noResults: "بحث من غير نتايج",
    noResultsShare: "{percent} من البحث",
    clickRate: "فتحوا نتيجة",
    clickRateHint_one: "نتيجة واحدة اتفتحت",
    clickRateHint_two: "نتيجتين اتفتحوا",
    clickRateHint_few: "{n} نتايج اتفتحت",
    clickRateHint_other: "{n} نتيجة اتفتحت",
    clickRateNone: "مفيش بحث طلّع نتايج",
    topTitle: "أكتر الكلمات بحثًا",
    topHint: "أكتر كلمات اتدوّر عليها، وبتلاقي كام منتج، والنتيجة بتتفتح قد إيه.",
    colQuery: "كلمة البحث",
    colSearches: "مرات البحث",
    colResults: "النتايج",
    colClicks: "اتفتحت",
    colRate: "النسبة",
    servedAs: "ظهرت كـ «{term}»",
    servedAsTitle: "الكلمة نفسها مالقتش حاجة، فظهرت نتايج مرادفها.",
    noneTitle: "بحث من غير نتايج",
    noneHint: "العملاء دوّروا على الكلمات دي ومالقوش حاجة. ضيف المنتج، أو مرادف يودّي للي بتبيعه.",
    times_one: "اتدوّر عليها مرة واحدة",
    times_two: "اتدوّر عليها مرتين",
    times_few: "اتدوّر عليها {n} مرات",
    times_other: "اتدوّر عليها {n} مرة",
    lastOn: "آخر مرة {date}",
    addSynonym: "أضف مرادف",
    noneEmpty: "كل بحث في الفترة دي لقى حاجة.",
    clickedTitle: "أكتر منتجات اتفتحت من البحث",
    clickedHint: "المنتجات اللي العملاء بيفتحوها بعد ما يدوّروا.",
    opens_one: "اتفتح مرة واحدة",
    opens_two: "اتفتح مرتين",
    opens_few: "اتفتح {n} مرات",
    opens_other: "اتفتح {n} مرة",
    clickedEmpty: "مفيش نتيجة اتفتحت من البحث في الفترة دي.",
    emptyTitle: "مفيش بحث في الفترة دي",
    emptyHint: "لما العملاء يستخدموا خانة البحث في متجرك، اللي دوّروا عليه هيظهر هنا.",
    kept: "البحث بيتحفظ ١٨٠ يوم.",
    addTitle: "مرادف لـ «{query}»",
    addDescription: "لما حد يدوّر على «{query}» ومايلاقيش، هتظهرله نتايج الكلمة اللي هتكتبها هنا.",
    addTerm: "كلمة عندك ليها منتجات",
    addTermHint: "زي اسم منتج، أو نفس الكلمة باللغة التانية.",
    addSame: "اكتب كلمة غير كلمة البحث نفسها.",
    addRequired: "اكتب الكلمة اللي نبحث بيها بدالها.",
    addGroupFull: "مجموعة الكلمة دي فيها {max} كلمات بالفعل. شيل واحدة من صفحة مرادفات البحث الأول.",
    addTooMany: "المتجر فيه {max} مجموعة بالفعل. شيل واحدة من صفحة مرادفات البحث الأول.",
    addBoth: "«{query}» و«{term}» كل واحدة في مجموعة مختلفة بالفعل. ادمجهم من صفحة مرادفات البحث.",
    addSave: "ضيف المرادف",
    addSaving: "بنضيف…",
    addDone: "اتضاف المرادف: «{query}» = «{term}».",
    addExists: "«{query}» و«{term}» مرادفين بالفعل.",
    cancel: "إلغاء",
    synTitle: "مرادفات البحث",
    synDescription: "لو حد دوّر على كلمة ومالقاش، بنجرّب مرادفاتها.",
    synHint: "حط الكلمات اللي ليها نفس المعنى في مجموعة واحدة — الكتابة بالعربي والإنجليزي، الأسماء المختصرة، والأخطاء الشائعة.",
    groupsTitle: "مجموعات الكلمات",
    group: "مجموعة {n}",
    groupPlaceholder: "اكتب كلمة ودوس Enter",
    groupHint: "من كلمتين لـ {max} كلمات. الكلمة بتبقى في مجموعة واحدة بس.",
    addGroup: "ضيف مجموعة",
    removeGroup: "شيل المجموعة {n}",
    groupTooSmall: "المجموعة محتاجة كلمتين على الأقل.",
    groupClash: "«{term}» موجودة في مجموعتين. خليها في واحدة بس.",
    maxGroups: "المتجر بياخد لحد {max} مجموعة.",
    synEmptyTitle: "مفيش مرادفات لسه",
    synEmptyHint: "مثلًا: تيشيرت = t-shirt = tee. اللي يدوّر على واحدة يلاقي المنتجات المكتوبة بالتانية.",
    synSaved: "المرادفات اتحفظت.",
    save: "احفظ المرادفات",
    saving: "بنحفظ…",
    openReport: "شوف العملاء بيدوّروا على إيه",
  },
} satisfies Messages;
