import type { ShippingRateType } from "@store-builder/api-client";
import type { Locale, Messages } from "@/i18n/LocaleContext";

export const SHIPPING_TAX_STRINGS = {
  en: {
    pageTitle: "Shipping & carriers",
    pageDescription: "Carrier accounts, shipping zones and their rates, plus the tax rates applied at checkout.",
    tabCarriers: "Carriers",
    tabZones: "Zones & rates",
    tabTax: "Tax",

    zonesTitle: "Shipping zones",
    addZone: "Add zone",
    editZone: "Edit zone",
    saveZone: "Save zone",
    zonesEmptyTitle: "No shipping zones yet",
    zonesEmptyDesc: "Add your first zone to set where you ship and what you charge.",
    noCountries: "No countries",
    noRatesInZone: "No rates in this zone yet.",
    activate: "Activate",
    deactivate: "Deactivate",

    taxTitle: "Tax rates",
    taxOffNote:
      "Tax is turned off for this store — these rates aren’t applied at checkout. Turn it on under Zones & rates to use them.",
    addTaxRate: "Add tax rate",
    editTaxRate: "Edit tax rate",
    saveTaxRate: "Save tax rate",
    taxEmptyTitle: "No tax rates yet",
    taxEmptyDesc: "Add your first tax rate to charge it at checkout.",

    colName: "Name",
    colCountry: "Country",
    colRate: "Rate",
    colAppliesToShipping: "Applies to shipping",
    colPricesIncludeTax: "Prices include tax",
    colType: "Type",
    colDetail: "Detail",
    colDelivery: "Delivery",
    colCarrier: "Carrier",

    addRate: "Add rate",
    editRate: "Edit rate",
    saveRate: "Save rate",

    toastActivated: "\"{name}\" activated.",
    toastDeactivated: "\"{name}\" deactivated.",
    toastDeleted: "\"{name}\" deleted.",
    toastAdded: "\"{name}\" added.",
    toastRateDeleted: "Rate deleted.",
    toastZoneSaved: "Zone saved.",
    toastRateSaved: "Rate saved.",
    toastTaxSaved: "Tax rate saved.",
    toastSettingsSaved: "Store shipping & tax settings saved.",

    confirmDeleteTitle: "Delete \"{name}\"?",
    confirmZoneDesc:
      "Removing a zone deletes its rates too. Orders already placed keep the shipping amount they were charged.",
    confirmZoneLabel: "Delete zone",
    confirmRateDesc: "This shipping rate is removed immediately. Past orders are unaffected.",
    confirmRateLabel: "Delete rate",
    confirmTaxDesc: "This tax rate is removed immediately. Past orders keep the tax they were charged.",
    confirmTaxLabel: "Delete tax rate",

    noCharge: "No charge",
    tierOne: "1 tier",
    tierMany: "{n} tiers",
    dayOne: "1 day",
    dayMany: "{n} days",
    daysRange: "{range} days",
    fromDays: "from {days}",
    upToDays: "up to {days}",

    nameLabel: "Name",
    zoneNamePlaceholder: "Domestic",
    countriesLabel: "Countries",
    countriesHint: "Two-letter codes separated by commas, e.g. EG, SA.",

    rateNamePlaceholder: "Standard",
    rateTypeLabel: "Rate type",
    amountLabel: "Amount",
    freeNoSettings: "A free rate has no extra settings.",
    tiersLabel: "Tiers",
    addTier: "+ Add tier",
    removeTier: "Remove tier",
    upToGrams: "Up to (grams)",
    upToQuantity: "Up to (quantity)",
    minSubtotal: "Minimum subtotal",
    overflowAmount: "Overflow amount",
    overflowHint: "Charged when the order is heavier / larger than every tier.",
    carrierCode: "Carrier code",
    optional: "Optional.",
    estMin: "Est. delivery — min days",
    estMinHint: "Optional. Shown to shoppers at checkout.",
    estMax: "Est. delivery — max days",

    errAmount: "Enter a valid amount.",
    errAtLeastOneTier: "Add at least one tier.",
    errTierAmount: "Every tier needs a valid amount.",
    errTierMinSubtotal: "Every tier needs a valid minimum subtotal.",
    errTierWeight: "Every tier needs a valid weight in grams.",
    errTierQuantity: "Every tier needs a valid quantity.",
    errDays: "Whole number of days, 0–3650.",
    errMaxLessMin: "Max days can't be less than min days.",

    taxNamePlaceholder: "VAT",
    countryLabel: "Country",
    countryHint: "Optional, two-letter code.",
    regionLabel: "Region",
    rateLabel: "Rate",
    rateHint: "Percentage, e.g. 14 for 14%.",
    appliesToShipping: "Applies to shipping",
    pricesAlreadyInclude: "Prices already include tax",
    errPercent: "Enter a percentage of 0 or more.",
    errCountryCode: "Use a two-letter country code.",

    settingsTitle: "Store shipping & tax",
    settingsDesc: "Storewide rules applied at checkout, before any individual zone or rate.",
    freeThreshold: "Free shipping threshold",
    freeThresholdHint: "Orders at or above this subtotal ship free. Leave blank to disable.",
    defaultRate: "Default shipping rate",
    defaultRateHint: "Charged when no active zone or rate matches. Leave blank to fall back to free.",
    chargeTax: "Charge tax at checkout",
    saveSettings: "Save settings",
  },
  ar: {
    pageTitle: "الشحن وشركات الشحن",
    pageDescription: "حسابات شركات الشحن، ومناطق الشحن وأسعارها، ونسب الضرائب المطبّقة عند إتمام الطلب.",
    tabCarriers: "شركات الشحن",
    tabZones: "مناطق الشحن والأسعار",
    tabTax: "الضرائب",

    zonesTitle: "مناطق الشحن",
    addZone: "إضافة منطقة",
    editZone: "تعديل المنطقة",
    saveZone: "حفظ المنطقة",
    zonesEmptyTitle: "لا توجد مناطق شحن بعد",
    zonesEmptyDesc: "أضف أول منطقة لتحدد أماكن الشحن وتكلفته.",
    noCountries: "لا توجد دول",
    noRatesInZone: "لا توجد أسعار في هذه المنطقة بعد.",
    activate: "تفعيل",
    deactivate: "إيقاف",

    taxTitle: "نسب الضرائب",
    taxOffNote:
      "الضرائب متوقفة لهذا المتجر — لن تُطبَّق هذه النسب عند إتمام الطلب. فعّلها من تبويب مناطق الشحن والأسعار لاستخدامها.",
    addTaxRate: "إضافة نسبة ضريبة",
    editTaxRate: "تعديل نسبة الضريبة",
    saveTaxRate: "حفظ نسبة الضريبة",
    taxEmptyTitle: "لا توجد نسب ضرائب بعد",
    taxEmptyDesc: "أضف أول نسبة ضريبة لتحصيلها عند إتمام الطلب.",

    colName: "الاسم",
    colCountry: "الدولة",
    colRate: "النسبة",
    colAppliesToShipping: "تُطبَّق على الشحن",
    colPricesIncludeTax: "الأسعار شاملة الضريبة",
    colType: "النوع",
    colDetail: "التفاصيل",
    colDelivery: "مدة التوصيل",
    colCarrier: "شركة الشحن",

    addRate: "إضافة سعر",
    editRate: "تعديل السعر",
    saveRate: "حفظ السعر",

    toastActivated: "تم تفعيل «{name}».",
    toastDeactivated: "تم إيقاف «{name}».",
    toastDeleted: "تم حذف «{name}».",
    toastAdded: "تمت إضافة «{name}».",
    toastRateDeleted: "تم حذف السعر.",
    toastZoneSaved: "تم حفظ المنطقة.",
    toastRateSaved: "تم حفظ السعر.",
    toastTaxSaved: "تم حفظ نسبة الضريبة.",
    toastSettingsSaved: "تم حفظ إعدادات الشحن والضرائب للمتجر.",

    confirmDeleteTitle: "حذف «{name}»؟",
    confirmZoneDesc: "حذف المنطقة يحذف أسعارها أيضًا. الطلبات السابقة تحتفظ بقيمة الشحن التي دُفعت.",
    confirmZoneLabel: "حذف المنطقة",
    confirmRateDesc: "سيُحذف سعر الشحن هذا فورًا. لن تتأثر الطلبات السابقة.",
    confirmRateLabel: "حذف السعر",
    confirmTaxDesc: "ستُحذف نسبة الضريبة هذه فورًا. الطلبات السابقة تحتفظ بالضريبة التي دُفعت.",
    confirmTaxLabel: "حذف نسبة الضريبة",

    noCharge: "مجانًا",
    tierOne: "شريحة واحدة",
    tierMany: "{n} شرائح",
    dayOne: "يوم واحد",
    dayMany: "{n} أيام",
    daysRange: "{range} أيام",
    fromDays: "من {days}",
    upToDays: "حتى {days}",

    nameLabel: "الاسم",
    zoneNamePlaceholder: "محلي",
    countriesLabel: "الدول",
    countriesHint: "رموز من حرفين مفصولة بفواصل، مثل EG, SA.",

    rateNamePlaceholder: "عادي",
    rateTypeLabel: "نوع السعر",
    amountLabel: "المبلغ",
    freeNoSettings: "السعر المجاني لا يحتاج إعدادات إضافية.",
    tiersLabel: "الشرائح",
    addTier: "+ إضافة شريحة",
    removeTier: "حذف الشريحة",
    upToGrams: "حتى (جرام)",
    upToQuantity: "حتى (كمية)",
    minSubtotal: "الحد الأدنى للمجموع الفرعي",
    overflowAmount: "مبلغ التجاوز",
    overflowHint: "يُحصَّل عندما يكون الطلب أثقل أو أكبر من كل الشرائح.",
    carrierCode: "رمز شركة الشحن",
    optional: "اختياري.",
    estMin: "مدة التوصيل المتوقعة — أقل عدد أيام",
    estMinHint: "اختياري. يظهر للعملاء عند إتمام الطلب.",
    estMax: "مدة التوصيل المتوقعة — أكبر عدد أيام",

    errAmount: "أدخل مبلغًا صحيحًا.",
    errAtLeastOneTier: "أضف شريحة واحدة على الأقل.",
    errTierAmount: "كل شريحة تحتاج مبلغًا صحيحًا.",
    errTierMinSubtotal: "كل شريحة تحتاج حدًا أدنى صحيحًا للمجموع الفرعي.",
    errTierWeight: "كل شريحة تحتاج وزنًا صحيحًا بالجرام.",
    errTierQuantity: "كل شريحة تحتاج كمية صحيحة.",
    errDays: "عدد أيام صحيح من 0 إلى 3650.",
    errMaxLessMin: "لا يمكن أن يكون أكبر عدد أيام أقل من أقل عدد أيام.",

    taxNamePlaceholder: "ضريبة القيمة المضافة",
    countryLabel: "الدولة",
    countryHint: "اختياري، رمز من حرفين.",
    regionLabel: "المنطقة / المحافظة",
    rateLabel: "النسبة",
    rateHint: "نسبة مئوية، مثلًا 14 تعني 14%.",
    appliesToShipping: "تُطبَّق على الشحن",
    pricesAlreadyInclude: "الأسعار شاملة الضريبة بالفعل",
    errPercent: "أدخل نسبة مئوية تساوي 0 أو أكثر.",
    errCountryCode: "استخدم رمز دولة من حرفين.",

    settingsTitle: "الشحن والضرائب للمتجر",
    settingsDesc: "قواعد عامة للمتجر تُطبَّق عند إتمام الطلب، قبل أي منطقة أو سعر محدد.",
    freeThreshold: "حد الشحن المجاني",
    freeThresholdHint: "الطلبات التي يساوي مجموعها الفرعي هذا المبلغ أو أكثر تُشحن مجانًا. اتركه فارغًا للتعطيل.",
    defaultRate: "سعر الشحن الافتراضي",
    defaultRateHint: "يُحصَّل عندما لا تتطابق أي منطقة أو سعر نشط. اتركه فارغًا ليصبح الشحن مجانيًا.",
    chargeTax: "تحصيل الضريبة عند إتمام الطلب",
    saveSettings: "حفظ الإعدادات",
  },
} satisfies Messages;

export type ShippingTaxStrings = Record<keyof typeof SHIPPING_TAX_STRINGS.en, string>;

export const RATE_TYPE_LABEL: Record<Locale, Record<ShippingRateType, string>> = {
  en: {
    flat: "Flat",
    weight_based: "Weight based",
    quantity_based: "Quantity based",
    order_value_based: "Order value based",
    free: "Free",
  },
  ar: {
    flat: "سعر ثابت",
    weight_based: "حسب الوزن",
    quantity_based: "حسب الكمية",
    order_value_based: "حسب قيمة الطلب",
    free: "مجاني",
  },
};
