import type { Messages } from "@/i18n/LocaleContext";

/**
 * The wording of the reports hub's «المنتجات» tab (ProductsTab.tsx and the
 * files beside this one). Egyptian Arabic, second person, short. Counted words
 * follow lib/plural.ts: `<key>_one / _two / _few / _other` (English only needs
 * `_one` and `_other`); a number is never written into a string, it comes in
 * through `{n}` and `fmt`.
 */
export const PRODUCTS_TAB_STRINGS = {
  en: {
    note: "Counted on the orders placed in the period. Stock is as it stands now.",
    deletedProduct: "A deleted product",
    openProduct: "Open the product",
    partError: "We couldn't load this right now.",
    partDenied: "This report isn't part of your role.",
    sideFailed: "Some figures didn't arrive: {parts}.",
    sideProfit: "profit",
    sideStock: "stock",
    sideCompare: "the comparison with the period before",
    listJoin: ", ",

    products_one: "1 product",
    products_other: "{n} products",
    variants_one: "1 option",
    variants_other: "{n} options",
    times_one: "once",
    times_other: "{n} times",
    outOf: "{n} in {of}",
    lessThanOutOf: "fewer than {n} in {of}",

    // KPI strip
    kpiUnits: "Pieces sold",
    kpiUnitsHint: "In the orders of this period",
    kpiSales: "Product sales",
    kpiSalesHint: "Before discounts and shipping",
    kpiListedHint: "Added up from the products in the table",
    vsYear: "vs the same days last year",
    kpiDelivery: "Products' delivery rate",
    kpiDeliveryHint: "Average of {products}; more pieces count for more",
    kpiDeliveryNone: "Nothing has shipped yet",
    kpiStock: "Out or running low",
    kpiStockHint: "At the pace of the last {days}",
    kpiStockNone: "No product has its quantity tracked",

    // The one chart
    chartProfit: "Top products by delivered profit",
    chartProfitNote: "Net profit of the period's finished orders (delivered or returned), before ad spend.",
    chartSales: "Best-selling products",
    chartSalesNote: "Sales of the orders placed in the period that weren't cancelled.",
    chartNoFinished: "No order has finished yet, so there is no profit to rank. These are sales.",
    chartEmpty: "No product sold in this period.",
    chartSummaryProfit: "Your products ranked by the profit of what was delivered",
    chartSummarySales: "Your products ranked by sales",
    coverageNone: "No delivered piece has a cost, so the profit here is higher than the truth.",
    coveragePartial: "Only {pct} of the delivered pieces have a cost, so the profit here is higher than the truth.",
    loss: "Loss",
    rank: "Number {n}",

    // The one table
    table: "Product by product",
    tableNote: "Delivery and return rates are out of the pieces that shipped.",
    tableCapped: "Showing your top {n} products by sales.",
    tableEmpty: "No product was viewed or sold in this period.",
    colProduct: "Product",
    colUnits: "Pieces",
    colSales: "Sales",
    colOrders: "Orders",
    colReturn: "Returned",
    colReturnHint: "Pieces returned or not delivered ÷ pieces shipped",
    colDelivery: "Delivered",
    colDeliveryHint: "Pieces delivered ÷ pieces shipped",
    colProfit: "Delivered profit",
    colProfitHint: "Net profit of the finished orders, before ads",
    colStock: "Stock lasts",
    colStockHint: "The first option to run out, at the pace of the last {days}",
    colViews: "Views",
    colViewsHint: "Visits that opened the product",
    colCarts: "Added to cart",
    colCartsHint: "Visits that added it to the cart, and their share of the views",
    colConversion: "Conversion",
    colConversionHint: "Orders ÷ views",
    stockOut: "Sold out",
    stockVariantOut: "An option is out",
    stockLastDay: "Less than a day",
    stockReorder: "Reorder now",
    stockSoon: "Running low",

    // The one sentence
    sayThin: "Too little sold in this period to say anything about your products. Try a longer period.",
    sayEarnProfit: "“{name}” earned you the most: {amount} of profit on what was delivered",
    sayEarnSales: "“{name}” is your best seller: {amount} in sales",
    sayReturns: "{rate} pieces of “{name}” come back, so check its description and packing",
    sayWeak: "“{name}” was viewed {views} but only {rate} visits order it, so check its price and photos",
    sayWhole: "“{name}”",
    sayVariant: "an option of “{name}”",
    sayStockDays: "{product} runs out in {days}, so reorder it now",
    sayStockLastDay: "{product} has less than a day of stock left, so reorder it now",
    sayStockOut: "{product} is sold out while it is still being ordered",
    sayCalm: "no product comes back a lot",
    sayJoin: "; ",
    sayEnd: ".",
    actStock: "Open the stock forecast",

    // «تفاصيل أكتر»
    moreFlagged: "Products that need a look",
    flaggedReturn: "{rate} pieces of “{name}” come back ({pct}). Check the description, the photos and the packing.",
    flaggedWeak: "“{name}” was viewed {views} but only {rate} visits order it (your average is {average}). Check the price, the photos and the offer.",

    moreProfit: "Profit per product",
    moreProfitNote: "Finished orders only: delivered or returned. Ad spend can't be split per product, so it isn't counted here.",
    colNet: "Net profit",
    colMargin: "Margin",
    colRevenue: "Delivered revenue",
    colCosts: "Costs",
    colCostsHint: "The product, shipping both ways and the fees",
    colDeliveredOrders: "Orders delivered",
    colReturnedOrders: "Orders returned",
    colOrderShareHint: "An order with several products is shared between them, so this is rounded",
    colMaxCpa: "Most to pay in ads per order",
    colMaxCpaHint: "The ad cost one order can carry before you lose money",
    pnlEmpty: "No finished orders in this period yet.",

    moreStock: "Out or running low",
    moreStockNote: "Worked out from sales over the last {window}.",
    colVariant: "Product and option",
    colStatus: "Status",
    colAvailable: "Available",
    colPerDay: "Sold per day",
    colDaysLeft: "Days left",
    colRunsOut: "Runs out on",
    colReorderBy: "Reorder by",
    colSuggested: "Suggested quantity",

    moreReturns: "Return requests by product",
    moreReturnsSummary: "What customers asked to send back after delivery, and why",
    moreReturnsNote: "For the orders of this period: pieces delivered, and pieces in return requests that weren't rejected. This is not the courier return rate of the table above.",
    colDeliveredUnits: "Delivered",
    colAskedBack: "Asked back",
    colRequestRate: "Share asked back",
    colReasons: "Reasons",
    high: "High",
    reason_damaged: "Damaged",
    reason_defective: "Defective",
    reason_wrong_item: "Wrong item",
    reason_not_as_described: "Not as described",
    reason_no_longer_wanted: "No longer wanted",
    reason_arrived_late: "Arrived late",
    reason_other: "Other reason",
    returnsEmpty: "Nothing was delivered or asked back in this period.",

    moreLanding: "Landing pages",
    moreLandingSummary: "The first page of each visit, and what those visits went on to buy",
    colPage: "Page",
    colSessions: "Visits",
    landingEmpty: "No visits in this period yet.",

    // Links out
    linkCollections: "Sales by collection",
    linkCollectionsHint: "Which collections sell, and what was actually delivered",
    linkOptions: "Sales by size and colour",
    linkOptionsHint: "How many of each size and colour sold, for your next supplier order",
    linkReturns: "Returns report",
    linkReturnsHint: "Why orders come back, and the products that come back most",
    linkSlow: "Slow-moving stock",
    linkSlowHint: "Products that haven't sold for a while, and the money tied up in them",
    linkValue: "Inventory value",
    linkValueHint: "What the stock on your shelves is worth at cost",
    linkInventory: "Inventory",
    linkInventoryHint: "Quantities, the stock forecast and purchase orders",
    linkCosts: "Product costs",
    linkCostsHint: "The cost, shipping and fees your profit is worked out from",
  },
  ar: {
    note: "محسوبة على الأوردرات اللي اتعملت في الفترة. المخزون على وضعه دلوقتي.",
    deletedProduct: "منتج اتمسح",
    openProduct: "افتح المنتج",
    partError: "معرفناش نجيب ده دلوقتي.",
    partDenied: "التقرير ده مش ضمن صلاحياتك.",
    sideFailed: "فيه أرقام ماجتش: {parts}.",
    sideProfit: "الأرباح",
    sideStock: "المخزون",
    sideCompare: "المقارنة بالفترة اللي قبلها",
    listJoin: "، ",

    products_one: "منتج واحد",
    products_two: "منتجين",
    products_few: "{n} منتجات",
    products_other: "{n} منتج",
    variants_one: "نوع واحد",
    variants_two: "نوعين",
    variants_few: "{n} أنواع",
    variants_other: "{n} نوع",
    times_one: "مرة واحدة",
    times_two: "مرتين",
    times_few: "{n} مرات",
    times_other: "{n} مرة",
    outOf: "{n} من كل {of}",
    lessThanOutOf: "أقل من {n} من كل {of}",

    kpiUnits: "قطع اتباعت",
    kpiUnitsHint: "في أوردرات الفترة دي",
    kpiSales: "مبيعات المنتجات",
    kpiSalesHint: "قبل الخصومات والشحن",
    kpiListedHint: "مجموع المنتجات اللي في الجدول",
    vsYear: "عن نفس الأيام السنة اللي فاتت",
    kpiDelivery: "نسبة تسليم المنتجات",
    kpiDeliveryHint: "متوسط {products}، واللي قطعه أكتر بيتحسب أكتر",
    kpiDeliveryNone: "لسه مفيش حاجة اتشحنت",
    kpiStock: "خلصت أو قرّبت تخلص",
    kpiStockHint: "على سرعة بيع آخر {days}",
    kpiStockNone: "مفيش منتج كميته متتبّعة",

    chartProfit: "أكتر المنتجات ربحاً من اللي اتسلّم",
    chartProfitNote: "صافي ربح أوردرات الفترة اللي خلصت (اتسلّمت أو رجعت)، من غير مصاريف الإعلانات.",
    chartSales: "أكتر المنتجات مبيعاً",
    chartSalesNote: "مبيعات أوردرات الفترة اللي متلغتش.",
    chartNoFinished: "لسه مفيش أوردر خلص عشان نحسب الربح. دي المبيعات.",
    chartEmpty: "مفيش منتج اتباع في الفترة دي.",
    chartSummaryProfit: "منتجاتك مرتّبة بربح اللي اتسلّم",
    chartSummarySales: "منتجاتك مرتّبة بالمبيعات",
    coverageNone: "مفيش تكلفة متسجّلة لأي قطعة اتسلّمت، فالربح هنا أعلى من الحقيقة.",
    coveragePartial: "{pct} بس من القطع اللي اتسلّمت ليها تكلفة، فالربح هنا أعلى من الحقيقة.",
    loss: "خسارة",
    rank: "رقم {n}",

    table: "منتج بمنتج",
    tableNote: "نسبة التسليم والمرتجع من القطع اللي اتشحنت.",
    tableCapped: "ظاهر أعلى {n} منتج بالمبيعات.",
    tableEmpty: "مفيش منتج اتشاف أو اتباع في الفترة دي.",
    colProduct: "المنتج",
    colUnits: "القطع",
    colSales: "المبيعات",
    colOrders: "الأوردرات",
    colReturn: "المرتجع",
    colReturnHint: "قطع رجعت أو متسلّمتش ÷ قطع اتشحنت",
    colDelivery: "اتسلّم",
    colDeliveryHint: "قطع اتسلّمت ÷ قطع اتشحنت",
    colProfit: "ربح اللي اتسلّم",
    colProfitHint: "صافي ربح الأوردرات اللي خلصت، من غير الإعلانات",
    colStock: "المخزون يكفي",
    colStockHint: "أول نوع هيخلص، على سرعة بيع آخر {days}",
    colViews: "المشاهدات",
    colViewsHint: "زيارات فتحت المنتج",
    colCarts: "أضافوا للسلة",
    colCartsHint: "زيارات حطّته في السلة، ونسبتها من المشاهدات",
    colConversion: "التحويل",
    colConversionHint: "الأوردرات ÷ المشاهدات",
    stockOut: "خلص",
    stockVariantOut: "نوع خلص",
    stockLastDay: "أقل من يوم",
    stockReorder: "اطلب دلوقتي",
    stockSoon: "قرّب يخلص",

    sayThin: "البيع في الفترة دي قليل، مش كفاية نقول حاجة عن منتجاتك. جرّب فترة أطول.",
    sayEarnProfit: "أكتر منتج كسّبك «{name}»: {amount} ربح من اللي اتسلّم",
    sayEarnSales: "أكتر منتج بيتباع «{name}»: {amount} مبيعات",
    sayReturns: "«{name}» بيرجع منه {rate}، فراجع وصفه وتغليفه",
    sayWeak: "«{name}» اتشاف {views} وبيشتريه {rate} بس، فراجع سعره وصوره",
    sayWhole: "«{name}»",
    sayVariant: "نوع من «{name}»",
    sayStockDays: "{product} هيخلص خلال {days}، فاطلبه دلوقتي",
    sayStockLastDay: "{product} باقي له أقل من يوم ويخلص، فاطلبه دلوقتي",
    sayStockOut: "{product} خلص من المخزون ولسه عليه أوردرات",
    sayCalm: "مفيش منتج بيرجع كتير",
    sayJoin: "، و",
    sayEnd: ".",
    actStock: "افتح توقّع المخزون",

    moreFlagged: "منتجات محتاجة نظرة",
    flaggedReturn: "«{name}» بيرجع منه {rate} ({pct}). راجع الوصف والصور والتغليف.",
    flaggedWeak: "«{name}» اتشاف {views} وبيشتريه {rate} بس (المتوسط عندك {average}). راجع السعر والصور والعرض.",

    moreProfit: "ربح كل منتج",
    moreProfitNote: "الأوردرات اللي خلصت بس: اتسلّمت أو رجعت. مصاريف الإعلانات مبتتوزّعش على المنتجات، فمش محسوبة هنا.",
    colNet: "صافي الربح",
    colMargin: "الهامش",
    colRevenue: "إيراد اللي اتسلّم",
    colCosts: "التكاليف",
    colCostsHint: "المنتج والشحن رايح جاي والرسوم",
    colDeliveredOrders: "أوردرات اتسلّمت",
    colReturnedOrders: "أوردرات رجعت",
    colOrderShareHint: "الأوردر اللي فيه كذا منتج بيتقسم عليهم، فالرقم متقرّب",
    colMaxCpa: "أقصى تكلفة إعلان للأوردر",
    colMaxCpaHint: "تدفع في الإعلان لحد كده للأوردر قبل ما تخسر",
    pnlEmpty: "لسه مفيش أوردرات خلصت في الفترة دي.",

    moreStock: "خلص أو قرّب يخلص",
    moreStockNote: "محسوب على بيع آخر {window}.",
    colVariant: "المنتج والنوع",
    colStatus: "الحالة",
    colAvailable: "المتاح",
    colPerDay: "بيتباع في اليوم",
    colDaysLeft: "يكفي كام يوم",
    colRunsOut: "هيخلص يوم",
    colReorderBy: "اطلب قبل",
    colSuggested: "الكمية المقترحة",

    moreReturns: "طلبات الإرجاع حسب المنتج",
    moreReturnsSummary: "اللي العملاء طلبوا يرجّعوه بعد الاستلام، وليه",
    moreReturnsNote: "لأوردرات الفترة دي: القطع اللي اتسلّمت، والقطع اللي في طلبات إرجاع ما اترفضتش. دي غير نسبة مرتجع الشحن اللي في الجدول فوق.",
    colDeliveredUnits: "اتسلّم",
    colAskedBack: "اتطلب إرجاعه",
    colRequestRate: "نسبة طلبات الإرجاع",
    colReasons: "الأسباب",
    high: "عالية",
    reason_damaged: "تالف",
    reason_defective: "عيب صناعة",
    reason_wrong_item: "منتج غلط",
    reason_not_as_described: "مش زي الوصف",
    reason_no_longer_wanted: "مبقاش عايزه",
    reason_arrived_late: "اتأخر",
    reason_other: "سبب تاني",
    returnsEmpty: "مفيش حاجة اتسلّمت أو اتطلب إرجاعها في الفترة دي.",

    moreLanding: "صفحات الهبوط",
    moreLandingSummary: "أول صفحة في كل زيارة، والزيارات دي اشترت إيه",
    colPage: "الصفحة",
    colSessions: "الزيارات",
    landingEmpty: "مفيش زيارات في الفترة دي لسه.",

    linkCollections: "المبيعات حسب المجموعة",
    linkCollectionsHint: "أنهي مجموعة بتبيع، وإيه اللي اتسلّم فعلاً",
    linkOptions: "المبيعات حسب المقاس واللون",
    linkOptionsHint: "اتباع كام من كل مقاس ولون، عشان طلبيتك الجاية من المورّد",
    linkReturns: "تقرير المرتجعات",
    linkReturnsHint: "الأوردرات بترجع ليه، وأكتر منتجات بترجع",
    linkSlow: "البضاعة الراكدة",
    linkSlowHint: "منتجات بقالها فترة مش بتتباع، والفلوس المحبوسة فيها",
    linkValue: "قيمة المخزون",
    linkValueHint: "البضاعة اللي على الرف تساوي كام بسعر التكلفة",
    linkInventory: "المخزون",
    linkInventoryHint: "الكميات، وتوقّع اللي هيخلص، وأوامر الشراء",
    linkCosts: "تكاليف المنتجات",
    linkCostsHint: "سعر التكلفة والشحن والرسوم اللي الربح بيتحسب بيها",
  },
} satisfies Messages;

export type ProductsTabStrings = (typeof PRODUCTS_TAB_STRINGS)["en"];
