import type { ProductQuestionStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Product questions and answers (handoff 212): the inbox, a question's row, its preview, the answer sheet and the product page's section. */
export const QUESTION_STRINGS = {
  en: {
    title: "Questions",
    description: "Shoppers ask on the product page. Nothing appears in your store until you answer and publish it.",
    pendingBadge: "{count} waiting",
    filterLabel: "Questions by status",
    tabPending: "Waiting for an answer",
    tabPublished: "Published",
    tabHidden: "Hidden",
    tabAll: "All",
    status_pending: "Waiting for an answer",
    status_published: "Published",
    status_hidden: "Hidden",
    colQuestion: "Question",
    colStatus: "Status",
    colAge: "Asked",
    colAction: "Next step",
    emptyPending: "No questions are waiting for an answer",
    emptyPendingBody: "A new question lands here first. It shows on the product's page once you answer it.",
    emptyPublished: "No published answers yet",
    emptyHidden: "No hidden questions",
    emptyAll: "No questions yet",
    emptyAllBody: "A question arrives when a shopper asks on a product's page. Answer it and it shows there for everyone.",
    seeAll: "See all questions",
    unknownProduct: "Deleted product",
    anonymous: "A shopper",
    emailPrivate: "Private — only your team sees this email",
    willEmail: "Your answer will be emailed to them once, when you publish it.",
    answer: "Answer",
    editAnswer: "Edit answer",
    answerTitle: "Answer the question",
    editTitle: "Edit your answer",
    answerLabel: "Your answer",
    answerPlaceholder: "Write the answer shoppers will read on the product page…",
    answerHint: "Shown under the question on the product's page.",
    publish: "Publish",
    publishing: "Publishing…",
    saveAnswer: "Save answer",
    saving: "Saving…",
    hide: "Hide",
    publishAgain: "Publish again",
    remove: "Delete",
    removeThis: "Delete this question",
    answerRequired: "Write an answer first: a question is published with its answer.",
    answeredOn: "Answered {date}",
    askedWhen: "Asked {when}",
    theQuestion: "The question",
    noAnswerYet: "Not answered yet.",
    whoAsked: "Who asked",
    hintPending: "Answer it and it shows on the product's page. Hide it and nobody sees it.",
    hintPublished: "Shoppers see this question and your answer on the product's page.",
    hintHidden: "Hidden: shoppers don't see this question.",
    peek: "Preview the question from {who}",
    menuLabel: "Actions for this question",
    menuPeek: "Quick look",
    menuProduct: "Open the product",
    openProduct: "Open the product",
    openProducts: "Open the products",
    toastPublished: "Published — it's on the product page now.",
    toastSaved: "Answer saved.",
    toastHidden: "Hidden — it's off the product page.",
    toastDeleted: "Question deleted.",
    deleteTitle: "Delete this question?",
    deleteBody: "It's removed for good, with its answer.",
    deleting: "Deleting…",
    cancel: "Cancel",
    productTitle: "Questions",
    productHint: "What shoppers asked about this product. An answer shows on its page once published.",
    productEmpty: "No one has asked about this product yet",
    productEmptyBody: "When a shopper asks on this product's page, the question lands here.",
    openInbox: "All questions",
  },
  ar: {
    title: "الأسئلة",
    description: "العملاء بيسألوا من صفحة المنتج. مفيش حاجة بتظهر في متجرك غير لما ترد وتنشر.",
    pendingBadge: "{count} مستني رد",
    filterLabel: "الأسئلة حسب الحالة",
    tabPending: "مستنية رد",
    tabPublished: "منشورة",
    tabHidden: "مخفية",
    tabAll: "الكل",
    status_pending: "مستني رد",
    status_published: "منشور",
    status_hidden: "مخفي",
    colQuestion: "السؤال",
    colStatus: "الحالة",
    colAge: "اتسأل",
    colAction: "الخطوة الجاية",
    emptyPending: "مفيش أسئلة مستنية رد",
    emptyPendingBody: "أي سؤال جديد بييجي هنا الأول، وبيظهر في صفحة المنتج بعد ما ترد عليه.",
    emptyPublished: "مفيش ردود منشورة لسه",
    emptyHidden: "مفيش أسئلة مخفية",
    emptyAll: "مفيش أسئلة لسه",
    emptyAllBody: "السؤال بيوصل لما عميل يسأل من صفحة منتج. رد عليه وهيظهر هناك لكل الناس.",
    seeAll: "شوف كل الأسئلة",
    unknownProduct: "منتج ممسوح",
    anonymous: "عميل",
    emailPrivate: "خاص — فريقك بس اللي بيشوف الإيميل ده",
    willEmail: "ردّك هيتبعتله على الإيميل مرة واحدة لما تنشره.",
    answer: "رُد",
    editAnswer: "عدّل الرد",
    answerTitle: "رُد على السؤال",
    editTitle: "عدّل ردّك",
    answerLabel: "ردّك",
    answerPlaceholder: "اكتب الرد اللي العملاء هيقروه في صفحة المنتج…",
    answerHint: "بيظهر تحت السؤال في صفحة المنتج.",
    publish: "انشر",
    publishing: "بننشر…",
    saveAnswer: "احفظ الرد",
    saving: "بنحفظ…",
    hide: "اخفي",
    publishAgain: "انشره تاني",
    remove: "امسح",
    removeThis: "امسح السؤال ده",
    answerRequired: "اكتب الرد الأول: السؤال بيتنشر مع ردّه.",
    answeredOn: "اترد عليه {date}",
    askedWhen: "اتسأل {when}",
    theQuestion: "السؤال",
    noAnswerYet: "لسه ما اتردّش عليه.",
    whoAsked: "مين سأل",
    hintPending: "رد عليه وهيظهر في صفحة المنتج. اخفيه ومحدش هيشوفه.",
    hintPublished: "العملاء بيشوفوا السؤال ده وردّك في صفحة المنتج.",
    hintHidden: "مخفي: العملاء مش بيشوفوا السؤال ده.",
    peek: "معاينة سؤال {who}",
    menuLabel: "إجراءات السؤال",
    menuPeek: "معاينة سريعة",
    menuProduct: "افتح المنتج",
    openProduct: "افتح المنتج",
    openProducts: "افتح المنتجات",
    toastPublished: "اتنشر — بقى ظاهر في صفحة المنتج.",
    toastSaved: "الرد اتحفظ.",
    toastHidden: "اتخفى — مبقاش ظاهر في صفحة المنتج.",
    toastDeleted: "السؤال اتمسح.",
    deleteTitle: "تمسح السؤال ده؟",
    deleteBody: "هيتمسح نهائي هو والرد بتاعه.",
    deleting: "بنمسح…",
    cancel: "إلغاء",
    productTitle: "أسئلة",
    productHint: "اللي العملاء سألوه عن المنتج ده. الرد بيظهر في صفحته بعد ما يتنشر.",
    productEmpty: "محدش سأل عن المنتج ده لسه",
    productEmptyBody: "لما عميل يسأل من صفحة المنتج ده، السؤال هييجي هنا.",
    openInbox: "كل الأسئلة",
  },
} satisfies Messages;

export type QuestionWords = Record<keyof (typeof QUESTION_STRINGS)["en"], string>;

export const QUESTION_STATUS_TONE: Record<ProductQuestionStatus, "warning" | "success" | "neutral"> = {
  pending: "warning",
  published: "success",
  hidden: "neutral",
};
