import type { ProductQuestionStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Product questions and answers: the inbox, a question's row, its preview, the answer sheet and the product page's section. */
export const QUESTION_STRINGS = {
  en: {
    title: "Questions",
    description: "Shoppers ask on the product page. Nothing appears in your store until you answer and publish it.",
    pendingBadge: "{count} waiting",
    filterLabel: "Questions by status",
    tabPending: "Waiting for an answer",
    tabPublished: "Published",
    tabHidden: "Hidden",
    tabAll: "All",
    status_pending: "Waiting for an answer",
    status_published: "Published",
    status_hidden: "Hidden",
    colQuestion: "Question",
    colStatus: "Status",
    colAge: "Asked",
    colAction: "Next step",
    emptyPending: "No questions are waiting for an answer",
    emptyPendingBody: "A new question lands here first. It shows on the product's page once you answer it.",
    emptyPublished: "No published answers yet",
    emptyHidden: "No hidden questions",
    emptyAll: "No questions yet",
    emptyAllBody: "A question arrives when a shopper asks on a product's page. Answer it and it shows there for everyone.",
    seeAll: "See all questions",
    unknownProduct: "Deleted product",
    anonymous: "A shopper",
    emailPrivate: "Private — only your team sees this email",
    willEmail: "Your answer will be emailed to them once, when you publish it.",
    answer: "Answer",
    editAnswer: "Edit answer",
    answerTitle: "Answer the question",
    editTitle: "Edit your answer",
    answerLabel: "Your answer",
    answerPlaceholder: "Write the answer shoppers will read on the product page…",
    answerHint: "Shown under the question on the product's page.",
    publish: "Publish",
    publishing: "Publishing…",
    saveAnswer: "Save answer",
    saving: "Saving…",
    hide: "Hide",
    publishAgain: "Publish again",
    remove: "Delete",
    removeThis: "Delete this question",
    answerRequired: "Write an answer first: a question is published with its answer.",
    answeredOn: "Answered {date}",
    askedWhen: "Asked {when}",
    theQuestion: "The question",
    noAnswerYet: "Not answered yet.",
    whoAsked: "Who asked",
    hintPending: "Answer it and it shows on the product's page. Hide it and nobody sees it.",
    hintPublished: "Shoppers see this question and your answer on the product's page.",
    hintHidden: "Hidden: shoppers don't see this question.",
    peek: "Preview the question from {who}",
    menuLabel: "Actions for this question",
    menuPeek: "Quick look",
    menuProduct: "Open the product",
    openProduct: "Open the product",
    openProducts: "Open the products",
    toastPublished: "Published — it's on the product page now.",
    toastSaved: "Answer saved.",
    toastHidden: "Hidden — it's off the product page.",
    toastDeleted: "Question deleted.",
    deleteTitle: "Delete this question?",
    deleteBody: "It's removed for good, with its answer.",
    deleting: "Deleting…",
    cancel: "Cancel",
    productTitle: "Questions",
    productHint: "What shoppers asked about this product. An answer shows on its page once published.",
    productEmpty: "No one has asked about this product yet",
    productEmptyBody: "When a shopper asks on this product's page, the question lands here.",
    openInbox: "All questions",
  },
  ar: {
    title: "الأسئلة",
    description: "يسأل العملاء من صفحة المنتج. لا يظهر شيء في متجرك حتى تجيب وتنشر.",
    pendingBadge: "{count} بانتظار الرد",
    filterLabel: "الأسئلة حسب الحالة",
    tabPending: "بانتظار الرد",
    tabPublished: "منشورة",
    tabHidden: "مخفية",
    tabAll: "الكل",
    status_pending: "بانتظار الرد",
    status_published: "منشور",
    status_hidden: "مخفي",
    colQuestion: "السؤال",
    colStatus: "الحالة",
    colAge: "وقت السؤال",
    colAction: "الخطوة التالية",
    emptyPending: "لا توجد أسئلة بانتظار الرد",
    emptyPendingBody: "كل سؤال جديد يصل إلى هنا أولًا، ويظهر في صفحة المنتج بعد أن تجيب عنه.",
    emptyPublished: "لا توجد إجابات منشورة بعد",
    emptyHidden: "لا توجد أسئلة مخفية",
    emptyAll: "لا توجد أسئلة بعد",
    emptyAllBody: "يصل السؤال عندما يسأل عميل من صفحة منتج. أجب عنه وسيظهر هناك للجميع.",
    seeAll: "عرض كل الأسئلة",
    unknownProduct: "منتج محذوف",
    anonymous: "عميل",
    emailPrivate: "خاص — يرى فريقك فقط هذا البريد الإلكتروني",
    willEmail: "ستُرسل إجابتك إلى بريده الإلكتروني مرة واحدة عند نشرها.",
    answer: "إجابة",
    editAnswer: "تعديل الإجابة",
    answerTitle: "الإجابة عن السؤال",
    editTitle: "تعديل إجابتك",
    answerLabel: "إجابتك",
    answerPlaceholder: "اكتب الإجابة التي سيقرؤها العملاء في صفحة المنتج…",
    answerHint: "تظهر تحت السؤال في صفحة المنتج.",
    publish: "نشر",
    publishing: "جارٍ النشر…",
    saveAnswer: "حفظ الإجابة",
    saving: "جارٍ الحفظ…",
    hide: "إخفاء",
    publishAgain: "نشره مرة أخرى",
    remove: "حذف",
    removeThis: "حذف هذا السؤال",
    answerRequired: "اكتب الإجابة أولًا: يُنشر السؤال مع إجابته.",
    answeredOn: "أُجيب عنه {date}",
    askedWhen: "سُئل {when}",
    theQuestion: "السؤال",
    noAnswerYet: "لم يُجَب عنه بعد.",
    whoAsked: "صاحب السؤال",
    hintPending: "أجب عنه وسيظهر في صفحة المنتج. أخفِه ولن يراه أحد.",
    hintPublished: "يرى العملاء هذا السؤال وإجابتك في صفحة المنتج.",
    hintHidden: "مخفي: لا يرى العملاء هذا السؤال.",
    peek: "معاينة سؤال {who}",
    menuLabel: "إجراءات السؤال",
    menuPeek: "معاينة سريعة",
    menuProduct: "فتح المنتج",
    openProduct: "فتح المنتج",
    openProducts: "فتح المنتجات",
    toastPublished: "تم النشر — أصبح ظاهرًا في صفحة المنتج.",
    toastSaved: "تم حفظ الإجابة.",
    toastHidden: "تم الإخفاء — لم يعد ظاهرًا في صفحة المنتج.",
    toastDeleted: "تم حذف السؤال.",
    deleteTitle: "هل تريد حذف هذا السؤال؟",
    deleteBody: "سيُحذف نهائيًا مع إجابته.",
    deleting: "جارٍ الحذف…",
    cancel: "إلغاء",
    productTitle: "أسئلة",
    productHint: "ما سأله العملاء عن هذا المنتج. تظهر الإجابة في صفحته بعد نشرها.",
    productEmpty: "لم يسأل أحد عن هذا المنتج بعد",
    productEmptyBody: "عندما يسأل عميل من صفحة هذا المنتج، سيصل السؤال إلى هنا.",
    openInbox: "كل الأسئلة",
  },
} satisfies Messages;

export type QuestionWords = Record<keyof (typeof QUESTION_STRINGS)["en"], string>;

export const QUESTION_STATUS_TONE: Record<ProductQuestionStatus, "warning" | "success" | "neutral"> = {
  pending: "warning",
  published: "success",
  hidden: "neutral",
};
