import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the editor's shell: the toolbar, the two side panels, the
 * phone's bars and sheets, autosave, publish, the published versions and the
 * first-run steps. The shared pieces (inspector, library, look panel) keep
 * their own words in editorLocale.ts; these are read with `useT`, which in the
 * website editor is the same language (WebsiteEditorPage sets both).
 *
 * Counted words come in the plural forms lib/plural.ts reads (`pages_one`,
 * `pages_two`, `pages_few`, `pages_other`); English only uses two of them.
 */
export const SHELL_STRINGS = {
  en: {
    // --- toolbar ---
    toolbar: "Editor toolbar",
    back: "Back to your sites",
    statusPublished: "Published",
    statusDraft: "Draft",
    statusChanged: "Unpublished changes",
    statusSuspended: "Suspended",
    pageSwitcher: "Switch page: {name}",
    pagesTitle: "Pages",
    newPage: "New page",
    device: "Preview size",
    devicePhone: "Phone",
    deviceTablet: "Tablet",
    deviceDesktop: "Desktop",
    undo: "Undo",
    redo: "Redo",
    saveIdle: "All saved",
    saveSaved: "Saved just now",
    saveSaving: "Saving…",
    saveFailed: "Not saved — try again",
    saveShortIdle: "Saved",
    saveShortSaved: "Saved",
    saveShortSaving: "Saving…",
    saveShortFailed: "Not saved",
    more: "More",
    publish: "Publish",
    showSectionsPanel: "Show the sections panel",
    hideSectionsPanel: "Hide the sections panel",
    showEditPanel: "Show the editing panel",
    hideEditPanel: "Hide the editing panel",

    // --- the «…» menu ---
    menuPageSettings: "Page settings (SEO, scripts)",
    menuHistory: "Published versions",
    menuLiveStore: "Open your live store",
    menuStoreLook: "Store look",
    menuDark: "Preview in dark mode",
    menuLight: "Preview in light mode",
    menuXrayOn: "Show outlines",
    menuXrayOff: "Hide outlines",
    menuRefresh: "Reload the preview",

    // --- panels ---
    startPanel: "Sections and pages",
    endPanel: "Editing panel",
    tabSections: "Sections",
    tabPages: "Pages",
    panelTabs: "What the panel shows",
    addSection: "Add a section",
    lookTitle: "Store look",
    lookHint: "Tap anything in the store to edit it.",
    pageInfo: "This page",
    pagePath: "Address",

    // --- the phone ---
    dock: "Editing tools",
    dockSections: "Sections",
    dockAdd: "Add section",
    dockLook: "Look",
    dockEdit: "Edit: {name}",
    sectionsSheet: "Page sections",
    editSheet: "Edit",
    sheetGrow: "Make the panel taller",
    sheetShrink: "Make the panel shorter",
    sheetHide: "Put the panel away",

    // --- the look bar ---
    lookBar: "Look changes go live at once — save them?",
    lookSave: "Save the look",
    lookSaving: "Saving the look…",
    lookRevert: "Undo them",

    // --- saving ---
    saveErrorTitle: "Your last changes aren't saved yet.",
    retry: "Try again",
    leaveTitle: "Leave without saving?",
    leavePageBody: "Your last changes to this page couldn't be saved. If you leave now they are lost.",
    leaveLookBody: "Your look changes aren't saved. If you leave now they are lost.",
    leaveConfirm: "Leave",
    switchBody: "Your last changes to this page couldn't be saved. If you switch pages they are lost.",
    switchConfirm: "Switch page",

    // --- section actions ---
    sectionDeleted: "“{name}” deleted",
    sectionHidden: "“{name}” is hidden from your store",
    pickImage: "Choose a picture",

    // --- publish ---
    publishTitle: "Publish your site",
    publishFirst: "First publish: every page of the site goes live for your customers.",
    publishWhat: "What changes in your store",
    publishNothing: "No page content changed since the last publish.",
    publishAll: "Publishing puts every page live as it is now.",
    publishSeoNote: "A page's title and search settings go live with the publish too.",
    pageChanged: "Edited",
    pageNew: "New",
    removedPages_one: "1 deleted page leaves your store.",
    removedPages_two: "{n} deleted pages leave your store.",
    removedPages_few: "{n} deleted pages leave your store.",
    removedPages_other: "{n} deleted pages leave your store.",
    pages_one: "1 page",
    pages_two: "{n} pages",
    pages_few: "{n} pages",
    pages_other: "{n} pages",
    problemsTitle: "Fix these before publishing",
    problemNoHome: "The site has no home page at the address “/”. Add one.",
    problemEmpty: "This page is empty. Add a section with something in it.",
    openPage: "Open the page",
    lookPending: "Your look changes aren't saved yet — publishing doesn't include them.",
    checking: "Saving your last changes…",
    publishNow: "Publish now",
    publishing: "Publishing…",
    cancel: "Cancel",
    publishedToast: "Published — version {n} is live for your customers.",
    viewStore: "See your store",
    publishSaveFailed: "We couldn't save your last changes, so nothing was published. Try again.",

    // --- published versions ---
    historyTitle: "Published versions",
    historyHint: "Every publish keeps a version. You can put any of them back in front of your customers.",
    revision: "Version {n}",
    liveNow: "Live now",
    byYou: "You published it",
    byTeam: "Someone on your team published it",
    restore: "Restore this version",
    restoreTitle: "Restore version {n}?",
    restoreBody:
      "Your customers see this version at once. The draft you are editing does not change, and the store look (colours, header, footer) does not go back with it.",
    restoreConfirm: "Restore it",
    restoring: "Restoring…",
    restored: "Version {n} is live for your customers.",
    historyEmpty: "You haven't published this site yet. Your first publish shows up here.",
    keep: "Keep the current one",

    // --- first run ---
    guide: "Your first steps",
    guideTemplate: "Pick a template",
    guideBrand: "Make it yours",
    guidePublish: "Publish",
    guideDone: "done",
    guideDismiss: "Hide the steps",
    brandHint: "Pick a ready style and watch your store change. You can fine-tune the colours after.",
    brandMore: "All look settings",
  },
  ar: {
    // --- toolbar ---
    toolbar: "شريط المحرر",
    back: "رجوع للمواقع",
    statusPublished: "منشور",
    statusDraft: "مسودة",
    statusChanged: "فيه تغييرات ما اتنشرتش",
    statusSuspended: "موقوف",
    pageSwitcher: "غيّر الصفحة: {name}",
    pagesTitle: "الصفحات",
    newPage: "صفحة جديدة",
    device: "حجم المعاينة",
    devicePhone: "موبايل",
    deviceTablet: "تابلت",
    deviceDesktop: "كمبيوتر",
    undo: "تراجع",
    redo: "رجّع اللي اتراجعت عنه",
    saveIdle: "كله محفوظ",
    saveSaved: "اتحفظ من شوية",
    saveSaving: "بيحفظ…",
    saveFailed: "ما اتحفظش — جرّب تاني",
    saveShortIdle: "محفوظ",
    saveShortSaved: "اتحفظ",
    saveShortSaving: "بيحفظ…",
    saveShortFailed: "ما اتحفظش",
    more: "المزيد",
    publish: "انشر",
    showSectionsPanel: "اظهر لوحة الأقسام",
    hideSectionsPanel: "اخفي لوحة الأقسام",
    showEditPanel: "اظهر لوحة التعديل",
    hideEditPanel: "اخفي لوحة التعديل",

    // --- the «…» menu ---
    menuPageSettings: "إعدادات الصفحة (SEO وسكربتات)",
    menuHistory: "النسخ اللي اتنشرت",
    menuLiveStore: "افتح متجرك المنشور",
    menuStoreLook: "شكل المتجر",
    menuDark: "شوف المعاينة غامق",
    menuLight: "شوف المعاينة فاتح",
    menuXrayOn: "اظهر حدود العناصر",
    menuXrayOff: "اخفي حدود العناصر",
    menuRefresh: "حدّث المعاينة",

    // --- panels ---
    startPanel: "الأقسام والصفحات",
    endPanel: "لوحة التعديل",
    tabSections: "الأقسام",
    tabPages: "الصفحات",
    panelTabs: "اللوحة بتعرض إيه",
    addSection: "ضيف قسم",
    lookTitle: "شكل المتجر",
    lookHint: "اضغط على أي حاجة في المتجر عشان تعدّلها.",
    pageInfo: "الصفحة دي",
    pagePath: "العنوان",

    // --- the phone ---
    dock: "أدوات التعديل",
    dockSections: "الأقسام",
    dockAdd: "ضيف قسم",
    dockLook: "الشكل",
    dockEdit: "عدّل: {name}",
    sectionsSheet: "أقسام الصفحة",
    editSheet: "تعديل",
    sheetGrow: "كبّر اللوحة",
    sheetShrink: "صغّر اللوحة",
    sheetHide: "نزّل اللوحة",

    // --- the look bar ---
    lookBar: "تغييرات الشكل بتتنشر على طول — احفظها؟",
    lookSave: "احفظ الشكل",
    lookSaving: "بيحفظ الشكل…",
    lookRevert: "تراجع",

    // --- saving ---
    saveErrorTitle: "آخر تعديلاتك لسه ما اتحفظتش.",
    retry: "جرّب تاني",
    leaveTitle: "تخرج من غير ما تحفظ؟",
    leavePageBody: "آخر تعديلاتك في الصفحة دي ما اتحفظتش. لو خرجت دلوقتي هتضيع.",
    leaveLookBody: "تغييرات الشكل لسه ما اتحفظتش. لو خرجت دلوقتي هتضيع.",
    leaveConfirm: "اخرج",
    switchBody: "آخر تعديلاتك في الصفحة دي ما اتحفظتش. لو غيّرت الصفحة هتضيع.",
    switchConfirm: "غيّر الصفحة",

    // --- section actions ---
    sectionDeleted: "اتمسح «{name}»",
    sectionHidden: "«{name}» اتخفى من متجرك",
    pickImage: "اختار صورة",

    // --- publish ---
    publishTitle: "انشر الموقع",
    publishFirst: "أول نشر: كل صفحات الموقع هتبقى قدام عملائك.",
    publishWhat: "اللي هيتغيّر في متجرك",
    publishNothing: "مفيش تعديل في محتوى الصفحات من آخر نشر.",
    publishAll: "النشر بينزّل كل صفحات الموقع زي ما هي دلوقتي.",
    publishSeoNote: "عنوان الصفحة وإعدادات البحث بينزلوا مع النشر كمان.",
    pageChanged: "اتعدّلت",
    pageNew: "جديدة",
    removedPages_one: "صفحة واحدة اتمسحت وهتختفي من متجرك.",
    removedPages_two: "صفحتين اتمسحوا وهيختفوا من متجرك.",
    removedPages_few: "{n} صفحات اتمسحت وهتختفي من متجرك.",
    removedPages_other: "{n} صفحة اتمسحت وهتختفي من متجرك.",
    pages_one: "صفحة واحدة",
    pages_two: "صفحتين",
    pages_few: "{n} صفحات",
    pages_other: "{n} صفحة",
    problemsTitle: "صلّح دول قبل النشر",
    problemNoHome: "الموقع مالوش صفحة رئيسية على العنوان «/». ضيف واحدة.",
    problemEmpty: "الصفحة دي فاضية. ضيف قسم فيه محتوى.",
    openPage: "افتح الصفحة",
    lookPending: "تغييرات الشكل لسه ما اتحفظتش — النشر مش هينزّلها.",
    checking: "بنحفظ آخر تعديلاتك…",
    publishNow: "انشر دلوقتي",
    publishing: "بينشر…",
    cancel: "إلغاء",
    publishedToast: "اتنشر — النسخة {n} بقت قدام عملائك.",
    viewStore: "شوف متجرك",
    publishSaveFailed: "معرفناش نحفظ آخر تعديلاتك، فما نشرناش حاجة. جرّب تاني.",

    // --- published versions ---
    historyTitle: "النسخ اللي اتنشرت",
    historyHint: "كل مرة بتنشر بنحتفظ بنسخة. تقدر ترجّع أي واحدة قدام عملائك.",
    revision: "نسخة {n}",
    liveNow: "قدام العملاء دلوقتي",
    byYou: "أنت اللي نشرتها",
    byTeam: "حد من فريقك نشرها",
    restore: "رجّع النسخة دي",
    restoreTitle: "ترجّع النسخة {n}؟",
    restoreBody:
      "عملاءك هيشوفوا النسخة دي على طول. المسودة اللي بتعدّل فيها مش هتتغيّر، وشكل المتجر (الألوان والهيدر والفوتر) مش بيرجع معاها.",
    restoreConfirm: "رجّعها",
    restoring: "بنرجّعها…",
    restored: "النسخة {n} بقت قدام عملائك.",
    historyEmpty: "لسه ما نشرتش الموقع ده. أول نشر هيظهر هنا.",
    keep: "خلّي الحالية",

    // --- first run ---
    guide: "أول خطواتك",
    guideTemplate: "اختار القالب",
    guideBrand: "لوّنه بهويتك",
    guidePublish: "انشر",
    guideDone: "خلصت",
    guideDismiss: "اخفي الخطوات",
    brandHint: "اختار شكل جاهز وشوف متجرك بيتغيّر. وبعدين ظبّط الألوان براحتك.",
    brandMore: "كل إعدادات الشكل",
  },
} satisfies Messages;

export type ShellStrings = Record<keyof (typeof SHELL_STRINGS)["en"], string>;
