import type { Messages } from "@/i18n/LocaleContext";

/**
 * Inventory → Locations, a location's stock, Transfer stock; the product
 * page's "Stock by location" and the order page's "Ships from" (handoff 206).
 * Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const INVENTORY_STRINGS = {
  en: {
    // hub
    pageTitle: "Inventory",
    pageDescription: "Where your stock is kept, what is on its way from suppliers, and counting what is on the shelf.",
    tabsLabel: "Inventory sections",
    tab_locations: "Locations",
    tab_transfers: "Transfer stock",
    tab_purchaseOrders: "Purchase orders",
    tab_suppliers: "Suppliers",
    tab_stockCounts: "Stock counts",
    tab_forecast: "Stock forecast",
    tab_lots: "Lots & expiry",
    tab_movements: "Stock movements",
    // locations list
    locationsTitle: "Locations",
    locationsDescription:
      "Warehouses and shops, each with its own stock. The store still sells from the total; the default location holds whatever the others don't.",
    addLocation: "Add location",
    transferStock: "Transfer stock",
    openInventory: "Open inventory",
    colLocation: "Location",
    colUnits: "Units",
    colPriority: "Shipping priority",
    colActive: "Active",
    colActions: "Actions",
    defaultBadge: "Default",
    inactiveBadge: "Off",
    activeFor: "{name} is active",
    defaultAlwaysOn: "The default location can't be switched off.",
    edit: "Edit",
    makeDefault: "Make default",
    delete: "Delete",
    emptyTitle: "No locations yet",
    emptyHint: "Add your first warehouse or shop. It's free, it becomes the default, and all the stock you have now is counted there.",
    viewOnlyHint: "Your role can see the stock but not change it.",
    turnedOn: "{name} is on.",
    turnedOff: "{name} is off. New orders won't be assigned to it.",
    // upgrade
    upgradeTitle: "Your plan has one location",
    upgradeBody: "To split your stock across more warehouses or shops, move to a plan with multiple warehouses.",
    upgradeLink: "See plans",
    upgradeAskOwner: "Ask the store owner to upgrade the plan.",
    planRefused: "Your plan has one location. Upgrade the plan to add another.",
    tooMany: "A store can have 50 locations at most.",
    // add / edit dialog
    addTitle: "New location",
    editTitle: "Edit location",
    dialogDescription: "A warehouse, a shop or anywhere else you keep stock.",
    name: "Name",
    namePlaceholder: "Main warehouse",
    nameError: "Enter a name for the location.",
    address: "Address (optional)",
    priority: "Shipping priority",
    priorityHint: "A new order ships from the first active location that has all of its items. The lower number goes first (0–1000).",
    priorityError: "Enter a whole number from 0 to 1000.",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    created: "Location added.",
    createdFirst: "Location added. It is the default, and all your stock is counted there.",
    saved: "Location saved.",
    // make default
    makeDefaultTitle: "Make {name} the default?",
    makeDefaultBody:
      "Every location keeps the units it has now. From now on {name} holds whatever the other locations don't, and orders no other location can fill ship from it.",
    makeDefaultConfirm: "Make default",
    madeDefault: "{name} is now the default location.",
    working: "Working…",
    // delete
    deleteTitle: "Delete {name}?",
    deleteBody: "Orders assigned to it go back to the default location, and its open stock counts are cancelled.",
    deleteConfirm: "Delete location",
    deleted: "Location deleted.",
    deleteHasStock: "This location still has stock. Transfer it to another location first.",
    deleteIsDefault: "This is the default location. Make another one the default first.",
    // location page
    back: "Locations",
    locationFallback: "Location",
    priorityLine: "Shipping priority {n}",
    searchLabel: "Search this location's stock",
    searchPlaceholder: "Product name",
    clearSearch: "Clear search",
    colProduct: "Product",
    colOnHand: "On hand",
    colReserved: "Reserved",
    colAvailable: "Available",
    adjust: "Receive / write off",
    adjustFor: "Receive or write off {name}",
    needsTransfer: "Needs a transfer",
    needsTransferBanner_one: "One product has more units reserved here than on hand. Transfer stock in from another location.",
    needsTransferBanner_other: "{n} products have more units reserved here than on hand. Transfer stock in from another location.",
    stockEmptyTitle: "No products yet",
    stockEmptyHint: "Once you add products, their stock at this location shows here.",
    noMatchTitle: "No product matches",
    noMatchHint: "The search looks at product names.",
    showAll: "Show all products",
    firstRows: "Showing the first {n} variants. Search by product name to find the rest.",
    singleVariant: "One variant",
    unknownProduct: "Deleted product",
    // adjust dialog
    adjustTitle: "Receive / write off",
    adjustDescription: "The store's total moves with it, and the change is written in the stock history.",
    adjustModeLabel: "What happened",
    modeReceive: "Receive",
    modeWriteOff: "Write off",
    quantity: "Quantity",
    quantityError: "Enter a whole number above zero.",
    writeOffTooMany: "Only {n} on hand here.",
    reason: "Reason",
    reasonReceivePlaceholder: "New delivery",
    reasonWriteOffPlaceholder: "Damaged in storage",
    reasonError: "Write a short reason.",
    onHandNow: "On hand here now",
    onHandAfter: "After this",
    adjustSubmitReceive: "Receive stock",
    adjustSubmitWriteOff: "Write off stock",
    adjusted: "Stock updated.",
    insufficient: "There aren't enough units here for this.",
    // transfers
    transferTitle: "Transfer stock",
    transferDescription: "Move units from one location to another. The store's total doesn't change.",
    from: "From",
    to: "To",
    choose: "Choose…",
    sameLocation: "Choose two different locations.",
    addProduct: "Add a product",
    product: "Product",
    variant: "Variant",
    chooseProduct: "Choose a product…",
    add: "Add",
    searchProducts: "Search products",
    pickerLoading: "Loading products…",
    pickerFailed: "Couldn't load the products.",
    pickerEmpty: "No products to choose from.",
    alreadyAdded: "added",
    availableNote: "{n} available",
    availableAt: "Available at {name}: {n}",
    transferQuantityFor: "Quantity of {name}",
    removeLine: "Remove {name}",
    lineQuantityError: "Enter a number from 1 to {n}.",
    lineNothingFree: "Nothing is free to move here.",
    noLines: "Add the products you want to move.",
    note: "Note (optional)",
    notePlaceholder: "Stocking the shop for the weekend",
    transferSubmit: "Transfer stock",
    transferring: "Transferring…",
    transferred: "Stock transferred.",
    transferShort: "Only {n} free at the source for one of the lines.",
    needTwoTitle: "Transfers need two locations",
    needTwoHint: "Add a second location, then move stock between them here.",
    goToLocations: "Go to locations",
    historyTitle: "Transfer history",
    historyEmpty: "No transfers yet.",
    colDate: "Date",
    colRoute: "From → to",
    colItems: "Items",
    colNote: "Note",
    routeText: "{from} → {to}",
    itemLine: "{name} × {n}",
    moreItems: "+{n} more",
    deletedLocation: "Deleted location",
    // product page card
    byLocationTitle: "Stock by location",
    byLocationDescription: "How each variant's stock is split across your locations.",
    reservedNote: "{n} reserved",
    manageLocations: "Manage locations",
    moreVariants: "Showing the first {n} variants.",
    // order page card
    shipsFrom: "Ships from",
    shipsFromHint: "The location this order's items leave from.",
    shipsFromSaved: "The order now ships from {name}.",
    shipsFromOff: "{name} (off)",
    shipsFromDefault: "{name} (default)",
    shipsFromViewOnly: "Your role can't change where the order ships from.",
  },
  ar: {
    pageTitle: "المخزون",
    pageDescription: "بضاعتك متخزنة فين، وإيه اللي جاي من الموردين، وجرد اللي على الرف.",
    tabsLabel: "أقسام المخزون",
    tab_locations: "المخازن",
    tab_transfers: "نقل مخزون",
    tab_purchaseOrders: "أوامر الشراء",
    tab_suppliers: "الموردين",
    tab_stockCounts: "الجرد",
    tab_forecast: "توقّع المخزون",
    tab_lots: "الدفعات والصلاحية",
    tab_movements: "حركة المخزون",
    locationsTitle: "المخازن",
    locationsDescription: "المخازن والمحلات، كل واحد بمخزونه. المتجر لسه بيبيع من الإجمالي، والمخزن الأساسي فيه الباقي اللي مش في غيره.",
    addLocation: "ضيف مخزن",
    transferStock: "نقل مخزون",
    openInventory: "افتح المخزون",
    colLocation: "المخزن",
    colUnits: "القطع",
    colPriority: "الأولوية في الشحن",
    colActive: "شغّال",
    colActions: "إجراءات",
    defaultBadge: "الأساسي",
    inactiveBadge: "متوقف",
    activeFor: "{name} شغّال",
    defaultAlwaysOn: "المخزن الأساسي مينفعش يتوقف.",
    edit: "تعديل",
    makeDefault: "اجعله الأساسي",
    delete: "حذف",
    emptyTitle: "لسه مفيش مخازن",
    emptyHint: "ضيف أول مخزن أو محل. ده مجاني، وبيبقى الأساسي، وكل المخزون اللي عندك دلوقتي بيتحسب فيه.",
    viewOnlyHint: "صلاحياتك تشوف المخزون بس من غير تعديل.",
    turnedOn: "{name} اشتغل.",
    turnedOff: "{name} اتوقف. الأوردرات الجديدة مش هتتوزع عليه.",
    upgradeTitle: "باقتك فيها مخزن واحد",
    upgradeBody: "عشان توزّع مخزونك على مخازن أو محلات أكتر، رقّي لباقة فيها أكتر من مخزن.",
    upgradeLink: "شوف الباقات",
    upgradeAskOwner: "اطلب من صاحب المتجر يرقّي الباقة.",
    planRefused: "باقتك فيها مخزن واحد. رقّي الباقة عشان تضيف مخزن تاني.",
    tooMany: "المتجر ليه ٥٠ مخزن بحد أقصى.",
    addTitle: "مخزن جديد",
    editTitle: "تعديل المخزن",
    dialogDescription: "مخزن أو محل أو أي مكان بتحط فيه بضاعتك.",
    name: "الاسم",
    namePlaceholder: "المخزن الرئيسي",
    nameError: "اكتب اسم للمخزن.",
    address: "العنوان (اختياري)",
    priority: "الأولوية في الشحن",
    priorityHint: "الأوردر الجديد بيتشحن من أول مخزن شغّال فيه كل منتجاته. الرقم الأقل بيتاخد الأول (من ٠ لـ ١٠٠٠).",
    priorityError: "اكتب رقم صحيح من ٠ لـ ١٠٠٠.",
    save: "حفظ",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    created: "المخزن اتضاف.",
    createdFirst: "المخزن اتضاف. هو الأساسي، وكل مخزونك بيتحسب فيه.",
    saved: "المخزن اتحفظ.",
    makeDefaultTitle: "تخلّي {name} هو الأساسي؟",
    makeDefaultBody: "كل مخزن هيفضل بالقطع اللي فيه دلوقتي. ومن دلوقتي {name} فيه الباقي اللي مش في المخازن التانية، والأوردرات اللي مفيش مخزن تاني يكفّيها بتتشحن منه.",
    makeDefaultConfirm: "اجعله الأساسي",
    madeDefault: "{name} بقى المخزن الأساسي.",
    working: "ثانية واحدة…",
    deleteTitle: "تحذف {name}؟",
    deleteBody: "الأوردرات اللي عليه هترجع للمخزن الأساسي، والجرد المفتوح بتاعه هيتلغي.",
    deleteConfirm: "احذف المخزن",
    deleted: "المخزن اتحذف.",
    deleteHasStock: "المخزن ده لسه فيه بضاعة. انقلها لمخزن تاني الأول.",
    deleteIsDefault: "ده المخزن الأساسي. خلّي مخزن تاني هو الأساسي الأول.",
    back: "المخازن",
    locationFallback: "المخزن",
    priorityLine: "الأولوية في الشحن {n}",
    searchLabel: "دوّر في مخزون المخزن ده",
    searchPlaceholder: "اسم المنتج",
    clearSearch: "امسح البحث",
    colProduct: "المنتج",
    colOnHand: "الموجود",
    colReserved: "محجوز",
    colAvailable: "متاح",
    adjust: "استلام / خصم",
    adjustFor: "استلام أو خصم {name}",
    needsTransfer: "محتاج نقل مخزون",
    needsTransferBanner_one: "فيه منتج محجوز منه هنا أكتر من الموجود. انقل له مخزون من مخزن تاني.",
    needsTransferBanner_two: "فيه منتجين محجوز منهم هنا أكتر من الموجود. انقل لهم مخزون من مخزن تاني.",
    needsTransferBanner_few: "فيه {n} منتجات محجوز منها هنا أكتر من الموجود. انقل لها مخزون من مخزن تاني.",
    needsTransferBanner_other: "فيه {n} منتج محجوز منهم هنا أكتر من الموجود. انقل لهم مخزون من مخزن تاني.",
    stockEmptyTitle: "لسه مفيش منتجات",
    stockEmptyHint: "أول ما تضيف منتجات، مخزونها في المخزن ده هيظهر هنا.",
    noMatchTitle: "مفيش منتج بالاسم ده",
    noMatchHint: "البحث بيدوّر في أسماء المنتجات.",
    showAll: "اعرض كل المنتجات",
    firstRows: "ظاهر أول {n} نوع. دوّر باسم المنتج عشان تلاقي الباقي.",
    singleVariant: "نوع واحد",
    unknownProduct: "منتج محذوف",
    adjustTitle: "استلام / خصم",
    adjustDescription: "إجمالي المتجر بيتحرك معاه، والتغيير بيتسجل في حركة المخزون.",
    adjustModeLabel: "إيه اللي حصل",
    modeReceive: "استلام",
    modeWriteOff: "خصم",
    quantity: "الكمية",
    quantityError: "اكتب رقم صحيح أكبر من صفر.",
    writeOffTooMany: "الموجود هنا {n} بس.",
    reason: "السبب",
    reasonReceivePlaceholder: "بضاعة جديدة وصلت",
    reasonWriteOffPlaceholder: "تالف في التخزين",
    reasonError: "اكتب سبب قصير.",
    onHandNow: "الموجود هنا دلوقتي",
    onHandAfter: "بعد كده",
    adjustSubmitReceive: "استلم",
    adjustSubmitWriteOff: "اخصم",
    adjusted: "المخزون اتحدّث.",
    insufficient: "مفيش قطع كفاية هنا للعملية دي.",
    transferTitle: "نقل مخزون",
    transferDescription: "انقل قطع من مخزن لمخزن. إجمالي المتجر مبيتغيرش.",
    from: "من",
    to: "إلى",
    choose: "اختار…",
    sameLocation: "اختار مخزنين مختلفين.",
    addProduct: "ضيف منتج",
    product: "المنتج",
    variant: "النوع",
    chooseProduct: "اختار منتج…",
    add: "ضيف",
    searchProducts: "دوّر في المنتجات",
    pickerLoading: "بنحمّل المنتجات…",
    pickerFailed: "معرفناش نحمّل المنتجات.",
    pickerEmpty: "مفيش منتجات تختار منها.",
    alreadyAdded: "متضاف",
    availableNote: "متاح {n}",
    availableAt: "المتاح في {name}: {n}",
    transferQuantityFor: "كمية {name}",
    removeLine: "شيل {name}",
    lineQuantityError: "اكتب رقم من ١ لـ {n}.",
    lineNothingFree: "مفيش قطع متاحة للنقل هنا.",
    noLines: "ضيف المنتجات اللي عايز تنقلها.",
    note: "ملاحظة (اختياري)",
    notePlaceholder: "تجهيز المحل لآخر الأسبوع",
    transferSubmit: "انقل المخزون",
    transferring: "بننقل…",
    transferred: "المخزون اتنقل.",
    transferShort: "المتاح في المخزن اللي بتنقل منه {n} بس لواحد من المنتجات.",
    needTwoTitle: "نقل المخزون محتاج مخزنين",
    needTwoHint: "ضيف مخزن تاني، وبعدها انقل البضاعة بينهم من هنا.",
    goToLocations: "روح للمخازن",
    historyTitle: "النقلات السابقة",
    historyEmpty: "لسه مفيش نقلات.",
    colDate: "التاريخ",
    colRoute: "من ← إلى",
    colItems: "المنتجات",
    colNote: "ملاحظة",
    routeText: "{from} ← {to}",
    itemLine: "{name} × {n}",
    moreItems: "و{n} كمان",
    deletedLocation: "مخزن محذوف",
    byLocationTitle: "المخزون في كل مخزن",
    byLocationDescription: "مخزون كل نوع متوزّع إزاي على مخازنك.",
    reservedNote: "محجوز {n}",
    manageLocations: "إدارة المخازن",
    moreVariants: "ظاهر أول {n} نوع.",
    shipsFrom: "بيتشحن من",
    shipsFromHint: "المخزن اللي منتجات الأوردر ده هتطلع منه.",
    shipsFromSaved: "الأوردر بقى بيتشحن من {name}.",
    shipsFromOff: "{name} (متوقف)",
    shipsFromDefault: "{name} (الأساسي)",
    shipsFromViewOnly: "صلاحياتك متسمحش بتغيير مكان الشحن.",
  },
} satisfies Messages;

export type InventoryStrings = (typeof INVENTORY_STRINGS)["en"];
