import type { PurchaseOrderStatus, StockCountStatus } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/**
 * Inventory → Suppliers, Purchase orders and Stock counts (handoff 207).
 * Arabic is the merchant's Egyptian, with the handoff's wording.
 */
export const PURCHASING_STRINGS = {
  en: {
    // shared
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    working: "Working…",
    colActions: "Actions",
    colProduct: "Product",
    colStatus: "Status",
    colNote: "Note",
    viewOnly: "Your role can see this but not change it.",
    singleVariant: "One variant",
    unknownProduct: "Deleted product",
    defaultLocation: "{name} (default)",
    // suppliers
    suppliersHint: "The companies and people you buy your stock from.",
    addSupplier: "Add supplier",
    colSupplier: "Supplier",
    colContact: "Contact",
    colPhone: "Phone",
    colEmail: "Email",
    suppliersEmptyTitle: "No suppliers yet",
    suppliersEmptyHint: "Add who you buy from, then raise purchase orders for them.",
    supplierAddTitle: "New supplier",
    supplierEditTitle: "Edit supplier",
    supplierDialogDescription: "Only your team sees these details.",
    supplierName: "Name",
    supplierNameError: "Enter the supplier's name.",
    contactName: "Contact person (optional)",
    phone: "Phone (optional)",
    email: "Email (optional)",
    emailError: "Enter a valid email, or leave it empty.",
    supplierAddress: "Address (optional)",
    supplierNotes: "Notes (optional)",
    supplierNotesHint: "Payment terms, delivery days, anything worth remembering.",
    supplierCreated: "Supplier added.",
    supplierSaved: "Supplier saved.",
    supplierDeleteTitle: "Delete {name}?",
    supplierDeleteBody: "It leaves your suppliers list. A supplier with purchase orders can't be deleted.",
    supplierDeleteConfirm: "Delete supplier",
    supplierDeleted: "Supplier deleted.",
    supplierInUse: "This supplier has purchase orders, so it can't be deleted.",
    // purchase orders list
    poHint: "What you ordered from suppliers, and what has arrived.",
    newPo: "New purchase order",
    poFilterLabel: "Show purchase orders",
    filterAll: "All",
    status_draft: "Draft",
    status_ordered: "Ordered",
    status_partially_received: "Partly received",
    status_received: "Received",
    status_cancelled: "Cancelled",
    colNumber: "Purchase order",
    colExpected: "Expected",
    colReceived: "Received",
    colTotal: "Total",
    receivedOf: "{received} of {ordered}",
    noDate: "No date",
    poEmptyTitle: "No purchase orders yet",
    poEmptyHint: "Raise a purchase order when you buy stock. Receiving it adds the units and updates your cost.",
    poNoMatchTitle: "No purchase orders with this status",
    poShowAll: "Show all purchase orders",
    unknownSupplier: "Deleted supplier",
    // purchase order page
    poBack: "Purchase orders",
    poNewTitle: "New purchase order",
    poFallbackTitle: "Purchase order",
    detailsTitle: "Details",
    supplier: "Supplier",
    chooseSupplier: "Choose a supplier…",
    supplierError: "Choose a supplier.",
    noSuppliers: "You have no suppliers yet. Add one first, then raise the order.",
    addSupplierLink: "Add a supplier",
    receiveAt: "Receive at",
    receiveAtHint: "The received units are added to this location's stock.",
    expectedAt: "Expected on (optional)",
    poNote: "Note (optional)",
    linesTitle: "Products",
    linesDescription: "What you are buying, how many, and what each one costs you.",
    addProduct: "Add a product",
    colQuantity: "Quantity",
    colUnitCost: "Unit cost",
    colLineTotal: "Total",
    colOrdered: "Ordered",
    colLeft: "Left",
    removeLine: "Remove {name}",
    linesEmpty: "Add the products you are buying.",
    linesError: "Add at least one product.",
    lineQtyError: "Enter a whole number above zero.",
    lineCostError: "Enter a cost, 0 or more.",
    total: "Total",
    saveDraft: "Save draft",
    poCreated: "Saved as a draft.",
    poSaved: "Purchase order saved.",
    markOrdered: "Mark as ordered",
    markOrderedTitle: "Mark {number} as ordered?",
    markOrderedBody: "After this it can't be edited. Receive its products when they arrive.",
    markedOrdered: "Marked as ordered.",
    saveFirst: "Save your changes first.",
    receive: "Receive",
    cancelPo: "Cancel order",
    cancelPoTitle: "Cancel {number}?",
    cancelPoBody: "Nothing was received on it, so your stock doesn't change.",
    cancelPoConfirm: "Cancel order",
    keepPo: "Keep it",
    poCancelled: "Purchase order cancelled.",
    poLocked: "This purchase order was already ordered, so it can't be edited. The page shows it as it is now.",
    poStatusChanged: "This purchase order's status has changed. The page shows it as it is now.",
    createdOn: "Created {date}",
    orderedOn: "Ordered {date}",
    receivedOn: "Received {date}",
    // receive dialog
    receiveTitle: "Receive {number}",
    receiveDescription: "Enter what arrived. The units are added to your stock.",
    receiveDescriptionAt: "Enter what arrived. The units are added to the stock at {name}.",
    receiveQtyFor: "Quantity received of {name}",
    leftToReceive: "{n} left to receive",
    updateCost: "Update cost",
    updateCostHint: "Sets each product's cost to the average of the stock you had and what you receive now.",
    receiveSubmit: "Receive",
    receiving: "Receiving…",
    receivedToast: "Stock received.",
    receivedAllToast: "Everything on this order is received.",
    receiveNothing: "Enter a quantity for at least one product.",
    receiveQtyError: "Enter a number from 0 to {n}.",
    overReceived: "Only {n} left to receive on one of the lines.",
    // stock counts list
    countsHint: "Count what is on the shelf, then correct the numbers in one step.",
    startCount: "Start a count",
    colStarted: "Started",
    colWhere: "Where",
    countStatus_open: "Open",
    countStatus_applied: "Applied",
    countStatus_cancelled: "Cancelled",
    wholeStore: "Whole store",
    aLocation: "A location",
    countsEmptyTitle: "No stock counts yet",
    countsEmptyHint: "Start a count, enter what you find, and apply it. Your stock is adjusted by the differences.",
    // start dialog
    startTitle: "Start a count",
    startDescription: "The count keeps what the system has now, so you only enter what you find.",
    countLocation: "Where",
    countScope: "What to count",
    scopeAll: "All products",
    scopeProduct: "One product",
    countProduct: "Product",
    chooseProduct: "Choose a product…",
    productError: "Choose a product.",
    productsFailed: "Couldn't load the products.",
    productsLoading: "Loading products…",
    productSearch: "Search products",
    countNote: "Note (optional)",
    scopeLimit: "A count takes up to 2000 variants.",
    startSubmit: "Start counting",
    starting: "Starting…",
    nothingToCount: "There is nothing to count here yet.",
    // count page
    countsBack: "Stock counts",
    countTitle: "Count of {date}",
    countFallbackTitle: "Stock count",
    whereLine: "Where: {name}",
    appliedOn: "Applied {date}",
    progress: "{counted} of {total} counted",
    colExpectedCount: "Expected",
    colCounted: "Counted",
    colDifference: "Difference",
    colApplied: "Adjusted by",
    countedFor: "Counted quantity of {name}",
    notCounted: "Not counted",
    matches: "Matches",
    countFilterLabel: "Show lines",
    filterUncounted: "Not counted",
    filterDifferent: "With a difference",
    countSearch: "Search this count",
    countSearchPlaceholder: "Product name or SKU",
    clearSearch: "Clear search",
    savingNow: "Saving…",
    savedNow: "Saved",
    saveFailed: "Couldn't save what you entered.",
    retrySave: "Try again",
    countInvalid: "Enter a whole number, 0 or more.",
    applyCount: "Apply count",
    applyTitle: "Apply this count?",
    applyBody: "Stock will be adjusted by the differences",
    applyDetail: "Each counted line is set against what is on hand at this moment. Lines you didn't count stay as they are.",
    applyConfirm: "Apply count",
    applyNeedOne: "Enter at least one count first.",
    applied: "Count applied. Your stock was adjusted.",
    applyBelowZero: "One of the counts would take a location's stock below zero. Check the numbers and try again.",
    cancelCount: "Cancel count",
    cancelCountTitle: "Cancel this count?",
    cancelCountBody: "Nothing changes in your stock. What you entered stays here to read.",
    cancelCountConfirm: "Cancel count",
    keepCount: "Keep counting",
    countCancelled: "Count cancelled.",
    countClosed: "This count is already closed. The page shows it as it is now.",
    noLinesMatch: "No lines match.",
    showAllLines: "Show all lines",
  },
  ar: {
    save: "حفظ",
    saving: "بنحفظ…",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    working: "ثانية واحدة…",
    colActions: "إجراءات",
    colProduct: "المنتج",
    colStatus: "الحالة",
    colNote: "ملاحظة",
    viewOnly: "صلاحياتك تشوف ده بس من غير تعديل.",
    singleVariant: "نوع واحد",
    unknownProduct: "منتج محذوف",
    defaultLocation: "{name} (الأساسي)",
    suppliersHint: "الشركات والناس اللي بتشتري منهم بضاعتك.",
    addSupplier: "ضيف مورد",
    colSupplier: "المورد",
    colContact: "المسؤول",
    colPhone: "التليفون",
    colEmail: "الإيميل",
    suppliersEmptyTitle: "لسه مفيش موردين",
    suppliersEmptyHint: "ضيف اللي بتشتري منهم، وبعدها اعمل لهم أوامر شراء.",
    supplierAddTitle: "مورد جديد",
    supplierEditTitle: "تعديل المورد",
    supplierDialogDescription: "البيانات دي فريقك بس اللي بيشوفها.",
    supplierName: "الاسم",
    supplierNameError: "اكتب اسم المورد.",
    contactName: "اسم المسؤول (اختياري)",
    phone: "التليفون (اختياري)",
    email: "الإيميل (اختياري)",
    emailError: "اكتب إيميل صح، أو سيبه فاضي.",
    supplierAddress: "العنوان (اختياري)",
    supplierNotes: "ملاحظات (اختياري)",
    supplierNotesHint: "شروط الدفع، أيام التوريد، أي حاجة تحب تفتكرها.",
    supplierCreated: "المورد اتضاف.",
    supplierSaved: "المورد اتحفظ.",
    supplierDeleteTitle: "تحذف {name}؟",
    supplierDeleteBody: "هيتشال من قايمة الموردين. المورد اللي عليه أوامر شراء مينفعش يتحذف.",
    supplierDeleteConfirm: "احذف المورد",
    supplierDeleted: "المورد اتحذف.",
    supplierInUse: "المورد ده عليه أوامر شراء، فمينفعش يتحذف.",
    poHint: "اللي طلبته من الموردين، واللي وصل منه.",
    newPo: "أمر شراء جديد",
    poFilterLabel: "اعرض أوامر الشراء",
    filterAll: "الكل",
    status_draft: "مسودة",
    status_ordered: "اتطلب",
    status_partially_received: "استلام جزئي",
    status_received: "اتسلّم",
    status_cancelled: "ملغي",
    colNumber: "أمر الشراء",
    colExpected: "متوقع يوصل",
    colReceived: "اللي وصل",
    colTotal: "الإجمالي",
    receivedOf: "{received} من {ordered}",
    noDate: "من غير تاريخ",
    poEmptyTitle: "لسه مفيش أوامر شراء",
    poEmptyHint: "اعمل أمر شراء لما تشتري بضاعة. لما تستلمه القطع بتتضاف للمخزون والتكلفة بتتحدّث.",
    poNoMatchTitle: "مفيش أوامر شراء بالحالة دي",
    poShowAll: "اعرض كل أوامر الشراء",
    unknownSupplier: "مورد محذوف",
    poBack: "أوامر الشراء",
    poNewTitle: "أمر شراء جديد",
    poFallbackTitle: "أمر شراء",
    detailsTitle: "التفاصيل",
    supplier: "المورد",
    chooseSupplier: "اختار مورد…",
    supplierError: "اختار مورد.",
    noSuppliers: "لسه معندكش موردين. ضيف مورد الأول، وبعدها اعمل أمر الشراء.",
    addSupplierLink: "ضيف مورد",
    receiveAt: "الاستلام في",
    receiveAtHint: "القطع اللي بتستلمها بتتضاف لمخزون المخزن ده.",
    expectedAt: "متوقع يوصل يوم (اختياري)",
    poNote: "ملاحظة (اختياري)",
    linesTitle: "المنتجات",
    linesDescription: "اللي بتشتريه، كام قطعة، والقطعة بتكلفك كام.",
    addProduct: "ضيف منتج",
    colQuantity: "الكمية",
    colUnitCost: "تكلفة القطعة",
    colLineTotal: "الإجمالي",
    colOrdered: "المطلوب",
    colLeft: "الباقي",
    removeLine: "شيل {name}",
    linesEmpty: "ضيف المنتجات اللي بتشتريها.",
    linesError: "ضيف منتج واحد على الأقل.",
    lineQtyError: "اكتب رقم صحيح أكبر من صفر.",
    lineCostError: "اكتب التكلفة، صفر أو أكتر.",
    total: "الإجمالي",
    saveDraft: "احفظ كمسودة",
    poCreated: "اتحفظ كمسودة.",
    poSaved: "أمر الشراء اتحفظ.",
    markOrdered: "اطلب",
    markOrderedTitle: "تعلّم على {number} إنه اتطلب؟",
    markOrderedBody: "بعد كده مش هيتعدّل. استلم منتجاته لما توصل.",
    markedOrdered: "اتعلّم إنه اتطلب.",
    saveFirst: "احفظ تعديلاتك الأول.",
    receive: "استلام",
    cancelPo: "إلغاء الأمر",
    cancelPoTitle: "تلغي {number}؟",
    cancelPoBody: "مفيش حاجة اتسلّمت منه، فمخزونك مش هيتغير.",
    cancelPoConfirm: "الغي الأمر",
    keepPo: "سيبه",
    poCancelled: "أمر الشراء اتلغى.",
    poLocked: "أمر الشراء ده اتطلب خلاص، فمبقاش ينفع يتعدّل. الصفحة بتعرضه زي ما هو دلوقتي.",
    poStatusChanged: "حالة أمر الشراء ده اتغيرت. الصفحة بتعرضه زي ما هو دلوقتي.",
    createdOn: "اتعمل {date}",
    orderedOn: "اتطلب {date}",
    receivedOn: "اتسلّم {date}",
    receiveTitle: "استلام {number}",
    receiveDescription: "اكتب اللي وصل. القطع هتتضاف لمخزونك.",
    receiveDescriptionAt: "اكتب اللي وصل. القطع هتتضاف لمخزون {name}.",
    receiveQtyFor: "الكمية اللي وصلت من {name}",
    leftToReceive: "باقي {n}",
    updateCost: "حدّث التكلفة",
    updateCostHint: "تكلفة كل منتج هتبقى متوسط المخزون اللي كان عندك واللي بتستلمه دلوقتي.",
    receiveSubmit: "استلم",
    receiving: "بنستلم…",
    receivedToast: "البضاعة اتسلّمت.",
    receivedAllToast: "كل اللي في الأمر ده اتسلّم.",
    receiveNothing: "اكتب كمية لمنتج واحد على الأقل.",
    receiveQtyError: "اكتب رقم من ٠ لـ {n}.",
    overReceived: "الباقي على واحد من المنتجات {n} بس.",
    countsHint: "عِدّ اللي على الرف، وصحّح الأرقام مرة واحدة.",
    startCount: "ابدأ جرد",
    colStarted: "بدأ",
    colWhere: "فين",
    countStatus_open: "مفتوح",
    countStatus_applied: "معتمد",
    countStatus_cancelled: "ملغي",
    wholeStore: "المتجر كله",
    aLocation: "مخزن",
    countsEmptyTitle: "لسه مفيش جرد",
    countsEmptyHint: "ابدأ جرد، اكتب اللي لقيته، واعتمده. مخزونك بيتعدّل بالفرق.",
    startTitle: "ابدأ جرد",
    startDescription: "الجرد بيحتفظ باللي على السيستم دلوقتي، وانت بتكتب اللي لقيته بس.",
    countLocation: "فين",
    countScope: "هتجرد إيه",
    scopeAll: "كل المنتجات",
    scopeProduct: "منتج واحد",
    countProduct: "المنتج",
    chooseProduct: "اختار منتج…",
    productError: "اختار منتج.",
    productsFailed: "معرفناش نحمّل المنتجات.",
    productsLoading: "بنحمّل المنتجات…",
    productSearch: "دوّر في المنتجات",
    countNote: "ملاحظة (اختياري)",
    scopeLimit: "الجرد الواحد بياخد لحد ٢٠٠٠ نوع.",
    startSubmit: "ابدأ العدّ",
    starting: "بنبدأ…",
    nothingToCount: "لسه مفيش حاجة تتجرد هنا.",
    countsBack: "الجرد",
    countTitle: "جرد {date}",
    countFallbackTitle: "جرد",
    whereLine: "فين: {name}",
    appliedOn: "اتعتمد {date}",
    progress: "اتعدّ {counted} من {total}",
    colExpectedCount: "المتوقع",
    colCounted: "اللي اتعدّ",
    colDifference: "الفرق",
    colApplied: "اتعدّل بـ",
    countedFor: "الكمية اللي اتعدّت من {name}",
    notCounted: "لسه متعدّش",
    matches: "مطابق",
    countFilterLabel: "اعرض السطور",
    filterUncounted: "لسه متعدّش",
    filterDifferent: "فيها فرق",
    countSearch: "دوّر في الجرد ده",
    countSearchPlaceholder: "اسم المنتج أو الكود",
    clearSearch: "امسح البحث",
    savingNow: "بنحفظ…",
    savedNow: "اتحفظ",
    saveFailed: "معرفناش نحفظ اللي كتبته.",
    retrySave: "جرّب تاني",
    countInvalid: "اكتب رقم صحيح، صفر أو أكتر.",
    applyCount: "اعتمد الجرد",
    applyTitle: "تعتمد الجرد ده؟",
    applyBody: "هيعدّل المخزون بالفرق",
    applyDetail: "كل سطر اتعدّ بيتقارن باللي موجود في اللحظة دي. والسطور اللي متعدّتش بتفضل زي ما هي.",
    applyConfirm: "اعتمد الجرد",
    applyNeedOne: "اكتب عدد لسطر واحد على الأقل الأول.",
    applied: "الجرد اتعتمد، والمخزون اتعدّل.",
    applyBelowZero: "واحد من الأعداد هينزّل مخزون مخزن تحت الصفر. راجع الأرقام وجرّب تاني.",
    cancelCount: "إلغاء الجرد",
    cancelCountTitle: "تلغي الجرد ده؟",
    cancelCountBody: "مخزونك مش هيتغير. واللي كتبته هيفضل هنا تقراه.",
    cancelCountConfirm: "الغي الجرد",
    keepCount: "كمّل عدّ",
    countCancelled: "الجرد اتلغى.",
    countClosed: "الجرد ده اتقفل خلاص. الصفحة بتعرضه زي ما هو دلوقتي.",
    noLinesMatch: "مفيش سطور مطابقة.",
    showAllLines: "اعرض كل السطور",
  },
} satisfies Messages;

type Key = keyof (typeof PURCHASING_STRINGS)["en"];

export const PO_STATUS_KEY: Record<PurchaseOrderStatus, Key> = {
  draft: "status_draft",
  ordered: "status_ordered",
  partially_received: "status_partially_received",
  received: "status_received",
  cancelled: "status_cancelled",
};

/** A draft waits, an order is on its way, a part arrived, all of it arrived, or it was called off. */
export const PO_STATUS_TONE: Record<PurchaseOrderStatus, "neutral" | "info" | "warning" | "success"> = {
  draft: "neutral",
  ordered: "info",
  partially_received: "warning",
  received: "success",
  cancelled: "neutral",
};

export const COUNT_STATUS_KEY: Record<StockCountStatus, Key> = {
  open: "countStatus_open",
  applied: "countStatus_applied",
  cancelled: "countStatus_cancelled",
};

export const COUNT_STATUS_TONE: Record<StockCountStatus, "neutral" | "warning" | "success"> = {
  open: "warning",
  applied: "success",
  cancelled: "neutral",
};
