import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words the inventory screens gained when they moved to the list pattern
 * (search fields, row menus, previews, the short lines of a phone card). The
 * older tables keep their own files (inventoryStrings, purchasingStrings,
 * forecastStrings, lotStrings). Arabic is the merchant's Egyptian.
 */
export const INV_UI = {
  en: {
    // shared
    noMatch: "Nothing matches this search",
    clearSearch: "Clear the search",
    actionsFor: "Actions for {name}",
    previewOf: "Preview {name}",
    openNamed: "Open {name}",
    openFully: "Open fully",
    copyNumber: "Copy the number",
    copiedNumber: "The number is copied",
    factAddress: "Address",
    notes: "Notes",
    askOwner: "Ask the store owner to give you access from Settings → Team.",
    // locations
    locationSearch: "Search the locations",
    locationSearchPlaceholder: "Location name or address",
    openStock: "Open its stock",
    activeBadge: "Active",
    turnOn: "Turn on",
    turnOff: "Turn off",
    factUnits: "Units on hand",
    factAdded: "Added",
    takesOrders: "Takes new orders",
    takesOrdersHint: "New orders are assigned to it when it has all of their items.",
    // a location's stock
    openProduct: "Open the product",
    stockLine: "{reserved} reserved · {available} available",
    goToProducts: "Go to products",
    // transfers
    transferSearch: "Search the transfers",
    transferSearchPlaceholder: "Location, product or note",
    transferMenu: "Actions for this transfer",
    transferAgain: "Transfer again between these two",
    factMoved: "Moved",
    // purchase orders
    poSearch: "Search purchase orders",
    poSearchPlaceholder: "Number, supplier or note",
    poList: "Purchase orders",
    poFirstRows: "Showing the newest {n}. Choose a status or a supplier to see the rest.",
    supplierChip: "Supplier: {name}",
    supplierOrders: "This supplier's purchase orders",
    showPo_one: "Show 1 purchase order",
    showPo_other: "Show {n} purchase orders",
    receivedLine: "{received} of {ordered} received",
    expectedOn: "Expected {date}",
    linesOnPage: "Open the order to see its products.",
    // suppliers
    supplierSearch: "Search the suppliers",
    supplierSearchPlaceholder: "Name, contact or phone",
    supplierList: "Suppliers",
    // stock counts
    countListSearch: "Search the stock counts",
    countListSearchPlaceholder: "Location, date or note",
    countListChips: "Stock counts by status",
    countList: "Stock counts",
    continueCount: "Keep counting",
    countMenu: "Actions for this count",
    expectedShort: "Expected {n}",
    refreshFilter: "Update this list",
    // forecast
    forecastSearch: "Search the forecast",
    forecastSearchPlaceholder: "Product name or SKU",
    forecastList: "Stock forecast",
    availableShort: "{n} available",
    orderShort: "Order {n}",
    lastsFor: "Lasts {days}",
    runsOut: "Runs out {date}",
    reorderBy: "Reorder by {date}",
    incoming: "{n} on the way",
    perDay: "{n} a day",
    // lots
    lotSearch: "Search the lots",
    lotSearchPlaceholder: "Product, lot code or note",
    lotList: "Lots",
  },
  ar: {
    noMatch: "مفيش حاجة بالبحث ده",
    clearSearch: "امسح البحث",
    actionsFor: "إجراءات {name}",
    previewOf: "معاينة {name}",
    openNamed: "افتح {name}",
    openFully: "افتح بالكامل",
    copyNumber: "انسخ الرقم",
    copiedNumber: "الرقم اتنسخ",
    factAddress: "العنوان",
    notes: "ملاحظات",
    askOwner: "اطلب من صاحب المتجر يفتحهالك من الإعدادات ← الفريق.",
    locationSearch: "دوّر في المخازن",
    locationSearchPlaceholder: "اسم المخزن أو العنوان",
    openStock: "افتح مخزونه",
    activeBadge: "شغّال",
    turnOn: "شغّله",
    turnOff: "وقّفه",
    factUnits: "القطع الموجودة",
    factAdded: "اتضاف",
    takesOrders: "بياخد أوردرات جديدة",
    takesOrdersHint: "الأوردرات الجديدة بتتوزع عليه لما يكون فيه كل منتجاتها.",
    openProduct: "افتح المنتج",
    stockLine: "محجوز {reserved} · متاح {available}",
    goToProducts: "روح للمنتجات",
    transferSearch: "دوّر في النقلات",
    transferSearchPlaceholder: "مخزن، منتج أو ملاحظة",
    transferMenu: "إجراءات النقلة",
    transferAgain: "انقل تاني بين المخزنين دول",
    factMoved: "اتنقل",
    poSearch: "دوّر في أوامر الشراء",
    poSearchPlaceholder: "رقم الأمر، المورد أو ملاحظة",
    poList: "أوامر الشراء",
    poFirstRows: "ظاهر أحدث {n}. اختار حالة أو مورد عشان تشوف الباقي.",
    supplierChip: "المورد: {name}",
    supplierOrders: "أوامر الشراء بتاعة المورد ده",
    showPo_one: "اعرض أمر شراء واحد",
    showPo_two: "اعرض أمرين شراء",
    showPo_few: "اعرض {n} أوامر شراء",
    showPo_other: "اعرض {n} أمر شراء",
    receivedLine: "وصل {received} من {ordered}",
    expectedOn: "متوقع يوصل {date}",
    linesOnPage: "افتح الأمر عشان تشوف منتجاته.",
    supplierSearch: "دوّر في الموردين",
    supplierSearchPlaceholder: "الاسم، المسؤول أو التليفون",
    supplierList: "الموردين",
    countListSearch: "دوّر في الجرد",
    countListSearchPlaceholder: "مخزن، تاريخ أو ملاحظة",
    countListChips: "الجرد حسب الحالة",
    countList: "الجرد",
    continueCount: "كمّل عدّ",
    countMenu: "إجراءات الجرد",
    expectedShort: "المتوقع {n}",
    refreshFilter: "حدّث القايمة دي",
    forecastSearch: "دوّر في التوقّع",
    forecastSearchPlaceholder: "اسم المنتج أو الكود",
    forecastList: "توقّع المخزون",
    availableShort: "متاح {n}",
    orderShort: "اطلب {n}",
    lastsFor: "يكفي {days}",
    runsOut: "هيخلص {date}",
    reorderBy: "اطلب قبل {date}",
    incoming: "جاي في الطريق {n}",
    perDay: "{n} في اليوم",
    lotSearch: "دوّر في الدفعات",
    lotSearchPlaceholder: "المنتج، كود الدفعة أو ملاحظة",
    lotList: "الدفعات",
  },
} satisfies Messages;
