import type { ConfirmationAttemptSource, ConfirmationOutcome } from "@store-builder/api-client";
import { useT, type Messages } from "@/i18n/LocaleContext";

/**
 * The confirmation queue's shared words: the page chrome, the list view's
 * cards, the outcome names and the toasts. The calling station keeps its own
 * table beside its files (station/stationStrings.ts).
 */
export const QUEUE_STRINGS = {
  en: {
    title: "Confirm orders",
    description: "Call each customer to confirm their order before it moves to fulfilment.",
    tabsLabel: "Queue tabs",
    tabPending: "Pending",
    tabInProgress: "In progress",
    tabDone: "Done",
    viewLabel: "How the queue is shown",
    viewStation: "One by one",
    viewList: "List",
    emptyPending: "No orders are waiting for confirmation right now.",
    emptyInProgress: "Nobody is on a call right now.",
    emptyDone: "No finished confirmations yet.",
    outcomeConfirmed: "Confirmed",
    outcomeRejected: "Rejected",
    outcomeUnreachable: "Unreachable",
    outcomePostponed: "Postponed",
    outcomesLabel: "What happened on the call?",
    itemsHeading: "What is in the order",
    moreItems: "+{n} more",
    times: "× {n}",
    attemptsOne: "1 previous attempt",
    attemptsOther: "{n} previous attempts",
    unnamedCustomer: "Unnamed customer",
    noPhone: "No phone number",
    claiming: "Claiming…",
    claimAndCall: "Claim & call",
    claimOnly: "Claim",
    takeOver: "Take over",
    reclaim: "Claim again",
    release: "Release",
    releasing: "Releasing…",
    rejectionReason: "Rejection reason",
    rejectionPlaceholder: "Customer changed their mind",
    notes: "Notes",
    notesPlaceholder: "Anything worth recording from the call (optional).",
    saving: "Saving…",
    saveOutcome: "Save & next",
    toastMarked: "{order} marked {outcome}.",
    toastReleased: "{order} is back in Pending.",
    callbackDue: "Callback due since {time}",
    callbackLater: "Callback scheduled for {time}",
    waitingTitle: "Waiting for the offers window",
    waitingBody:
      "The customer is still on the sales funnel's offers and may add to this order. It opens for confirmation in {left} (at {time}), with its final total.",
    waitingSoon: "The customer is still on the sales funnel's offers. It opens for confirmation in a moment.",
    waitingCount: "{n} waiting for the offers window",
    lastAttempt: "Last: {outcome} by {agent}, {time}",
    yourClaim: "You're on this call · {left} left",
    yourClaimExpired: "Your claim expired. Claim it again before saving — someone else may take it.",
    heldBy: "{name} is on this call · {left} left",
    heldByExpired: "{name}'s claim expired — anyone can take it over.",
    someone: "Another agent",
    lockedBy: "{name} is already on this call ({left} left).",
    doneAt: "{outcome} · {time}",
    doneBy: "by {agent}",
    orderCancelled: "Order cancelled",
    orderDetails: "Order details",
    history: "History ({n})",
    sourceQueue: "call",
    sourceOrderPage: "order page",
    sourceCorrection: "correction",
    corrected: "{from} → {to}",
    unknownAgent: "Unknown user",
    correct: "Correct outcome",
    correctTitle: "Correct {order}",
    correctToRejected:
      "Change to Rejected. Any courier booking that hasn't been collected is cancelled and the stock is released.",
    correctToConfirmed: "Change to Confirmed. The stock is reserved again; this fails if it has sold out.",
    correctReason: "Reason",
    correctReasonPlaceholder: "Customer called back",
    correctNotes: "Notes (optional)",
    correctSubmit: "Change to {outcome}",
    cancel: "Cancel",
    toastCorrected: "{order} changed to {outcome}.",
    filtersTitle: "Sort and filter",
    showCount: "Show {count}",
    showAll: "Show the queue",
    activeFilters: "Filters in effect",
    removeFilter: "Remove: {label}",
    clearAll: "Clear all",
    sortLabel: "Sort",
    sortChip: "Sort: {label}",
    sort_default: "Queue order",
    sort_newest: "Newest first",
    sort_oldest: "Oldest first",
    sort_total_desc: "Total: high to low",
    sort_total_asc: "Total: low to high",
    assignmentFilter: "Who's on it",
    assignShow: "Assign",
    assignChange: "Change",
    filterAll: "All tasks",
    filterMine: "Assigned to me",
    filterUnassigned: "Unassigned",
    filterAgents: "Assigned to an agent",
    assignedTo: "Assigned to {name}",
    assignedToYou: "Assigned to you",
    notAssigned: "Not assigned",
    assignTo: "Assign {order} to",
    nobody: "Nobody (open to all)",
    assignedToast: "{order} assigned to {name}.",
    unassignedToast: "{order} is open to every agent again.",
    assignedToOther: "Assigned to {name}. Only they or a manager can take it.",
    selectTask: "Select {order}",
    selectAll: "Select all shown ({n})",
    allSelected: "Everything shown is selected.",
    sel_one: "1 selected",
    sel_other: "{n} selected",
    bulkAgent: "Agent for the selected tasks",
    bulkAssign: "Assign to…",
    bulkAssignTitle: "Assign {count} to",
    bulkAssignHint: "Pick an agent. Only they or a manager can then take these calls.",
    bulkUnassign: "Remove assignment",
    bulkDone: "{n} tasks updated.",
    bulkSkipped: "{n} finished tasks were left as they were.",
    via: "via {channel}",
    answerNone: "No calls waiting. New cash-on-delivery orders land here by themselves.",
    answer_one: "1 call left",
    answer_other: "{n} calls left",
    answerDue: "{n} of them are due now",
    answerMine: "you are on {n}",
    lockSoon: "Only {left} left on your claim — save the result now.",
    emptyAction: "See all orders",
  },
  ar: {
    title: "تأكيد الأوردرات",
    description: "كلّم كل عميل وأكّد أوردره قبل ما يتشحن.",
    tabsLabel: "أقسام القائمة",
    tabPending: "مستنية",
    tabInProgress: "شغالين عليها",
    tabDone: "خلصت",
    viewLabel: "شكل عرض القائمة",
    viewStation: "واحد واحد",
    viewList: "القائمة",
    emptyPending: "مفيش أوردرات مستنية تأكيد دلوقتي.",
    emptyInProgress: "محدش في مكالمة دلوقتي.",
    emptyDone: "لسه مفيش تأكيدات خلصت.",
    outcomeConfirmed: "أكّد",
    outcomeRejected: "رفض",
    outcomeUnreachable: "مردّش",
    outcomePostponed: "أجّل",
    outcomesLabel: "إيه اللي حصل في المكالمة؟",
    itemsHeading: "الأوردر فيه إيه",
    moreItems: "+{n} كمان",
    times: "× {n}",
    attemptsOne: "اتكلّم مرة قبل كده",
    attemptsOther: "اتكلّم {n} مرات قبل كده",
    unnamedCustomer: "عميل من غير اسم",
    noPhone: "مفيش رقم موبايل",
    claiming: "بنستلم…",
    claimAndCall: "استلم واتصل",
    claimOnly: "استلم",
    takeOver: "استلم مكانه",
    reclaim: "استلم تاني",
    release: "رجّعه للقايمة",
    releasing: "بنرجّعه…",
    rejectionReason: "سبب الرفض",
    rejectionPlaceholder: "العميل غيّر رأيه",
    notes: "ملاحظات",
    notesPlaceholder: "أي حاجة مهمة من المكالمة (اختياري).",
    saving: "بنحفظ…",
    saveOutcome: "سجّل واللي بعده",
    toastMarked: "{order}: {outcome}.",
    toastReleased: "{order} رجع للقايمة.",
    callbackDue: "معاد المكالمة التانية جه من {time}",
    callbackLater: "المكالمة التانية معادها {time}",
    waitingTitle: "مستني العروض تخلص",
    waitingBody:
      "العميل لسه بيتفرج على عروض مسار البيع وممكن يزوّد على الأوردر ده. هيفتح للتأكيد بعد {left} (الساعة {time}) بإجماليه النهائي.",
    waitingSoon: "العميل لسه في عروض مسار البيع. الأوردر هيفتح للتأكيد كمان شوية.",
    waitingCount: "{n} مستنيين العروض تخلص",
    lastAttempt: "آخر محاولة: {outcome} بواسطة {agent}، {time}",
    yourClaim: "إنت مستلم المكالمة دي · باقي {left}",
    yourClaimExpired: "وقتك خلص. استلمه تاني قبل ما تحفظ — ممكن حد تاني ياخده.",
    heldBy: "{name} مستلم المكالمة دي · باقي {left}",
    heldByExpired: "وقت {name} خلص — أي حد يقدر يستلمه.",
    someone: "زميل",
    lockedBy: "{name} مستلم المكالمة دي (باقي {left}).",
    doneAt: "{outcome} · {time}",
    doneBy: "بواسطة {agent}",
    orderCancelled: "أوردر ملغي",
    orderDetails: "تفاصيل الأوردر",
    history: "السجل ({n})",
    sourceQueue: "مكالمة",
    sourceOrderPage: "صفحة الأوردر",
    sourceCorrection: "تصحيح",
    corrected: "{from} ← {to}",
    unknownAgent: "مستخدم مش معروف",
    correct: "صحّح النتيجة",
    correctTitle: "تصحيح {order}",
    correctToRejected: "هيتغيّر لمرفوض. أي شحنة المندوب لسه ما استلمهاش هتتلغي والمخزون هيرجع.",
    correctToConfirmed: "هيتغيّر لمتأكد. المخزون هيتحجز تاني، ولو خلص التغيير مش هيتم.",
    correctReason: "السبب",
    correctReasonPlaceholder: "العميل اتصل تاني",
    correctNotes: "ملاحظات (اختياري)",
    correctSubmit: "غيّرها لـ {outcome}",
    cancel: "إلغاء",
    toastCorrected: "{order} اتغيّر لـ {outcome}.",
    filtersTitle: "الترتيب والفلاتر",
    showCount: "اعرض {count}",
    showAll: "اعرض القائمة",
    activeFilters: "الفلاتر الشغّالة",
    removeFilter: "شيل: {label}",
    clearAll: "امسح الكل",
    sortLabel: "الترتيب",
    sortChip: "الترتيب: {label}",
    sort_default: "ترتيب القايمة",
    sort_newest: "الأحدث الأول",
    sort_oldest: "الأقدم الأول",
    sort_total_desc: "الأغلى الأول",
    sort_total_asc: "الأرخص الأول",
    assignmentFilter: "مين شغال عليها",
    assignShow: "وزّع",
    assignChange: "غيّر",
    filterAll: "الكل",
    filterMine: "بتوعي",
    filterUnassigned: "مش متوزعة",
    filterAgents: "متوزعة على",
    assignedTo: "متوزع على: {name}",
    assignedToYou: "متوزع عليك",
    notAssigned: "مش متوزع",
    assignTo: "وزّع {order} على",
    nobody: "محدش (متاح للكل)",
    assignedToast: "{order} اتوزّع على {name}.",
    unassignedToast: "{order} بقى متاح لكل الفريق تاني.",
    assignedToOther: "متوزع على {name}، ومحدش يستلمه غيره إلا المدير.",
    selectTask: "حدّد {order}",
    selectAll: "حدّد كل المعروض ({n})",
    allSelected: "كل المعروض متحدد.",
    sel_one: "أوردر واحد متحدد",
    sel_two: "أوردرين متحددين",
    sel_few: "{n} أوردرات متحددة",
    sel_other: "{n} أوردر متحدد",
    bulkAgent: "الموظف للأوردرات المتحددة",
    bulkAssign: "وزّع على…",
    bulkAssignTitle: "وزّع {count} على",
    bulkAssignHint: "اختار موظف. بعدها هو أو المدير بس اللي يستلموا المكالمات دي.",
    bulkUnassign: "شيل التوزيع",
    bulkDone: "{n} اتحدّثوا.",
    bulkSkipped: "{n} خلصانين اتسابوا زي ما هم.",
    via: "عن طريق {channel}",
    answerNone: "مفيش مكالمات مستنياك. أوردرات الدفع عند الاستلام الجديدة بتنزل هنا لوحدها.",
    answer_one: "باقي مكالمة واحدة",
    answer_two: "باقي مكالمتين",
    answer_few: "باقي {n} مكالمات",
    answer_other: "باقي {n} مكالمة",
    answerDue: "{n} منهم معادهم جه",
    answerMine: "إنت شغال على {n}",
    lockSoon: "باقي {left} بس على استلامك — سجّل النتيجة دلوقتي.",
    emptyAction: "شوف كل الأوردرات",
  },
} satisfies Messages;

export type QueueStrings = Record<keyof typeof QUEUE_STRINGS.en, string>;

export function useQueueStrings(): QueueStrings {
  return useT(QUEUE_STRINGS);
}

/** Outcome names for the list's toggles, the done cards and the toasts, in the active locale. */
export function useOutcomeLabels(): Record<ConfirmationOutcome, string> {
  const t = useT(QUEUE_STRINGS);
  return {
    confirmed: t.outcomeConfirmed,
    rejected: t.outcomeRejected,
    unreachable: t.outcomeUnreachable,
    postponed: t.outcomePostponed,
  };
}

export function sourceLabel(t: QueueStrings, source: ConfirmationAttemptSource): string {
  if (source === "order_page") return t.sourceOrderPage;
  if (source === "correction") return t.sourceCorrection;
  return t.sourceQueue;
}
