import { useT, type Messages } from "@/i18n/LocaleContext";

/** The calling station's own words. Outcome names for toasts and the list stay in ../queueStrings.ts. */
export const STATION_STRINGS = {
  en: {
    stationLabel: "Calling station",
    cardLabel: "Order {order} from {name}",
    nextUp: "Next: {name}",
    progress: "{done} of {total}",
    progressLabel: "Calls done this sitting: {done} of {total}",
    attempt: "Attempt {n}",
    lockShort: "{n} min",
    lockExpired: "Your claim ran out — it is taken again when you record a result.",
    openOrderNumber: "Open order {order}",
    phoneHidden: "Part of the number is hidden",
    historyLabel: "Their history with the store",
    firstOrder: "Their first order",
    before: "{orders} before this",
    beforeRejected: "{orders} before this — rejected {n}",
    flaggedNumber: "Number is flagged",
    reliability: "Reliability {n} of {max}",
    receives: "Takes delivery of {rate}",
    receivesTitle: "Across every store on the platform: delivered {delivered} of {finished} orders.",
    deposit: "Ask for a deposit",
    depositTitle: "Low delivery rate: ask for a deposit or for the shipping fee upfront.",
    spam_one: "1 report from another store",
    spam_other: "{n} reports from other stores",
    moreFlags: "+{n}",
    offer: "Offer: {name}",
    total: "Total",
    placed: "Placed {when}",
    placedLate: "Placed {when} — waiting for more than {hours}",
    noAddress: "No shipping address",
    assignedYou: "Assigned to you",
    assignedTo: "Assigned to {name}",
    lastNote: "Note from the last call",
    contactLabel: "Reach the customer",
    outcomesLabel: "What happened?",
    call: "Call",
    whatsapp: "WhatsApp",
    used: "used on this call",
    confirmed: "Confirmed",
    noAnswer: "No answer",
    later: "Call later",
    cancelled: "Cancelled",
    skip: "Skip",
    skipLabel: "Skip to the next order without a result",
    note: "Note",
    noteAdded: "Note added",
    openOrder: "Open the order to edit it",
    keyEnter: "Enter",
    sheetFor: "{name} · {order}",
    laterTitle: "Call later",
    cancelTitle: "The customer cancelled",
    cancelSave: "Record the cancellation",
    noteTitle: "A note on this call",
    noteHint: "It is saved with the result you record next.",
    noteDone: "Done",
    back: "Back",
    takenBy: "{name} got to this order first — moved on to the next one.",
    takenAssigned: "This order is assigned to {name} — moved on to the next one.",
    takenDone: "This order already has its result — moved on to the next one.",
    loadingNext: "Getting the next order…",
    doneTitle: "Calls are done",
    noneDue: "No calls for you right now",
    doneConfirmed: "You confirmed {orders} this sitting. New cash-on-delivery orders land here by themselves.",
    doneLogged: "You logged {calls} this sitting. New cash-on-delivery orders land here by themselves.",
    bookedLabel: "Booked for later",
    later_one: "1 call is booked for later",
    later_other: "{n} calls are booked for later",
    nearest: "next at {time}",
    others_one: "1 call is with a teammate now",
    others_other: "{n} calls are with teammates now",
    filtered: "A filter is on, so some calls may not be showing.",
    clearFilters: "Clear the filters",
    refresh: "Check for new orders",
    showList: "Open the list",
  },
  ar: {
    stationLabel: "محطة المكالمات",
    cardLabel: "أوردر {order} من {name}",
    nextUp: "اللي بعده: {name}",
    progress: "{done} من {total}",
    progressLabel: "المكالمات اللي خلصت في القعدة دي: {done} من {total}",
    attempt: "المحاولة {n}",
    lockShort: "{n} د",
    lockExpired: "وقتك خلص — هنستلمه تاني أول ما تسجّل النتيجة.",
    openOrderNumber: "افتح الأوردر {order}",
    phoneHidden: "جزء من الرقم مخفي",
    historyLabel: "تاريخه مع المتجر",
    firstOrder: "أول أوردر ليه",
    before: "{orders} قبل كده",
    beforeRejected: "{orders} قبل كده — رفض {n}",
    flaggedNumber: "رقم عليه علامة",
    reliability: "درجة الثقة {n} من {max}",
    receives: "بيستلم {rate}",
    receivesTitle: "على كل متاجر المنصة: استلم {delivered} من {finished} أوردر.",
    deposit: "اطلب عربون",
    depositTitle: "نسبة استلامه قليلة: اطلب عربون أو مصاريف الشحن مقدم.",
    spam_one: "بلاغ من متجر تاني",
    spam_two: "بلاغين من متاجر تانية",
    spam_few: "{n} بلاغات من متاجر تانية",
    spam_other: "{n} بلاغ من متاجر تانية",
    moreFlags: "+{n}",
    offer: "عرض: {name}",
    total: "الإجمالي",
    placed: "اتطلب {when}",
    placedLate: "اتطلب {when} — مستني أكتر من {hours}",
    noAddress: "مفيش عنوان شحن",
    assignedYou: "متوزع عليك",
    assignedTo: "متوزع على: {name}",
    lastNote: "ملاحظة من آخر مكالمة",
    contactLabel: "كلّم العميل",
    outcomesLabel: "إيه اللي حصل؟",
    call: "اتصل",
    whatsapp: "واتساب",
    used: "اتستخدم في المكالمة دي",
    confirmed: "اتأكد",
    noAnswer: "ما ردّش",
    later: "كلّمني بعدين",
    cancelled: "اتلغى",
    skip: "عدّي",
    skipLabel: "عدّي للأوردر اللي بعده من غير نتيجة",
    note: "ملاحظة",
    noteAdded: "فيه ملاحظة",
    openOrder: "افتح الأوردر وعدّله",
    keyEnter: "Enter",
    sheetFor: "{name} · {order}",
    laterTitle: "كلّمني بعدين",
    cancelTitle: "العميل لغى الأوردر",
    cancelSave: "سجّل الإلغاء",
    noteTitle: "ملاحظة على المكالمة",
    noteHint: "هتتسجّل مع النتيجة اللي هتختارها.",
    noteDone: "تمام",
    back: "رجوع",
    takenBy: "{name} سبقك للأوردر ده — عدّينا للي بعده.",
    takenAssigned: "الأوردر ده متوزع على {name} — عدّينا للي بعده.",
    takenDone: "الأوردر ده اتسجّلت نتيجته خلاص — عدّينا للي بعده.",
    loadingNext: "بنجيب الأوردر اللي بعده…",
    doneTitle: "خلّصت المكالمات",
    noneDue: "مفيش مكالمات ليك دلوقتي",
    doneConfirmed: "أكّدت {orders} في القعدة دي. أوردرات الدفع عند الاستلام الجديدة بتنزل هنا لوحدها.",
    doneLogged: "سجّلت {calls} في القعدة دي. أوردرات الدفع عند الاستلام الجديدة بتنزل هنا لوحدها.",
    bookedLabel: "متأجل لبعدين",
    later_one: "مكالمة واحدة معادها بعدين",
    later_two: "مكالمتين معادهم بعدين",
    later_few: "{n} مكالمات معادها بعدين",
    later_other: "{n} مكالمة معادها بعدين",
    nearest: "أقربها {time}",
    others_one: "مكالمة واحدة مع زميل دلوقتي",
    others_two: "مكالمتين مع زمايلك دلوقتي",
    others_few: "{n} مكالمات مع زمايلك دلوقتي",
    others_other: "{n} مكالمة مع زمايلك دلوقتي",
    filtered: "فيه فلتر شغّال، فممكن يكون فيه مكالمات مش ظاهرة.",
    clearFilters: "امسح الفلاتر",
    refresh: "شوف لو فيه جديد",
    showList: "افتح القائمة",
  },
} satisfies Messages;

export type StationStrings = Record<keyof typeof STATION_STRINGS.en, string>;

export function useStationStrings(): StationStrings {
  return useT(STATION_STRINGS);
}
