import type { Messages } from "@/i18n/LocaleContext";

/** Words shared by the Scripts tab and its dialog (custom code → Scripts). */
export const SCRIPT_STRINGS = {
  en: {
    title: "Scripts",
    description: "Add your own code to the store and choose where and on which pages it runs.",
    add: "Add script",
    position: "Position",
    head: "Head",
    body_start: "Body start",
    body_end: "Body end",
    pages: "Pages",
    all: "All pages",
    home: "Home",
    collection: "Collection",
    product: "Product",
    page: "Custom pages",
    funnel: "Funnel steps",
    cart: "Cart",
    checkout: "Checkout",
    thank_you: "Thank you",
    liveOnly: "Code runs only on your live store, not in the editor preview.",
    trust: "Only paste code from sources you trust: a bad script can break the store or leak orders. Every change is recorded in the activity log.",
    empty: "No scripts yet",
    emptyHint: "Add a chat widget, a heatmap or any tracking tag, then choose where it goes and the pages it runs on.",
    limit: "A store keeps at most {max} scripts",
    usage: "{count} of {max}",
    name: "Name",
    order: "Order",
    active: "Active",
    updated: "Updated",
    actions: "Actions",
    on: "On",
    off: "Off",
    toggle: "Run {name} on the store",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    edit: "Edit {name}",
    remove: "Delete {name}",
    deleteTitle: "Delete this script?",
    deleteBody: "“{name}” stops running on your store. This can't be undone.",
    deleteConfirm: "Delete script",
    deleting: "Deleting…",
    cancel: "Cancel",
    deleted: "Script deleted",
    turnedOn: "Script on",
    turnedOff: "Script off",
    moved: "Order saved",
    added: "Script added",
    saved: "Script saved",
  },
  ar: {
    title: "السكريبتات",
    description: "ضيف كود بتاعك للمتجر واختار مكانه والصفحات اللي يشتغل فيها.",
    add: "إضافة سكريبت",
    position: "المكان",
    head: "داخل head",
    body_start: "أول الـ body",
    body_end: "آخر الـ body",
    pages: "الصفحات",
    all: "كل الصفحات",
    home: "الرئيسية",
    collection: "المجموعة",
    product: "المنتج",
    page: "الصفحات الخاصة",
    funnel: "خطوات مسار البيع",
    cart: "السلة",
    checkout: "إتمام الطلب",
    thank_you: "صفحة الشكر",
    liveOnly: "الكود بيشتغل على المتجر الحقيقي بس، مش في المعاينة.",
    trust: "الصق كود من مصادر بتثق فيها بس: سكريبت وحش ممكن يبوّظ المتجر أو يسرّب الأوردرات. كل تغيير بيتسجل في سجل النشاط.",
    empty: "مفيش سكريبتات لسه",
    emptyHint: "ضيف شات أو أداة تتبع أو أي كود، وبعدين اختار مكانه والصفحات اللي يشتغل فيها.",
    limit: "المتجر ياخد {max} سكريبت بالكتير",
    usage: "{count} من {max}",
    name: "الاسم",
    order: "الترتيب",
    active: "شغّال",
    updated: "آخر تعديل",
    actions: "إجراءات",
    on: "شغّال",
    off: "متوقف",
    toggle: "شغّل {name} على المتجر",
    moveUp: "طلّع {name} لفوق",
    moveDown: "نزّل {name} لتحت",
    edit: "تعديل {name}",
    remove: "مسح {name}",
    deleteTitle: "تمسح السكريبت ده؟",
    deleteBody: "«{name}» هيبطل يشتغل على متجرك. مش هتقدر ترجّعه.",
    deleteConfirm: "امسح السكريبت",
    deleting: "بيمسح…",
    cancel: "إلغاء",
    deleted: "اتمسح السكريبت",
    turnedOn: "السكريبت اشتغل",
    turnedOff: "السكريبت وقف",
    moved: "اتحفظ الترتيب",
    added: "اتضاف السكريبت",
    saved: "اتحفظ السكريبت",
  },
} satisfies Messages;
