import type { AutomationChannel, AutomationTrigger } from "@/mock/types";
import type { Locale, Messages } from "@/i18n/LocaleContext";

export const STRINGS = {
  en: {
    title: "Automations",
    description: "WhatsApp, SMS and email flows that run on order events — confirmations, recovery, shipping updates.",
    newAutomation: "New automation",
    editAutomation: "Edit automation",
    kpiActive: "Active flows",
    kpiActiveHint: "{n} total",
    kpiSent: "Messages sent this month",
    kpiSentHint: "WhatsApp + SMS + email",
    kpiRecovered: "Recovered revenue",
    kpiRecoveredHint: "From abandoned cart & unreachable flows",
    recipes: "Recipes",
    emptyTitle: "No automations yet",
    emptyDescription: "Start from a recipe above, or build your own flow.",
    runsLine: "{runs} runs · Last run {date}",
    untitled: "untitled",
    toastActivated: "Automation activated.",
    toastPaused: "Automation paused.",
    toastDeleted: "Automation deleted.",
    toastSaved: "Automation saved.",
    toastCreated: "Automation created.",
    confirmDeleteNamed: "Delete \"{name}\"?",
    confirmDelete: "Delete automation?",
    confirmDeleteDescription: "Pending scheduled messages from this flow are cancelled.",
    deleteAutomation: "Delete automation",
    toggleLabel: "Automation on/off",
    immediately: "Immediately",
    afterMin: "After {n} min",
    afterHour: "After 1 hour",
    afterHours: "After {n} hours",
    afterDay: "After 1 day",
    afterDays: "After {n} days",
    // editor
    name: "Name",
    namePlaceholder: "Order confirmation",
    trigger: "Trigger",
    steps: "Steps",
    addStep: "Add step",
    moveUp: "Move up",
    moveDown: "Move down",
    removeStep: "Remove step",
    delay: "Delay",
    unit: "Unit",
    minutes: "Minutes",
    hours: "Hours",
    days: "Days",
    channel: "Channel",
    webhookUrl: "Webhook URL",
    templateName: "Template name",
    whatsappHint: "Must match an approved WhatsApp Business template.",
    message: "Message",
    bodyPlaceholder: "Hi {{customer.firstName}} …",
    errName: "Give the automation a name.",
    errSteps: "Add at least one step.",
    errWebhook: "Enter the webhook URL.",
    errTemplate: "Enter a template name.",
    errBody: "Write the message body.",
    saveAutomation: "Save automation",
    createAutomation: "Create automation",
    preview: "Preview",
    previewHint: "First message with sample values substituted.",
    business: "Business",
    typeToPreview: "Type a message to preview it here.",
  },
  ar: {
    title: "الأتمتة",
    description: "مسارات رسائل WhatsApp وSMS والبريد الإلكتروني تعمل تلقائيًا مع أحداث الطلبات — تأكيد الطلب، واسترجاع السلال المتروكة، وتحديثات الشحن.",
    newAutomation: "أتمتة جديدة",
    editAutomation: "تعديل الأتمتة",
    kpiActive: "المسارات النشطة",
    kpiActiveHint: "الإجمالي {n}",
    kpiSent: "الرسائل المُرسلة هذا الشهر",
    kpiSentHint: "WhatsApp + SMS + البريد الإلكتروني",
    kpiRecovered: "الإيرادات المُستردّة",
    kpiRecoveredHint: "من مسارات السلة المتروكة وتعذّر الوصول للعميل",
    recipes: "قوالب جاهزة",
    emptyTitle: "لا توجد أتمتة بعد",
    emptyDescription: "ابدأ من أحد القوالب الجاهزة أعلاه، أو أنشئ مسارك الخاص.",
    runsLine: "{runs} تشغيل · آخر تشغيل {date}",
    untitled: "بدون اسم",
    toastActivated: "تم تفعيل الأتمتة.",
    toastPaused: "تم إيقاف الأتمتة مؤقتًا.",
    toastDeleted: "تم حذف الأتمتة.",
    toastSaved: "تم حفظ الأتمتة.",
    toastCreated: "تم إنشاء الأتمتة.",
    confirmDeleteNamed: "حذف «{name}»؟",
    confirmDelete: "حذف الأتمتة؟",
    confirmDeleteDescription: "سيتم إلغاء الرسائل المجدولة المعلّقة من هذا المسار.",
    deleteAutomation: "حذف الأتمتة",
    toggleLabel: "تشغيل/إيقاف الأتمتة",
    immediately: "فورًا",
    afterMin: "بعد {n} دقيقة",
    afterHour: "بعد ساعة",
    afterHours: "بعد {n} ساعات",
    afterDay: "بعد يوم",
    afterDays: "بعد {n} أيام",
    name: "الاسم",
    namePlaceholder: "تأكيد الطلب",
    trigger: "المُشغِّل",
    steps: "الخطوات",
    addStep: "إضافة خطوة",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    removeStep: "حذف الخطوة",
    delay: "التأخير",
    unit: "الوحدة",
    minutes: "دقائق",
    hours: "ساعات",
    days: "أيام",
    channel: "القناة",
    webhookUrl: "رابط Webhook",
    templateName: "اسم قالب الرسالة",
    whatsappHint: "يجب أن يطابق قالبًا معتمدًا في WhatsApp Business.",
    message: "الرسالة",
    bodyPlaceholder: "أهلاً {{customer.firstName}} …",
    errName: "أدخل اسمًا للأتمتة.",
    errSteps: "أضف خطوة واحدة على الأقل.",
    errWebhook: "أدخل رابط Webhook.",
    errTemplate: "أدخل اسم قالب الرسالة.",
    errBody: "اكتب نص الرسالة.",
    saveAutomation: "حفظ الأتمتة",
    createAutomation: "إنشاء الأتمتة",
    preview: "معاينة",
    previewHint: "أول رسالة مع استبدال المتغيرات بقيم تجريبية.",
    business: "حساب تجاري",
    typeToPreview: "اكتب رسالة لمعاينتها هنا.",
  },
} satisfies Messages;

export const TRIGGER_LABEL: Record<Locale, Record<AutomationTrigger, string>> = {
  en: {
    order_created: "Order placed",
    order_confirmed: "Order confirmed",
    order_shipped: "Order shipped",
    order_delivered: "Order delivered",
    order_cancelled: "Order cancelled",
    checkout_abandoned: "Checkout abandoned",
    confirmation_unreachable: "Customer unreachable",
  },
  ar: {
    order_created: "تم إنشاء الطلب",
    order_confirmed: "تأكيد الطلب",
    order_shipped: "تم الشحن",
    order_delivered: "تم التوصيل",
    order_cancelled: "تم إلغاء الطلب",
    checkout_abandoned: "سلة متروكة",
    confirmation_unreachable: "تعذّر الوصول للعميل",
  },
};

export const CHANNEL_LABEL: Record<Locale, Record<AutomationChannel, string>> = {
  en: { whatsapp: "WhatsApp", sms: "SMS", email: "Email", webhook: "Webhook" },
  ar: { whatsapp: "WhatsApp", sms: "رسالة SMS", email: "البريد الإلكتروني", webhook: "Webhook" },
};

export type RecipeKey = "confirm" | "abandoned" | "shipped" | "review";

export const RECIPE_TEXT: Record<Locale, Record<RecipeKey, { title: string; description: string }>> = {
  en: {
    confirm: { title: "Order confirmation on WhatsApp", description: "Ask the customer to reply 1 to confirm — cuts fake COD orders before you ship." },
    abandoned: { title: "Abandoned cart, 2 steps", description: "WhatsApp nudge after 30 minutes, then an SMS with a discount the next day." },
    shipped: { title: "Shipping notification", description: "Send the tracking link the moment the carrier picks up the parcel." },
    review: { title: "Delivered → review request", description: "Two days after delivery, ask for a review on WhatsApp." },
  },
  ar: {
    confirm: { title: "تأكيد الطلب على WhatsApp", description: "اطلب من العميل الرد بـ 1 للتأكيد — يقلّل طلبات الدفع عند الاستلام الوهمية قبل الشحن." },
    abandoned: { title: "سلة متروكة، على خطوتين", description: "تذكير على WhatsApp بعد 30 دقيقة، ثم رسالة SMS بخصم في اليوم التالي." },
    shipped: { title: "إشعار الشحن", description: "أرسل رابط التتبع فور استلام شركة الشحن للطرد." },
    review: { title: "تم التوصيل ← طلب تقييم", description: "بعد يومين من التوصيل، اطلب تقييمًا على WhatsApp." },
  },
};
