import type { FunnelStatus, UiEdgeCondition, UiStepType } from "./funnelAdapter";
import type { Locale, Messages } from "@/i18n/LocaleContext";

export const EDITOR_STRINGS = {
  en: {
    notFound: "This funnel doesn't exist.",
    backToFunnels: "Back to funnels",
    clickToRename: "Click to rename",
    unsavedChanges: "Unsaved changes",
    preview: "Preview",
    pause: "Pause",
    resume: "Resume",
    publish: "Publish",
    republish: "Publish changes",
    cantPublish: "This funnel can’t be published yet:",
    steps: "Steps",
    selectHint: "Select a step on the canvas or in the list to edit it.",
    deleteStepTitle: "Delete this step?",
    deleteStepDescription: "\"{name}\" and every edge connected to it will be removed. Nothing is deleted until you save.",
    deleteStep: "Delete step",
    toastSaved: "Funnel saved.",
    toastFixProblems: "Fix the problems below before publishing.",
    toastPublished: "Funnel published.",
    toastPaused: "Funnel paused.",
    toastResumed: "Funnel resumed.",
    canvasLabel: "Funnel flow canvas",
    savingProgress: "Saving {done}/{total}…",
    saveFailed: "Save stopped: {message} Changes made before this point were saved; reload to see the server state.",
    reload: "Reload",
    history: "History",
    historyTitle: "Published revisions",
    historyEmpty: "No revisions yet. Each publish creates one.",
    revisionLabel: "Revision #{n}",
    revisionSteps: "{n} steps",
    revisionLive: "Live",
    rollback: "Restore",
    rollbackTitle: "Restore revision #{n}?",
    rollbackDescription: "Visitors will see revision #{n} immediately. Your draft steps and edges are not changed.",
    toastRolledBack: "Revision #{n} is live.",
    publishedRevision: "Live: revision #{n}",
  },
  ar: {
    notFound: "مسار البيع هذا غير موجود.",
    backToFunnels: "العودة إلى مسارات البيع",
    clickToRename: "انقر لإعادة التسمية",
    unsavedChanges: "تغييرات غير محفوظة",
    preview: "معاينة",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    publish: "نشر",
    republish: "نشر التغييرات",
    cantPublish: "لا يمكن نشر مسار البيع هذا بعد:",
    steps: "الخطوات",
    selectHint: "اختر خطوة من اللوحة أو من القائمة لتعديلها.",
    deleteStepTitle: "حذف هذه الخطوة؟",
    deleteStepDescription: "ستتم إزالة «{name}» وكل الروابط المتصلة بها. لن يُحذف شيء قبل الحفظ.",
    deleteStep: "حذف الخطوة",
    toastSaved: "تم حفظ مسار البيع.",
    toastFixProblems: "أصلح المشكلات أدناه قبل النشر.",
    toastPublished: "تم نشر مسار البيع.",
    toastPaused: "تم إيقاف مسار البيع مؤقتًا.",
    toastResumed: "تم استئناف مسار البيع.",
    canvasLabel: "لوحة تدفق مسار البيع",
    savingProgress: "جارٍ الحفظ {done}/{total}…",
    saveFailed: "توقف الحفظ: {message} ما تم قبل هذه الخطوة محفوظ؛ أعد التحميل لرؤية الحالة على الخادم.",
    reload: "إعادة التحميل",
    history: "السجل",
    historyTitle: "النسخ المنشورة",
    historyEmpty: "لا توجد نسخ بعد. كل عملية نشر تُنشئ نسخة.",
    revisionLabel: "النسخة رقم {n}",
    revisionSteps: "{n} خطوات",
    revisionLive: "منشورة",
    rollback: "استعادة",
    rollbackTitle: "استعادة النسخة رقم {n}؟",
    rollbackDescription: "سيرى الزوار النسخة رقم {n} فورًا. لن تتغير خطوات وروابط المسودة.",
    toastRolledBack: "النسخة رقم {n} منشورة الآن.",
    publishedRevision: "المنشور: النسخة رقم {n}",
  },
} satisfies Messages;

export const LIST_STRINGS = {
  en: {
    addStep: "Add step",
    reorder: "Reorder {name}",
    deleteNamed: "Delete {name}",
  },
  ar: {
    addStep: "إضافة خطوة",
    reorder: "إعادة ترتيب {name}",
    deleteNamed: "حذف {name}",
  },
} satisfies Messages;

export const CANVAS_STRINGS = {
  en: {
    entry: "entry",
    abRunning: "A/B test running",
    statsUnavailable: "Stats appear once analytics is connected",
  },
  ar: {
    entry: "البداية",
    abRunning: "اختبار A/B قيد التشغيل",
    statsUnavailable: "ستظهر الإحصاءات بعد ربط التحليلات",
  },
} satisfies Messages;

export const INSPECTOR_STRINGS = {
  en: {
    stepSettings: "Step settings",
    closeInspector: "Close inspector",
    name: "Name",
    type: "Type",
    key: "Step key",
    offer: "Offer",
    product: "Product",
    pickProduct: "— Pick a product —",
    offerLabel: "Offer",
    pickOffer: "— Pick an offer —",
    noOffers: "This product has no active offers. Create one on the product page.",
    noProducts: "No products yet. Add a product and an offer first.",
    offersError: "Couldn't load offers.",
    required: "Required before publishing.",
    offerPrice: "Offer price",
    offerPriceNone: "Uses variant prices",
    abRunning: "An A/B experiment is attached to this step.",
    manageExperiments: "Manage in Experiments",
    edges: "Edges",
    thankYouEnds: "The thank-you page ends the funnel.",
    noEdges: "No outgoing edges yet.",
    toStep: "To step",
    toStepOption: "→ {name}",
    removeEdge: "Remove edge",
    condition: "Condition",
    priority: "Priority (higher runs first)",
  },
  ar: {
    stepSettings: "إعدادات الخطوة",
    closeInspector: "إغلاق لوحة الإعدادات",
    name: "الاسم",
    type: "النوع",
    key: "معرّف الخطوة",
    offer: "العرض",
    product: "المنتج",
    pickProduct: "— اختر منتجًا —",
    offerLabel: "العرض",
    pickOffer: "— اختر عرضًا —",
    noOffers: "لا توجد عروض نشطة لهذا المنتج. أنشئ عرضًا من صفحة المنتج.",
    noProducts: "لا توجد منتجات بعد. أضف منتجًا وعرضًا أولًا.",
    offersError: "تعذّر تحميل العروض.",
    required: "مطلوب قبل النشر.",
    offerPrice: "سعر العرض",
    offerPriceNone: "يستخدم أسعار المتغيرات",
    abRunning: "توجد تجربة A/B مرتبطة بهذه الخطوة.",
    manageExperiments: "الإدارة من صفحة التجارب",
    edges: "الروابط",
    thankYouEnds: "صفحة الشكر هي نهاية مسار البيع.",
    noEdges: "لا توجد روابط خارجة بعد.",
    toStep: "إلى الخطوة",
    toStepOption: "← {name}",
    removeEdge: "إزالة الرابط",
    condition: "الشرط",
    priority: "الأولوية (الأعلى يُنفَّذ أولًا)",
  },
} satisfies Messages;

/** Client-side pre-check; mirrors backend funnelGraph.validateGraph (server messages win on publish). */
export const VALIDATION_STRINGS = {
  en: {
    noSteps: "A funnel needs at least one step.",
    noEntry: "No entry step — every step has an incoming edge. Remove the edge into your first step.",
    manyEntries: "Exactly one step may have no incoming edge (found {n}: {names}).",
    danglingEdge: "An edge points to a step that no longer exists ({from} → {to}).",
    unreachable: "\"{name}\" can't be reached from the entry step.",
    needsOffer: "\"{name}\" ({type}) needs an offer.",
  },
  ar: {
    noSteps: "يحتاج مسار البيع إلى خطوة واحدة على الأقل.",
    noEntry: "لا توجد خطوة بداية — كل خطوة لها رابط داخل إليها. احذف الرابط الداخل إلى خطوتك الأولى.",
    manyEntries: "يجب أن تكون خطوة واحدة فقط بلا رابط داخل (يوجد {n}: {names}).",
    danglingEdge: "يوجد رابط يشير إلى خطوة لم تعد موجودة ({from} ← {to}).",
    unreachable: "لا يمكن الوصول إلى «{name}» من خطوة البداية.",
    needsOffer: "«{name}» ({type}) تحتاج إلى عرض.",
  },
} satisfies Messages;

export const STEP_TYPE_LABELS: Record<Locale, Record<UiStepType, string>> = {
  en: {
    landing: "Landing page",
    sales: "Sales page",
    opt_in: "Opt-in",
    checkout: "Checkout",
    upsell: "Upsell",
    downsell: "Downsell",
    thank_you: "Thank you",
    custom: "Custom page",
  },
  ar: {
    landing: "صفحة الهبوط",
    sales: "صفحة البيع",
    opt_in: "صفحة التسجيل",
    checkout: "صفحة الدفع",
    upsell: "عرض بعد الشراء",
    downsell: "عرض بديل",
    thank_you: "صفحة الشكر",
    custom: "صفحة مخصصة",
  },
};

/** Default display name for a freshly added step (becomes editable user data). */
export const STEP_DEFAULT_NAMES: Record<Locale, Record<UiStepType, string>> = {
  en: {
    landing: "Landing page",
    sales: "Sales page",
    opt_in: "Opt-in",
    checkout: "Checkout",
    upsell: "Upsell",
    downsell: "Downsell",
    thank_you: "Thank you",
    custom: "Custom page",
  },
  ar: {
    landing: "صفحة الهبوط",
    sales: "صفحة البيع",
    opt_in: "تسجيل البيانات",
    checkout: "الدفع",
    upsell: "عرض بعد الشراء",
    downsell: "عرض بديل",
    thank_you: "شكراً لطلبك",
    custom: "صفحة مخصصة",
  },
};

export const CONDITION_LABELS: Record<Locale, Record<UiEdgeCondition, string>> = {
  en: {
    always: "Always",
    completed_checkout: "Completed checkout",
    accepted_offer: "Accepted",
    declined_offer: "Declined",
  },
  ar: {
    always: "دائمًا",
    completed_checkout: "أكمل الدفع",
    accepted_offer: "قبِل العرض",
    declined_offer: "رفض العرض",
  },
};

export const STATUS_LABELS: Record<Locale, Record<FunnelStatus, string>> = {
  en: { draft: "Draft", published: "Published", paused: "Paused" },
  ar: { draft: "مسودة", published: "منشور", paused: "متوقف مؤقتًا" },
};
