import type { FunnelStatus, StarterTemplateId, UiEdgeCondition, UiStepType } from "./funnelAdapter";
import type { Locale, Messages } from "@/i18n/LocaleContext";

export const EDITOR_STRINGS = {
  en: {
    notFound: "This funnel doesn't exist.",
    backToFunnels: "Back to funnels",
    clickToRename: "Click to rename",
    unsavedChanges: "Unsaved changes",
    preview: "Preview",
    pause: "Pause",
    resume: "Resume",
    publish: "Publish",
    republish: "Publish changes",
    cantPublish: "This funnel can’t be published yet:",
    steps: "Steps",
    selectHint: "Select a step on the canvas or in the list to edit it.",
    deleteStepTitle: "Delete this step?",
    deleteStepDescription: "\"{name}\" and every edge connected to it will be removed. If it sat in a straight line, the step before it is joined to the step after it. Nothing is deleted until you save.",
    deleteStep: "Delete step",
    toastSaved: "Funnel saved.",
    toastFixProblems: "Fix the problems below before publishing.",
    toastPublished: "Funnel published.",
    toastPaused: "Funnel paused.",
    toastResumed: "Funnel resumed.",
    canvasLabel: "Funnel flow canvas",
    savingProgress: "Saving {done}/{total}…",
    saveFailed: "Save stopped: {message} Changes made before this point were saved; reload to see the server state.",
    reload: "Reload",
    history: "History",
    historyTitle: "Published revisions",
    historyEmpty: "No revisions yet. Each publish creates one.",
    revisionLabel: "Revision #{n}",
    revisionSteps: "{n} steps",
    revisionLive: "Live",
    rollback: "Restore",
    rollbackTitle: "Restore revision #{n}?",
    rollbackDescription: "Visitors will see revision #{n} immediately. Your draft steps and edges are not changed.",
    toastRolledBack: "Revision #{n} is live.",
    publishedRevision: "Live: revision #{n}",
    viewFlow: "Flow",
    viewPage: "Page",
    views: "Editor view",
    readyToPublish: "Ready to publish",
    toFix: "{n} to fix before publishing",
    oneToFix: "1 thing to fix before publishing",
    showStep: "Show step",
    serverSaid: "The server checked the saved draft:",
    collapsePanel: "Collapse panel",
    expandPanel: "Expand panel",
  },
  ar: {
    notFound: "مسار البيع هذا غير موجود.",
    backToFunnels: "العودة إلى مسارات البيع",
    clickToRename: "انقر لإعادة التسمية",
    unsavedChanges: "تغييرات غير محفوظة",
    preview: "معاينة",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    publish: "نشر",
    republish: "نشر التغييرات",
    cantPublish: "لا يمكن نشر مسار البيع هذا بعد:",
    steps: "الخطوات",
    selectHint: "اختر خطوة من اللوحة أو من القائمة لتعديلها.",
    deleteStepTitle: "حذف هذه الخطوة؟",
    deleteStepDescription: "ستتم إزالة «{name}» وكل الروابط المتصلة بها. لو كانت في خط مستقيم، الخطوة اللي قبلها هتتوصل باللي بعدها. لن يُحذف شيء قبل الحفظ.",
    deleteStep: "حذف الخطوة",
    toastSaved: "تم حفظ مسار البيع.",
    toastFixProblems: "أصلح المشكلات أدناه قبل النشر.",
    toastPublished: "تم نشر مسار البيع.",
    toastPaused: "تم إيقاف مسار البيع مؤقتًا.",
    toastResumed: "تم استئناف مسار البيع.",
    canvasLabel: "لوحة تدفق مسار البيع",
    savingProgress: "جارٍ الحفظ {done}/{total}…",
    saveFailed: "توقف الحفظ: {message} ما تم قبل هذه الخطوة محفوظ؛ أعد التحميل لرؤية الحالة على الخادم.",
    reload: "إعادة التحميل",
    history: "السجل",
    historyTitle: "النسخ المنشورة",
    historyEmpty: "لا توجد نسخ بعد. كل عملية نشر تُنشئ نسخة.",
    revisionLabel: "النسخة رقم {n}",
    revisionSteps: "{n} خطوات",
    revisionLive: "منشورة",
    rollback: "استعادة",
    rollbackTitle: "استعادة النسخة رقم {n}؟",
    rollbackDescription: "سيرى الزوار النسخة رقم {n} فورًا. لن تتغير خطوات وروابط المسودة.",
    toastRolledBack: "النسخة رقم {n} منشورة الآن.",
    publishedRevision: "المنشور: النسخة رقم {n}",
    viewFlow: "المسار",
    viewPage: "الصفحة",
    views: "طريقة العرض",
    readyToPublish: "جاهز للنشر",
    toFix: "{n} حاجات لازم تتصلّح قبل النشر",
    oneToFix: "حاجة واحدة لازم تتصلّح قبل النشر",
    showStep: "روح للخطوة",
    serverSaid: "السيرفر راجع المسودة المحفوظة:",
    collapsePanel: "طي اللوحة",
    expandPanel: "فتح اللوحة",
  },
} satisfies Messages;

export const LIST_STRINGS = {
  en: {
    addStep: "Add step",
    reorder: "Reorder {name}",
    deleteNamed: "Delete {name}",
  },
  ar: {
    addStep: "إضافة خطوة",
    reorder: "إعادة ترتيب {name}",
    deleteNamed: "حذف {name}",
  },
} satisfies Messages;

export const CANVAS_STRINGS = {
  en: {
    entry: "entry",
    abRunning: "A/B test running",
    statsUnavailable: "Stats appear once analytics is connected",
    addAfter: "Add a step after {name}",
    insertHere: "Add a step between {from} and {to}",
    pickType: "Add which step?",
    offer: "Offer: {offer}",
    offerOf: "{offer} · {product}",
    noOffer: "No offer picked",
    offerUnknown: "Offer not found or inactive",
    sections: "{n} sections",
    oneSection: "1 section",
    emptyPage: "Empty page",
    toFix: "{n} to fix",
    tidy: "Tidy layout",
    tidyHint: "Line the cards up in flow order, yes paths above no paths.",
    legendYes: "Yes / accepted",
    legendNo: "No / declined",
    legendNext: "Next",
    emptyTitle: "Start from a template",
    emptyBody: "Pick a starting flow. Every step, page and connection can be changed afterwards, and nothing is saved until you click Save.",
    orBlank: "Or add steps one by one with “Add step”.",
    openPageHint: "Drag to move. Double-click to edit this step's page.",
  },
  ar: {
    entry: "البداية",
    abRunning: "اختبار A/B قيد التشغيل",
    statsUnavailable: "ستظهر الإحصاءات بعد ربط التحليلات",
    addAfter: "إضافة خطوة بعد {name}",
    insertHere: "إضافة خطوة بين {from} و{to}",
    pickType: "تضيف خطوة إيه؟",
    offer: "العرض: {offer}",
    offerOf: "{offer} · {product}",
    noOffer: "لسه مختارتش عرض",
    offerUnknown: "العرض مش موجود أو مش نشط",
    sections: "{n} أقسام",
    oneSection: "قسم واحد",
    emptyPage: "الصفحة فاضية",
    toFix: "{n} للتصليح",
    tidy: "رتّب اللوحة",
    tidyHint: "رصّ الكروت بترتيب المسار، و«وافق» فوق «رفض».",
    legendYes: "وافق",
    legendNo: "رفض",
    legendNext: "بعد كده",
    emptyTitle: "ابدأ من قالب",
    emptyBody: "اختار مسار تبدأ بيه. تقدر تغيّر أي خطوة أو صفحة أو رابط بعدين، ومفيش حاجة بتتحفظ غير لما تدوس حفظ.",
    orBlank: "أو ضيف الخطوات واحدة واحدة من «إضافة خطوة».",
    openPageHint: "اسحب عشان تحرّك. دوس مرتين عشان تعدّل صفحة الخطوة.",
  },
} satisfies Messages;

/** Unmistakable draft / live / paused explanation under the editor header. */
export const STATUS_STRINGS = {
  en: {
    draftTitle: "Draft — not live",
    draftBody: "Visitors can't open this funnel yet. Publish it when every step is ready.",
    liveTitle: "Live",
    liveTitleRevision: "Live — revision #{n}",
    liveBody: "Visitors see the published revision. Changes you save stay in the draft until you click “Publish changes”.",
    pausedTitle: "Paused",
    pausedBody: "Visitors are told this funnel isn't available right now. Resume to bring the published revision back.",
    unsaved: "You have unsaved changes.",
  },
  ar: {
    draftTitle: "مسودة — مش منشور",
    draftBody: "الزوار لسه مايقدروش يفتحوا المسار ده. انشره لما كل الخطوات تجهز.",
    liveTitle: "منشور",
    liveTitleRevision: "منشور — النسخة رقم {n}",
    liveBody: "الزوار بيشوفوا النسخة المنشورة. أي تعديل بتحفظه بيفضل في المسودة لحد ما تدوس «نشر التغييرات».",
    pausedTitle: "متوقف مؤقتًا",
    pausedBody: "الزوار بيتقالهم إن المسار مش متاح دلوقتي. دوس استئناف عشان النسخة المنشورة ترجع.",
    unsaved: "عندك تعديلات لسه متحفظتش.",
  },
} satisfies Messages;

/** The step page view: section library, inspector and storefront preview for one step. */
export const PAGE_STRINGS = {
  en: {
    step: "Step",
    backToFlow: "Back to flow",
    pageOf: "Page of “{name}”",
    pageHint: "Drag sections to reorder, click one to edit it. Saved with the rest of the funnel.",
    empty: "This page is empty. Add a section from the library — a step needs content before the funnel can be published.",
    selectSection: "Select a section to edit its content.",
    deleteSectionTitle: "Delete this section?",
    deleteSectionDescription: "\"{name}\" and its content will be removed from this step's page. Nothing is deleted until you save.",
    deleteSection: "Delete section",
    preview: "Preview",
    previewTitle: "Preview — {name}",
    previewHint: "Rendered by your storefront, unsaved changes included, inside your store's header and footer. Customers can't see this.",
    refresh: "Refresh preview",
    desktop: "Desktop width",
    mobile: "Mobile width",
    close: "Close preview",
    frameTitle: "Funnel step preview",
    useProduct: "Show “{product}” in this page's product blocks",
    useProductHint: "This step's offer is on {product}. Product blocks with no product picked show your newest product instead.",
    noSteps: "Add a step first — each step has its own page.",
    collapsePanel: "Collapse panel",
    expandPanel: "Expand panel",
  },
  ar: {
    step: "الخطوة",
    backToFlow: "رجوع للمسار",
    pageOf: "صفحة «{name}»",
    pageHint: "اسحب الأقسام عشان ترتّبها، ودوس على قسم عشان تعدّله. بيتحفظ مع باقي المسار.",
    empty: "الصفحة دي فاضية. ضيف قسم من المكتبة — الخطوة لازم يكون فيها محتوى قبل ما المسار يتنشر.",
    selectSection: "اختار قسم عشان تعدّل محتواه.",
    deleteSectionTitle: "تمسح القسم ده؟",
    deleteSectionDescription: "«{name}» ومحتواه هيتشالوا من صفحة الخطوة دي. مفيش حاجة بتتمسح قبل الحفظ.",
    deleteSection: "حذف القسم",
    preview: "معاينة",
    previewTitle: "معاينة — {name}",
    previewHint: "المتجر بتاعك هو اللي بيرسمها، بالتعديلات اللي لسه متحفظتش، جوه هيدر وفوتر المتجر. العملاء مش شايفينها.",
    refresh: "تحديث المعاينة",
    desktop: "عرض الكمبيوتر",
    mobile: "عرض الموبايل",
    close: "إغلاق المعاينة",
    frameTitle: "معاينة خطوة المسار",
    useProduct: "اعرض «{product}» في بلوكات المنتج في الصفحة دي",
    useProductHint: "عرض الخطوة دي على {product}. بلوكات المنتج اللي مفيهاش منتج متحدد بتعرض أحدث منتج عندك.",
    noSteps: "ضيف خطوة الأول — كل خطوة ليها صفحتها.",
    collapsePanel: "طي اللوحة",
    expandPanel: "فتح اللوحة",
  },
} satisfies Messages;

export const INSPECTOR_STRINGS = {
  en: {
    stepSettings: "Step settings",
    closeInspector: "Close inspector",
    name: "Name",
    type: "Type",
    key: "Step key",
    offer: "Offer",
    product: "Product",
    pickProduct: "— Pick a product —",
    offerLabel: "Offer",
    pickOffer: "— Pick an offer —",
    noOffers: "This product has no active offers. Create one on the product page.",
    noProducts: "No products yet. Add a product and an offer first.",
    offersError: "Couldn't load offers.",
    required: "Required before publishing.",
    offerPrice: "Offer price",
    offerPriceNone: "Uses variant prices",
    abRunning: "An A/B experiment is attached to this step.",
    manageExperiments: "Manage in Experiments",
    edges: "Edges",
    thankYouEnds: "The thank-you page ends the funnel.",
    noEdges: "No outgoing edges yet.",
    toStep: "To step",
    toStepOption: "→ {name}",
    removeEdge: "Remove edge",
    condition: "Condition",
    priority: "Priority (higher runs first)",
    problems: "Fix before publishing",
    page: "Page",
    pageEmpty: "This step's page is empty.",
    editPage: "Edit page",
    addNext: "Add next step",
  },
  ar: {
    stepSettings: "إعدادات الخطوة",
    closeInspector: "إغلاق لوحة الإعدادات",
    name: "الاسم",
    type: "النوع",
    key: "معرّف الخطوة",
    offer: "العرض",
    product: "المنتج",
    pickProduct: "— اختر منتجًا —",
    offerLabel: "العرض",
    pickOffer: "— اختر عرضًا —",
    noOffers: "لا توجد عروض نشطة لهذا المنتج. أنشئ عرضًا من صفحة المنتج.",
    noProducts: "لا توجد منتجات بعد. أضف منتجًا وعرضًا أولًا.",
    offersError: "تعذّر تحميل العروض.",
    required: "مطلوب قبل النشر.",
    offerPrice: "سعر العرض",
    offerPriceNone: "يستخدم أسعار المتغيرات",
    abRunning: "توجد تجربة A/B مرتبطة بهذه الخطوة.",
    manageExperiments: "الإدارة من صفحة التجارب",
    edges: "الروابط",
    thankYouEnds: "صفحة الشكر هي نهاية مسار البيع.",
    noEdges: "لا توجد روابط خارجة بعد.",
    toStep: "إلى الخطوة",
    toStepOption: "← {name}",
    removeEdge: "إزالة الرابط",
    condition: "الشرط",
    priority: "الأولوية (الأعلى يُنفَّذ أولًا)",
    problems: "صلّح قبل النشر",
    page: "الصفحة",
    pageEmpty: "صفحة الخطوة دي فاضية.",
    editPage: "تعديل الصفحة",
    addNext: "إضافة الخطوة اللي بعدها",
  },
} satisfies Messages;

/** Client-side pre-check; mirrors backend funnelGraph.validateGraph (server messages win on publish). */
export const VALIDATION_STRINGS = {
  en: {
    noSteps: "A funnel needs at least one step.",
    noEntry: "No entry step — every step has an incoming edge. Remove the edge into your first step.",
    manyEntries: "Exactly one step may have no incoming edge (found {n}: {names}).",
    danglingEdge: "An edge points to a step that no longer exists ({from} → {to}).",
    unreachable: "\"{name}\" can't be reached from the entry step.",
    needsOffer: "\"{name}\" ({type}) needs an offer.",
    emptyPage: "\"{name}\" has an empty page — add at least one section with content.",
  },
  ar: {
    noSteps: "يحتاج مسار البيع إلى خطوة واحدة على الأقل.",
    noEntry: "لا توجد خطوة بداية — كل خطوة لها رابط داخل إليها. احذف الرابط الداخل إلى خطوتك الأولى.",
    manyEntries: "يجب أن تكون خطوة واحدة فقط بلا رابط داخل (يوجد {n}: {names}).",
    danglingEdge: "يوجد رابط يشير إلى خطوة لم تعد موجودة ({from} ← {to}).",
    unreachable: "لا يمكن الوصول إلى «{name}» من خطوة البداية.",
    needsOffer: "«{name}» ({type}) تحتاج إلى عرض.",
    emptyPage: "صفحة «{name}» فاضية — ضيف قسم واحد على الأقل فيه محتوى.",
  },
} satisfies Messages;

/** Starter flows offered when creating a funnel, and on an empty funnel in the editor. */
export const STARTER_TEMPLATE_TEXT: Record<Locale, Record<StarterTemplateId, { name: string; description: string }>> = {
  en: {
    blank: { name: "Blank", description: "Landing → checkout → thank you. Build the rest yourself." },
    "cod-single": { name: "COD single product", description: "One product, cash on delivery, phone-first checkout." },
    "cod-upsell": {
      name: "COD product + one-click upsell",
      description: "Product page → cash on delivery checkout → one extra offer → thank you. Pick the upsell's offer in the editor.",
    },
    "cod-bundle": {
      name: "COD bundle",
      description: "A page that sells a bundle → cash on delivery checkout → thank you. Point the product grid at the bundle's products.",
    },
    "upsell-downsell": { name: "Upsell + downsell", description: "Post-purchase offer with a fallback if declined." },
    "lead-magnet": { name: "Lead magnet", description: "Collect a phone number first, sell on the thank-you page." },
  },
  ar: {
    blank: { name: "فارغ", description: "صفحة الهبوط ← صفحة الدفع ← صفحة الشكر. وأكمل الباقي بنفسك." },
    "cod-single": { name: "منتج واحد بالدفع عند الاستلام", description: "منتج واحد، دفع عند الاستلام، وصفحة دفع تبدأ برقم الهاتف." },
    "cod-upsell": {
      name: "منتج بالدفع عند الاستلام + عرض إضافي بضغطة",
      description: "صفحة المنتج ← الدفع عند الاستلام ← عرض إضافي ← صفحة الشكر. اختار عرض الخطوة الإضافية من المحرر.",
    },
    "cod-bundle": {
      name: "باقة بالدفع عند الاستلام",
      description: "صفحة بتبيع باقة ← الدفع عند الاستلام ← صفحة الشكر. وجّه شبكة المنتجات لمنتجات الباقة.",
    },
    "upsell-downsell": { name: "عرض بعد الشراء + عرض بديل", description: "عرض بعد الشراء مع عرض بديل إذا رفضه العميل." },
    "lead-magnet": { name: "جذب العملاء المحتملين", description: "اجمع رقم الهاتف أولًا، ثم اعرض البيع في صفحة الشكر." },
  },
};

export const STEP_TYPE_LABELS: Record<Locale, Record<UiStepType, string>> = {
  en: {
    landing: "Landing page",
    sales: "Sales page",
    opt_in: "Opt-in",
    checkout: "Checkout",
    upsell: "Upsell",
    downsell: "Downsell",
    thank_you: "Thank you",
    custom: "Custom page",
  },
  ar: {
    landing: "صفحة الهبوط",
    sales: "صفحة البيع",
    opt_in: "صفحة التسجيل",
    checkout: "صفحة الدفع",
    upsell: "عرض بعد الشراء",
    downsell: "عرض بديل",
    thank_you: "صفحة الشكر",
    custom: "صفحة مخصصة",
  },
};

/** Default display name for a freshly added step (becomes editable user data). */
export const STEP_DEFAULT_NAMES: Record<Locale, Record<UiStepType, string>> = {
  en: {
    landing: "Landing page",
    sales: "Sales page",
    opt_in: "Opt-in",
    checkout: "Checkout",
    upsell: "Upsell",
    downsell: "Downsell",
    thank_you: "Thank you",
    custom: "Custom page",
  },
  ar: {
    landing: "صفحة الهبوط",
    sales: "صفحة البيع",
    opt_in: "تسجيل البيانات",
    checkout: "الدفع",
    upsell: "عرض بعد الشراء",
    downsell: "عرض بديل",
    thank_you: "شكراً لطلبك",
    custom: "صفحة مخصصة",
  },
};

export const CONDITION_LABELS: Record<Locale, Record<UiEdgeCondition, string>> = {
  en: {
    always: "Always",
    completed_checkout: "Completed checkout",
    accepted_offer: "Accepted",
    declined_offer: "Declined",
  },
  ar: {
    always: "دائمًا",
    completed_checkout: "أكمل الدفع",
    accepted_offer: "قبِل العرض",
    declined_offer: "رفض العرض",
  },
};

/** Short labels drawn on the flow map's connectors (the full condition is the tooltip). */
export const CONNECTOR_LABELS: Record<Locale, Record<UiEdgeCondition, string>> = {
  en: {
    always: "Next",
    completed_checkout: "Ordered",
    accepted_offer: "Yes",
    declined_offer: "No",
  },
  ar: {
    always: "بعد كده",
    completed_checkout: "طلب",
    accepted_offer: "وافق",
    declined_offer: "رفض",
  },
};

export const STATUS_LABELS: Record<Locale, Record<FunnelStatus, string>> = {
  en: { draft: "Draft", published: "Published", paused: "Paused" },
  ar: { draft: "مسودة", published: "منشور", paused: "متوقف مؤقتًا" },
};
