import type { Locale, Messages } from "@/i18n/LocaleContext";
import type { UiEdgeCondition, UiStepType } from "../funnelAdapter";

/**
 * The words of the funnel editor's two side panes: the steps list and the
 * step inspector (editor/StepsPane.tsx, editor/StepInspector.tsx,
 * GenericPagesPanel.tsx). The English of "Name" and "Fix before publishing"
 * is what FunnelEditorPage.test.tsx looks for.
 */
export const PANE_STRINGS = {
  en: {
    // The steps list.
    steps: "Steps",
    addStep: "Add step",
    addStepTitle: "Add which step?",
    addStepHint: "It is added after the selected step, or at the end of the funnel.",
    collapse: "Hide the steps list",
    reorder: "Move {name} in the list",
    rowMenu: "Actions for {name}",
    openPage: "Open the page",
    rename: "Rename",
    duplicate: "Duplicate",
    remove: "Delete",
    toFix: "{n} to fix",
    noSteps: "No steps yet. Add the first one, or pick a template on the map.",
    reorderNote: "Dragging here only changes the order of this list. The path a shopper walks is the arrows on the map.",
    reorderNoteOk: "Got it",

    // The inspector.
    stepSettings: "Step settings",
    close: "Close step settings",
    problems: "Fix before publishing",
    name: "Name",
    nameEmpty: "Give the step a name so you can tell it apart.",
    key: "Step key",
    copyKey: "Copy the step key",
    type: "Type",
    typeTitle: "Change the step's type",
    typeHint: "The page and the ways out stay as they are.",
    offer: "Offer",
    product: "Product",
    pickProduct: "Pick a product",
    offerLabel: "Offer",
    pickOffer: "Pick an offer",
    noOffers: "This product has no active offer. Add one on the product's page.",
    noProducts: "No products yet. Add a product and an offer first.",
    offersError: "We couldn't load the offers. Check the connection and open the step again.",
    offersLoading: "Loading the offers…",
    required: "Required before publishing.",
    offerMissing: "The offer is gone or switched off. Pick another one.",
    offerPrice: "Offer price",
    offerPriceNone: "Uses the variant prices",
    bump: "Checkout add-on offer",
    bumpHint: "Optional. A tick box on this step's order form — “Add to your order” — that goes into the same order.",
    bumpHintSales: "On a sales page it shows on the page's order form, beside the product's own add-ons.",
    bumpLabel: "Add-on offer",
    after: "After this step",
    afterHint: "Where the shopper goes next.",
    addWay: "Add a way out",
    noWays: "No way out yet. Add one, or this step ends the funnel.",
    thankYouEnds: "The thank-you page ends the funnel.",
    needOtherStep: "Add another step first, then link this one to it.",
    wayWhen: "When",
    wayTo: "Goes to",
    wayToOption: "{name}",
    wayGone: "That step was deleted. Pick another one.",
    pickStep: "Pick a step",
    removeWay: "Remove this way out",
    priority: "Priority",
    priorityHint: "With two ways that both fit, the higher number wins.",
    otherConditions: "Other conditions",
    sameCondition: "Two ways out share a condition. The shopper takes the one with the higher priority.",
    noDecline: "No way out for a shopper who says no. Add one, or they stop here.",
    noAccept: "No way out for a shopper who says yes. Add one, or they stop here.",
    whenButton: "When they press “{label}”",
    page: "Page",
    pageEmpty: "The page is empty. Add something before publishing.",
    pageCount: "{sections} · {elements}",
    section_one: "1 section",
    section_other: "{n} sections",
    element_one: "1 element",
    element_other: "{n} elements",
    testRunning: "A test is running on this step",
    testNamed: "“{name}” is showing two versions of this page.",
    openTests: "Open tests",
    addNext: "Add the next step",
    addNextTitle: "Which step comes next?",
    deleteStep: "Delete step",
    emptyTitle: "Pick a step on the map",
    emptyBody: "Here you name it, choose its offer, open its page and decide where the shopper goes next.",

    // Generic pages.
    pagesTitle: "Other pages",
    pagesHint: "Contact, about, policies — off the map. Link to them from any page.",
    pagesShow: "Show other pages",
    pagesHide: "Hide other pages",
    pagesAdd: "Add page",
    pagesEmpty: "No other pages yet.",
    contact: "Contact us",
    about: "About us",
    policies: "Policies",
    blank: "Blank page",
    contactWhy: "Phone, WhatsApp and a form",
    aboutWhy: "Your story, in your words",
    policiesWhy: "Shipping, returns, privacy",
    blankWhy: "Start from nothing",
    pageMenu: "Actions for {name}",
    copyLink: "Copy the link",
    copied: "Link copied: {path}",
    unsaved: "Save the funnel to give it a link",
    contactBody: "Write how customers can reach you: phone, WhatsApp, email and working hours.",
    aboutBody: "Tell your story: who you are, what you sell and why customers trust you.",
    policiesBody: "Write your shipping, returns and privacy policies here.",
    blankBody: "",
  },
  ar: {
    steps: "الخطوات",
    addStep: "ضيف خطوة",
    addStepTitle: "تضيف أنهي خطوة؟",
    addStepHint: "بتتضاف بعد الخطوة اللي مختارها، أو في آخر الفانل.",
    collapse: "اخفي قايمة الخطوات",
    reorder: "حرّك {name} في القايمة",
    rowMenu: "إجراءات {name}",
    openPage: "افتح الصفحة",
    rename: "غيّر الاسم",
    duplicate: "اعمل نسخة",
    remove: "امسح",
    toFix: "{n} محتاجة تتصلّح",
    noSteps: "مفيش خطوات لسه. ضيف أول خطوة، أو اختار قالب من الخريطة.",
    reorderNote: "السحب هنا بيغيّر ترتيب القايمة بس. طريق الزبون هو الأسهم اللي على الخريطة.",
    reorderNoteOk: "تمام",

    stepSettings: "إعدادات الخطوة",
    close: "اقفل إعدادات الخطوة",
    problems: "صلّح دول قبل النشر",
    name: "الاسم",
    nameEmpty: "اكتب اسم للخطوة عشان تعرفها من غيرها.",
    key: "كود الخطوة",
    copyKey: "انسخ كود الخطوة",
    type: "النوع",
    typeTitle: "غيّر نوع الخطوة",
    typeHint: "الصفحة والطرق اللي خارجة منها بتفضل زي ما هي.",
    offer: "العرض",
    product: "المنتج",
    pickProduct: "اختار منتج",
    offerLabel: "العرض",
    pickOffer: "اختار عرض",
    noOffers: "المنتج ده ملوش عرض شغّال. ضيف عرض من صفحة المنتج.",
    noProducts: "مفيش منتجات لسه. ضيف منتج وعرض الأول.",
    offersError: "معرفناش نحمّل العروض. اتأكد من النت وافتح الخطوة تاني.",
    offersLoading: "بنحمّل العروض…",
    required: "مطلوب قبل النشر.",
    offerMissing: "العرض مش موجود أو متوقف. اختار عرض تاني.",
    offerPrice: "سعر العرض",
    offerPriceNone: "بياخد أسعار الاختيارات",
    bump: "عرض إضافي على فورم الأوردر",
    bumpHint: "اختياري. علامة صح على فورم الخطوة دي — «ضيفه على أوردرك» — وبيتضاف على نفس الأوردر.",
    bumpHintSales: "في صفحة البيع بيظهر على فورم الأوردر اللي في الصفحة، جنب إضافات المنتج نفسه.",
    bumpLabel: "العرض الإضافي",
    after: "بعد الخطوة دي",
    afterHint: "الزبون يروح فين بعد كده.",
    addWay: "ضيف طريق",
    noWays: "مفيش طريق خارج لسه. ضيف طريق، وإلا الفانل هيقف هنا.",
    thankYouEnds: "صفحة الشكر هي آخر الفانل.",
    needOtherStep: "ضيف خطوة تانية الأول وبعدين اربطها بدي.",
    wayWhen: "إمتى",
    wayTo: "يروح على",
    wayToOption: "{name}",
    wayGone: "الخطوة دي اتمسحت. اختار خطوة تانية.",
    pickStep: "اختار خطوة",
    removeWay: "شيل الطريق ده",
    priority: "الأولوية",
    priorityHint: "لو طريقين ينفعوا مع بعض، الرقم الأعلى هو اللي بيتنفّذ.",
    otherConditions: "شروط تانية",
    sameCondition: "فيه طريقين بنفس الشرط. الزبون هياخد اللي أولويته أعلى.",
    noDecline: "مفيش طريق للزبون اللي يرفض. ضيف طريق، وإلا هيقف هنا.",
    noAccept: "مفيش طريق للزبون اللي يوافق. ضيف طريق، وإلا هيقف هنا.",
    whenButton: "لما يدوس على الزرار «{label}»",
    page: "الصفحة",
    pageEmpty: "الصفحة فاضية. ضيف فيها حاجة قبل النشر.",
    pageCount: "{sections} · {elements}",
    section_one: "قسم واحد",
    section_two: "قسمين",
    section_few: "{n} أقسام",
    section_other: "{n} قسم",
    element_one: "عنصر واحد",
    element_two: "عنصرين",
    element_few: "{n} عناصر",
    element_other: "{n} عنصر",
    testRunning: "اختبار شغّال على الخطوة دي",
    testNamed: "«{name}» بيعرض نسختين من الصفحة دي.",
    openTests: "افتح الاختبارات",
    addNext: "ضيف الخطوة اللي بعدها",
    addNextTitle: "أنهي خطوة تيجي بعدها؟",
    deleteStep: "امسح الخطوة",
    emptyTitle: "اختار خطوة من الخريطة",
    emptyBody: "هنا بتسمّيها، تختار عرضها، تفتح صفحتها وتحدد الزبون يروح فين بعدها.",

    pagesTitle: "صفحات تانية",
    pagesHint: "تواصل معانا، عننا، السياسات — برّه الخريطة. اربطها من أي صفحة.",
    pagesShow: "اعرض الصفحات التانية",
    pagesHide: "اخفي الصفحات التانية",
    pagesAdd: "ضيف صفحة",
    pagesEmpty: "مفيش صفحات تانية لسه.",
    contact: "تواصل معانا",
    about: "عننا",
    policies: "السياسات",
    blank: "صفحة فاضية",
    contactWhy: "موبايل وواتساب وفورم",
    aboutWhy: "حكايتك بكلامك",
    policiesWhy: "الشحن والاسترجاع والخصوصية",
    blankWhy: "ابدأ من الصفر",
    pageMenu: "إجراءات {name}",
    copyLink: "انسخ اللينك",
    copied: "اللينك اتنسخ: {path}",
    unsaved: "احفظ الفانل عشان الصفحة تاخد لينك",
    contactBody: "اكتب إزاي العملاء يوصلولك: الموبايل، واتساب، الإيميل ومواعيد الشغل.",
    aboutBody: "احكي حكايتك: إنت مين، بتبيع إيه، وليه العملاء بيثقوا فيك.",
    policiesBody: "اكتب هنا سياسات الشحن والاسترجاع والخصوصية.",
    blankBody: "",
  },
} satisfies Messages;

/** One line saying what each step type is for (the "Add step" menu and the type picker). */
export const STEP_TYPE_PURPOSE: Record<Locale, Record<UiStepType, string>> = {
  en: {
    article: "A story that warms the shopper up before the offer",
    landing: "The first thing a shopper sees",
    sales: "Sells the product and takes the order on the page",
    opt_in: "Takes a name and a number before they go on",
    checkout: "The order form: details, then confirm",
    upsell: "One more thing, offered right after the order",
    downsell: "A smaller offer for a shopper who said no",
    thank_you: "The last page, after the order",
    custom: "A free page you build as you like",
  },
  ar: {
    article: "حكاية تسخّن الزبون قبل ما يشوف العرض",
    landing: "أول حاجة الزبون يشوفها",
    sales: "بتقنعه بالمنتج وبياخد منها الأوردر",
    opt_in: "بتاخد اسمه ورقمه قبل ما يكمّل",
    checkout: "فورم الأوردر: يكتب بياناته ويأكّد",
    upsell: "حاجة زيادة بتتعرض عليه بعد ما يطلب",
    downsell: "عرض أصغر للي رفض العرض اللي قبله",
    thank_you: "آخر صفحة، بعد الأوردر",
    custom: "صفحة حرّة تبنيها زي ما تحب",
  },
};

/** A way out's condition as the sentence it is: "when does the shopper take this path?" */
export const CONDITION_WORDS: Record<Locale, Record<UiEdgeCondition, string>> = {
  en: {
    always: "Always",
    completed_checkout: "After they order",
    accepted_offer: "If they take the offer",
    declined_offer: "If they say no",
    clicked_through: "When they press a button",
  },
  ar: {
    always: "دايمًا",
    completed_checkout: "بعد ما يطلب",
    accepted_offer: "لو وافق على العرض",
    declined_offer: "لو رفض",
    clicked_through: "لما يدوس على زرار",
  },
};

/**
 * The conditions that mean something on each step type, most likely first
 * (what the storefront really sends from that kind of step). The rest stay
 * reachable under "Other conditions": the backend accepts any of them.
 */
export const SENSIBLE_CONDITIONS: Record<UiStepType, UiEdgeCondition[]> = {
  article: ["clicked_through", "always"],
  landing: ["clicked_through", "always"],
  sales: ["completed_checkout", "clicked_through", "always"],
  opt_in: ["clicked_through", "always"],
  checkout: ["completed_checkout", "always"],
  upsell: ["accepted_offer", "declined_offer", "always"],
  downsell: ["accepted_offer", "declined_offer", "always"],
  thank_you: ["always"],
  custom: ["clicked_through", "always"],
};
