import type { Messages } from "@/i18n/LocaleContext";

/**
 * Every word of the "store" tab of the reports hub (../StoreTab.tsx and the
 * files beside this one). The store-search block reads its own words from
 * pages/searchInsights/searchStrings.ts, where they already were.
 *
 * Three counts of "people who came" live on this tab and each keeps ONE name:
 * «الزوار» (web analytics: distinct sessions with a page view), «الزيارات»
 * (web analytics: a session cut into visits of activity) and «دخلوا المتجر»
 * (the sales report's sessions — the first step of the funnel and what the
 * conversion rate is measured over).
 */
export const STORE_STRINGS = {
  en: {
    // ------------------------------------------------------------ KPI strip
    visitors: "Visitors",
    visitorsHint: "Opened at least one page of your store",
    visits: "Visits",
    visitsHint: "Coming back after half an hour counts as a new visit",
    conversion: "Conversion rate",
    conversionHint: "Of everyone who entered the store, the share that ordered",
    conversionOver: "More orders than counted visits — some orders were placed outside the store",
    bounce: "Bounce rate",
    bounceHint: "Visits that saw one page and left",
    duration: "Time per visit",
    durationHint: "How long one visit lasts on average",
    entered: "Entered the store",
    enteredHint: "Every entry to the store, counted once",
    views: "Page views",
    vsYear: "vs the same days last year",
    webFailed: "We couldn't load the visitor figures.",
    durHours: "{h}h {m}m",
    durMinutes: "{m}m {s}s",
    durSeconds: "{s}s",

    // ------------------------------------------------------------ the funnel
    funnelTitle: "How far visitors get",
    funnelNote: "Every entry to the store is counted once, at each step it reached.",
    funnelEmpty: "Nobody entered the store in this period. The steps fill in with the first visitor.",
    funnelSummary: "The purchase path: how many reached each step",
    step_sessions: "Entered the store",
    step_product: "Viewed a product",
    step_cart: "Added to cart",
    step_checkout: "Started the order",
    step_purchase: "Ordered",
    ofPrevious: "of the step before",
    ofAll: "of all",
    left_one: "1 left",
    left_other: "{n} left",
    biggestLeak: "Biggest leak:",
    barTitle: "{step}: {count} — {rate} of everyone who entered",

    // ---------------------------------------------------------- the sentence
    leak_product:
      "Most people leave before they see a product: of every {of} who entered the store, {kept} viewed one{was} — put your products on the first screen.",
    leak_cart:
      "Most people leave at the product page: of every {of} who viewed a product, {kept} added it to the cart{was} — check the photos, the price and the description.",
    leak_checkout:
      "Most people leave at the cart: of every {of} who added to the cart, {kept} started the order{was} — check the shipping fees and make the buy button obvious.",
    leak_purchase:
      "Most people leave while filling in the order: of every {of} who started it, {kept} finished{was} — call the ones who left before they go cold.",
    keptSome: "only {n}",
    keptNone: "none",
    wasPrevious: "(it was {n} of every {of} the period before)",
    wasYear: "(it was {n} of every {of} on the same days last year)",
    healthy: "No step loses most of its visitors: the weakest is “{step}”, and {n} of every {of} carry on from the step before it.",
    thin: "Too early to say where people leave: only {n} entered the store in this period, and it takes at least {min}.",
    thinNone: "Nobody entered the store in this period — once visits come in, this line says where people leave.",
    thinSteps: "The numbers at each step are still too small to say where people leave.",
    act_product: "Edit the storefront",
    act_cart: "Open products",
    act_checkout: "Shipping fees",
    act_purchase: "Lost orders",

    // ------------------------------------------------------------- the table
    viewLabel: "Break the visitors down by",
    view_pages: "Pages",
    view_sources: "Sources",
    view_devices: "Devices",
    view_countries: "Countries",
    title_pages: "Most visited pages",
    title_sources: "Where visitors come from",
    title_devices: "What they browse on",
    title_countries: "Where they are",
    dimLabel: "Detail",
    dim_path: "Page",
    dim_title: "Page title",
    dim_referrer: "Referring site",
    dim_channel: "Channel",
    dim_utm_source: "UTM source",
    dim_utm_campaign: "UTM campaign",
    dim_device: "Device type",
    dim_browser: "Browser",
    dim_os: "Operating system",
    dim_screen: "Screen size",
    dim_language: "Language",
    dim_country: "Country",
    dim_region: "Region",
    dim_city: "City",
    tableNote: "Counted in visitors.",
    tableNoteFilter: "Counted in visitors. Press the first cell of a row to filter by it.",
    tableCapped: "These are the top {n} only.",
    tableEmpty: "No visits in this period.",
    tableEmptyFiltered: "Nothing matches these filters.",
    tableFailed: "We couldn't load this table.",
    colVisitors: "Visitors",
    colShare: "Of all visitors",
    colShareHint: "This row's visitors as a share of every visitor in the period",
    colEntries: "Entered here",
    colEntriesHint: "The first page they opened in a visit",
    colExits: "Left from here",
    colExitsHint: "The last page they saw before leaving",
    colExitRate: "Exit rate",
    colExitRateHint: "Of the page's visitors, the share that left the store from it",
    filterBy: "Filter by {value}",
    direct: "Direct / no source",
    unknownValue: "Unknown",
    channel_direct: "Direct",
    channel_paidAds: "Paid ads",
    channel_referral: "Other sites",
    channel_affiliate: "Affiliates",
    channel_sms: "SMS",
    channel_llm: "AI assistants",
    channel_organicSearch: "Search engines",
    channel_paidSearch: "Search ads",
    channel_organicSocial: "Social media",
    channel_paidSocial: "Social ads",
    channel_email: "Email",
    channel_organicShopping: "Shopping sites",
    channel_paidShopping: "Shopping-site ads",
    channel_organicVideo: "Video",
    channel_paidVideo: "Video ads",
    device_mobile: "Mobile",
    device_laptop: "Laptop",
    device_desktop: "Desktop",
    device_tablet: "Tablet",

    // ----------------------------------------------------------- the filters
    filtersLabel: "Filtered by",
    removeFilter: "Remove the filter {label}: {value}",
    clearFilters: "Clear all",
    filteredFailed: "We couldn't load the totals for these filters.",
    filtersApply: "These numbers follow the table's filters: {filters}.",
    f_url: "Page",
    f_referrer: "Referring site",
    f_title: "Page title",
    f_browser: "Browser",
    f_os: "System",
    f_device: "Device",
    f_country: "Country",
    f_region: "Region",
    f_city: "City",
    f_language: "Language",
    f_screen: "Screen",
    f_event: "Event",
    f_hostname: "Host",
    f_tag: "Tag",
    f_utm_source: "UTM source",
    f_utm_medium: "UTM medium",
    f_utm_campaign: "UTM campaign",
    f_utm_content: "UTM content",
    f_utm_term: "UTM term",

    // ------------------------------------------------------- «تفاصيل أكتر»
    moreFunnel: "The purchase path in numbers",
    moreFunnelSummary: "Every step: how many reached it and how many carried on",
    moreTime: "Visits over time",
    moreTimeSummary: "Visitors, page views and conversion through the period",
    moreWeekly: "Busiest days and hours",
    moreWeeklySummary: "When visitors come during the week",
    moreDevices: "Who buys, by device",
    moreDevicesSummary: "Entries, orders and sales for each kind of device",
    moreChannels: "Who buys, by source",
    moreChannelsSummary: "What each source brought: entries, orders and sales",
    moreLanding: "Landing pages",
    moreLandingSummary: "The first page of a visit, and what those visits went on to buy",
    moreEvents: "Events",
    moreEventsSummary: "What the store recorded visitors doing, and how often",

    colStep: "Step",
    colReached: "Reached it",
    colOfAll: "Of all who entered",
    colOfPrevious: "Of the step before",
    colBeforePrevious: "The period before",
    colBeforeYear: "Same days last year",
    colChange: "Change",
    colDevice: "Device",
    colSource: "Source",
    colEntered: "Entered the store",
    colOrders: "Orders",
    colConversion: "Conversion",
    colSales: "Sales",
    colPage: "Page",
    colEnteredHere: "Entered here",
    colEvent: "Event",
    colTimes: "Times",
    funnelTableNote: "Counted by entry to the store, from the sales report.",
    devicesNote: "Entries to the store by device, and what they ordered.",
    channelsNote: "Entries to the store by where they came from, and what they ordered.",
    landingNote: "The {n} pages most visits began on.",
    eventsNote: "How many times each event happened in the period.",
    noRows: "Nothing in this period yet.",

    metricLabel: "Show",
    metric_traffic: "Visitors",
    metric_entered: "Entered the store",
    metric_conversion: "Conversion",
    unitLabel: "Split the time by",
    unitAuto: "Automatic",
    unitAutoIs: "Automatic ({unit})",
    unit_minute: "Minute",
    unit_hour: "Hour",
    unit_day: "Day",
    unit_month: "Month",
    trafficSummary: "Page views as the light bar with visitors in front of it.",
    trafficSummaryCompared: "Page views as the light bar with visitors in front of it; the comparison period dashed.",
    enteredSummary: "Entries to the store through the period.",
    conversionSummary: "The conversion rate through the period.",
    salesUnfiltered: "This is counted for the whole store — the filters do not change it.",
    thisPeriod: "This period",
    cmpPrevious: "The period before",
    cmpYear: "Same days last year",
    timeEmpty: "No visits in this period.",

    weeklySummary: "Visitors by weekday and hour",
    weeklyHint: "Each square is one hour of one weekday: darker means more visitors.",
    weeklyBusiest: "Busiest: {day} {hour}",
    weeklyEmpty: "No visits in this period.",
    less: "Less",
    more: "More",
    days: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
    visitorsCount_one: "1 visitor",
    visitorsCount_other: "{n} visitors",

    // ---------------------------------------------------------- shared parts
    loading: "Loading…",
    partFailed: "We couldn't load this part.",
    partDenied: "This part isn't part of your role.",
    retry: "Try again",
    up: "Up",
    down: "Down",

    // ----------------------------------------------------------------- links
    linkNow: "Who is in the store right now",
    linkNowHint: "Visitors and orders as they happen",
    linkAds: "Sales sources and campaigns",
    linkAdsHint: "Which source and which campaign bring delivered orders",
    linkWebsite: "Edit the storefront",
    linkWebsiteHint: "The pages your visitors see",
    linkLost: "Lost orders",
    linkLostHint: "Call the ones who started an order and did not finish",
    linkFunnels: "Sales funnels",
    linkFunnelsHint: "Each funnel's own numbers, from its row in the list",
    linkSynonyms: "Search synonyms",
    linkSynonymsHint: "Point a word that finds nothing to a product you sell",
  },
  ar: {
    visitors: "الزوار",
    visitorsHint: "فتحوا صفحة واحدة على الأقل من متجرك",
    visits: "الزيارات",
    visitsHint: "اللي يرجع بعد نص ساعة بيتحسب زيارة جديدة",
    conversion: "معدل التحويل",
    conversionHint: "من كل اللي دخلوا المتجر، كام عملوا أوردر",
    conversionOver: "الأوردرات أكتر من الزيارات المتسجّلة — فيه أوردرات اتعملت من بره المتجر",
    bounce: "معدل الارتداد",
    bounceHint: "زيارات شافت صفحة واحدة ومشيت",
    duration: "مدة الزيارة",
    durationHint: "متوسط وقت الزيارة الواحدة",
    entered: "دخلوا المتجر",
    enteredHint: "كل دخلة للمتجر محسوبة مرة واحدة",
    views: "المشاهدات",
    vsYear: "عن نفس الأيام السنة اللي فاتت",
    webFailed: "معرفناش نحمّل أرقام الزوار.",
    durHours: "{h} س {m} د",
    durMinutes: "{m} د {s} ث",
    durSeconds: "{s} ث",

    funnelTitle: "الزوار بيوصلوا لحد فين",
    funnelNote: "كل دخلة للمتجر بتتحسب مرة واحدة، عند كل خطوة وصلتلها.",
    funnelEmpty: "مفيش حد دخل المتجر في الفترة دي. الخطوات هتتملي مع أول زائر.",
    funnelSummary: "مسار الشراء: كام واحد وصل لكل خطوة",
    step_sessions: "دخلوا المتجر",
    step_product: "شافوا منتج",
    step_cart: "ضافوا للسلة",
    step_checkout: "بدأوا الأوردر",
    step_purchase: "عملوا أوردر",
    ofPrevious: "من اللي قبلها",
    ofAll: "من الكل",
    left_one: "واحد مشي",
    left_two: "اتنين مشيوا",
    left_few: "{n} مشيوا",
    left_other: "{n} مشيوا",
    biggestLeak: "أكبر تسريب:",
    barTitle: "{step}: {count} — {rate} من كل اللي دخلوا",

    leak_product:
      "أكتر ناس بتمشي قبل ما تشوف منتج: من كل {of} دخلوا المتجر، {kept} شافوا منتج{was} — خلّي منتجاتك تبان من أول صفحة.",
    leak_cart:
      "أكتر ناس بتمشي عند صفحة المنتج: من كل {of} شافوا منتج، {kept} ضافوه للسلة{was} — راجع الصور والسعر والوصف.",
    leak_checkout:
      "أكتر ناس بتمشي عند السلة: من كل {of} ضافوا للسلة، {kept} بدأوا الأوردر{was} — راجع مصاريف الشحن وخلّي زرار الشراء واضح.",
    leak_purchase:
      "أكتر ناس بتمشي وهي بتكمّل الأوردر: من كل {of} بدأوا الأوردر، {kept} كمّلوه{was} — كلّم اللي سابوه قبل ما يبردوا.",
    keptSome: "{n} بس",
    keptNone: "ولا واحد",
    wasPrevious: "(كانوا {n} من كل {of} الفترة اللي قبلها)",
    wasYear: "(كانوا {n} من كل {of} في نفس الأيام السنة اللي فاتت)",
    healthy: "مفيش خطوة بتخسّرك كتير: أضعف واحدة «{step}»، وبيوصلها {n} من كل {of} من الخطوة اللي قبلها.",
    thin: "لسه بدري نقول الناس بتمشي منين: {n} بس دخلوا المتجر في الفترة دي، ومحتاجين {min} على الأقل.",
    thinNone: "مفيش حد دخل المتجر في الفترة دي — أول ما الزيارات تيجي هنقولك الناس بتمشي منين.",
    thinSteps: "الأرقام عند كل خطوة لسه قليلة عشان نقول الناس بتمشي منين.",
    act_product: "عدّل واجهة المتجر",
    act_cart: "افتح المنتجات",
    act_checkout: "مصاريف الشحن",
    act_purchase: "الأوردرات المفقودة",

    viewLabel: "قسّم الزوار حسب",
    view_pages: "الصفحات",
    view_sources: "المصادر",
    view_devices: "الأجهزة",
    view_countries: "الدول",
    title_pages: "أكتر الصفحات زيارة",
    title_sources: "الزوار جايين منين",
    title_devices: "بيتصفحوا من إيه",
    title_countries: "بيدخلوا من فين",
    dimLabel: "التفصيل",
    dim_path: "الصفحة",
    dim_title: "عنوان الصفحة",
    dim_referrer: "الموقع اللي جايين منه",
    dim_channel: "القناة",
    dim_utm_source: "UTM source",
    dim_utm_campaign: "UTM campaign",
    dim_device: "نوع الجهاز",
    dim_browser: "المتصفح",
    dim_os: "نظام التشغيل",
    dim_screen: "مقاس الشاشة",
    dim_language: "اللغة",
    dim_country: "الدولة",
    dim_region: "المنطقة",
    dim_city: "المدينة",
    tableNote: "العدّ بالزوار.",
    tableNoteFilter: "العدّ بالزوار. دوس على أول خانة في أي صف عشان تفلتر بيه.",
    tableCapped: "دي أول {n} بس.",
    tableEmpty: "مفيش زيارات في الفترة دي.",
    tableEmptyFiltered: "مفيش حاجة بالفلاتر دي.",
    tableFailed: "معرفناش نحمّل الجدول ده.",
    colVisitors: "الزوار",
    colShare: "من كل الزوار",
    colShareHint: "زوار الصف ده من كل زوار الفترة",
    colEntries: "دخلوا منها",
    colEntriesHint: "أول صفحة فتحوها في الزيارة",
    colExits: "خرجوا منها",
    colExitsHint: "آخر صفحة شافوها قبل ما يمشوا",
    colExitRate: "نسبة الخروج",
    colExitRateHint: "من زوار الصفحة، كام واحد مشي من المتجر عندها",
    filterBy: "فلتر بـ {value}",
    direct: "مباشر / من غير مصدر",
    unknownValue: "غير معروف",
    channel_direct: "مباشر",
    channel_paidAds: "إعلانات مدفوعة",
    channel_referral: "مواقع تانية",
    channel_affiliate: "مسوّقين بالعمولة",
    channel_sms: "رسايل SMS",
    channel_llm: "مساعدين الذكاء الاصطناعي",
    channel_organicSearch: "محركات البحث",
    channel_paidSearch: "إعلانات البحث",
    channel_organicSocial: "السوشيال ميديا",
    channel_paidSocial: "إعلانات السوشيال",
    channel_email: "الإيميل",
    channel_organicShopping: "مواقع التسوّق",
    channel_paidShopping: "إعلانات مواقع التسوّق",
    channel_organicVideo: "الفيديو",
    channel_paidVideo: "إعلانات الفيديو",
    device_mobile: "موبايل",
    device_laptop: "لابتوب",
    device_desktop: "كمبيوتر مكتبي",
    device_tablet: "تابلت",

    filtersLabel: "متفلتر بـ",
    removeFilter: "شيل فلتر {label}: {value}",
    clearFilters: "امسح الكل",
    filteredFailed: "معرفناش نحمّل إجمالي الفلاتر دي.",
    filtersApply: "الأرقام دي ماشية بفلاتر الجدول: {filters}.",
    f_url: "الصفحة",
    f_referrer: "الموقع اللي جايين منه",
    f_title: "عنوان الصفحة",
    f_browser: "المتصفح",
    f_os: "النظام",
    f_device: "الجهاز",
    f_country: "الدولة",
    f_region: "المنطقة",
    f_city: "المدينة",
    f_language: "اللغة",
    f_screen: "الشاشة",
    f_event: "الحدث",
    f_hostname: "النطاق",
    f_tag: "الوسم",
    f_utm_source: "UTM source",
    f_utm_medium: "UTM medium",
    f_utm_campaign: "UTM campaign",
    f_utm_content: "UTM content",
    f_utm_term: "UTM term",

    moreFunnel: "مسار الشراء بالأرقام",
    moreFunnelSummary: "كل خطوة: كام وصلوا وكام كمّلوا",
    moreTime: "الزيارات على مدار الوقت",
    moreTimeSummary: "الزوار والمشاهدات والتحويل على طول الفترة",
    moreWeekly: "أيام وساعات الزحمة",
    moreWeeklySummary: "الزوار بييجوا إمتى في الأسبوع",
    moreDevices: "مين بيشتري: حسب الجهاز",
    moreDevicesSummary: "الدخول والأوردرات والمبيعات لكل نوع جهاز",
    moreChannels: "مين بيشتري: حسب المصدر",
    moreChannelsSummary: "كل مصدر جاب كام دخلة وكام أوردر ومبيعات",
    moreLanding: "صفحات الهبوط",
    moreLandingSummary: "أول صفحة في الزيارة، واللي دخلوا منها اشتروا إيه",
    moreEvents: "الأحداث",
    moreEventsSummary: "اللي المتجر سجّل إن الزوار عملوه، وكام مرة",

    colStep: "الخطوة",
    colReached: "وصلوا",
    colOfAll: "من كل اللي دخلوا",
    colOfPrevious: "من الخطوة اللي قبلها",
    colBeforePrevious: "الفترة اللي قبلها",
    colBeforeYear: "نفس الأيام السنة اللي فاتت",
    colChange: "التغيير",
    colDevice: "الجهاز",
    colSource: "المصدر",
    colEntered: "دخلوا المتجر",
    colOrders: "الأوردرات",
    colConversion: "التحويل",
    colSales: "المبيعات",
    colPage: "الصفحة",
    colEnteredHere: "دخلوا منها",
    colEvent: "الحدث",
    colTimes: "عدد المرات",
    funnelTableNote: "العدّ بالدخلة للمتجر، من تقرير المبيعات.",
    devicesNote: "اللي دخلوا المتجر من كل نوع جهاز، وعملوا أوردرات بكام.",
    channelsNote: "اللي دخلوا المتجر من كل مصدر، وعملوا أوردرات بكام.",
    landingNote: "أكتر {n} صفحة الزيارات بدأت منها.",
    eventsNote: "كل حدث حصل كام مرة في الفترة.",
    noRows: "مفيش حاجة في الفترة دي لسه.",

    metricLabel: "اعرض",
    metric_traffic: "الزوار",
    metric_entered: "دخلوا المتجر",
    metric_conversion: "التحويل",
    unitLabel: "قسّم الوقت بـ",
    unitAuto: "تلقائي",
    unitAutoIs: "تلقائي ({unit})",
    unit_minute: "دقيقة",
    unit_hour: "ساعة",
    unit_day: "يوم",
    unit_month: "شهر",
    trafficSummary: "المشاهدات في العمود الفاتح والزوار قدّامه.",
    trafficSummaryCompared: "المشاهدات في العمود الفاتح والزوار قدّامه، وفترة المقارنة بخط متقطع.",
    enteredSummary: "اللي دخلوا المتجر على طول الفترة.",
    conversionSummary: "معدل التحويل على طول الفترة.",
    salesUnfiltered: "الرقم ده محسوب للمتجر كله — الفلاتر مش بتغيّره.",
    thisPeriod: "الفترة دي",
    cmpPrevious: "الفترة اللي قبلها",
    cmpYear: "نفس الأيام السنة اللي فاتت",
    timeEmpty: "مفيش زيارات في الفترة دي.",

    weeklySummary: "الزوار حسب اليوم والساعة",
    weeklyHint: "كل مربع ساعة من يوم: الأغمق زوار أكتر.",
    weeklyBusiest: "أزحم وقت: {day} {hour}",
    weeklyEmpty: "مفيش زيارات في الفترة دي.",
    less: "أقل",
    more: "أكتر",
    days: "الأحد,الإثنين,الثلاثاء,الأربعاء,الخميس,الجمعة,السبت",
    visitorsCount_one: "زائر واحد",
    visitorsCount_two: "زائرين",
    visitorsCount_few: "{n} زوار",
    visitorsCount_other: "{n} زائر",

    loading: "بنحمّل…",
    partFailed: "معرفناش نحمّل الجزء ده.",
    partDenied: "الجزء ده مش ضمن صلاحياتك.",
    retry: "جرّب تاني",
    up: "زاد",
    down: "قلّ",

    linkNow: "مين في المتجر دلوقتي",
    linkNowHint: "الزوار والأوردرات لحظة بلحظة",
    linkAds: "مصادر المبيعات والحملات",
    linkAdsHint: "أنهي مصدر وأنهي حملة بيجيبوا أوردرات بتتسلّم",
    linkWebsite: "عدّل واجهة المتجر",
    linkWebsiteHint: "الصفحات اللي الزوار بيشوفوها",
    linkLost: "الأوردرات المفقودة",
    linkLostHint: "كلّم اللي بدأوا أوردر وما كمّلوش",
    linkFunnels: "مسارات البيع",
    linkFunnelsHint: "أرقام كل مسار بيع، من صفّه في القايمة",
    linkSynonyms: "مرادفات البحث",
    linkSynonymsHint: "خلّي الكلمة اللي مابتلاقيش حاجة تودّي لمنتج عندك",
  },
} satisfies Messages;
